### ISSUE TITLE
You can shoot, but not be hit by, turrets if standing in doorways

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#10080]
If you're standing in the doorway of the AI core, you can shoot, but not get hit by, the turrets.
This is bad for obvious reasons.

**Comment by Jalleo** [comment]
Its how the targeting system works

**Comment by Dorsisdwarf** [comment]
Targeting system draws LOS, IIRC, rather than the old area-based methods. Might be relevant

**Comment by Supermichael777** [comment]
actual from what i have seen on both sides of this the turrets shoot but the wall blocks them while a human can shoot from the door. something to do with firing from the corners of your sprite(and your projectile moving diagonally around the corner) if not on an absolute grid-line, but aiming for the center of tiles, tl;dr the way guns shoot and aim is silly and favors taking cover behind corners. Realy gimps the AI turrets, but their current setup is to prevent them from firing out of the room.

**Comment by Miauw62** [comment]
this is actually *realistic*.
at least, if you're holding your gun in the apropriate hand.
its still shit tho

**Comment by Razharas** [comment]
Its problem of projectile moving pattern
First it tries to get rid of lesser coordinate difference, then travel straight by the second coordinate until reaching the target's turf, and only then will it start moving as believable trajectory
It means that since the turrets in AI core are more different by x than by y from the entrance, shooting from higher y will make the projectile get rid of y difference first, thus traveling by both y and x at the same rate until y difference reches 0, then straight into the turret by x, this trajectory meets no obstacles
But if you try to shoot as turret to the player at the entrance,  it will also try to get rid of y difference, traveling diagonally until y diff is 0 and them by x into the player
Unfortunately this path meets wall at the end of the even diagonal movement, not even reaching the straight movement part and thus unable to reach the player

**Comment by Actionb** [comment]
This isn't an issue with the AI upload and the AI sat foyer though. Move the core turrets one tile further towards the centre? Yes, that would let the turrets shoot through the airlock into the foyer, but AI defenses are a joke already. 
On a sidenote: corner sniping the turrets has been a thing since forever. Even before the introduction of the satellite.

**Comment by Bawhoppen** [comment]
this should no longer be relevant considering pixel projectiles is now merged,
