### ISSUE TITLE
Client crash on radio/headset VV

### ISSUE THREAD

**Issue by Cheridan** [tgstation/tgstation#10881]
Attempting to use VV on a radio/headset will reliably crash your DS client.

It it only crashes on the obj/item/radio/headset type. Parent types do not cause the crash, neither do child types.
The only conditions known (so far) to prevent the crash, is if the headset is on a wooden floor tile, or has been previously picked up by a human.

What the hell

**Comment by Cheridan** [comment]
[21:03]	MrStonedOne	so i made something that opens the vv window repetitively, once for each var
[21:03]	MrStonedOne	so that you can see it as it builds the var list
[21:03]	MrStonedOne	no crash until the last var, z, meaning it only crashes with the complete list

**Comment by Summoners** [comment]
I have no idea why it does it, it's a mystery

**Comment by Jordie0608** [comment]
Seems to happen with teleport beacons as well.

**Comment by Thunder12345** [comment]
I can make this happen reliably with /obj/item/weapon/nullrod/sord over multiple rounds and servers

**Comment by phil235** [comment]
So apparently it has to do with attack_verb. The nullrod subtypes that always crash share the same 8-element-long attack_verb list, except for nullrod/tribal_knife which doesn't seem to crash. And from testing it doesn't seem to be because it's the last subtypes to be define or the last one alphabetically, since adding another subtypes after the tribal knife and alphabetically after it ends up making an item that doesn't crash, just like the tribal knife.

Even stranger, changing all those 8 element list to only have 6 elements seems to reverse the roles: the tribal knife and the new added one crashes, but all the others are fine.
