### ISSUE TITLE
Ninja phase jaunt cannot jump into walls, but will still drain energy.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#11152]
What it says on the tin. It shouldn't drain it at all if it doesn't let you jump into walls.

**Comment by Supermichael777** [comment]
why can nijas do this again?
are thye a beter admin wizard?

**Comment by WJohn** [comment]
It's significantly less powerful control. While it's instantaneous and can be used while you're knocked down, you can't cover nearly as much distance and is easily limited by its power cost. Besides, ninjas need SOME method of escape.

**Comment by Supermichael777** [comment]
still kind of shity anyway. now that we have invisibility cant nijas just have a time limited version of that? think adrenals plus temporary invis(10 seconds should be plenty) that dosent alow interactions but makes you pass through people.maybe add a holographic ninja body for cool disapering acts.

on to the issue i think it was due to the fact that it made being a ninja too easy when you could vanish and appear through three airgapped rwalls.

**Comment by Dorsisdwarf** [comment]
Supermichael777, this is a question about a bug with a feature, not a feedback thread for how overpowered ninjas are.

**Comment by Repukan** [comment]
@ChangelingRain Was this fixed?

**Comment by Repukan** [comment]
@ChangelingRain Teleportation got moved to the katana so this can be closed

**Comment by Repukan** [comment]
@KorPhaeron
