### ISSUE TITLE
Flashlight light source wont go away after putting it in a backpack

### ISSUE THREAD

**Issue by Aloraydrel** [tgstation/tgstation#11172]
Take out flashlight in a dark area and turn it on

Put it in your backpack and watch how the light source stays there even when moving

**Comment by WJohn** [comment]
Wait, it doesn't move with you? The light source is just stuck in the same spot even when you leave?

**Comment by Aloraydrel** [comment]
Yup pretty much until you take it back out

**Comment by WJohn** [comment]
Are you able to stack this on the same tile? What happens then?

**Comment by Mervill** [comment]
This is still an issue
1. Find a totally dark room (ie: remove the two lights from atmos on runtimestation)
2. Turn on a light that can be placed in a backpack, then place it in your backpack
3. Move in any direction, notice how the light source is fixed to where you were standing when you put the light into the backpack

- You can do step 2 before step 1 for the same outcome

- If opening a door causes the tile the bug was preformed on to have it's lighting updated, the bug disappears
  - The bug does not disappear if the tile's lighting is updated when installing a lightbulb in a light fixture
- You can replicate this bug as many times as you have flashlights (so if you have 3 flashlights you can bug 3 light sources)
  - They can be all on the same tile, or all on different tiles
