### ISSUE TITLE
Lawsync is broken

### ISSUE THREAD

**Issue by Jalleo** [tgstation/tgstation#11511]
You can update a cyborg via cyborg upload if their lawsync is set to 0.
Happened to Firecage who was a sydicate MMI borg.

**Comment by MrStonedOne** [comment]
PM: MrStonedOne/(MrStonedOne)->Jalleo/(Jeremy Sealis): lawsync should be stopping auto law downloads from their connected ai. this means they are connected to an ai, but don't get their laws from that ai.
PM: Jalleo/(Jeremy Sealis)->MrStonedOne/(MrStonedOne): Yeah well changing the laws directly to syndicate cyborgs are possible at least with syndicate MMIs
PM: MrStonedOne/(MrStonedOne)->Jalleo/(Jeremy Sealis): in fact, its only if law sync is 1 that you shouldn't be able to use a cyborg law upload
PM: Jalleo/(Jeremy Sealis)->MrStonedOne/(MrStonedOne): right ya sure on that?
PM: MrStonedOne/(MrStonedOne)->Jalleo/(Jeremy Sealis): yes, you can't upload laws to a borg who gets their laws from their ai (lawsync=1)
PM: Jalleo/(Jeremy Sealis)->MrStonedOne/(MrStonedOne): right so what about a syndicate MMI since there is also something called aisync as well as lawsync
PM: MrStonedOne/(MrStonedOne)->Jalleo/(Jeremy Sealis): Hmm, something to look at thats for sure.

**Comment by Jalleo** [comment]
Perhaps the syndicate MMI should be setting law sync to =1 to prevent people changing it at cyborg upload.
