### ISSUE TITLE
Spiderlings refusing to grow.

### ISSUE THREAD

**Issue by Aliannera** [tgstation/tgstation#11620]
A bunch of spiderlings stacked on one another in a dorm room, spawned by a player ling, refused to grow up into adult spiderhood even after a very extended period of time, somewhere around thirty minutes or so. I thought it might have been due to so many being on top of one another, but testing in the Thunderdome showed this was not the case as even in massive stacks of spiderlings, even those spawned from a player ling, still grew up to be their adult self. Was unable to find the source as to why they didn't grow.

**Comment by Zilenan91** [comment]
Perhaps it was because the ling in question was standing on top of the vent near the middle-ish of the room, and due to how spider AI works, they are coded to run away from anything bigger than them. My guess is they were trying to path somewhere outside the dorm to get away, not realising they could go down the vent due to a player being on top of it, and getting stuck like this.
