### ISSUE TITLE
hand held crew monitor can show the wrong map

### ISSUE THREAD

**Issue by Supermichael777** [tgstation/tgstation#11655]
may have been because i logged in to server two to check for polls

**Comment by WJohn** [comment]
Wait so having both games open and refreshing a crew monitoring console from one can show you metastation?

**Comment by Supermichael777** [comment]
thats the only explination i can come up with
showed me data from box just with the meta map

**Comment by Core0verload** [comment]
BYOND issue. It can be fixed on server side by using dififrent map names for any map.

**Comment by neersighted** [comment]
Unresolvable -- connecting to multiple servers can cause cache collisions. While we could prefix minimap files with the map name, this is just a band-aid. The real issue is BYOND's cache being shared between instances, which can even cause collisions with different codebases (such as Goon).

**Comment by nullquery** [comment]
This shouldn't occur. If you use `browse_rsc` to send a resource then the client should overwrite it if it already exists and differs from the provided file. If this is not happening then a bug report may need to be filed with BYOND for this.

**Comment by neersighted** [comment]
@nullquery this is happening when you connect to server a, connect to server b, and then look at the map on server a (you see server b).

**Comment by nullquery** [comment]
Shouldn't happen. When you connect to a server, the map is immediately sent using `browse_rsc`, this should overwrite any existing file.

But iirc this was removed due to interface lag? In that case the fix is to put the md5 hash for that map into the filename. A collision should be unlikely and if it does occur reopening the window should fix it.

**Comment by neersighted** [comment]
@nullquery Ah, this is a side effect of our asset_cache, which only sends files once and avoids sending files again if requested a second time (hence the cache part). @MrStonedOne ported it from VG, maybe he'd like to weigh in.

**Comment by nullquery** [comment]
Have you tried using client-side savefiles to store hashes of the files? You can then get the savefile and perform a comparison on the server side.

**Comment by MrStonedOne** [comment]
so ya, i figured this bug out.

open sybil, wait 30 seconds
open basil (leaving sybil open as well), wait 30 seconds
go to sybil and use a crew monitor, it will have basil's map.

when you connect to sybil, it sends all registered resources slowly over 30 or seconds(it scales to clients round trip time) to avoid clogging up the file send queue (since browse() uses this same queue) 

So after 30 seconds of connecting to sybil, minimap.png (or what ever it's called) is placed in your cache folder,

Then you connect to basil, and basil overrides it.

Then you load up a crew monitor and it has basil's overridden map.

This is a byond bug, it's actually an exploit, and i'm reporting it as a security issue

**Comment by MrStonedOne** [comment]
@optimumtact this can be closed, it was fixed when the crew monitor was made tgui, since it uses the map name in the file name.
