### ISSUE TITLE
Energy weapons can't burst fire

### ISSUE THREAD

**Issue by Thunder12345** [tgstation/tgstation#11661]
If any energy weapon is set to burst size >1, when fired the first shot works normally, and it clicks on the second and stops trying to fire. Guessing this is to do with how they handle casings.

**Comment by Supermichael777** [comment]
Because they have only one bullet and fire it multiple times as far as i can tell. Yes this is stupid.

**Comment by Jalleo** [comment]
This is caused by a non interactive conflict between the for loop
https://github.com/tgstation/-tg-station/blob/304d91fa2cddb1cf424cf4040a778bd96f955097/code/modules/projectiles/gun.dm#L192
and 
https://github.com/tgstation/-tg-station/blob/304d91fa2cddb1cf424cf4040a778bd96f955097/code/modules/projectiles/guns/energy.dm#L40

**Comment by lzimann** [comment]
This got fixed somewhere.
