### ISSUE TITLE
Server will not attempt to reconnect to the database upon disconnection.

### ISSUE THREAD

**Issue by kyrahabattoir** [tgstation/tgstation#11948]
If you restart your mysql database server while the game server is running, it will not attempt to reconnect:
- The library service will be down.
- Reloading the admin list will cause currently logged admins to be demoted.

**Comment by MrStonedOne** [comment]
Its due in part to a byond bug that prevents us from knowing that the connection is down.

There is a verb to help with that thou, reestablish database connection.

Requires +debug to force a reconnect when byond says its already connect.

**Comment by kyrahabattoir** [comment]
Crap, so there is no way to make the server reconnect on it's own?

**Comment by MrStonedOne** [comment]
There is, but its hard, and not portable.

Byond doesn't give an interface for mysql error numbers, so you have to parse it from the next. Byond also improperly handles the connected property so that it isn't changed to disconnected when the connection dies.

So you would have to add a handler to every query to parse the error message (if any) and figure out if the error number is 2006, and hope that the output of the error message doesn't change, fucking up your parser.

**Comment by kyrahabattoir** [comment]
I was thinking about a simple query that would, for instance return a reply we already know.

SELECT * FROM `dbcheck` WHERE 1

(assuming dbcheck is a table with a single entry in it just for the purpose of doing this check)

If It returns 1 row, we know the db is connected.

If it returns anything else we can then conclude that we need to reconnect? Good? Bad?

**Comment by Jordie0608** [comment]
Simply `SELECT 1` would suffice.

**Comment by kriskog** [comment]
#44144 solves the main issue here.
