### ISSUE TITLE
Blob camera eye should stay on shuttles when they depart 

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#12158]
goddamnit I was 5 OFF of getting a node before it departed FUCK me

**Comment by GunHog** [comment]
Was your core on the shuttle? It would not make sense to control your blob parts through hyperspace.

**Comment by Bawhoppen** [comment]
Thats what I was complaining about, it should let you control if you have ANY blob on the shuttle

**Comment by MMMiracles** [comment]
Its possible to still plant nodes and other shit if your camera is on the other side of a string of blob if you get completely separated from your core, so it makes sense that it should work on a shuttle too.

**Comment by MrStonedOne** [comment]
I have a half finished branch that fixes this issue.

The reason this happens is because blob override is of type mob/camera, and that can't move when shuttles move for AI reasons.

I'll look at re-opening the branch up, It's goal is to move a atom shuttle move proc so that atoms can handle shuttle moves on their own. I had already made blob overmind allow the move if there is a nearby blob tile on the shuttle

**Comment by Bawhoppen** [comment]
why is this closed its still relevant

**Comment by KorPhaeron** [comment]
It was labelled a feature request and NOTABUG
