### ISSUE TITLE
Over 300 paths fail to garbage collect

### ISSUE THREAD

**Issue by duncathan** [tgstation/tgstation#12213]
https://tgstation13.org/parsed-logs/sybil/runtimes/runtime-2015-10-07-condensed.txt

In the past 12 hours, the new public del() logs report 348 unique failures. In reality, some of these are false positives caused by a byond bug, but there are still a ton of genuine failures here. 
As we know, having to hard delete something is very expensive, so solving these failures may noticeably reduce lag, particularly singulo lag. 

REMINDER: To garbage collect properly, an object's `Destroy()` proc must clear all references held to it. These references are quite often set up in the object's `New()` proc, as well as other procs called by `New()`. When attending to solve a failure, first ensure that all references set up in those procs get cleared in `Destroy()`.
If, after that, the failure persists, there is a method to find all references held to an object after its `Destroy()` proc has been called. To use this method, you must first go to _compile_options.dm and uncomment the line `//#define TESTING`. After that, go to the problem object's `Destroy()` proc. In most cases, this proc will return `..()`. If it is an explicit return (`return ..()`), comment that line and add the following:

```
..()
return QDEL_HINT_FINDREFERENCE
```

If it is an implied return (`. = ..()`) simply add `return QDEL_HINT_FINDREFERENCE`. 
Once you've done that, recompile and destroy the object in any way you can think of (bombs, singulo, deconstruction, etc). The game will automatically find all references left to the object (this takes a long time, don't worry) and report them to you. Then you must simply find the problem references and ensure they're cleared in `Destroy()`.
Make sure to recomment the compile option and restore the original return value of `Destroy()`.

Happy hunting!

**Comment by securitycopper** [comment]
@duncathan As an admin, when I "Right Click" on an object and click "Delete". Will that call the Destory() method?  It seems simpler then attempting to destroy the object by other means.

**Comment by duncathan** [comment]
@securitycopper yes, that will qdel the object (which calls Destroy()) but unfortunately due to a byond issue if you use that verb the object will always fail to GC

**Comment by securitycopper** [comment]
@duncathan I uncommitted #define TESTING, but when i add QDEL_HINT_FINDREFERENCES to a Destory method, I get the following warning when I compile. Is this normal?
warning: QDEL_HINT_FINDREFERENCES: unused label

Do basic types like integers need to be set to null?

**Comment by securitycopper** [comment]
@duncathan Regarding the bug beyond has around Delete, is it possible for us to add a admin sub menu entry on the same list as Delete that will spawn a special object that will destroy the target object? For example, same way an explosion would destroy objects if the explosion only was on one tile. The main difference here is that it would only remove targeted item. I've been looking around for the right click code but haven't found it yet. I don't mind exploring this option if you can point me in the right direction.

**Comment by MartiUK** [comment]
I'm not too familiar with BYOND, a lot of the objects that fail to GC don't have a Destroy() proc. Does an object need one for the GC to work?

**Comment by securitycopper** [comment]
@duncathan I've been reviewing the GC code for the past several hours and have come to the conclusion that qDel isn't fully implemented across different root types. For this reason Destory() isn't a defined proc on obj, only datum .

I found one point in the code where some of the gc code doesn't do anything.

I'm going to update the garbage collection logic and will do a pull request when done.
I've added a new right click option for special builds to allow you to generate a fully destructive explosion on the tile where you click the object.This allows us to do better Delete testing using actual explosion logic to delete the object how it would be removed during game play.

I was working on footprints and discovered that Destory doesn't exist on obj.  
The following path has failed to GC 57 time(s).
Path : /obj/effect/decal/cleanable/blood/footprints 

The warning  was due to the fact that the Label i was using, its value was never used, so that was why it gave me the warning.

**Comment by securitycopper** [comment]
@duncathan 

Two corrections:
Looks like the code is looking for QDEL_HINT_FINDREFERENCE not QDEL_HINT_FINDREFERENCES

Due to a typo, my conclusion wasn't correct. /obj do have a Destroy because the datum defines the proc.

I'm still going to improve the GC logic. For example, I'm going to let the GC qDel proc null out all references on the datum before it is added to the queue. This will improve the changes that all references are cleared by the time the object is pulled off the queue for hard del().

In theory, after the change, the only time datums need to implement their own Destroy is when they want to notify referenced objects that they are being cleaned up.

Is setting a list var = null good enough to clean it up, or should we clear the list before nulling it? 

I like the idea of rule based cleanup of known data types. This way we can fix many of the gc issues without having to write custom Destroy procs for each object having an issue.

**Comment by duncathan** [comment]
@securitycopper thanks for pointing out the typo; I'll fix that in the OP. As for everything else you're doing.... There's a bunch of reasons why not to. I'm too tired to explain it all right now, but ping me on #coderbus (I'm Dunc and Dunc|Mobile) and we'll talk

**Comment by securitycopper** [comment]
With the find references logic, what does the following do? 

	testing("Beginning search for references to a [type].")
	var/list/things = list()
	for(var/client/thing)
		things |= thing
	for(var/datum/thing)
		things |= thing

**Comment by Jalleo** [comment]
@duncathan can this be closed?

**Comment by duncathan** [comment]
I mean it hasn't been fixed; yesterday approx 308 paths failed to GC gracefully

**Comment by Cyberboss** [comment]
This is a hard issue to fix because, for the lower GC failure counts, the path itself usually isn't at fault. Some other orthogonal datum probably grabbed a reference to it for whatever reason and didn't release it.

**Comment by nightred** [comment]
This issue has not been touched in years,
The scope is also makes it so if a single item fail's GC this is still valid.
Please open reports of failed GC items for further review.
