### ISSUE TITLE
Roundstart cells from borgs and APCs have incorrect cell rating descriptions

### ISSUE THREAD

**Issue by freerealestate** [tgstation/tgstation#12327]
If you pull a roundstart cell out of an APC or a borg, the description says it has a charge rating of 1000. But APCs start with cells with a maxcharge of 2500, and borgs start with 7500.

**Comment by Supermichael777** [comment]
I THINK its because  var/cell_type just var-edits a default cell to match the value. as all default apcs have this it meas that you get a battery with an incorrect description. var/cell_type gets changed whenever a battery is inserted or removed so it doesn't cause other issues.
Fun fact any outdated apcs would have a battery with only 1 or 2 capacity..
i suspect round-start Borg does the same thing.

**Comment by Supermichael777** [comment]
apc code is a type-checking bitch. WHAT IS OBJECT ORENTATION

**Comment by msgerbs** [comment]
I think #30327 fixes this, can this be closed?

**Comment by PKPenguin321** [comment]
Closeable?
