### ISSUE TITLE
Timestop doesn't stop thrown items in the field

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#12693]
So you can throw into, out of, and past the timestop field without the items ever stopping.

**Comment by Supermichael777** [comment]
flashbangs

**Comment by Incoming5643** [comment]
I believe this is because throwing only ever checks to see if an item COULD get through a throwing path, the item itself never actually occupies those spaces, it just teleports to the destination/point of impact. If there's no gravity the item will then swap to a throw that actually moves the item along the path. This means timestop would work on thrown items provided the throw ended somewhere before the end of the timestop AND there was no gravity.

**Comment by Zilenan91** [comment]
This should stay tbh. Time Stop cancer wizard is bad enough as-is.
