### ISSUE TITLE
Floor tile system limits ability to add new colors and patterns

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#12867]
As-is, if you want to add a new floor tile color with all the directions and such, you need 13 sprites, four for each half-colored tile, four for the three-quarter colored tiles, four for the corner colored tiles, and one for the full-colored tile. And if you want the color to have a checkerboard pattern, that's two more sprites.
And that's just for one base tile color, so if you want that tile color on white or black tiles, you've got to make that many more sprites just to add one color.

This significantly limits the ability to add more colors and patterns, as well as bloating the floor.dmi excessively due to how many sprites it adds to make a single additional color.

**Comment by WJohn** [comment]
I mean I guess we could change it so that colors are just overlays, like warning lines are. I wonder how that'd be handled in game with repairing damaged floor tiles, and how feasible it'd make finally painting them ourselves.

**Comment by Dorsisdwarf** [comment]
You don't *technically* need to give it half and quarter options with all the other floor tiles, but I agree that this could use a refactor. Maybe an Auto-Floor-Painter for the janitor

**Comment by Anonus** [comment]
There was some decal system for floor tiles that would apply the colors/warning lines to the tile and save that as a generated sprite somehow, but I forget which codebase had it. it reduced you to needing four sprites per additional color.
Also, the problem is less ingame and more "if you want a different pattern or tile color, you've got to add shitloads of sprites"

Also for reference, those warning line overlays break if you crowbar them and replace them, which makes them less usable.

**Comment by ChangelingRain** [comment]
Fun fact I checked and floors.dmi has a minimum of 814 sprites in it, counting directions and animations
