### ISSUE TITLE
Some people seem to just be plain faster than others

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#13376]
I swear sometimes two people running in a straight line, roundstart, with no encumbering gear, will have one person easily catching up to another slowly but surely.

I've heard rumour it has something to do with client connection but I have no idea what causes the issue, and its hard to prove it even exists.

**Comment by Steelpoint** [comment]
I've heard rumours that it has to do with your ping to the server.

But that's just rumours, I have noticed something to this effect some times in the game but its hard to distinguish outside of controlled scenarios.

**Comment by Anonus** [comment]
It happens and I'd bet it's basically just connection and how byond handles it.
Faster connection, more movement key inputs, higher likelyhood of inputting a movement key input right after you have the ability to move again.

**Comment by Incoming5643** [comment]
pretty much, "moving constantly" in byond doesn't really exist, it's just reading inputs, if you connection is less steady or has higher latency, the time between inputs can cause a slow loss of "speed" over a straight away.

It's probably not impossible to implement some sort of "dead reckoning" system for movement to help with this, but then that could probably lead to people accidentally lagging out an airlock because their router decided to burp at a critical moment.

**Comment by WJohn** [comment]
I figured this was the case, I don't know if anything can be done.

**Comment by MrStonedOne** [comment]
Ya, something can be done, if the time until next allowed movement is less than 3/4 of the movement delay, we can just queue up a move for them rather than wait until the next tick that they send a move command.

But this would require abusing spawns, sleeps, and the like, and would in some cases make the time until you start moving after releasing the key even longer, especially in laggy connections.

There is one other trick i can look at, and that's replacing the default north/south/west/east with instant verbs. A special kind of verb that allows multiple calls per-tick. The issue would still exist, but be much less of an issue.

**Comment by YotaXP** [comment]
I've noticed this as well.  In fact, I started off one round moving very slowly unencumbered, and at some point later in the round, I started speeding around faster than everyone else.  I have no idea what happened.

**Comment by MrStonedOne** [comment]
figured out a fix.
````
	var/delay = mob.movement_delay()
	if (move_delay+delay < world.time)
		move_delay = delay + world.time
	else
		move_delay += delay
````

basically if your movement only came in a little late, it subtracts that from your movedelay

**Comment by neersighted** [comment]
:+1:, please implement this @MrStonedOne

**Comment by okaw** [comment]
imagine it going horribly wrong

**Comment by optimumtact** [comment]
Clearly he never intended to fix this
