### ISSUE TITLE
Syndicate shuttle deletes the outer airlock door at the nukeops base

### ISSUE THREAD

**Issue by tigercat2000** [tgstation/tgstation#13738]
Problem Description: The syndicate shuttle, and possibly other shuttles, delete any non-turfs within their bounding box at their new location, regardless of the object's area. Specific example is that the nukeops shuttle deletes the outer airlock, which is in the syndicate mothership area..

Before (Screenshot of map in DM):
![Before](https://puu.sh/lZ8NS/66acb1ae4c.png)
After:
![After](https://puu.sh/lZ8Wl/b4ae8a82b1.png)

What did you expect to happen: Objects that are part of the stationary dock's area type would not be deleted when the shuttle arrives.

What happened instead: Any objects within the square bounding box of the shuttle are deleted.

Why is this bad/What are the consequences: It isn't too bad, as I believe the nukeops shuttle is the only shuttle that has such an odd bounding box, however, it does cause small issues like the door being missing.

Steps to reproduce the problem: 
- Observe that there is a door within the syndicate shuttle bounding box on the map.
- Boot server, jump to the syndicate shuttle.
- Observe that the door is missing.

Server: N/E, Local server testing another project when I noticed it.

Revision: 6c998f9eeaa736ce23112ed0acc33c95b6dcd0be 

Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?): I am relatively sure that the objects are deleted by the `roadkill()` proc.

**Comment by Incoming5643** [comment]
Honestly, in this situation, we really don't need the blast door to begin with, once the shuttle docks (on loading) any future undock will leave breathable snow tiles behind, so the corridor doesn't need to be pressurized.

**Comment by KorPhaeron** [comment]
I'll fix this after my nuke PR is merged (or before if it sits long enough)

**Comment by MrStonedOne** [comment]
logically, this shouldn't be happening, shuttles who's mobile docking port are in an area of type /area/shuttle/* will do area based movement rather than bounding rectangle based movement, and the areas match up on box's z1 and generics z2. so this is a mapping error with one of the maps, or a bug in shuttle code.

**Comment by MrStonedOne** [comment]
update, it has to be a bug in shuttle code.

**Comment by WJohn** [comment]
Yeah this isn't a map issue, the shuttle specifically has an area of its own in order to prevent this sort of thing from happening. If there WASN'T an area, then it would be logical for it to destroy everything in a box-shape, but the area is designed as a sort of outline on what objects it's specifically allowed to move around in that box. This is to allow things like a crescent shaped ship with an airlock/docking port in the middle without those getting deleted.

**Comment by ChangelingRain** [comment]
this is fixed!

**Comment by tigercat2000** [comment]
@ChangelingRain What exactly fixed it, do you know?
