### ISSUE TITLE
Fast clone Exploit

### ISSUE THREAD

**Issue by icecreamcohn** [tgstation/tgstation#14392]
Users are able to ghost while being cloned to pop out the body from the cloner. If the user then re-enters his body he can be defib'd back to life. Possible bug?

**Comment by phil235** [comment]
Does the defib removes the clone damage of the cloned mob? If yes, then that's an exploit. Otherwise it's just another version of fast cloning I guess.

**Comment by icecreamcohn** [comment]
Nah it still starts you at crit.  Its just a fast I clone maybe. An admin asked me to report it. He said ghositng while cloning should make a it impossible to defib.

**Comment by phil235** [comment]
Yeah, something's not right, if you ghost while alive, you cannot renter your corpse.

**Comment by icecreamcohn** [comment]
I can ghost from crit and re-enter my body as long as I do not turn off darkness it seems. Been able to do this for a few months now.

**Comment by Changelingrain** [comment]
Ghost succumbs if in crit.

**Comment by phil235** [comment]
In any case, the mob still start with all the clone damage from cloning, and the defib does not remove clone damage (I checked), so I guess this is pretty much the same as ejecting the cloned mob and putting it in cryo. It just makes the operation safer since you can always defib if the patient dies.

If we want to prevent that, we can add a clone damage threshold to defibrillation (just like we have a 200 brute/fire damage threshold). Maybe something like 150.

**Comment by PKPenguin321** [comment]
blame defibs

**Comment by Changelingrain** [comment]
Or you can give the clone a rezadone pill and they'll get up instantly because it heals all clone damage, instantly.

**Comment by Buggy123** [comment]
But Carpotoxin isn't the easiest stuff to come by.
