### ISSUE TITLE
DNA Saboteur monkifies

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#14442]
I thought the intention was to give you disabilities and NOT monkify everyone it infects?

**Comment by Zilenan91** [comment]
I think the issue with it is that it keeps rerolling on the disability table over and over and over again, so it eventually rolls monkey, which it shouldn't be able to, whereupon the rolling does nothing because monkeys can't have any disabilities aside from tourettes, and unmonkeying people isn't a disability. I could be completely wrong on this too.

**Comment by phil235** [comment]
This shouldn't be possible, see https://github.com/tgstation/-tg-station/blob/89b6e5d0961a005a587e2f9d987d0c93c96031b0/code/datums/diseases/advance/symptoms/genetics.dm#L45

**Comment by Supermichael777** [comment]
Genetics code is ass. Monkiefy isn't being subtracted by that bit of logic. I suspect the logic is badly written.
