### ISSUE TITLE
SPIDER POPUP WINDOWS

### ISSUE THREAD

**Issue by Ausops** [tgstation/tgstation#14689]
> spiders lay eggs
> no end of popup windows and beeps asking if you want to be a spider
> you think it's stopped finally
> they lay eggs again

Absolutely critical issue

**Comment by Shapsy** [comment]
Fucking 5-10 popups per second with no end holy shit send help

**Comment by kevinz000** [comment]
Would YOU like to be a spider?

**Comment by KorPhaeron** [comment]
Could probably be changed to work like an ERT poll does, with each cluster being a team, instead of once per spidet

**Comment by WJohn** [comment]
![](http://i.imgur.com/DQGqmft.png)

The announcements were accelerating towards the end, such that you literally could not close the windows fast enough. The sounds were also being layered, so it got louder and LOUDER AND LOUDER *BEEEEEEP*

It was a nightmare. Admins couldn't even delete the spiderlings away because there were countless eggs, nurses, and spiderlings constantly perpetuating eachother.

**Comment by Lumipharon** [comment]
Or just do the logical thing and make all "do you wan to be X?" appear in chat, not in a pop up box.
Like seriously, half of them are sensible (like golems/posibrains) and appear in chat. There should be no reason for anything to make a pop up box when they clearly don't need to, and if nothing else, for consistancy's sake.

**Comment by WJohn** [comment]
This is still happening with giant *ice* spiders.
