### ISSUE TITLE
Possible Timer Subsystem Oversight?

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/tgstation#15371]
Correct me if I'm wrong, but won't: https://github.com/tgstation/-tg-station/blob/master/code/controllers/subsystem/timer.dm#L25

qdeleted(event.thingToCall) always return 0 due to the fact that it's a variable and not a datum?

This also, incidentally adds a considerable about of overhead to the timer subsystem as it has to do an istype check for every single timer every single cycle.

@MrStonedOne

**Comment by MrStonedOne** [comment]
event.thingToCall holds a reference of the thing needed to be called. Its a variable that holds a datum, an atom, or a client.

**Comment by Fox-McCloud** [comment]
Alright, makes sense.

It is still extremely concerning to me that `qdeleted` is so expensive though---IIRC, the timer subsystem was meant to be a replacement for spawn()'ing, but, if you profile timers, it's notttttt so great compared to just regular old spawn()ing.

**Comment by MrStonedOne** [comment]
the thing is, our mc uses 510's world.tick_usage to properly throttle and ensure that ticks don't overun (`if (world.tick_usage + SS.tick_usage > 80) continue;` with SS.tick_usage being the avg tick_usage thats biases to higher then avg tick_usage), so that's idle cpu anyways.

One thing we could do is change it to store a \ref, so it doesn't stop gcing, and some way to mark it so it can detected re used refs, then that check wouldn't need to run until we actually are about to run the event (this is the reason we check it before checking the event run time.)

I thought about sorting, but that overhead negates the avoidance of spawn

**Comment by Fox-McCloud** [comment]
>the thing is, our mc uses 510's world.tick_usage to properly throttle and ensure that ticks don't overun (if (world.tick_usage + SS.tick_usage > 80) continue; with SS.tick_usage being the avg tick_usage thats biases to higher then avg tick_usage), so that's idle cpu anyways.

There goes the one thing our Process Scheduler had on your MC =p

**Comment by Cyberboss** [comment]
Closable?

**Comment by MrStonedOne** [comment]
No, but it will be soon, i'm making the big sstimer refactor to basically null out the last of it's overhead.
