### ISSUE TITLE
You can severely lag and possibly crash the server with station bound radios.

### ISSUE THREAD

**Issue by Chnkr** [tgstation/tgstation#15434]
1. Put >100 activated radios on a tile.
2. Speak.
3. ???
4. Profit

**Comment by neersighted** [comment]
saycoooode

**Comment by optimumtact** [comment]
it is always been known, you can also just spam the general chat and get banned

**Comment by Shapsy** [comment]
Well I mean it's not hard to figure out who's doing it, so admins can just ban them

**Comment by Firecage** [comment]
Actually, unless someone recently changed it, I only ever got station bounced radio's to transmit different radio messages when not on the same tile. On the same tile, it was still only ever one message

**Comment by Chnkr** [comment]
@Firecage forgot to clarify that bit, you need to turn them on so they automatically transmit.

**Comment by MrStonedOne** [comment]
@tgstation/commit-access People using this to crash bagil is getting annoying.

**Comment by Rinoka** [comment]
Does this still experience serious issues with the new code for compressing messages?

Simple fix would be to disable auto-transmission; however it looks to me like station-bounced radios will use Hear() for broadcasting and _conveniently_ already have an error trapping if/then for preventing inappropriate broadcasts. Location is radio.dm:276.

It should be pretty simple to add a check that if speaker == item/device/radio it'll refuse to broadcast the message; I'll play around with it when I get the chance, but I'm doubting myself if only because this seems like a very, very simple fix for a problem we've been buggered with for two years.

**Comment by optimumtact** [comment]
I've never experienced anyone doing this in a long time

**Comment by Rinoka** [comment]
Same, but it's an issue and we're in a feature freeze, plus this was always kind of a pain in the ass.

**Comment by subject217** [comment]
is this still an issue? I can't reproduce it at all in the way that the OP says.
