### ISSUE TITLE
Cohiba Cigar Case

### ISSUE THREAD

**Issue by Wafflecones** [tgstation/tgstation#15492]
![new bitmap image](https://cloud.githubusercontent.com/assets/17214372/13026622/102eca58-d1f4-11e5-9672-47004c6f202d.png)

This issue is best shown with the picture above. The cigar case takes up two inventory slots with the second one having no sprite. The yellow paint marking shows where my cursor was pointed to get the item ID at the bottom of the screen. If you click on both of the backpack squares, the case will come in your hand...and the issue extends even if you drop the pack.

**Comment by octareenroon91** [comment]
Was there still a slot in your pack that showed 'cohiba robusto cigar case' after you put the case on the table?

It's intentional that an object in storage will be clickable for the whole square of that slot on your screen.

**Comment by phil235** [comment]
The bug happens because when the cigarcase is open and full, it shows individual cigar using overlays and pixel shift. The only real individual cigar sprite has the cigar all the way to the left so each cigar in the case after the first one is an overlay shifted to the right. The problem is that the overlay inherit the layer and mouse opacity of the cigar case object, which means when the case is inside your backpack the overlay of the rightmost cigar is clickable, and since it's pixel shifted to the right it carries over the box to the right.

**Comment by ShizCalev** [comment]
Will fix after #38161
