### ISSUE TITLE
Ninja mask invisible when worn with helmet

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#15972]
![mem](http://puu.sh/nyS8d/6d474906dc.jpg)

**Comment by PKPenguin321** [comment]
i think this is a dupe

**Comment by phil235** [comment]
I closed the dupe.
The issue is simple: Give the ninja mask HIDEMASK bitflag and you get the bug here. Don't give the HIDEMASK bitflag and you get big masks like clown mask protruding out of the helmet. Choose your poison.

OR make the ninja helmet visor opaque, just like it's shown in the item's icon_state (the one shown here in the head slot at the bottom left)

**Comment by kilkun** [comment]
Why not an if statement that gives it the flag if the ninja suit isn't on, but as soon as it's on, it's given the flag? It's not like you can turn it on without the mask.

**Comment by phil235** [comment]
It would still look awful when not on.

**Comment by Shadowlight213** [comment]
You can turn the ninja suit on without the mask.

**Comment by kilkun** [comment]
then why not make it so you can't equip any non-ninja mask when wearing the helmet?

**Comment by ShizCalev** [comment]
This was fixed.
