### ISSUE TITLE
SNPC mimes talk

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#16015]
### What is the problem?

SNPC mimes talk like other SNPCs.

### Why is it a problem, or what should have happened?

TALKING MIMES

TALKING

T A L K I N G

### How can the problem be reproduced?

make SNPC, customize it to mime

**Comment by Dorsisdwarf** [comment]
@sawu-tg

**Comment by sawu-tg** [comment]
This isn't really a bug, It's more an unintended problem. 

SNPCs should not be able to spawn as Mime/Chaplain (and they didn't before I added the customise verb) because Mime, Chaplain, Borg and AI all use special data input that will runtime the server if you try to spawn as them.

Next update the aforementioned jobs will be removed from the customise list.

**Comment by Lumipharon** [comment]
>not letting people spawn teams of snpc mimes that wall off corridors with invisible walls, or create invisible mazes
