### ISSUE TITLE
Quick Virus Stealth Inquiry and Hidden Status of Viruses

### ISSUE THREAD

**Issue by Fox-McCloud** [tgstation/tgstation#16599]
Two quick things regarding virus stealth:
- https://github.com/tgstation/-tg-station/blob/master/code/datums/diseases/advance/advance.dm#L185 is it intended that viruses have a base stealth of 1? This causes conflicts in terms of what's stated on the wiki for what is required to hide a virus from the scanner---though the wiki for virology is also barely updated/maintained.
- https://github.com/tgstation/-tg-station/blob/master/code/datums/diseases/advance/advance.dm#L202 shouldn't this be merely `(2)`? This would mean you'd have to have a level of `4` or higher for it to be hidden by the pandemic and not `3` or higher.

**Comment by optimumtact** [comment]
@LanCartwright

**Comment by LanCartwright** [comment]
1.
I didn't touch these.

2.
No it isn't intended; so far all symptoms have non-default stats.

I think this is for viruses that could be missing a stat and that missing stat will be set to default of 1.

3.
This is interesting since I haven't touched it and it seems to have been overlooked. I'm likely going to sit down and dabble some math over this to rework it lest I apply a simple fix.

**Comment by LanCartwright** [comment]
#16637
This should fix this. As for those stats defaulting to 1 that should be a placeholder or something so I'd hope it shouldn't matter.

**Comment by Fox-McCloud** [comment]
Shouldn't the virus stealth default to 0 though? That would mean the numbers on the wiki would be in-line with what's expected....seems decently logical too.

**Comment by LanCartwright** [comment]
No. I'm not sure what the 1s do, but it's either a placeholder for viruses missing a stat or something involved in the calculation since severity is marked 0 and calculated differently.

**Comment by Cyberboss** [comment]
@lzimann @XDTM  fixed this
