### ISSUE TITLE
Fire Axe on-back side-facing sprites are weird

### ISSUE THREAD

**Issue by Zilenan91** [tgstation/tgstation#16735]
The fire axe hangs in front of you rather than under you like it does on the south and North on-back sprites

**Comment by phil235** [comment]
Purely a sprite issue. the fireaxe should always appear behind the mob when facing WEST/EAST (see combat shotgun on back for reference)

**Comment by SweaterKittens** [comment]
Went ahead and tested this by manually pulling the sprites manually: [Fireaxe Sprite Test](http://imgur.com/a/kjd6L) as well as in-game: [Fireaxe in-game Sprite Test](http://imgur.com/a/VyAQD).

I have to conclude that something funky was going on with the game at the time, because the sprites are a-okay.
