### ISSUE TITLE
Can't see your resources or hp as blob.

### ISSUE THREAD

**Issue by Aloraydrel** [tgstation/tgstation#17142]
FIIIIIX IT

**Comment by phil235** [comment]
Can't reproduce by manually spawning a blob (although I did get a runtime for trying to spawn one before the 2 minute timer ended).

**Comment by ChangelingRain** [comment]
The resources/health don't appear until you actually have a core, as well, but it updates normally once you get one.

**Comment by Aloraydrel** [comment]
The entire round my hud wasn't updates. Tried reconnecting and then admin ghosting in/out. Nothing worked

**Comment by ChangelingRain** [comment]
The only reason I can guess it would fail is it runtiming, but the runtimes would stop once you had a core so that's a tenuous theory at best.

Maybe for some reason you had a core but the overmind's blob_core var wasn't set to it? That should be impossible, though, as all blob creation goes through place_blob_core() or create_overmind(), which both set that.

**Comment by optimumtact** [comment]
or the hud subsystem isn't updating due to lag

**Comment by optimumtact** [comment]
old cannot reproduce
