### ISSUE TITLE
Trying to unban someone crashes the server

### ISSUE THREAD

**Issue by KorPhaeron** [tgstation/tgstation#17475]
unban-panel

type in "saegrimr" in admin field because undoing his bans is my favourite hobby

server freezes

Happening on sybil which is up to date with master as of this post. 

Basically we can't unban anyone Saegrimr has taken over the server please send help

**Comment by Saegrimr** [comment]
MY BANS ARE TOO STRONG.
YOU CAN'T STOP ME.

**Comment by Jordie0608** [comment]
Reproduced, unsure if happens with other admins. I checked the logs, no errors or runtimes relevant.

**Comment by Jordie0608** [comment]
Exported server ban table to local machine and tried again; searching my own bans took a second or two to return. Searching for Saegrimr's bans just lagged out client for a good minute or so but it did eventually return the result. Observed same effect with NikNakFlak's bans. 

Since they both have a lot of bans to their name it would seem this is just a problem with BYOND taking a while to generate the html page for the banning panel, I doubt SQL is at fault here.

**Comment by MMMiracles** [comment]
>having so many bans that the system struggles to comprehend it

whew

**Comment by Jordie0608** [comment]
There's only 22k rows; the feedback table for instance has 1.8 million rows and it's accessed fine.

**Comment by optimumtact** [comment]
almost certainly the html markup

**Comment by tedward1337** [comment]
Sae taking the server by storm.

**Comment by Supermichael777** [comment]
does this still exist?

**Comment by Jordie0608** [comment]
Yes

**Comment by Mervill** [comment]
p a g i n a t i o n

**Comment by PKPenguin321** [comment]
my bans are too strong for you traveler

t. saeg

**Comment by Jordie0608** [comment]
@Mervill That would be admitting defeat to the HTML

**Comment by volas** [comment]
Not sure about /tg/, but maybe empty ckey request will also be fatal for server.

I did some work for the Bay once:
https://cloud.githubusercontent.com/assets/4064061/6557287/f448d818-c684-11e4-9091-8ebfc95f737f.png
(100 last ban's limit on request (who need more?), and advanced search options).

Unfortunately currently I don't have time to port this...
