### ISSUE TITLE
Diagnostic HUD sees traitor silicons

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#17889]
Screeenshot from player who saw a traitor borg: http://i.imgur.com/bQGmNXF.png
Testing traitor AI with diagnostic HUD on: http://i.imgur.com/CuLR4Vb.png

Also someone mark this as spoiler because this is a pretty big fucking exploit.

**Comment by ChangelingRain** [comment]
You can't mark issues as spoilers, silly.

**Comment by Anonmare** [comment]
Look I don't know how git works fam. I just report stuff.

**Comment by GunHog** [comment]
The "[s]" tag means "Security". It is meant for ingame exploits and other things that present a risk to the integrity of the game, gameplay or general security. It is often abused, though.

I believe I know what the problem is, a Diag HUD define is set to the same number as the Antag HUD define. I will have a fix up after I finish testing it.
