### ISSUE TITLE
Gibtonite exploded after stopping it at 0 

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#17951]
![bullshit](https://cloud.githubusercontent.com/assets/6778786/15581552/d6b6e894-233a-11e6-9da7-110ccddabef8.png)

I died and got my leg blown off. You can see the 0 Gibtonite sitting there

**Comment by coiax** [comment]
https://github.com/tgstation/tgstation/blob/ba3f4f4733c5740981e7199ff703c4ccae7da6c1/code/modules/mining/mine_turfs.dm#L207

Gibonite detonation code is here. Depending on which stages the various processes are in, I can see it is possible for you to get the message while it still exploding. If it makes you feel any better, it's a pretty tiny window that you hit; you have to hit it JUST after it's made the final check.

@RemieRichards you're my goto person for time sensitive and peformance level stuff, apart from some rewriting of the defuse() proc, so it turns the gibonite off IMMEDIATELY, rather than modifying some vars first, is there anything that can be done?

**Comment by phil235** [comment]
I don't see how that could happen, the defuse() proc sets the stage var to 2, and the code before the explosion specifically checks for stage == 1.

**Comment by coiax** [comment]
It does things after the checks though.

**Comment by phil235** [comment]
no it doesn't. If stage equals 2 (which is the case when you defuse the gibtonite) then the countdown proc does not call the explosion() or anything.

**Comment by Kromgar** [comment]
Well i didn't have any gibtonite nearby that I defused there was only one Gibtonite.

**Comment by MrStonedOne** [comment]
coiax, unless something sleeps, code execution will always be linear. there is no way for any other code to run while the `defuse()` proc runs

**Comment by MrStonedOne** [comment]
How ever, explosion code sleeps, so that is most likely it. it's not something running while `defuse()` runs, its that explosion has already queued the explosion by the time defuse starts, and it finishes it after defuse ends and control is returned back to byond after attack_by finishes

**Comment by coiax** [comment]
Wait, we have linear execution? How does spawn() work then?

**Comment by MrStonedOne** [comment]
it bypasses linear execution by queuing the spawn's inners to run later during idle time.

sleep does the same thing, spawn is just a non-blocking sleep.

how it works is during sleeps, disk activity, shell() calls, and winget()/winexist(), the current stack is paused, and another stack can be ran.

basically faking multiple threading by having multiple stacks that run in turn on one thread.

a spawn rather then pause the stack, copys the most recent node from the stack, and freezes that, allowing it to see proc local vars as how they were when the spawn was created.

**Comment by coiax** [comment]
I stand informed and corrected.
