### ISSUE TITLE
De-culted Ratvar Servants still hearing Servant chat

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#18023]
Had a player who claimed he was still hearing servant chat after being de-converted. Xhuis, mind taking a look at the code?

**Comment by phil235** [comment]
@Xhuis

**Comment by Xhuis** [comment]
The code says that this shouldn't be possible. I'll test it locally and get back to you.

**Comment by Xhuis** [comment]
Found the problem. Someone coded remove_cultist() in a stupid way and it prevents any other procs from being called in the same proc that it's in. I'll fix that in the second post-merge patch and not code any features for it so that this (and two other high-priority issues) can be fixed.

In the mean time, please just admin-remove servants if they drink enough holy water.
