### ISSUE TITLE
Escape gulag with one simple trick (security HATES him)

### ISSUE THREAD

**Issue by InsaneHyena** [tgstation/tgstation#19120]
OOC: Improvedname: 1 simple trick
OOC: Improvedname: there is 1 simple trick that poeple didnt figure out yet to easily escape gulag
OOC: Improvedname: lord
OOC: Improvedname: When the stacker gets 50 metal pretty much a stack of anything
OOC: Improvedname: it dispenses on the other side
OOC: Improvedname: You break the window of the shuttle
OOC: Improvedname: to get to the other side
OOC: Improvedname: get the metal
OOC: Improvedname: use it again
OOC: Improvedname: for more points
OOC: Improvedname: then repeat it a few times
OOC: Improvedname: and bang escape

This sounds like an exploit to me.

**Comment by xxalpha** [comment]
Time to remove the gulag.

**Comment by jughu** [comment]
Auctally this wasnt a exploit in asteroid mining since there was space so you didnt had enough time to destroy the window cuz you would die

But at lavaland there isnt anything that can kill you when you do that causing this to happen
Why didnt poeple figure out this earlier

I AM THE FIRST TO FIGURE IT OUT? :^) :ok_hand:
