### ISSUE TITLE
Invisbile seed

### ISSUE THREAD

**Issue by kustridaren** [tgstation/tgstation#19266]
When i had used the seed dna manipulator i removed seed from the dna manipulator and there was no seed in my hand but when i press on the dna machine or tray it plants the seed/inserts the seed. The plant i used was the cannabis plant.

**Comment by jughu** [comment]
#Lack of content

**Comment by Firecage** [comment]
Eh, should be fixed when the server updates. As far as I could tell code-wise, it seems to have been due to the goon cannabis seed sprites being in a seperate icon file, which didn't have the experimental seed packet sprite in it aswell, it thus found nothing and didn't give it a sprite and it ended up being invisible.

**Comment by KorPhaeron** [comment]
@Firecage 

Was this fixed?
