### ISSUE TITLE
Thick darkness?

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#19283]
![](http://i.imgur.com/f70zf2p.png)

This is a bug that's been around for ages, reappearing over and over for different reasons. I'm not quite sure what caused this to happen, but the lights are no longer penetrating this darkness. Turning off the area's lights and back on again fixes it.

**Comment by MrStonedOne** [comment]
it's byond `view()` memes,

Because `view()` takes darkness into account, in certain edge cases the fix i did to make the tile the light is on be non-dark up to 7 tiles out in the split second before running `view()` doesn't work. the only fix would be a "mob" that is moved to the location to then have view() be ran from it's perspective so we can set the mob's see flags to ignore darkness but not walls.

**Comment by Iamgoofball** [comment]
ADVANCED DARKNESS

**Comment by MrStonedOne** [comment]
wjohn, next time this happens, save the VV for the turf the light is on, one of the super dark turfs, the light itself, the light source datum on the light, as well as all `/atom/movable/light` objects in the contents of either of the two turfs (making note on if their is more than one `/atom/movable/light` as turfs should never have multiple)

**Comment by WJohn** [comment]
![](http://i.imgur.com/b4IxiAl.png)

May be related. This lava all over the place was pitch black, several people have died to it because they couldn't see it even with their lights on.

**Comment by MrStonedOne** [comment]
two light sources..... hmm.

**Comment by optimumtact** [comment]
looks fucked

**Comment by MrStonedOne** [comment]
the amount of light sources is actually normal, thats because lava acts like a light source.

the amount of lighting objects in contents is fucked. that isn't support to happen.
