### ISSUE TITLE
I spawned without my chest

### ISSUE THREAD

**Issue by InsaneHyena** [tgstation/tgstation#19398]
https://i.gyazo.com/4ee2afd977ecb3159d7bb680b3e2ac4e.png

18;41 server time, I've suddenly spawned without my chest. What's up with that?

**Comment by AnturK** [comment]
Straight out of arrivals ?

**Comment by InsaneHyena** [comment]
Yes

**Comment by PKPenguin321** [comment]
@phil235 ???

**Comment by jughu** [comment]
Feature

**Comment by phil235** [comment]
no clue. Can't seem to reproduce either.

**Comment by Jalleo** [comment]
This may be a edgecase byond issue with how we focus our ticks and have a lot of new() when people are created. @MrStonedOne 
Also replicating probably likely by making serious overhead with the singularity and other things going on at the same time possibly causing too much new() usage but it will be hard to replicate without throttling the server instance hard due to the underlying issue.
