### ISSUE TITLE
Tesla grilles targets only 1 mob

### ISSUE THREAD

**Issue by yackemflam** [tgstation/tgstation#20192]
If there's a tesla grille, only one guy gets targeted.

**Comment by PKPenguin321** [comment]
Intended part of the refactor in #20084

**Comment by PKPenguin321** [comment]
Whoops wrong PR, I meant to link to explosive tesla one

**Comment by PKPenguin321** [comment]
Yeah this one https://github.com/tgstation/tgstation/pull/20083

Exploding tesla bolts on grilles was bad since you could bomb the bridge/sec by throwing a screwdriver at a window, so I made the bolts from grilles separate from actual tesla bolts so they don't ricochet off of the mob they're aiming at anymore

**Comment by yackemflam** [comment]
You also made it so that they get so damaged they get husked.

**Comment by PKPenguin321** [comment]
It was actually always like that afaik, just that because the bolt ricocheted the damage spread out. I guess I could lower it.

**Comment by yackemflam** [comment]
Meh, if enough players complain about it then lower it, but atm it's funny as hell.
You can play russian roulette with a bunch of people.

**Comment by PKPenguin321** [comment]
In that case this issue can be closed

**Comment by kevinz000** [comment]
exploding things by tossing people and grillshocking them sounds fun.

**Comment by PKPenguin321** [comment]
not if you're the HoP, or the CE, or on the bridge, or in the brig
