### ISSUE TITLE
AI has zero defense against changelings

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#20195]
Changelings can kill the AI with ease, and there is absolutely nothing an AI can do to stop them. All they have to do is crawl through the vents as a monkey and EMP when they reach the AI core. the amount of time it takes to recover from a ling EMP is more then enough time for the monkey to break in and kill the AI.

This is a pretty glaring balance issue in a game where the AI already has an extreme amount of trouble dealing with anything else trying to enter the AI core. turrets are next to useless against anyone else due to the new projectiles and how easy they are to just juke, and the stun bolts have huge blind spots in the core besides. I've been making issues about this repeatedly but there's been no change.

**Comment by kevinz000** [comment]
I can also take out the metastation AI core with two ion rifle shots and hacking tools, alone. ;^)

**Comment by PKPenguin321** [comment]
I think this is a dupe

**Comment by AdamElTablawy** [comment]
have a borg weld vents once ling is declared

**Comment by PKPenguin321** [comment]
EMP works from within the vents

**Comment by Niknakflak** [comment]
Not a bug

**Comment by Anonmare** [comment]
Wait, I thought this was already fixed like 6 months ago.

**Comment by Shadowlight213** [comment]
This is a dupe

**Comment by xxalpha** [comment]
Pipe filters to stop crawlers from passing.

**Comment by Shadowlight213** [comment]
Honestly the counter to ventcrawling lings is what any good atmos tech should do.
Max pressurize the distro line. If there's atmos techs, they can replace the gas pump with a volume pump, and if there isn't, the AI can just max the pressure on the regular pump.
It pretty much stops regular monkey ventcrawl and discourages lings since they have to constantly keep fleshmending the pressure damage.

**Comment by optimumtact** [comment]
Feedback forum
