### ISSUE TITLE
Runtime with carpet new and mineral titanium interior

### ISSUE THREAD

**Issue by Jalleo** [tgstation/tgstation#20259]
[Note]: # Says it on the tin

Just load up via a local server and it will happen pretty much on every load up.
I believe this is caused by the crashed ship ruin.

**Comment by Shadowlight213** [comment]
I know exactly what's causing this. It's been an issue with the black market packers ship for ages.
Along the wall in the west part of the ship, there's 2 turfs stacked on top of each-other. One is the slanted wall, and the other is the carpet.
The update_icon proc that is used to smooth the carpet gets run on the wall instead of the carpet and causes a runtime as it doesn't have that proc.
