### ISSUE TITLE
Cannot catch bolas. ISsue or intended?

### ISSUE THREAD

**Issue by nullbear** [tgstation/tgstation#20317]
Throw bola at someone who is in throw-mode. Ensnare them anyways.

**Comment by PKPenguin321** [comment]
not intended, supposed to be covered by this: https://github.com/tgstation/tgstation/blob/master/code/game/objects/items/weapons/handcuffs.dm#L329

iirc when i first made them and tested this worked properly so something might have broken since then (or this report is just wrong, needs reproduction)

**Comment by XDTM** [comment]
@AnturK tested, bola gets caught properly if in throw mode
