### ISSUE TITLE
Service borg glass generates infinite liquids

### ISSUE THREAD

**Issue by pubby** [tgstation/tgstation#20383]
1. Be service borg
2. Use the dropper to pick up liquids and put them into your drinking glass
3. Create a new drinking glass using the Rapid-Service-Fabricator
4. Transfer the contents of your drinking glass into the new drinking glass
5. Wait

After a minute or two your drinking glass will magically refill with its previous contents, allowing you to empty it again into a new glass. You can use this to create infinite Omnizine,  Morphine, Polonium, or whatever rare chemical you want.

**Comment by InsaneHyena** [comment]
Working as intended

**Comment by Kromgar** [comment]
Ah hello sir. Would you like a healthy glass of... POLONIUM?

**Comment by xxalpha** [comment]
This is a feature.

**Comment by evsey9** [comment]
f e a t u r e

**Comment by xxalpha** [comment]
@optimumtact this isn't a bug.

**Comment by optimumtact** [comment]
Yes it is

**Comment by Dorsisdwarf** [comment]
Pretty sure that its just a badly implemented feature, but I'll defer to the citrus

**Comment by xxalpha** [comment]
Loll maybe the code for refilling is somewhere else, how is that a bug? Reagent containers don't just refill themselves as far as I am aware, so this effect had to be intentionally coded.

But keep on nerfing borgs.

**Comment by Dorsisdwarf** [comment]
Uh.
I'll look some more, but the different borg modules are pretty clean with their stuff. There's explicit procs for recharging/replenishing, there dont seem to be any procs that would do this attatched to service borgs, and its not a special object. its just a glass. (/obj/item/weapon/reagent_containers/food/drinks/drinkingglass). The enzyme bottle _does_ have explicit code right there for doing something very similar, so if it IS an intentional feature, I might have to track down who made it and burn them in effigy for atrocious code standards.

also gtfo I've been against almost every silicon nerf there's been :/

**Comment by AlexTheSysop42** [comment]
@shizcalev close this, it's a feature (see the part that the pr removes)

**Comment by optimumtact** [comment]
this is a bug

**Comment by pubby** [comment]
If yall want it to be a feature it should be implemented like one. Make it a button or a module and give it text descriptions explaining what it does.

**Comment by AlexTheSysop42** [comment]
It literally says what it does in a comment and is obviously intentional, how is this a bug

**Comment by optimumtact** [comment]
because I said so

**Comment by Detective-Google** [comment]
still happens
