### ISSUE TITLE
CE can fly (and move) through space without a jetpack,also affects borgs

### ISSUE THREAD

**Issue by Lexorion** [tgstation/tgstation#20410]
Reply PM from-David273/(David Whyvenyr): Advanced magboots let me attach to space

This basically means they can move through space without jetpacks. A borg also had a similar "issue",it was able to walk on space after it dragged a computer frame from a plating.

**Comment by TechnoAlchemisto** [comment]
now thats what i call scifi

**Comment by lzimann** [comment]
works with any kind of magboots

**Comment by optimumtact** [comment]
likely caused by @ChangelingRain in #20303 but I cannot for the life of me work out exactly why

https://github.com/tgstation/tgstation/pull/20303/files#diff-119f6ba4ac80669866f8d4f362d8a7ffR34

this line was clearly shortcut in the old system if the turf was a space turf, so that if you are not on some solid ground the magboots give no gravity but I cannot determine what exactly in the pr changed it.

**Comment by ChangelingRain** [comment]
I've figured out why and it's dumb and I'm going to fix it the easy way rather than the frustrating, debug-filled way.
