### ISSUE TITLE
How to handle teams

### ISSUE THREAD

**Issue by AnturK** [tgstation/tgstation#20587]

**Comment by Jalleo** [comment]
Please explain more by what you mean with teams. Antag? department? etc. etc.

**Comment by AnturK** [comment]
Antag teams but can be generic enough to be expandable to anything really. Initial idea is some lightweight /datum/team created on demand by the antag datums. Would ideally be as thin as possible (members tracking and shared objectives only ?) to allow for various usage (giving objectives to crew groups etc). Stored by type in some generic teams[type] = list() to allow for multiple teams per antag type.  This is just initial idea and the issues are more specific but having some feedback never hurts.

**Comment by Jalleo** [comment]
Okay well its probably best with leaders in one list and general antags of that team in a second. (Also on phones you cant go to the projects bit and on desktop ut dosent show if a issue report is connected to a project yet...)

**Comment by JJRcop** [comment]
Maybe teams should have ranks, that is simply a number, that digferent members of the team can be assigned to.

Also, where will code go from modes like Cult? It should go SOMEWHERE other than the gamemode datum, as ideally that datum will be killed. I think it would be best served by the team datum, and of course be rewritten with multiple teams of the same type in mind, instead of simply ported over out of the horrible stinky slum of gamemode.

**Comment by KorPhaeron** [comment]
Leave discussion for datum antags on the currently open PR please
