### ISSUE TITLE
The bible can be forced to take any form and shape.

### ISSUE THREAD

**Issue by Chnkr** [tgstation/tgstation#20720]
There are no range/in hand checks here, which would allow anyone that has a `/ref` of the bible `src` to set it's icon.

``` dm
/obj/item/weapon/storage/book/bible/Topic(href, href_list)
        if(href_list["seticon"] && ticker && !ticker.Bible_icon_state)
                var/iconi = text2num(href_list["seticon"])

                var/biblename = biblenames[iconi]
                var/obj/item/weapon/storage/book/bible/B = locate(href_list["src"])

                B.icon_state = biblestates[iconi]
                B.item_state = bibleitemstates[iconi]

                //Set biblespecific chapels
                setupbiblespecifics(B, usr)

                if(ticker)
                        ticker.Bible_icon_state = B.icon_state
                        ticker.Bible_item_state = B.item_state
                feedback_set_details("religion_book","[biblename]")

                usr << browse(null, "window=editicon") // Close window
```

**Comment by Carbonhell** [comment]
>not criticizing the vars defined under ticker
you've failed me erik

**Comment by Mervill** [comment]
Ok so here is another issue that's easy to fix but harder to solve. 

In principle it's easy to convert this to a popup and make this issue go away, but the underlying problem (in my mind) is that the chaplain is allowed to change the cover of the bible at all, since the title of the book is set by your religion when you create a character (So you can end up with a Quran that's titled "Dianetics").

Should the chaplain be allowed to set the cover/religion of the bible after roundstart, or should it be set by the religion variable from character creation?
