### ISSUE TITLE
The communications console input() is awful.

### ISSUE THREAD

**Issue by Chnkr** [tgstation/tgstation#20796]
You can simply stack multiple `input()` screens and them use those to spam the ever-living shit out of them.

![fire coderbus](https://totallynotmy.website/QrWl.png)

**Comment by Giacom** [comment]
It's so easy to create bugs with Input() since it stalls the thread until the user gives you something, so there's no callback you can give it to execute after the input has been entered. This is why using menus and Topic() is better since the Topic() is essentially a monolithic callback to refer to.
