### ISSUE TITLE
Players with "return to lobby" set in job preferences can be made antags in the lobby.

### ISSUE THREAD

**Issue by NSSherlock** [tgstation/tgstation#20804]
1. Ready-up for round with "return to lobby if preferences unavailable" set in occupation preferences, and "be revolutionary" set to "yes," in game preferences.
2. Don't get selected for a chosen job, remain in lobby.
3. Notified of revhead status and objectives anyway.

In this instance, there was still one revhead in the round, but in another instance it could presumably result in a case of #20554 .

Note that this was _not_ a case of hitting "ready" at the last second (or even close to it) as in #14469 .

Additional information: Since I didn't know with certainty if I would keep the status (and didn't want to play with metaknowledge regarding the round type in the event that I didn't keep it), I chose to observe instead. At round end I was not listed among the revheads.

I'm assuming this can happen with other antag types as well, and is probably related to the aforementioned unresolved issues, but since this was enough different than the specific sequence described in the prior issue report, I thought it probably merited its own. If nothing else, this seems like a bit less of an edge case than readying at the last second, IMO.

**Comment by AnturK** [comment]
This is because you technically can't reject antag assigned player but without set role he won't spawn. Probably needs to assign random job in this case despite the preference since reverting antag choice is more annoying.

**Comment by NSSherlock** [comment]
It was Metastation on Basil with 40ish players, I think. So not really high pop, but not exactly low pop, either.

**Comment by Shadowlight213** [comment]
Found it!
https://github.com/tgstation/tgstation/blob/master/code/game/gamemodes/revolution/revolution.dm#L57
https://github.com/tgstation/tgstation/blob/master/code/controllers/subsystem/jobs.dm#L478

In pre_setup(), the code doesn't give them a special_role for rev. It adds them to a list, but then trims it based off the head count. The special_role isn't actually given till the greet_revolutionary proc.

For other gamemodes, the special_role is set in pre_setup().
Reject_player() only returns and forces them to spawn if they already have a special_role assigned.

Since only pre_setup() is called before DivideOccupations(), and the post_setup() is called afterwards, they were in the head_revolutionaries list, but as their mind's special_role hadn't been set, Reject_player() didn't detect it, and left them in the lobby. Post_setup() then tried to make them a revhead.

As for fixing it, I can't really think of a way to do this without problems.
* Having the revhead special_role be set in pre_setup() means either the head balance is disabled and there are always max revheads regardless of the number of heads, or if it's not disabled, the player gets a hard tell that it's rev due to them spawning and not being antag.
* Delaying the player's spawn till the head roles have been given would probably be super snowflake.
* Make people with "return to lobby if preferences unavailable" set be excluded from the revhead role is a band-aid fix and kinda shitty.
* Remove the revolution gamemode completely.

Hopefully, there is a way to do this that I missed.
