### ISSUE TITLE
Engy borg station alert window can't be closed and steal focus every 5 seconds or so

### ISSUE THREAD

**Issue by CyberbossJHCB** [tgstation/tgstation#20852]
>Play engy borg
>Open alert window
>Cry when you stop moving every five seconds and have to click the main window again

**Comment by lzimann** [comment]
It has a "canclose=0" when it opens the browser for some reason:
https://github.com/tgstation/tgstation/blob/dff4db726a6b6e98b5c82684644f3a1c6e330679/code/modules/mob/living/silicon/robot/robot.dm#L338

I'm currently changing to work as our custom browser datum instead of using byond's so it will be a bit prettier aswell.
