### ISSUE TITLE
Invisible hulk morphs

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#20945]
Morphs can gain genetics powers from things they eat, and moving around as a invisi hulk morph doesn't make you go visible

**Comment by phil235** [comment]
>Morphs can gain genetics powers from things they eat

When did that happen??

**Comment by PKPenguin321** [comment]
The real reason is that morphs inherit transparency from their disguise target, meaning that if they disguise as a human who's currently invisible from the chameleon mutation, they become invisible. However, they lack the actual mutation, meaning the code for making them visible when they move is not there.

**Comment by phil235** [comment]
>morphs inherit transparency
why....
