### ISSUE TITLE
Ruins generating power alarms

### ISSUE THREAD

**Issue by francinum** [tgstation/tgstation#21152]
![](https://file.house/UCSb.png)

**Comment by CyberbossJHCB** [comment]
Where was this? Station console? AI Console? Tablet?

**Comment by phil235** [comment]
so apparently power alarm code doesn't check z level?

**Comment by CyberbossJHCB** [comment]
The thing is I don't think the rigid alarm console and the alarm downloadable program use the same code, because I've noticed this bug before but could only repro it on tablets i think.

See https://github.com/tgstation/tgstation/blob/eace4eec148e8a366ee2fe6673f852b59a2e77b1/code/game/machinery/computer/station_alert.dm

and

https://github.com/tgstation/tgstation/blob/eace4eec148e8a366ee2fe6673f852b59a2e77b1/code/modules/modular_computers/file_system/programs/alarm.dm

I think the bug is in the second one, I'll fix it.

**Comment by francinum** [comment]
Tablet.

**Comment by KorPhaeron** [comment]
I think this got fixed when Phil redid the areas
