### ISSUE TITLE
Server does not show up on HUB and station name setting in config is ignored.

### ISSUE THREAD

**Issue by straycat0000** [tgstation/tgstation#21160]
My server (with code from 23.10.2016), does not show up on the HUB. 

This is how the config looks like:

http://pastebin.com/xnJzUt3w

**Comment by MrStonedOne** [comment]
stupid bug where if DreamDeamon is in private mode, setting hub in code sets it to invisible mode, rather then public mode. change that drop down.

**Comment by straycat0000** [comment]
That is not the case here. My dream deamon is in public mode.

**Comment by straycat0000** [comment]
Also the station name setting is ignored.

**Comment by MrStonedOne** [comment]
https://secure.byond.com/forum/?post=2167713

**Comment by Bitwise10** [comment]
MrStonedOne, I believe that may be a separate issue. I do not believe this is just a BYOND bug. I have been using vanilla /tg/ code that was from August 24, and these features worked perfectly fine. I decided to update my code today to the latest release, and now the "SERVERNAME", "STATIONNAME", and "HUB" variables in the /config/config.txt do not seem to be reading properly. 

To confirm this is not the issue you described in your BYOND forum post, I have been testing this with DreamDaemon in "Public" mode.

Taking a peek at the timeline in between the end of August and the date this issue was opened, there are two commits I see that altered the code for processing these variables:
https://github.com/tgstation/tgstation/commit/44f563229974d56842173d2a89caf153ed70e201
and
https://github.com/tgstation/tgstation/commit/37f3b275d10bfda850f69703e075765bf7c9c4fe

I'll try downloading an old repo that pre-dates these changes and test if that solves the issue.

**Comment by MrStonedOne** [comment]
its a byond bug, plain and simple, try reading the linked bug report.

**Comment by Bitwise10** [comment]
I did read the bug report, and that's why I brought this to your attention.

**Comment by MrStonedOne** [comment]
you can test by changing the server's publicity from public to private, then back to public, the server will show right back on the hub.

there is a linked test project and hub page, do the same with that, and you get the same results.

your best bet would be to bump that bug report

**Comment by Cyberboss** [comment]
According to MSO this was fixed

**Comment by MrStonedOne** [comment]
Fixed in #29446
