### ISSUE TITLE
Devil Antag pick is ignoring the setting that protects implanted people from being antag. I was a security guard and got devil antag.

### ISSUE THREAD

**Issue by straycat0000** [tgstation/tgstation#21195]
Devil Antag pick is ignoring the setting that protects implanted people from being antag. I was a security guard and got devil antag.

**Comment by Anonmare** [comment]
>Implying the Security staff are not Evil Incarnate already
Are you sure it's not like pop-blob where it ignored antag protections on purpose?

**Comment by straycat0000** [comment]
I don't know what pop blob means. I was being the devil at round start despite being security guard.

**Comment by AnturK** [comment]
@lordpidey Was this intended or just omission ?

**Comment by lordpidey** [comment]
It was intended, but if you feel it would be best to NOT have, it can easily be removed.  Right now the list of forbidden jobs is:

protected_jobs = list("Lawyer", "Librarian", "Chaplain", "Head of Security", "Captain", "AI")

AI is forbidden simply because it doesn't work.  Captain/HoS are forbidden as it would make a round too unfun.  Chaplain devil seems thematically inappropriate, and lawyer/librarian are designed to work as anti-devils, so they need to NOT be devils.

**Comment by lordpidey** [comment]
Oh, one last question:  Was it a devil round, or a devil-agent round?  If it's devil agent, one of your objectives will be to have more souls than another specific devil, for regular devil, you'll have two normal devil objectives.

**Comment by straycat0000** [comment]
My impression was that "protect jobs from antags" affects all NT implanted jobs.

**Comment by Cyberboss** [comment]
It's a friken devil though. I think it thematically shouldn't care. Captain and HoS are enough.

**Comment by jughu** [comment]
Mindshields for devils

**Comment by kriskog** [comment]
Intentional
