### ISSUE TITLE
Medibots can and still will overdose you

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#21346]
>30u tricord >Overdosing >It keeps injecting the same things >You now have metric tons of tricord in you.

**Comment by XDTM** [comment]
Man, tricord does more harm than good. Maybe its recipe should have another component.

**Comment by GunHog** [comment]
Reproduction steps, please. We had long since believed that we fixed this.

**Comment by PKPenguin321** [comment]
Syndie mediborgs probably do it considering it happens with tricord

**Comment by GunHog** [comment]
Yes, so we Syndicate medi**bots**, also known as "Mysterious Medibot", as being the cause. I need more data, though. What happened? How was the patient injured? Was a pAI inserted into the medibot? **Was an emag used only once or twice on it?** (Once to unlock it, twice to hack it)

**Comment by Onule** [comment]
If you have enough brute, burns and toxin damage, medibots will inject you with enough bicaridine, kelotane and antitoxin that'll mix into tricord. Since it injects 15u each, you'll get around 40u~ tricord when mixed, getting an overdose and taking, you've guessed it, brute, burns and toxin damage. It will then try to inject more chems, that'll mix into more tricord.

**Comment by TechnoAlchemisto** [comment]
maybe we should raise tricord's OD level to around 60

**Comment by GunHog** [comment]
Ooooooooooooooooh. So it is a chemical reaction. The medibot does not detect the chems it injects, because they become tricord? That is amazing! You could also consider changing the recipe for tricord, or requiring it to be heated to react. (But then might it react when a guy is on fire and the medibot injects all three chems?

**Comment by Shadowlight213** [comment]
Feature

**Comment by PKPenguin321** [comment]
yeah i think this should be considered a non issue imo

**Comment by Iamgoofball** [comment]
Don't buff tricord

**Comment by XDTM** [comment]
Really though would it be acceptable to add, i don't know, water to the tricord recipe so accidental tricording doesn't happen? This issue is related to upgraded sleepers, since many people don't know about tricord mixing/overdosing and end up killing their patients.

**Comment by Shadowlight213** [comment]
No, this is hilarious. Keep it.

**Comment by SgtxRootbeer** [comment]
maybe set the medibots to use charcoal instead of antitoxin, to prevent the mixing?

**Comment by Bawhoppen** [comment]
No, leave it

**Comment by YakumoChen** [comment]
I didn't even know medibots could inject anti-toxin...
