### ISSUE TITLE
Bees possibly causing lag

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#21633]
Mob subsystem was at about 320ds. I deleted all bees (24) and it dropped to 180ds

handle_automated_action() for bees is also relatively high up on the profiler list

**Comment by optimumtact** [comment]
likely fixed by 21688
16:47 < oranges> can someone spawwn a shit tonne of bees and tell me if the server lags?
--------------------------------------------------------------------------------------------
16:50 <+PKPenguin321> sure
16:53 <+PKPenguin321> spawned 100 bees on thunderdome
16:53 <+PKPenguin321> no lag
