### ISSUE TITLE
backup emergency shuttle not loading

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#21731]
![rip](http://puu.sh/stqz2/b3e2954ed6.png)
This happens roundstart on every map.
@coiax

**Comment by coiax** [comment]
Looks like a map error to me. Backup shuttle is just a feature on z2, not a template.

**Comment by Shadowlight213** [comment]
@coiax the thing is, in DM map editor, the shuttle looks perfectly fine

**Comment by coiax** [comment]
I'll bisect it, see where it turned up

**Comment by coiax** [comment]
The bug is not happening in 8d86c23c47ab106a20d37d85678b019de07021ee, on my machine. Does it always happen?

**Comment by Shadowlight213** [comment]
Yes. Every single round pretty much.

**Comment by PKPenguin321** [comment]
This doesn't happen every round, I see it load sometimes and fail other times.

**Comment by PKPenguin321** [comment]
I've seen it load properly on Box, will edit with other maps when they happen.

**Comment by coiax** [comment]
Looking at the screenshot again, I think I've seen it do this before, a while back, but I can't remember the circumstances.

If we could get it reliably reproducing, then that would be a step to understanding what the problem is.

As an aside, it's not even required anymore, it was originally coded to provide a sort of failsafe for a bad template load or horrific admin var fuckery, but I don't think it ever actually is used, despite its fantastic design.

**Comment by coiax** [comment]
I think I fixed this.

**Comment by Shadowlight213** [comment]
Yeah, it seems to be fixed.
