### ISSUE TITLE
Movement at 60 FPS feels really fucking floaty and unresponsive.

### ISSUE THREAD

**Issue by Iamgoofball** [tgstation/tgstation#21839]
We need to do something about glide animations at 60 FPS.

**Comment by MrStonedOne** [comment]
do 40 or 100 fps.

It should to be a multiple of the server fps (20) that even divides into 1000. That is basically 40 fps or 100fps.

Otherwise the ticks will either alternate between being in and out of phase with the server tick, or they will be out of phase with byond's internal timer and get rounded to some odd ass number that has the first condition.

**Comment by MrStonedOne** [comment]
Also: http://www.byond.com/forum/?post=2178421

**Comment by MrPerson** [comment]
There's very little that can actually be done with gliding. Glides that are perfect locally are messed up networked. I don't know why, I don't care to find out anyway.
