### ISSUE TITLE
PDA overlays getting reset

### ISSUE THREAD

**Issue by willox** [tgstation/tgstation#22038]
When opening/refreshing either the PDA's messenger or messages list, the overlays get reset.

Steps to reproduce:
1) Place ID in PDA, so that the red light turns green
2) Open messenger
3) Witness light turning red once again

You'll also see the pen's overlay disappear.

I think it's caused by the code @ https://github.com/tgstation/tgstation/blob/09ea5ad2e5c595c1631486146c1f5051699e3a2d/code/game/objects/items/devices/PDA/PDA.dm#L559-L560.

If that's the case, the same issue probably occurs when you receive a message due to https://github.com/tgstation/tgstation/blob/09ea5ad2e5c595c1631486146c1f5051699e3a2d/code/game/objects/items/devices/PDA/PDA.dm#L654

Server revision compiled on: 2016-12-08
Test merge active of PR #19250 
Test merge active of PR #21992 
Based off master commit 5a1aa561fd7e04b4469843da14057234cf0fba3f

**Comment by blockheads** [comment]
ughh my git is all sorts of fucked up, but anyways the fix is really easy

`	if (mode == 2||mode == 21)//To clear message overlays.
-		cut_overlays()
+		update_icon()
 
 	if ((honkamt > 0) && (prob(60)))//For clown virus.
 		honkamt--
 @@ -651,7 +652,7 @@ var/global/list/obj/item/device/pda/PDAs = list()
 	if(L && L.stat != UNCONSCIOUS)
 		L << "\icon[src] <b>Message from [source.owner] ([source.ownjob]), </b>\"[msg.message]\"[msg.get_photo_ref()] (<a href='byond://?src=\ref[src];choice=Message;skiprefresh=1;target=\ref[source]'>Reply</a>)"
 
-	cut_overlays()
+	update_icon()
 	add_overlay(image(icon, icon_alert))`

all you have to do is change cut_overlays() to update_icon() and it should fix it
