### ISSUE TITLE
[Delta Station] Brig issues

### ISSUE THREAD

**Issue by Cobraman202** [tgstation/tgstation#22394]
Issues:
1. Brig lacks non-perma brigs, and any timers for the multiple person cells.
2. Warden lacks button to close armory door shutters.
3. There are a grand total of 5 prisoner uniforms in the entire brig. Consider adding more in a locker.

**Comment by Okand37** [comment]
The brig lacks non-perma brigs? Having some difficulty understanding what you mean here so correct me if i'm wrong;, the two cells in the main portion of security both have timers, as well as every department cell having a timer. https://i.gyazo.com/f1065807bdd81ceb445fd7eee4fbf4ac.png

There is a button to close the armory door blast door, it is in the armoury near the desk. There are no shutters for the windows, this is intentional.

I'll add a few extra pair of prisoner jumpsuits to the prisoner lockers in the permanent residence area.

**Comment by ExcessiveUseOfCobblestone** [comment]
@tgstation/commit-access I don't think this is an issue, as there is a perma area above the cells, there are timers for each non-perma cell, and the Warden does in fact have buttons in his office [just not beside him in the desk, it's beside the door].

**Comment by optimumtact** [comment]
report these issues on hte map thread for each map
