### ISSUE TITLE
Switch body into changeling... bite corpse... come back in autocloner... changeling body pops and I am unable to be mind potioned into the monkey changeling bdoy due to higher form of thinking

### ISSUE THREAD

**Issue by Kromgar** [tgstation/tgstation#22528]
Fucking hell that pissed me off

It shouldn't force you into the cloner body if you switched bodies

**Comment by XDTM** [comment]
I remember when a tator killed me, stole my brain and borged me, only for me to be forced into my cloned body ready for revenge

**Comment by Kromgar** [comment]
Maybe make it a prompt?

**Comment by JJRcop** [comment]
Wow grandma, what long issue title you have!

**Comment by Kromgar** [comment]
The better to provide coders details with @JJRcop

**Comment by jughu** [comment]
I MEAN TECHNICALLY THIS ISNT A BUG

**Comment by ExcessiveUseOfCobblestone** [comment]
https://github.com/tgstation/tgstation/blob/e4053877ad6d29d80cf4a77f57db8359021d7080/code/game/machinery/cloning.dm#L134

I'm thinking the best way to do this is to add a second argument to the get_ghost proc which checks if you're an observer, but i'm afraid if I do that I'll have to edit everything get_ghost related.

**Comment by Shadowlight213** [comment]
All these bugs due to the fucking delayed cloning pull.
I swear we should just remove it.
@ExcessiveUseOfCobby adding a pull argument won't solve it. The clone will still process, but just throw out a braindead or whatever while also deleting the record. Next thing we know, we have people complaining that the autocloner is bugged since they cot scanned, died, but got defibbed before the clone finished, then died again and didn't get cloned.
Plus, that runs into the side effect of if someone ghosts, but then re-enters their body, it will stop their cloning.
I think a better way to handle it, is to have the mind's active body be switched to the cloning body upon the cloning process starting. That should fix all the delayed cloning bugs, since it'll consider the new body to be active and returning to corpse or whatever will go into the cloning body.
You might need to add a flag to the ghost as well to prevent other get ghosts from pulling.
That should fix the actual bug part of the complaint, where they got pulled from a body. The autocloner grabbing them if they ghost even if they mindswapped is 100% intended since their mind is still the same. They shouldn't have gotten scanned or gotten someone to delete their record if they were planning to xenobio ling.

**Comment by ExcessiveUseOfCobblestone** [comment]
jesus i'm an idiot in the mornings

**Comment by Kromgar** [comment]
Thats how it used to be...
