### ISSUE TITLE
Slime Speed Potion doesnt increase speed

### ISSUE THREAD

**Issue by HankMoodyExperience** [tgstation/tgstation#22675]
When using a slime speed potion, from a slime or admin spawned otherwise (hi kev) on an object such as a scooter or mech, it does not increase the speed or remove any cooldowns, simply making it red. 

Red wunz are supposed to go fasta' you gits.

**Comment by XDTM** [comment]
It only removes any slowdown it causes.

**Comment by GunHog** [comment]
> It only removes any slowdown it causes.

This is only true for worn items, not vehicles.

https://github.com/tgstation/tgstation/blob/f3ed316aa307f1dc065960b8241b12425dba031b/code/modules/research/xenobiology/xenobiology.dm#L334

Mechs are /obj, but there is no code in the slime speed potion for boosting mechs. The Gygax and Ripley mechs would need to be refactored slightly in order to support speed increases due to their speed change code.

Scooters reset their movespeed after someone gets on them, negating the speed up: https://github.com/tgstation/tgstation/blob/e9ebe52616d1ada3009253a31263f5dc0ae1c4d7/code/modules/vehicles/scooter.dm#L50.

**Comment by PKPenguin321** [comment]
My bad on the scooters bit, that's an oversight since I never accounted for outside forces to change the speed. I can think of a fix

**Comment by AnturK** [comment]
Not a bug.

**Comment by GunHog** [comment]
@AnturK Scooters being unaffected by speed potions **is** a bug. Mechs being painted red by speed potions yet not gaining speed **is also a bug**.

**Comment by AnturK** [comment]
Was that ever a feature ?

**Comment by KorPhaeron** [comment]
Mechs being painted red were never supposed to go faster

The scooter is supposed to go faster though

**Comment by MimicFaux** [comment]
Doesn't remove slowdown from clownshoes either!

**Comment by PKPenguin321** [comment]
Nevermind I can't think of a fix without snowflaking the scooter/red potion interaction

**Comment by HankMoodyExperience** [comment]
thank you for responding and not calling me retarded guys; glad someone other than kevinz believed me

**Comment by YakumoChen** [comment]
I remember riding red scooters around the station back when they were added

**Comment by PKPenguin321** [comment]
Yeah that was before I fixed them being turbo wheelchairs
