### ISSUE TITLE
Error message after reconnecting after internet failure

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#22804]
```
Connection failed.
Reconnecting in 10 seconds...
Unrecognized or inaccessible verb: .update_ping

```

@MrStonedOne 
Context, I pulled the ethernet cable out of my laptop, and then it was back in by the time it reconnected. That message then occured.

**Comment by MrStonedOne** [comment]
ya, byond can take a moment to load verbs, it's actually kinda hard to know when it's done so, and its not info the SS has because we don't store the connection time of the mob.

We would either have to store that and make the ping ss delay pings for clients that just connected or just ignore the issue.

**Comment by coiax** [comment]
Wait, why is it a verb?

**Comment by MrStonedOne** [comment]
its how this entire system works.

We send a command to the client, telling it to run a verb with the current time info as the arg, it runs that verb, we process it on the server.

It can't be a topic because topic's are only processed at the start of every byond tick, whereas verbs can be made to process the moment it gets the verb on a verb by verb bases

Also the only way we can make the client trigger a topic is browse() or output() and those have other queuing constraints that winset doesn't have.

**Comment by coiax** [comment]
Ah, it has to be a verb because it's running stuff on the client side?

**Comment by MrStonedOne** [comment]
yes... oh, you thought byond gave us a way to see the client's ping? you silly dog you. We have to use all sorts of trickery to get this to work. https://github.com/tgstation/tgstation/pull/22531/files

**Comment by coiax** [comment]
So this is a "can't fix" issue?

**Comment by optimumtact** [comment]
it's work aroundable at least
