### ISSUE TITLE
shunted AIs lose all their malf verbs.

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#22848]
This also includes, unfavorably, the ability to undo a shunt.

**Comment by ChangelingRain** [comment]
you can't [s] an issue, silly.

**Comment by kevinz000** [comment]
Shunting should be giving the AI a verb to return to core in malfunction tab, but after shunting the malf picker datum isn't even there which makes it impossible to go back.

**Comment by GunHog** [comment]
The Shunting ability should be reworked to avoid creating a new AI inside of an APC, but instead moving the same AI over, and setting a var on the old core structure tying its AI back to it. 

The AI can return to the core as long as it still exists, and the core will have an icon indicating that it belongs to an AI (instead of being empty). Since the core becomes an empty structure item (same as when an AI is carded from one), the crew can simply perform one step in deconstruction to clear the var and prevent the AI returning.

**Comment by MimicFaux** [comment]
The AI code itself is a tangled monstrosity that probably needs to be gutted in the future.

**Comment by evsey9** [comment]
SO THATS WHY I COULDN'T DO ANYTHING AS A SHUNTED AI EARLIER
FUCK YOU CODERS



well i greentexted though

**Comment by Cyberboss** [comment]
```
[15:16:58] Runtime in apc.dm,875: Cannot execute null.transfer to().
  proc name: malfoccupy (/obj/machinery/power/apc/proc/malfoccupy)
  usr: Wikipedia () (/mob/living/silicon/ai/spawned)
  usr.loc: The floor (150,32,1) (/turf/open/floor/bluegrid)
  src: MiniSat Chamber Hallway APC (/obj/machinery/power/apc)
  src.loc: the floor (152,43,1) (/turf/open/floor/bluegrid)
  call stack:
  MiniSat Chamber Hallway APC (/obj/machinery/power/apc): malfoccupy(Wikipedia (/mob/living/silicon/ai/spawned))
  MiniSat Chamber Hallway APC (/obj/machinery/power/apc): ui act("occupy", /list (/list), /datum/tgui (/datum/tgui), /datum/ui_state/default (/datum/ui_state/default))
  /datum/tgui (/datum/tgui): Topic("src=%5B0x21007912%5D&action=oc...", /list (/list))
  Cyberboss (/client): Topic("src=%5B0x21007912%5D&action=oc...", /list (/list), /datum/tgui (/datum/tgui))
```
