### ISSUE TITLE
Meteor shields cant be deployed by hand

### ISSUE THREAD

**Issue by Shadowlight213** [tgstation/tgstation#23027]
Using an empty hand on them doesn't do anything.
@ChangelingRain

**Comment by Firecage** [comment]
@Shadowlight213 By meteor shields, do you mean those sattelites from cargo for Station Goal?

**Comment by AnturK** [comment]
Can't reproduce for station goal satellites.

**Comment by Shadowlight213** [comment]
It is the station goal satellites.
@kevinz000 was there when we ran into this.
The map was deltastation btw.

**Comment by ChangelingRain** [comment]
What feedback did you get, if any?

**Comment by Shadowlight213** [comment]
@ChangelingRain none.

**Comment by coiax** [comment]
I can confirm, I had this bug as well. The only way to activate them was via the computer, and the numbers aren't visible through examine so it was a crapshoot to activate them.

TBH, all of the station goals seem to be maximum buggy and because of their high costs and inconsistent presence, a lot of stuff is slipping through the radar. I'd suggest that we enable all station goal crates, possibly in its own cargo tab.

**Comment by Kromgar** [comment]
They should just be orderable for free and show up on the shuttle at round start. Having to pay huge amounts of money for this shit makes cargo not order it because they want shotguns

**Comment by YakumoChen** [comment]
the point of the goal though is that it takes a huge amount of resources... 

Especially the meteor shields since the ONLY cost is cargo points. Cargo should just suck it the fuck up and mine more plasma.
