### ISSUE TITLE
People being cloned twice with a multiple pods setup

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#23501]
@Cyberboss Saw this on basil, some guy ended up occupying both pods. One of the bodies produced was catatonic.

**Comment by Cyberboss** [comment]
Feature?

**Comment by XDTM** [comment]
True cloning, now we need one to be the evil twin

**Comment by AnturK** [comment]
Is this automatic or only on user error ? If the former this is a bug.

**Comment by Cyberboss** [comment]
I know for a fact you can't clone the same record twice. You could rescan
the body and then clone it twice, leading to this.

On Jan 30, 2017 12:19 PM, "AnturK" <notifications@github.com> wrote:

Is this automatic or only on user error ? If the former this is a bug.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tgstation/tgstation/issues/23501#issuecomment-276125799>,
or mute the thread

**Comment by coiax** [comment]
I saw a guy get two bodies pushed out, so it happens in some circumstances. I was only observing, so I can't tell you more than that.

**Comment by Time-Green** [comment]
![schermopname 404](https://cloud.githubusercontent.com/assets/7501474/23176065/d127953e-f861-11e6-8612-f8c5b40f3705.png)
Absolutely a feature.

**Comment by Cyberboss** [comment]
REPRO STEPS

**Comment by Time-Green** [comment]
>get multiple autocloners
>scan yourself in all of them
>beat yourself to death
>profit

**Comment by lzimann** [comment]
Fixed on #25230
