### ISSUE TITLE
Round stats being duplicated? 

### ISSUE THREAD

**Issue by nfreader** [tgstation/tgstation#23517]
https://atlantaned.space/newSS13tools/stats/viewRound.php?round=65736  
https://atlantaned.space/newSS13tools/stats/viewRound.php?round=65737
The data being reported for these rounds is the exact same (verified with a `sha1` hash). 

https://atlantaned.space/newSS13tools/stats/viewRound.php?round=65720  
https://atlantaned.space/newSS13tools/stats/viewRound.php?round=65721  
The data here is almost the exact same, but eerily similar.

https://atlantaned.space/newSS13tools/stats/viewRound.php?round=65730  
https://atlantaned.space/newSS13tools/stats/viewRound.php?round=65731
Ditto

Might be a continuation of #23396

**Comment by Jordie0608** [comment]
I suspect this is because the feedback data is saved during `world/Reboot()` before the check for if a restart was cancelled by admins: https://github.com/tgstation/tgstation/blob/master/code/world.dm#L212
This suggests what might've happened is the data was saved, restart was cancelled and then it was saved again in the next restart.
Unfortunately this only explains the second and third examples, I'm not sure how two restarts would've happened in the same second for the first example. But it must've since the round ID was incremented per when `save_all_data_to_sql()` is called https://github.com/tgstation/tgstation/blob/74e4acd827a89a45d17806316fe8cb02fb69b1f7/code/modules/research/message_server.dm#L310
More testing is likely needed.

**Comment by ChangelingRain** [comment]
This happened with another round;
https://atlantaned.space/newSS13tools/stats/viewRound.php?round=65760
https://atlantaned.space/newSS13tools/stats/viewRound.php?round=65761

I was there; there was a map change happening, so the reboot delayed itself.
