### ISSUE TITLE
[Deltastation] Janitor / custodial office still dropping in temperature

### ISSUE THREAD

**Issue by Iatots** [tgstation/tgstation#23563]
Changelog says merged on 30.1.2017 but on server revision 31.1.2017 it's still happening.

**Comment by Tofa01** [comment]
I have looked into this i have not been able to track the cause of this down though yet. My leading hypothesis is that upon launching Dream Daemon with Deltastation compiled to run many build_pipeline errors occur an example of which would be this:

"## WARNING: build_pipeline(): /obj/machinery/atmospherics/pipe/simple/supply/hidden added to a pipenet while still having one. (pipes leading to the same spot stacking in one turf) Nearby: (143, 65, 1)"

If you go to this turf you will find a stacking pipe i believe that this may be causing Atmospherics disturbances on the station. There are clearly many of them because shortly after these errors start appearing a message appears that looks like this: 

"## WARNING: build_pipeline(): further messages about pipenets will be supressed"

I am looking to fixing these errors but it is a very tedious project and may not even be the cause of this issue.

**Comment by Poojawa** [comment]
There's a button under the mapping tab called 'check plumbing' that will list all unconnected/doubled pipes. You'll need to enable all debug verbs. Then just search out whatever turf location and delete/add pipes to it.

**Comment by Tofa01** [comment]
If you would like go for it, it should be a simple fix its just a bit tedious.

**Comment by Poojawa** [comment]
Found the problem with the temperature, several floor tiles are set to 2.7 not 293.15

**Comment by Tofa01** [comment]
Ahhh, i see it now ill go ahead and release a PR for it shortly unless you are already working on it?

**Comment by Poojawa** [comment]
Could do, I also fixed a ton of the pipes as well, so I'll give it a whack with the compiler tools so I don't break the everything.

**Comment by Tofa01** [comment]
Cool, just remember to run prepare maps before editing and mapmerge to TGM when done and you should be good to go good luck!
