### ISSUE TITLE
Changelog html file has a lot of names at the top

### ISSUE THREAD

**Issue by JJRcop** [tgstation/tgstation#24076]
![](https://cloud.githubusercontent.com/assets/5211576/22898893/f10433d8-f1f6-11e6-8703-3fad2ce5950a.png)

It kinda skirts around it by saying "active GitHub contributors" but those names are still there. It's not *that* bad but I guess we should either update the list to contain notable coders or scrap the list. Maybe replace it with just the maintainers along with a message thanking all contributors.

It is pretty old.

**Comment by RemieRichards** [comment]
Still annoys me I got my maintainership like a week after we decided to stop adding names, it's why Miauw is on there and I'm not, he got his just a little before me.

**Comment by lzimann** [comment]
just go rogue and add yourself there :^)

**Comment by Cyberboss** [comment]
Credits are a meme, delete them

**Comment by Cyberboss** [comment]
Or generate properly formatted credits from the changelogs

**Comment by Jordie0608** [comment]
This has been discussed before. Those credits are there, among other reasons, to preserve a proper list of contributors prior to Git as oft emails included in the google-code commit logs are non-indicative. It's not updated anymore because the list of contributors on Github will always be more comprehensive and isn't hard to reach. Hence we decided to just leave the header template as is.
