### ISSUE TITLE
Putting items into bodies' hands deletes said item.

### ISSUE THREAD

**Issue by Onule** [tgstation/tgstation#24236]
Try putting anything into a corpse's hands. It'll get deleted.
This will happen if the body is laying down on the ground.

**Comment by XDTM** [comment]
@cyberboss?

**Comment by Cyberboss** [comment]
BUT, WHO DOES THIS? @lzimann

On Feb 18, 2017 12:12 PM, "XDTM" <notifications@github.com> wrote:

@cyberboss <https://github.com/cyberboss>?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tgstation/tgstation/issues/24236#issuecomment-280859470>,
or mute the thread

**Comment by Cyberboss** [comment]
This only happens to dead people
