### ISSUE TITLE
Changeling cloning

### ISSUE THREAD

**Issue by DanteRU0312** [tgstation/tgstation#24385]
Problem Description: If changeling revives themselves during the cloning, it causes some buggery.

What did you expect to happen: I expected my cloned body to be catatonic and run around in my previous body.

What happened instead: I was running in maint tunnels and suddenly got placed into my cloned body. My old body became catatonic, later i found it and took my stuff from it. What's better, you can absorb it and get a DNA point.

Why is this bad/What are the consequences: It's just really damn weird.

Steps to reproduce the problem: Die as a ling, wait until you get stuffed into cloning instead of defib, revive while your new body is creating.

Server: Bagil

Revision: Server revision compiled on: 2017-02-23

**Comment by Repukan** [comment]
Might be related to #22528

**Comment by Kromgar** [comment]
Not might is its the same shit. The cloners pull your soul out of yoru fucking body

**Comment by Repukan** [comment]
Calm the fuck down

**Comment by Sligneris** [comment]
There really should be a way to opt out of a started cloning - the same thing happened when I was saved in the autocloner and wanted to transfer my consciousness to a headslug - instead of staying a dead headslug and waiting to respawn as a ling, I popped out of a cloner and found a playerless monkey where I was supposed to be a ling. 

It's a really strange effect.

**Comment by kriskog** [comment]
You are immediately put in the new body now, and cant initialize cloning if you revived already.
