### ISSUE TITLE
Fluke ops implants

### ISSUE THREAD

**Issue by DanteRU0312** [tgstation/tgstation#24443]
Problem Description: X-ray implant(and possibly other implants too) has no autoimplanter.

What did you expect to happen: Expected it to come with autoimplanter.

What happened instead: Received the xray eyes with no implanter

Why is this bad/What are the consequences: Something was changed in term of implants, and someone forgot to update the description, saying, that it comes with autoimplanter. You can't even use it with autoimplanter.

Steps to reproduce the problem: Become an op, buy x-ray eyes,  

Server: Bagil

Revision: 2017-02-25

**Comment by Mindustry** [comment]
Not a bug. You have all the tools and even an operating table in the ship.

**Comment by DanteRU0312** [comment]
>someone forgot to update the description

**Comment by GunHog** [comment]
It may not be a bug, but it _is_ an issue. Autoimplanters exist so that Nuke Ops can get their implants installed without wasting 10 minutes fumbling around with each other. Nuke Ops, being team antagonists, are able to trust each other at all times, therefore there is no risk component (besides incompetence) involved in the surgery.

**Comment by PKPenguin321** [comment]
This is a bug. I think this might be a dupe as well. See: https://github.com/tgstation/tgstation/blob/master/code/modules/uplink/uplink_item.dm#L1141

The organs are supposed to spawn with an autoimplanter should their path match with cyberimplants, but eye implants are not cyberimplants since the eyes update.

**Comment by coiax** [comment]
This is @KorPhaeron's fault, kinda.

**Comment by CPTANT** [comment]
Had the same issue with the cnc rebooter, it came without the stated auto implanter.
