### ISSUE TITLE
Cloning Pod Autoprocess clones same person in all pods 

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#24480]
Die, have multiple pods, and have the cloner on autoprocess. The cloner will clone you in all the available pods. 
edit: Might only work if you scan the person after cloning them with autoprocess, since I just saw it work.

**Comment by kevinz000** [comment]
goddamnit @coiax

**Comment by coiax** [comment]
Multiple pods was @Cyberboss, unless you are memeing.

**Comment by coiax** [comment]
Anyway, what I think is happening is that since you don't "own" the growing clone body until it's ejected, the cloning data sent to the pod isn't rejected.

It's also sending the cloning data multiple times, possibly relating to "ownership" of the clone body.

One thing we could definitely do is make it that a cloned person "owns" the cloning body immediately, but then ghost them out of it. They can still reenter if they want (and they only get one free ghosting), but that should fix some problems, methinks.

**Comment by BeeSting12** [comment]
Yeah, don't think this would be an issue when you were put back into your body during cloning.

**Comment by Kromgar** [comment]
God damn it stop rippign ghosts out of their bodies this still majorly fucks with liiiings reeee

**Comment by Cyberboss** [comment]
#23535 is closable now?

**Comment by XDTM** [comment]
Should be fixed with #25230

**Comment by Cyberboss** [comment]
@lzimann
