### ISSUE TITLE
New lights cannot be placed in the base construction area

### ISSUE THREAD

**Issue by Hatfish** [tgstation/tgstation#24658]
See title.  Attempting to place a fixture returns a message that light fixtures cannot be placed in this area.
Probably not related to any testmerged PRs, but they're #24171 and #24504

**Comment by GunHog** [comment]
It is because the Aux Base is technically a shuttle, which are always lit (until it lands at lavaland for some reason) and powered. Power, pipes, and other things bug out when moved.

See this for explanation of why you cannot place lights or other wall frames: https://github.com/tgstation/tgstation/blob/a9be4e68d08697aad2bab6c2dbad955e733fadc6/code/game/objects/items/apc_frame.dm#L22

A refactor of wall frame, shuttle, or power code is necessary for a proper fix.

**Comment by lzimann** [comment]
This might change with the lightning refactor, but I'm not sure if shuttles having proper lightning is being added there.

**Comment by GunHog** [comment]
My testing of /vg/ lighting reveals that shuttles and the base will be always lit, and the light will even shine through the windows to light the surrounding basalt tiles. It looks pretty cool. I will look into this more after /vg/ lighting is merged, and see about the power thing as well.

**Comment by Hatfish** [comment]
Probably "fixed" by Joan's dynamic shuttle lighting PR.

**Comment by ChangelingRain** [comment]
It was not!

**Comment by Hatfish** [comment]
Oops.
