### ISSUE TITLE
Airlock cycling does not work properly anymore

### ISSUE THREAD

**Issue by Hamfam77** [tgstation/tgstation#24800]
Maps so far that I've seen have this issue are Meta, Box, and Delta for Virology and Xenobio. 

When clicking on the button to cycle the airlocks (not the access panel, the button itself), it doesn't respond. Clicking the button with no ID equipped will generate the 'Access Denied' message, but otherwise no response.

**Comment by TehPear** [comment]
Controller variable is returning null in some cases on the access buttons, which can be easily fixed by admin online. 

Oddly only some access buttons seem to be doing this. Meta's Xenobiology will be broken but virology will work. 

Box's virology, the outer(button used to go into virology from medbay) access button works, but the inner virology access button has controller = null

I have not encountered issues on Delta as of yet or seen any variation to this.
