### ISSUE TITLE
Weird Luxury Shuttle bugs

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#24843]
![image](https://cloud.githubusercontent.com/assets/609465/23715905/33bfbc7e-0426-11e7-991a-e1400bb7fe4f.png)

I don't even know where to begin. But I blame @Cyberboss, of course.

**Comment by Cyberboss** [comment]
Is anything testmerge?

**Comment by coiax** [comment]
No.

**Comment by PKPenguin321** [comment]
From the other issue,

>That's where the swimming pool is.

probably a sprite issue

**Comment by KorPhaeron** [comment]
@Cyberboss you already fixed templates right

**Comment by Cyberboss** [comment]
Wouldn't have fixed this I think. Is it still happening?

On Apr 6, 2017 12:04 PM, "KorPhaeron" <notifications@github.com> wrote:

@Cyberboss <https://github.com/Cyberboss> you already fixed templates right

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tgstation/tgstation/issues/24843#issuecomment-292222464>,
or mute the thread

**Comment by Buggy123** [comment]
Didn't we get rid of shuttle variants? Can't we close this now?

**Comment by KorPhaeron** [comment]
We did not

**Comment by ninjanomnom** [comment]
I can't reproduce this and this should be fixed by my dock rewrite. It can be closed now
