### ISSUE TITLE
ORM becomes impossible to interact with

### ISSUE THREAD

**Issue by Slignerd** [tgstation/tgstation#24967]
Under some circumstances (but ridiculously often), ORM can become impossible to interact with - you click on it, and nothing comes up.

When that happens, nothing short of deconstructing it and assembling it again fixes it. And, you know, losing all unclaimed points and minerals.

**Comment by kevinz000** [comment]
Minerals get dropped but points don't, believe this is related to the @coiax  stacking bugs.

**Comment by Sligneris** [comment]
@coiax should not be allowed to ever touch stacking again. It kind of also broke floor tiles. Two different 20 floor tiles stacks combined into a 21 floor tiles stack instead of 40.

**Comment by kevinz000** [comment]
@Sligneris by that logic tbh i wouldn't be allowed to touch 80% of the code and 75% of the adminbuttons and probably 90% of the game lmao.

**Comment by Profakos** [comment]
Is this still an issue, now that ORM uses materials instead of stacks?

**Comment by vuonojenmustaturska** [comment]
I've never seen this despite exclusively playing shaft miner for months, however I started playing after the code involved was changed so it's possible it the bug was inadvertently fixed. I'm going to close this, if anyone is still suffering from this issue ping me on discord or IRC and I'll reopen and start fixing.
