### ISSUE TITLE
Invisible robotic and augmented limbs

### ISSUE THREAD

**Issue by ram001400** [tgstation/tgstation#25586]
Like the title says, the robotic limbs not including ones made from the fabricator, its only limbs that have been or are attached to people, are completely invisible.  On the floor they don't show up at all but their names do show up if I right click the tile they are on.  On people, it just looks like they're missing the limb, but the vars (unedited) say the robotic limb is there.  This has been going on for me through different commits.  So far this has been for each body part.  In the picture the two invisible limbs are invisible. with their visible counterparts.
![invisible limbs](https://cloud.githubusercontent.com/assets/13338320/24430308/ebcb5158-13e3-11e7-8538-a5da02a44501.png)

**Comment by YakumoChen** [comment]
why do we even have these when robotic limbs do the exact same thing?

**Comment by Profakos** [comment]
I have conducted experiments. It seems to be the cause is setting the limb's state to organic without changing its icon, so it won't find the image. 
https://github.com/tgstation/tgstation/blob/061cd1c6920f22a44cca4fa501f57d33afb82dbd/code/modules/surgery/bodyparts/bodyparts.dm#L324

Also the surplus right leg has an incorrect icon state.
