### ISSUE TITLE
Jump boots don't protect against lava

### ISSUE THREAD

**Issue by 4dplanner** [tgstation/tgstation#25858]
On using jump boots to jump over lava I was immediately set on fire - I reproduced this by attempting on a different lava river. I was told this was not intended behaviour ( did not test chasms).

**Comment by Repukan** [comment]
Did you press any movement keys during the jump?

That tends to break it earlier

**Comment by MMMiracles** [comment]
Jump boots do not protect against lava because all they do is throw the mob x tiles. 

A lava-protection upgrade was planned but the only way I knew of doing it was either making throwing nullify lava (which is a huge balance thing), or a specific check on lava turfs to see if the person was wearing active jump boots, which was deemed too snowflake-y.

So, yeah. Useful for chasms only until someone makes throwing negate lava-burning.

**Comment by Repukan** [comment]
You can throw stuff without it burning tho?

That's how I use cubes to jump across rivers

**Comment by MMMiracles** [comment]
You're safe when throwing objects, mobs don't count in that check.

**Comment by XDTM** [comment]
That was changed, though, i'm pretty sure

**Comment by octareenroon91** [comment]
Thrown mobs still catch fire.

**Comment by Grazyn** [comment]
Who told you it isn't intended? I recall I was told it is actually intended last time I asked. It also prevents gulag prisoners throwing each other over the river

**Comment by factoryman942** [comment]
If you mount a borg which then throws you off by spinning you can cross lava without igniting :^)

**Comment by Repukan** [comment]
The only thing I mount are spessgirls

**Comment by vuonojenmustaturska** [comment]
@kevinz000 This can be fixed easily by giving the mob lavaproof before throw and removing it in the callback. In fact this is exactly how alien hunters do it.

**Comment by optimumtact** [comment]
Not going to be fixed because of the balance issues it causes
