### ISSUE TITLE
Freon still crashes servers!!

### ISSUE THREAD

**Issue by Cheridan** [tgstation/tgstation#25890]
AI and a couple engis freon-flooded the station, leading to a full proc lockup. No movement, no functioning buttons. LeoZ had to hard-reboot the server.

**Comment by GunHog** [comment]
Do not forget the milestone!

**Comment by ChangelingRain** [comment]
freon was a m i s t a k e

**Comment by Kromgar** [comment]
#removefreon

**Comment by optimumtact** [comment]
No profile proving it's freon, no runtimes proving it's freon, in fact no proof of anything other than you flooded the entire station with gas and it caused atmos to lockup.

closing issue for being a shit bug report.

**Comment by KorPhaeron** [comment]
The server crashing on a regular basis when freon is used is merely coincidence

**Comment by optimumtact** [comment]
Come with proof or don't come at all Kor, 99% of bug reports on this tracker never get followed up on because nobody brings any useful information

**Comment by Iamgoofball** [comment]
i'm wondering about if this is just a core atmos bug because I've seen this happen after the release of OTHER meme gases (Freon/BZ/Reagent Gas when that was a thing)

**Comment by duncathan** [comment]
@Iamgoofball well freon is horribly slow regardless; it has ridiculous high proc call overhead because it calls a proc on fuckin everything it touches
I seriously doubt BZ would've approached the scale of this
reagent gas was a terrible idea from the very beginning and i'm sure it was not implemented very efficiently either.

freon has the unique property of reacting on any tile where it's present - every other reaction (barring water vapor i guess) has some sort of other requirement, like temperature or thermal energy or other gases that limits its use. that means that flooding freon by nature will be considerably more expensive than flooding say plasma, since plasma won't start reacting until it ignites, and it's a faster reaction.
I'm very confident that this is mostly a freon problem. Shitty implementation is one of the many reasons I want to see freon gone eventually.
