### ISSUE TITLE
Parallax looks dumb on a high FPS

### ISSUE THREAD

**Issue by Tacolizard** [tgstation/tgstation#25948]
Parallax seems to animate each time you move between tiles, not based on frame rate. This means that if you turn up your framerate then parallax appears to jump around instead of smoothly animating as you walk.

**Comment by MrStonedOne** [comment]
Gonna need a video, it looked fine for me on 100fps

**Comment by Jalleo** [comment]
This maybe a thing with lag due to the updating from server to client.

**Comment by kevinz000** [comment]
@MrStonedOne isn't an issue for me :P

**Comment by Tacolizard** [comment]
to clarify, the parallax between the ship and space is smooth, but the individual space layers jump when they animate to move over each other: https://vimeo.com/213559154

**Comment by Cyberboss** [comment]
I believe @Tacolizard fixed this by adding another layer

**Comment by Tacolizard** [comment]
@Cyberboss I did not fix this

**Comment by timothymtorres** [comment]
The related video that was posted for this issue doesn't seem to indicate anything is wrong.  Also there is not a clearly defined "problem" for this issue report.  Marking this for cleanup.

**Comment by MrStonedOne** [comment]
Let me help.

They had 100fps and then moved in walking speed, causing them to move very slowly going to the next tile. However, the paralax layer move happens the moment they start moving and only takes a pixel to do so, so it looks like a "jump" that happens at the start of the move.

the issue boils down to parallax code not taking mob movespeed/movedelay into account to smooth out the transitions. Given these are 1 to 4 pixel large moves. I don't think we ever will, since animating this has a non-trivial cost and for most people, will be entirely unnoticeable. (see #59759)

**Comment by timothymtorres** [comment]
Thanks for the clarification.  So this issue seems redundant and smells more like a feature request.  The `Cleanup` label will auto-close this in a few days unless you want me to keep it open @MrStonedOne

**Comment by LemonInTheDark** [comment]
Resolved? by #66567
