### ISSUE TITLE
Catgirls who go for captain and become human show up on sec records as a catgirl

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#25973]
EDITED FOR PICTURES
https://gyazo.com/fd922e6db219f18d9fe9b27672c95e9b

**Comment by coiax** [comment]
Just make catperson its own race already.

**Comment by BeeSting12** [comment]
she was also a shit captain lmao

**Comment by kevinz000** [comment]
intended

**Comment by octareenroon91** [comment]
Seems humorous and tolerable.

**Comment by Bawhoppen** [comment]
catgirls
>GIRLS

**Comment by factoryman942** [comment]
Nyaa

**Comment by FantasticFwoosh** [comment]
Hypocrisy for them being human mutants, but also barred from round-start station roles (features auto removed) if they get ANY special mention which is a slap in the face for people who just want mutants to be classifiable like angels or cat-people their own thing rather than human powercreep meme clique meme.

**Comment by Razharas** [comment]
![image](https://media.tenor.co/images/9350689c6ea30bb140032470afcb1d27/tenor.gif)

**Comment by Bawhoppen** [comment]
My """""joke""""" sounded better in my head, I apologize sincerely for my poor rationale in the coderbus.

Also it is a bug, is it not?
