### ISSUE TITLE
Sending a Syndicate Briefcase full of cash to centcomm does not add any supply points.

### ISSUE THREAD

**Issue by Expletive** [tgstation/tgstation#26280]
Server Revision: 3952aed40bf369618cf6a62012eeb5d72382ad08

Today while traitoring as QM, I spent 6 TC on an Emag, 2 on an encryption key, and then spent the remaining 12 on briefcases full of cash. I put them in a closed crate on the shuttle, sent the crate out, and then received 0 supply points for the cash, instead of the 5000 each.  I ended up stealing all the minerals instead to buy my null crates. The gist of it seems to be that they don't add supply points unless you take the cash out of the briefcase. This is pretty cumbersome when you buy 12 of the damn things.

**Comment by Profakos** [comment]
Spacecash has no export value. You have to put the money into the bank machine.

**Comment by Jalleo** [comment]
Yeah they dont check contents inside contents because of reasons.

**Comment by Profakos** [comment]
No, the cause is that money exports were removed in #19947, intentionally.  I have also run tests, and items in crates are exported fine.

**Comment by Jalleo** [comment]
That aspect I forgot about. (Mainly because I wasnt around after it got closed and then reopened.)

**Comment by octareenroon91** [comment]
Courtesy reminder: QM office has an export scanner. I think it's in the locker.

**Comment by ExcessiveUseOfCobblestone** [comment]
@optimumtact not a bug

**Comment by BeeSting12** [comment]
The money in the brief case does not count toward the export. Taking the money out and putting it in a crate does give you the proper amount of money. 
Source: Wasted 14 TCs one round because I tried this.

**Comment by Profakos** [comment]
No, not even putting spacecash in a crate would grant you credits, tested it earlier.

**Comment by jughu** [comment]
It did a litteraly weeks ago

**Comment by Profakos** [comment]
Are you sure it wasn't coins? Coins have a related export datum. 

Further, more detailed test results: 
Using the QM's export scanner directly on spacecash gives the following message: "Scanned the space cash, no export value.". This uses the same proc as selling an item. 

I have also put a diamond coin (export value of 500), put it into a syndie briefcase, and put it into a closet. The result was 'Scanned the emergency closet, value: 500 credits (contents included)'.  Sell result was '+500 credits: Received 400 cm3 of diamonds. '.

The true fix to this issue is to make it somehow more obvious that money has to be deposited into the vault's Bank Machine.

**Comment by octareenroon91** [comment]
Maybe have Centcom send back (most) of the cash back, stacked?

**Comment by ExcessiveUseOfCobblestone** [comment]
no the workers there will take your space cash because they get paid about as much as we do [see: none]

**Comment by AnturK** [comment]
Not a bug, balance/visibility issue.
