### ISSUE TITLE
Alien embryos deal 70 toxin damage at stage 4 and again at stage 5.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#26431]
I don't know if this was an intentional change or WHY this was changed, but if you reach stage 4/5 of infection you will begin taking MONSTROUS toxins damage. 70 at the rate of 10/second when you reach stage 4, and again at stage 5. You seem to continue taking ticks of 10 toxins every now and again, I'm not sure what's happening here, as I'm not seeing any reagents in the person.

I won't mark this as a bug yet as I don't know if it is one, or just an unmentioned change?

**Comment by coiax** [comment]
WJohn, it's a side effect of me changing how xeno ghost selection worked.

Previously, the embryo would advance to stage 5, select a non-afk ghost and then burst. Otherwise, if it couldn't find anyone in that single tick, it would do a single 10 toxin damage, and then drop back to stage 4.

Now: When you hit stage 5, you stay on stage 5 while the deadchat poll is in progress, and then it drops to stage 4 if it doesn't find anyone. But this takes probably 10 seconds, which is, I'm going to hazard a guess here: 7 ticks of the organ.

Make sense?

**Comment by WJohn** [comment]
Huh. So it's intended, just a bizarre set of effects caused by looking for a suitable ghost? Alright then, closing.
