### ISSUE TITLE
Omega Station doubled up turfs

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#26476]
![](http://i.imgur.com/N5foQPg.png)

This RX charge is unable to be removed, same problem as #25124

Omega station likely has a lot of these, because it was created before antur's floor changes with warning lines. There's also a number of missing floor textures in xenobio and R&D due to this.

**Comment by coiax** [comment]
So there are two turfs on the same tile?

**Comment by WJohn** [comment]
Yes, same as last issue. This happens when you use a turf with transparency on top of another, such as how warning tiles functioned before they got turned into decals. Antur's warning tile turfs to decals tool will likely have us scouring for these bugs for a long time to come.

**Comment by Penguaro** [comment]
@wjohn I'm trying to replicate the problem so I can work on a fix. Can you suggest steps to reproduce this?
 Was the charge set there? Dropped there? Also, do you know the name of the back-end name of the device in the picture? I've tried with other explosives and have been able to manipulate each one in the round so far from that specific tile. Aside from a TAG variable used there, I can't seem to find anything else unique to that square.

**Comment by Penguaro** [comment]
@WJohn I'm trying to replicate the problem so I can work on a fix. Can you suggest steps to reproduce this?
Was the charge set there? Dropped there? Also, do you know the name of the back-end name of the device in the picture? I've tried with other explosives and have been able to manipulate each one in the round so far from that specific tile. Aside from a TAG variable used there, I can't seem to find anything else unique to that square. (Note I redid this since I didn't tag you properly before)

**Comment by Penguaro** [comment]
There are double turfs on that station but that tile isn't one of them. I suspect there may be an issue with that particular explosive but I don't know what the object is to test for it. If anyone can shed light, I'm happy to investigate further.
