### ISSUE TITLE
Cigarettes and cigars work in no-oxygen environments

### ISSUE THREAD

**Issue by coiax** [tgstation/tgstation#26487]
I've seen plasmamen smoking cigarettes in plasma only rooms.
I've seen people smoking cigarettes in space.

MUH REALISM. Also, for balance, they really should produce CO2.

**Comment by Sligneris** [comment]
> I've seen plasmamen smoking cigarettes in plasma only rooms.
> I've seen people smoking cigarettes in space.

Lighting cigarettes in plasma rooms and removing your internals in space? That's hardcore.

**Comment by Armhulen** [comment]
Plasmamen are the space beasts that come to kill everything, donchu get it?

**Comment by Robustin** [comment]
This is the kind of stuff that prevents real issues from getting addressed.

**Comment by coiax** [comment]
Fuck off Robustin

**Comment by FantasticFwoosh** [comment]
This applies to wooden torches (crafted with log & some dried grass) & some other lighting objects too.

That is unless you want to remove the oxygen restrictions of the bonfire, which i believe this can be rooted in a realism consistency arguement (bonfires can't be lit up in oxygenless enviroments)

**Comment by Robustin** [comment]
This issue is going to stay here until the end of time or until someone spends an unecessary amount of time and server processing having all the flammable shit constantly making sure its in an oxygenated environment, and even that "fix" will inevitably spawn 50 more issues where people complain that they can't smoke inside a mech while in space or some shit. 

Or we just say Nanotrasen was smart enough to provide space-age oxidized material in its (intentionally) flammable equipment and have this super duper nobody-cares edge case put to bed 4ever.

**Comment by BeeSting12** [comment]
@optimumtact 
Can you close this because of what @Robustin said?

**Comment by optimumtact** [comment]
no
