### ISSUE TITLE
Lights missing on backup shuttle

### ISSUE THREAD

**Issue by Bawhoppen** [tgstation/tgstation#26508]
![ss 2017-04-23 at 07 44 26](https://cloud.githubusercontent.com/assets/6510293/25319168/49c272ec-2860-11e7-95fb-202cf03263fc.png)

**Comment by WJohn** [comment]
I don't think that shuttle even works, and I've never even seen it used. I don't think it's worth noting as an issue but whatever.

**Comment by octareenroon91** [comment]
It works, it happens.

**Comment by coiax** [comment]
I've said this before and I'll say it again. The backup shuttle exists as a code safety in case something fucks up, because shuttle function is vital to normal round ending. It is not supposed to be used.

The fact that it's been used a great deal probably speaks to some horrendously broken shuttle manipulator code I need to sniff out.

**Comment by octareenroon91** [comment]
The asteroid with rockets on has shown special amounts of trouble, including stalling and losing all floor on launch

**Comment by BeeSting12** [comment]
I'll get this in a couple minutes

**Comment by coiax** [comment]
IT'S NOT SUPPOSED TO BE A REAL SHUTTLE REEEEEEEEE

**Comment by Bawhoppen** [comment]
I see it used occasionally

**Comment by coiax** [comment]
IT'S NOT SUPPOSED TO BE
