### ISSUE TITLE
Dual wielding single-fire shots is HORRENDOUSLY inaccurate, but burst-fire shots are fine.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#26510]
![](http://i.imgur.com/HR7gOqk.png)

![](http://i.imgur.com/pqvQ0DB.png)

Retro laser gun (behaves identically to regular laser gun, but with 10 shots instead of 12)

And C20r.

Both these guns are perfectly accurate when only one is fired.

ALL energy weapons suffer something like 30+ degrees deviation. Bullet weapons never seem to suffer more than 5 degrees.

Bulldog shotguns are a perfect example of both in action. If they have taser rounds, they're horrifically inaccurate, if they have slugs, they're fine. If they have buckshot? No noticeable change in accuracy.

I don't know if this is a bug or some sort of really bad balance decision/oversight.

**Comment by Bawhoppen** [comment]
GIFs:
![c20rfiring](https://cloud.githubusercontent.com/assets/6510293/25320190/9d42007c-286a-11e7-8d99-affa34c48d0d.gif)
![laserfiring](https://cloud.githubusercontent.com/assets/6510293/25320196/a6f109a6-286a-11e7-9973-fb84fe298c9a.gif)

**Comment by Repukan** [comment]
I feel that since energy weapons have technically unlimited ammo, they should keep the higher degree of innacuracy

**Comment by octareenroon91** [comment]
> I feel that since energy weapons have technically unlimited ammo, they should keep the higher degree of innacuracy

Energy guns take time to recharge. Bullets can be mass-produced. Let's see what turns up in searching the code/PRs.

**Comment by Repukan** [comment]
And you can upgrade the chargers too. You need metal and manually putting in the magazines and clips on the ballistics, and some of them don't have printeable ammo. 

Although you can recharge ballistics faster, and if you use a shotgun or other you can reprint the ammo, all energy weapons can be recharged in the same standard charger. If you're shit out of luck you can't get new ammo for certain weapons (Bulldog, Sniper rifles, Grenade Launcher, etc)

**Comment by WJohn** [comment]
Recharging energy guns is a matter of having a specific place secured while you hunker down.

Reloading ballistic guns is simply slapping in a new magazine, taken from your backpack. You can do it anywhere.

In any case, that's not a good argument for balance, combat is handled in short bursts of high intensity. If the guy who's able to fight for those high intensity moments for longer (and put out more bullets, ALL of which hit much more accurately), then he's at a huge advantage. Out-of-combat versus in-combat are not good counter balances.

**Comment by Repukan** [comment]
You can wrench out rechargers and wrench back real fast.

You don't even need secure places for them, see blob rounds.

And whoever's using ballistics needs that advantage. At hand the ones using ballistics the most are Nuke ops, and again, the strength of their weapons is limited by the amount of shots they get. In tactical sense, the station or whoever has energy weapons wins by virtue of time due to how easily feasible it is to move your charger closer or finding a charging spot is.

A ballistics user has to have a safe space with a protolathe or autolathe, metal and keep his magazines in order to charge his weapon. If you want to say "It's fast to reload" then I'd have to point at the fact that even reloading ballistics takes more in average than energy weapons.

Most shootouts situations aren't even that fast. You can find yourself in a situation were you and the other person are locked into covers and whoever manages to land more shots wins. Both ballistics and lasers have advantages depending on context, and I believe given the quirks using ballistics has, this should not be changed to make both types of weapon equal.

**Comment by FantasticFwoosh** [comment]
Dual wielding a advanced plasma cutter & a KA has similar effects, is it only when 1 laser is equipped or would having a ballistic in 1 hand and a laser in the other stablise?

**Comment by SgtxRootbeer** [comment]
Repukan, realize that laser weapons shouldn't produce any kickback. Ballistics should produce a lot of kickback.
Combine that with the fact that ballistics can have their faster reload without prep time or prep work (dragging a recharger around, upgrading it, etc.)

**Comment by Robustin** [comment]
This feels like a balance discussion now but I'll throw in my 2 cents and say that dual-wielding energy spread is abhorrent. Like its a bad joke to punish anyone who is foolish enough to try it.

**Comment by PKPenguin321** [comment]
I've had lots of success with energy spread in the past. I think making it more accurate would be too strong since it's already not that bad

**Comment by WJohn** [comment]
>Not that bad
Have you not seen the gifs? They're almost impossibly inaccurate.

Yes, occasionally if you're lucky

**Comment by WJohn** [comment]
Correction, it's not ENERGY weapons which are accurate, it's SEMI AUTO -- single fire. Burst weapons, which fire multiple times, are very accurate with dual wielding. Single fire is NOT. It just so happens that we have like 0 burst LASER weapons, so I didn't catch that. My bad.
