### ISSUE TITLE
Syndicate Elite Hardsuit helmet does not protect against aliens

### ISSUE THREAD

**Issue by Work4Bots** [tgstation/tgstation#26560]
Version: 164f7f9b5431ac0e32987313fc896fed46a952bd 

The Syndicate Elite Hardsuit Helmet is fully ignored by alien facehuggers whilst in combat mode.

**Comment by octareenroon91** [comment]
NODROP but not spaceproof!

**Comment by GunHog** [comment]
Maaaaaybe because **your face is physically exposed**?

**Comment by WJohn** [comment]
Strange that it's not inheriting the protection from parent rig suits.

**Comment by GunHog** [comment]
Your. Face. Is. Exposed. This is not a bug! Combat mode is supposed to remove thickmaterial and stuff for a speed boost.

**Comment by octareenroon91** [comment]
Doesn't the hardsuit toggle to a faster but exposed mode?

**Comment by GunHog** [comment]
Yes, just like its parent, the normal Syndie hardsuit. The issue is of _sprites_ more than the code. The normal Syndie hardsuit **exposes the face** of the user, but the sprite for the elite version does not reflect this. In my opinion, the sprite should just be changed to raise the visor or something when in combat mode.

**Comment by WJohn** [comment]
Oh! So it means specifically when it's in combat mode, which lacks showing the face. This is a sprite issue then, not a bug.
