### ISSUE TITLE
You can't fill a welding tool with a beaker of welding fuel, but can magically refill it with a fuel tank

### ISSUE THREAD

**Issue by ma44** [tgstation/tgstation#26608]
Muh immersion

**Comment by GunHog** [comment]
How is this an immersion issue? The tools would have a safety port that exclusively connects with the tank in order to avoid leakage of fumes. If you tried to pour a beaker of welding fuel into a tool without an appropriate opening, you would just end up making a mess.

As a _gameplay_ issue, I agree that you should be able to fill welding tools with fuel, provided that the beaker contains only fuel. (Else you would get into weird situations)

**Comment by KorPhaeron** [comment]
What gun hog said
