### ISSUE TITLE
Every time a revenant reforms after dying, they get a separate round end entry/set of objectives

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#26620]
Leading to ridiculous spam like:

The traitors were:
JarekTheRaptor was revenant (860) the revenant and had their body destroyed
Objective #1: Absorb 385 points of essence from humans. Fail.
Objective #2: Hinder the crew while attempting to avoid being noticed. Success!
The revenant has failed!

JarekTheRaptor was revenant (793) the revenant and had their body destroyed
Objective #1: Absorb 389 points of essence from humans. Fail.
Objective #2: Damage and render as much of the station rusted and unusable as possible. Success!
The revenant has failed!

JarekTheRaptor was  the revenant and had their body destroyed
The revenant was successful!

JarekTheRaptor was revenant (379) the revenant and had their body destroyed
Objective #1: Absorb 455 points of essence from humans. Fail.
Objective #2: Cause as much chaos and anger as you can without being killed. Success!
The revenant has failed!

JarekTheRaptor was  the revenant and had their body destroyed
The revenant was successful!

JarekTheRaptor was revenant (818) the revenant and had their body destroyed
Objective #1: Absorb 351 points of essence from humans. Fail.
Objective #2: Damage and render as much of the station rusted and unusable as possible. Success!
The revenant has failed!

JarekTheRaptor was  the revenant and had their body destroyed
The revenant was successful!

JarekTheRaptor was revenant (157) the revenant and had their body destroyed
Objective #1: Absorb 367 points of essence from humans. Fail.
Objective #2: Avoid killing in plain sight. Success!
The revenant has failed!

JarekTheRaptor was revenant (604) the revenant and had their body destroyed
Objective #1: Absorb 351 points of essence from humans. Fail.
Objective #2: Cause as much chaos and anger as you can without being killed. Success!
The revenant has failed!

JarekTheRaptor was  the revenant and survived as revenant (604)
The revenant was successful!

**Comment by FantasticFwoosh** [comment]
Im quite sure this is because revenant cycles the players its given to when the revenant revives. It was supposed to go to someone else, but it went back to Jarek, refreshing the revenant's state, progress & renewing them as a seperate antagonist (from the revanant numbers, its a different one every time, a different antag)

Jarek must have been either the only ghost in the lobby or the only one with revenant antagonist enabled.

**Comment by Metacide** [comment]
Wait so you can't even kill grief ghosts?

**Comment by bgobandit** [comment]
ectoplasm reforms if not dealt with, this has always been the case

**Comment by 4dplanner** [comment]
Fwoosh, this is just not true - the issue is because ectoplasm creates a new revenant to put the client in instead of reviving the old one, but it specifically tries to grab the original client first.

R.client_to_revive = src.client //If the essence reforms, the old revenant is put back in the body

**Comment by bgobandit** [comment]
yeah exactly, and even if it did ask ghosts, the round-end report is clearly bugged in SOME way
