### ISSUE TITLE
Crowbaring the ore redemption machine when it has no power makes its density 0.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#26810]
What it says on the tin. The machine has to be depowered in order for you to crowbar it open and release its contents. Doing so will simultaneously make its density 0, so you can walk through it. Using the crowbar on it again won't fix it, neither will turning the power back on.

You can deconstruct/reconstruct it to fix this, though.

**Comment by Profakos** [comment]
I touched this machine last time. All i changed with regards to deconstruction was the I changed on_deconstruct() to call materials.retrieve_all(), and then call ..(). I'll take a look.

**Comment by Profakos** [comment]
A quick look says this proc https://github.com/tgstation/tgstation/blob/162ca92e51e81e8408c8914119b2e8e82dc23482/code/game/machinery/machinery.dm#L304   calls this one https://github.com/tgstation/tgstation/blob/162ca92e51e81e8408c8914119b2e8e82dc23482/code/game/machinery/machinery.dm#L304 , which sets density. I'll continue examining this later.

**Comment by Profakos** [comment]
Okay I couldn't stop myself, and the result is that the ore redemption machine should have an override for open_machine, probably.

**Comment by Profakos** [comment]
A lot of things has this issue, as it looks like that open_machine was intended for things you can hide in. Perhaps there is a need for a new flag, for the following things: 

- Gibber
- Holopad: holopads are already nondense so it isn't much of an issue but still
- Hydroponic trays
- Monkeyrecycler
- Ore Redemption
- Recycler
- Processor
- Seed Extractor
- Smartfridges
- Suit Storage Unit: if opened via the interface instead of a crowbar, it won't become nondense, but crowbar prying makes it so.

Somehow the processor and the gibber is not effected by this.
