### ISSUE TITLE
client New is all fucked:

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation#26924]
client New is all fucked:

cid randomzier checks are failing and not redirecting
byond account age isn't even working at all
some people just can't connect
oh, and the ready up button broke for random people
I couldn't github revert it, so i reverted the update

#26425

**Comment by optimumtact** [comment]
JORDIEEEEEEEEEEEEEEEEEEE

**Comment by Jordie0608** [comment]
I can't reproduce anything but 
> byond account age isn't even working at all

Tried with both normal and newly made account.

CID randomizer code had the call to it moved, but otherwise untouched and I don't think it accesses anything that was changed.
I've got no clue about the other two; although just now I was refused connection to Sybil with a runtime about languages, but the MC was going nutty so that is more likely the case for that.

**Comment by MrStonedOne** [comment]
>CID randomizer code had the call to it moved, but otherwise untouched and I don't think it accesses anything that was changed.

I do know that its location in the chain was very carefully selected, but i can't remember why.

**Comment by Robustin** [comment]
Ready up broke for me today.

**Comment by ChangelingRain** [comment]
The entire Ready Up menu randomly doesn't work, actually.
