### ISSUE TITLE
Debrain bug

### ISSUE THREAD

**Issue by Charmisokay** [tgstation/tgstation#27142]
After going into the recycler while wearing a fake ID (Dominican John), my head was destroyed but 'my' brain popped out.
Problem: The brain belonged to a non-existant person, Dominican John. I could not posses the brain, so I thought cloning was impossible.

Upon examination, I found my 'corpse' near the recycler. A little speck of nothing. (see pic below)

The doctors put the Domican John brain into a body anyways, and I was able to jump back into the body, and get cloned. When I was cloned, I came out without a name. (see pic below)

![image](https://cloud.githubusercontent.com/assets/25822752/25958883/42ddd4c4-3672-11e7-9df8-e04a87d20a0e.png)

![image](https://cloud.githubusercontent.com/assets/25822752/25959231/5e99d2fc-3673-11e7-9e95-47c7f4c3dec0.png)

**Comment by Tacolizard** [comment]
I've lost my name when cloned before.

**Comment by monkeyboyinc** [comment]
I was the CMO in this shift, and it gets weirder. I assumed that the loss of name was due to a mismatch between the body and the head, as the case normally is. My attempts at fixing your DNA probably failed because I was using the DNA of the head stitched into the body, meaning the UE and UI's I was giving you already belonged to an unknown.

The weirdness comes from the fact that I didn't actually place your brain inside a head. I reattached a head to a body, clicked the brain and it teleported into your skull. Was your head destroyed along with your body? If so, your brain teleported into someone else's head somehow.

**Comment by QualityVan** [comment]
This is weird for a couple of reasons. First of all, going into the recycler shouldn't produce a brain from a human. It'll produce a head if it's set to gib via badminnery(emagging only makes it kill people, not gib them, from what I can tell) and that head will be occupied by whoever went in. Second, the recycler straight up won't accept heads or brains right now(properly speaking there's a bug where the brain/head will vanish if you put it through a grinder, which's due to the recycler gibbing the brainmob).

The brain being named the same as the person it seems to have dropped out of is intended. The fact that you couldn't occupy it is weird. The fact that it teleported is really weird. Conclusion: what the heck

**Comment by Charmisokay** [comment]
Oh I forgot to clarify that part. He tossed our heads into disposals, the recycler ate our heads and pooped out a couple of brains. One belonging to my fake ID (dominican john) and one for the detective (forgot his name, he was braindead so I don't think he got cloned). 

Upon examination of 'my brain' the brain was described as being completely inactive. 

I did come out in the proper body, but without a name.

So fixing the brainmob-gibbing should circumvent this problem, too.

**Comment by QualityVan** [comment]
Oh, good to know. In that case no idea what's going on, I couldn't make the recycler consume a head and produce a brain. The fix should prevent it from happening, I guess.

Still doesn't explain the 'brain teleported into the right body' thing though what the hell
