### ISSUE TITLE
Server can't get the round id if its the first round on the database

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation#27308]
@Cyberboss 

@balohmatevz

@Jordie0608 

(From general logs)
```sql
INSERT INTO feedback SELECT null, Now(), MAX(round_id)+1, "server_ip", 0, ":60759" FROM feedback;
SELECT MAX(round_id) FROM feedback;
```

**Comment by Cyberboss** [comment]
No rows returned = set round_id to 1?

**Comment by MrStonedOne** [comment]
This also breaks all feedback stats because the round id var is an empty string. Found this testing for #27139

Everything about how this system works is broken.

The sad truth is we should be having a round table with a auto_inc id, and use that.

**Comment by balohmatevz** [comment]
Don't think I put the round ID retrieval thing in. The way it was made was to dump all round feedback at the end, which is when the actual round ID was created. This means a round ID is only known at the end of the round, at least that's how I coded it originally. Don't know what kind of edits were made later though.

**Comment by MrStonedOne** [comment]
RoundID became more of a thing in recent times.

The round is opened up at server start, I had thought you added that part (since this is how stats knew about rounds that crashed.)

**Comment by balohmatevz** [comment]
When I stopped coding, feedback didn't log for rounds which crashed - the data was lost during the crash. The way I identified rounds that crashed in a no-longer-active chronograph part of the stats page ( https://github.com/balohmatevz/SS13Tools/blob/master/Tools/index.php#L5461 ) was just based on whether a log existed for a time slot or not.

**Comment by MrStonedOne** [comment]
That makes sense.

Then ya, it looks like this bug was added by @Jordie0608

**Comment by balohmatevz** [comment]
The feedback system outgrew itself ages ago and is in need of a refactor. The original reason why data was dumped at the end was because MySQL queries were (probably still are) blocking operations for the TGStation server, so minimising their impact was important and the end of the game was a good time to block the server for a bit and dump everything at once. 

Later, however, when database based banning was added, a whole bunch more blocking mysql queries happened during the round (every time a player joins, a query is made), which was a problem for a while, but resolved itself or people stopped noticing / caring. Then polls were added, which are probably still a potential way for players to cause server lag (same with library which predates my work).

**Comment by MrStonedOne** [comment]
#27139 fixes almost all of those issues. I had added it to feedback reporting manually, now i'm making it its own system.

The cost is in the query itself, not the actual insert 99% of the time. So grouping them up into one query fixes that.

And the abuse of the 5.6's DELAYED keyword for tables that support it also helps.

**Comment by nfreader** [comment]
[screaming]

**Comment by Jordie0608** [comment]
SQL a nerd.
I guess I'll stop putting off making that round info table.
@nfreader @MrStonedOne Do you have any other crazy ideas you'd like done at the same time?
