### ISSUE TITLE
Swarmers can deconstruct the doors to the SM

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#27477]
Title is what it says. Seems like an unintended oversight

**Comment by Penguaro** [comment]
Are Swarmers currently limited on things they can decon?

**Comment by FantasticFwoosh** [comment]
High pressure windows can also be smashed too remember, it just takes a very very long time because of the 1000 health, which would be about 20 hits given swarmers can destroy

> It has a similar strength to the revenants defile ability, in which onetime i destroyed the highpressure windows.

Sufficiently without specific exceptions, the door/windows need to be replaceable or indestructible.  OR a way is established to connect it to a button network to maintain safety.

**Comment by 4dplanner** [comment]
Also no hull breaches allowed

**Comment by octareenroon91** [comment]
Mapping convention is to put supermatter containment in its own area. How about banning any destruction in that area at all?

**Comment by kriskog** [comment]
This has been fixed.
