### ISSUE TITLE
Template atmospherics vents and scrubbers start off.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#27746]
Even if you set them to ON in the map maker, they will still default to OFF in game, you need to turn them on through the air alarm to get them working again.

This bug is specific to templates loaded partway through the round, though it MIGHT happen with roundstart ruins, too.

**Comment by duncathan** [comment]
This bug does not occur until after the round has begun - this includes the rare case of loading a map after initialization but before the round starts. Seems to be an underlying inconsistency with the map loader - it behaves differently pre-round and mid-round.

**Comment by Cyberboss** [comment]
8:21 PM <%Cyberboss> Dunc|Mobile i think its the fact that atmos machinery hasn't been ported to Initialize yet
8:21 PM <%Cyberboss> so whats happening is
8:22 PM <%Cyberboss> machinery/New() is adding the obj to the atmos processing list
8:22 PM <%Cyberboss> WHILE the template is still loading
8:22 PM <%Cyberboss> and then process_atmos is called
8:22 PM <%Cyberboss> can't find NODE1 because it's not loaded yet
8:22 PM <%Cyberboss> so it shuts off
8:22 PM <%Cyberboss> so the fix is a bulk port of everything atmos to Initialize

**Comment by Cyberboss** [comment]
Okay so even after the Initialize port, we run into the issue of stuff added to atmos processing, sleeping before atmosinit is run, and thus shutting down because it has no nodes. So there's two solutions as I see it:

1. Move all SSair.atmos_machinery += src to atmosinit
2. Call atmosinit from Initialize

Your opinion @duncathan?

**Comment by JohnFulpWillard** [comment]
loaded pirate ship mid-round and it seemed fine, so i assume it's fixed by now
![image](https://user-images.githubusercontent.com/53777086/224140785-1f9f030b-a3f3-432a-8dfb-aea9100cc76d.png)
