### ISSUE TITLE
being in gang/vigilante and being turned into a clown by an anomaly crystal causes your uplink to unimplant itself and drop on the floor

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#27821]
round 71072

**Comment by Kromgar** [comment]
What the fuck

**Comment by factoryman942** [comment]
yes

**Comment by Dorsisdwarf** [comment]
This is why we had the EDGE CASE tag

**Comment by PKPenguin321** [comment]
Drop all items needs an arg to ignore implants/organs

**Comment by lzimann** [comment]
Is this on regular gang or on the now closed Robustin's gang overhaul?

**Comment by factoryman942** [comment]
yes.

**Comment by factoryman942** [comment]
I think without robustin's stuff the uplinks aren't implanted are they?

**Comment by Robustin** [comment]
The problem is that the crystal makes a new mob with the same mind so anything not stored in mind is out. There might be checks for implants but definitely not for gangtools. 

It's not a big concern for me because 1) its a major edge case and 2) that just means it functions like any ordinary gang tool, if a boss gets clowned the same thing happens. The tool still functions fine once its been removed from your body - the most troubling implication is that another gangster could pick it up and use it.

**Comment by lzimann** [comment]
Anyway I think this was on a testmerge and not the actual gang
