### ISSUE TITLE
Dwarf metabolism is weird

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/tgstation#27838]
@Iamgoofball 
Drinking just one sip of ale causes dwarves to become fat, not sure which one of the basic three ales it was but it seems to be any. Dwarves also seem to have trouble getting rid of toxins and other reagents within the body.

Edit. Alternatively ales contain a ton of reagents

**Comment by RandomMarine** [comment]
Because the ale already gives nutrition on par with raw nutriment. To compare, a whole meatpizza contains 30u nutriment.

As a bonus, if you use any plants that contain nutriment to brew the ale, it stacks its effect. So one mug of plump helmet or wheat ale is like chugging 100 units of nutriment. Honk.

Also, I don't think testmerges should be reported on the tracker, I'd comment on the pull request itself.

**Comment by FantasticFwoosh** [comment]
Reagents are bleeding out into the ale, meanwhile i can't actually see any ale working so has the code gone wrong somewhere and instead we are juicing the plants?

**Comment by Iamgoofball** [comment]
This is working as intended
