### ISSUE TITLE
Chloral Hydrate appears to be worthless, as are sleepypens

### ISSUE THREAD

**Issue by Robustin** [tgstation/tgstation#27983]
The recent change swapped out the morphine for the chloral but now all it does is moderate stamina damage and a mute, no sleep, no stun, nothing.

**Comment by VeryRealAccount** [comment]
Isn't that because we nerfed Chloral ages ago because it was so overused?

**Comment by Expletive** [comment]
Replace the chloral with sulfonal then.

**Comment by YakumoChen** [comment]
Goofball Tier (tm) code at work

**Comment by Iamgoofball** [comment]
fuck you weeb eat dicks

**Comment by kevinz000** [comment]
wow goofball you sound salty man

**Comment by CPTANT** [comment]
What if we make Chloral not suck again?

**Comment by msgerbs** [comment]
Yeah, how about making chloral not suck again? Considering the lethal injection syringes still use it (do they even kill anymore?).

I can't think of any situation I'd want to use chloral instead of sulfonal except when I need a slightly faster knockout (but then I might just use neurotoxin). Sulfonal is slightly more difficult to make, but takes literally 1/10th the volume as Chloral to do anything at all, and a full syringe is a gauranteed crit and a *6 minute* knockout barring no outside interference.

If we make the sleepypen use sulfonal then the sleepypen would need to have its dose lowered or it would go from "sleepy pen" to "death pen"

**Comment by CPTANT** [comment]
chloral is a good example of a huge overnerf.

The original chloral only needed a slight nerf to the time it takes to knock you down, but it was just practically removed from the game isntead.

**Comment by Tacolizard** [comment]
@msgerbs yes, lethal injection syringes still work.


iirc the way the choral nerf went was its pretty much useless unless you inject 30u, normal syringes are 15u and lethal injection syringes are 30u. The issue with sleepypens is probably that they don't have a high enough capacity.

**Comment by kevinz000** [comment]
@CPTANT no

**Comment by bgobandit** [comment]
this isn't goof's fault like everyone said it is the fruits of a MASSIVE nerf to chloral

**Comment by Iamgoofball** [comment]
actually this might be a bug, I put chloralhydrate2 in which is supposed to be just knockout and it's not functioning properly

**Comment by ShizCalev** [comment]
@Tacolizard Lethal injection syringes don't use chloral.

https://github.com/tgstation/tgstation/blob/d95e859e5d4e055a95f3246a9c0b7ae1bacb95f7/code/modules/reagents/reagent_containers/syringes.dm#L216

**Comment by msgerbs** [comment]
There's a variant right above it that uses chloral, and that's the one I've seen on the station.

**Comment by ShizCalev** [comment]
The ones on the station are /obj/item/weapon/reagent_containers/syringe/lethal/execution. 
The chloral one is only present on the gasthelizards ruin and the oldaisat space ruin.

**Comment by msgerbs** [comment]
Maybe it was on Hippie but I know I've seen 50u syringes of chloral on the station, and not that long ago either.
