### ISSUE TITLE
Devil Bugs

### ISSUE THREAD

**Issue by Difrit** [tgstation/tgstation#28051]
[Note]: #15794, #18520

True devils/Archdevils are completely deaf. This makes it extremely difficult to, you know, talk people into taking contracts.
True devils get two sets of every button, meaning two hellfires and two pitchforks at the same time.
True/Archdevils do not heal at all.
True/Archdevils are immune to burns from fire, but still take burn damage from lasers (?)
True/Archdevils can be handcuffed.
True/Archdevils can be cremated. This completely defeats the purpose of being a huge hulking thing if you can be stuffed in the cremator like a changeling.
Accompanying the previous point, if your body gets incinerated, you spawn shortly afterwards in Maintenance as a deaf True Devil, with tier 1 powers.

You can shove contracts, signed and unsigned, into papertrays where they'll never ever be found.
People walk hellfire off like it's nothing smh

**Comment by lordpidey** [comment]
> True devils/Archdevils are completely deaf. This makes it extremely difficult to, you know, talk people into taking contracts.

Will fix.

>True devils get two sets of every button, meaning two hellfires and two pitchforks at the same time.

Will fix.

> True/Archdevils do not heal at all.

Intentional, but this can be changed.  I think it might make them too powerful.

>True/Archdevils are immune to burns from fire, but still take burn damage from lasers (?)

Intentional.  Being from hell, it makes sense to be immune to a blazing inferno, but lasers aren't typically something found in hell.

>True/Archdevils can be handcuffed.

I'll change this.  It was intentional, but you're right.  This is kinda stupid.

>True/Archdevils can be cremated. This completely defeats the purpose of being a huge hulking thing if you can be stuffed in the cremator like a changeling.

Intentional.  They should also come back unless corpse destruction is their banishment method.

>Accompanying the previous point, if your body gets incinerated, you spawn shortly afterwards in Maintenance as a deaf True Devil, with tier 1 powers.

I'll fix the deaf thing, it's because they don't have ears.  Tier 1 though is strange, I'll have to look into that.

> You can shove contracts, signed and unsigned, into papertrays where they'll never ever be found.

I can remove this easily enough, I think, but I'm not sure if I should.

>People walk hellfire off like it's nothing smh

I'll buff hellfire a little.
