### ISSUE TITLE
Byond seems to take incorrect files when set in the map maker.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#28085]
![](http://i.imgur.com/CZLniZh.png)

If you try to set the sound to /sound/weapons/Laser.ogg, it will automatically be replaced with /sound/vox_fem/laser.ogg.

This doesn't just happen with sound files, icons suffer from this too (and presumably others?) If you try to set, say, an indestructible riveted wall to /icons/turf/mining.dmi and pick the "rock" icon, the sprite will fail because it will automatically re-select to /icons/obj/mining.dmi.

This seems to affect only var editing in the map maker, but I don't know if it extends to anything else.

**Comment by xxalpha** [comment]
That's really weird, try recompiling a clean rsc.

**Comment by WJohn** [comment]
Still happening even after clean compile.

**Comment by MrStonedOne** [comment]
http://www.byond.com/forum/?post=2254896

**Comment by Cyberboss** [comment]
Should this really remain in OUR issue tracker?

**Comment by xxalpha** [comment]
Yes, it serves as a record that we know about it and informs people we can't do anything.

**Comment by MrStonedOne** [comment]
We have always kept byond bugs open.

Keeping bugs that can't be fixed open lowers dupes because issue search by default does not show closed issues, and most people would assume a closed issue is fixed and it happening again would warrant a new issue anyways. 

Like, @Cyberboss, I'm banned from microsoft, reddit, RES, and a few other github repos because I believe firmly that cantfix or wontfix is not a reason to close an issue report.

Do you *really* think i'd ever let this issue get closed here?

**Comment by MrStonedOne** [comment]
Can somebody confirm this issue still exists in 512, no action was done on the byond side, but 512 changed a bunch of things in the map maker.

**Comment by SuperNovaa41** [comment]
No longer an issue.
