### ISSUE TITLE
You must summon narsie in "nothing" where the veil is weak enough

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#28284]
![](http://i.imgur.com/sCtVCcM.png)

Where the hell is "nothing"? Looks like it failed to pick a location.

**Comment by DaxDupont** [comment]
Just had it happen again on meta. 
Server revision compiled on: 2017-06-09

c113a1

REEE @Robustin stop half assing stuff,

**Comment by Cyberboss** [comment]
Fixed by #28279

**Comment by Robustin** [comment]
Not half-assed, it just boils down to the interaction of datum objectives and mode-setup getting really stupid and unintuitive. 

The mode gives out both objectives to the cult and then actually determines the sac target after the objective is made, but because of the goofy ordering of things, the same treatment didn't work with the summoning objective.
