### ISSUE TITLE
IF SHUTTLE LEAVES STATION AND NARSIE IS SUMMONED, ROUND ENDS WHEN SHUTTLE IS DOCKED

### ISSUE THREAD

**Issue by PraiseRatvar** [tgstation/tgstation#28325]
FUNNIEST CULT BUG SINCE FUNNIEST CULT BUG

**Comment by MrStonedOne** [comment]
Please explain.

**Comment by MrStonedOne** [comment]
Like, the way you have it written, it sounds like the shuttle had already left the station, well, the round is suppose to end when it docks with centcom.

Thats not a bug

So something tells me you didn't explain it well, so start from the beginning, don't speak in all caps, and actually describe the issue in more details.

**Comment by DaxDupont** [comment]
Cult won. Normally when Nar'si gets summoned the round will go on for a bit and it'll play the round end victory animation for cult. 
Instead cult won, green text and all but instead of the whole harvesters dragging corpses and round end animation the round ended instantly after summoning due to the docking. 

Maybe it's intended? Just kinda weird that cult had a victory with the abrupt end.

**Comment by PraiseRatvar** [comment]
Sorry for not explaining well enough but basically escape shuttle arrives to station and leaves station without any difficulties, then during shuttle's transit to centcom, nar'sie is summoned. Then shuttle arrives to cencom thus ending the round abruptly, I forgot to check if bloodcult actually won that round but the roundid _probably_ is 71687 or 71686

i'm unsure if this is a bug or not but maybe an alternate victory/loss should be done here?

**Comment by Jalleo** [comment]
Its a edgecase.

**Comment by ExcessiveUseOfCobblestone** [comment]
it's not suppose to return and pickup narsie if that's what you're saying.

**Comment by lordpidey** [comment]
@Cyberboss this doesn't seem like an issue, the shuttle landing should be end of round, bar admin intervention.
