### ISSUE TITLE
Cryotubes now eject beaker behind tube.

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#28608]
Server revision compiled on: 2017-06-19

The following pull requests are currently test merged:
#28580: 'Fix cid reconnect message not showing' by MrStonedOne

Based off origin/master commit: 9c9691
![dreamseeker_2017-06-19_21-37-53](https://user-images.githubusercontent.com/17237624/27303410-076e64fc-553b-11e7-9f14-e68d44e38a5b.png)

**Comment by DaxDupont** [comment]
(i know shit was fucked up at that point but even on roundstart it does that)

**Comment by ShizCalev** [comment]
This is due to the layer adjustment to cryo.dm in #28466.

If it's not prefered, the layer can be adjusted - however, doing so will make it so that windows, displays, air/fire alarms, extinguisher cabinets, posters, & signs will appear above cryotubes if placed on either square that it occupies (effectively reopening #15051.)

**Comment by nicbn** [comment]
We could make it go to the user's hand or to the tile that the user is.

**Comment by MoreRobustThanYou** [comment]
Fixed by #30938

**Comment by MoreRobustThanYou** [comment]
@Cyberboss close this please
