### ISSUE TITLE
Supermatter in vacuum blows up super easily

### ISSUE THREAD

**Issue by CPTANT** [tgstation/tgstation#28638]
Supermatter behaviour in vacuum is weird. When surrounded by all sides you can fire emitters all day without anything appearing to happen. I then placed one floor next to the supermatter and it instantly delaminated at 1000%

[img]http://i.imgur.com/0wGZ9y9.png[/img]

Supermatter should fail in vacuum, but this doesn't seem the intended reaction.

**Comment by ohnopigeons** [comment]
Not a bug, the only possible solutions are hacks or a complete overhaul. The SM reacts to the gases around it. Placing the SM in a vacuum eliminates all coolant gases, so that repairing the source of the vacuum means that the SM feedbacks off of its own waste gases, causing the runaway and instant delamination.

**Comment by AnturK** [comment]
Actually a bug. Or at least unless it was meant to get energy in space but the comments were never changed ?

**Comment by CPTANT** [comment]
The comments state this:

// This stops people from being able to really power up the supermatter
 // Then bring it inside to explode instantly upon landing on a valid turf.

But this is exactly what is happening now?

**Comment by CPTANT** [comment]
Ohw one thing to note is that in my test the supermatter itself wasn't on space, it was on a floor surrounded by space.

**Comment by XDTM** [comment]
Even if it didn't charge off the emitters, it could've been the fault of a tiny amount of air. Since the SM considers air heat regardless of how much air is there, a small amount of heat is much more efficient when the air to share it with is minimal.

**Comment by Tokiko1** [comment]
The intended behavior is that in line 210, it checks if there gas and/or if its in space and if it is, it's supposed to cause damage depending on how much power it still has so people can't just cheese it and RCD the floors away under it. The problem is caused by the fact that it returns instead of ever getting to line 368 where the explosion check happens. There is other important checks and stuff happening onwards of line 306 to 382 including radio messages and radiation. Maybe run those in the beginning of process() or turn it into a proc or something.

**Comment by ohnopigeons** [comment]
lmao this isn't fucking fixed

**Comment by praisenarsie** [comment]
@duncathan
