### ISSUE TITLE
AI core camera chunks do not update properly in some areas

### ISSUE THREAD

**Issue by SgtLion** [tgstation/tgstation#28637]
>Server revision compiled on: 2017-06-20
>The following pull requests are currently test merged:
>#28616: 'Makes movement delay calculation not round to the tick' by MrStonedOne
>Based off origin/master commit: 885c49

When unbolted and taken to the escape shuttle, the AI core has no sight in its vicinity. It can still hear and speak as normal, but also still gets messages to the effect of "Urist McUristface put a MultiPhase X07 Energy Gun into a security satchel". Which leads me to think the AI core is still receiving some sight messages, despite not actually being able to see.

I currently like to think the AI core has a super-advanced audial frequency analysis system that can tell exactly what is putting what into what, based on the sound it makes.

**Comment by GunHog** [comment]
You have this issue backwards. AIs are intended to see around them, as per the camera object inside of them (the camera object is required to support a nerf that prevents the AI using its own mob sight). The bug is that camera chunks do not update properly on shuttles and in some cases Lavaland areas as well.

The AI is supposed to be able to see things around it just as you do, but because it relies entirely on camera chunks, bugs with the chunks will blind an AI.

**Comment by SgtLion** [comment]
Ah. Well, I had no way of knowing the intention. That is an even better fix.

**Comment by Shadowlight213** [comment]
Pretty sure this is a dupe, as this issue has been around ever since the AI nerf with having a camera in the core.
