### ISSUE TITLE
Where my deaths at

### ISSUE THREAD

**Issue by nfreader** [tgstation/tgstation#28833]
Seriously, the last death recorded in the DB was [over three weeks ago](https://atlantaned.space/newSS13tools/death.php?death=2307463). Dunno if it's a server thing or a code thing, but I miss seeing deaths :(

**Comment by Jordie0608** [comment]
Well k but I meant open an issue 3 weeks ago when it first happens =P

**Comment by Jordie0608** [comment]
`[03:54:20]SQL: Unknown column 'x_coord' in 'field list'`
Looks like DB wasn't updated; I guess @MrStonedOne never heard word about the change.

**Comment by MrStonedOne** [comment]
I did that, this issue is still not fixed.

Please don't hastily close issue reports until its confirmed fixed.

@tgstation/commit-access 
@tgstation/issue-managers 
Please re-open this issue.

**Comment by Cyberboss** [comment]
Fuck

**Comment by Jordie0608** [comment]
Srsly

I closed it because it didn't appear to be a code issue; but I guess that assumption was wrong ¯\\\_(ツ)\_/¯
What is the new sql error?

**Comment by MrStonedOne** [comment]
Still shouldn't have closed it until we knew that was the only issue, and confirmed they started recording again.

It costs nothing (in terms of effort) to leave an issue open a few extra hours

The costs to closing an issue early however are much greater. Everybody who's seen the issue but didn't subscribe to it, will assume the bug is already reported, and won't bother to report it if they see the bug again, only somebody who both was subscribed to the issue report, AND notices the bug is still around, would even bother asking for a re-open.

So there is a chance the bug might never get re-opened.

Also I had to subscribe every maintainer to this thread to get it re-opened, so now they all get notifications, that seems silly.

Next time wait.

**Comment by MrStonedOne** [comment]
Anywho, I fucked up the query, and it never deleted the old coord column, and errored about no default value for it. Fixed. and I confirmed deaths are getting reported, so this can be closed.

**Comment by nfreader** [comment]
Thanks MSO!

**Comment by Jordie0608** [comment]
Welp all's well that ends well.

**Comment by RemieRichards** [comment]
I'm subbed to all threads anyway...
