### ISSUE TITLE
Observing citrus causes every light to be blinding until you cancel camera-view.

### ISSUE THREAD

**Issue by Hadrin** [tgstation/tgstation#28956]
[Note]: # (Please enter the commit hash and active testmerge numbers from the "Show Server Revision" verb if you can. If you believe the issue to be caused by a testmerge, please report it in its relative PR thread. State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

b210c8
Using the observe verb to observe citrus the sloth causes all lights to be blindingly bright until you use the cancel camera view verb. I've had two others confirm that this happens on their hardware as well. I tested using multiple scaling modes and none caused the blindingly bright lights to disappear.

Related image: [http://imgur.com/ifbxHNM](http://imgur.com/ifbxHNM)

**Comment by PKPenguin321** [comment]
@optimumtact what have you done

**Comment by Xhuis** [comment]
Through testing, I've determined that this happens with Observe _in general_, not just with Citrus. From what I can gather, it's because it shows you the screen that the mob sees; this includes their lighting objects. Because the ghost's lighting isn't suppressed, however, it shows both players' lighting at once, resulting in this horrific effect.

I'm not sure how to work with lighting, but it should be a fairly easy fix.
