### ISSUE TITLE
can someone fix holodeck its interface is broke

### ISSUE THREAD

**Issue by kevinz000** [tgstation/tgstation#29010]
pls

**Comment by GunHog** [comment]
"Please enter the commit hash and active testmerge numbers from the "Show Server Revision" verb if you can. If you believe the issue to be caused by a testmerge, please report it in its relative PR thread. State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them)"

You see this every time you make an issue, Kev. Why are you not following it? How is the holodeck broken? Is it broken for everyone or just a specific mob type? Does the interface show up but buttons refuse to work? Does the interface show up at all? What type of mob were you and what were you doing when you tried to open it? Did you emag it?

Details, Kev. Details.

**Comment by Xhuis** [comment]
Screenshots? Information? This gives me nothing and I'm not going to be bothered to fix it if you aren't going to be bothered to tell me about it.

**Comment by octareenroon91** [comment]
OK, I noticed a holodeck bug since the TGUI port, presumably the same one.

Picking a holodeck program spawns the objects SOMEWHERE, but doesn't actually put anything where a player can reach it. The holodeck floor remains the standard gridded surface, unchanged. No visible objects appear.

Changing holodeck programs after you pick one and 'nothing' happens, you get a message about all the holographic objects disappearing.

The only screenshot would be a list of holographic items despawning in the chat log, with a holodeck in its initial state.
