### ISSUE TITLE
Medical borgs on skateboards look weird

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#29019]
alternatively: medical cyborgs, when buckled to skateboards which are facing vertically, have their sprite off-centre from the centre of the tile while the board itself is in the centre of the tile, meaning they look weird; they also hover slightly above the board itself

**Comment by PKPenguin321** [comment]
Any mob can buckle to skateboards, it looks weird but I liked it so I kept it in

**Comment by factoryman942** [comment]
See alternative title
Also when they collide with something they have the same kind of ultra-cripple-stun flashes cause, which is kinda annoying but probably not a bug

**Comment by bgobandit** [comment]
fucking feature

**Comment by Xhuis** [comment]
I'm not actually sure if I should be patching this out or not.

@Cyberboss You seem to be the most active maintainer. What are your thoughts on this? It's not an issue and was kept in on purpose, but it's in a grey area where I'm not sure if it should be kept or removed.

**Comment by Cyberboss** [comment]
Someone can fix the offsets

**Comment by Xhuis** [comment]
Dang, thank you for the fast response. Should the feature itself (every mob is able to be on skateboards) be staying?

**Comment by Cyberboss** [comment]
I see no reason why not

**Comment by Xhuis** [comment]
Sounds good to me! I'll see what I can do about the offset issues that it's been having.

**Comment by Xhuis** [comment]
Pixel offsets seem as though they'll have to differ on a per-mob basis based on their own sprites, especially for the larger ones. Do you know of an easy solution to this?

**Comment by Cyberboss** [comment]
@kevinz000 @Militaires

**Comment by PKPenguin321** [comment]
There is no easy solution unless you can calculate distance of the offset by coding something that counts the number of vertical pixels in the buckled mobs sprite, but this would also have to account for overlays and mobs that have something lower on their sprite than their feet (like a tail), so it's not really feasible at all. The other possible solution is to make the rider an overlay instead of just buckling which would be a massive pain in the ass, and the third solution is to make a separate pixel offset for every mob in the game case by case, which would be massive and snowflake as fuck. This isn't really fixable without removing the ability for non-humans to ride them, and it's such a minor visual bug that it doesn't really matter if it stays in. I think that this issue should just be closed.

**Comment by PKPenguin321** [comment]
I think somebody might have changed this recently but I forget

**Comment by kriskog** [comment]
Still offset on the downward sprite. 
![image](https://user-images.githubusercontent.com/33292112/61508342-b6271700-a9e9-11e9-973f-bd6ea68a0e07.png)

**Comment by TaeruAlethea** [comment]
This issue needs to be attached to PR #59059
