### ISSUE TITLE
Cerestation prison cells can be opened by prisoners

### ISSUE THREAD

**Issue by Tacolizard** [tgstation/tgstation#29272]
They're all access doors

**Comment by MMMiracles** [comment]
I swear I had a fix for those up ages ago and it never went through for whatever reason. I think it may of been due to someone else having a fix PR up for the map. 

I can't do any map work where I currently am so someone else needs to come in and fix this or just drop the map from rotation until I get free time again to fix shit.

**Comment by Mark9013100** [comment]
That was my PR, however there were merge conflicts and I've forgotten how to resolve those.

**Comment by nicbn** [comment]
Just remove cerestation

**Comment by Anajamois** [comment]
SEE I KNEW SOMEBODY OTHER THAN ME KNEW THIS WAS BULLSHIT
REMOVE CERE
