### ISSUE TITLE
Xenomorphs can infinitely chainstun without cost

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#29517]
This seems to be a long-lasting bug, but it's worth addressing since it completely breaks the flow of any round involving xenomorphs.

**Comment by BeeSting12** [comment]
Balance issue, close.

**Comment by WJohn** [comment]
That's not a  bug, that's completely intentional. They're supposed to be extremely dangerous in close quarters, and you should avoid melee with them at all costs.

I even made sure to give some way to survive an encounter with them should they get a lucky hit on you. If you're holding an item in your active hand, it will always and ONLY ever disarm the item, rather than tackle. If your hand is empty, it will always and ONLY ever tackle you. Keep an item in your hand and it can't tackle you.

Furthermore, there's also protection from leaping. Any basic physical shield like a riot/telescopic/roman/wooden shield will totally block leaping and even stun the hunter, on top of helping the item in your hand last that little bit longer.

**Comment by AnonymousNow** [comment]
I'm not sure how this information has passed me by for so long, but it does change things. I feel as though it could be better shared.
