### ISSUE TITLE
Drone filter broken

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#29717]
![dreamseeker_2017-08-04_19-30-15](https://user-images.githubusercontent.com/28678854/28981846-6fede35c-794b-11e7-923d-2577fbbe860c.png)
roundid 74259
went on observer on roundstart, came back 20 minutes later and decide to pick drone > repair drone

**Comment by PraiseRatvar** [comment]
![dreamseeker_2017-08-04_19-34-23](https://user-images.githubusercontent.com/28678854/28981989-f86b29d8-794b-11e7-8e3f-7c37a2f02388.png)
it appears drones work and i am guessing other non-crew shit too

**Comment by PraiseRatvar** [comment]
![dreamseeker_2017-08-04_19-54-33](https://user-images.githubusercontent.com/28678854/28982722-c3e398b4-794e-11e7-9631-daf5251bb599.png)
????????????

**Comment by Bombpants** [comment]
I have had that happen in the past too! Only a select few humans were visible

**Comment by WJohn** [comment]
This bug has been around for ages, and is actually a dupe of #8191.

**Comment by DoctoreMad** [comment]
I thought Higgs-Bugson issues were supposed to be closed

**Comment by PraiseRatvar** [comment]
they are.

either we remove drone filter entirely or keep everything as it is (or even fix it!)

**Comment by DoctoreMad** [comment]
As in "this is a pain in the ass to fix and only occurs occasionally so how are we going to fix it"

**Comment by RandomMarine** [comment]
I don't like the filter in the first place.
Code issues include this, being able to see invisible revenants, or the most annoying being that you can't tell at a glance if simple mobs (Especially carp) are dead or not.

And even if they get fixed it's still a pain to have to examine every single static blob to avoid doing things such as repairing damage to a broken-in room while the culprit is still inside, or stay away from known drone validhunters.

I'd rather just see the vision filter done away with.

**Comment by WJohn** [comment]
Yeah I'd say remove it, tbh. Less hassle to maintain, edge cases, and deals with this issue.

**Comment by theo2003** [comment]
I had this issue too.

**Comment by AnturK** [comment]
Going to close this in favour of the fresh report that has round data.
