### ISSUE TITLE
Turret control panels have an accessible range of 0 tiles.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#29730]
This means you have to be on the same tile as the turret controls (which are often pixel shifted on maps, so this isn't always obvious). Being too far away for being just off to the side when all other wall-mounted objects in the game accept that totally fine is inconsistent and kind of annoying.

Been around for ages but no one has ever made a report on it.

**Comment by RandomMarine** [comment]
I always thought this was a balance thing.

**Comment by YakumoChen** [comment]
it's kind of a balance thing yeah, maps like Box have you stand on tiles in range of turrets to turn the controls off.

**Comment by DoctoreMad** [comment]
Well how else could you tell who turned the turrets on if there are 2-3 suspects since you can access the turret controls in a 3x3 radius?

**Comment by BeeSting12** [comment]
It should be switched to make you be able to do it on tiles adjacent to it.

**Comment by MrStonedOne** [comment]
````
|oxxxo|
|oxXxo|
|--T--|
````

T is where the turrent contol appears to be (on the wall), X is the current range, x is the proposed range.

Does anybody see a glaring issue there?

The issue is that it bases that off of actual position, not the pixel shifted position. so you can be standing two tiles away and still be able to interact with it. This applies to all wall objects, i've abused this on air alarms as atmos tech to fuck with them while it being obvious that i'm doing so.

This is what you most likely really want:

````
|ooooo|
|oxXxo|
|--T--|
````

but that has a hidden issue, in that it's really:

````
|ooooo|
|oxXxo|
|--T--|
|oxxxo|
````

Being able to use a turret control thru a wall where you can't even see it anymore isn't ideal. So a new system would need to be done

**Comment by WJohn** [comment]
In the meantime it would be best if we didn't have to be on the exact specific tile necessary to turn these off, and just make it consistent with everything else.

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/97661dac3351ff0077f7dcff68a1a767ee71e7f0/code/game/machinery/porta_turret/portable_turret.dm#L798
relevant line.
