### ISSUE TITLE
Delta station has no White Ship

### ISSUE THREAD

**Issue by The-clown-known-as-Pepe** [tgstation/tgstation#29772]
Basically the title

Delta station is the only big station without a white ship.

**Comment by PraiseRatvar** [comment]
@ShizCalev

**Comment by jughu** [comment]
Not an issue maps dont need to be dupes

**Comment by CPTANT** [comment]
Not an issue.

**Comment by Repukan** [comment]
@KorPhaeron not an issue

**Comment by pubby** [comment]
I remember seeing this awhile ago

OOC: Y0SH1_M4S73R/(Speaks-Her-Mind) : I&#39;m working on a white ship for Delta. I&#39;ve designed it so that it has an incomplete cryopod, freezer, and chem dispenser so that actually making the medbay fully functional is a complicated task that has to be completed using the included autolathe.

@Y0SH1M4S73R

**Comment by optimumtact** [comment]
not a bug

**Comment by Y0SH1M4S73R** [comment]
@pubby 
Yes i did say that. I'll finish it and get mappers to review it in the next few days.
