### ISSUE TITLE
Admins can deconvert last revhead without any warning, ending round early.

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/tgstation#29851]
There is no warning for the admin that the person is the last/only revhead when deconverting them through the TP. Led to a round ending early by mistake when they requested to be removed as a revhead via ahelp.

**Comment by ExcessiveUseOfCobblestone** [comment]
...

**Comment by DoctoreMad** [comment]
Well WHAT did you expect?

**Comment by Dorsisdwarf** [comment]
i dont really see why this is on the issue tracker, there isnt a warning if you decide to drop a bomb on the wizard for some reason either

**Comment by Cyberboss** [comment]
Deconverting revheads happens often enough for this to be a legitimate issue

On Aug 11, 2017 2:40 PM, "Dorsisdwarf" <notifications@github.com> wrote:

i dont really see why this is on the issue tracker, there isnt a warning if
you decide to drop a bomb on the wizard for some reason either

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/tgstation/tgstation/issues/29851#issuecomment-321888981>,
or mute the thread

**Comment by ExcessiveUseOfCobblestone** [comment]
Since when?
