### ISSUE TITLE
Virus symptoms sometimes stop working in the middle of a round

### ISSUE THREAD

**Issue by Resto171** [tgstation/tgstation#30009]
In some rounds, when I make a healing virus it suddenly stops working in the middle of the round. So mid-round, if I get damaged and I have a symptom that should heal me, it would fail to do so even though earlier in the round the virus was working fine. I would check the PANDEMIC and it would say I  still have the virus.

I think this should be given some attention because that means in some rounds it pretty much nullifies a whole job.

Thank you!

Round ID: 74891

**Comment by Nabski89** [comment]
Same thing, Round 74892. 

Virus was Cough, Necrotizing Fasci, Itching, Fever.

Resto did you have any overlapping symptoms?

**Comment by Cyberboss** [comment]
@XDTM

**Comment by SyruseEln** [comment]
On behalf of the player Gene Ball and myself we can both attest to this happening with any advanced disease. Yesterday my healing virus quit out on me for no reason, yet I was still infected with it. A death virus that I made also only effected one mob at a time leaving all others unharmed until the mob that was dying because of the virus finally expired. And now today Gene was doing experiments with viruses and infected himself with one which promptly stopped killing him despite being stage 5.

**Comment by Resto171** [comment]
Just made viruses the normal way. Brute forcing to get the desired symptoms from the reagents until they show up. I didn't do any overlapping.

**Comment by XDTM** [comment]
I'll test this out. This is pretty odd, since it uses the standard method for cooldowns (i.e. cooldown = world.time + x; wait until world.time goes over that value). It would be nice to check the virus vars when this happens, if possible, i'll try to reproduce this on my own in the meantime.

**Comment by XDTM** [comment]
wait, i fucking hope the symptoms aren't actually shared between viruses, it should be creating new instances per virus

**Comment by SyruseEln** [comment]
That would explain why my virus only acted on one mob at a time.
