### ISSUE TITLE
Swarmers can destroy the SM chamber door

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#30299]
Ban bait.

**Comment by Repukan** [comment]
How is it ban bait?

**Comment by YakumoChen** [comment]
Because it opens up the SM to pour all the gasses out.

**Comment by Ergovisavi** [comment]
It's not ban bait, swarmers should never be banned for killing someone, if they do it's a design problem not an administration problem

I'll look into a way to fix this.

**Comment by Cyberboss** [comment]
I already know how

**Comment by YakumoChen** [comment]
>It's not ban bait, swarmers should never be banned for killing someone or creating a hazardous environment, if they do it's a design problem not an administration problem

But it's listed in their laws to not kill people, and you already have in-code ways to prevent creating hazardous environments. Intentionally introducing other mobs into deadly situations is bad and as far as I've seen isn't allowed for swarmers (like repeatedly stunning someone in an airless space and letting them suffocate). Opening the SM is an exploit, not only that it messes with the power (which Swarmers also shouldn't mess with)

**Comment by Ergovisavi** [comment]
Those "laws" are not intended to be followed and were created to give a sense of purpose, not an administration problem. Again, if administration has banned someone for such activities in the past, then it is a mistake.

It's not ban bait, it's a DESIGN PROBLEM, which should be fixed by DESIGN and it looks like Cyberboss will fix that

**Comment by Supermichael777** [comment]
Ergo stop ruling from the coders seat. those are silicon laws, we enforce them to the letter, especially for "stock" law sets that have established interpretations.  Don't sabotage power and don't intentionally kill people are SIMPLE, STRAIGHTFORWARD, AND UNAMBIGUOUS instructions backed by strong but not perfect IC mechanics.  Just because a medical borg CAN kill people with the saw doesn't mean Asimov is a suggestion.  Same for all other silicons that DON'T have a law zero.

**Comment by Repukan** [comment]
I've seen admins laugh and wew when people manage to kill as swarmers.

**Comment by Ergovisavi** [comment]
@supermichael777

What the fuck are you even talking about? We're talking about swarmers and their fluff laws, not silicons and their administration enforced laws

What do those have to do with anything I was talking about

**Comment by DoctoreMad** [comment]
>Ergo stop ruling from the coders seat

You know I always scratch my head when I see that. What does it even mean?
If coders design something to work as X, it should work as X. If you don't want something merged hire better people for the github instead of making new rulings for it once its in.
I can understand adding new rules once something is tried and doesn't work but doing it the moment its merged is basically telling the coder to go fuck himself.
