### ISSUE TITLE
"Hair sprite substitution when hats are worn" system results in bald lines when hats are too small 

### ISSUE THREAD

**Issue by Militaires** [tgstation/tgstation#30433]
When hats are too small E.G berets they result in a line of baldness under them because they don't cover the newly substituted cropped out hair completely.

edit: im reeing but ok

**Comment by Cyberboss** [comment]
@RemieRichards

**Comment by ChangelingRain** [comment]
The solution is just to add sprites for that hat type.

**Comment by Militaires** [comment]
>adding a hat-specific sprite for each hair

but

**Comment by Cyberboss** [comment]
Yep

**Comment by Militaires** [comment]
>as the number of hats grows, so will the incompabilities, and vice versa for hair
but

**Comment by ChangelingRain** [comment]
Yep

**Comment by Militaires** [comment]
>multiple, even 10s of incompatibilities each for each piece of hair, in the distant future, the amount of incompatibilities generated when a new piece of hair or headwear is added will be so massive that it is virtually impossible to amend.

**Comment by ShizCalev** [comment]
...what

**Comment by ShizCalev** [comment]
>95 hair sprites per hat

**Comment by ShizCalev** [comment]
>109 current hair styles
>4 sprites needed for each hair for every hat added to the game
>you need to make 436 sprites per hat added just for hair.

**Comment by ShizCalev** [comment]
Or am i missing something with this system?

**Comment by kingofkosmos** [comment]
In theory a shitload of sprites would be the best but I think in practice we only need another version of the current +generic-suffix-sprites that's one pixel higher for short hats.

**Comment by RemieRichards** [comment]
@ShizCalev it was originally opt-in.
It was made opt-out because someone made all of them for the detective hat, and that was *mostly* a good fir for all other hats in the game.

**Comment by kingofkosmos** [comment]
I made an example with the big afro, made it one pixel longer so the bald line is gone:
![image](https://user-images.githubusercontent.com/5420151/30247557-2188ec74-9620-11e7-9f0e-418b56670338.png)
It doesn't look good. IMO in these cases the hair could just ignore the hat instead of cutting off, like this:
![image](https://user-images.githubusercontent.com/5420151/30247703-788e0ef8-9622-11e7-9604-b8a3e2796478.png)


@Militaires which hats have a bald line right now? I'll have a look at them.
