### ISSUE TITLE
Skeleton limbs inserted into lizards show up as lizard limbs

### ISSUE THREAD

**Issue by JonAdalwolf** [tgstation/tgstation#30508]
Round ID: 75842

Admins spawned skeleton onboard.  Brought a skeleton to surgery and de-limbed it. Upon inserting limbs (both legs) on myself (lizard race), new limbs assumed regular lizard sprites, with matching skin color. Not sure if the same would have happened with humans.

**Comment by FantasticFwoosh** [comment]
Full human faces also convert into lizard faces and don't carry onto overlayed faces (if that applies) 

- for instance if i commit to a full head transplant by getting a lizard, carefully severing the head, then attaching my pre-supplied human head with brain & defib, the implanted head will not bear any resemblance to its original owner.

- Its partially because skeleton arms aren't unique, you just implanted a generic arm onto your stump belonging formerly to a skeleton.
________________________________________________________________________________

That feature seems to only work on same-race transplants as switching heads between two humans creates different appearances, but switching arms or legs between two humans will cause them to recolor to the base mob's skin pigment.

**Comment by KorPhaeron** [comment]
@RemieRichards

**Comment by RemieRichards** [comment]
Not mine.

**Comment by KorPhaeron** [comment]
You made frankenstein surgery so I assumed you'd best know how to fix it though

**Comment by RemieRichards** [comment]
I didn't make it, I removed it being disabled, there's a difference.

**Comment by PKPenguin321** [comment]
To add to this, last time I tried it putting any human part on a fly/lizard/golem didn't show up visually. Was awkward when my Frankenstein asked what I had changed and didn't believe me when I told him

**Comment by YakumoChen** [comment]
Is there actually a code difference between parts? I'd assume you would have to be skeleton or zombie race to easily reattach limbs and you don't gain any racial benefits of cross race limbs

**Comment by Firecage** [comment]
Well, as I remember. Only digitigrade legs are their own kind of limbs when it comes to mutant races. All other mutant race limbs are merely var edits and icon edits of human ones.
