### ISSUE TITLE
Lightgeists - Floating False Advertisement

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#30556]
- Can only fix burn and brute damage types (oversight?)
- Can't heal themselves (intended?)
- Will report to be mending machinery etc. that they're clicking on, but it will do nothing (definitely a problem.)

Considering how rare and vulnerable these things are, I think it's silly that their abilities are limited so. You can see player health, but you can't get any more information, so you have to sort of guess what damage type they've taken (which is easy for people who play medical often, but difficult for the layman) to figure out if you're wasting your time (and the patient literally cannot tell you).

You could consider them overpowered if they could do all of the above; in that case, pick any two, preferably the first two. That'd make the Lightgeist a bit more interesting to play.

**Comment by DoctoreMad** [comment]
150 hours

**Comment by AnonymousNow** [comment]
?

**Comment by DoctoreMad** [comment]
150 hours of testing

**Comment by ExcessiveUseOfCobblestone** [comment]
The only thing that sounds like an "issue" to me is number 3 and that's just a result from it's friendly message.

**Comment by AnonymousNow** [comment]
The lightgeist had 150 hours of testing? And it's still this ineffective?

**Comment by ExcessiveUseOfCobblestone** [comment]
No no no no that's a coderbus meme.

**Comment by AnonymousNow** [comment]
Ah yes, the Coderbus. It is obscure from the outside, being completely opaque, so it didn't clique for a second in my head.

**Comment by RemieRichards** [comment]
>completely opaque
>door wide open, public IRC

it's your own fault if you feel you're missing out.

**Comment by AnonymousNow** [comment]
Come now, Remie, it's only a gentle ribbing.

**Comment by Ergovisavi** [comment]
* Can only fix burn and brute damage types (oversight?)

Intended, this is so they don't entirely take over Medbay's job such as with toxin or clone damage. They're a little bonus to make the round a little more weird, not a complete hostile takeover of medbay.
* Can't heal themselves (intended?)

Intended. Just respawn as another lightgeist if you get destroyed. Lightgeists are intentionally easy to kill for station crew so that they can get rid of them if they're indiscriminately healing allies/enemies of whomever.

* Will report to be mending machinery etc. that they're clicking on, but it will do nothing (definitely a problem.)

This is due to me lazily just using their attack message and having it say "mend". I can add an actual check, I suppose.

**Comment by AnonymousNow** [comment]
Respawn as another lightgeist? I have seen two, total. How are you supposed to respawn?

**Comment by Ergovisavi** [comment]
Click on the crystal again and you will be able to respawn as one. After it's activated, it serves as a permanent beacon for ghosts to spawn from it. The only way to stop them is to hurl the crystal into space.

"An anomalous crystal has been activated in [get_area(src)]! **This crystal can always be used by ghosts hereafter.**" - The message broadcast to ghosts when the crystal is activated

**Comment by AnonymousNow** [comment]
With more time and research, I'd have to contest that, with lightgeists being made of glass and being unbiased healers, they should be able to heal themselves if they somehow manage to survive a single attack from anything.

**Comment by Cyberboss** [comment]
Not a bug
