### ISSUE TITLE
Critical lore oversight

### ISSUE THREAD

**Issue by Slignerd** [tgstation/tgstation#30656]
![Loyalty implanter](https://i.imgur.com/cWAyPyB.png)

They're called mindshield implants.

**Comment by Supermichael777** [comment]
Mapping issue

**Comment by PraiseRatvar** [comment]
it probably was called loyalty implants in the past but whatever. this doesn't matter and it's an OLD exhibit if you look at the other stuff on display.

**Comment by banthebantz** [comment]
loyalty implant is and always will be the superior name

**Comment by ShizCalev** [comment]
What @PraiseRatvar said, an an exhibit of things from the past, and they were called loyalty implants in the past. Blame corporate rebranding.

**Comment by Slignerd** [comment]
Retcons are known to change past as well, you know.

**Comment by ShizCalev** [comment]
Time does pass ingame. The current year is 2557. 7 years ago when I started playing the year was 2550. The effigent species weren't discovered yet, lizards were barely allowed to take service roles on board the stations, the derelict station was an actual functional station, and the AI had an actual sattelite before it was bombed to hell by the syndicate, becoming what's now know as the ingame old AI sattelite.

Also it's not currently a retcon. Retconning would be /to/ change the exhibit's description. Right now it's just an exhibit with a description of what something was called years ago before it was rebranded by Nanotrasen.

You don't go to a museum in real life and demand they update the name of an old product made a decade earlier on a plaque because the makers decided to rebrand going forward, do you?

**Comment by Slignerd** [comment]
I'm getting flashbacks. 😒

**Comment by Slignerd** [comment]
Out of curiosity though, what's the source on that year?

**Comment by Arianya** [comment]
I don't see any harm in leaving it as loyalty implants on the old exhibit. In game lore as loosely managed as ours a retcon doesn't need to be a total removal from the nebulous past of the game, and we have plenty of other references in game to content that no longer exists or has changed substantially.

**Comment by ShizCalev** [comment]
@slignerd 
Official backstory, the tgstation wiki in numerous locations, as well as numerous references within the codebase itself.
