### ISSUE TITLE
clock cult: lizards spawn as human with lizard name on reebe

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#31226]
[Directions]: # (Include the Round ID from the Status panel or retrieve it from https://atlantaned.space/newSS13tools/round.php ! If you believe the issue to be caused by a testmerge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead. Explain your issue in detail, including the steps to reproduce it.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by The-clown-known-as-Pepe** [comment]
not a bug

**Comment by Y0SH1M4S73R** [comment]
This presents an interesting problem that has persisted ever since the initial testmerge. Humans with lizard names can only occur under the following situations:

1. A lizard given stable mutation toxin
2. A roundstart borg derived from a lizard character has their brain removed and cloned (might warrant a separate issue all on its own, edge case it might be)
3. Change Faces wizard event
4. Someone is violating the character naming rules
5. It's clock cult

Guess which of these doesn't involve players doing anything. As a consequence, this could lead to lizard-named humans being assumed clock cultists and immediately confirm the presence of the clock cult if the round type actually is clock cult. In my opinion, this is a bullshit tell.

The problem stems from the mechanism used to spawn the clock cultists. The other antag types that spawn humanized (wizard and ops) are renamed at roundstart, while clock cultists keep the names in their prefs. Sure you can argue that roundstart humanized-lizard clock cultists can just stay on Reebe and not go to the station, but what if ALL the roundstart clock cultists are humanized lizards? Does that mean that nobody should go to the station, or draw even more suspicion by skulking around as Unknowns?

As I see it, there are several solutions to this issue: 

1. Don't turn nonhuman clock cultists into humans.
2. Give nonhuman clock cultists random names once humanized.
3. Give ALL clock cultists random names.

I'm willing to implement whichever solution the maintainers like the most.

**Comment by BeeSting12** [comment]
@Xhuis said that the reason he implemented it this way is plasmamen would catch on fire when spawned, so the solution would be a) make plasmamen human, or b) make plasmamen spawn with their suits. He said he didn't know how species code works well enough to make the latter happen, so he just made everyone human.

**Comment by Y0SH1M4S73R** [comment]
@BeeSting12 Well if that was why @Xhuis implemented it that way, there's a simple fix. Define a plasmeme-specific clock cult outfit and give plasmeme clock cultists that outfit.

**Comment by BeeSting12** [comment]
Yeah that'd work. I don't really know how to do that so if you could that'd be great!

**Comment by Xhuis** [comment]
This was intentional, yes, given the nature of plasmamen. It was low on my priority list given that I just wanted to get the mode in. I can see about implementing this now.
