### ISSUE TITLE
Gygaxes with max tier parts can use mech overdrive forever. 

### ISSUE THREAD

**Issue by GuyonBroadway** [tgstation/tgstation#31385]
Build gygayx.

Use Quadratic capacitor and triphasic scanner.

Finish mech.

Get inside.

Activate overdrive mode.

https://youtu.be/gRRJczV85Ts

The gygax becomes a kill on contact wall-clipping rape machine being able to run forever.

Its probably due to whatever multiplier that multiplies the power cost of stepping when overdive mode is active only applying AFTER the step cost has been reduced to 0.

**Comment by ma44** [comment]
If the scanning module is tier 4, then the step_energy drain is 0. Equation for energy drain per step being  step_energy_drain = 20 - (5 * SM.rating) at 
`https://github.com/tgstation/tgstation/blob/d3dcc118ecb5f5410de684b1bb46289f8066ab23/code/game/mecha/mecha.dm#L212`

What's also neat to know, is that the energy drain per step is multiplied by 100, but since at tier 4 the energy drain becomes 0, then the mech will still never drain energy. 
Equation for energy drain
`https://github.com/tgstation/tgstation/blob/d1ae0a0c95d9b29d7d826ffd4736f01d80de1498/code/game/mecha/mecha_actions.dm#L206`

**Comment by kevinz000** [comment]
hahahaha wtf

**Comment by Armhulen** [comment]
DO NOT CHANGE THIS

**Comment by Armhulen** [comment]
wait can we make an admin variant that has 0 step cost

**Comment by Y0SH1M4S73R** [comment]
Mayyyyyyyyyybe.......... maybe a min() could be added to the gygax overdrive step drain?

**Comment by Anonmare** [comment]
You'll never catch me Krabs, not when I shift into MAXIMUM OVERDRIVE

**Comment by Y0SH1M4S73R** [comment]
@Anonmare I knew I should have gotten the turbo.
