### ISSUE TITLE
Reebe maxcap

### ISSUE THREAD

**Issue by pyronie** [tgstation/tgstation#31480]
ROUND ID: 77184
I was playing and there was a clock cult but the test merge clock cult
anyways so when we got near the ark someone threw a maxcap bomb and detonated, and it destroyed the whole of reebe
we need the maxcap hardcoded into reebe
otherwise we will have rounds where someone just builds a max cap, throws it through a portal, and blam.
clock cult destroyed mission accomplished

**Comment by ShizCalev** [comment]
So someone ran up to a portal leading to an alternate dimension filled with cultists trying to release their god who was hellbent on destroying everything, ultimately blowing them all up and ending the threat in one fell swoop?

Emergent gameplay imo.

**Comment by pyronie** [comment]
yes but that ruins the fun for the cultists and it kills everyone in reebe

**Comment by ShizCalev** [comment]
@Xhuis

**Comment by Xhuis** [comment]
If a bomb destroyed all of Reebe, an admin disabled the bomb cap. A 5/10/20(?) bomb is not enough to do that. 

This isn't an issue; toxins is by design capable of doing these things. I view it the cult's responsibility to neutralize toxins as a threat. If they continue being stopped by bombs literally every round I may buff them to force more interesting tactics from the crew.

**Comment by Robustin** [comment]
Rofl it was the cult who used the bombs (it was me).

I think the underlying issue is that stacking bombs enhances the explosion, one maxcap wouldn't have done what I did but I detonated 3 and it basically GG'd Reebe. 

What really sucks is we would have done except:

1) The fucking cogscarabs spammed tables in our own base so we literally couldn't move to the ark before the explosion and

2) All the cultists dying is an autolose for the cult. My bombs saved the ark but it killed the remaining cultists so we lost.

**Comment by Robustin** [comment]
I would've opened a PR to change #2 but I worry it might encourage more WMD cult strats where you just make Reebe uninhabitable via explosions/plasma. 

Then again in the game's current state it just encourages the opposite, 6 maxcaps in a bag thrown anywhere near the cult base would win every game every time because even if you don't kill the ark all you need to do is kill the cultists.

**Comment by Cyberboss** [comment]
Bombs do not stack, if multiple bombs are detonated, sure there will be multiple explosion "rings" but the radius will only be that of the largest bomb

**Comment by Robustin** [comment]
You're missing the point Cyber, getting hit with a light explosion near the outer limit isn't lethal.

Getting hit with 3 light explosions at the same time... GG. 

Stacking 3 bombs basically turns the maxcap from 5/10/20 into 20/20/20. 

Go to Reebe and hit the maxcap button in the dead center (of the cult side) multiple times with dummies placed around the edges and tell me who survives.

**Comment by Xhuis** [comment]
~~well dummies have godmode so technically they would all survive~~

**Comment by pyronie** [comment]
https://github.com/tgstation/tgstation/pull/31503

**Comment by PKPenguin321** [comment]
Robustin forget to put the "Fixes #31480" statement in his PR that fixed this. This is not an issue and should be closed
