### ISSUE TITLE
Immortal runic-changelings.

### ISSUE THREAD

**Issue by vitoras6** [tgstation/tgstation#31998]
[Directions]: # (Include the Round ID from the Status panel or retrieve it from https://atlantaned.space/newSS13tools/round.php ! If you believe the issue to be caused by a testmerge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead. Explain your issue in detail, including the steps to reproduce it.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)
If changeling transforms himself into the runic golem(through Xenobiology), he becomes Immortal because of abuse of transform(cast delay for jaunt resets if changeling transforms into other people).

**Comment by ExcessiveUseOfCobblestone** [comment]
can someone explain differently

**Comment by AnonymousNow** [comment]
From what I can gather, a changeling who has runic golem DNA can jaunt almost indefinitely by beginning a jaunt, transforming into someone else, and then immediately re-jaunting when the first jaunt wears off for an infinite chain, because using the changeling transform power resets the cooldown on the runed golem jaunt.

Is this right, Vitoras?

**Comment by XDTM** [comment]
makes sense, to solve this the runic golem skills should start on cooldown

**Comment by Darkgenerallord** [comment]
I reported this like six months ago, but you've more or less got it, Anon.
