### ISSUE TITLE
White ship console oddity in PubbyStation

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/tgstation#32136]
Server revision compiled on: 2017-10-26
7d098a

Looks like PubbyStation has more than 1 White Ships. The one I found is the old Box Station ship and it has White Ship Console and White Ship Navigation Computer. By default the nav computer is unusable and the main console says *missing*. I am able to unscrew the console screen and screw it back to bring up control of some other White Ship and the console does work. The Box White Ship however will not move.

**Comment by Mark9013100** [comment]
@WJohn

**Comment by WJohn** [comment]
i don't remember touching pubby's white ship console, or the possible locations it can fly to, nor did i touch the docking ports, i don't believe.

**Comment by Marflowerose** [comment]
Apparently the old box station white ship is a Ruin nowdays. The Pubby's own ship console was working fine just to reiterate, the oddity is that the Ruin ship also has console which can be used to move whatever is the actual White Ship of the map.

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/5c6903874ea5571b8bd6f28165d2e5e385b7fd4b/code/modules/ruins/spaceruin_code/whiteshipruin_box.dm

https://github.com/tgstation/tgstation/blob/b82f8582da970ae9b471aff3080fb8cadd8e9cb3/_maps/RandomRuins/SpaceRuins/whiteshipruin_box.dmm#L132

Might be because the shuttle_docker is a child? Thought changing the ID should have resolved this.

@ninjanomnom any ideas on this?

**Comment by Marflowerose** [comment]
Dunno if my explanation was shit but here's a video to illustrate: https://youtu.be/MLvIGH0DXa0

Also if you dismantle the white ship RUIN console you get regular white ship control circuit.

**Comment by ShizCalev** [comment]
@ninjanomnom Not sure how to resolve the missing thing, assuming it's due to a missing docking_port for the ruin?

**Comment by Marflowerose** [comment]
Last times I've tested it's been fixed so can probably close this
