### ISSUE TITLE
Servant golems can effectively "free" themselves by completing a shell, commiting suicide, and moving into the new body.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#32364]
What it says on the tin. They will be loyal to their previous self, not their original master. Golems also created by any other golems will be subservient to that golem, not that golem's human master.

GOLUM

**Comment by XDTM** [comment]
Master gave golem a <s>sock</s>shell!

**Comment by AnonymousNow** [comment]
Strange, since you'd think that "grandchild" golems would still know to follow "grandparent" creator commands.

Can we add a slavery lineage system? "You were created to serve X, who was created by Y who you must serve, who was created by Z who you must serve, who was created by A, who you must serve, who was created by B..."

Some time and a bunch of golems later...

"...who was created by P, who you must serve, who was created by Q, the overmaster, whom you must serve above all others."

Imagine chains of hundreds of golems. Beautiful.

**Comment by PKPenguin321** [comment]
It seems intentional by lore that creators aren't inherited by golems made by golems.
Would be easier to keep track of the ckey that creates a golem shell, and if a ckey tries entering the shell that it created it messages admins or something

**Comment by Firecage** [comment]
Ehhh, I don't really see that big of an issue with this though. And let's say its one of the multiple cases where, code wise, it is a servant Golem, and yet, like more than half of the times I have been a xenobio servant Golem, I was ended up being freed and told to do whatever by the creator(kinda like how Free Golems are free...), how would that then be handled?

**Comment by YakumoChen** [comment]
Sounds like an ahelpable issue if a golem, which is stated on spawn to have the sole directive of serving your master, is trying to intentionally subvert their directive.

**Comment by kevinz000** [comment]
sounds like an admin issue

**Comment by RemieRichards** [comment]
@PKPenguin321 
1. get a golem friend
2. make a shell for them
3. they free themselves since you made that shell
4. they make you a shell
5. you free yourself
6. ???
7. Bwoink.

**Comment by PKPenguin321** [comment]
Yeah it's not perfect
Not sure any fix is perfect really
Maybe if you wake up in a shell and your master is dead, you automatically get the objective to revive them in some way

**Comment by Armhulen** [comment]
admin issue really

**Comment by tralezab** [comment]
as i was about to close this issue i was GOING TO SAY...
there is already logging for new shells + suicides and as PKP says, any fix for this wouldn't be perfect.
