### ISSUE TITLE
All-In-One Grinders only grinding one instead of all

### ISSUE THREAD

**Issue by Ispiria** [tgstation/tgstation#32369]
During round 78272 I noticed as chef that my all-in-one grinder was only grinding one reagent at a time instead of all of them at once. With a whole ton of wheat needed to mass-produce my cakes this was obviously super frustrating and time-consuming; I don't know much about PR's or coding, but I can't seem to find any notes saying this was intentionally added.

**Comment by praisenarsie** [comment]
ironic

**Comment by ShizCalev** [comment]
fukken grinder memes lately

**Comment by Anonmare** [comment]
I didn't touch anything but the grinder list

**Comment by PKPenguin321** [comment]
Why does the grinder even have a set list instead of being generalized
Just allow it to take any items that are `small` sized or lower that have a `reagents` object in them, transfer all reagents to the beaker, then delete the item

**Comment by Anonmare** [comment]
Remie said the same but Iwouldn't know how to do that

**Comment by PKPenguin321** [comment]
It would be easy let me try

**Comment by PKPenguin321** [comment]
I spoke way too soon and answered my own question
A lot of the objects you can grind for reagents don't normally have reagents in them, for example getting iron from metal sheets
Could technically be fixed by adding reagents to all of those things...

**Comment by kingofkosmos** [comment]
That would sound like the optimal solution considering possible future features, like making all items, with fuel inside them, explode if they get too hot etc.

**Comment by PKPenguin321** [comment]
Consider looking at https://github.com/tgstation/tgstation/pull/32376 if you want to try fixing this

**Comment by vuonojenmustaturska** [comment]
if your grinding operation results in 51 of item, you can't grind more than one using a large beaker. Ask r&d for a bluespace one to get around this. 

Aside from sheets being a general pain in the ass that would require snowflake code wrt reagents, juices are another. Adding the respective juice as a reagent inside the fruits causes gameplay changes and logistical problems with botany, as growables are reagent holders themselves with 50/100 max capacity and a botanist generally wants to grow useful reagents rather than juices.

**Comment by Ratvar** [comment]
Botany can remove juices with DNA manipulator any moment if it wants to grow useful reagents, or even mix reagents itself in some empty alone plant
