### ISSUE TITLE
I think its known but overlays randomly dont update

### ISSUE THREAD

**Issue by Magikarpet** [tgstation/tgstation#32548]
overlays seems to be surpassing atmos in terms of weight sometimes even doubling how much lag/cpu they use compared to it(i dunno if its normal so I may as well make a note because i'm functionally retarded with code)

Overlays also seem to randomly break and not update at all. This can cause people to start naked with equipment on, it's been happening randomly for a short while now but it recently has become incredibly common.

**Comment by Bawhoppen** [comment]
During the testmerge you mean right?

**Comment by Magikarpet** [comment]
Right now on live without any testmerges IIRC but I forget because I'm dumb!

**Comment by praisenarsie** [comment]
known

**Comment by Cyberboss** [comment]
@MrStonedOne

**Comment by MrStonedOne** [comment]
>overlays seems to be surpassing atmos in terms of weight sometimes even doubling how much lag/cpu they use compared to it(i dunno if its normal so I may as well make a note because i'm functionally retarded with code)

overlays have priority 500, atmos has a priority of 20 and is a background subsystem (meaning it runs last, and the mc doesn't reserve it any time to run, it just runs if there's left over time) So thats likely to be part of the cause

anywho, last night ssoverlay ran into an issue of not updating for some reason, so I put the test merge back in yesterday after 2 days of no testmerge of the ssoverlays pr ***because*** they weren't updating.

So it's not likely to be related to my test merge.

Anywho, @Magikarpet general issue reports can be helpful, but at the end of the day we need data to fix the issue. I can glance at overlay code all day but if i don't know where to look I'm not likely to find the bug.

Example round ids can help so we can look at the logs and what not and try to find out what went wrong or at least figure out how to reproduce the issue.

**Comment by Magikarpet** [comment]
Fair enough, sorry about being dumb with the issue report. I went to go do something else then I remembered to make an issue on this in the back of my mind causing a lack of details.

**Comment by DaxDupont** [comment]
https://atlantaned.space/newSS13tools/round.php?round=78523

**Comment by Jalleo** [comment]
@MrStonedOne https://github.com/tgstation/tgstation/issues/32538
Related?
