### ISSUE TITLE
Particle Acceleration Rifle is janky as fuck

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#32543]
>Build particle acceleration rifle
>right click
>suddenly zoom out 50 miles
>turn mouse, spin at 2000rpm
>try to aim
>euclidean geometry breaks
>distant screaming and children crying
>ri͞ft t͟o t͝h͜e ̸O͜t̴her̶worl̸d ơpens̢, e̸͢ld̵̛r͢it̡̛c͞͝͡h͘͝͏ ̸̨́a̸͠b̸̨͏o̧͠͠m͢͡ì̴̀nàt̀į̧o͠͞ns ̴̕a̵̡f͜͠ḑ́s̴o͟͠ij̸̢ ̵t͘hr͏o͢͠ųgh̀ ̴҉an̛d̡ ̷͠ę̷̡vé̢͘r̡̕͠ý̷ò̶̴ne̷̕͘ ́̕͘n̨͡e̷ár̶̢b̸̀͡y ͞c͞o͟l̶l̸̛͢ą͘p͠s̨͢e̡ś ͢be̶c͠͠au͢͡s̷͜e̕͡͝ ̷̨͢k̢͘͡t̷o̢h͢r̷̴sr̀́͝

Please fix.

**Comment by WJohn** [comment]
the best setting i find is static + centered. this makes it instantly zoom out to its full view in one click instead of jankily jerking your screen around a dozen times as it "gradually" zooms out, and prevents your camera from swinging all over the place when you're moving around. frankly it should be the default setting.

**Comment by feemjmeem** [comment]
what is the point of this weapon

**Comment by praisenarsie** [comment]
@feemjmeem blame kevinz for the rnd powercreep
