### ISSUE TITLE
bee boxes dont make their free worker bee, meaning they can't do shit

### ISSUE THREAD

**Issue by Iamgoofball** [tgstation/tgstation#32609]
see title

**Comment by Cyberboss** [comment]
premade boxes or built ones? built ones require a queen to be inserted

**Comment by Cyberboss** [comment]
Reminder to myself to close this in a week if it's not reprod

**Comment by FantasticFwoosh** [comment]
As one of the few people who managed to actually run a functioning apiary that didn't self collapse into a horrendous heap, i can inform you that inserting all 3 trays at once will kill a hive.

- Each honey **tray** can sustain five bees, which require 1 active plant each, therefore you should never load in more than 2 trays in the existing hydroponics setup since 10 is a usual average maximum of plants that botanists juggle at once.

Proposed player solution is to create gaia tray starthistle plots (even just dirt plots made out of grass sand) with lifespan modified to a 100 for invulnerability around your apiary area if you want honey specifically.

- **_Itt the person who coded bees doesn't know how they work._**

Its actually the botanists job to kill bees if they are overpopulating the plant ratio at a given time so the hive doesn't self collapse from not being able to feed itself from lack of plant harvests.

**Comment by RemieRichards** [comment]
There is no such thing as a "temporary bee", you are talking out of your ass.

1 Honey frame is indeed 5 bees, but having more frames/more bees will not lead to their death/the collapse of the colony. In fact you SHOULD strive for maxing out your capacity of bees, as it means any beesources will be used on honeycomb, only being spent on bees when you drop below capacity.
"efficiency" wise, again, no, the more bees the better. Once a bee pollinates a plant, that plant cannot be polinated again for a short while (20 seconds), after that any bee can pollinate it again, more bees means there's more likely to be a bee next to the plant when it becomes available again, however if you're wanting to keep the AMOUNT of bees efficient (IE: not many beekeeper suits/don't want to get lynched) then yes, max capacity hives are overkill.

I should know, I coded them.

**Comment by RemieRichards** [comment]
@Cyberboss week

**Comment by FantasticFwoosh** [comment]
Hey didn't we quit @RemieRichards ?

Also your flat out statement about my remark is wrong, to clarify the bees put so  resources into making those workers that without a adequate ratio, if all the bees were to suddenly die it would collapse, ive seen it personally with my own eyes happen & produce no workers afterwards **hence this issue report exists**. Its the easiest way to flatline the bees, over-expand above hydroponics set limit and under feed the colony to 100% go into more bees while making no honeycomb with not enough plants.

2 or even 1 tray to the amount of plants and regular bee culls so plants aren't over-pollinated to the amount of plants you have & uninterrupted honeycomb production. Without culling go spare, so that's 1 tray guranteed for basic station hydroponics.

> Bees don't "feed" off of beesources

Poorly worded on my part then, but it is used for producing more bees and in real life honey is used to feed bee larva. No implication of maintenance upkeep in bees having a share of beesources meant, but meant from a purely production viewpoint.

- Easiest way to kill bees, release them onto the station public & they will literally all fly out of the window into the hallways to sting everyone in sight because Hydro is so overcrowded with 3 trays. 🎾 

- Worker bee is not free, don't collapse the hive numbers then steal the honey sticky fingered @RemieRichards  🐝 🍯 🐝 
______________________________________________

Alternatively you could just nerf it to 2 trays because more than 15 trays at any one time is unrealistic for station settings and you can just construct more hives.

**Comment by RemieRichards** [comment]
>if all the bees were to suddenly die

Yes, because as I've said, they won't do so on their own which is what you keep implying.
>functioning apiary that didn't self collapse
>inserting all 3 trays at once will kill a hive off the bat

Neither of these things you've said rely on outside influence, which is the only thing that can end a bee colony.

>Worker bee is not free

Your first worker bee is free, if there is no worker bee, you get one, it's as simple as that, a colony (that's a queen in an apiary) will always have one worker bee, if that one gets killed they will produce another.
However, all this does is keep the minimum at 1, if you already have bees, you won't get any free ones (unless somebody kills them all off, in which case you get another free one)

**Comment by AnturK** [comment]
Allegedly something was fixed here
