### ISSUE TITLE
Pipes on layers other then 2 can't be scanned/analyzed

### ISSUE THREAD

**Issue by Arianya** [tgstation/tgstation#32604]
Direction: Set up a pipe in layer 1 or 3, put gas in that pipe, try to scan pipe.

Expected Outcome: Output of pipe contents, pressure and temperature

Actual Outcome: None, nothing happens.

**Comment by praisenarsie** [comment]
@kevinz000 @duncathan

**Comment by Grazyn** [comment]
Also, sometimes you can analyze them, sometimes you can't, I have not found a way to reproduce it yet. They don't seem to transfer gas as well when they're in that state (e.g. if it's a heat exchange pipeline with hot gas in it, you'll see the bugged pipes stand out in the pipeline because they are the only ones not coloured according to the temperature).

**Comment by BeeSting12** [comment]
1 5 0 H O U R S

**Comment by nicbn** [comment]
I think that was fixed
