### ISSUE TITLE
White ship and new rooms cause bad shit

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/tgstation#32706]
Land White ship to lavaland: Someone expands the area with new rooms, accidentally sets part of white ship as the new room -> Moving the white ship now means the ship is permanently in transit and oh god there's lag and server crashed.

**Comment by ninjanomnom** [comment]
I'm not sure how the server would crash from an expanded shuttle area. I'll need to test this particular case but being stuck in transit normally happens because of a null destination turf.

**Comment by Marflowerose** [comment]
@ninjanomnom Borg was unable to fix the holes in the ship so something was funky

**Comment by Jord1081** [comment]
Im pretty sure that was me, basically I used a blueprint to try and make a new room outside of the white ship, but because the white ship was part of the new room, it stole the walls and doors from the ship. Meaning that the doors were no longer powered, and when the white ship took off the titanium walls and doors stayed on the ground. And I think I just couldn't fix the holes because you cant build on open space during the transit, not completely sure.

**Comment by ninjanomnom** [comment]
Yeah you wouldn't be able to fix the holes during transit like that. However when it finishes moving you could fix the walls and use a blueprint to expand the room inside to it.

I need to make a goggles mode that allows you to see rooms.

**Comment by praisenarsie** [comment]
https://github.com/tgstation/tgstation/issues/30981

this was what i was trying to explain in my issue ^
but alas me English not verily good.

**Comment by ninjanomnom** [comment]
The room changes fucking things up isn't a bug but the crash is, I need a round id for when it happened and/or reproduction steps

**Comment by ninjanomnom** [comment]
No one's said anything about how to reproduce the crash. Make a new issue with reproduction steps if it happens again.

The other parts of this issue relating to repair have had their code changed significantly and so isn't relevant anymore here. In particular you can't overlap shuttle areas with new areas.
