### ISSUE TITLE
chem dispensers cant be "opened" with screwdriver

### ISSUE THREAD

**Issue by Deitus** [tgstation/tgstation#32745]
as in title, unable to upgrade chem dispensers outside of bluespace rpd's due to this.

**Comment by PKPenguin321** [comment]
I believe this is intended

**Comment by epochayur** [comment]
I'm almost 100% positive you can't upgrade regular chem dispensers, only the portable chem dispensers and the chem master 3000s

**Comment by Deitus** [comment]
why is that a thing though? chem is usually something that can benefit from upgrades, and being unable to disassemble/upgrade roundstart chem machines seems kind of silly. is there a reason why this is intended?

**Comment by PKPenguin321** [comment]
It's just how it's been. It might be stupid but it's not a bug.

**Comment by Iamgoofball** [comment]
@Dorsisdwarf not a bug

**Comment by Deitus** [comment]
is there a reason not to change it other than it just being like that in the past?

**Comment by PKPenguin321** [comment]
No but the issues list is for the most part a place for bugs or unintended behavior and this is very much working as intended

**Comment by Deitus** [comment]
should i make a forum topic or something then?

**Comment by PKPenguin321** [comment]
I mean if you want

**Comment by SgtxRootbeer** [comment]
deitus, this is by design. we want chemists to have all the chems that a t3 chem dispenser can produce, but at round-start. we also want them to have a much larger energy reserve so that they can actually do their job instead of just waiting for the charge meter to fill.
now, we could just add a var-edited/special subtype to the map, which has the increased energy reserve and a larger array of chems, but then we have the issue of rnd wanting to steal the parts to speed up rnd. that and if the parts *aren't* stolen for rnd, but instead they are upgraded with t4s, then they would be a tad op.
the solution: make it more snowflakey by removing the maint panel, and our ability to swap parts out of it.

**Comment by vuonojenmustaturska** [comment]
The roundstart portable ones are gone so removing the portable typepath should be worth considering

**Comment by DaxDupont** [comment]
@vuonojenmustaturska the portable subtype was around before roundstart chemdispensers

**Comment by praisenarsie** [comment]
not a bug and dupe, check my issues and you'll find the dupe

**Comment by francinum** [comment]
This is no longer an issue, @KorPhaeron
