### ISSUE TITLE
MetaStation: can't interact with pump outside Turbine

### ISSUE THREAD

**Issue by joonoro** [tgstation/tgstation#32855]
Outside the Turbine room on MetaStation is a gas pump leading to the injector. The gas pump starts turned on, but if you replace it with a Volume Pump it is impossible to interact with (you can't turn it on or anything).

See image: https://i.imgur.com/MKtqqgy.png

Round ID: 78925
```
Server revision compiled on: 2017-11-18

The following pull requests are currently test merged:
#31026: '[READY] RND TECHWEBS + DEPARTMENTAL LATHES' by kevinz000 at commit eeb1c9

Based off origin/master commit: 1daf43
```

**Comment by WJohn** [comment]
This is likely because it is lacking an area around there. Super easy fix. Just extend the area a little further to cover the pipe and that's it.

**Comment by BeeSting12** [comment]
If Good First Issue is a replacement for the easy fix tag then I don't like it, I'd prefer easy fix

**Comment by DaxDupont** [comment]
Why was the label added after it was already fixed in the first place. 
![jzkjyj7 1](https://user-images.githubusercontent.com/17237624/32983369-a1f739f2-cc93-11e7-82b3-409294a033b9.png)
![rci17qd 1](https://user-images.githubusercontent.com/17237624/32983371-a8617b9a-cc93-11e7-8529-24aa09ea21f5.png)

**Comment by duncathan** [comment]
@BeeSting12 Good first issue integrates automatically with GitHub to show to newer contributors; that's why renamed the tag
