### ISSUE TITLE
Pandemic Machines Vaccine Production is broken, again

### ISSUE THREAD

**Issue by Chocodaemon** [tgstation/tgstation#33068]
Round ID: 79192

During a Nuke Op Round, procured a blood sample with Fungal TB antibodies from a cured crew member. The Holodeck Pandemic machine I then used did not produce any vaccine with the sample, only producing empty bottles, despite listing the identified vaccines in the machine UI.

**Comment by Potato-Masher** [comment]
I also can confirm this.

I also confirm that the round this happened on was total and absolute aids. The ops didn't even win somehow, even with a Mauler and over half the crew down with TB. The only chemist in sight went and made **_SPRAY TAN_** instead of treatment for TB, and proceeded to spray the TB infected people in medbay lobby with said spray tan.

**Comment by praisenarsie** [comment]
@XDTM

**Comment by DaxDupont** [comment]
This is a dupe from more than a month ago, https://github.com/tgstation/tgstation/issues/31534 
Thanks for fixing it @AnturK

**Comment by Chocodaemon** [comment]
It was broken, then fixed. I'm noting that it's broken again.

**Comment by Chocodaemon** [comment]
Round 79238, Pandemic machines still do not produce vaccine. Virus was GBS this time.

**Comment by ShizCalev** [comment]
Duplicate of #31534
