### ISSUE TITLE
[IC] Target ref pin is cleared when reagent pump pumps reagents

### ISSUE THREAD

**Issue by golfer45** [tgstation/tgstation#33471]
Round: 80055
Target ref pin is cleared when reagent pump pumps reagents.

**Comment by epochayur** [comment]
I can't seem to reproduce this, do you have any more details?

**Comment by golfer45** [comment]
Target was a smoke gen, source large beaker

**Comment by epochayur** [comment]
Alright, if I understand this correctly, you wired the output self-ref of the smoke generator to the input target ref of the reagent pump? The real problem is the smoke gen only outputting null as its self-ref. I'm honestly not sure what it's for or if there's any criteria where it's set to anything other than null. I might try to fix this but in the meantime, you can just get a ref of the smoke gen with the debugger and set it to the target ref of the pump without wiring anything and it should work fine.
