### ISSUE TITLE
Dragging between z-levels is messed up

### ISSUE THREAD

**Issue by Marflowerose** [tgstation/tgstation#33676]
Pull box/anything while you're jetpacking in space and the object you were pulling stops when you cross the border

**Comment by vuonojenmustaturska** [comment]
The bug is likely that https://github.com/tgstation/tgstation/blob/b2b3f7f7c0cbb357a5452bc6f31e3f8ee2b7d9ab/code/game/turfs/space/space.dm#L144 causes the pulled item to stop being pulled, however I would like to see the game log to see if there's actually a different bug/runtime, and you've provided no roundid. I'll take a look by weekend if no-one else fixes it first.
