### ISSUE TITLE
Plasmaman Augmentation

### ISSUE THREAD

**Issue by Hermod132** [tgstation/tgstation#33716]
A fully augmented plasmaman still requires a envirosuit, otherwise it will combust in the station's atmosphere. To me it seems that all body parts of a plasmaman being replaced should remove this downside.

**Comment by FantasticFwoosh** [comment]
Its pointless because the only way the plasmaman would heal is to apply cable wire & welding through the suit which if memory serves wouldn't be legal, so the *still internally on fire* plasmaperson would have to take off their suit.

Disallow plasmapeople from attaining augmentations without going a wonky route of turning into another race, getting the procedure & then turning into a plasmaman

**Comment by Peeping-Peacock** [comment]
Just had the same thing happen to me, its nonsensical that you still catch fire fully aug'd.

**Comment by adamkad1** [comment]
Fun thing is plasmamen dont need to breathe plasma when they get normal lungs
