### ISSUE TITLE
Punching a abandoned crate with a mech will blow you up and dismember you. Inside the mech.

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#33809]
And the mech is completely unharmed.

**Comment by vuonojenmustaturska** [comment]
i took a look at the code, and i think this is because mechas by design only give you a chance equal to the mecha's deflection chance of reducing the severity of the explosion that will recurse into their contents. And also because explosions are RNG central where less severe effects can be more fatal depending on a dice roll.

I kind of want to refactor explosions in a big way to be deterministic in 99% of cases, to the point of making ex_act() and contents_explosion() conditional like the canatmospass var and proc. I just haven't started or managed to convince anyone on coderbus that this is a good idea.

**Comment by Buggy123** [comment]
tbh abandoned crates are kinda a weird and stale meme, especially since 90% of the time the only one anyone interacts with is the lavaland one. I'm not even sure if you can defuse them, never even tried.

I mean, a 1/100 chance for a katana? Bitch i just killed a dragon that dropped a bottle of blood and now i can turn into a fucking _dragon_ i don't give a shit about a katana.

**Comment by newfren** [comment]
the abandoned crates are just a mastermind game my dude

**Comment by Barhandar** [comment]
The problem isn't even that you get dismembered while inside, the problem is that mech is _completely unharmed by the explosion_.

**Comment by kriskog** [comment]
It hurts the mech, and the pilot. Has a chance of dismembering. Just how explosions and mechs work currently.
