### ISSUE TITLE
Lavaland syndie base: Minor ash storm issue

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#34014]
Related to: #33962
@WJohn

**Issue**:
During ash storms, these two outdoor tiles aren't affected by the storm (no damage to players on the tile, no ash storm effect overlay):
https://i.imgur.com/wLEBkEl.jpg

**Comment by WJohn** [comment]
Can't do much about that. That's because the lavaland area is not powered, and in order for these lights to function they must take on the area of the bar next to them or wherever, which does not suffer from ash storms. The mining base also has this issue. I'd need a powered lavaland area to place on top of this to fix it (as well as the mining base)

**Comment by ShizCalev** [comment]
Happens with most of the ruins with external lights (clown ruins, animal shelter, ect)

**Comment by FantasticFwoosh** [comment]
Run some floodlight objects through it @WJohn under a wire connection, a APC would not be required. Same goes for the other ruins.

**Comment by WJohn** [comment]
floodlights are powerful as hell and block movement so in some instances they're not an option.

**Comment by 81Denton** [comment]
I'll close this since I don't see a proper way this can be fixed (same with #32600).
