### ISSUE TITLE
Diagonal movement makes gulag escapes too easy

### ISSUE THREAD

**Issue by jughu** [tgstation/tgstation#34153]
You only take damage for walking 1 lava tile instead of the usual two
making escapes way easier with no risk involved of hitting crit at all.

**Comment by praisenarsie** [comment]
@ninjanomnom

**Comment by ChangelingRain** [comment]
If diagonal movement isn't moving over both tiles, that's a pretty big issue.

**Comment by Ordonis** [comment]
Out of curiosity, which tiles would it be moving over? Because in diagonal movement, there's the starting and ending tile, but there are two paths one can take to get to the same place using street-grid movement; unless diagonal movement just picks one path arbitrarily to follow, then I think there would be a risk of taking the equivalent of three tiles of damage; I'll need to test this with bananas or beartraps.

**Comment by Cyberboss** [comment]
@AnturK fixed by #34573 right?

**Comment by AnturK** [comment]
Nope that's unrelated.

**Comment by SpaceManiac** [comment]
Not actually true as far as I can tell in testing
