### ISSUE TITLE
plasma fire and other atmospheric dangers shouldnt work on reebe

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#34251]
enclosed place with no escape + fire = bad thing

**Comment by WJohn** [comment]
to be fair a lot of the time it kills the attackers

**Comment by Tlaltecuhtli** [comment]
it was being used by clocks, they can just wall off the plasma fire place and watch crew teleing and burn alive

**Comment by Buggy123** [comment]
On one hand I agree, but on the other I don't think it should be _completely_ disabled because, if the clock cult are retarded and don't declare war, using plasma _against them_ is also a valid tactic.

In essence the problem with plasmafires is that some locations are vital, irreplacable, and completely static. There are, practically speaking, very few gamemode-central things that _cannot move_. Nar-siean Cultists can make new bases/summoning runes if their base gets bombed. Revs don't have a central anything. Rogue AIs can have a borg relocate them and fire/space doesn't bother them anyway. Comms consoles can be built or moved, only need 1 hazard-proofed person to reach them to serve their purpose, and there are alternative and backup methods of calling the shuttle.

Whatever the situation, you don't necessarily _need_ to be in a location. It might be annoying, or a pain, or even nigh impossible to completely avoid that location for whatever you're doing, but ultimately you can _go somewhere else_.

Put simply, clockwork cult is _completely_ unlike any other gamemode in that it is massively, completely focused around a singular, static, absolutely positively 100% completely immovable unchangable resolute location. You cannot move the ark. You cannot move the teleport consoles. You cannot move the crew's teleport-in location. You cannot modify the shape of the ark, you cannot make new rooms, you cannot. The _closest_ thing that exists to this is the summoning room limitations Nar-siean cultists get, and that _also_ fucks them over half the time because they get shit like "Armory, Supermatter Engine".

The fact that clockwork cult is stationary is such a big deal because its possible to make _massive areas completely uninhabitable for anyone unprepared, and its usually impossible to prepare everyone for these hazards even if you know about them beforehand_. There literally _are not_ enough fire-**proof** firesuits or spacesuits for even 1/4th of a typical crew, cargo cannot order more of the former, never orders more of the latter, and with clock cult you almost certainly don't know you'll need them before you **permanently, irrevocably and immediately** teleport into whatever stationary hazard you might find yourself in.

Reebee _slightly_ mitigates this because you cannot open a hole to space, and the atmosphere is habitable by _default_ so any sort of breach to the surroundings will slowly stabilize things. Though, I'd argue it balances this out by not having a active atmosphere correction system. But regardless, it is entirely possible to drop a hellfoam grenade, plasma can and lighter, or any number of other things in a vital area, and almost unavoidable hurt or kill servants teleporting to the ark or crew teleporting to the station.

However, at the same time atmospheric hazards still have a role to play, because if you don't _literally teleport into them_ they can serve as a unique and mitigatable hazard to accompany all the other possibilites cultists have, and it serves as a way for the crew themselves to fight back against cultists, either with voice-activated hellfoam grenades planted on seemingly-ideal convertees, or flamethrowers, or any number of things.

I'd argue that the issue is largest with lighting plasmafires in the spawn area the crew teleports into. Even if you can't push a open plasma can and a welder through now, you can still put a can near the barrier, wall it off, and open it. To solve this, I have a few suggestions, pick and choose as desired:


# 1: LET THE CREW TELEPORT BACK TO THE FUCKING STATION
Make it drop you in a random-but-habitable location of the station, if you want to avoid supplying people with easy logistical support from the station (eg medbay). But the complete inability of the crew to assess and react to the situation on the ark _beforehand_ can easily fuck them over with no counter except the absurd "prepare for literally everything". This change would render plasma fires far less deadly because you could run through the portal, look at the blazing fire now surrounding you for all of half a second, run back through, drop and roll, and yell "GET SOME FUCKING FIRESUITS" over the comms. Alternatively, you could go through, look up and see that there is a raging plasma fire just outside of the spawn area, and go back and find some firesuits and toss them through, turning a tactic that prevents 90% of the crew from participating in the assault, to a simple but effective delaying tactic that hinges on how effectively the crew reacts.


# 2: PROTECT THE ARK ROOM AND SERVANTS ROOMS FROM HAZARDS

The servants can end up in the exact same boat. The ark room should be protected from fire because servants teleport into there, and the camera room, etc because those are also 100% vital.


# 3: ADD ACTIVE-ATMOSPHERIC CORRECTION TO REBEE. AKA SCRUBBERS.

A fire on the station will not permanently render a area hot without a moderate or large amount of prepwork. A fire will either be cleaned out in a few minutes by the atmospheric system, or burn a hole to space which sucks it all out and replaces it with much less hazardous vacuum and cold. Reebee should also have some sort of active system that can correct fires.

 # 4: MAKE CLOCKWORK CULT NOT COMPLETELY STATIC

Way, way more difficult and balance changing than all other options, this would mean allowing the relocation of the ark, construction of additional rooms, etc. If the crew can just build a lattice across the white space of Reebee's dimension, it doesn't matter so much if half of Reebee is on fire.



Do at least _one_ of these and this won't be as much of a issue.

**Comment by ShizCalev** [comment]
Use the forum for this.
