### ISSUE TITLE
Microwaving an oxygen tank bomb empties out all the contents of it.

### ISSUE THREAD

**Issue by yorii** [tgstation/tgstation#34402]
Sorry no round ID as I just remembered this, but it's easily reproduced.

[Reproduction]:  Strapping a timer-igniter assembly to an oxygen tank and microwaving it.

**Comment by nicbn** [comment]
Tested it locally, unable to reproduce the issue

**Comment by Buggy123** [comment]
Even if this is a issue... why?

We should just make microwaves explode if you put a _metal tank full of compressed gas_ into them.

**Comment by Tlaltecuhtli** [comment]
make the gas inside heat up

**Comment by DaedalusGame** [comment]
microwaves already explode if you put metal in them don't they?

**Comment by Buggy123** [comment]
Ingame or in real life?

In real life it's... complicated. I don't fully understand the math behind it, but smooth metal=okay, not smooth metal=uneven electric charge buildup, resulting in sparking, etc.

And regardless of whatever you put in it the energy it puts out **has** to go _somewhere_, and SS13 microwaves are fairly beefy (hot pocket, ~1-2 minutes (defrosted 1100 watts), ~10 seconds in SS13), so you are gonna melt or fry _something_ within a short order of time, and because we're on deathtrap station 13 that means it has to violently explode.

**Comment by DaedalusGame** [comment]
Ingame, I think they make a 0,1,2 if you put metallic stuff in them?

**Comment by Buggy123** [comment]
`		var/metal = 0
		for(var/obj/item/O in contents)
			O.microwave_act(src)
			if(O.materials[MAT_METAL])
				metal += O.materials[MAT_METAL]

		if(metal)
			visible_message("<span class='warning'>Sparks fly around [src]!</span>")
			if(prob(max(metal/2, 33)))
				explosion(loc,0,1,2)
			broke()`

Yep, looks like it.
