### ISSUE TITLE
Cuck cult vitality matrix is instagibbing simplemobs AND PLAYER ZOMBIES.

### ISSUE THREAD

**Issue by YogsMcree** [tgstation/tgstation#34597]
round id 82155 post station time 12:35, war cult.
Vitality memetrixes are instantly dusting Player zombies and player simplemobs created by the wabbajack statue. Seems REALLY OP considering how long it takes to dust a normal human player. Intended?

**Comment by YogsMcree** [comment]
@Xhuis

**Comment by Xhuis** [comment]
I don't know why this is happening, because vitality matrices are hardcoded to dust things that are considered dead. I don't think player zombies are considered as such (they might...?) but if they are it would make sense for them to be killed instantly. Simple mobs I'm not sure about.

**Comment by YogsMcree** [comment]
So if a player were to suicide and be dragged across, it would dust the corpse instantly? That would make sense for why zombies get dusted, but their flavor text suggests their heart is still beating. 
Sounds like theres no REAL issue, but its just a bit of "this feels really shitty but makes sense" gameplay

**Comment by Xhuis** [comment]
I don't actually know if zombies are considered dead by the code. Given how mob code works I would think not, which is why I'm confused.

**Comment by Ordonis** [comment]
Is there a difference between the attribute 'dead' and the actual state of being dead? Because I could see zambies being considered 'dead' for the purposes of holywater, chem reactions, and so on, giving them a tag normally reserved for things which are dead in the sense of no longer moving. I don't know how chem reactions work for zombies; I would think that if they have the mob + isalive status, they shouldn't dust, but if they for whatever reason don't have isalive, then their being dusted makes sense.

**Comment by QualityVan** [comment]
Were they horizontal zombies or upright zombies? Because zombies die when they're killed, they just get better shortly afterwards.

**Comment by ExcessiveUseOfCobblestone** [comment]
https://github.com/tgstation/tgstation/blob/e093857c11eda5ca3d291d5bfd45c4d8cd6ad0ca/code/game/gamemodes/clock_cult/clock_effects/clock_sigils.dm#L293

???
