### ISSUE TITLE
Wizard summon guns is spawning abstract gun paths.

### ISSUE THREAD

**Issue by biznessmannnn** [tgstation/tgstation#34962]
[Round ID]: 82554
Issue: If you hold a somatoray in your hand as a botanist and you become a survivalist, there is no gun spawned for you. (Server time was waround 12:10)

**Comment by optimumtact** [comment]
Round ID was 82554 basil, a gun was spawned from wiz summon guns but had an invalid icon state as per viewvar

![](https://file.house/DC1Z.png)


/obj/item/gun/ballistic/automatic/shotgun was the path, and it appears to be an abstract path used for hosting automatic shotguns

**Comment by WJohn** [comment]
I don't know if there's a great way to fix this because in a lot of places, some parent paths don't actually really contain anything themselves, while others are fully functional and intended to be used. Blacklist, maybe? Whitelist, maybe? Though we'll periodically have to update it to include new guns, we won't run into this problem again down the line as with a blacklist.

**Comment by SpaceManiac** [comment]
I saw this somewhere in the code but I forget where, but one possible pattern is:

```
/atom
    var/const/abstract
/obj/gun
    abstract = /obj/gun
/obj/gun/mars
```

Then to check if a specific typepath is abstract, check `T == initial(T.abstract)`.

**Comment by coiax** [comment]
The summon guns list is just a list of types, and apparently one of the types stopped working.
