### ISSUE TITLE
Can't take control of reformed Revenant as original controller

### ISSUE THREAD

**Issue by Hathkar** [tgstation/tgstation#35390]
Issue reported from  Round ID: 83183 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Died as a revenant, and my ashes/residue wasn't scattered. The revenant reformed with one of those "Would you like to play as X" popping up, instead of just giving me control back. Admin said that "It couldn't find the old client".

**Comment by ExcessiveUseOfCobblestone** [comment]
On rev's `death()` it needs to add the mob to the dead_mob_list since that's where it searches to see if the client exists.

**Comment by ExcessiveUseOfCobblestone** [comment]
@Armhulen free gbp lol

**Comment by Hathkar** [comment]
Also on a similar note, I couldn't talk in deadchat either. I could see it, though.

**Comment by ExcessiveUseOfCobblestone** [comment]
Sounds like you were stuck in the body so what I suggested is a bandaid fix to whatever the actual issue is 😢

**Comment by YPOQ** [comment]
revenants force the ghost out when they die
https://github.com/tgstation/tgstation/blob/75bbe88caf8ef898ea7497f78f5e640cfb91fdc5/code/modules/antagonists/revenant/revenant.dm#L226

 #33744 is why you can't talk in dead chat

I think this might be because the admin used to vv to set the rev's ckey but I'll have to do some more investigation.

**Comment by YPOQ** [comment]
Oh it's because he reconnected while reviving. Refactoring the code to use grab_ghost (or whatever it's called) instead of manually copying the client would fix this.
