### ISSUE TITLE
Can we get everything on the same Lag page?

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#35526]
Let me tell you the story of approx 80% of the times I've died on lavaland:

1: Fighting a mega, doing perfectly fine because I've killed nearly two fucking hundred of these shits.
2: Its dying like clockwork.
3: SUDDEN LAG!
4: Me, a mob/living/carbon/human, starts moving extremely slowly/effectively frozen in place.
5: Megafauna, a mob/living/simple_animal, completely unaffected.
6: Swoop/charge/whatever, completely unaffected.
7: Instantly gibbed because that's what happens if you get hit by a swoop/charge/whatever.

I'm getting tired of being instantly gibbed because of, effectively, RNG. If there was a random event that picked 1 person on the station and immediately gibbed them, we wouldn't think that _that_ was okay. Is there _anything_ we can do to fix this shit?

We don't have to fix lag, we just have to fix the bizarrely uneven lag. Even fixing it so that it properly affects swoops/charges would be enough.

Yes, I Ded. A lot. It's getting old.

**Comment by Kromgar** [comment]
HAd the same happen to me fighting an Ash Drake when the supermatter delammed. I could barely move but the drake which thankfully wasnt swooping was able to run up and bite me twice doing massive damage while I could barely move

**Comment by ChangelingRain** [comment]
this is technically fixable but for practical purpose it'll never be fixed.

A: if it's client lag, you're fucked. there's no way we can fix your internet.
B: if it's game lag, the best we could do is adjust the swoop speed based on... I think the best choice would be perceived time dilation; we can't adjust mob movement based on game lag, since we use byond's internal movement procs to have mobs move.

Why can't we roll our own movement proc to move mobs in your direction? because pathfinding algorithms are costly assholes.

**Comment by Buggy123** [comment]
Its game lag I assure you, I have a consistent internet connection and <30ms ping.

**Comment by MrStonedOne** [comment]
@KorPhaeron to solve this you would have to put every part of simple mob's attack sequence behind add_timer so it processes intune with the mc. sleeps would not only be unaffected by mc lag, but would even increase mc lag.
