### ISSUE TITLE
Hallucination noises wont stop even in death and new life.

### ISSUE THREAD

**Issue by Teepeepee** [tgstation/tgstation#35534]
roundID:83421
I was assistant, broke into vault and started cracking the safe, I was hearing hallucination noises already (well, actually only emergency shuttle has docked with the station, new command report and emergency shuttle has been called, only those three sounds, over and over), I'm guessing cause the vault core thingy emits radiation, not sure about that. Midway through it an explosion went off in sec that reached the vault and I died, as ghost, the noises still wouldn't stop, I bared with it for a while until a drone shell was available, and once I had spawned as drone they still kept on playing. Admins at the time suggested I reconnect and restart dreamseeker once that failed (this also failed to stop the issue).

**Comment by praisenarsie** [comment]
@XDTM

**Comment by XDTM** [comment]
the sounds repeating seems really odd, i have no clue about what could be causing that.

@Buggy123 As for hallucinations sticking around too long, it's because hallucinations don't tick down over time; instead, every hallucination reduces the value based on its severity. And to avoid hallucinations being _too_ obvious, there's some time between each hallucination. The only thing i can think of is to increase the cost of hallucinations.

**Comment by Buggy123** [comment]
Okay, that makes more sense. I don't think that's too bad but there should still be more ways to purge it, and Panacea should _definitely_ purge it.

**Comment by timothymtorres** [comment]
This probably fixed with #56422 or #55927.  If this problem still persists ping me and I will reopen this.
