### ISSUE TITLE
Petsplosion triggers infinite loop detection in roundstart logout report

### ISSUE THREAD

**Issue by SpaceManiac** [tgstation/tgstation#35715]
```
Infinite loop suspected--switching proc to background.
If it is not an infinite loop, either do 'set background=1' or set world.loop_checks=0.
proc name: display roundstart logout report (/proc/display_roundstart_logout_report)
  source file: game_mode.dm,397
  usr: (src)
  src: null
  call stack:
display roundstart logout report()
/datum/callback (/datum/callback): InvokeAsync()
Timer (/datum/controller/subsystem/timer): fire(0)
Timer (/datum/controller/subsystem/timer): ignite(0)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop()
Master (/datum/controller/master): StartProcessing(0)
```

85c5a20e756ab7030af6c0b65fac843552bbfa82

**Comment by DaedalusGame** [comment]
Petsplosion?

**Comment by SpaceManiac** [comment]
Wizard event that generates a lot of copies of all the simple_animals on the station.

**Comment by DaedalusGame** [comment]
ah

**Comment by Ordonis** [comment]
Frankly are we sure that it's not causing a processing demand similar to that of an infinite loop, or running into some issue where it duplicates all the simple animals and doesn't mark them as duplicates, so it keeps duplicating until it overflows or crashes? Because duplication madness absolutely seems like the type of thing to cause infinite loops.

**Comment by SpaceManiac** [comment]
I think what's probably happening is that the roundstart logout report is written inefficiently and runs for a long time if there are a lot of mobs, long enough to trigger the warning.
