### ISSUE TITLE
Occasionally, some people on the server will lag immensely for no apparent reason.

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#36052]
Sometimes, a lag wave will hit the server and only affect some people, driving their pings into the thousands and making the game unplayable for 5-10 minutes.

Has happened in many rounds, but one example is 84342

**Comment by praisenarsie** [comment]
@MrStonedOne

**Comment by Jordie0608** [comment]
I'd imagine this is likely unrelated to the game and a network issue.
Do you know names of those who are affected?
Is it the same people each time?
It'd be helpful to see a route trace comparison between normal play and when they'e ping-spiking.

**Comment by Buggy123** [comment]
It seems to be the same people yes, at the very least it seems that all of the spikes have affected _me_. It'd be rather strange if it was a network issue, or at least a network issue on the user's end, since it affects quite a few people and it only recently emerged, and for some weird reason only traffic _to_ the server is inhibited, not _from_ the server.

**Comment by Tlaltecuhtli** [comment]
happened to me too, another similar problem that happened before (right now doesnt happen anymore ) was that i couldnt join the server (others were fine)

**Comment by AlexTheSysop42** [comment]
happened to me as well twice, one during a round yesterday and one a while before that when I first found out about the lobotomy trick

**Comment by MrStonedOne** [comment]
>It'd be rather strange if it was a network issue, or at least a network issue on the user's end, since it affects quite a few people and it only recently emerged, and for some weird reason only traffic to the server is inhibited

That sounds par for the course of a network issue.

Very likely its mid route so only certain packets routed thru certain middle man routers are affected.

This could be a simple as some dust on the connector of some router only impacting transmission during high peak times because of heat causing it to shift from expansion and contraction and it goes away shortly after because the issue causes the router to cool down since it receives less good packets to process.

**Comment by Supermichael777** [comment]
God damn is it annoying.

**Comment by AlexTheSysop42** [comment]
>thousands

*HUNDRED THOUSANDS

**Comment by Dorsisdwarf** [comment]
i doubt we can fix this but idk what to tag it

**Comment by MrStonedOne** [comment]
the proper tag is blame mso

**Comment by Teepeepee** [comment]
I have this same issue, with the added detail that I'm connecting from another country, which I guess is relevant. Every other thing that is internet related works nornally, but my game client stays at 1-5k ms for long periods of time. Is it a server side issue or is it something with the way my third world internet reaches it?

**Comment by Jordie0608** [comment]
While you're playing the game normally, run tracert and pathping to the servers:
1. Run > cmd.exe
2. Type `tracert sybil.tgstation13.org` or `tracert bagil.tgstation13.org` and hit enter
3. Type `pathping sybil.tgstation13.org` or `pathping bagil.tgstation13.org` and hit enter
4. Observe and save results
Then when your game starts ping-spiking, run another tracert as above and compare the two.
Post results.

**Comment by Sharkeybtm** [comment]
6    43 ms    74 ms    45 ms  gar24.attga.ip.att.net [12.122.141.181]
  7    72 ms    61 ms   194 ms  be-202-pe03.56marietta.ga.ibone.comcast.net [75.149.228.85]
  8    57 ms    43 ms    66 ms  be-11486-cr02.56marietta.ga.ibone.comcast.net [68.86.85.253]
  9    53 ms    69 ms   116 ms  be-11422-cr02.miami.fl.ibone.comcast.net [68.86.84.154]
 10     *        *        *     Request timed out.
 11     *        *        *     Request timed out.
 12     *        *        *     Request timed out.
 13     *        *        *     Request timed out.
 14     *        *        *     Request timed out.
 15     *        *        *     Request timed out.
 16     *        *        *     Request timed out.
 17     *        *        *     Request timed out.
 18     *        *        *     Request timed out.
 19     *        *        *     Request timed out.
 20     *        *        *     Request timed out.
 21     *        *       58 ms  game.tgstation13.org [45.58.127.134]
  
Omitted the first five as they had good pings and I didnt want to post my IP/

**Comment by AlexTheSysop42** [comment]
c o m c a s t

I also did a tracert at one point, the error was also around where it is here

**Comment by Tlaltecuhtli** [comment]
just tracertd on a lag spike same thing

**Comment by MrStonedOne** [comment]
I need the exact actual tracerts to send to the datacenter provider, "same thing" tells them nothing and at the end of the day they have to send these tracerts to their transit provider to prove to their transit provider there is an issue affecting multiple people to get anything done.

Actually tracetrs aren't even that good of a tool, WinMTR http://winmtr.net/winmtr-v0-92-now-available/ is better because it does more then 3 pings on each host.

I've been too busy during the day when this happens to monitor for this myself but the more tracerts and mtrs (they prefer mtrs) you can get me the better the datacenter can solve the issue, even if its the same thing, proof that it happens regularly will help them in negotiating with the transit provider. (and will help me in making them discount next month's bill)

**Comment by MrStonedOne** [comment]
Don't worry guys! I have five different nodes all doing MTR reports on the game server,, while the game server does an mtr report on all 5 nodes, now we can finally see all the info the datacenter needs to fix the issue.

Cue the issue not triggering...

**Comment by Jalleo** [comment]
Heh.

**Comment by MrStonedOne** [comment]
![image](https://user-images.githubusercontent.com/7069733/37813571-eab4d71c-2e22-11e8-9011-9933105cc981.png)
This is fixed
