### ISSUE TITLE
Roundstart traits don't transfer when slimepeople split bodies

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#36278]
Revision: 55f5870b7bf48a5a17b46386e8bf6244978d751f

When a slimeperson splits bodies, their roundstart traits "stick" with the original body and don't get copied to the spares. They don't transfer on body swap either.

Edit: Can someone test if this applies to people who get borged too?

**Comment by ExcessiveUseOfCobblestone** [comment]
why does a borg need those traits?

**Comment by 81Denton** [comment]
I think it would be interesting if traits like pacifism transfered to borgs. Or maybe just obnoxious and code bloat.

**Comment by ExcessiveUseOfCobblestone** [comment]
you're evil

**Comment by Rinoka** [comment]
This happens because traits as defined in _trait.dm are applied on roundstart, as far as I can tell, by being baked into the mob, which normally should work.

The cloner takes the list of traits (presumbly from the corpse) and re-initializes them on the new mob using a new trait generation loop.

I was skimming Jellycode and it doesn't really look like there's something to load the roundstart traits on new bodies - not sure if this is something to ping Xhius over as an oversight or if it's an oversight from back when mob traits became a thing.

**Comment by Xhuis** [comment]
This is an oversight, I can patch it up.

**Comment by Rinoka** [comment]
@Xhuis 

Sounds good. Slight oversight note: mob storage like this means I could, in theory, perform brain surgery and shove someone's brain in a humanized monkey body to help them get over their pacifism.

Not sure if you've error trapped against that (I haven't skimmed rebraining code) but I thought I should point that out. Might be better to bake certain traits into the mind (ie personality traits like pacifism) and have them carry over on mind relocation.

**Comment by Xhuis** [comment]
That would likely allow circumventation of traits, but it would also remove all the positives, thus giving them a "blank slate", per se. It doesn't currently break balance enough for me to be super worried about, since it's a lot of effort just to be the same as a normal person.
