### ISSUE TITLE
Became Borged via AI machine, Got blown up, No MMI.

### ISSUE THREAD

**Issue by Brimcon** [tgstation/tgstation#36310]
Issue reported from  Round ID: 84728 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])

Reporting client version: 512

Oops! Something went very wrong, your MMI was unable to receive your mind. You have been ghosted. Please make a bug report so we can fix this bug.

Was Pathfinder - 13, forced as a Borg due to walking into the Auto Borger machine. 

[Reproduction]: Get transformed into a Borg via Auto Borger, Get blown up by bomb or some other explosive device.

**Comment by XDTM** [comment]
Emagged borgs disintegrate the brain if blown remotely.

**Comment by Anonmare** [comment]
The autoborger doesn't emag you however

Also when you say blown up, do you mean via console or by a bomb?

**Comment by Brimcon** [comment]
Bomb. Not exactly sure WHAT killed me but I think I was gibbed, but I didn't even leave behind parts.

**Comment by Anonmare** [comment]
If you were in the devestation zone then you probably got gibbed. 

Usually it leaves an MMI behind, unless you got caught in two separate explosions, one after the other

**Comment by ExcessiveUseOfCobblestone** [comment]
an AI can hack you which functions equivalent to the emag right?

**Comment by Anonmare** [comment]
Yeah it's effectively an emag, even makes MMIs irretrievable so that it can cover its tracks.

**Comment by ExcessiveUseOfCobblestone** [comment]
so did the AI hack op?

**Comment by Brimcon** [comment]
Not hacked as far as I was aware. I suspect there was two explosions near engineering. Not sure why there was though.

**Comment by ExcessiveUseOfCobblestone** [comment]
prob a bomb + SM

**Comment by YPOQ** [comment]
This error happens if the cyborg has an mmi but not a brainmob at the time it is destroyed.
https://github.com/tgstation/tgstation/blob/f300a5c155c6bc69fd2a158bc1f79dca2b7ce6d8/code/modules/mob/living/silicon/robot/robot.dm#L174

From what I can tell this can happen if a level 2 explosion hits the cyborg and does 200+ damage to the brain_item (enough to destroy an item) but not the mmi.
https://github.com/tgstation/tgstation/blob/f300a5c155c6bc69fd2a158bc1f79dca2b7ce6d8/code/game/objects/obj_defense.dm#L69

The brainmob itself is immune to explosions but destroying the brain_item will destroy the brainmob.

See also #33175
