### ISSUE TITLE
Pressure Tanks can't be analyzed

### ISSUE THREAD

**Issue by Davidj361** [tgstation/tgstation#36448]
[Round ID]: 85024

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)
1. Go to the turbine room on box station. (Probably the same happens with all pressure tanks)
2. Try to scan the Pressure Tank (Plasma) in there with an analyzer or PDA Gas Scan.
3. Be unable to analyze the Pressure Tank.

**Comment by ExcessiveUseOfCobblestone** [comment]
Testmerges and/or RID?

**Comment by Davidj361** [comment]
On the server, live.

**Comment by SpaceManiac** [comment]
Don't worry too much about RID, it's been like this for months and is just a code architecture thing. They can't be analyzed in the same way that connectors, vents, pumps, freezers, etc. can't be analyzed. You don't need to analyze it most of the time anyways, it equalizes with any pipe it's connected to. It might be possible to add analysis for unary components in general since they only have one air mix, though I'm not sure how useful it'd be.

**Comment by Davidj361** [comment]
I put [Round ID]: 85024 but the comment doesn't display it, wtf?

**Comment by SpaceManiac** [comment]
Markdown formatting `[something]: something else` is hidden until `[something]` is referred to at another location.

**Comment by praisenarsie** [comment]
p sure this is intended and i know you can't analyze them
