### ISSUE TITLE
AIs can see wall-mounted objects inside rooms with no cameras

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#36527]
Revision: 77bb4d70e1a7d39f347bf666d742b37c82efb436

On Meta, AIs can view and access the prisoner education chamber's bolt button through the wall.

![meta bolt](https://user-images.githubusercontent.com/32391752/37592473-0cd870b2-2b6f-11e8-8705-52c523affbd5.JPG)

**Comment by MimicFaux** [comment]
Be amusing if the button was labeled 'kill switch'.

**Comment by ShizCalev** [comment]
This is a touch awkward. Not really a map issue per say, more of an issue/oversight with AI's can_see(). They shouldn't be able to see anything on those walls since it's all inside a room which they have no cameras inside of. One could think of it as if the machines still being connected to the station cause them show up on their sensors, though in situations like this it doesn't quite seem logical.

**Comment by Supermichael777** [comment]
some idiot probably laced it on the wall itself

**Comment by 81Denton** [comment]
@Supermichael777 Nah, they're placed inside the room. 
Cargo warehouse has the same issue:
![ai](https://user-images.githubusercontent.com/32391752/37778796-1b6e5df2-2deb-11e8-87ec-3117bb63f8ef.JPG)

**Comment by 81Denton** [comment]
Another one: When a malf AI shunts into an APC and tries to click objects that are visible through walls, you get 
`ADMIN LOG: [ckey] might be running a modified client! (failed can_see on AI click of the area power controller`

**Comment by WJohn** [comment]
There's not exactly a clean fix for this, because the *entire* reason that APCs were moved into maintenance is because the AI could still interact with those from the other side. We'd have to undo those changes on box from years ago. Not exactly the hardest thing in the world, but annoying.

**Comment by timothymtorres** [comment]
Is this still a thing?  Wouldn't this be considered intended since the AI has access to all electronics on the station?

**Comment by timothymtorres** [comment]
#36527
#55793
#47841

Are all duplicates and this behaviour is intended.  This is a mapping effect that happens when you place a wall-mounted object on a tile and then offset by pixel x/y.  So if you can send the tile it was placed on, you can also see the object that was offset regardless of if it is on another tile or not.
