### ISSUE TITLE
Curators can speak literally any language, but the Archives show up as gibberish.

### ISSUE THREAD

**Issue by Hate9** [tgstation/tgstation#36550]
This isn't a one-time error; it's more like an oversight. If anyone who isn't a cultist tries to use the Archives, they get the message, "All of these books seem to be gibberish." However, the person most likely to click on the Archives is the Curator, who knows literally every language, **including gibberish**.
I'm in no way suggesting that the Curator should be able to use the Archives (that would be stupid and overpowered), but it seems stupid for it to show up to them as unreadable.

**Comment by QualityVan** [comment]
If they are gibberish, doesn't it make sense that they'd seem to be gibberish?

**Comment by arsserpentarium** [comment]
I think, curator should be able to use magic. And have ability to summon and conjure demons at cost of human sacrifice.
Basically, balance factor is simple. Until curator abilities is really needed, security will prevent usage of curator powers. Because he need too horrible atrocities to make his magic work.

**Comment by Iamgoofball** [comment]
turn Curator into Harry Dresden when?

**Comment by arsserpentarium** [comment]
More likely into Joseph Curwen from The Case of Charles Dexter Ward. But more sinister.

**Comment by Shadowflame909** [comment]
Curator can summon one enslaved laughter demon per shift afterbtwo clown sacrifices when

**Comment by arsserpentarium** [comment]
^
