### ISSUE TITLE
Pacifists can't use less-than-lethal rounds + can't use DRAGnet

### ISSUE THREAD

**Issue by iskyp** [tgstation/tgstation#36600]
Round ID: Irrelevant

Reproduction:
Step 1) Load shotgun with beanbag rounds or stun rounds.
Step 2) Be unable to fire.

This probably isn't an easy tweak to make at all and I'm not sure if it's a feature but if it is then that is a bit stupid.

To fix this, you'd have to make the game check what ammo type is chambered every time you wanted to fire, and that could cause issues with burst fire weapons, either stopping you mid burst, or allowing players to autisticly load rounds so that they could fire a non-lethal round and then finish the burst with lethals.

However, it would be much more modular than just designating guns as "harmful" and "non-harmful"
Edit: edited for clarity.

**Comment by Mark9013100** [comment]
Beanbag rounds and rubber shot do brute damage iirc.

**Comment by iskyp** [comment]
they do around 5 brute damage, but it doesn't just apply to shotguns.
there's also things like the sniper soporific rounds which do no damage, but are unusable because they are  in a "harmful" weapon.

**Comment by ExcessiveUseOfCobblestone** [comment]
Stuns are lethal in our combat system so dunno why pacifists can bypass that.

**Comment by iskyp** [comment]
nice joke
stuns combined with other forms of damage are lethal
stuns by themselves are non-lethal

**Comment by Tlaltecuhtli** [comment]
guns dont kill people. people kill people

**Comment by ExcessiveUseOfCobblestone** [comment]
Stuns ensure the other individual can't miss.

Doesn't seem very pacifist if you can chainstun a guy while someone else beats him to death, or hell just dump them out of an airlock while they're stunned.

**Comment by Polyphynx** [comment]
There are still a bunch of ways to kill as a pacifist. Stuns make it much easier, but it also gets you to stop a violent threat. If pacifists use roundabout ways of killing people, then that's more them not going for RP (don't know why you'd choose pacifist in the first place if that's the case, though)

**Comment by ExcessiveUseOfCobblestone** [comment]
If they have to go out of their way to get people killed I can more easily claim it as an admin issue though :^)

**Comment by iskyp** [comment]
If pacifists go out of their way to get people killed, it's a fault of the playerbase, rather than the trait.

The trait just encourages you to not kill people by limiting your options to kill them.

**Comment by ExcessiveUseOfCobblestone** [comment]
All i'm saying is pacifism, as the name implies, should be non**confrontational**, not non**lethal**. Hitting someone with a stun device, especially one that does damage, is still violent.

It should be clear what the intent of it is within the trait's flavortext to the player so if push comes to shove admins can enforce fringe cases without pushback.

**Comment by iskyp** [comment]
Make an issue to rename the trait "[Technical Pacifist](http://tvtropes.org/pmwiki/pmwiki.php/Main/TechnicalPacifist)" then

**Comment by ShizCalev** [comment]
can a pacifist drag someone into space

**Comment by iskyp** [comment]
i made this issue because it seemed somewhat inconsistent that the pacifist trait limited certain stuns but allowed others
the game calls the trait pacifist which implies being an actual pacifist (cobby's interpretation), but in game you're allowed to use stun weapons for confrontation, which implies being a technical pacifist (my interpretation)

yes i do want the trait to be technical pacifist rather than actual pacifist, since the trait would be literally worthless and completely unused if you were unable to fight back in any sort of direct combat whatsoever

**Comment by Rinoka** [comment]
i get where you're coming from, but embracing "you're _technically_ a pacifist" would just be encouraging people to learn whatever is the most technical way to get around it in the first place

i don't think pacifist should be completely defenseless, but i feel like current balance discourages you from initiating a conflict, keeps you from finishing one with violence easily, but also doesn't make you the easiest target in the room - you can still reasonably stun an opponent and run.

... also "pacifist" conveys the general intent better than "technical pacifist" just in general tbh

**Comment by Rinoka** [comment]
not to say technical pacifist isn't more accurate, it's just an extra word that would change how players treated it (i'm p. sure current playerbase would be like "it's _technical_" to justify weird bullshit to get around the limitations)

**Comment by iskyp** [comment]
I can see where your coming from, although just saying pacifist might leave it too general, and people could be like "OH but I'M X TYPE of pacifist"
At that point though it's just getting ridiculous.

Changing the description from"The thought of violence makes you sick. So much so, in fact, that you can't hurt anyone." to "The thought of killing makes you sick. So much so, in fact, that you've sworn to never take another life." and giving them sadness if they witness a death nearby might be a good fix.

Either way though, changing pacifism to detect whether or not the chambered ammo is harmful rather than the weapon itself would be a much better system and allow for more options if non-lethal rounds were ever explored further.

**Comment by Rinoka** [comment]
Yeah, I getcha -- but still, pacifist is a bit more blanket and consistent. Doesn't really matter if someone says they're X type - they're forced to maintain a very restrictive attitude.

But I think a description change and a sadness moodlet would work well, though that may need to wait until the feature freeze ends, since it's not so much a fix as a clarification.

(Also, I think the issue would be that in some cases it's not possible for a pacifist to reasonably know what is chambered in the gun, so maybe for things like tasers but we might want to shelve the idea for chambered weapons unless there's a major rework or addition to non-lethal rounds.)

Right now, the real answer is probably just that pacifist preventing ranged engagement is mostly working as intended, and it'll get some adjustments for enforcability/clarity after the freeze ends.

**Comment by iskyp** [comment]
`(Also, I think the issue would be that in some cases it's not possible for a pacifist to reasonably know what is chambered in the gun, so maybe for things like tasers but we might want to shelve the idea for chambered weapons unless there's a major rework or addition to non-lethal rounds.)`
I'm not sure if you're saying that it would be hard to check for the code, or for the player here.

Also slightly related, pacifists can't use DRAGnet

**Comment by Rinoka** [comment]
i mean more that it doesn't make sense if you're a pacifist to pick up a gun you didn't load, turn and attempt to pull the trigger, and only fail because you sensed, deep within the cartridge, pure lethality

**Comment by iskyp** [comment]
~~who cares~~
Just pretend that every time a pacifist picks up a gun/fires one he checks the next round at ludicrous speed.
speed matches up with being able to screw open a maintenance panel, pull out a multitool from your toolbelt, pulse a wire, put either your screwdriver/multitool back into your toolbelt, unclip a crowbar, and pry open a door in less than 3 seconds.

**Comment by Rinoka** [comment]
lmao you could pretend that but i think it's stranger to say "the pacifist checks the round at ludicrous speed and recognizes if it's lethal or not" than "the pacifist won't pull the trigger on weapons that could be lethal"

caveat: i think they should be able to use tasers and other weapons that can be clearly toggled to nonlethal without chambering rounds, ie some laser guns w/ the disable function, so maybe that could see a fix. dragnet obviously included

i just don't think the ammunition-variant guns (anything with bullets basically) should be something where we handwave it as pacifists just Knowing, it just makes more sense for them to pussy out because they don't know

**Comment by iskyp** [comment]
i'm fine with just handwaving it, but i do see your point.

still, making the change from "this gun is/isn't harmful" to "the round chambered is/isn't harmful" would allow you to let pacifists use the disabler firemode on e-guns, while restricting them from lethal firemode (atleast, it should if i read the code correctly)

**Comment by Rinoka** [comment]
yeah, disablers should at least allow pacifists to use them for that kind of thing

it's also worth noting there are certain potentially positive guns that are nearly impossible to error-trap this way (like needle guns) so keeping electric guns the exception rather than the rule would be delightful so that people don't have their eyes detonate on reading the code

**Comment by iskyp** [comment]
well after tinkering with code for about 2.5 hours I've managed to get this working perfectly.
going to PR it (although I don't know if it will be accepted because it might be considered a tweak or whatever)

**Comment by Rinoka** [comment]
power to you
