### ISSUE TITLE
Wet floors dry too quickly

### ISSUE THREAD

**Issue by Arianya** [tgstation/tgstation#36661]
**[Round ID]:** 85425

**[Reproduction]:** Wet a floor with any water source, observe as the wet tile dries itself in roughly 2 seconds.

Most likely related to #36130. 
@kevinz000 

Assuming I'm reading the code right, it looks like floor tiles wetted by normal water from a mop/shower/etc should be wet for 15 seconds, and then have that time sped up by ([TEMPERATURE IN CELSIUS] * 0.1) seconds.

So in 20 degrees Celsius, this should be lowering the time to dry from 15 to 13. Instead, things appear to be drying in 2 seconds.

Wasn't able to test this in non-20*C enviroments.

**Comment by Kraseo** [comment]
feature

**Comment by Arianya** [comment]
Slightly unrelated, but from the same PR:

`#define COMSIG_TURF_MAKE_DRY "make_turf_try"						//(max_strength, immediate, duration_decrease = INFINITY): Returns bool.`

This should probably read make_turf_*dry*

**Comment by Rinoka** [comment]
_let the turf try damn you_

is it just the visual effect, or do they also stop slipping? asking because curious

**Comment by Arianya** [comment]
They also stop slipping

**Comment by Rinoka** [comment]
goddamnit kevinz

**Comment by Rinoka** [comment]
skimmed kevcode

i suspect this happens because the system doesn't appropriately read the number type kevinz includes, which means that the duration gets _completely fucked_ when it's loaded into the system - i don't think there's anything in his temp code that should actively be taking chunks out of the duration, albeit commenting the reduction out would confirm that

because basically every method of slipping floors listed in his changelog records in seconds or more, but the .dm itself notes that its list is in deciseconds, which would explain the apparent 2s duration -- honestly i think that it might appear that long due to icon updates and it kills itself off even faster

there is only one form of water component generation that doesn't use his seconds/minutes notation, and that's water vapor

if you wanna give this a test to lambaste kevinz with then see if water vapor lasts longer visually compared to normal water splashes
