### ISSUE TITLE
Ghosts cause sparks when going through portals

### ISSUE THREAD

**Issue by MMMiracles** [tgstation/tgstation#36742]
When a ghost clicks on a portal created by something like the hand tele, they create sparks like every other mob when they go through.

oops

**Comment by ShizCalev** [comment]
how many fucking times does this have to be fixed jfc

**Comment by arsserpentarium** [comment]
why is it problem?

**Comment by AlexTheSysop42** [comment]
>plasma flood
>someone opens a portal
>no one goes in
>ghost clicks it
>oops, fire

alternatively:
>someone gets hand tele
>asks a ghost questions
>has ghost trigger sparks once for yes, twice for no
>meta achieved

**Comment by arsserpentarium** [comment]
Yes, that's spiritism.What's wrong?
When you can encourage occult and dark arts, you should do it.

**Comment by AlexTheSysop42** [comment]
Problem with 1st scenario: ghosts can start fires

Problem with second scenario: it's metagaming, you can also just use a camera obscura and you won't be as likely to get banned, because it's a feature

Some problems with metagaming:
* Ghosts can reveal the mode for almost all of them (ghosts can see cc/cult/abductor/syndie/ling/holopara chat and therefore know if it's one of those modes)
* Ghosts can reveal a malf or onehumaned AI
* Ghosts can reveal emagged borgs
* Ghosts can potentially reveal the location of SCP-294, giving the crew powerful chems
* Ghosts can reveal if a person is an antag
* etc

The only limit to the metagaming is the exploiter's ability to choose good yes/no questions

Also, hand tele portals aren't exactly very occult, unless the chaplain is worshipping the bluespace gods or something.

**Comment by arsserpentarium** [comment]
Did you know, that plasma fires can start by itself with some probablity?

Also ghosts can reveal you complete bullshit.You decide, if you should believe them.And you, probably, shouldn't do it blindly.
Probablity to be goofed and yes/no limited questions is fairly balanced way to get info.
P.S.Are you sure, that you know, how portals work? maybe some traces in bleuspace leads to realm of dead?

**Comment by fludd12** [comment]
Ok, so while those are all very cool explanations and excuses for the existence of a bug, it doesn't mean the bug should continue to exist. If the camera obscure is already a functional medium for ghosts, we don't need portals to be.

**Comment by arsserpentarium** [comment]
Sometimes bugfeatures are valuable too. Like chair rotating, SM telekinesis interaction and much more.
It's just method, that nature uses to create life.Entire process of evolution is conversion of reproduction bugs into features, throught natural selection.

**Comment by MMMiracles** [comment]
Because ghosts being able to interact with portals was added as a QoL change so ghosts could more easily follow a situation rather than jumping to whatever mob went through. The fact it's already been fixed multiple times should be enough to that it isn't intentional.
