### ISSUE TITLE
Poly struggles to repeat phrases heard from recordings

### ISSUE THREAD

**Issue by MMMiracles** [tgstation/tgstation#36758]
![polree](https://user-images.githubusercontent.com/9276171/37993297-2b7834d0-31dc-11e8-89c2-b958206013e8.png)

oof

**Comment by Davidj361** [comment]
Probably a problem with how taperecorder is coded to say and record things. I was trying to overhaul it before, but didn't get to finish it before last year's freeze.

**Comment by praisenarsie** [comment]
@Incoming5643

**Comment by PKPenguin321** [comment]
UH HUH

**Comment by Davidj361** [comment]
Also if I remember clearly, the problem with the current universal tap recorder is that it records all that HTML crap and then says it like that too. I fixed it with my shitty feature update of it, but I wasn't done making the feature.

**Comment by ShizCalev** [comment]
also see #41177

**Comment by san7890** [comment]
I don't think this should apply anymore since the Parrot Rework in #79762 where everything was moved to `/datum/component/listen_and_repeat` and the whole `Hear()` process for living mobs being drastically overhauled several times - the component will override the entire `Hear()` chain via the `COMSIG_MOVABLE_PRE_HEAR` signal now, so I don't believe this should happen anymore? the whole code has been reshuffled so many time sin the last six years that i think we should just create a new issue report and focus on fixing `listen_and_repeat` rather than have this be buried as some parrot/poly issue.
