### ISSUE TITLE
Rune of the Spirit Realm detaching ghosts from their old bodies forcefully

### ISSUE THREAD

**Issue by zaracka** [tgstation/tgstation#36849]
Round 85788.

The rune has two functions, one of which manifests ghosts as semitransparent homunculi. If you are orbiting someone who uses this ability, you are automatically forced into the new body and are detached from your old body. This means people who died and were awaiting cloning can no longer be cloned simply because they orbited the wrong person at the wrong time. The same applies to cultists that could have been revived using a Revive rune.

When the ability is used, a button appears in the top right of the screen for ghosts. The button is used to willingly come back as a ghost role. This should be the only way it works.

**Comment by Barhandar** [comment]
This is likely a vestige of when that rune required the ghost to actually occupy same tile, since back then there weren't any fancy ghost UIs, mechanics for easier ghosting, or the orbit command.
>This should be the only way it works.

No. The button is often un-obvious, and the response needs to be prompt (that's what astral travel, merged into Spirit Realm, rune was for, getting ghosts to cooperate). What it should do is show a notification for ghosts on the rune, the "wanna be X? Answer in 10 seconds!" one, and make the resulting homunculi a bit more persistent so they don't _instantly_ re-ghost the moment the cultist steps off of the rune.

**Comment by zaracka** [comment]
You're right. The button itself works by teleporting ghosts onto the tile with the rune on it.

There are other ghost roles that use the same button style, like marauders and positronic brains. But they don't use a rune and positioning, they create a Yes/No dialog box and instantly put you into the body upon hitting "Yes."

I should note, most people currently use the ability to trigger other abilities that require more than 1 cultist and instantly cancel it afterwards. However, making them more persistent could be interesting.

**Comment by Barhandar** [comment]
I don't mean persistent like constructs or golems, I mean just having a few seconds for cultist to get back on the rune before the summons are dusted.
>I should note, most people manifest homunculi to act like an extra cultist for runes that require extra invokers. They are generally destroyed once this purpose is met.

This is explicitly original intention of the rune.

**Comment by zaracka** [comment]
From the wiki: You can even use this function after manifesting ghosts to help guide them in combat - manifested ghosts can also see regular ghosts and therefore can see your dark spirit as you lead them in battle!

Is a 10 second prompt worth it? I'm not saying it's not, but all factors should be considered.
