### ISSUE TITLE
Curator Snake Phobia seems to trigger randomly.

### ISSUE THREAD

**Issue by Ozymandias-1** [tgstation/tgstation#36978]
[Round ID]: # 12361 on Citadel Station.

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.) Im not sure, however the issue only began to occur within the last 3 days.

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.) I cannot reproduce the error, but have spent the last few days trying to ascertain the cause. I get the "Hearing the word snake spooks you to the bone!" And all the associated IC things like shaking and screaming, though no one has said snake, snek, boop, or any of the other trigger words ive noticed. I thought maybe it had something to do with Citadel stations Naga characters or their voices, but sometimes im fine near them, other times it goes off around them constantly, and ive been unable to find any reason. I dont believe im near any snake plush or anything like that, and i know im not near actual snakes or the snake staff. It just seems to trigger randomly.

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by Ozymandias-1** [comment]
After some looking, ive determined that words ending in 's are what caused it, as i saw in another thread.

**Comment by iskyp** [comment]
>say "what's the deal with lizards"
>You can't bring yourself to say the word "snake"!
>say "snake"
>Audrina Dean says, "Snake"
>say "what's"
>Audrina Dean says, "What's"

any word that ends with a character that is not a letter followed by another word will make you unable to speak the word (ie "what's the", "what8s the", "what<<s the", etc. all make you unable to speak, while whats the works fine)

oh and this isn't just restricted to snake phobia either.
every single phobia has this issue.
trigger words literally do not do anything, but hearing "word[nonletterchar(s)]s word" will trigger any phobia.

**Comment by iskyp** [comment]
oh, i should probably do this
@XDTM

**Comment by XDTM** [comment]
Not my fault, it's whoever converted it to regex. Still, there probably is a check for (non-cnon-char)(any amount if 's')(non-char) which triggers in this case. It would just take a conversion to ss+ or sss+ instead of s+.

**Comment by Rinoka** [comment]
it was regex'd by #36457, so @Tacolizard 

the regex is "regex(@"[^\l][REGEX_QUOTE(word)]*s[^\l]")"; aka [^\l][word]*s[^\l]

here's a great testing ground: https://pythex.org/

test out that regex with "it's things, wings, wails, oranges, roads, and derails, but no word was spoken." you'll probably see how ridiculously broken it gets.

that regex is saying "with no preceding or following lowercase letters, i want to find any *or 0* instances of *one or more of the characters in word*, followed by an s"

which is what breaks the entire fuckin' thing. this is why you don't have to have a phobia word to trigger, **and** why it won't trigger off phobia words: it'll react to characters in them. you could probably trigger the same effects as above with "'ss ", "'ns ", "'as ", "'ks ", "'es ". (replace word with snake and test it out if you're curious.)

here's a fixed regex: regex(@"\bREGEX_QUOTE(word)s*\b"), or \bwords*[^\l]

(if that doesn't compile, return [] around REGEX_QUOTE)

1) [^\l] is bad form for attaching to the start of regular expressions; it won't match the newline, so saying "Snake" would never cause a reaction. It remains on the end to keep "Snake's" or anything else it can greedy-grab

2) the \* operator has to go AFTER the part you want to modify -- in this case, the s.

3) even though this was in the documentation for this function, you shouldn't insert a [] because it transforms a phrase into "match characters", so [word] matches w, o, r, and d. i think this is why the actual words did nothing, though it might be due to the [^\I] in the beginning as mentioned.

i'd have just PRed with this but i won't have access to my git computer for an hour or two and this is maybe a one-two line fix lmao, should be easy enough to implement

protip tho: always use WYSIWYG editors for regex it's the only way
