### ISSUE TITLE
Nyctophobia trait activates when you outpace your light source.

### ISSUE THREAD

**Issue by subject217** [tgstation/tgstation#37146]
Round ID: 86384

Nyctophobia is a trait that makes you automatically walk whenever you're in the dark. While it's normally not an issue if you're carrying any light source, in times of greater time dilation you can outpace the lighting. For example, I experienced it when I was running through maintenance as a bomb went off. So under less dilation I'd be fine, all of a sudden I'm forced to walk until the lighting updates. It makes the trait really annoying to use whenever there's time dilation.

**Comment by Rinoka** [comment]
@Xhuis since trait problemz

it'd probably be best to attach a timer or something. also because with this in mind i'm very tempted to fuck with people who have the trait by flickering the lights as AI

**Comment by PKPenguin321** [comment]
>also because with this in mind i'm very tempted to fuck with people who have the trait by flickering the lights as AI

Unironically not a bug

**Comment by Rinoka** [comment]
feature: emotional trauma, in fact, is not included in human harm

**Comment by optimumtact** [comment]
this isn't fixable without rewriting lighting

**Comment by PKPenguin321** [comment]
Or just having light phobia not kick in immediately

**Comment by subject217** [comment]
If you're going to close it you might as well just remove the trait, because it's completely worthless right now.

**Comment by optimumtact** [comment]
@PKPenguin321 that's an ugly hack

**Comment by Rinoka** [comment]
@optimumtact this bug is uglier. it means even with a light source you can't go into the dark, which means that you're fucked.

additionally, adding a timer makes sense because it should be happening when the person realizes they're in pitch darkness, not when the server decides they're in pitch darkness.

you should reopen this, because like subject says, if the solution to this isn't a timer, it's the removal of the trait. if our lighting system can't support this, Okay, but then the trait either shouldn't exist or it should be fixed (or rebalanced).

**Comment by optimumtact** [comment]
no
it's fine to have a texture system like traits not work perfectly and not have shitty code

don't like it, dont' take the trait, it's entirely optional

**Comment by Rinoka** [comment]
then reopen the trait and have the fix be its removal.

**Comment by optimumtact** [comment]
no

**Comment by Rinoka** [comment]
you realize we're just going to keep getting this issue and having to mark it as a repeat right

**Comment by optimumtact** [comment]
ok
