### ISSUE TITLE
Airlocks with aiControlDisabled can be hacked roundstart

### ISSUE THREAD

**Issue by 81Denton** [tgstation/tgstation#37157]
AIs can hack airlocks with aiControlDisabled (execution chamber and steel rain) roundstart, which invalidates the whole "AI control disabled" part.

Imo these either need hackProof = TRUE or some sort of indication that the AI is hacking the valid chamber door.

**Comment by YakumoChen** [comment]
It takes an extremely long time to hack doors if the AI wire is cut, so I don't see how it is a very big deal. IC wise, AI has no reason to expect the "transfer centre" to be an execution room, and steel rain doors being hackable isn't a big deal since the ops will be out of the pod long before the AI can finish hacking.

**Comment by Anonmare** [comment]
It would be an issue if the AI has a way of seeing Steel Rain before it drops and while AIs shouldn't be doing it roundstart, they *can* hack the door if they have a  reason to suspect the room is not what it says it is (sec call it the execution chamber).

**Comment by YakumoChen** [comment]
the point of the room is that you're supposed to use it to fool the AI into thinking it's not an execution chamber. Roundstart AIs should not know nor assume it's used for executions.

**Comment by 81Denton** [comment]
You made some good points, I'll close this issue then.
