### ISSUE TITLE
Mining satchels pickup ore while in backpack

### ISSUE THREAD

**Issue by ExcessiveUseOfCobblestone** [tgstation/tgstation#37260]
Server revision compiled on: 2018-04-15

The following pull requests are currently test merged:
37024: 'Puts some brakes on the Cult Train' by Robustin at commit a2366c
37039: 'testing new icons for webs!' by Armhulen at commit 5ad857
36754: '[s] Invisimin HUD Fix + Changeling AI HUD Fix + Fixes Changeling Digital Camo with AI' by Davidj361 at commit 69a66b
37202: 'Fixes cat parts not showing up in perfs.' by DaxDupont at commit eef589

@kevinz000

**Comment by kevinz000** [comment]
weird bug, how is equipped called but not dropped when it's moved? =|

**Comment by kriskog** [comment]
Had this happen to me yesterday, saw this is still open. Part of my normal routine as a miner is picking up an additional satchel, and that causes this to happen. Figured I might as well supply a bit of information and uninformed conclusions. Hope it helps, and sorry if its redundant. 

This is what I figured out while playing:
-The issue only happens when the mining satchel spawns in the backpack, and if removed doesn't happen again. (Wrong flags added to the satchel when initialized?)
-From the linked issue, doesn't care about backpack location (Again, satchel flagged as equipped on player or the other way around?)
-Bypassess backpack capacity. (Normal full satchel behavior is adding ore to empty active hand, reading backpack slot as empty hand? Is this forced?)
