### ISSUE TITLE
Anacea does not completely block the full effects of healing chemicals

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#37271]
[Round ID]: # 86643

[Reproduction]: Lately I've been delving deep into the world of death mixes (chemistry). However, I have encountered a bug which renders a potentially powerful mix useless. In the mix, the chemicals in concern are lexorin and anacea. Lexorin should cause a tremendous amount of oxygen damage, and the anacea should effectively counter any epinephrine (or healing chemicals in general) used on the patient. However, for the briefest of time, healing medicines heal the patient before getting purged by the anacea. In the round, an epinephrine medipen was used, effectively stopping the lexorin in its tracks (it immediately brough the oxygen damage down to 15). This is not just epinephrine, for I have seen other chemicals such as Pentetic Acid and Salbutomal penetrate anacea's shield before getting purged. Therefore, my deathmix is effectively useless, as anyone cunning enough to use a medipen can prolong their death long enough for medical attention. 

[For Admins]: This occurs often, because I have used the exact death mix I used this round on three occasions, and each time the issue occurred ( I don't remember the rounds theses occurred on). For reference, DarkGeneralLord uses the same death mix as me, so he may or may not have encountered this bug during his time here.

**Comment by Rinoka** [comment]
not a bug; oxyloss's unique feature is that epinephrine *severely* reduces it (a value over 35 drops to 35) and anacea isn't able to force-stop medicine reactions, it just forces an extremely fast purge to reduce the potency of healing mixes

i'm personally interested in a rework of chemistry to allow for facilitator chems, so that anacea could just force the facilitation coefficient to 0 and thus make it useless, but as chemistry stands this is entirely working as intended

**Comment by Rinoka** [comment]
suggestion, though: mix in curare (if tator) or a knockout chem to avoid the outcome of someone stimming out on epinephrine to save themselves. curare in and of itself should fuck with people who thought they were safe just popping their emergency syringe; stun chems that immediate come to mind are sulfonal, pancuronium (tator), or cyanide. if you like botanists, you can also grab something like amanitin to stack on a secondary damage type.

**Comment by PKPenguin321** [comment]
Agreed, this isn't a bug, more of a stupid side effect of the functionality that even the smallest dosage of epinephrine provides

**Comment by imsxz** [comment]
i told you to use tox based deathmixes noob, they can kill through cryo+epi if they're any decent.

not a bug/i ded/feature request

**Comment by Rinoka** [comment]
i get the feeling that oxyloss kills you way too quickly for it to actually save you unless it's either ridiculously potent or forces stability regardless of dose...

given, that could also be tweaked so that it requires a certain amount to actually force stability, but it might not fix this issue if it hasn't metabolized the amount in the syringe before it triggers the effect

**Comment by Rinoka** [comment]
also imsxz is correct, since we don't have a "resist this" setup chemistry is currently about stacking as many unique drugs in as possible to create absolutely ridiculous damage numbers of a singular type

toxin damage is the easiest way to achieve this because we have like 20 different chems that apply tox damage and they're all designed to be solo-effective soooOOO

**Comment by ExcessiveUseOfCobblestone** [comment]
All chemicals should scale to avoid small dose abuse tbh.

**Comment by Rinoka** [comment]
that's why we have metabolism stuff

the problem is that dealing like 75 damage in 1 tick before anyone can react is still better than dealing 400 damage over a minute because current chems are all about reaction time

**Comment by zaracka** [comment]
Purge chems are the most overpowered reagents, essentially nullifying the reagent system in general. However, neurotoxin and beepsky smash obviously don't give you enough time to pop a charcoal pill. But then those reagents in a syringe gun are essentially a taser.

**Comment by Rinoka** [comment]
yeah, that's true too.

the real problem is that chems are either short burst damage to fuck you over and need a purge chem to save you applied very quickly, or they're long-form shit that nobody cares about because you stall, get to the chem desk, and chug charcoal until you're not dying anymore

there really isn't an inbetween and it's what makes our chem system so OP: its only real counter is also itself, and that's the hardest possible counter you can apply.

i'm even more interested in adding in inert/activator chems now. might be able to mitigate this if you're required to have a certain ratio of a secondary chem to get the most powerful effect and make them metabolize differently.

**Comment by vuonojenmustaturska** [comment]
@Rinoka after the freeze is over i'm planning to expand chemistry a fair bit, make it more of a real department and not a wiki-based coffee machine

**Comment by Rinoka** [comment]
@vuonojenmustaturska i respect this and hmu when you start in on that bc i have been thinking about how to improve chems for far too long

**Comment by wesoda25** [comment]
Yeah, at this point I've been maining oxyloss because it's so stupidly powerful, provided meds arent on hand. I've begun to look into toxin based damage, however the fact that possibly one of the strongest non traitor (which I never use) chems is cyanide, which is completely luck based, is semi discouraging. Regardless, this post was enlightening, and I'll make sure to use some of this stuff.
//Side Note - I'm interested in learning reagent coding, and if I end up looking into it, I'd try to diversify chemistries toxins. Probably not really robust chems, just the subtle, goofy sort, the likes of mimes bane.

**Comment by Rinoka** [comment]
@wesoda25 most damagetypes are stupid powerful -- the general list is oxyloss > bleed > toxin > burn > brute in my book. the only issue with oxyloss is that it can be flat-stopped and stabilized; bleed is great if you can start it because it's difficult to handle without bandages since there's no chems for it. toxin is mostly OP because you can generate a fuckload of it quickly -- burn because most of the methods of infliction results in you literally catching on fire or being electrocuted -- and brute being the most common and thus having the most ways to resist it (sans bombs).

**Comment by Rinoka** [comment]
also fun point: ask for spare slime extracts from xenobio. grind them into slime jelly.

it heals brute but will eagerly burst out anywhere from 20 to 60 toxin damage. iirc it procs on insertion, so you could totally get away with shoving that in someone and getting free extra toxin bursts off 1u of the stuff.

**Comment by AlexTheSysop42** [comment]
Sufonal knocks out and kills before the target wakes up if they don't get medical attention. Particularly useful if they think you're morphine-ing them and try to hide.

**Comment by wesoda25** [comment]
Alex that goes for a lot, my current mix is OK if I add neurotoxin, bc despite the quick metabolization, they won't be getting up from it. Anyways, if I could learn coding, one thing I'd try to add is a chem which lengthens/shortens metabolization rate, bc I think it could be very, very fun to experiment with. (Ex: Chems hit twice as fast, or last twice as long...)

**Comment by Rinoka** [comment]
"hit twice as fast" wouldn't apply, because metabolization rate is basically "on each tick, remove this much". doubling it is basically what charcoal and shit does.

that's already a thing in virology, though. check out metabolic boost under datum/diseases/advanced/symptoms/heal.dm. it doesn't use a var, just multiprocs the processing, but yeah.

**Comment by kevinz000** [comment]
not a bug

**Comment by ExcessiveUseOfCobblestone** [comment]
@KorPhaeron @optimumtact please close

**Comment by Rinoka** [comment]
^
