### ISSUE TITLE
Spear icons broke

### ISSUE THREAD

**Issue by Therapist1** [tgstation/tgstation#37393]
[Round ID]: 86926

[Testmerges]: The following pull requests are currently test merged:
#37342: 'Makes it possible to see tiles past z transitions' by ninjanomnom at commit 176d76
#37384: 'Re-adds and reworks fusion.' by as334 at commit f09802
#36866: 'refactors overlays to append/remove individual overlays instead of cutting' by Robustin at commit a73e33

[Reproduction]: Craft or find a spear. The only problem is, they're invisible. I encountered this while playing as an ashwalker, not sure if it works if you craft a spear, but I did find a table full of invisible spears.

**Comment by DaxDupont** [comment]
Null rods and such break too

**Comment by DaxDupont** [comment]
Round ID: 86926

Server revision compiled on: 2018-04-23

The following pull requests are currently test merged:
#37342: 'Makes it possible to see tiles past z transitions' by ninjanomnom at commit 176d76
#37384: 'Re-adds and reworks fusion.' by as334 at commit f09802
#36866: 'refactors overlays to append/remove individual overlays instead of cutting' by Robustin at commit a73e33


Based off origin/master commit: 6e236f

Revision: c4157a9fcfa5e6fc2efdb9cfc47eb6fdfe33f6de

**Comment by ShizCalev** [comment]
Fixed by #37394
