### ISSUE TITLE
all corgis bought from cargo are female

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#37708]
shouldnt it be 50% lisa and 50% corgi (male)

**Comment by MMMiracles** [comment]
corgis practically breed like rabbits, have you seen cargo backrooms when they're left alone? 

no wonder central only sells females

**Comment by praisenarsie** [comment]
sounds like really good/bad luck

**Comment by SpaceManiac** [comment]
"All female" is just luck, but the ratio is off. Because 50% of corgi crates are Lisa which are always female, and the others are random, only 25% of corgi crates contain males.

https://github.com/tgstation/tgstation/blob/37c30b798dc5b14116c6aac33f406f246c5d957c/code/modules/mob/living/simple_animal/simple_animal.dm#L98-L99
