### ISSUE TITLE
You can get infinite ammounts of vendor products.

### ISSUE THREAD

**Issue by Teepeepee** [tgstation/tgstation#37728]
This isn't really a big issue unless it works with donksoft vendors really, but those already have lots of stock in them so not even then.

Anyways, the thing goes like this:
1. hit vendor until products pop out, count them (they should be below the ammount you could get from emptying the vendor manually).
2. keep hitting till it breaks into generic machine frame.
3. rebuild with the stuff it dropped (restock modules).
4. repeat infinitely, getting products beyond what the stock on the machine says.

I didn't report this when it happened cause I'm a dumb dumb, the station was power sinked, if that's relevant at all.

**Comment by AlexTheSysop42** [comment]
With donksoft you can just use a restocker anyway

**Comment by Tlaltecuhtli** [comment]
so it seems the parts it spill dont grab from the stock inventory

**Comment by Ignies** [comment]
There are easier steps to reproduce this, _for example;_  tacticool turtlenecks

**1.** hack the vendor.
**2.** Take the product.
**3.** Deconstruct and reconstruct the machine using screwdriver and crowbar.

I believe the problem lies in that the system doesn't know which item was sold once you deconstruct and reconstruct the machine, if you keep repeating these steps, you will notice that certain special items dissapear as if you bought them, until they are all depleted.

_Tacticool turtlenecks are not game changing, but_ **on nuke ops rounds you can hack the medivendor and take enough spaceacilin and salbutamol pills for the whole crew.**

**Comment by Jalleo** [comment]
This is how it is currently designed. Mainly because we havent set up a way that easilyvresolves this issue.

**Comment by PKPenguin321** [comment]
The fix is to refactor so the vendor's stock is kept track of in the restocker unit, then to make it to vendors only use one restocker instead of 3

**Comment by Jalleo** [comment]
Which is much easier said than done. If you do it properly.

**Comment by octareenroon91** [comment]
Restocker units could lose their potential to be any merch item on deconstruction, instead splitting up the vendor inventory.
