### ISSUE TITLE
Ambient Occlusion should not be turned on for pipes.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#37744]
Atmospherics in particular REALLY suffers from it being shown too much.
![](https://i.imgur.com/ZngQhUR.png)

**Comment by 81Denton** [comment]
Dear god, that makes it look like a shitty HDR photo.

**Comment by Barhandar** [comment]
That aptly describes entire ambient occlusion thing, Denton.

**Comment by Iatots** [comment]
>That aptly describes entire ambient occlusion thing, Denton.

:point_up:

**Comment by ChangelingRain** [comment]
@deathride58

**Comment by deathride58** [comment]
Visible pipes are on the game plane primarily so that pipes on top of walls aren't hidden, such as the mix to engine pipe on Boxstation, the incinerator's fuel pipe on Metastation, and the occasional lazy atmos tech's pipenet repair attempts. If I could selectively disable AO for specific types of objects without turning the organization of planes into an absolute mess, I would.

**Comment by optimumtact** [comment]
it's not fixable with the current plane setup, so you just have to live with it or turn it off
