### ISSUE TITLE
Cold proof species are affected by some cold stuff

### ISSUE THREAD

**Issue by GuppyLaxx** [tgstation/tgstation#37781]
So, cold proof for species still lets you get affected by cryo, cold showers, temp gun cooling beams.
Like, c'mon. Muh consistency

**Comment by XDTM** [comment]
Cold proof doesn't mean they physically cannot get cold, just that lower temperatures do not affect their biology.
The coldres mutation instead keeps your heat steady and actually prevents the cases you mentioned.

**Comment by GuppyLaxx** [comment]
ngl i only made this issue because i get triggered over watchers freezing me to death when i mine :^(

**Comment by XDTM** [comment]
When i mentioned that i was not aware that cold actually _hurt_ coldproof people. I'm gonna have to recheck this stuff, it shouldn't.

Fun fact: cryo actually semi-works on cold immune mobs only because whoever wrote the cryo cooling formula did not consider that multiplication comes before addition, making

`((1 - cold_protection) * 0.1 + conduction_coefficient) = conduction_coefficient`
even at full cold protection

**Comment by GuppyLaxx** [comment]
Yeah, while cold proof you still burn by freezing by shower, cryo, or temp beams.
~~so i get double fucked as i take nearly double damage from it and fucking walk slower than a human in walk mode~~
