### ISSUE TITLE
Can't float diagonally in zero gravity

### ISSUE THREAD

**Issue by zaracka** [tgstation/tgstation#37862]
Round 87972. Bagil.

If you move diagonally in zero gravity, you're forced to float in a non-diagonal direction.

**Comment by Tlaltecuhtli** [comment]
diagonal movement isnt real

**Comment by Jord1081** [comment]
I dont think diagonal movement is real, its just faked. Im pretty sure when you move diagonally you still move over the two tiles you normally would. So if you are in zero g then trying to move diagonally makes you move the first tile then you lose your grip and float off in an unintended direction.

A similar thing happens when moving diagonally over slippery floor. You try to move diagonally and just slip straight in one direction,

**Comment by praisenarsie** [comment]
@ninjanomnom
