### ISSUE TITLE
Shell got transformed into corgy, i got left out off being the ai, and died after a couple of seconds (out of nowhere)

### ISSUE THREAD

**Issue by AzureWildfire** [tgstation/tgstation#38229]
Issue reported from  Round ID: 88829 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Testmerges:
#37790: 'Individual Logs now follow the client around automatically' by optimumtact at commit 74f05572a8
#38225: 'Include item overlays in attack animations (shows the proper color of screwdrivers etc)' by vuonojenmustaturska at commit b4d2b8a0e0

Bug: So i was an ai on this round,(this was a wizard round), i was using a shell, the wizard used staff of change, i got transformed into a corgi, i was unable to go back to being the ai, and died after a couple of seconds. 

Reproduction: be an ai in a shell, get the shell tranformed into something else.

**Comment by chesse20** [comment]
not a bug you got owned

**Comment by ShizCalev** [comment]
You don't automatically transform back after being staff of changed.

**Comment by msgerbs** [comment]
This seems odd to me that the big gigantic AI core is rendered useless because its shell got transformed. If it's really "not a bug" it's still counterintuitive and really only makes sense with an understanding of the underlying code. I don't think it should work this way.

**Comment by GunHog** [comment]
I would personally consider this a bug. An AI "shell" is, lorewise, supposed to be a robot body controlled _remotely_ by the AI. That is why hitting the AI or cutting its power breaks the connection.

In my opinion, as co-author of this feature, anything that destroys or otherwise render the shell broken or non-existant should return the AI to its core. The shell is a remote-controlled robot. Think of it like being in VR. Your VR character being magically transformed into a corgi does not do the same thing to your "real" one.

Of course, this is only an opinion. There is nothing I can actually do about this.

**Comment by chesse20** [comment]
this is a bug unclose this issue RIGHT NOW
