### ISSUE TITLE
Roundstart borgs don't start with their pref name 

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#38281]
It just gives the "Cyborg ###" name now

**Comment by chesse20** [comment]
fix this

**Comment by lolman360** [comment]
when you choose a module it sets the name to prefrence, so there's no functionality problem unless you want to walk around without a module

**Comment by CitrusGender** [comment]
![image](https://user-images.githubusercontent.com/31262308/41777077-212fd522-75f8-11e8-9b78-cd0da278c7bf.png)
![image](https://user-images.githubusercontent.com/31262308/41777122-4ee16efe-75f8-11e8-96c8-88e50848af67.png)

Definitely because client is null for on initialization for some reason. I don't know if that's intentional or not. Must be inside of one of the parent objects. I'll take a look.
