### ISSUE TITLE
Fernet is deadly

### ISSUE THREAD

**Issue by Mickyan** [tgstation/tgstation#38565]
This is apparently intended, so I'm just pointing out how absurd it is

Its effect are so extreme that drinking an entire glass is almost guaranteed to starve you and then kill you with toxloss. 
This is also the case for most recipes that contain it, which are usually just as strong as drinking it straight (but with a fraction of the boozepwr) despite the fact it would realistically be heavily diluted

**Comment by ExcessiveUseOfCobblestone** [comment]
@ThePainkiller

**Comment by ThePainkiller** [comment]
Its boozepwr is 80, the same as Thirteen Loko, and 5 more points than Whiskey. It reduces satiety a bit more than Lipolicide does, with the drawback of causing more toxin damage if you're starving and being an alcoholic drink (that causes liver failure on the long run). This is to compensate the fact that lipolicide isn't as fast and easy to obtain than **pure** Fernet.
For starters, you **SHOULDN'T** drink an **ENTIRE** glass of **PURE** Fernet (bolded for emphasis so I can get this point across), wich has been even hinted at its description:
_"A glass of pure Fernet. Only an absolute madman would drink this alone."_

This is an _aperitiff_, a drink that is meant to be **mixed**, not drank on its own. And of course, drank **AFTER** eating too much since it's meant to help with digestion, and not just binge-drank. It's meant for you to sit down, stop eating, enjoy a drink, have a chat with the bartender, then be on your way.

Now, unto the drinks that are made of it:
Fernet Cola has the exact same boozepwr as Beer, wich is 25. In fact, I have wanted to run a re-test of its code since continued use in-game has proven not to reduce satiety, or at least being _very_ slow at it, wich was its primary use. It will, of course, cause toxin damage if you are starving (as lipolicide does), wich is why, I have to clarify again, this drink is an _aperitiff_, only meant to be drank **when you're fat**.
Fanciulli is a sobering drink, it has **negative** boozepwr wich makes you not worry about liver damage, at all. It also has no satiety-reducing mechanic at all, so no toxin damage from that source either.
Branca Menta has 35 boozepwr, doesn't have the satiety-reducing trait, but cools you down if overheated and also causes a minor tick of stamina damage (in fact, I had first planned it to be just enough for you to get a slowdown, but I realized that people would powergame with it as if it were tirizene, even if it's on_mob_add, so the idea was scratched)

Another shot at logic:

An entire drinking glass of Fernet equals 50 units. 50 units is, by game standards, literally **half** a bottle. Have you ever drank half a bottle of **pure** Fernet and lived to tell the tale? Try that with Thirteen Loko, Hooch or Moonshine, you'll get almost the same effects. Other than lethal injections from brig there aren't many ways to inject 50u of Fernet into someone for it to be a problem.

Fernet is **meant** to be discouraging to drink **pure**.

**Comment by Mickyan** [comment]
Original PR:
> Did you ever want to reduce your satiety FAST without poisoning you in the process with lipolicide?

Now:
> It reduces satiety a bit more than Lipolicide does, with the drawback of causing more toxin damage

At the very least the original PR is misleading, so which one is it

> Branca Menta has 35 boozepwr, doesn't have the satiety-reducing trait

What's this
```
/datum/reagent/consumable/ethanol/branca_menta/on_mob_life(mob/living/M)
	M.adjust_bodytemperature(-20 * TEMPERATURE_DAMAGE_COEFFICIENT, T0C)
	if(M.nutrition <= NUTRITION_LEVEL_STARVING)
		M.adjustToxLoss(1*REM, 0)
	M.nutrition = max(M.nutrition - 5, 0)
	M.overeatduration = 0
	return ..()
```
Again, this has the same effect as drinking it straight despite being only 1/3 fernet

>  Try that with Thirteen Loko, Hooch or Moonshine, you'll get almost the same effects.

50u of Hooch will not kill you, not even close. You will get minor liver damage and will be perfectly fine after a few minutes.

Whatever way you want to look at it starving to death from drinking alcohol is stupid, boozepwr is there to handle negative effects from drinking too much and if you're really so adamant about giving it a downside then you should have it as an overdose effect so people don't have to scour through the code to figure out why they suddently dropped dead from drinking random drinks at the bar.

**Comment by Tlaltecuhtli** [comment]
thing is it causes more tox dmg which means more liver dmg which means it kills slighthy faster if you are also hunghry

**Comment by bgobandit** [comment]
feature, have you ever tasted fernet

**Comment by Mickyan** [comment]
Mate I'm italian, I tasted all of the most disgusting liqueurs you've ever heard of and then some (some of which go up to 70% alcohol content), somehow I lived to tell the tale

**Comment by Grazyn** [comment]
Fernet 9/11

**Comment by bgobandit** [comment]
it's a joke mate

**Comment by Mickyan** [comment]
it's hard to tell when there's someone else saying that unironically

**Comment by ExcessiveUseOfCobblestone** [comment]
So we assume he poorly worded his PR description and go home now?

**Comment by Mickyan** [comment]
It's still unclear what is and isn't a bug, and its design philosophy seem to change in each paragraph

My current plans are, assuming the creator doesn't give a better explanation or make some changes by the time I bother to act on it, to fix branca menta reducing satiety and then move fernet to contraband, because poison disguised as a drink does not belong in the standard selection of the bar

**Comment by ExcessiveUseOfCobblestone** [comment]
go for it 🤷‍♂️

**Comment by zamolxius** [comment]
this is retarded just like fernet and the italian ThePainkiller guy

**Comment by ExcessiveUseOfCobblestone** [comment]
using the r word is ToS violation i'd remove that.
