### ISSUE TITLE
Immortal Circuit machines can be used to instantly kill nukies

### ISSUE THREAD

**Issue by Shadowflame909** [tgstation/tgstation#38587]
Round ID: 89692

Server: Bagil

This needs to be fixed IMMEDIATELY.

A mauler and a syndicate mediborg got instantly killed by an invincible unclickable circuit.
The glass thrower 4 shotted a mech, and then instantly killed the elite nukie inside of it.
It instantly killed the Syndicate Mediborg as soon as it saw it. 

The problem with this is that the nukies tried to e-saw it and shoot it with guns and missiles. None of them hit because the circuit was treated like it was a floor tile planted into the ground. It instantly killed the nukies and ended the round with Circuit bug abuse.

This is some top-tier power game and is unfun for anyone who gets killed by this immortal monster. Especially as an antagonist that has no chance of "picking it up" If this gets abused by a traitor, only devastation could occur! 

Edit: I hear you can pick this invincible item up. But isn't this a noob trap that forces you to get out of your mauler, only to be devastated and put into instant -120 health by a glass thrower? Also syndiborgs cant pick up circuits. So this is just a TC disaster waiting to happen. It also chases you, and swarms around you. Making sure that you cant grab it, and cant out run it.

**Comment by Arianya** [comment]
From cursory investigation, and co-operation from the circuit maker, which is basically all the information I can gather due to #38588:

The machine in question was a remote controlled drone using grabbers to carry 10 small circuits loaded with a thrower and a reloading mechanism.

What this meant was that the drone was composed of:

The drone itself, the remote which the user can use to remotely target it, and the smaller "thrower" circuits. While it doesn't appear to be actually immortal, it is by its nature small and difficult to target, and its 10 throwers meant that it dealt a lot of damage in a very short amount of time.

The issue at hand seems to be the fact that the grabber can hold smaller circuits then itself and that those circuits are still functional while grabbed, but obviously even if they weren't then the drone/circuit could just drop the 10 thrower circuits and then trigger them, so a robust solution is going to be needed.

**Comment by Shadowflame909** [comment]
Thanks for the coherent and easy to understand report Admin!
