### ISSUE TITLE
Gulagging headrevs doesn't trigger end round.

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#38630]
Issue reported from  Round ID: 89783 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

We have multiple headrevs, one of them gets gulagged and the others get killed afterwards, it isn't until he returns to the station and gets killed that the round ends.

He's still listed as fleeing the station.

**Comment by Arianya** [comment]
If this is in reference to the round I think it was, then I believe the headrev in question was gulagged, but was gulagged with a point total and made it back to station before his co-heads died.

I suspect the actual issue is that the round end report shows them as "fleeing the station" even though they had returned to the station and died on station.

**Comment by TheBonded** [comment]
this is no longer an issue since defeating a revolution does not end the round as of dynamic

**Comment by TheBonded** [comment]
I can now actually do something about this
