### ISSUE TITLE
Nutriment pump doesn't do anything after implanting.

### ISSUE THREAD

**Issue by Wilchenx** [tgstation/tgstation#38671]
Because it replaces the stomach slot, you do not regain hunger.

**Comment by GunHog** [comment]
Remember that the standard pump lets you get to the warning level of nutrition but will not let you fall into the red. The PLUS version feeds you whenever you are hungry, so you will only get the warning for a second before it activates.

**Comment by Wilchenx** [comment]
you get stuck at whatever hunger level you were

**Comment by xxalpha** [comment]
The issue isn't the nutriment implant, it works as intended. As you said, removing the stomach stops hunger, this is because the only call to the species digestion proc is in the stomach organ object. Either the proc call is moved to somewhere that makes more sense, or the implant is simplified into an hunger stopping device so it doesn't have to waste resources on a useless on_life() call.

**Comment by Wilchenx** [comment]
I remember it working in the past without a stomach
