### ISSUE TITLE
Abductors are fucking bullshit against AIs.

### ISSUE THREAD

**Issue by Winterous** [tgstation/tgstation#38701]
On what is now two separate rounds, I, as an AI, have been carded and stolen by abductors. There is almost literally nothing that can be done to prevent this.

As I see it, this is many different issues, only one or more of which needs to be solved.

1. They can teleport into secure areas, which are impenetrable to Clock Cultists, for example. This includes upload, AI core and general minisat areas, armoury, etc.. Point is, they're supposed to be SECURE areas.

2. They can teleport inside walls. This renders turrets practically useless against the, as they can just select a blind spot, regardless of where it might be.

3. They are able to act immediately upon teleporting. For an antag with almost godlike power to steal shit at their fingertips, you'd figure there should be a slight stun period in which they're vulnerable, so they can't teleport right next to someone and prod them before they can do anything to defend themselves.

4. They have no rules, despite being one of the few antag roles that really SHOULD have rules. As mentioned above, they have an almost godlike power, they can go pretty much wherever the hell they want, horde whatever items they want, and there's shit all anyone can do about it. There's nothing preventing them from going on a murder spree other than their inability to use guns. Their mission statement is to experiment and observe, severe interference like removing the station's AI seems like a massive breach of that mission, and I feel that things like that and intentionally murdering people except in self-defense should cop a job ban.

For the love of god do SOMETHING to curb this behaviour, it's literally the single most bullshit thing in the game, the only possibly defense is to cut cameras in the AI core, which you would need to do before knowing there are abductors because the pricks will probably do it ASAP, which would obviously be metagaming, and renders you incapable of interacting with your surroundings.

**Comment by DaxDupont** [comment]
this seems like its meant for the forums

**Comment by AlexTheSysop42** [comment]
>meant for the forums
>all but one are code things

**Comment by DaxDupont** [comment]
@AlexTheSysop42 what is coding feedback

Issue tracker is for bugs, and bugs only.

**Comment by GunHog** [comment]
1. Agreed. I have done this twice as Abductor after completing my objective. I steal the AI and implant the card into someone. Both times the AI got really salty because it had to wait a long time for me to capture a victim. Still, as an AI, you cannot defend against this without metagaming. It is almost as bad as wraiths.

2. Response included in point 1.

3. There is a tell a few seconds before an agent hot-drops you. That is plenty of time to move away. Nearly all of my abductor rounds, my agent (or myself) teleported in nearby, then ran up to the target to stun. No change is needed here.

4. I do not feel a change is needed here, except the secured areas change outlined in response 1.

Also, like Dax and Citrus have said, this does not belong on the issue tracker - it is feedback, not a bug, oversight, or code issue.

**Comment by YPOQ** [comment]
1 is mentioned here #37143
2 is kind of mentioned here #35790

**Comment by Tlaltecuhtli** [comment]
i ded

**Comment by ShizCalev** [comment]
Take it to the forum, please.
