### ISSUE TITLE
Frequent random static on cameras

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#38734]
[Testmerges]: #38644 

[Reproduction]: # Its been quite common recently, i'll notice an area that I should have vision on as an ai show up blank for some reason despite the camera working and having it randomly work again.

![image](https://user-images.githubusercontent.com/16896032/41896717-a7d1c59a-7968-11e8-9c32-d127084f351c.png)

Being a malf ai with all camera upgrades and every camera working is definitely a sign that things are fucked.

**Comment by SpaceManiac** [comment]
This is a BYOND bug with `vis_contents`. It also occurs with gas overlays, but is less obvious because there are less of them. It's most noticeable with AIs and ghosts because those involve the most moving around the map.

I haven't yet been able to put together a consistent minimal repro case; as soon as I do I will report it upstream.

The workaround is to use the "Reconnect" option in the top-left menu.

**Comment by SpaceManiac** [comment]
http://www.byond.com/forum/?post=2379470

**Comment by SpaceManiac** [comment]
Though new BYOND bugs continue to arise, this particular one has been fixed
