### ISSUE TITLE
mimes with advanced mimery who are borged keep their mime spells

### ISSUE THREAD

**Issue by factoryman942** [tgstation/tgstation#38975]
round 90680
testmerged: #38938 
Mime "Quiet", engiborg "Ex Syndicate".

**Comment by AlexTheSysop42** [comment]
All spells are tied to the mind and most don't need hands to use, thus any mob with the same mind can use them. Robed spells are an exception, seeing as only humans can wear both a robe and a hat.

**Comment by Shadowflame909** [comment]
Not a bug. If your polymorphed into a simple mob as a wizard, you still keep fireball.

**Comment by OmegaShoots** [comment]
Technically not a bug since the wizard fireball thing.
But, oversight?

Should you be able to use mime spells if you're no longer a mime? You don't keep your vow if you get borged do you? What about polymorphed? And aren't these spells supposed to check if you have your vow of silence?

You should probably lose them if borged/polymorphed but if you get turned back into a human you should regain them.

**Comment by AlexTheSysop42** [comment]
vow of silence is also a spell

**Comment by Shadowflame909** [comment]
Not an oversight either, maybe a coding feedback discussion. Because it was intentional when the spells were linked to the wizards mind.

**Comment by XDTM** [comment]
but how do they use finger guns _with no hands_

**Comment by AlexTheSysop42** [comment]
easy, they mime having fingers
