### ISSUE TITLE
Xenobiology is unplayable as a role without a game version revert.

### ISSUE THREAD

**Issue by birchbark** [tgstation/tgstation#39021]
[Round ID]: # 90778, and the following round on Sybil.

[Reproduction]: # I was able to feed my slimes 4 times, on the newest BYOND build, and the game would crash. This issue has been absolutely catastrophic over the last couple of releases. These would not be server crashes, they're client side hard crashes that have to be ended forcefully.

It's not easy to reproduce, but I seem to increase it's frequency by clicking quickly.

Best way I've managed to avoid this is Reverting to 512.1416. It reduces the frequency. 
Something is absolutely fucked with viewscreens as a whole, just like in
 https://github.com/tgstation/tgstation/issues/39018

**Comment by AnActualDog** [comment]
Yeah please fix this, I had sort of similar problems with botany, it's still playable but I crash two or three times every round. I highly suspect its a shared cause of the problem.

**Comment by Shadowflame909** [comment]
I told you oranges, Reverting to 512.1416 is the best option client side! It fixes all dumb issues

**Comment by birchbark** [comment]
@Shadowflame909 Instead of hard crashes, we get static issues. I can only imagine this has gone undiagnosed for so long because of round times on Bagil being so fucking short.

**Comment by Unit2E** [comment]
I can confirm this is a major issue currently, it's true that reverting to earlier BYOND versions almost entirely solves this issue, too. Pretty much as described in the OP, not reverting means you will crash with a frequency of almost every minute, or every other. I've had crashes as early as feeding the slimes you start with initially, after which the game would crash.

For me, the crashes seem to make the game unresponsive for a second first, then fully freeze without any hope of recovery. I have to force quit out when it happens. I've also heard AI players talk about the static that would happen before, though I don't know their situation currently.

Lastly, I don't believe this is just because of Bagil rounds being short or anything like that. These crashes, or otherwise, static issues, are overwhelmingly common. Before, it wasn't uncommon to be unable to see 2/3 of the pens purely because of the static before 10 minutes round time, and now, it's not uncommon to crash before that point, either. Could be that Xenobiology is entirely neglected in Bagil of course, I wouldn't really know. As a very very last thing, for me, both issues are fairly easy to run into, though they do not follow a set pattern. Crashes happened very, very frequently, as said, every other minute. Seemingly at a similar frequency as when static would normally occur before recent patches, make of that what you will.

**Comment by Cyprex** [comment]
Is this still an issue?
