### ISSUE TITLE
Shuttle navigation computers do not work.

### ISSUE THREAD

**Issue by subject217** [tgstation/tgstation#39030]
How to reproduce: Simply try to use the navigation computer on any shuttle that has one. It will print a message "Warning: Shuttle connection severed!" and nothing can happen. On shuttles that require you to set a location in the first place like the Pirate shuttle, this makes them completely unable to go anywhere.

To clarify, the navigation computer is the computer that lets you set a custom location. The normal shuttle console works fine, except on shuttles that require a location to work at all, like the Pirate Shuttle console.

**Comment by subject217** [comment]
Not a client side issue, very unlikely to be a BYOND issue. My BYOND is on 512.1416 and the server is currently on 1435. If I had thought this stuff relevant I would have included it.

**Comment by nervere** [comment]
Yeah. Just had this issue. Pirate shuttle consoles stay locked because they can't find a destination at all.
It's also worth noting something with the syndicate nukeops shuttle console: although it has a bunch of destinations (see below), it can only fly to syndicate_nw, and back to the syndie base. It can't even use custom locations.
```"syndicate_away;syndicate_z5;syndicate_ne;syndicate_nw;syndicate_n;syndicate_se;syndicate_sw;syndicate_s;syndicate_custom"```
