### ISSUE TITLE
Eye of a blood drunk miner crusher mod can disable your limbs

### ISSUE THREAD

**Issue by CoolCatIsFeelingGroovy** [tgstation/tgstation#39309]
[Testmerges]:
#39136: 'Removes can_vv_get from some things' by Cyberboss at commit 75ea5e3c1b
#37922: '[WIP] [Testmerge-Ready] Nanites 2' by XDTM at commit ee647338a6
#38944: 'Third time's the charm - Photography update: 7x7 cameras, photo logging with full metadata, persistent albums and wall frames!' by kevinz000 at commit 0b3ea71828

[Reproduction]:
When you detonate a crusher mark with a crusher that has an eye of a blood drunk miner mod on it it gives you the blood drunk buff, which also for some reason makes parts of the health doll go red temporarily even though it doesn't damage you, if you get hit even once while you have the buff and it hits you in one of the areas that has gone red that limb can then get completely disabled and just will not work anymore, even after the buff wears off. This can even mean if your limb has already taken a lot of damage just activating the buff can be enough to disable it.

**Comment by XDTM** [comment]
So i've read what it does... apparently it's meant to reduce damage by 90% for one second while active. 

Thing is, what the code actually does is multiply max health along with all current damage by 10, and doing a contrived tick check to multiply healing by 10 (actually eleven because the 10x heal is tacked on to the normal heal). The bug happens because while it does multiply limb damage by 10, it does not update the limb's max health by 10 along with it so 5 damage put it over the max post-buff. But since it doe snot use the proper damage adjustment proc, the limb does not notice it's broken until it takes damage again.

All this could be easily avoided by using the very simple damage_resistance var in the physiology datum, which reduces damage by a percentage.

**Comment by DingleFlop** [comment]
LOL. Thanks for the write up.

**Comment by kriskog** [comment]
Fixed in #42795
