### ISSUE TITLE
Suiciding w/ a gun shoots you in the chest instead of the head/mouth

### ISSUE THREAD

**Issue by Enzarel** [tgstation/tgstation#39601]
![immersionbroken](https://user-images.githubusercontent.com/40743854/43803111-2bed92f0-9a98-11e8-9f3e-4a77bc451658.png)
Found while messing around on my private server running slightly outdated tg code. Haven't tried reproducing on the official server. Damage was applied to the head as normal.

**Comment by Anonmare** [comment]
Maybe you're just a really bad shot

**Comment by CitrusGender** [comment]
![image](https://user-images.githubusercontent.com/31262308/43819116-a1b0d242-9aaf-11e8-8943-c2f24936a606.png)
works just fine on the live server.

I even targeted my chest, head, and mouth.

**Comment by evsey9** [comment]
Except that is a suicide while OP used help ( I think ) intent with mouth targeted on himself

**Comment by CitrusGender** [comment]
yup, can confirm. My b.

**Comment by Kagus** [comment]
As a somewhat related note, be careful if you're trying to use mouth-targeted executions on someone lying on a bed... The round might end up hitting the bed instead of whoever's lying on top of it.

At least, I managed to do that once on the lavaland syndibase with a humanized monkey. They were even buckled to the bed.

Like, I know that they're just bioweapon scientists, but how can they be _that bad_ of a shot when firing point-blank?

Another funny interaction is when I tested with the sniper rifle... The round hit their left leg while dealing enough brute damage to both instantly kill the target and dismember the leg. However, since the leg was removed on impact, the target died with only about 20 brute damage, due to all the damage flying away with the limb it was applied to.
