### ISSUE TITLE
The library console pops up two windows every time it is interacted with

### ISSUE THREAD

**Issue by harmonyn** [tgstation/tgstation#39793]
Round/testmerges: All

How to reproduce: Try to use the library console. An extra window will pop up and it will also refresh in weird ways

Why this is bad: Fucking annoying to have to close an extra window every time you click a button.

**Comment by LudwigVonChesterfield** [comment]
This most likely occurs due to parent proc call in

https://github.com/tgstation/tgstation/blob/master/code/modules/library/lib_machines.dm#L207
https://github.com/tgstation/tgstation/blob/master/code/modules/library/lib_machines.dm#L314

as the parent has a popup of it's own

https://github.com/tgstation/tgstation/blob/master/code/modules/library/lib_machines.dm#L314
