### ISSUE TITLE
hatred-powered jetpack

### ISSUE THREAD

**Issue by RedFoxIV** [tgstation/tgstation#39996]
![2018-08-30_01-37-35](https://user-images.githubusercontent.com/38788538/44819393-6420ab80-abf5-11e8-90fc-b811cc7b847b.gif)
You can use them as a jetpack.

**Comment by RedFoxIV** [comment]
![](https://im.ezgif.com/tmp/ezgif-1-582b5dd4fb.gif)

**Comment by GunHog** [comment]
Well, a very skilled individual could "realistically" (as far as such a thing goes in this game) do this to a space fish. He is kicking away from the fish as it gets within range, AND is getting bitten while doing so.

I would not so much call this a bug, as it seems at least a little plausible to me.

**Comment by Time-Green** [comment]
we need to be able to actually harness carps and use them as a jetpack

**Comment by GuyonBroadway** [comment]
You know that thing they do at seaworld where the keeper swims in the pool and a killer whale swims up under them and pushes them into the air so the keeper does a flip?  You're doing that but with a space carp.

**Comment by Arkvold** [comment]
So, emergent behavior of predator-fueled space mobility, rather than a bug, eh?  The Mario Bros. would be proud.

I say leave it in - reward audacious badassery.  It's not like it's without danger, since he's gotta risk getting bitten with each push-off.  If you can do it, live, and save your own life in the process, more power to you.

**Comment by SpaceManiac** [comment]
emergent behavior, not a bug
