### ISSUE TITLE
Free Miners don't have mech access

### ISSUE THREAD

**Issue by GenericDM** [tgstation/tgstation#40198]
Free Miner ID's don't start with mech access, so they can't fix errors or upgrade power cells of their mech(s) without going to a HoP.

**Comment by FantasticFwoosh** [comment]
I don't mean to say i don't find the premise of the proposed fix a nice QOL to fiddle with mech's but this is just a circumstance where mining only ID is deliberately limiting. Intended i guess, contact your nearest HOP.

**Comment by SpaceManiac** [comment]
I don't think there is a such thing as "mech access". The access requirements of a mech are determined completely by the constructor or operator of the mech - if you want mining conscripts to be able to access a mech, don't upload accesses they don't have.

**Comment by zxaber** [comment]
The access page is a bit strange anyway, as it seems to serve a dual purpose. Only people who have all access listed can seem to hop in, but if you put an MMI into the mech, it gains the door access from that list as well. The list isn't required for door access if you have an ID on you as an organic, so it's a bit counter-intuitive.

That being said, I think Generic is talking about the maintenance procedures, which you start by swiping a card with (I believe) robo access. The only use for this is to swap batteries or repair wires, and it does seem a bit strange that this would require robo access to do. Since the mech can already allow or disallow maintenance procedures from the cockpit menu, it seems a bit inconsistent that this is required (as most other machines in the game aren't job-locked like this).

**Comment by SpaceManiac** [comment]
seems like you're right
```dm
var/list/internals_req_access = list(ACCESS_ENGINE,ACCESS_ROBOTICS)//REQUIRED ACCESS LEVEL TO OPEN CELL COMPARTMENT
```
