### ISSUE TITLE
It is hilariously difficult to die of alcohol poisoning

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#40253]
>join as mime
>pubbystation, lowpop, no bartender
>promptly speed drink every single bottle of alcohol in the damn bar (pubby has them out in public)
>pass out and vomit a bunch, hallucinate, stammer and stagger, but never get (non-hallucinatingly) below green health

no traits, bottle of nothing, etc were in play

**Comment by FantasticFwoosh** [comment]
#36089

- [Over here](https://github.com/tgstation/tgstation/pull/36089/commits/dfee78eec316f196521ca96012a8bb7d9c7e1fc8#diff-81f7c0a4df6099bec4d42e1d86656c66R43), alter this value because the code looks stable enough, knock it down to say... 80-90? 

I dont have time to **_perfectly test_** all these drink-by-drink, and put up a PR @bgobandit  because everyone is honestly going to moan that they end up killing themselves at the bar because everyone tends to drink different amounts. Though liberally knocking it down by 50 or more should kill off people who empty the entire bar or drink dangerous high strength spirits recklessly. (_if i understood the formulae right_)

**Comment by kriskog** [comment]
Get light drinker or go for the very hard liquour if you wanna drink yourself to death, killing yourself with beer isn't easy irl either. Or bring it to the forums as a feature request.
