### ISSUE TITLE
Fire Fuckery

### ISSUE THREAD

**Issue by Poojawa** [tgstation/tgstation#40261]
So been experimenting with heat radiation into walls, which from what I can tell is working amazingly. but I've noticed some weird fuckery that I believe is unrelated for the most part

Holodeck plasma flood is impossible to light without a bonfire, it just doesn't work at all. Or it works sporadically. as if not all the spark igniters trigger at once. It's usually only a short spark that ends up with the room at ~98C

Fire extinguishers are kinda fucky in how they cool stuff. I've had rooms dip below 0 spraying with them. other times it doesn't do much but remove the hotspots and cool 2-3C a spray.

Wall heat radiation means fires are able to put themselves out by becoming too cold to continue burning, which is kinda weird. Might need a change in how fires act since I don't think they've been touched in a positive way other than being fancy colored in ages.

Wall heat doesn't transfer nicely with ambiance, so stuff like space doesn't cool maintenance. It would be neat to have atmosia worry about things like proper distro temperature that isn't just 'haha it's burnmix time' heated.

Doors don't transfer heat. seems only a thing that /machinery/atmospherics is allowed to do.

**Comment by Barhandar** [comment]
>It would be neat to have atmosia worry about things like proper distro temperature that isn't just 'haha it's burnmix time' heated.

Atmostechs are _already_ incompetent and can barely follow an inept wiki tutorial, do you want them to be extra incompetent? Bonus: Meta has heater/freezer on distro while Box doesn't.

**Comment by cinder1992** [comment]
The obscene tempuratures seen in that round (93829) originated from a supermatter failure caused by an ashwalker with a wrench.

it burned a lot of tritium, and while I didn't get a look at how hot the supermatter chamber actually got, the heat radiation was enough to heat adjacent rooms to almost 1e+21c in places, while at the same time spreading to other rooms faster than it could vent into space, causing some form of "thermal runaway"

The 4.8e+9c number was just one I could copypaste in time to warn people of the high tempuratures, sadly it heated stuff so fast that most of the station was dead from the heat before anyone could do anything about it.

(pls fix omega)

**Comment by miniusAreas** [comment]
I can also attest to the issue with heat. Becoming a arsonist with a flamethrower or releasing plasma into the distro has become impossible without literaly having a welder and or ignighter timer on every tile you want lit, else it puts itself out and relights the tile endlessy untill theres no plasma. Fires dont spread at all unless you reach stupid high temps. A few rounds of hippie and SunsetStation, a branch of TGcode thats beng updated downstream, and testing on a local server bring me to this conclusion-
>Fires can no longer spread from other fires
>Flamethrowers cant spread their fire to other plasma moles.
>Igniters wont light or start fires
>The Atmospheric Burn holodeck Program no longer lights completely on fire, instead resulting in a ton of plasma in a room.
>Turbine works fine however, leading to a new conclusion.
That is, that the new Atmos gasses (Tritum, etc) for fusion are doing some weird shit with atmos that puts the plasma out due to temp or otherwise, and may be replacing all the o2 on a tile at once, or burning it all at once. Finding this was due to the turbine burning at max plasma temp in just a few seconds, even with the vents open. Fires cant procure enough o2 to even spread, meaning that my favorite Hijack method of running onto the station with a atmos firesuit, hauling several re-labled cans of plasma or o2/plas burnmix onto the shuttle is impossible. This is going into a seperate issue, but commented here due to the fact that they may be linked.

**Comment by kriskog** [comment]
Fire ignition is more consistent now, was fixed a while ago. The rest seems to be feature or rework requests, bring it to the forums where it might be seen by someone.
