### ISSUE TITLE
Staff of locker deleting people on vehicles

### ISSUE THREAD

**Issue by Suicidalpickles** [tgstation/tgstation#40292]
round #93931
title, seen multiple people on janicarts get hit by it and it ghosts them instantly, nothing left of their bodies to clone.

**Comment by Qustinnus** [comment]
lol classic timegreen code

**Comment by 81Denton** [comment]
It also has some fun interactions when used with the locker staff
- Gibs anyone inside the locker
- Straight up deletes silicons, only thing left is their encryption key

**Comment by YPOQ** [comment]
Here's what's happening
1. The bolt hits the janicart, causing a locker to created (empty if the bolt hasn't hit anyone else)
2. The bolt hits the person riding the janicart, moving the person into the bolt
3. The bolt is qdel()
4. The bolt's Destroy() attempts to forceMove() its contents (the janicart rider) onto the bolt's turf, however this causes the rider to Bump() the bolt, which for projectiles will call prehit/on_hit(), moving the rider back into the bolt.
5. The standard Destroy() calls qdel() on the bolt's contents

The issue @81Denton mentioned is just because explosion severity is being decreased (more devastating explosion) instead of increased.
https://github.com/tgstation/tgstation/blob/3a73bb504614917e4653ed7478e712c0c26db38a/code/modules/projectiles/projectile/magic.dm#L416

**Comment by Qustinnus** [comment]
@Kmc2000 @nichlas0010 every time(green)

**Comment by nichlas0010** [comment]
@Time-Green :))))

**Comment by Time-Green** [comment]
Lower severity is stronger explosion? That doesnt seem right
The locker gib thing is just what happens when you nullrod a locker, might be a slight balance issue.
I overlooked the locker instantly picking it back up when something dropped, I’ll fix it somewhere later today

**Comment by octareenroon91** [comment]
> EDIT: ill also just disable the gib stuff, and see check what the deal is with severity, apart from not being *0.5

The `severity` parameter of `ex_act` is an index, not a scalar.
`1` = devastation
`2` = heavy damage
`3` = light damage

**Comment by Time-Green** [comment]
Oh god I really fucked up there then
