### ISSUE TITLE
You can't show your ID by using it inhand anymore.

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#40530]
Caused by the economy. I'd suggest making it alt click to show your ID or something.

**Comment by bgobandit** [comment]
man what isn't caused by the economy these days

**Comment by Hathkar** [comment]
Does this also affect things like Agent IDs?

**Comment by wesoda25** [comment]
Again, is there no way to check your current funds? I’ve noticed that if you examine your own id, it just acts as if you examined your character. Am I doing something wrong or is this an issue as well?

**Comment by Iamgoofball** [comment]
@wesoda25 thats a bug, examining IDs in the ID slot redirects to s self examine for some reason

This was not an oversight, this was removed and I forgot to document it. You can show your ID off to people by having them examine you. Agent IDs probably are fine, since they used a different method anyways.

**Comment by BeeSting12** [comment]
No, it's an oversight. You should still be able to show IDs. Make it so alt click does it.

**Comment by Iamgoofball** [comment]
It's not an oversight if it was removed intentionally, and alt-click is already reserved for syndicate ID stuff, and also a pain in the ass, but sure, whatever. I'll get around to it later this weekend after I wrap up some other projects, ping me on discord in 2-3 days
