### ISSUE TITLE
Lavaland tendril was moved to station, created chasms on-station

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#41067]
Was reported in round by a player. Player claims they buckled the tendril to a lava boat and dragged the boat to the station.

**Comment by XDTM** [comment]
The chasm spawning should do a lavaland ztrait check, so at least it stops making holes into nowhere on station every time a new exploit pops up or if admins feel like spawning one

**Comment by evsey9** [comment]
Feature, lavaland tendrils are actually advanced syndicate bluespace tech used to send nanotrasen agents into the shadow realm and turn them to syndicate's side

**Comment by FantasticFwoosh** [comment]
No different to a BOH chasm except the part with pernament death. Feature.

* Rod & floortile to fix it back to normal, this is also the case on lavaland.



> 
> 
> Are we not gonna address the fact that this absolute unit of a miner buckled a fucking tendril to a boat and hauled it onto the station

Even if you couldn't move it directly (office chairs also work) you would still be able to fulton it to the station because its a mob. Kevinz broke a few things with tendrils specifically with the moveresistance PR.

**Comment by kriskog** [comment]
Fixed a while ago
