### ISSUE TITLE
Robotics surgery area on Metastation is missing a cautery

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#41117]
Issue reported from  Round ID: 95979 (/tg/Station Sybil [ENGLISH] [US-EAST] [100% LAG FREE])
Reporting client version: 512
#41029: '[READY] Hilbert's Hotel' by TheDreamweaver at commit 13222f3d9a

Box has one, not sure about delta/pubby. Considering they have (really awkward) access to implants and organ manipulations, unlike amputations/replacements, need cautery to finish, they should have one.

**Comment by ahkent** [comment]
also wtf is with the archaic exofabs

why dont they work like a scifab or protolathe or w/e

**Comment by ahkent** [comment]
im 100% ok with exofabs handling all cybernetics period, implants included, its the responsibility of robotics to do cybernetics. they might need a name change to something other than "exo" fab because not all exosuits, but.. 

god, robotics needs some fuckn love. its stuck in 2010 in, like, all aspects.

**Comment by kriskog** [comment]
This if fixed
