### ISSUE TITLE
[goon genetics] sometimes completing the gene wont activate it

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#41477]
i had 2 #15 mutations from 2 subjects, when i finished the genome it didnt activate, happened in multiple rounds

http://take.ms/TQPQI

97038

**Comment by Time-Green** [comment]
Are you sure it was correct and are you sure it wasnt a monkey?

**Comment by AlexTheSysop42** [comment]
happened to me too, not a monkey and definitely correct (round 98960) for 3 different genes - 11, 5, and another that I dont remember
this also happened multiple times on another round, I suspect certain genes are failing to activate when completed and thus not showing as completed or having any effects (and I suspect void magnet is one of them)

**Comment by AlexTheSysop42** [comment]
I haven't gotten it activated once

**Comment by Time-Green** [comment]
If this happens again, and you’re 100% sure you did it right, ask an admin to do the following:
Go to your dna datum, and check mutation_index.
Compare the mutation’s sequence with the one from the global variable called full_sequences.
If they’re completely identical and the host isnt a monkey or something else incompatible, post the sequences here with the mutation and some other details that may’ve caused it to break.

I’ve ran into this problem too, but every single time it was because I made a mistake solving the genome

**Comment by Names-Are-Hard** [comment]
![image](https://user-images.githubusercontent.com/35442306/66625992-6a7ca780-ebab-11e9-804d-cad8af9bc029.png)

**Comment by Time-Green** [comment]
Oh, thank you. I’ll get on it sometime this weekend

**Comment by SuperNovaa41** [comment]
Genetics UIs have been reworked a number of times by this point, and I have never personally experience this issue, nor heard of it from anyone else. It's probably safe to say that this has been solved.
