### ISSUE TITLE
Revs arent being saved to manifest.txt

### ISSUE THREAD

**Issue by nfreader** [tgstation/tgstation#41581]
## Round ID: 97283

Check the manifest.txt: https://tgstation13.org/parsed-logs/basil/data/logs/2018/11/18/round-97283/manifest.txt

No head revs or revs listed, even though this was a rev round: https://sb.atlantaned.space/rounds/97283

**Comment by Jordie0608** [comment]
Revs are selected in `post_setup()` called at https://github.com/tgstation/tgstation/blob/6b83785146edde2f65c4e8bc6f301072c96799ae/code/controllers/subsystem/ticker.dm#L295

whereas the manifest is made before this in `setup()` https://github.com/tgstation/tgstation/blob/6b83785146edde2f65c4e8bc6f301072c96799ae/code/controllers/subsystem/ticker.dm#L264

Would be fixed by simply moving `GLOB.datacore.manifest()` to after L295 and changing it to loop through a different list than one of new players. `joined_player_list` or mobs with jobs probably.

**Comment by AnturK** [comment]
Yeah it's done bit too early and needs some minor refactor.

**Comment by AnturK** [comment]
It doesn't, manifest only logs special_role aka roundstart/latejoin assignment. Honestly should probably remove antag logging from that file, antagonist feedback is more accurate in most cases.

**Comment by nfreader** [comment]
Roundstart/latejoin is a useful metric, but if we can get that same data from the antagonist feedback then that's fine too.
