### ISSUE TITLE
tactical plastic flaps

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#41589]
1. Punch someone and start a fight
2. Run and crawl under flaps
3. Have free reign to click them while they can’t click back, double points in you click with a stun weapon so they don’t even get a chance to alt click the tile and click you.

Might not seem too exploitable at first but it wouldn’t be that difficult to set up multiple flaps around places you might be fighting, or baiting people to parts of departments with them.

**Comment by GravitronBlue** [comment]
Similar issue to #41348 
Although if you're really you're serious enough to setup more plastic flaps to get overlay cover you may as well just raid engineering to print atmos holoprojectors. (which IMO are much better)

A mildly effective tactic to deal with overlay cover is to crawl into cover with them, which still runs of the risk of being hit but leaves you less exposed bringing up the tile contents menu in order to melee, but overall you're best off throwing things or getting a ranged weapon.

I'm not all too certain on a solution, options range from #11786 (which was closed due to negative feedback), changing above-mob layered icons to have gaps big enough to click mobs under them, making said icons no longer layered above mobs, or possibly buffing the alt-click menu to let you open up tile contents from a reasonably short distance so long as you can see it.

Using a ranged weapon or throw things would sound like and be the optional hard-counter, however I present... **TACTICAL ASCENSION**
![](https://i.imgur.com/rIeI5SG.png)

**Comment by Tlaltecuhtli** [comment]
emergent gameplay

**Comment by k-k-karma** [comment]
stop reporting my meta tactics

**Comment by OmegaShoots** [comment]
I mean just... walk away?
Nobody says you have to sit there and fight them.

**Comment by nicbn** [comment]
Just make holobarriers be placed below mobs and make the center of the plastic flaps non-opaque to mouse by using vis_content
