### ISSUE TITLE
Magic 8 ball item requires ghost proximity to be able to answer

### ISSUE THREAD

**Issue by Vidiveni** [tgstation/tgstation#41718]
## Round ID: 
Terry 97766

## Testmerges: 
#41099

## Reproduction:
1. Chilled as a ghost. 
2. Saw "Kennard Beach is shaking the magic eightball, hoping to get an answer to "Congratulations, you made it to Orion!" (Click to help) "
3. Clicked . I got a popup with every option greyed out. So I quickly clicked "orbit" under ooc to find his name and get close. The options stopped being greyed out and I could answer. The answer was repeated IC by the ball. 

I expect ghosts to be able to answer the ball without needing proximity. This was the toy version, and I assume the traitor item is broken as well.

**Comment by YPOQ** [comment]
Here's the call chain that is causing this
https://github.com/tgstation/tgstation/blob/e7cc2074c6825e9052fc5b5d9909057d4ba7d75a/code/_onclick/other_mobs.dm#L59-L62
https://github.com/tgstation/tgstation/blob/e7cc2074c6825e9052fc5b5d9909057d4ba7d75a/code/_onclick/other_mobs.dm#L49-L51
https://github.com/tgstation/tgstation/blob/e7cc2074c6825e9052fc5b5d9909057d4ba7d75a/code/modules/mob/mob.dm#L746-L747

It would be easy enough to change `can_interact_with` to allow observers or override `can_interact` on magic eight ball but this code probably should be refactored since it's overriding the tgui logic
