### ISSUE TITLE
Round time mismatches

### ISSUE THREAD

**Issue by Dorsisdwarf** [tgstation/tgstation#41725]
## Round ID: 97807

![](https://puu.sh/C9EyI/fc11b8c2bf.png)

Some sort of bug causes a mismatch between the official round time and the amount of time the round actually has gone on for. This apparently causes stuff like the alert level elevation to happen instantly instead of several minutes in.

## Testmerges:
The following pull requests are currently test merged:
#41099: '[READY]New Map: Donutstation V.5 (GOLD) (Platinum Hits)' by MMMiracles at commit 
[b8372c3950]

## Reproduction:
 I don't know how this would be reproduced unless its happening every round.

**Comment by kriskog** [comment]
The status tab round timer starts counting as soon as the lobby starts, while the end report timer only counts the time from round start. Don't know if this is intended behavior.

**Comment by Jacquerel** [comment]
This bug may or may not be fixed, in that I don't understand which part is the bug.

The round time listed in the status panel is, confusingly, the time since the _server restarted_ not the time since you actually started playing the game. It will always be off by the amount of time spent in the lobby where you can decide whether or not you are ready.
As far as I can tell this has been true basically always, and still is.

This shouldn't affect when the blue alert happens, and as far as I can tell playing the game about four years later, it correctly doesn't.
