### ISSUE TITLE
Lost control of AI shell and could no longer pilot it after a crash

### ISSUE THREAD

**Issue by Anonmare** [tgstation/tgstation#41748]
ROUND ID: 97880
![image](https://user-images.githubusercontent.com/12382984/49324484-6a8d2f00-f526-11e8-8805-818bd8c8ccd7.png)

**Comment by Anonmare** [comment]
I am definitely The Machine and I was piloting that borg 1 minute earlier. I crashed, reconnected and could no longer use it.

**Comment by GunHog** [comment]
Did you crash *while* controlling the shell, and reconnected to find yourself in the AI core? My guess is that your game crash prevented the code resetting the deployed status on that shell, so the shell still thinks it is in use.

**Comment by Anonmare** [comment]
Yeah it crashed while I was in control and put into the AI core

**Comment by zxaber** [comment]
I attempted to test this by connecting to a shell and then killing the game process, but I ended up dropped back into the shell when I reconnected. I suppose it might be fixable with a check to see if the AI attempting to connect to the shell is the same AI that's listed as connected in the shell's variables, but I'm not sure if I'd be able to test it working.

**Comment by GunHog** [comment]
Perhaps you could do the dual login trick (on a local server, connect using your BYOND account, then log out. Connect a second time as a Guest and you will have two connections). Play as AI, spawn a shell, switch to it as AI, and then disconnect. Use your second client to smack the AI with something, forcing a disconnect. Rejoin as the AI player and see if that reproduces the issue.

If this does NOT reproduce the issue, then something else screwed up for Anonmare and I have not the slightest clue what.

**Comment by zxaber** [comment]
No luck. When the AI client rejoins afterwards, they are in the core, but the shell was correctly released and is able to be used again. The only way I could reproduce the issue was by admin-ghosting the AI player while they're in the shell, and then offering the AI's core to ghosts and re-entering it with the AI player.

**Comment by GunHog** [comment]
I tried to catch as much as I could think, although admin-ghosting does not release the mob like normal ghosting does. Thinking about it now, I never accounted for player swaps during a shell deployment. If another player gets put into the AI while the old player is in the shell or is ghosted from that shell, I suppose that could trigger this issue too.

As for line 924, since the AI shell never gets to run the `undeploy()` code, it will fail the `R.deployed` check. It basically says "Of all AI shells ingame, show the ones that are: alive, **not already deployed**, not dead, and not synced to a different AI." 

Another very remote possibility is that the AI shell might not be on the AI shell list. AI shells are added to the list when made into a shell (usually by using the B.O.R.I.S.). AI shells are removed from this list when the shell is reverted by resetting its module, or when it is destroyed. Unlikely, but mentioned for the sake of completeness.

I am not sure what happened for Anonmare, though. I imagined that anything that breaks it would be the result of admin shenanigans, as I am not aware of anything that tries to mess with the AI player's client/mind while it is using a shell.

**Comment by zxaber** [comment]
Oh, yeah, it says 'if not deployed'. I missed the 'not' part. Makes sense why it wouldn't let me back in during my tests, and that should be a fairly simple reorganized 'if' chain to fix.

The only other thing I can think of that might have caused the issue is if a client crashing does something crazy before exiting. I had tried to simulate a crash by just ending the game process. But maybe a natural crash gives enough time to try and clean things up or something, who knows.

**Comment by Anonmare** [comment]
Since it's admin shenanigans - closing it.
