### ISSUE TITLE
Disablers don't have a capped stamina damaga on limbs

### ISSUE THREAD

**Issue by GhostEcho** [tgstation/tgstation#41774]
Round ID: 97988

 Testmerges: Not a testmerge, but I believe the issue is caused by this: https://github.com/tgstation/tgstation/commit/107cb109379059940c8eefd42d1f84429c7b7126

 Reproduction: Disablers don't seem to have a cap on how much stamina damage they can do, which means you can essentially permanently stun someone by just firing a bunch of disabler shots at them. Even one egun spread across two people can stun someone for several minutes. This doesn't seem intended, but if it is, then that seems idiotically overlooked, and horrendously overpowered

**Comment by GhostEcho** [comment]
So the issue seems to be stamina damage in general, rather than just disablers

**Comment by ExcessiveUseOfCobblestone** [comment]
@kevinz000 perhaps :O

**Comment by ATH1909** [comment]
Who needs the brig when you can just administer TIMEOUTS (because let's face it, that's what brigging someone is) on the go? With our patented disablers, you can make someone inactive for several minutes without ever needing to deal with that pesky Warden!

Buy some disablers from your local cargo department (or mug the Warden for some) today!

**Comment by optimumtact** [comment]
fixed apparently
