### ISSUE TITLE
Impossible reflection of emmitter beams on reflectors

### ISSUE THREAD

**Issue by KetasDotepasto** [tgstation/tgstation#41987]
## Reproduction: On Metastation, set up the mirrors in the SM engine as seen in the attachement. 

For the reflectors, set the angles as follos, clockwise from bottom left: 290, 290, 270.

This resulted in the beams beeing reflected in an impossible way, also, please see the attachement.
![impossiblemirrorreflection](https://user-images.githubusercontent.com/11960566/50059077-9513f480-0182-11e9-8937-e4bfb6d1f768.gif)

**Comment by Korywon** [comment]
Could be related to #41980 

I believe the issue is related to the reflector boxes. The double-sided and single-sided are reflecting them into the box. However, once it gets to the reflector boxes, it bounces back and forth between them and then bounces on the left double-sided reflector, resulting in those two beams being thrown back.

**Comment by kriskog** [comment]
This has been fixed
