### ISSUE TITLE
Reflector boxes/emitters are behaving wierdly.

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#41980]
Issue reported from  Round ID: 98705 (/tg/Station Terry [EU] [100% LAG FREE])

Reporting client version: 512

See the gif:
https://i.imgur.com/LNtvsyg.gif

**Comment by 81Denton** [comment]
#41919 could this be the cause?

**Comment by DaxDupont** [comment]
@81Denton seems doubtful
@kevinz000 I'm correct in assuming that PR doesn't cause this issues right?

**Comment by Korywon** [comment]
Had this issue as well yesterday. Tried using different emitters, tried changing the reflector boxes, moved the reflector boxes. Oddly enough, the reflectors work fine for me if I fired it from the north.

**Comment by ma44** [comment]
This is probably because reflectors uses a different way of reflection that doesn't use handle_ricochet()

https://github.com/tgstation/tgstation/blob/master/code/game/objects/structures/reflector.dm#L62

The auto_reflect() does actually reduce the range but only by one per reflect (while also refreshing the range)

**Comment by ExcessiveUseOfCobblestone** [comment]
#41915 sounds like a very similar issue
