### ISSUE TITLE
H.E.C.K. Suit not Lavaproof?

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#42031]
Round ID: 98965

I was playing the holoparasite of a miner, and we ended up on lavaland after we got dumped in a reality tear. I suggested he run through the lava to get back, but we quickly died, while he slowly died to lava damage.

**Comment by HomocidlePancakes** [comment]
It never was lavaproof and i have no idea why you thought so

**Comment by 4dplanner** [comment]
It says on it that it can withstand lava. This is confusing, but it means the SUIT can withstand lava, not the person inside it.

**Comment by YakumoChen** [comment]
It has a LAVAPROOF tag on it though

**Comment by 4dplanner** [comment]
> It has a LAVAPROOF tag on it though

There's a LAVAPROOF tag, which means the item isn't destroyed by lava, and a LAVAPROTECT tag, which means the item protects the wearer from lava. HECK suit has the first, but not the second.

**Comment by Whoneedspacee** [comment]
H.E.C.K. suit was never lavaproof for the user and I’ve never seen anything that would indicate that. Probably a more fitting consistent item for a more difficult boss, I’d like to see more lava proof user besides like the drake potion.

But yeah not the heck suit, it just doesn’t work since bubblegum already drops op as hell loot.

**Comment by optimumtact** [comment]
desc probably needs an update but yeah not a bug.
