### ISSUE TITLE
c4 and x4 messages ghost get when clicked wont move you to the place the bomb is

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#42172]

**Comment by SpaceManiac** [comment]
Happens only if the non-turf the C4 is planted on has been fully destroyed by the time you click

**Comment by Iatots** [comment]
Right now, it happens when it's a wall subtype I believe.
On a recent round 4 charges were planted, handily on 4 different objects: a wall, an rwall, a window and a plasma window. The wall I could not follow to. The rwall was armoury outer, and I could not follow to (and I did scoot to armory as ghost to check it out). The normal window was escape sec station on metastation, and the plasma window was the window right of the SM engine. Both windows I could follow.

I can't for the life of me find the round ID, it was on terry this week and the antag was grug caveman.

**Comment by PKPenguin321** [comment]
The ghost prompt should maybe report coords instead of the actual object

**Comment by SpaceManiac** [comment]
I would expect turfs to actually work perfectly but maybe there's some shenanigans afoot

**Comment by timothymtorres** [comment]
Maybe this is due to c4 being in nullspace?

**Comment by EuclidianGeometer** [comment]
I believe this issue has been resolved?

**Comment by Sealed101** [comment]
surely #80810 fixed this for good
