### ISSUE TITLE
Lazarus Injectors Breaks Morphs

### ISSUE THREAD

**Issue by Shadowflame909** [tgstation/tgstation#42352]
## [Round ID]: 100189

So, correlating with my last issue. I found a new one the same round.

I died, got lazarus injector'd unknowingly, so the Morph NPC took control. It turned into an air injector pipe and vent-crawled.

I re-entered my body, and walked out of a vent.

I literally couldn't see myself, I walked around, walked into space. Nothing, I was invisible, literally.

The worst part was that I was invisible shape-shifted, so I couldn't interact with anything outside of moving either and I couldn't unshapeshift as I had no mob to click on, to unshapeshift!

A potential solution for this may just be some sort of alternative hotkey, that allows you to restore your Morph-Form. For those times you literally can't click yourself, like this.

**Comment by ExcessiveUseOfCobblestone** [comment]
Or to not have the AI turn literally invisible lol.

**Comment by PKPenguin321** [comment]
Alt click the tile you're on and you'll see yourself in the alt click panel where you can be shift clicked

**Comment by Shadowflame909** [comment]
I tried that, game didn't detect me. Only the floor tiles!

**Comment by Mooshimi** [comment]
Make it so lazarus injector forces ghosts back into body, not sure why it doesn't currently

**Comment by Sealed101** [comment]
can no longer reproduce; morphs are basic as of #77503, lazarus injector works on basic mobs as of #72440 and `revive()` fetches the ghost of the dead mob, if any... which was the case when this issue was filed, so the problem was maybe caused by the simplemob AI back then? oh well
https://github.com/tgstation/tgstation/blob/9849ce19534d28d2aea8813866b87f507a40c1e0/code/modules/mob/living/living.dm#L845-L888
https://github.com/tgstation/tgstation/blob/9849ce19534d28d2aea8813866b87f507a40c1e0/code/datums/mind/_mind.dm#L525-L529
