### ISSUE TITLE
ai turret bug

### ISSUE THREAD

**Issue by kilmne** [tgstation/tgstation#42368]
Issue reported from  Round ID: 100285 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

disabled the turrets in ai upload, the top and mid right turret did not turn off causing round loss

**Comment by ATH1909** [comment]
Which map?

**Comment by zxaber** [comment]
According to Statbus, this was on Metastation.
https://sb.atlantaned.space/rounds/100285
However, I just tested with a local server that was freshly downloaded two days ago, and could not reproduce the error. Using a captain-level ID, I can disable the upload turrets without issue.

**Comment by timothymtorres** [comment]
So I looked at the attack logs for that round and I can confirm that @kilmne did turn off the turrets and got blasted by electrodes for a long while.  Then another head came and turned on the turrets and set them to lethal and killed him.  I don't believe the AI messed with the turrets either.

Regardless this is an old issue and turrets have had numerous code improvements since then that removed a lot of bugs.  I'm going to close this since I haven't been able to find any similar issues matching this bug.  It is very likely that whatever was causing it got fixed at some point.  Ping me if you run into this problem again and I will reopen this issue.
