### ISSUE TITLE
radioactive contamination issues

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#42496]
if you're wearing a full rad suit, the radiation still contaminates the clothes being covered by it.

**Comment by Daxxed** [comment]
Fusion is risky stuff, having to camp a shower and stripping every item including those in boxes inside backpacks is a feature.

**Comment by Menshin** [comment]
> Theres a parameter called protect contents or something, which I personally think the rad suit needs.

They actually do, but it does nothing since underneath clothes are not `content` of the rad suit, but the mob wearing the radsuit.

Worth to note : radsuits can become contaminated themselves, and once acquired `component/radioactive` never gets away (it gets stuck near `background radiation` level, slightly below 9).

**Comment by Bawhoppen** [comment]
Contamination is no longer a thing so this issue can be closed
