### ISSUE TITLE
Being unconscious while having the AI Multitool allows you to see around you.

### ISSUE THREAD

**Issue by KomradeSpectre** [tgstation/tgstation#42580]
Issue reported from  Round ID: 101033 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

I was unconscious in maintenance during the round, and decided to see if I could toggle any of my tools (as I always like finding weird edge case errors to report), and lo and behold upon clicking the toggle for the AI Multitool, the unconscious/blind overlay was removed, and replaced with the AI Multitool overlay that let me see everything around me while I was unconscious.

Before toggling it:
![image](https://user-images.githubusercontent.com/12734451/51889928-c4fd0d00-2368-11e9-90a0-7ae92c9a7c1a.png)

After toggling it:
![image](https://user-images.githubusercontent.com/12734451/51889923-c0d0ef80-2368-11e9-8412-dcf018a70772.png)

The only reason for the second picture looking like it still limited my FOV is because I was in a dark area.

**Comment by ATH1909** [comment]
I've been telling people about this bug (on both Discord and in OOC chat) for quite a while now.

You don't need to turn it on while you're unconscious- as long as it's on/active (and in your pocket, hand, etc.), you can see while blind, unconscious, and/or in crit. You can even see while in areas with no cameras watching them!

Do note that if you would normally be blind without the multitool, you won't be able to see any messages that blind people wouldn't see (although you can still see sprites change), nor can you examine things.

I seem to remember being able to see in the dark (but also not see any better in the light, with everything looking a bit darker than normal in lighter areas) while blind and with this multitool on/active. Maybe it was because I had flashlight eyes (this item makes them actually viable, since you can ignore their major downside of blinding you and reap)? I could have sworn that I was able to see in the dark with them both on and off, though. Maybe it's because you have thermals?

All of this for only 1 TC- much better (in most circumstances) than, say, a box of syndicate tools.

If you do decide to fix this bug, might I suggest adding a separate traitor item that replicates this bug but costs more than 1 TC? Call it a "third eye" or something.

Is this really deserving of a priority: high flag when things like shapeshifting (or at least vampire shapeshifting) and antimagic are still borked, though? Like, I'm pretty sure that the chaplain's null rod not providing any protection against wizard spells is a bigger issue than an AI detection multitool making flashlight eyes semi-viable, and I don't recall the antimagic issues having priority: high flags (do correct me if I'm wrong, though).
