### ISSUE TITLE
Bug Compilation (Gun Issues) Post PR #41804

### ISSUE THREAD

**Issue by Zoozele** [tgstation/tgstation#42683]
Issue reported from  Round ID: 101414 (/tg/Station Bagil [ENGLISH] [US-EAST] [100% FREE LAG])

Reporting client version: 512

Spawn an RPG
Wonder why its not there
Right click tile -> its there, it just has no sprite.

Possibly caused by #41804?

![rpg machine broke](https://user-images.githubusercontent.com/30756491/52318517-7106af80-298a-11e9-9a04-b238cd37cf7f.PNG)

**Comment by ExcessiveUseOfCobblestone** [comment]
Yes

**Comment by ExcessiveUseOfCobblestone** [comment]
#42686

**Comment by Tlaltecuhtli** [comment]
donksoft lmg is missing sprite

**Comment by Tlaltecuhtli** [comment]
donksoft smg (syndie) has no mag sprite

**Comment by actioninja** [comment]
donksoft shit being broken is due to me incorrectly assuming toy weapons used their own shit instead of just being the exact same sprite code but pointing to a different dmi. Working on a fix for that right now that doesn't result in dupe sprites.
RPG is already fixed, missed some custom nonsense that I forgot to clear so it wasn't using the overlay system like it should.
grenade launcher just wasn't pointing to the right state, fixed.
I have no clue what's wrong with the empty 1911, it should be working. It just isn't, going to need to do some more testing.

Once I get all these done going to roll them into a PR.

**Comment by subject217** [comment]
The L6 SAW claims in the examine text that you ctrl+click it to open the cover, but you actually alt click. @actioninja

**Comment by subject217** [comment]
Bulldog magazine overlay appears to be non-functional.
