### ISSUE TITLE
minibomb not damaging the vault safe

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#42739]
an operative team used 2 c4 on the vault safe, getting it to the "heavily damaged" state. Heavy+ explosions are supposed to increase its exploson count, but syndie minibombs right next to it did not push it to the needed third explosion. It was clear that the tile of the vault safe was getting hit with heavy explosions.

https://github.com/tgstation/tgstation/blob/c4213f13ab6ab368d00db9f4383bdf556c1bc4ea/code/game/objects/structures/safe.dm#L182

**Comment by Tlaltecuhtli** [comment]
it needs a devastation ex act doesnt it?

**Comment by timothymtorres** [comment]
This is because the syndie minibomb exploded on the tile next to it.  See:

https://github.com/tgstation/tgstation/blob/9e72e7af249c104ca5d69e1cc12efad3fc7a3e71/code/__DEFINES/explosions.dm#L1-L9

https://github.com/tgstation/tgstation/blob/55b92786dcf0f9c5172efd111a6ecbf83ec0dae2/code/game/objects/structures/safe.dm#L85-L94

https://github.com/tgstation/tgstation/blob/11302feef45d2bc0fc717ee426114c2c7e52caeb/code/game/objects/items/grenades/syndieminibomb.dm#L1-L11

If the minibomb had exploded directly on the tile it would have broken open.
