### ISSUE TITLE
Voice Change symptom permanently prevents speaking

### ISSUE THREAD

**Issue by Names-Are-Hard** [tgstation/tgstation#42871]
## Round ID:

102365

## Testmerges:
None

## Reproduction:
Be infected with a virus that has transmission 14 and the voice change symptom.

**Comment by ATH1909** [comment]
To clarify, I believe that you have to get the virus cured in order to become unable to speak any language (you can still use borg chat, though (did I mention that this effect persists if you get MMI'd or borged?)).

If I had to guess, I'd say that the symptom locks you into only being able to speak one language, but doesn't undo that when it gets removed. It'd then revert your languages back to the what they were before, leaving you locked into a language that you can't speak.

That's just theorizing, though- I'll need to get a better look at the code to see if my theory is plausible.

Try seeing if curators are (usually) able to speak after getting the disease cured, and see if they're locked into one of their many languages.

**Comment by AnturK** [comment]
Isn't this intended ?
https://github.com/tgstation/tgstation/blob/3e30e3fbb9a27097bb3e86c92c7c24b61a79be29/code/datums/diseases/advance/symptoms/voice_change.dm#L34

**Comment by Names-Are-Hard** [comment]
The problem is that the effect persists even after the disease is cured.
