### ISSUE TITLE
Tactical Liver Removal can be exploited to benefit from on_mob_add

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#43024]
## Round ID: 
103049

## Reproduction:
Remove a patient's liver, make them drink cyanide, watch as they take no toxins damage whatsoever because not having a liver means you can't process chems which means they can't affect you at all. Who thought that's how *any* of this works??

This makes not having a liver basically superior because you're able to treat injuries with bruise packs and ointment and are immune to every poison in the game. While you won't be able to treat toxins, the only sources of toxins you can even take are things that deal direct toxins damage to you, like mini ebows.

**Comment by ATH1909** [comment]
Not having a liver is actually pretty lethal... unless you can mass-produce corazone, which lets you not suffer any damage or the like you take for not having a liver.

But wait, it gets cheesier: You're not immune to the on_mob_add (or the on_mob_remove) effects of chems, such as the speed boost from nuka cola and the full stun immunity and psychotic brawling martial art from bath salts, which won't expire until those chems fully leave your system (if they'd normally expire from the calling of on_mob_remove) (which will be hard to make happen, as you don't process chems and they won't deplete naturally). You won't suffer the nastier side effects of some of those drugs (such as the brain damage from bath salts), of course, since they're tied to on_mob_life.

I made a list of the chems with positive on_mob_add effects that you can use with this bug back when imsxz reported it; lemme see if I can pull it up.

**Comment by ATH1909** [comment]
Here's a link to imsxz's report of this bug: https://github.com/tgstation/tgstation/issues/42016

And here's my list of chems with beneficial/non-instantaneous (so not the healing from, say, being splashed by synthflesh) on_mob_add chems and their effects:
bath salts (get the psychotic brawling fighting style and immunity to stuns and sleep)
meth (speed)
happiness (good mood)
ephedrine (speed)
morphine (ignore slowdown)
psicodine (fearless)
brave bull (+10 max and current health)
tequila sunrise (radiate light)
alexander (+10 block chance with a shield)
nuka cola (speed)
grey bull (shock immunity)
holy water (holy trait)

stimulum (bath salts without the psychotic brawling)
nitryl (speed)

pax (pacifism)
zombie powder (fake death, will leave you immobile)
mimesbane (makes you unable to emote)

ghoul powder (fake death, won't leave you immobile)
stimulants (speed)
changeling speed chems (speed)
muscle stimulant (ignore slowdown, only found in hot potatoes (I think))

**Comment by ATH1909** [comment]
> ok good job wasting 20 min

HAH! I showed _you_, Tlaltecuhtli! The list _did_ come in handy!

It should be noted that corazone has a special variable called "self_consuming" set to TRUE that makes it be processed (and passively consumed) by liverless creatures; you could patch this exploit without letting people process and/or consume all chems while liverless by setting that variable to "TRUE" for the chems in the list above.

**Comment by WJohn** [comment]
i mean

maybe we should make it so you can still be affected by chems in your body even if you don't have a liver

i see no reason why cyanide shouldn't be able to actively kick your ass *and* linger in your body at the same time. they simply wouldn't ever be flushed out.

**Comment by tralezab** [comment]
The problem with that is that you could inject 1u of every healing/positive chem in the game and become the tyrant from resident evil

**Comment by ATH1909** [comment]
I mean, I guess you could make medicinal and drug chems deplete themselves by default, while letting toxins not deplete themselves but still deal damage (by default)?

**Comment by imsxz** [comment]
@tralezab thats not how it works. you dont get the on_mob-life(when the chem is processed) part of the chems; they don't process. the issue is specifically that you *dont* get that, while getting on_mob_add (when the chem is added)

this makes stuff such as bath salts, morphine, and ephedrine especially strong with this exploit. Bath salts gives stun IMMUNITY when it's added. You won't have a liver to process it, so you dont get the massive brain damage that would be working in tandem to balance it. The same is true for morphine's slow immunity, and ephedrines speed boost, in that without a liver you get to have all 3 of these listed chems (at 1u or whatever you fancy) and get a permanent stun immunity, speed boost, and immunity to being to slowed, without incurring the massive brain damage from bath salts, sleeping from morphine, or whatever ephedrine does on mob life.

**Comment by ATH1909** [comment]
> @tralezab thats not how it works. you dont get the on_mob-life(when the chem is processed) part of the chems; they don't process. the issue is specifically that you _dont_ get that, while getting on_mob_add (when the chem is added)
> 
> this makes stuff such as bath salts, morphine, and ephedrine especially strong with this exploit. Bath salts gives stun IMMUNITY when it's added. You won't have a liver to process it, so you dont get the massive brain damage that would be working in tandem to balance it. The same is true for morphine's slow immunity, and ephedrines speed boost, in that without a liver you get to have all 3 of these listed chems (at 1u or whatever you fancy) and get a permanent stun immunity, speed boost, and immunity to being to slowed, without incurring the massive brain damage from bath salts, sleeping from morphine, or whatever ephedrine does on mob life.

He was responding to WJohn's suggestion:


> i mean
> 
> maybe we should make it so you can still be affected by chems in your body even if you don't have a liver
> 
> i see no reason why cyanide shouldn't be able to actively kick your ass _and_ linger in your body at the same time. they simply wouldn't ever be flushed out.

**Comment by ExcessiveUseOfCobblestone** [comment]
just make a lack of liver immediately give OD effects regardless of current units so it's epic HiRiskHiReward gameplay

**Comment by PKPenguin321** [comment]
Doesn't not having a liver make you die
Like in real life I mean

**Comment by ExcessiveUseOfCobblestone** [comment]
it would be extremely painful *bane voice*

**Comment by Cyprex** [comment]
We shouldn't have two github issues open for the same issue, #42016

**Comment by 81Denton** [comment]
>it would be extremely painful *bane voice*

@ExcessiveUseOfCobblestone for you

**Comment by WJohn** [comment]
That has variable effects, cobby. Some chems do not have an OD threshold at all, and I'm sure we have some chems that do not have OD *and* have secondary effects. If you know which chem that is from reading the code, you'd still benefit from those, and otherwise be immune to a huge amount of poisons.

**Comment by ExcessiveUseOfCobblestone** [comment]
don't tell anyone but I want ODs for everything
