### ISSUE TITLE
Ass photocopying is broken

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#43348]
Round: 104689, Sybil

Photocopying your ass doesn't work anymore, you get a blank photo ("The photo appears to be blank...")

**Comment by DaxDupont** [comment]
CRITICAL SHOWSTOPPER BUG

**Comment by HomocidlePancakes** [comment]
Intended feature. Ass pictures are fetish content and thus are not allowed on our ERP-free christian TG servers. You should be ashamed of even ATTEMPTING to photocopy your ass because PHOTOCOPIERS and ASSHOLES are the SPAWN OF THE DEVIL created in to lead yout to DAMNATION. Repent child. Go to a church this sunday. Tell the priest about the HORRIBLE DEED you have done to a PHOTOCOPIER with your ASS today or suffer eternal hellfire after your DEATH.

**Comment by kevinz000** [comment]
huhwhat?!
