### ISSUE TITLE
Holding an empty grenade casing allows you to block bullets without losing the casing.

### ISSUE THREAD

**Issue by Nickkoranda** [tgstation/tgstation#43503]
Step 1. get an empty grenade casing
Step 2. hold it
Step 3. congrats you have rng chance to get hit and not take damage

**Comment by Ratvar** [comment]
Step 4. Does it work with flamethrower empty canisters?

**Comment by PKPenguin321** [comment]
Surprised nobody noticed this sooner

**Comment by WJohn** [comment]
holy shit that's hilarious

**Comment by ATH1909** [comment]
I believe that I did notice this earlier, but I thought that it'd delete the grenade casing, so I didn't look into it too much.

Does it work while in your pocket?

**Comment by ATH1909** [comment]
As far as I can tell by looking at the code, this only works while the grenade is in your hand.

The chem grenade isn't destroyed because it isn't in the "READY" stage yet, causing the prime() function to return without destroying or using the grenade.

This doesn't really break game balance- this only has a 15% chance to block non-stamina projectile attacks (and doesn't block any other kinds of attacks). Compare that to the block chances and block mechanics of shields, and it's pretty clear that this is outclassed by even the buckler (it is cheaper to mass-produce, though, I guess).

**Comment by FloranOtten** [comment]
We should make the bible block bullets instead
