### ISSUE TITLE
Adding solar panels to the SM chamber increases power output

### ISSUE THREAD

**Issue by FloranOtten** [tgstation/tgstation#43520]
Issue reported from /tg/Station Terry [EU] [100% LAG FREE] [New-Dedi]

Reporting client version: 512

Step 1. Activate SM
Step 2. Add solar panels all around SM
Step 3. Watch as power goes from 300-400KW to 960KW

Don't ask me how I found out

**Comment by Michael-Ashfield** [comment]
Could this be due to the stupid way radiation works. Like, chucking any item into the SM chamber increases power output because the items become irradiated and then radiate their radiation. There is a current exploit which uses bluespace RPEDs to easily get multiple MW power output on a basic engine setup.

**Comment by FloranOtten** [comment]
![image](https://user-images.githubusercontent.com/38219334/55675495-c811fd80-58c3-11e9-8342-d4801ae1f253.png)
picture for reference

**Comment by ATH1909** [comment]
Why haven't we changed the way that radiation works yet?

**Comment by nicbn** [comment]
@ATH1909 be our guest and do it

**Comment by YakumoChen** [comment]
We did and that's why it is how it is now

**Comment by ondrej008** [comment]
this is related to the radiation memes, if you used a bluespace RPED filled with parts, even more power would be made

**Comment by willox** [comment]
This would be a dupe of https://github.com/tgstation/tgstation/issues/42572

**Comment by tralezab** [comment]
and the other one is a bit more descriptive
