### ISSUE TITLE
buying message should have a cooldown

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#43535]
it says it every time you buy

![image](https://user-images.githubusercontent.com/222630/55689847-b7529d80-593e-11e9-8d7d-d069696a69aa.png)

**Comment by Daxxed** [comment]
I use this message to count how many survival pens/core stabilisers I bought as miner.
Would have to count or right click and check the pile otherwise, this is great please do not remove.

**Comment by Daxxed** [comment]
The issue here is that med vendors spam it to common chat.
Most vendors, like the mining one just give you a local or maybe even personal message.
They do not take up the entire screen because it would be something like
"The vendor clanks and dispenses a survival pen x5" rather than spamming the entire chatlog.

**Comment by nicbn** [comment]
@SpaceManiac fixed
