### ISSUE TITLE
Resist button avoids mech exit time

### ISSUE THREAD

**Issue by Rowelll** [tgstation/tgstation#43648]
Issue reported from  Round ID: 106361 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1466

As the title says. You can click the "Resist" button to not wait some seconds, like you do with EXIT button in the left upper corner.

**Comment by ATH1909** [comment]
Epic.

**Comment by Whoneedspacee** [comment]
where its called on living: https://github.com/tgstation/tgstation/blob/704e1183b457cae333c0ccd600b963a314853d34/code/modules/mob/living/living.dm#L704

where it happens: https://github.com/tgstation/tgstation/blob/a944c2a362ebacbc603358d4137f103257f09221/code/game/mecha/mecha.dm#L981

why the change to give mech exiting the timer was done this way causing this idk but this is why its happening

where the change was: https://github.com/tgstation/tgstation/blob/c035efd05195cbef4a1127daf9ddc2fe37bc8eb8/code/game/mecha/mecha_actions.dm#L49

literally only changed the action to exit instead of the exiting proc neato
