### ISSUE TITLE
Nanites has no grief protection or ability to hide personal programs - there should be something that works similarly to the disks in Genetics

### ISSUE THREAD

**Issue by AWalton** [tgstation/tgstation#43697]
Was learning nanites earlier and it quickly became obvious the limitations of nanites seeing as anybody can walk in and delete your programs, or if you're traitoring then anyone is able to see that you've been making psuedo-viruses by checking the Cloud Controller (unless you destroy the console completely). Similar issues have happened to me in Genetics before I learnt to use disks, so personally I wouldn't consider nanites until some sort of fix is made, and it makes sense to me now why this lab is always empty (on Terry at least). 

__Proposed solution: Nanites tablet__

A small handheld device that you pop the disks into and similarly to the Cloud Controller you upload the Program Hub data to it. It can hold dozens of programs but it's use is only:
- For storing your programs as a backup (similarly to genetics cloning disks)
- For editing the nanites in the device user's body. Other people with nanites are not affected by the changes made 

This is also a lot more believable. There's no way in the future we wouldn't want to get a mobile app which could control our nanites, this is the closest alternative.

**Comment by HomocidlePancakes** [comment]
H U G B O X

**Comment by RaveRadbury** [comment]
Could make a case for a program for modular PC's. @Wilchenx

**Comment by ATH1909** [comment]
This is supposed to be the main drawback of having cloud-synced nanites.

If you don't want the programs of your nanites to be remotely edited, don't sync your nanites to a cloud ID.

**Comment by AWalton** [comment]
>This is supposed to be the main drawback of having cloud-synced nanites (perhaps even greater than the shock/emp weaknesses of nanites).

I can see that, but the drawbacks of nanites are too large right now which is why the lab is always empty. In contrast Genetics has a way to make backups of your work, and that doesn't have all the triggers and the scripting you have to do for nanites. 

It feels like using a floppy disk when you're surrounded by supercomputers on the station. You can't store old programs you've created when you want to swap them out for different ones for only a certain duration of time. You can't backup your programs even if you're playing good-guy nanites scientist who only modifies themselves. 

I don't see a good reason for not at least having a way to backup your data i.e. instead of a tablet it would be a nanites hard drive which works basically the same as Genetics cloning disk. 

The ability to modify your personal nanites without the chamber or console is a _separate_ proposal, which I don't want to get in the way of the first. 

The traitor maint Cloud Controller which affects everyone? Sure, that fits. But editing just your own? I think it's excessive. Maybe a way to trial it could be the tablet only has the signal to edit your personal nanites if within 50 tiles of the originating Nanites Programmer. That way it's easier to nerf this capability and reduce the range if it proves to be too powerful, or extend the range if fits well as an ability of a nanites scientist.

**Comment by Barhandar** [comment]
The lab is always empty for entirely different reasons. Namely: 

1. You need considerable amount of research for nanites to become useful, including the cloud controller. Attempting to research them before actually valuable researches are done can and will end up with you getting lynched for being a selfish prick.  
2. Whether or not you use cloud, nanites involve a _lot_ of shuffling individual disks back and forth between three different TGUIs, meaning you need to dedicate considerable amount of time to do it. And without a test subject, pretty sure you can't even do it solo before cloud - and nobody is going to be willing to sit in there having nanites applied to them, simply because it's boring.

Also, nanites are actually extremely powerful, so making them easier to use can and _will_ end up the same way viro vent: in state of complete garbage.

P.S. Just print more nanite disks instead of overriding your programs on them every time.

**Comment by ATH1909** [comment]
> P.S. Just print more nanite disks instead of overriding your programs on them every time.

P.P.S. There's a box of, like, 7 nanite disks in the nanite lab already; you don't even need to print any extras.

I think what AWalton is trying to say here, though, is that you should be able to "save" a full nanite setup to a special kind of disk so that if the clown deletes all of your programs, you won't have to painstakingly recreate/reupload all of them (and can instead put in the special disk, which will let you replace the programs that are currently in a cloud ID with the programs that have been saved on the disk). Maybe even make it like circuit cloning (back when circuits were a thing), where you can get a code for your nanite setup that you can use in a later round to make one of these "full loadout disks" from a nanite programming console (provided that you have all of the techs required to make the programs used in the disk/nanite setup).

**Comment by YakumoChen** [comment]
It'd be nice to be able to upload more than one program to a disk at a time, too.

**Comment by Angustmeta** [comment]
If you wall in the cloud controller with reinforced walls it's usually left alone the rest of the round.

**Comment by optimumtact** [comment]
this is not a bug, these are feedback for the forum.
