### ISSUE TITLE
bodybag of holding + a bag inside 

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#43766]
you can fold the bodybag with the bag inside (and keep the inventory window open) and then place the folded bodybag inside to make its content disappear from reality

**Comment by ExcessiveUseOfCobblestone** [comment]
*sigh*

**Comment by ATH1909** [comment]
Does it go into nullspace, or,..?

**Comment by Time-Green** [comment]
It goes into the mob contents. I used it with a nukedisk once but they just blew up my body and grabbed the respawned disk

**Comment by ATH1909** [comment]
> It goes into the mob contents. I used it with a nukedisk once but they just blew up my body and grabbed the respawned disk

Wait, what did they blow up to make the disk teleport? If I'm understanding this bug right, the bluespace bodybag and all of its contents just disappear (into nullspace?). There's nothing left behind to blow up.

If someone tried to do this with the nuke disk during an op round, couldn't the ops just survive until the ending of the round and get a minor syndicate victory (since you presumably can't bring a disk that's in nullspace with you on the escape shuttle when it launches).

**Comment by Time-Green** [comment]
@ATH1909 not exactly sure how it all works, but it really does end up in mod contents. Using it with people will just have them constantly on you, till they break free and go on with their life

**Comment by ATH1909** [comment]
Will the disk still show up on pinpointers?

**Comment by Time-Green** [comment]
Yup.
