### ISSUE TITLE
Grass bug - growth not progressing

### ISSUE THREAD

**Issue by Iocanthos** [tgstation/tgstation#43760]

**Comment by HomocidlePancakes** [comment]
Had that happen like 5 months ago or so. I was making grass in deep storage, but it never fully grew. Even AHd that.

**Comment by Teepeepee** [comment]
this is a bug that keeps coming back ever so often, I remember someone reported it last year and some months ago too, and I've been experiencing it on and off through that time period too

**Comment by jegub** [comment]
The impression I've gotten is that it's related to grass having a particularly low maturation speed (2), and that this causes an intermittent failure of /obj/machinery/hydroponics/proc/update_icon_plant() in hydroponics.dm.
It's possible to have some plants reach maturity as expected and others not in the same round, plants which don't tend to do so eventually but sometime past 30 cycles rather than 7. Altering the changeable stats either beforehand or with mutagen once planted doesn't seem to make any difference.

**Comment by jegub** [comment]
Just tried a quick and lazy fix out locally, I bumped maturation speed up to 3 and took production speed down to 4 from 5. One thing I hadn't anticipated was that the trays did not immediately show the growing grass sprite, perhaps reaching that stage instantly has been a factor.
I've grown 45 trays of grass and 15 of carpet without issue so I would be inclined to just alter those values and not have anything with a maturation speed below 3.

**Comment by optimumtact** [comment]
which server did the original issue occur on?

**Comment by HomocidlePancakes** [comment]
I had it happen on bagil once

**Comment by ArcaneMusic** [comment]
Due to the changes to both earthsblood, botany, and  plantgrowth, I think this may be fixed.
