### ISSUE TITLE
Overpowered wizard exploit

### ISSUE THREAD

**Issue by py01** [tgstation/tgstation#43782]
Wizard can mindswap with a scout stand, then fly around the map nearly invisible, at a very high speed, and with the ability to walk through walls, while still being able to cast spells, such as fireball. The stand now controlling the wizards body can now stand in a locker while the wizard kills the entire station with little effort.

**Comment by AnturK** [comment]
Hilarious.

**Comment by Fikou** [comment]
feature

**Comment by Eskjjlj** [comment]
That was an epic murderbone by the way. I'm pleased.

**Comment by ATH1909** [comment]
That's amazing. It's like the fugu gland+scout stand thing (which isn't actually all that strong), but so much better

**Comment by GhostAvenger** [comment]
Feature

**Comment by ATH1909** [comment]
Mind transfer already checks to see if the body you're trying to mind transfer into is a changeling, wizard, etc. (and then fails if the check passes); it'd be a trivial matter to add holoparasites to that list.

**Comment by 4dplanner** [comment]
lol

**Comment by ATH1909** [comment]
Combine with the host being an alien golem for maximum cheese.

I do recommend picking up a scrying orb for your holoparasite (in your body)- both to be nice and so that it doesn't get bored and commit suicide and/or ghost in your body (having an ally that can listen to deadchat and silently communicate with you from anywhere is also pretty nice).

If you want to troll instead of murderbone, you can take blindness, curse of the barnyard, and forcewall instead of fireball x2. This leaves you without a way of directly harming people, but that might be for the best (as being trolled by a nigh-invisible, noclipping wizard is much less infuriating/likely to provoke a bwoink than being killed by one).

**Comment by py01** [comment]
here's another possible use: wiz gets tp then mindswaps, tp's to station as scout, leaving his host in an inaccessible dimension as an alloy golem to heal out any damage, and the wiz can instantly recall to another dimension if ever threatened.

**Comment by GhostAvenger** [comment]
Damn it stop making this problem even worse with your smart thinking

**Comment by Tlaltecuhtli** [comment]
i see no bugs here

**Comment by ATH1909** [comment]
> here's another possible use: wiz gets tp then mindswaps, tp's to station as scout, leaving his host in an inaccessible dimension as an alloy golem to heal out any damage, and the wiz can instantly recall to another dimension if ever threatened.

Two problems with that plan:
1: Teleport isn't a robeless spell; you can't cast it as a holoparasite (without summon events-related or admin-related shenanigans).
2: IIRC, the scout holoparasite's "infinite" range uses the normal holoparasite range mechanics, just with a maximum range of 255 tiles. As far as I can tell, this means that you'll just be automatically recalled back to your host once you leave their z-level.

**Comment by Ratvar** [comment]
Nah, you get recalled into NULLspace if you leave current zlevel as holoparasite, I think. Thanks bugs

**Comment by ExcessiveUseOfCobblestone** [comment]
TP is clothes req so can't do that.

**Comment by GhostAvenger** [comment]
Surprised none of the staff noticed this and put it up as exploit

**Comment by 4dplanner** [comment]
>  the staff

Who?
