### ISSUE TITLE
I found a monkey that had only one potential mutation

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#43812]
This is an image of the monkey's genetic sequence: https://cdn.discordapp.com/attachments/326826573951008769/574177443154362378/one_mutation.PNG

As you can see, it only has one mutation (monkified) in it.

The monkey also had an "ERROR" message on him when I humanized him: https://cdn.discordapp.com/attachments/326826573951008769/574177696519684096/one_mutation2.PNG

Gene scanning the monkey also suggested that it had only one potential mutation.

**Comment by Time-Green** [comment]
Error could be hair. I’ll go figure out what got fucked

**Comment by ArcaneMusic** [comment]
There have been several genetics reworks and major tweaks since this issue was posted and current. I think it's far to say that this may have been fixed since then, and with no round ID to go on, there's not much one can go on here to really pursue this issue any further. If it does creep back up, feel free to comment and I'll reopen.
