### ISSUE TITLE
Strained muscles not being very straining

### ISSUE THREAD

**Issue by Garen7** [tgstation/tgstation#43980]
When I was testing #43979 I noticed the changeling ability strained muscles  seems way better than the comment "At first the changeling may regenerate stamina fast enough to nullify fatigue, but it will stack" implies and may be a bug caused by some of the changes people have done to stamina over time.

In practice strained muscles lets you run at full speed for a very long time with very short almost negligible bursts where you are forced to walk, and also when looking at my character's vars it said I had 0 stamina damage even late into the ability so it seems like something must be up, please someone verify that this is the original way ling strained muscles worked when they were first made.

**Comment by ATH1909** [comment]
Fun fact: if you toggle Strained Muscles on and off, you get to keep the speed boost without needing to deal with the increasing amounts of stamina damage.

This is because turning off your Strained Muscles power (without collapsing from exhaustion) actually just gives you the movement speed modifier of the power again instead of removing it (and before you ask, no, it doesn't stack).

**Comment by py01** [comment]
dupe #42787

**Comment by Garen7** [comment]
@py01 no, I'm saying I think the stamina damage of strained muscles is being negated even if you have strained muscles on, besides I'm fixing #42787 in the PR I mentioned in the description.

**Comment by optimumtact** [comment]
That does sound like a balance issue but I don't think it's a bug as such
