### ISSUE TITLE
Metastation garden has a lighting anomaly

### ISSUE THREAD

**Issue by Chocobro** [tgstation/tgstation#44092]
## Round ID:
108975

## Reproduction:
![ok](https://user-images.githubusercontent.com/5677255/58192195-17678e00-7cb8-11e9-9ae8-6b6c8566e6a1.PNG)

**Comment by WJohn** [comment]
That's not lighting, it's line of sight. Opaque directional objects look very nasty like this, and reveal what's on their tile no matter what direction you look at it from. This also happens in the holodeck lounge as it uses tinted windows.

![image](https://user-images.githubusercontent.com/5988156/58192546-f8a0d180-7c8e-11e9-82a1-fa6925c8fa18.png)

Like this circled spot isn't a lighting issue either. It's just weird LOS issues caused by directional objects yet again.

**Comment by Chocobro** [comment]
yeah yeah DEFINITIONS just making fix berserker

**Comment by HomocidlePancakes** [comment]
Issue? Wut. It’s a tanned window, you aren’t supposed to see through it

**Comment by Barhandar** [comment]
The issue is the tile with window itself being visible. As opposed to "black tile that has the window drawn over it.

**Comment by Chocobro** [comment]
what barhandar said
fix is either make the full tile opaque or make the door seethrough
