### ISSUE TITLE
kevinz broke projectile colossion a while ago and nobody has reported it until now

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#44143]
related to the revenant ones, lasers are hitting bots and mice and otherwise shit that lasers would normally pass over without targetting directly. the thing that broke it was the check that made projectiles hit people that are resting but not stunned.
@kevinz000

**Comment by ATH1909** [comment]
"colossion"

Bring back tactical resting; that should fix this bug.

**Comment by Whoneedspacee** [comment]
honestly it doesnt really make sense anyways that people that are resting dont get hit, they should be more capable at dodging than someone unconscious

**Comment by Barhandar** [comment]
You don't need to get up to hold weapons and shoot back.

**Comment by Whoneedspacee** [comment]
crouch shooting is the css of the future

**Comment by YakumoChen** [comment]
shooting people by targeting their sprite is a lot harder then just shooting a direction their sprite is in. It's a strategy that works a lot more well for people who aren't security, as mobility is important as security and you are often outnumbered and hindering yourself by cutting your mobility is an easy way to die or get griefed by whoever is nearby that wants to fuck with an arrest. 
On the other hand a traitor with a revolver or whatever wins by lying down because now he's just become exponentially harder to hit while also being able to move and shoot.

**Comment by Tlaltecuhtli** [comment]
i tought it was a feature

**Comment by HomocidlePancakes** [comment]
#42656 I did report it but noone CARED : (

**Comment by ArcaneDefence** [comment]
Kevinz has changed projectiles yet again
