### ISSUE TITLE
Oversight - Ash walkers cannot make leather

### ISSUE THREAD

**Issue by Denthamos** [tgstation/tgstation#44308]
## Reproduction:

Ash walkers are unable to make leather for goliath cloaks as they do not have a puddle or sink in order to wash leather in to wet it.  You are unable to wet leather using their water tank, bucket, or water bottle.

**Comment by ATH1909** [comment]
It's also very hard for them to acquire the sheet of plasteel required for them to make a pestle (for a mortar and pestle).

**Comment by HomocidlePancakes** [comment]
They won’t be doing ghetto chem anyway so they don’t need a pestle. I would like a puddle to be added at ashwalker place tho.

**Comment by YPOQ** [comment]
Getting wet leather is possible, just a bit unintuitive. First you use a spear on a goliath hide to get hairless hide, then drop the hairless hide on the ground and splash a bucket of water (use harm intent) on it.
I'm not aware of anyway to dry the hide though.

**Comment by Denthamos** [comment]
@YPOQ That is what I was figuring on how it would work, but none of the ash walkers in the round were able to actually do that.  You had 6 ashwalkers all surrounding leather with a bucket and the water tank, trying to splash it.  All we could do was splash the ground the leather was on and that did not work.

**Comment by RaveRadbury** [comment]
@HomocidlePancakes There's an idea to grind the mushrooms up to make a poultice that doesn't have nutriment, so.

**Comment by Daxxed** [comment]
What do you mean no ghetto chem ?
Uranium + iron = RIP disabler and borgs

**Comment by HomocidlePancakes** [comment]
@daxxed if you are raiding station you might as well use the grinder in mining kitchen tbh

@RaveRadbury I am suprised I never thought of it myself. Tbh I would just heal with milk

**Comment by Daxxed** [comment]
@HomocidlePancakes
I like to do everything self sufficient when possible. I feel disgusting enough breaking machines for cable coil to make a bola.
Lizards could always use some more powergame but if I can do it like a savage then I will.

Biggest reason lizards even had a flavour/rule change is because they would show up in mechs from the golem ship using a teleporter. The combat would be perfectly balanced if they were not able to powergame from other ruins.

**Comment by HomocidlePancakes** [comment]
>I like to do everything self sufficient when possible. I feel disgusting enough breaking machines for cable coil to make a bola.

You are harvesting cable coils. How isn’t that self-sufficient?

**Comment by FantasticFwoosh** [comment]
There is no tutorial to play the game but  _microwave_act_ introduced to bonfire grilles will dry your leather for you, and the free resource of unlimited water can be found in showers & sinks on ruins and the mining base to be taken back to the camp and stored. Both of these were added in #27546 &  #27250 respectively.

This entire issue I believe is a hugboxing of new player's inexperience in the optional role with different gameplay, much which is learnt and improvised rather than designed and planned.
