### ISSUE TITLE
Lavaland flora chemicals not extractable via botany disks

### ISSUE THREAD

**Issue by funkmaster3000** [tgstation/tgstation#44519]
Issue reported from  Round ID: 110576 (/tg/Station Event Hall: Sseth overflow event. [ENGLISH] [EU] [100% FREE LAG])

Reporting client version: 512.1448

The special chemicals from lavaland plants, like tinia luxor and vitrium froth, cannot be extracted from the plants in the DNA extractor with a disk, unlike every other plant. They seem to only have a placeholder nutriment gene.

**Comment by ExcessiveUseOfCobblestone** [comment]
That's intentional IIRC

**Comment by HomocidlePancakes** [comment]
Why was it made intentional?

**Comment by ExcessiveUseOfCobblestone** [comment]
Oh then yeah they're a bug.

The ORIGINAL pr adding them specifically left them out if memory serves correct.

**Comment by ExcessiveUseOfCobblestone** [comment]
just populate `reagents_add`

**Comment by funkmaster3000** [comment]
if I was interested in learning how to do some basic DS coding so I could try to fix stuff like this, where would I even start?

**Comment by granpawalton** [comment]
If you already know the basics of coding learn how to create a PR through git desktop(easier) or git bash(harder but more robust)

If you dont know the basics of coding then look up youtube tutorials or go on something like codingbat.com and start with like java because once you learn one language its typically really easy to learn the next

If you want to start only on dm coding then I dont think I can give you the best advice there
