### ISSUE TITLE
Going to station causes shuttles (nukeops, whiteship etc) to become stucc forever

### ISSUE THREAD

**Issue by adamkad1** [tgstation/tgstation#44605]
steps
1-get shuttle
2-go to station
3-try to get away from station
4-nope.avi

**Comment by necromanceranne** [comment]
It's not just delta. It's literally anywhere but a custom destination. This is affecting the white ship as well, and basically means that nukies cannot win at all because they can never send their shuttle back to the base.

This has been happening for about three or so days. You can pretty much guarantee replicate it every time trying to doc the white ship station side.

**Comment by AnturK** [comment]
@ninjanomnom From quick runtime lookup placing custom docking port makes it nullspace then moves it so it can't retrieve backdrop area.

**Comment by ninjanomnom** [comment]
once again custom shuttle docking ruining everything

**Comment by Shapsy** [comment]
Did we mention this nuke ops run was a suicide mission?

No?

Oops!
