### ISSUE TITLE
Curator Nasa Void helmet does not protect plasmamen

### ISSUE THREAD

**Issue by MegaEmpirical** [tgstation/tgstation#44648]
Still lights us on fire even though the helm is space worthy.

**Comment by fludd12** [comment]
This appears intentional. Plasmamen do not appear to be able to wear just any spaceworthy helmet, they seem to require their helmet specifically.

In exchange for this, plasmamen helmets are innately spaceworthy.

**Comment by MegaEmpirical** [comment]
This is the only helmet I know that has this issue. EVA suits are fine and so are all hardsuit helmets. Are there others you're aware of that are not safe? Also, it doesn't make any sense for a suit that protects you from the environment around you wouldn't keep gases out.

**Comment by fludd12** [comment]
Ah - I see the issue, actually. I misread the code. In order to maintain survivability, you have to wear a full space suit set to obtain the `atmos_sealed` flag required to not light on fire if you aren't wearing the standard plasmaperson set. If you are just wearing the NASA Voidsuit helmet, it will not stop you from igniting.

If wear the full suit and the issue persists, I have _absolutely_ no idea how that happens, as the NASA voidsuit is a nearly unmodified subtype of the EVA suits.

**Comment by MegaEmpirical** [comment]
Ah, I didn't get to try both on at once since I was burning. I've never had an issue mixing matching before (Eva helmet, plasma suit/hard suit, plasmaman helmet) but not being able to mix and match at least makes sense.

I'll see about trying to full suit later today.

**Comment by MegaEmpirical** [comment]
I think I found the issue and it was just me being stupid. My bad.

However, shouldn't the cursor outfit + the curator space suit protect from scrubber ejections? I just got hit with fucking 80+ units of morphine and the guy next to me in a rad suit is fine.

**Comment by tralezab** [comment]
though testing (peace of mind) using the plasmaman helmet or using the void helmet and suit both create a seal that prevents fire. AKA what fludd12 said above. This seems to be working as intended

**Comment by MegaEmpirical** [comment]
Sorry for the delay, ended up getting busy. I did some testing and realized that this seems to be the case. Thanks for looking into it.
