### ISSUE TITLE
Multi Z(not) light dont light up and down.

### ISSUE THREAD

**Issue by Dennok** [tgstation/tgstation#44681]
## Reproduction:
Walk up on 2 levels and see dark above lamp.

**Comment by Dennok** [comment]
@SpaceManiac please add this to the [Multi Z Stations](https://github.com/tgstation/tgstation/milestone/30) milestone

**Comment by timothymtorres** [comment]
I tested this today on ice.

![dreamseeker_Vs8DgPgppZ](https://user-images.githubusercontent.com/5195984/143782165-1d2b73d0-d0a4-43c7-8b53-0c1b19764ca5.png)
![dreamseeker_2B8fE52EvN](https://user-images.githubusercontent.com/5195984/143782168-091d4591-d122-4377-9302-e1d6ed54cb7f.png)
![dreamseeker_UFQnVs7QlI](https://user-images.githubusercontent.com/5195984/143782172-270059a1-62b3-49c1-9398-723c910bc695.png)

I'm going to mark this with the `Cleanup` label (autocloses it in 7 days) since I think this is resolved.

**Comment by TheBonded** [comment]
>(autocloses it in 7 days)
@timothymtorres are you sure about that?
