### ISSUE TITLE
Power bugs

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#44973]
Wiring is even more shit then usual despite the testmerge, satellites with SMES units aren't delivering power properly. I had Donut tcomms go out immediately on the last Donut round I played and it couldn't be fixed the entire round.

round ID: 112314

## Testmerges:
#44310 
#44945

**Comment by YakumoChen** [comment]
@actioninja

**Comment by actioninja** [comment]
Yeah this is due to smeses currently connecting in on themselves. They'll pull from the network just as much as they put out resulting in APCs not charging correctly.
The testmerge (that should be untestmerged it's fullmerged now) was actually fixing wires being borderline nonfunctional, but in the process broke accidentally broke the non-self connect logic on the actual functionality side, despite the visuals still working.
