### ISSUE TITLE
Slime extracts always get used, regardless of extra uses

### ISSUE THREAD

**Issue by gabrielckc** [tgstation/tgstation#45003]
Round ID: 112428
BYOND version: 512.1472

Admin spawned recurring rainbow slime extracts were always consumed no matter how many uses they had left when I injected them with 5u of plasma. Admin spawned them many times and this issue occurred every single time. It had the desired effect but the extract disappeared. I tried extending the uses of a normal rainbow extract created by one of the previous reactions, but it was also consumed, regardless of the extra use.

**Comment by fludd12** [comment]
I found the cause - this is specifically for rainbow slime extracts injected with plasma, it seems. The responsible code is found [here.](https://github.com/tgstation/tgstation/blob/4244df912f2d9dd911b8edc19e3f9dffd7d3e2ee/code/modules/reagents/chemistry/recipes/slime_extracts.dm#L653)

Simply removing this line (L653) should fix the issue. I'm at work, otherwise I'd do it myself.

**Comment by fludd12** [comment]
It's worth noting that you may also want to make it spawn the clusterbuster at get_turf(holder.my_atom), as otherwise it may spawn the explosive _inside you_ when you are holding it.
