### ISSUE TITLE
Silicons can't use security record consoles

### ISSUE THREAD

**Issue by nfreader** [tgstation/tgstation#45004]
## Testmerges:
#43148 
#44945 

## Reproduction:
1. Be an AI
2. Log into a security records console
3. Try to add a crime (citation/minor/major)
4. Get the "_You are too far away_" message

Unsure what exactly is causing this. I made some changes to the security record consoles in #44853 but I shouldn't have touched anything related to silicon use.

**Comment by nfreader** [comment]
I have another pass on citations coming up so I can just roll the bugfix into that PR

**Comment by YPOQ** [comment]
https://github.com/tgstation/tgstation/blob/5e4dafb30e653ea3491f06be0a12037390eab9a4/code/game/machinery/computer/security.dm#L918
I think this need to be
`if(user.canUseTopic(src, !issilicon()))`

**Comment by ATH1909** [comment]
I believe that borgs can still use these consoles, though. Maybe they need to be close?

What happens if the AI's core is adjacent to the security record console that it's trying to use?

It should be noted that AIs can still set people to arrest with security record consoles... they just can't add crimes to their record.

**Comment by zkxs** [comment]
I can confirm that borgs and shells can still use the consoles, but only if they are close to it.

**Comment by kriskog** [comment]
I made changes to this in #44020. I was sure AI using it was one of my test cases, but I guess not. ¯\\\_(ツ)_/¯
