### ISSUE TITLE
new disease cure is bugged: in vv it had 1 cure and another when examined on pandemic

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#45014]
112473

in game it said aranesp, an admin vv'd it and it was haloperinol fix this shit or revert cause its gonna break every viro round

**Comment by ATH1909** [comment]
A friend of mine also reported this happening to their virus to me over Discord.

**Comment by kriskog** [comment]
I'll look into it

**Comment by kriskog** [comment]
Something is causing the viruses to lose their cure and reroll after a while. This can't be explicitly caused by the addition of more cures, but is noticeable now that there can be different ones on the same resistance. 

Still trying to find the cause, but depending on the patient the cure might be different for the same disease so I guess make combo pills until it is fixed.
