### ISSUE TITLE
Golem Shell transfer doesn't transfer traitor status and quirks

### ISSUE THREAD

**Issue by Cyprex** [tgstation/tgstation#45229]
Issue reported from  Round ID: 113318
Jeff Reiter turned themselves into an adamantine golem (via the adamantine major luminiscient reaction). Then he made another golem shell and transffered himself into it. This didn't transfer his antag status and quirks.
Notes(IC->Notes) were lost too.
I gave him traitor again, the end-of-round report lists him twice, once the original traitor objectives and the second one the new objectives he got when I gave him traitor again.

**Comment by Akrilla** [comment]
Is becoming a traitor when moving to a new body intentional?

**Comment by Cyprex** [comment]
How does this work for slimepeople clones? They should hopefully share traitor status

**Comment by ExcessiveUseOfCobblestone** [comment]
It's all mind bound. If you're not having the mind transfer, traitor status won't transfer. Golems SHOULD transfer mind because that also carries the `enslaved_to` var for bound golems

As for slimepeople clones (IIRC), they are not traitors or any antag up until your mind is in the body. When your mind gets transfered out again the body "loses" (it never had) antag.
