### ISSUE TITLE
No sitties for One Mind

### ISSUE THREAD

**Issue by Malkraz** [tgstation/tgstation#45465]
Issue reported from  Round ID: 114085 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1471

Players within the One Mind cannot buckle themselves to chairs.

**Comment by Coconutwarrior97** [comment]
Just tested this, I think it may have more to do with it being much more difficult to buckle yourself due to the sprite effect of one mind, where it makes your sprite a big bigger. If you stand facing forward/backward it is almost impossible to buckle yourself due to the sprite size increase caused by the glow. When you face either right or left it is a little bit easier but still quite difficult to buckle yourself but definitely possible since the glow is not quite as pronounced.
![Forward](https://user-images.githubusercontent.com/40315842/61865530-fdede880-ae98-11e9-99cd-d1c3d0becace.png)
![Sidewars](https://user-images.githubusercontent.com/40315842/61865531-ff1f1580-ae98-11e9-9221-a64e1f5e7c8c.png)
