### ISSUE TITLE
recylcer buthcering gliched

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#45546]
![23](https://user-images.githubusercontent.com/33834933/62004918-d6627e80-b12b-11e9-88a1-d1fd2ddc7f13.jpg)

114403

the recycler will pause after gibbing a monkey (not supposed to )
not all the organs will be created
bad text

**Comment by optimumtact** [comment]
learn to type

**Comment by nemvar** [comment]
Actually legit issue created by #45299 
The organ part isn't an issue though, that's literally intended functionality.

**Comment by nemvar** [comment]
Actually, there's only one part of this that's legit, and that is the grammar part, ironically enough. The gibber is supposed to stop if a brain enters it and *surprise surprise* a brain enters it when you gib monky :monkey: 

This only didn't happen, or rather, didn't happen as often, before because recyclers were using snowflake code for their collision.

**Comment by PKPenguin321** [comment]
Pedantic but that message is a bug, so the bug tag is still appropriate
