### ISSUE TITLE
Spontaneous death from cloning pod emag

### ISSUE THREAD

**Issue by TetraK1** [tgstation/tgstation#45591]
## Testmerges:
#45457: 'Tend Wounds Now Is -2 Steps and Borg-Friendly!' by ExcessiveUseOfCobblestone at commit b253806759
#44639: '[Ready] Ports dynamic gamemode from /vg/' by TheChosenEvilOne at commit 9c3be66b44
#45485: '[Test Mergeable] Infection Gamemode' by Whoneedspacee at commit 79cf8b8f47

## Reproduction:
Died several times during the round and was cloned two or three times.  While walking the halls, my screen jumped from where I was to the cloning pod, and I got the emagged cloning pod death message.  I was playing Tet O'Weenie, but my memories were displayed upon jumping as if I had been moved to another body, and the memories were "Aldenein Phoenix's Memories:" ie not mine.  

The body I was walking the halls in was left in the halls, and was catatonic after the jump.  Several minutes later, I popped out the cloning pod as a fresh clone.  I wasn't watching the pod after the emag so I don't know if I came out of the same emagged pod or if the pod was fixed in the meantime.

Dying from someone emagging the cloning pod while across the station is pretty wack.

**Comment by YPOQ** [comment]
https://github.com/tgstation/tgstation/blob/049b3c1adcfd63f7b7272b7aa5acd7581a38e6d2/code/game/machinery/cloning.dm#L445-L446

I believe this issue is caused by the `clonemind` var not being nulled when a clone is completed (or when an empty clone is started) so you can clone someone -> start empty clone -> emag to move the cloned persons mind into the empty clone
