### ISSUE TITLE
Round end escapees count ghosts

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#45850]
Issue reported from  Round ID: 115642 (/tg/Station Bagil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 512.1471

This was during a wizard round where ghosts were visible. I'm not sure if it happens normally. A slaughter demon killed the majority of the crew (according to the round end report 11 of 58 survived) but the evacuation rate was listed as 46 people, 33 on the shuttle. When I asked in OOC after the round multiple players suggested it was counting ghosts as well.

**Comment by ATH1909** [comment]
It happens normally as well.

This has been a thing for a long, long time now, but I don't think that many people have reported it because we all believed that someone else MUST have reported it by now.

**Comment by willox** [comment]
Escapees is counting dead people who made it to centcomm or the syndie base and NPCs (bots, chickens, spiders.) 🤔

In your specific round there were 3 people on the shuttle alive, but 22 total counted (due to it counting corpses that made it to centcomm), a dead borg that was on the shuttle, the laughter demon, and 22 NPCs. That's a total of 46.

**Comment by willox** [comment]
fixed by https://github.com/tgstation/tgstation/pull/48188 at the same time as https://github.com/tgstation/tgstation/issues/48186
