### ISSUE TITLE
ethereals are apparently tesla proof

### ISSUE THREAD

**Issue by carlarctg** [tgstation/tgstation#45908]
## Reproduction: be ethereal 2. spawn tesla ball 3. be unharmed???

not 100% sure on this but wow that is way too overpowered if true, last round was a single ethereal with space adaptation surviving a tesla directly on top of the shuttle

**Comment by ATH1909** [comment]
"wow that is way too overpowered if true"

Excuse me, what? Oh no, they can survive being exposed to one specific consequence of engine failure, oh, the humanity!

**Comment by carlarctg** [comment]
oh yeah the only way to make a tesla is via the supermatter i forgot

oh wait

**Comment by nemvar** [comment]
Ethereals have a lot better protection against the tesla because their siemens coeff doesn't get effected by the snowflaking of the tesla. This means that they have insuls, they need to take four times the damage that a normal person would need for it to effect them.

This could also happen because of certain other factors, such as shockproof mutation, which makes you completely immune to tesla bolts too.

**Comment by nemvar** [comment]
I just did the math on tesla damage and if it weren't capped, a normal tesla ball would deal 2897.1 damage if it hit you directly. This certainly isn't caused by the ethereal extra siemens mod, my money is on the shockproof mutation though

**Comment by nemvar** [comment]
Alright, this happens with all mobs, or at least the ones I've tested, I think it is runtime related.

**Comment by PKPenguin321** [comment]
Reproduction steps por favor

**Comment by nemvar** [comment]
Reproduction:
Spawn any carbon
Spawn tesla
Watch the mob randomly not taking damage from the bolts, yet still conducting them and also getting a shitload of runtimes.
