### ISSUE TITLE
Chief Engineer is now a fucking Yes/No option on Terry

### ISSUE THREAD

**Issue by severepwnage** [tgstation/tgstation#45999]
RoundID: 116285

lol
very cursed image ahead

https://i.imgur.com/HLV8yqn.png

How to recreate: no idea maybe join terry?

**Comment by Tlaltecuhtli** [comment]
did u ask admins if they did this

**Comment by redmoogle** [comment]
not an issue it's caused by an event 'Bureaucratic Error'

**Comment by carlarctg** [comment]
sounds like its still an issue that it appears in job preferences

**Comment by redmoogle** [comment]
Last i check it's intentional design that it does that

**Comment by kriskog** [comment]
Confirming this happens to a random role when the bureaucratic error event runs. There's no reason it should change the buttons in the preferences window though, since thats not what pops up when you join the round late. If you set the preference to yes, it just reverts to a low setting for the job in the next round. 

It might have been intentional, but there is no reason it should do this on current tg at least. Calling this a bug.
