### ISSUE TITLE
Dynamic Revs means a head can alter their job and then go to lavaland, and it counts as surviving

### ISSUE THREAD

**Issue by MacBlaze1** [tgstation/tgstation#46088]
## Reproduction:

Step 1: Be head on dynamic revs
Step 2: Change Job to Something Idk, Captain
Step 3: Go to lavaland and fight mobs or some shit, far out and away from the reaches of evil communists
Step 4: Revs "win" due to killing all the heads left on the station. 
Step 5: Shuttle is called, lands, and revs go to centcomm. 
Step 6: Round ends, says the head Who WENT to LAVALAND, survives.
 Tl;dr infinite stalemate between revs and heads causing no one to win, and the game only ending when the shuttle reaches centcomm, or when the revs flee the station by going to centcomm. 
Edit: This is incredibly exploitable, as altering job titles or roles makes it so the previous state of your role stays in its previous state or some shit.

**Comment by Cyprex** [comment]
Sounds like it's not using the role of the mind?

**Comment by adamkad1** [comment]
it does, but i wish it didnt

**Comment by kriskog** [comment]
There is nothing in the code to support this, and I am also unable to reproduce. The ID is never checked for their active job, nor does it take any changes to whatever designated you as head in the first place into account. Mind you there might still be a bug here, but there has been a fair bit of changes and fixes to the mode and ruleset since.

If this comes up again, make a new issue
