### ISSUE TITLE
The sleepers on the nuke op shuttle are a bit weird

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#46126]
https://cdn.discordapp.com/attachments/326826573951008769/615021648516743191/screenshot.PNG

While the sleepers on the nuke op shuttle display a full assortment of chems, they will only actually inject the basic ones (you can click on the buttons for the other chems, but they won't actually inject any chems).

Those sleepers might have been admin-edited or something (we were having... "issues" with the tox damage from some BVAK injectors), though, since I could have sworn that they were only displaying the buttons for the basic chems earlier in the round.

If you'd like to see the full text transcript of the conflict (which ended with me being banned for 30 minutes for OOC in IC for saying the word "screenshot" (said ban caused me to miss the first seven minutes or so of the /tg/ summer ball, since that round was the round that took place immediately before the ball round did)) that you can see a portion of in the bottom right corner, say so, and I'll probably make a Reddit post or something that'll contain it.

**Comment by Names-Are-Hard** [comment]
I tweaked their component ratings to 50, I don't think that should make them stop working, but it might be my fault.

**Comment by kriskog** [comment]
If you made the components rating that high, it will no doubt have caused a runtime due to list index being out of bounds, and subsequent runtimes when attempting to use it. For future reference, t4 parts has a rating of 4 and you should try not to go past that for most stuff as not everything has sanity checks - although especially sleepers.

ATH, please do not attempt to bring administrative drama to github. We aren't interested, and we do not want it. Also, for this kinda thing the round ID is pretty important so dont leave that out.

**Comment by PKPenguin321** [comment]
Closed accidentally?

**Comment by Names-Are-Hard** [comment]
I just confirmed that sleepers do in fact work properly when their component ratings aren't set stupidly high.

**Comment by kriskog** [comment]
Sorry yes, I did confirm that too. Not a bug, just over the top varediting.
