### ISSUE TITLE
ID Console can create "ghost" ID card

### ISSUE THREAD

**Issue by hazamaitsuru** [tgstation/tgstation#46156]
Stick your ID card in your PDA. Open up an ID console and click the button to insert your ID. Click the button to remove your ID. You now hold a "ghost" copy of your ID that will perform its functions, but cannot be inserted into your PDA (as it believes the card is still inserted). The ghost card will warp from wherever it is to your hand when you use "Eject ID" on the PDA it came from.

Deleting the ghost card will mostly remove the ID from play, but the card still in the PDA can be ejected and used, though it will be invisible. If this invisible card is placed into your pocket, that pocket will be rendered useless and nothing else can be placed there. Placing the ID in any other container (including PDA) or dropping it appears to completely remove it from play.

**Comment by sandshark808** [comment]
It appears that someone may have attempted to fix this bug, but the result is a slightly altered version of the same bug. 

Now, instead of producing a "ghost" ID card, the original ID card exists in some kind of quantum stasis between the PDA and the console. You may use the PDA as your ID AND use the ID elsewhere at the same time. If you use the PDA (by logging into a new console or extracting the ID by hand) it immediately teleports back to you, no matter who else has it.

One consequence of this is that you can insert one ID into **as many PDAs as you want**, retaining the privileges of that ID (and the ability to instantly recall it at any time) across all PDAs.

This is easily abusable if you're an antagonist or greytider, because it means you can stash a blank PDA with, for example, the Captain's Spare ID inside of it. In the event that you're arrested, and the ID is confiscated, you can simply go back to the toilet or locker you stashed it in and recall the ID to your hand.
