### ISSUE TITLE
Riot darts don't deal stamina damage anymore

### ISSUE THREAD

**Issue by py01** [tgstation/tgstation#46198]
Privateclient test, donksoft riot lmg/smg don't deal stamina damage

**Comment by kriskog** [comment]
Likely caused by your changes in #45484. Radiation projectiles also stopped applying correctly around  the same time: #45576

**Comment by Fhaxaris** [comment]
Ok, so I did some testing and it seems that if you have a projectile with `nodamage = TRUE`, it will not apply_effects() on the mob. this happens because there is an if statement that checks if `nodamage` is true and if it is it won't apply the effects.

some projectiles with `nodamage = true`, don't use `apply_effects()` and use `on_hit()` to do stuff (ion for example) so they still work.
I will make a PR.
