### ISSUE TITLE
Ranged Holoparasites Can Become Nearly Invincible With Wumborian Glands

### ISSUE THREAD

**Issue by VashStampede-BugGuy** [tgstation/tgstation#46324]
TG Bagil Id: 117746

To Reproduce: Get a wumborian fungus from a gold core in xenobiology and kill it.
Apply gland dropped from wumborian to ranged stand in scout mode.
Ranged stand in scout mode can now attack.
R.I.P Station

**Comment by VashStampede-BugGuy** [comment]
First post, have mercy

**Comment by ATH1909** [comment]
I could have sworn that I had reported this myself a month or two ago; I know some admins helped me test it.

This also lets protector stands in defense mode deal a decent amount of damage per hit (10 damage per hit instead of, like, 2 damage per hit (or maybe it was 4 damage per hit?)). Note that if a stand leaves the mode that you applied to gland to, they'll lose the attack buffs from the gland (even if they return to the form that the gland was applied to).

**Comment by PKPenguin321** [comment]
Correct fix would be to make the Scout mode of the ranged stand properly override its attack code so that it cannot run, rather than just setting its damage to 0.

**Comment by Shadowflame909** [comment]
Bro time to buff my ora ora stand

And they said departmental cooperation wasn't based

**Comment by OverlyGeneric** [comment]
not even sure how an almost intangible being would be able to eat the gland without a mouth.

still isn't much of a problem when you would often kill the stand user over the stand.

**Comment by 81Denton** [comment]
Just append "Requiem" to the holoparasite's name after you feed it a gland tbh

**Comment by Rodey125** [comment]
just fixed this in my first PR
