### ISSUE TITLE
Lost own rev hud icon on cloning

### ISSUE THREAD

**Issue by py01** [tgstation/tgstation#46427]
Round ID: 118248

Was rev, got killed and cloned, was still rev but myself and other revs could not see a red R above me.

**Comment by Dawson1917** [comment]
I've also seen at least 1 blood brother and 1 traitor lose their antagHUD icon after cloning. Not even admins can see it. This happened at least two or three weeks ago

**Comment by Cyprex** [comment]
This happened mostly in dynamic, perhaps this is a requirement to reproduce this bug. This usually leads to the cloned person getting killed in revs. I feel like this should receive a priority:high label as a result.

**Comment by ATH1909** [comment]
Imagine if this bug happened to a headrev and they got lynched by their own team, ending the round.

**Comment by py01** [comment]
getting hit by staff of change as a wizard apprentice also appeared to do this

**Comment by willox** [comment]
I believed this is caused by https://github.com/tgstation/tgstation/pull/45295 which adds some state for the icons into `/datum/mind` which is unused by revs/cult but takes precedence anyway.

You can reproduce locally by making yourself a rev head (enable it in the prefs by changing the player count requirements) and doing a rudimentary transformation to human. The icon will disappear. If you test again after reverting the mention PR, the icon will not disappear.
