### ISSUE TITLE
equip sounds play when latejoining

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#46478]
Issue reported from  Round ID: 118453 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1471

just a bit odd if you don't know the source and obviously you're supposed to already be wearing it
#46387
@actioninja

**Comment by 81Denton** [comment]
@actioninja This issue is still happening, I sadly can't give you the round ID since Terry shows it as 0.

**Comment by Fhaxaris** [comment]
do you mean when you are at the main menu? or when you click the join button?

**Comment by cacogen** [comment]
I've gotten used to the zip when you spawn and actually like it now. It seems intentional. Makes me wish each job had its own spawning sound.

I don't know if it's still happening, but maybe a week ago during a round I was on I was still in the lobby and could hear zip after zip, presumably as other people were spawning. I didn't think the title screen was that close to the arrivals shuttle transit space, but maybe it is. I haven't noticed it since, but I probably haven't spent that long on the title screen since.

**Comment by AnonymousNow** [comment]
Adding my anecdote. Encountered this myself. Happens when I late-observe, interestingly - sounds like a zip.

**Comment by TheBonded** [comment]
This is because the lobby area is where player mobs spawn first before they are teleported to the arrivals shuttle/wherever they spawn. sometimes, you'll hear the clothing equip noise whenever someone late joins from the lobby. I wouldn't say this is a bug at all, and merely a side effect of spawning the crew under the starting area before teleporting them to wherever they need to be.
