### ISSUE TITLE
Unable to interact with floors under airlocks

### ISSUE THREAD

**Issue by NoxVS** [tgstation/tgstation#47139]
You can't interact with the floor under airlocks. One example is floor tiles, you can't remove them or add a floor tile if there isn't one, nothing happens when you click.

Issue reported from  Round ID: 121575 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1488

**Comment by Qustinnus** [comment]
This has to do with the changes done to obscuring

**Comment by AnturK** [comment]
The flag changes were only done on base door type, and open functions do not call parent on subtypes.

**Comment by jdawg1290** [comment]
Feel free to revert 47015 for now since it needs more work, i’m stuck at work for 7 hours. Door’s initialize also needs to check the initial density so the flag is initialized Correctly for firelocks. Firelocks actually do use door’s open so they work right with these changes (after adding the flag initial check). I will look into refactoring the open calls when I get home.
