### ISSUE TITLE
R&D Servers

### ISSUE THREAD

**Issue by NinjaNos** [tgstation/tgstation#47191]
R&D Servers do not seem to work as intended or implied. It seems like the more R&D Servers = More points generated. However not only does that not work but if you use a screwdriver on an R&D Server it disappears. Upgrading its parts or cooling it down further doesn't not seem to do anything either. 

## Round ID:
Happens on all rounds

## Reproduction: 
- Using a screwdriver on an R&D Server turns it invisible. If tile is alt-clicked it still shows the name without icon. Can be screwdriver'd back to turn visible or Crowbar'd to show the machine frame.

- Destroying all R&D Consoles results in 0 points regenerated. 1 Console generates around 3258/min. Having any more than 1 console does not increase the amount of points generated although the description of the R&D Server implies that they add more research points.

**Comment by nemvar** [comment]
Research servers not adding up their research is intended behaviour.

**Comment by zxaber** [comment]
Multiple R&D servers existing seems to be mostly for redundancy; as long as at least one exists, you'll get point generation, but you don't get to multiply it with extra servers.

The code for temperature affecting point generation is nonfunctional. Most of the procs don't even get called anymore (and one of them would runtime until I fixed it so that I could have the temp show on the server management console). One of my many things I want to eventually change is re-adding point gen being affected by temperature.
