### ISSUE TITLE
Energy bows and proto-kinetic accelerators recharge instantly

### ISSUE THREAD

**Issue by NoxVS** [tgstation/tgstation#47264]
Normally they shoot, recharge, and can be fired again when recharged. Now that they recharge near instantly they become semi automatic with no ammo to worry about. Dear god

Issue reported from  Round ID: 121879 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1488

**Comment by CRITAWAKETS** [comment]
THIS IS WHY YOU TEST YOUR PRS AND THIS IS WHY THEY ARE TESTMERGED

**Comment by CRITAWAKETS** [comment]
Going to lavaland and back to the station fixes it. Somehow.

**Comment by kriskog** [comment]
@Qustinnus Probably skills huh

**Comment by necromanceranne** [comment]
How many times do we have to keep teaching this lesson old man?

**Comment by necromanceranne** [comment]
As a serious observation, this is entirely negated by gaining any proficiency in mining, so I guess that's the culprit.

**Comment by Qustinnus** [comment]
@critawakets it was test merged and it was tested. Why do you insist on being such an insufferable douche on github?

**Comment by Kraseo** [comment]
iT wAs TeSt MeRgEd AnD iT wAs TeStEd. WhY dO yOu InSiSt On BeInG sUcH aN iNsUfFeRaBlE dOuChE oN gItHuB?

maybe if you actually tested more than 5 seconds you'd find basic shit like completely breaking cargo and not letting them be able to order anything without express

or, you know, the major fuckup of parts irradiating everyone because they wanted the endgame gear

but no, the person who reports the bugs you make is the "insufferable douche"
![imagen](https://user-images.githubusercontent.com/3855300/67186353-3ba2d480-f3e8-11e9-8c93-2329346064fe.png)

lol

**Comment by actioninja** [comment]
> maybe if you actually tested more than 5 seconds you'd find basic shit like completely breaking cargo and not letting them be able to order anything without express

Not related to this PR at all.

> or, you know, the major fuckup of parts irradiating everyone because they wanted the endgame gear

This PR went through multiple testmerges and testing cycles.

You're on thin ice.

**Comment by nemvar** [comment]
Fixed in https://github.com/tgstation/tgstation/pull/47222

**Comment by nemvar** [comment]
Wait... no actually not.

**Comment by wesoda25** [comment]
@necromanceranne dude its "how many times do we have to teach you this lesson old man" smh if you're gonna quote the bible get it right

**Comment by necromanceranne** [comment]
I-I'm swowwy pwease forgive me QwQ

**Comment by TheVekter** [comment]
Should be fixed in #47299.

**Comment by TheVekter** [comment]
I imagine #47299 should fix this.
