### ISSUE TITLE
tgui++ uis tend to disappear and being unable to reopen more commonly than old tgui

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#47755]
123582

i had to relog 3 times because chem machines uis kept disappearing after i moved away and unable to reopen
the old tgui tricks like opening a new window to make the old one appears doesnt work you can only relog to fix it

**Comment by carlarctg** [comment]
or you can decon-recon the dispenser

**Comment by PKPenguin321** [comment]
From what I can tell this is because the window is still "open" but not visible, so you can't open it as it's already open. Reconnecting closes all windows so you can open it again. You can also fix it by moving away from the machine (assuming the window auto closes when you move away from it normally).

I think a verb similar to the cancel-camera-view like `close-all-tguis` would be useful as a temporary fix, since we've had this issue for a while and a real fix feels far off

**Comment by 81Denton** [comment]
@actioninja @stylemistake

**Comment by Cyprex** [comment]
I can also confirm this happening a lot to me sporadically on old tgui.

**Comment by actioninja** [comment]
Referenced issue is likely the same issue.

**Comment by stylemistake** [comment]
I am fairly certain this is no longer an issue. Closing.
