### ISSUE TITLE
I was somehow able to see an APC and a torn poster through a wall as a cyborg, but only from certain tiles/angles

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#47841]
Look in the top left corner:
![image](https://user-images.githubusercontent.com/222630/69021011-457a1200-096b-11ea-8913-04931ce75f41.png)

**Comment by davethwave** [comment]
Well I guess this is just because of where they actually are, the sprite and hitbox shows it to be on the wall but they are actually on the tile right above it instead.

**Comment by kriskog** [comment]
Yeah, what dave said. They are offset from the turf above the wall.

**Comment by ATH1909** [comment]
Wait, why was I even able to see that vent up there in the top left corner? Shouldn't my line of sight to it have been blocked by those walls?

**Comment by davethwave** [comment]
I have no answer for that. You indeed probably shouldn't be able to see there at all.

**Comment by timothymtorres** [comment]
#36527
#55793
#47841

Are all duplicates and this behaviour is intended.  This is a mapping effect that happens when you place a wall-mounted object on a tile and then offset by pixel x/y.  So if you can send the tile it was placed on, you can also see the object that was offset regardless of if it is on another tile or not.
