### ISSUE TITLE
Wizard can mindswap into sentient statues

### ISSUE THREAD

**Issue by ghost** [tgstation/tgstation#47850]
Mindswap into an animated statue to become invincible, then run around shooting fireballs while being immune to all forms of damage

may or may not be bad enough to be considered a serious exploit, but probably wasn't intendeed

**Comment by IllotAFV** [comment]
Animated statues still take damage, it’s just severely reduced, but it can be destroyed. If I remember right, statues can be obtained only from flesh to stone spell. And these statues are temporary. This effect doesn’t last long enough to be that viable. Moreover, to pull this strategy right you need staff of animation with recall spell, so your every new body can create new statues. Or wand belt with recharge spell. On top of that flesh to stone requires full wizard outfit. 
There was a statue in a slime gold pool, but I am not sure about that.

**Comment by necromanceranne** [comment]
It's not severely reduced, statues have 50k health. They are PRACTICALLY invincible.

**Comment by ATH1909** [comment]
The statues created by the flesh to stone spell will eventually turn back into humanoids, even if they've been animated

**Comment by davethwave** [comment]
Well the perfect way to have this perfected is the spell that turns you to stone 2 points however it requires a robe, a bound staff of animation which is 3 points, fireball which is another 2 points, and mindswap which is 2 points. This rounds up to 9 points. If the instant summons book can be used twice you could use it on a backpack and put your robes into hiding once you find your victim. Just hide it and hope it doesn't get found, mindwap into statue, kill to your desire. Rinse and repeat is possible as long as your stuff doesn't get found.

**Comment by necromanceranne** [comment]
The fact that you need your robes for this to work at all means that once the statue reverts you're basically at the mercy of anyone who doesn't already know you're a wizard, and more importantly, you would need to give up recall in order to have a usable robeless spell (fireball).

To be honest, this is working as intended and isn't an exploit. The only part of this that is bad is that the statue is 50k health, which is ridiculous for obvious reasons. You can, if you work quickly enough, seal it in a wall cage since it doesn't destroy walls, and then wait out the timer. it won't have radial blind/actual blind (since that's 1 point and fitsi n davethwaves budget) up all the time after all. And if it didn't have fireball, it won't be able to fight back with eyes on it. It's when it has fireball that proves to be the issue. At which point, you'll likely just have to wait. If you found the staff, he isn't doing this again.

That or somehow manage to put 50k damage into the statue. Maybe get a combat shotgun and start shooting? Even one riot shotgun full of buckshot at pointblank is 640 each. just do that a hundred more times! (that's a joke by the way)

**Comment by kriskog** [comment]
Eh, inclined to call it emergent gameplay. Should probably not stay in forever though.

**Comment by trollbreeder** [comment]
Give this the FUCK tag.

**Comment by dragomagol** [comment]
Nerfed (see#51480 and #52682)
