### ISSUE TITLE
Hardsuits with combat mode dont update movespeed properly

### ISSUE THREAD

**Issue by kriskog** [tgstation/tgstation#47871]
## Reproduction:
Wear an elite syndicate hardsuit or select equipment as debug outfit, you are slowed down.
Changing helmet mode does nothing to movespeed.
Remove helmet, get full movespeed.
Put helmet back on, keep full movespeed in both modes.

**Comment by ATH1909** [comment]
How does this affect your protection from vacuums/space?

**Comment by necromanceranne** [comment]
I'd be careful about labeling this an exploit since you will be swapping modes constantly as part of the functionality of the item, and I doubt any admin would enforce it as such as an exploit that is banworthy since it's literally impossible not to replicate, if the replication is as you say.

I know that all syndicate hardsuits will spawn in EVA mode with helmet down, so I actually do this kind of thing as a matter of course whenever I get the suit and usually take it off and on fairly often to keep up disguises. I've not noticed any problem updating movement speed between combat and EVA mode however, so that's fairly new. I feel like it might have something to do with some of the movement changes lately.
