### ISSUE TITLE
Random mindswap makes catatonics.

### ISSUE THREAD

**Issue by zeroisthebiggay** [tgstation/tgstation#47885]
Issue reported from  Round ID: 124012 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1488

A summon events wizard rolled random mind swap and caused most of the station to go braindead. Like pretty much every single person there.

**Comment by nemvar** [comment]
Did anyone get ghosted? Creating catatonics doesn't mean much code wise, could just be that people are switching with monkey man or something.

**Comment by BOBAMAx** [comment]
seems to be an issue with mindswap in general and not just mass mindswap, you get ghosted out of your body most of the time. To reproduce: get mindswapped.

**Comment by trollbreeder** [comment]
Had this happen to me, got mindswapped with the wizard then ghosted out because i was furiously dodging and then i "had no body".
Probably related to #47826 
To be honest, mindswap needs a rework because it's an infinite use get out of jail free card and allows stealth wizards to be stupidly easy as you can just swap if your disguise falls apart, as long as you get in butt sniffing distance of some loser.

**Comment by trollbreeder** [comment]
Update: Turns out the event version of Mindswap is broken too! Isn't that fun?
It causes you to swap minds with **ghosts.** Had this happen to me too and deadchat was more salty than a shaker of sodium chloride.
