### ISSUE TITLE
Kilo Emitters Don't Fire

### ISSUE THREAD

**Issue by coleminerman** [tgstation/tgstation#47886]
Round ID: 124015 (Sybil)

Merge: Kilostation

Reproduction:
Upon round start, the emitters in the SM room don't fire even when powered. I've seen this before, but this is the first round I've seen people struggle with it and be unable to figure it out. This happens every kilo round.
However, there are some quick and easy steps to fixing it. Just dismantle the emitters and put them back together, with the same boards. Weird, but it works. You can also replace them with new emitters. It is only the ones in the SM chamber at round start that are effected.

Edit: Clarified that I was on sybil at the time of the glitch.

**Comment by necromanceranne** [comment]
Kilo has some problems with the power grid. Likely, the problem was that the emitters were being powered last and weren't getting enough power directly. This is a known problem as far as I know. In the meantime, put them on a separate grid (just clip the wires except for those looped under the emitters and between the two sides of emitter fields) and fire up a pacman on the grid. It'll start firing with the influx of localized power.

**Comment by Iatots** [comment]
On meta (terry) emitters fail to power up as well sometimes, so it might not be a mapping issue, unless there is new power code and the maps aren't updated.

**Comment by necromanceranne** [comment]
New wires are trash basically is the problem. They have huge problems with power gridding. Other stations only have this problem when power is too low. So starting early is important to power the SM.

**Comment by Cyprex** [comment]
Could you properly document how new wires behave differently regarding powergrids?

**Comment by CAPTTLasky** [comment]
I'm not big on how power works but theoretically couldn't you replace the APC with one that has higher starting charge and be done with it?

**Comment by LemonInTheDark** [comment]
No, the emitters run directly off the powernet, as opposed to the chem dispenser for example. APCs have nothing to do with em.

**Comment by iprice** [comment]
We had an issue with Kilo the other day which was the engine room SMES pulling all the power leaving none available for the emitters (zero excess on the wire to the emitters), might be the same thing.

I had a thought some time ago, relating to late engine starts, power sinks, or in one case just a bored assistant conveyoring corpses into electrified grilles (basically works like a power sink)...

Give the emitters their own SMES with an initial charge, this means even if you empty the engineering SMES you can at least start the engine back up (or it will keep running, even if all the output gets sucked out of it).

On the other hand this may be considered affecting balance (i.e. powersinks intentionally stall the SM and make engineers curse whoever stole the pacman/plasma from stores) so I wasn't sure, otherwise, SMES seem a reasonable way to "isolate" loops (be a battery for) and the emitters could make sure the engine can always be started without too much panic.

(Tested - a power sink will not suck power out of a SMES if only on the input terminal side.  interestingly.)

Any thoughts on the balance implications?
