### ISSUE TITLE
Genetics chromosome addition is broken

### ISSUE THREAD

**Issue by Iatots** [tgstation/tgstation#47907]
## Round ID: 
been consistent for me for more than a week now.

## Testmerges:
just kilo by okand

## Reproduction: 
try to click chromie button to add chromie, window refreshes but nothing happens. Also synchronization chromosomes sometimes spawn on top of the console instead of inside. I am running 1488, i reinstalled once (actually updated to beta but switched back because it was unplayable) and it fixed the issue, but the fix lasted one round.
Also chromosomes can't be added to stored mutation, probable oversight, or related.

**Comment by kriskog** [comment]
Would be nice to have a round ID to check for issues in the logs, please grab one for us please.

**Comment by kriskog** [comment]
The first issue is due to not having a compatible chromosome. Not all chromosomes can be used on all mutations. This needs better feedback, as there is currently none.

The chromosomes spawning on top of console is surprisingly enough intended.
```
				if((LAZYLEN(stored_chromosomes) < max_chromosomes) && prob(60))
					CM.forceMove(src)
					stored_chromosomes += CM
					to_chat(user,"<span class='notice'>[capitalize(CM.name)] added to storage.</span>")
```

As for adding chromosomes to stored mutations, I'm gonna go with intended. They arent added to people when you activate the mutation normally, but after.
