### ISSUE TITLE
issue with ninja recalling energy katana

### ISSUE THREAD

**Issue by imsxz** [tgstation/tgstation#47980]
https://www.youtube.com/watch?v=2JfwcBsuBak&feature=youtu.be

basically 1) lights are out. 2)someone else holding energy katana. these are my 2 biggest hypotheses for why recalling katana didnt work. as you can see by me grabbing hypercharged yellow core, i have extremely rapid and self recharging, so it isnt a power issue. I use the adrenal ability, so my suit is certainly initialized and i wasnt stunned.

I've had this issue before, didn't report it the first time because I thought it was just a 1 time fucky wucky, this time confirmed it though

**Comment by HomocidlePancakes** [comment]
I think I had this issue occur to me a while ago, bat as far as I can remember, there was both light and it was on the ground. I tried recalling my katana from a close range - enough for it to get thrown towards you instead of teleporting in hand. Katana got launched towards me, but it wasn’t put in to my hand. Noticing this, I ran out of the throw range, so it teleports instead and it worked fine.

**Comment by kriskog** [comment]
Got robusted by a sybilite, blames bugs smh. :smirk: 

The issue is most likely with the paralyze status effect sticking around. The adrenals isnt clearing it properly so you arent able to use action buttons until the paralyze was supposed to end. We should probably make it do that on Paralyze(0), and the other ones too.

**Comment by Tharcoonvagh** [comment]
Alt click on the arrow, maybe that speeds it up a bit
