### ISSUE TITLE
Drinks category missing in crafting menu

### ISSUE THREAD

**Issue by gwhit94** [tgstation/tgstation#48027]
## Round ID: #124600

[Round ID]: #124600

## Reproduction:

Open crafting menu, lizard wine nowhere to be found.

**Comment by kriskog** [comment]
#47696 moved all drinks to a new category, Drinks, which is missing from the ui.
@actioninja Time for round four? I couldnt see any immediate reason it shouldn't work.

**Comment by actioninja** [comment]
god
dammit

**Comment by actioninja** [comment]
issue was file wasn't checked.
@Krysonism https://www.youtube.com/watch?v=2ZIpFytCSVc

**Comment by Krysonism** [comment]
I don't think i caused this. file seems to be checked on my drinks branch.

**Comment by actioninja** [comment]
![image](https://user-images.githubusercontent.com/5194834/69859773-a9dd8100-1249-11ea-9e80-9b28bc84a3bb.png)
put on your clown nose clown boy

**Comment by Krysonism** [comment]
![goofed](https://user-images.githubusercontent.com/49783092/69892917-f2a93e80-130a-11ea-9a9d-786944fbe13d.png)

**Comment by actioninja** [comment]
This one was puzzling me a bit so I looked more into it and turns out the blame view doesn't show removals.
Had to manually browse through history to find this one, but the real clown boy is @ArcaneMusic 
https://github.com/tgstation/tgstation/commit/a7021f483d11c7fdbdd23ca929b0f0e14bbaf590#diff-bf1891198155256f0439c1ecbd48de4c

![image](https://user-images.githubusercontent.com/5194834/69900382-6a856200-1327-11ea-8a83-35f8bba74293.png)



Also @optimumtact you didn't catch this one in review
