### ISSUE TITLE
Slimes Sometimes spawn inside walls they can't get out of.

### ISSUE THREAD

**Issue by Shirbu** [tgstation/tgstation#48215]
Issue reported from  Round ID: 125578 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 512.1488

Pyroclastic anomaly inside the AI sat spawned a slime sandwiched between the R-Walls.

Tbh, pyro anomalies shouldn't be in the AI sat in the first place.

**Comment by Tharcoonvagh** [comment]
![HeartyInsecureCuttlefish-size_restricted](https://user-images.githubusercontent.com/54288658/70639207-7122ac00-1c3a-11ea-8390-2dd8e1c275bb.gif)

**Comment by 81Denton** [comment]
Related to #33611

**Comment by Sealed101** [comment]
mostly caused by anomalies getting spawned in walls or otherwise blocked off areas. at least codewise the anomalies should no longer spawn in walls or other dense turfs, as described in #33611, so this should also not be an issue anymore. unless a mapper builds a wacky corner block with consoles or something
