### ISSUE TITLE
Who the fuck thought of these prices

### ISSUE THREAD

**Issue by Buggy123** [tgstation/tgstation#48274]
ingame:
![image](https://user-images.githubusercontent.com/16315400/70967305-edb2f180-2063-11ea-892b-b79658eb202d.png)
reality:
![image](https://user-images.githubusercontent.com/16315400/70967334-f99eb380-2063-11ea-8c5c-f85151d0c90f.png)

ingame:
![image](https://user-images.githubusercontent.com/16315400/70967428-3cf92200-2064-11ea-97f6-320b7bf40c09.png)
reality:
![image](https://user-images.githubusercontent.com/16315400/70967467-500bf200-2064-11ea-8078-c32419b4b82b.png)

ingame:
![image](https://user-images.githubusercontent.com/16315400/70967498-61ed9500-2064-11ea-8a25-3dab45a80136.png)
reality:
![image](https://user-images.githubusercontent.com/16315400/70967537-7f226380-2064-11ea-878d-aa03193fa9a4.png)

**THREE HUNDRED AND FIFTY DOLLARS
FOR A PEN**

**IT WOULD TAKE A ASSISTANT 14 PAYDAYS TO AFFORD A PEN**

![tenor (3)](https://user-images.githubusercontent.com/16315400/70967643-cf012a80-2064-11ea-8a07-f289665d2edb.gif)

**Comment by actioninja** [comment]
Issues aren't for balance changes.

**Comment by Mickyan** [comment]
the only issue here is we're still using the dollar sign for vending machine prices

**Comment by cacogen** [comment]
I haven't played with these prices so I'm not sure if they're well thought out or not but values being 1:1 with USD values of items sold in the United States is a dumb argument. It's 500 years in the future, we're on a space station (you can imagine things like water might be far more valuable due to lack of supply) and using a different currency which, if USD still exists, will have its own conversion rate.

**Comment by Anonmare** [comment]
Inflation is a hell of a drug
