### ISSUE TITLE
Crafting is bugged

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#48469]
## Reproduction:
Try crafting a paper bag. Try crafting a burger. These and other recipes remain greyed out despite having the appropriate items.

**Comment by swindly** [comment]
I was able to craft a spear.
![Untitled](https://user-images.githubusercontent.com/22402048/71572751-9176b580-2ad8-11ea-82d4-630102f4069c.png)

But putting paper on the table prevented me from crafting both the spear and the paper sack.
![Untitled2](https://user-images.githubusercontent.com/22402048/71572776-abb09380-2ad8-11ea-8024-f6dff029d28f.png)

But putting the paper on the floor and the spear stuff on the counter let me craft the spear (but still not the paper bag).
![Untitled3](https://user-images.githubusercontent.com/22402048/71572856-fdf1b480-2ad8-11ea-94fa-8462eed3ee27.png)

Moving from the influence of the paper restored the ability to craft spears with the spear stuff on the floor.
![Untitled4](https://user-images.githubusercontent.com/22402048/71572969-7ce6ed00-2ad9-11ea-807e-a623b3013d12.png)

One last test: I was able to create a makeshift pipe cleaner layer with a stack of 15 metal sheets, but not with a stack of 14 metal sheets and a stack of 1 metal sheet.

I don't know precisely what's wrong, but it looks like it was caused by https://github.com/tgstation/tgstation/pull/48451

**Comment by AnturK** [comment]
@Cyberboss forgot to init the per type instances sublist.

**Comment by Cyberboss** [comment]
Gotta rush to get in fuckup of the year ofc
