### ISSUE TITLE
Destructive Analyzer Exploit

### ISSUE THREAD

**Issue by Fishimun** [tgstation/tgstation#48752]
Issue reported from  Round ID: 128018 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 512.1488
 If you use materials in a destructive analyzer and click materials reclaimation a lot before clicking confirm on the confirmation window, the confirmation window pops up everytime you clicked it and you can pretty much get infinite materials if you spam this.

**Comment by trollbreeder** [comment]
Sounds like the polycircuit aggregate menu all over again

**Comment by ArcaneMusic** [comment]
Nah, this is more on the tgui-side if anything. I ran into that issue a **LOT** while I was  working through the arcade app for modular computers, because the window will have a delay between certain actions being taken, and their requirements being fulfilled. (EG: Spamming attack would queue several attacks on the players side, but also several attacks for the opponent.) Similar thing here.
