### ISSUE TITLE
Having Exact Change for Mining Vendor Item Gives Error Message, Eats Points, Doesn't Vend Item

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#48771]
Manuel Round 128063

Attempted to vend a Liberator's Legacy with exactly 2000 points (its price) on my card. Machine spat out following error message, removed all points from my card and did not vend item:
**_"Error: Transaction failure, please try again later!"_** 

Thanks to admin Wubli for helping me to recreate this bug for testing. We discovered:
- The error message is the same every time.
- It happens regardless of what type of mining ID you use (station or golem)
- It happens regardless of what type of vendor you use (station or golem)
- It happens regardless of the price of the item, so long as your current point value exactly matches its price (having even one point over it vends it as usual).

This isn't likely to come up often, but it's a right bugger when it does come up, wiping your points without vending the item. A pain for Free Golems trying to get the Legacy, and for miners trying to buy the Luxury Bar Module.

**Comment by SouDescolado** [comment]
https://github.com/tgstation/tgstation/blob/58209b970e6ca6d8ebd26f24e97d6b22bf63dc6d/code/modules/mining/machine_vending.dm#L109


Problem is here. It uses the check to see if the mining points minus the prize cost is true. However, to return true, it has to return 1 or more. Since it returns 0, it triggers false, consuming the points and not giving the item.
