### ISSUE TITLE
Kilo consistently crashes server

### ISSUE THREAD

**Issue by peoplearestrange** [tgstation/tgstation#48830]
## Round ID:
Any kilo round (I will add some examples later)
128039 Manuel
128052 Manuel
128284 Manuel
127793 Manuel (2020/01/09)

## Reproduction:
After Kilo has been running for roughly 1hr 04minutes the server self reboots.
Near the point there is considerable lag.
I've only seen/tested this happening on Manuel, un-known if it happens on other servers
I'll try to run a round and take regular MC readings to check if there is anything obvious.

Obviously its a long time to wait to test, but its been consistently happening and I have yet to see a game on kilo end properly.

EDIT: from looking at a couple of logs it produces the following error:
[2020-01-13 05:03:29.058] GAME: BYOND out of memory. Restarting

**Comment by Jordie0608** [comment]
Several rounds are recorded to have ended fine on Kilo after reaching at least around an hour.
https://sb.atlantaned.space/rounds/128283
https://sb.atlantaned.space/rounds/128268
https://sb.atlantaned.space/rounds/128263
https://sb.atlantaned.space/rounds/128151

**Comment by peoplearestrange** [comment]
Hmm Interesting, Its been fairly consistent with what I've seen on Manuel. I'll look into it further

**Comment by peoplearestrange** [comment]
So the issue is that it seems crashed Kilo maps do not show on map bus at all.
128039 Is an example where Kilo crashed the server and its no where on statubus that I can see.

It also seems to be Byond running out of memory in that one. I'll look more

**Comment by peoplearestrange** [comment]
It does seems to not crash sometimes, so I was wrong about it never being successful. But for example, on the 13th when there was 1 successful round, there were 2 crashed rounds in the same day. On the 12th there was 1 crashed and 1 successful

**Comment by Dorsisdwarf** [comment]
I think its a server thing in general, it was pretty consistently crashing at 1:30-1:50 a few days ago

All the incidences I checked were byond out-of-memory, restarting errors too

**Comment by Taylorkills2** [comment]
From what I experienced, this has been a problem with Kilo since it was testmerged. It doesn't always crash, but it crashes frequently often compared to other maps, sometimes before 1 hours, times around 1.5 hours. Though 1 hour really seems to be the sweet spot for crashing.
Many players hate Kilo due to the fact it crashes very frequently and it's pretty commonly known(or at least "rumored" among high pop players)
I don't know what causes it, maybe a memory issue due to a combination of a high population of players and high amounts of turfed terain outside the station on the same z level?
Map looks like it works fine on dead/super low pop. I've seen multi hour Kilo rounds when Manuel was still Sybil 2.

**Comment by Jalleo** [comment]
It happened on events hall eu too. There is a missing round from yesterday close to midnight after the cult round on Delta.
https://sb.atlantaned.space/rounds/128253
Round after crash was Delta again.
https://sb.atlantaned.space/rounds/128276

**Comment by trollbreeder** [comment]
Higgs-bugson

**Comment by ArcaneMusic** [comment]
We removed kilo months ago, this can probably be closed.

**Comment by EOBGames** [comment]
seemingly resolved in #54245
