### ISSUE TITLE
Being immune to the cold because of a robotic augment still makes you complain about the cold moodwise

### ISSUE THREAD

**Issue by tralezab** [tgstation/tgstation#48846]
## Testmerges:

#48583: 'Don't recheck connected clients in isbanned() (and other isbanned() dos mitigations)' by MrStonedOne at commit 23fba6671c

## Reproduction:

get fully augmented, stand in space. be able to stand around just fine yet get really depressed about how cold space is

**Comment by XDTM** [comment]
I've been looking all over the code to check where do augmented limbs actually prevent space damage...
Unless i missed something, it really looks like it's all due to the flat damage reduction on robotic limbs, which would mean the whole mechanic was probably not even intended to begin with. 
Although that would not prevent you from cooling down and getting all the alerts anyway; do they pop up when spacewalking augmented?

If that's the case, then properly using traits instead of damage reduction should solve the issue.

**Comment by necromanceranne** [comment]
Yes you get all the bells and whistles.

Also thank you for telling me that I was wondering what happened to them on a fork.

**Comment by PKPenguin321** [comment]
>which would mean the whole mechanic was probably not even intended to begin with.

It may not mean that. It may be intended, hence why the damage res is just enough to allow for it.

**Comment by XDTM** [comment]
i did say probably

**Comment by TheBonded** [comment]
Just because the cold isn't hurting you doesn't mean it's not uncomfortable. I *think* this sort of makes sense, whether it's intentional or not.

The reason why this occurs is because all augmented limbs do is remove -4 burn and -5 brute damage from all incoming damage, which makes it immune to pressure and cold damage while still technically allowing your body to take that damage. it just reduces the damage to 0 so it's practically the same as being immune.

**Comment by Sealed101** [comment]
can't get the cold alert with full augged body anymore; most likely fixed by https://github.com/tgstation/tgstation/pull/78905 or other robot limbs fixes
