### ISSUE TITLE
Lizards are oneshot by temperature guns/watcher eye beams

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#48876]
Issue reported from  Round ID: 128456 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 512.1484

Because of the body temperature changes in this PR https://github.com/tgstation/tgstation/pull/48569, lizards are apparently incapable of stabiling their temperature quickly enough not to die to the freeze ray shooting them just once. This weapon has an obscene number of shots, so you don't even have to try to hit someone with it.

I have no idea if this intentional or not because of the broken explanation in the PR body doesn't really help elucidate whether this is working as intended but it definitely is a massive, massive issue with ashlizards and lizard players in general.

I think the core problem is that they're not stabilizing quickly enough and that the temperature gun puts you at -170 degrees celcius. Which is....really fucking low. I think temp guns and watcher beams need a serious re-evaluation and pretty soon.

**Comment by trollbreeder** [comment]
Temperature is bullshit

**Comment by HomocidlePancakes** [comment]
Good. Fuck xenos.

**Comment by PKPenguin321** [comment]
While I'm not sure if this is outright intentional, I don't think it's a bug

**Comment by ATH1909** [comment]
Do ling cryo stings also one shot them? Does being set on fire for 5-101 seconds one shot them?

Hell, does ANYTHING that brings their temperature to a damaging level one shot them?

This was EXACTLY what I was afraid of and warned you guys about when I was commenting on that PR. Great job screwing over lizard miners, guys.

**Comment by TheMidnightRose** [comment]
> Do ling cryo stings also one shot them? Does being set on fire for 5-101 seconds one shot them?
> 
> Hell, does ANYTHING that brings their temperature to a damaging level one shot them?
> 
> This was EXACTLY what I was afraid of and warned you guys about when I was commenting on that PR. Great job screwing over lizard miners (they now need to pop a survival medipen every time they fight a watcher), guys.

I mean. its called being in melee against watchers, or good at dodge. Melee Watchers dont shoot cryo beams, and if you still have the ore crate, you can swing it around quickly to block cryo shots. If they cant do either of those, then they die in mining like the rest of us.

But yeah this might be a big issue due to blobs,  meteors, nukies, all of which cause holes to space which can quickly freeze lizards.

**Comment by Taylorkills2** [comment]
Lizards might have been a specialized race at one time, but they've long since been cucked entirely. The body temperature PR is just another shit on lizards.

Midnight, I am a very good miner, even I get occasionally shot my watchers cryobeam, specifically when I'm doing other things than fighting Watchers. A Miner can go on a watcher genocide spree to stop them from ever shooting someone, but then you set the focus of the job to a very niche aspect of it. 
idrc, just makes them more of a "hardmode" race.

**Comment by HomocidlePancakes** [comment]
>The body temperature PR is just another shit on lizards.

Out of interest, what are the other “shits” on lizards?

**Comment by kriskog** [comment]
@nightred Thoughts?

**Comment by nightred** [comment]
Lizards are weak to temp guns but not one shot.
As a lizard you will not warm up fast, take your suit off, you can survive the heat of lava land.
But this is a real risk of being a lizard. Also hard suits hold your current temp as a lizard so warm up with it off.

This behavior is as expected (from my view).

**Comment by nightred** [comment]
So the behavior is not a bug. (based on the closed PR#48889)
The temp guns might need a rework so that they account for insulation from clothes or natural body insulation.
And hardsuits have no active regulation, only prevents loss of temp from the area, this does mean that if you have no natural stabilization you do not warm up in a hardsuit. (or fire suit, or bio suit)

**Comment by PKPenguin321** [comment]
There you go then

**Comment by WarlockD** [comment]
"Heat of laval land" Really?  I have yet to see lava land above 24C.  Most of the time I see it at near 0C, but that's more of a pet peeve.  I wonder if that has something to do with the damage as well.
