### ISSUE TITLE
the experimentor can "jam"

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#49219]
<img width="1066" alt="experimentor bug" src="https://user-images.githubusercontent.com/42606352/73919746-be617980-4889-11ea-85f2-6bf6f00f5195.PNG">

Steps to reproduce:
1. Test different objects with the experimentor until you find one that works with the poke reaction.
2. Test other objects of that poke object's type with the poke reaction until the poke reaction calls the obliterate reaction.
3. Cry because the experimentor that you spent 3 or so hours codediving to learn how to properly use refuses to do anything for the rest of the round (or until it is deconstructed) because it will always give you a message of "The E.X.P.E.R.I.-MENTOR has been used too recently!" whenever you try to perform a test with it.

Note that this was done on a Fulpstation round with an experimentor fully upgraded with fulpstation's special "quantum" tier 5 parts. Those special parts shouldn't be the source of the bug, however, as they don't seem to break any values/push any values past 0.

Also note that I was able to cause this bug to occur twice in one round, so I'm pretty sure the problem here has something to do with the poke experiment calling the obliterate experiment (or maybe the obliterate experiment itself?).

**Comment by kriskog** [comment]
remove it

**Comment by Tharcoonvagh** [comment]
>People say I'm not okay
'Cause I love such experimentory things

**Comment by GunHog** [comment]
My only guess is that anything that would cause the `experiment()` proc to runtime or otherwise fail to complete would break the E.X.P.E.R.I.-MENTOR, because the timer that resets the cooldown is at the *end* of the if statement chain. 

I think the lazy "fix" would be to move https://github.com/tgstation/tgstation/blob/26093e5ac226aebbb29939f864eba9b26f753437/code/modules/research/experimentor.dm#L531 to line 249 so runtimes do not "jam" the machine. Someone will still need to test the experiments locally to find out if any runtimes are happening.

**Comment by TheVekter** [comment]
That's... weird. I can't imagine what's causing it to runtime. I'll read through the obliterate experiment and see what can be done to fix it.

Also, fun fact, there isn't an 'obliterate' proc, all of the experiments and results are one very, very long if/else chain. I'm not joking, go read it.

> remove it

This is the eventual idea, it's functionality will be replaced by the research scanner.

**Comment by JohnFulpWillard** [comment]
I think this was caused by T5 since they affected the machine, so not an issue?
