### ISSUE TITLE
Plumbing reaction chamber not emptying correctly

### ISSUE THREAD

**Issue by dakiito** [tgstation/tgstation#49213]
Issue reported from  Round ID: 129697 (/tg/Station Event Hall: Sseth overflow event. [ENGLISH] [EU] [100% FREE LAG])

Reporting client version: 513.1507
![bruh](https://user-images.githubusercontent.com/49733878/73892963-816b9780-4835-11ea-9e26-889fa717e2da.PNG)
(Dont mind the tube connecting output to input, that was put in after I died by someone else)

if a reaction chamber is directly adjacent to a tank it will not empty, after spacing the two tanks between tubes, the chamber returned to not emptying.
After two admins tried helping me, I was told to submit this report

**Comment by Tlaltecuhtli** [comment]
i had a chamber next to tank recently and it was fine

**Comment by Time-Green** [comment]
There aren’t any directly reaction chambers adjacent to tanks in the picture. What was the setup you used?

**Comment by kriskog** [comment]
I looked at this, and it only started creating gunpowder once it was hooked to the rest of the network. This reaction chamber was full of 1:1:1 multiver:saltpetre:sulfur but didnt output any gunpowder to the tank hooked up just south of it. When it was hooked to the rest of the network it did for some reason start working for a bit, but stopped once the connection was broken.
![image](https://user-images.githubusercontent.com/33292112/73933946-cfd47100-48dd-11ea-9625-9e408e62e93c.png)

**Comment by IHadMyUsernameTaken** [comment]
I think the issue was that he tried to have 66.6667 units worth of each reagent in the reaction chamber (or so I recall from looking at that reaction chamber in the picture, since I'm the ghost with the green hair) when the reaction chamber can only at most hold 200 units, since 66.6667*3 = 200.0001 > 200.
Of course, I might be wrong and the issue is something else, but I did manage to have a similar problem with the reaction chamber not getting to the emptying state when I used the 66.6667 value as the volume for some three reagents.
In my case, the reagent chamber only managed to have two reagents with a volume of 66.6667 and one with just 66.6666, since the total volume then is 200, which I assume to be causing the reaction chamber to stay in the filling state, because it can't get the third reagent to the 66.6667 volume.

**Comment by kriskog** [comment]
Wouldnt it mix and move before filling though?

**Comment by IHadMyUsernameTaken** [comment]
If I understood your question correctly, then I don't think the reaction chamber will let any reagents mix or move out of its output pipe before it has the required volume of each reagent you have set for it to get, which at least is the impression I get from using the chamber.
I assume that the pipe you attached to the system let the reagents move and react, because it allows the tanks of multiver, saltpetre and sulfur to directly send reagents to the output tank instead of having the reaction chamber itself push its reagents out.

**Comment by kriskog** [comment]
Oh yeah, that makes sense
