### ISSUE TITLE
Supermatter tongs with a shard in them don't dust people when used by non-player characters even though they can still pick them up.

### ISSUE THREAD

**Issue by Bokkiewokkie** [tgstation/tgstation#49263]
I was playing around with the supermatter tools when making a sprite for them and noticed that when a monkey picks up the tongs and attacks a player with it, it doesn't dust the player or the monkey.
Tested this on a private server with no testmerges or changes.

I think it's related to this line including "user" in 'theft_tools.dm' instead of any mob but that's just my theory.
`/obj/item/hemostat/supermatter/proc/Consume(atom/movable/AM, mob/user)`

## Reproduction:

1. Spawn supermatter tongs.
2. Spawn supermatter sliver.
3. Pick up the sliver with the tongs.
4. Find/spawn a monkey.
5. Make the monkey pick up the tongs/ put the tongs in their hands.
6. Make the monkey angry so he attacks you. (usually already the case after step 5)
7. You and the monkey are still alive and it doesn't do any damage to either party except for the usual radiation from the shard if you haven't equipped a radsuit.

**Comment by ShizCalev** [comment]
The idea of a NPC monkey murderboning with a supermatter shard is scary

**Comment by Dennok** [comment]
I see now. Problem in monkey attack. It call `attackby` instead of `melee_attack_chain` that calls `afterattack` that calls `Consume` that Dust target and holder.

https://github.com/tgstation/tgstation/blob/0fb62da664da8f65422ee54759160286b46a493b/code/modules/mob/living/carbon/monkey/combat.dm#L338-L343

https://github.com/tgstation/tgstation/blob/0fb62da664da8f65422ee54759160286b46a493b/code/_onclick/item_attack.dm#L10-L20

https://github.com/tgstation/tgstation/blob/e22560a346772216419457d1a6ad302cf72589dd/code/game/objects/items/theft_tools.dm#L233-L238

https://github.com/tgstation/tgstation/blob/e22560a346772216419457d1a6ad302cf72589dd/code/game/objects/items/theft_tools.dm#L248-L265

**Comment by cacogen** [comment]
>The idea of a NPC monkey murderboning with a supermatter shard is scary

Sounds pretty incredible
