### ISSUE TITLE
Helmet Sprites Don't Update

### ISSUE THREAD

**Issue by Pugie** [tgstation/tgstation#49395]
Wear a security helmet. Attach a seclite to it, the sprite won't change until you take the helmet off and on.

Same applies with turning the seclite off and on, the sprite won't update when you turn the seclite off and on until you take the helmet off and on.

**Comment by trollbreeder** [comment]
i'm guessing the action that turns the seclite on/off doesn't call update_icon

**Comment by itseasytosee** [comment]
Idk works fine for me and it does call update icon. more info?

**Comment by cacogen** [comment]
might've been an issue caused by that PR which if i remember right changed a bunch of things to use update_icon_state() instead of update_icon() which broke some things but if it does call update_icon() and i'm remembering right then that is probably not the case

**Comment by Bokkiewokkie** [comment]
It's the sprite that you wear on your head (so not the one that's in your inventory) that doesn't update so it isn't properly updating the item_state. It having been updated when you removed and reequipped it is because clicking on it does check for a seclite on the helmet and update the item_state (as well as the icon but that's updating fine).

**Comment by ShizCalev** [comment]
Likely an issue with the update_icon_updates_onmob element.

**Comment by ShizCalev** [comment]
confirmed, update_icon_updates_onmob doesn't seem to be initializing on the helmet
