### ISSUE TITLE
New Strange Reagent doesn't work on dead bodies

### ISSUE THREAD

**Issue by 2whatever2** [tgstation/tgstation#49502]
## Round ID:
Completely Forgot that issue bug reports exists and commented on cobby's SR pull instead of actually reporting it and didn't check the Round ID before i left

## Testmerges:
Also dunno the current testmerges while this happened 

## Reproduction:

![image](https://user-images.githubusercontent.com/24631139/74710700-3c942780-525d-11ea-878c-9bd57d472083.png)
Used 50 SR on a lizard with no damage and full blood but they have damaged organs. At first i thought it was because of a stais bed. But then i used another 50 SR and it still did nothing. I used pills for the SR.
![image](https://user-images.githubusercontent.com/24631139/74710833-8715a400-525d-11ea-96b7-f479260b42e5.png)
Then orange man said it only works with patches then i tried it and yielded no results
![image](https://user-images.githubusercontent.com/24631139/74711090-1458f880-525e-11ea-855a-2f2ba5df055e.png)
^Different person now unhusked person. Didn't even convulse with patches.

**Comment by ATH1909** [comment]
god fucking damnit cobby

**Comment by ATH1909** [comment]
Did the corpse convulse when you applied the strange reagent in pill form to it?

Strange reagent doesn't work on husks, but it should still make the husked corpse convulse if it was applied orally. If it's applied via a non-orally method to a carbon (such as a human), it WON'T make corpses convluse (or revive them).

Did you try applied strange reagent orally at any point AFTER unhusking the corpse?

**Comment by 2whatever2** [comment]
Strange reagent still convulses husked bodies and no i didn't give them a pill because i was testing the patch version since I've already tested the pills on the non-husked bodies.

**Comment by ArcaneDefence** [comment]
![image](https://user-images.githubusercontent.com/51932756/76082627-119e1900-5f69-11ea-8da8-da6ad4ab9f56.png)
6u sr in beaker, 5u consumed, revived

https://cdn.discordapp.com/attachments/326831214667235328/685453584372072468/unknown.png
![image](https://user-images.githubusercontent.com/51932756/76082653-1e227180-5f69-11ea-94ad-d9d3625843de.png)
5u sr in beaker, 5u consumed, did not revive, did not call `proc/do_strange_revive`

![image](https://user-images.githubusercontent.com/51932756/76082674-29759d00-5f69-11ea-9dac-8e1176b58931.png)
300u in beaker, 1u sr 299u water, 0.0166u sr consumed, revived

Pills, in any amount, do not work, as they do not call `proc/do_strange_revive`
Patches and splashing do not work, despite people saying they do as they fail `if(iscarbon(M) && method != INGEST)`

**Comment by ArcaneDefence** [comment]
![image](https://user-images.githubusercontent.com/51932756/76119688-30be9a00-5fad-11ea-92ed-7f9dd88826c1.png)
5u of SR in the beaker, splashing onto a simple mob and a silicon, failed to call `proc/do_strange_revive`, presumably because the reagent container has no volume of reagents in it after application. 

![image](https://user-images.githubusercontent.com/51932756/76119966-b6424a00-5fad-11ea-8858-94d978554ac1.png)
6u SR in a spray bottle failed to call `proc/do_strange_revive` as well. 

![image](https://user-images.githubusercontent.com/51932756/76120036-dd008080-5fad-11ea-88ff-7440fcc77f0e.png)
Filling the spray bottle doesn't make it call `proc/do_strange_revive` either.

Spray bottles don't work on carbons because, again, `if(iscarbon(M) && method != INGEST)`.

The simple mob is recognizing both the 5u and 10u sprays calling `/reaction_mob`, but not `proc/do_strange_revive` 
The silicon is recognizing the 5u spray to call `/reaction_mob`, but the 10u spray does not. Neither call `proc/do_strange_revive`

**Comment by redguy999** [comment]
how is this suppose to work?
