### ISSUE TITLE
Minebots have old meson vision.

### ISSUE THREAD

**Issue by HomocidlePancakes** [tgstation/tgstation#49511]
It hurts my eyes.

**Comment by trollbreeder** [comment]
I think engiborgs have old meson vision too.

**Comment by Tharcoonvagh** [comment]
Whats the difference

**Comment by trollbreeder** [comment]
Everything is fullbright as if you're in a badly made gmod map

**Comment by ArcaneDefence** [comment]
![1](https://user-images.githubusercontent.com/51932756/76486331-b2b32680-63e4-11ea-9bee-94b0c29c7c88.png)
![2](https://user-images.githubusercontent.com/51932756/76486347-bd6dbb80-63e4-11ea-9b62-411ca0d97cbd.png)
![3](https://user-images.githubusercontent.com/51932756/76486350-bf377f00-63e4-11ea-9519-924421b02dcb.png)

Here's a few screenshots of the involved mobs.

Engieborgs have see_in_dark to 1, and lighting_alpha to 0 instead of 192 like the other two. 
Obviously any turfs shown by the engieborg/mining bot are fullbright as if their lighting_alpha was set to 0.

I'm starting to think I'm losing my sanity looking at this, so I'ma stop now.

**Comment by LemonInTheDark** [comment]
Not a good fucking first issue. It had to do with THE FUCKING HUD SYSTEM.
