### ISSUE TITLE
Drying Rack Can't Dry Leather

### ISSUE THREAD

**Issue by Something1sWrong** [tgstation/tgstation#49529]
Issue reported from  Round ID: 130828 (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Drying racks, when inspected, clearly say that they can dry wet leather, but when you try to use leather on the drying rack it says "the drying rack smartly refuses the wet leather"

Reporting client version: 513.1507

**Comment by trollbreeder** [comment]
drying racks are subtypes of smart fridges and are coded to only take in plant material, like weed, apples, bananas, deathnettles, etc.
however, they aren't coded to accept wet leather, probably because unless someone codes a new behaviour for this thing, it's gonna turn into dried leather which you can roll up into a blunt

**Comment by Learner10** [comment]
Did the drying rack have power? If not, that might have been why it refused it.

**Comment by nemvar** [comment]
Worked fine for me.
