### ISSUE TITLE
Putting goliath meat in the microwave turns it into a regular steak, not a goliath steak subtype

### ISSUE THREAD

**Issue by spessbandit** [tgstation/tgstation#49538]
In other words, the steak it becomes will not work on any recipes requiring specifically a goliath steak subtype, like the stuffed legion.

Probably because microwaving goliath meat follows the usual steak rules, but the goliath steak subtype is a snowflake result of burning it in lava here: https://github.com/tgstation/tgstation/blob/af1230637bde79cfcde1c351f7bc2055929a2e81/code/modules/food_and_drinks/food/snacks/meat.dm#L231

**Comment by Yenwodyah** [comment]
Pretty sure this is intended.

**Comment by cacogen** [comment]
I don't know if there still is (I have no reason to believe it's changed) but there was a cargo bounty requiring lava grilled goliath steaks, which the microwave version doesn't work for. I guess it differentiates based on typepath rather than something that won't make it unsuitable for recipes that only require goliath meat steaks.

**Comment by fludd12** [comment]
Microwaved goliath meat is also intended to be mildly toxic IIRC.

**Comment by nemvar** [comment]
It's not a traditional goliath steak if it isn't lava cooked. I'd say this is intended
