### ISSUE TITLE
Smoking Pipe Bugs

### ISSUE THREAD

**Issue by Eldeen** [tgstation/tgstation#49637]
Issue reported from  Round ID: 131204 (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1511

A bug I found with all pipes, is that when you pack them, then extinguish them, they are no longer usable. The game says that, "It is already packed!", when you try to add anything new to it and will say, "There is nothing to smoke!", if you try to re-light it. Seems like its stuck in some kind of Schrodinger's weed state where the pipe both has and has nothing inside it. Finally, if you are smoking tobacco in the pipe, it doesn't satisfy your nicotine cravings at all.

Since im autisticly covering smoking in a clown killing, wire weaving simulator. Smoking a cigar (and pipe I believe) seem to make your lungs worse, you dont actually breath in cigar smoke, you are tasting it in your mouth and blowing it out. Same deal with pipes.

(edited out the portion with, unable to create a cob pipe, apparently you need to remove all the kernels of the corn first...)

**Comment by ArcaneDefence** [comment]
![image](https://user-images.githubusercontent.com/51932756/114787138-859a1b80-9d3c-11eb-9bf3-92bb9c4b6585.png)
This isn't the same behavior as described any more, but clearly still bugged.

Smoking tobacco in a pipe also satisfies a nicotine addiction, so that's not a problem any more.
Nicotine addiction has its own issues with how fast it progresses relative to the positive moodlet given for smoking
