### ISSUE TITLE
Chasms are harmless ( can not be moved onto )

### ISSUE THREAD

**Issue by Daxxed** [tgstation/tgstation#50051]
## Round ID:
Been going on for a while I reckon

## Reproduction:
Killed a necropolis tendril
Tried to run into the chasm it created
Tried throwing people in
Tried throwing items in

Oversight from another PR as I can't seem to find anything specificly changing chasms
EDIT: https://github.com/tgstation/tgstation/pull/48659 maybe ?

**Comment by Pumpkinoe** [comment]
I thought this was an intentional change, since not looking where you're going for like five seconds and suddenly getting removed from the round because you were trying to fight a megafauna and didn't see the different pixels on the floor wasn't fun

**Comment by Daxxed** [comment]
It's not that hard to keep track of where the holes are in my opinion.
Pretty sure this was just a bit of forgotten code, sorry you got used to the bug by now.

**Comment by ATH1909** [comment]
Honestly, I think that this is an improvement to the instadeath tiles that chasms were before.

Can we just... keep them this way?

**Comment by Pumpkinoe** [comment]
agree with ATH, is there really a reason to have them be instadeath tiles after the main threat?

**Comment by GravitronBlue** [comment]
>Honestly, I think that this is an improvement to the instadeath tiles that chasms were before.
Can we just... keep them this way?

While the issue is absolutely an oversight bug that's bound to be fixed soon(tm), it seems like there's at least support for boots or something that prevents you from accidentally running over chasms(and perhaps lava?). Granted a feature like that sounds a bit hugbox and wormhole jaunters are meant to fill the niche for a chasm lifesaver item as it is.
