### ISSUE TITLE
Screen freezing when, as a ghost, you fly towards cargo from the southeast

### ISSUE THREAD

**Issue by Shirbu** [tgstation/tgstation#50113]
Issue reported from  Round ID: [132626](https://scrubby.melonmesa.com/round/132626) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1516

I was adminning on Manuel, when 3 consecutive times, twice whilst following someone and once just moving to cargo from science, the visual part of my screen froze. 

Reconnecting made the screen black, but did not recover the visuals. Text was not frozen, and I could hear and speak to ghost chat. 
Hitting aghost in order to return to my body did not resolve the issue. 
Quitting the game and rejoining resolved the issue. 

No other ghosts experienced this freezing.

Will continue testing and report results.

**Comment by Shirbu** [comment]
Failed to reproduce after quitting twice, rejoining, deadmining, readminning, and testing again.

**Comment by Shirbu** [comment]
Occurred once more when a menu was open, moving from northwest hop office, moving northwest

**Comment by Shirbu** [comment]
Dreamseeker is now stopping working each time I attempt to rejoin

**Comment by Shirbu** [comment]
Ending byond via the task manager did not resolve this issue. It is ongoing.

**Comment by Shirbu** [comment]
Restarting computer did not resolve the issue. It is ongoing.

**Comment by Shirbu** [comment]
I did update to the latest version of the beta minutes before logging in

**Comment by Dennok** [comment]
Try clear byond cache. and make screenshot.
and maybe try change view size

I get this things when move shuttle docking over station.
Last time as i use it, it freeze near escape shuttle dock.

**Comment by Shirbu** [comment]
How does one change byond cache? Can't stay in the game long enough to change view size.

**Comment by TimeURSS** [comment]
I also have this issue often, and it's kind of annoying. When I join the game, in a determinate time the screen freezes, but I can listen people doing stuff and me moving. Chat works as well. I then try to reconnect, just to see the screen black with the same conditions as before. Kind of weird, but I really hope it gets fixed, since I cannot play barely any server due to this issue. Sometimes the walls and stuff glitches, and I can only see the flooring.

This is when screen froze, kept like this for long time: https://cdn.discordapp.com/attachments/587000604547874826/690490188933365760/unknown.png
Screen glitching: https://cdn.discordapp.com/attachments/587000604547874826/690500942226915338/unknown.png
Screen after reconnecting, chat keeps going on and sound stays: https://cdn.discordapp.com/attachments/279359975250198528/690501498727301140/unknown.png

**Comment by Arkatos1** [comment]
I also have this issue after updating to 513.1516, it is prolly connected to that. Try downgrading to some older 513 version and see if it helps.

**Comment by Shirbu** [comment]
ok.

**Comment by TimeURSS** [comment]
It seems reverting worked! Seems it's a problem of the update. Thanks, and I hope the update gets fixed!

**Comment by Arkatos1** [comment]
New BYOND version 513.1517 was released, which seems to have fixed the issue.
