### ISSUE TITLE
The "Wacky" mutation's description text is broken

### ISSUE THREAD

**Issue by TheSmallBlue** [tgstation/tgstation#50474]
## Round ID:
[134231](https://scrubby.melonmesa.com/round/134231)

## Testmerges:
None (as far as I can tell)

## Reproduction:

- Do the usual genetics procedure (get a monkey inside the DNA scanner, open the DNA console and go to the sequencer)
- Humanize the monkey and start resolving genomes until you get Wacky
- Check Wacky's description under "Sequence Info", instead of it being "Unknown" as usual, it will say "`<span class='sans'>Unknown.</span>`"

![image](https://user-images.githubusercontent.com/24967815/78821852-82918000-79b0-11ea-8756-ce12e219bae8.png)

[The Wacky mutation shown in the "sequence" screen on the bottom DNA console]

![image](https://user-images.githubusercontent.com/24967815/78821916-9a690400-79b0-11ea-99ee-aa46533f85ec.png)

[Full room shot, I'm with the chair with chameleon. Hows which console I'm using and the map]

(Appears in all DNA consoles, in both the Storage (on Disk and on console storage) and the sequencer screens. Seems kinda obvious but decided to check just in case.)

![image](https://user-images.githubusercontent.com/24967815/78821958-a9e84d00-79b0-11ea-9d52-0ea32650e57c.png)

[Wacky mutation on the storage screen, in the console storage]

![image](https://user-images.githubusercontent.com/24967815/78821966-aead0100-79b0-11ea-9ca5-771424d695f4.png)

[Wacky mutation in the storage screen, in the disk storage]

![image](https://user-images.githubusercontent.com/24967815/78822039-ca180c00-79b0-11ea-9068-3a476561201c.png)

[Wacky mutation on the disk storage screen, on a different DNA console]

**Comment by Timberpoes** [comment]
Hi! Thanks for the incredibly detailed issue report.

It's because of the new interface not being compatible HTML from text strings, previously Wacky would show up as "Unknown" in a cute lil' comic sans font in the HTML-based interface.

![image](https://user-images.githubusercontent.com/24975989/78839774-08352000-79f1-11ea-9b11-f3a1f235c50d.png)

I may end up just rewriting the Wacky description. I don't think there's an elegant way to handle this in particular - Wacky is the only mutation that has HTML embedded in its description.
