### ISSUE TITLE
The turbine defies the laws of thermodynamics

### ISSUE THREAD

**Issue by LemonInTheDark** [tgstation/tgstation#50667]
This is less of an unintended issue, and more like an intended one.

The issue lies in how the machine makes power.
The turbine generates power based on the pressure of the tile in front of the compressor.
It does this by in-taking a proportion of the gas in front of it, using the molar count and temp to modify the goal rpm, and then outputting a portion of the gas out the other end.

You can then take that gas, move it back to the input, and repeat.
The only thing about this system that changes is the heat, due the way tiles slowly cool down.

Fortunately we can just rely on the molar count.

The only way to fix this I can think of is to make pumping the required gas cost more then the output power.

See the image for more details. This is with full upgrades, so divide the power output by 4 to get upgraded values.

![image](https://user-images.githubusercontent.com/58055496/80270675-1630a500-866f-11ea-9bb1-d1d3ca82be0e.png)

**Comment by bobbahbrown** [comment]
the turbine should be cooling the gas on the other side

the gas loses energy from doing work on the turbine itself and it also cools from expanding

**Comment by LemonInTheDark** [comment]
That would help, we'd still have the issue of the molar counts. I'll look into it.

**Comment by TemporalOroboros** [comment]
If it's any help there's a Wikipedia article on pretty much exactly this. https://en.m.wikipedia.org/wiki/Steam_turbine
Though that might be a bit too much math for the turbine.

**Comment by griffithlol** [comment]
One of the basic gas power cycles is called a Brayton cycle. 
![fig5BraytonClosedCycle_web](https://user-images.githubusercontent.com/18688323/86031270-9ecb1900-ba03-11ea-9a7a-584709b61c98.jpg)

This isnt exactly what we have occuring, but this is an example of a thermodynamic cycle we can model and refrence. I need to think about it a bit more to try to lay out whats going on, but I hope this helps. Really in order to understand it, we need to capture the gas properties at every step, ie. From this and a better understanding of each step, we can draw things like the efficiency of the cycle, the work in and out, and the heat in and out, and likely put a numerical value on the problem. 

On another note, looking at the code for the turbine in `tubine.dm` is kinda interesting. there are several points in which the programmer comments, "this should be changed later". I will do some digging and see if I can figure out step by step what is going on.

**Comment by griffithlol** [comment]
Ok after some reflection, I have reached an impasse. The setup makes no sense. The compressor being placed **after** the combustion occurs defines any engine I can think of, and makes next to no sense. The purpose of a compressor is to drive the combustion hotter by jacking up the air pressure before fuel is injected for the burn. If you look at airplane turbines
![turbofanturbojet](https://user-images.githubusercontent.com/18688323/86038048-52390b00-ba0e-11ea-8905-f666beb70f8a.png) 
You can see the pattern I am talking about.

**Comment by LemonInTheDark** [comment]
Yeah. Part of it is most of the more... techy? stuff in the game aren't really true to life, but more true to how people think it works. Which makes catching on to it a lot faster. See chemistry for a really good example.

The main issue here is the turbine makes power based on pressure, so heat and molar count, and the draw a pump requires to create that much pressure is lower then the power that amount of pressure is worth. We can't change this without making pumps prohibitively expensive to use, or lowering turbine power output so much that it becomes useless. 

This is very similar to the issue with the TEG.

**Comment by griffithlol** [comment]
I think theres plenty of room to play with power costs for pumps(including scrubbers, injectors, volume and pressure etc) and most of the station wouldn't notice. Playing around with this we may be able to come up with a fair balance. I will have to do some code diving to see how much energy pumps require, but even changing it so that it requires more at higher pressures may be able to chip away at the balance issue. Worth at least trying to get some numbers to reflect on.
