### ISSUE TITLE
Health Sensor Attached Grenade DID NOT Trigger On Death

### ISSUE THREAD

**Issue by DAKKA-WAAAGH** [tgstation/tgstation#50673]
## Reproduction:
After finding out I can utilize health sensors for creating a bomb triggered on death/crit, I made one to test out this round because it was ops. I created a 100u pot bomb, stuffed it in a nade, turned the sensor on and set it to detecting death and used the screwdriver (as per wiki instructions) to attach it to the unfinished grenade. Finished it, set it to 3 seconds, and eventually my death came at the hands of a nukie. Luckily the nukie started looting me at the same time I died... but no explosion came and I could see that the nade didn't even activate in the first place. He turned me into a zombie afterward and I confirmed again that the nade was still in my pocket where I left it and it was still how I left it before death.

You can imagine how disappointing it is to have a perfect moment for something to happen and it just doesn't work. (He was low on health too, dammit!)

**Comment by Angustmeta** [comment]
I'll test

**Comment by Angustmeta** [comment]
Tested now with latest updates:
- 10/10 potassium/water with health sensor on death mode, placed inside the internals box in the backpack of a chemist. Blasted the fool with a laser to death. Worked, exploded. 
- Same again but I used a screwdriver on it to set it to 3 seconds after completion. Worked, exploded. 
- Same as above but with the grenade in a pocket instead of internals box. Still set to 3 seconds. Worked, exploded, but after a weird second of delay. 
- Same as above but drank romerol first. Worked, exploded. 

Grenade chem logging seems to be broken so I can't figure anything out from the logs either.
