### ISSUE TITLE
Plant grafts runtime due to references to deleted plants

### ISSUE THREAD

**Issue by Angustmeta** [tgstation/tgstation#50879]
Every round nearly all grafts stop working when they've been saved for a while. 

### Reproduction
I don't know exactly how they break, but I do get a runtime message when trying to use a broken graft on a tray with a growing plant. 

**[18:23:35] Runtime in hydroponics.dm,739: Cannot read null.lifespan
  usr: angust/(Nehemiah Hill)**

Do grafts have limited lifespan or something?

**Comment by TemporalOroboros** [comment]
I'm going to guess that this is caused by the graft holding a reference to the plant it was cut from.  I am also going to guess that the plant is getting `qdel()`ed when it's cleared from the tray which nulls the reference the graft holds hand causes problems when the graft is applied. If this is true the graft is probably also affected by changes to its original after it has been cut.
