### ISSUE TITLE
Comprehensive list of belts with missing sprites.

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#50895]
Issue reported from  Round ID: [136312](https://scrubby.melonmesa.com/round/136312) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1513

Reproduction: Go to game panel, click create object, search "belt." I tested out every object that came up for this search.

/obj/item/storage/belt/utility/chief

/obj/item/storage/belt/utility/chief/full

/obj/item/storage/belt/utility/full/engi

/obj/item/storage/belt/utility/full

/obj/item/storage/belt/utility/full/atmostech

/obj/item/storage/belt/utility/full/syndicate

/obj/item/storage/belt/utility

/obj/item/storage/belt/medical/paramedic

/obj/item/storage/belt/medical

/obj/item/storage/belt/security/full

/obj/item/storage/belt/security

/obj/item/storage/belt/military/abductor/full

/obj/item/storage/belt/military/abductor

/obj/item/storage/belt/military/assault

/obj/item/storage/belt/chameleon   ....................     This is because it is disguised as a toolbelt.

/obj/item/storage/belt

**Comment by Dorsisdwarf** [comment]
From combined issue #50870 showing utility belt errors> ![image](https://user-images.githubusercontent.com/63235460/80954801-5f66be80-8dfe-11ea-9da6-3d5e41592fab.png)
> ![image](https://user-images.githubusercontent.com/63235460/80954813-6392dc00-8dfe-11ea-96f2-b33136cc02f7.png)
> ![image](https://user-images.githubusercontent.com/63235460/80954823-68f02680-8dfe-11ea-8289-4d3cab687308.png)

**Comment by Fhaxaris** [comment]
### I might be wrong here but...
items, where `icon_state` and `item_state` are identical, aren't broken (provided they have an actually have an icon)
NOT BROKEN:
https://github.com/tgstation/tgstation/blob/248a6fd50cc92a8964567929b83cb1910d349738/code/game/objects/items/melee/misc.dm#L164-L169
BROKEN:
https://github.com/tgstation/tgstation/blob/248a6fd50cc92a8964567929b83cb1910d349738/code/game/objects/items/stunbaton.dm#L1-L6
Changing the `icon_state` to match the `item_state` the item will display on the character correctly (but of course this messes up the way the stun baton looks on the floor and in the inventory.) This also doesn't happen in the suit slot. Placing the stun baton in the suit slot instead of the belt doesn't have this issue (same with some other stuff like the PDA, which is why like everyone is running around with the stupid pink belt.)
All of this suggests to me that items in the belt slot are incorrectly displaying the `icon_state` in place of the `item_state`. (which typically isn't a problem because they are normally identical).
