### ISSUE TITLE
Inorganic Biology Bug Part 4 or 5

### ISSUE THREAD

**Issue by Shikarego** [tgstation/tgstation#51150]
Issue reported from  Round ID: [137338](https://scrubby.melonmesa.com/round/137338) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1524

Same deal. This time I got IB early and set it aside. I made the rest of my virus, then mixed the cultures till I had all 6. Usually I get IB last to avoid the bug (works pretty consistently) so this time I wanted to see if I could predict and trigger it. I **/think/** it's related to IB being added in from a different culture rather than mutated by a chem, but that's an educated guess at best.

**Comment by XDTM** [comment]
That does narrow it down a lot.

The advance_mix proc apparently works by creating a Copy() of each disease (which currently var-copies the infectable_biotypes var, but does not apply symptoms due to an oversight), then picks randomly one of these two diseases as a base and adds the symptom of the other (properly, calling `OnAdd()`) to it. So there is a 50% chance of having a disease with a cloned `infectable_biotypes` with Inorganic Biology never having used OnAdd(), and a 50% chance of a disease with a regular `infectable_biotypes` which then gets modified by the Inorganic Biology's OnAdd(). 

Given that it's pretty likely that one of these two results is what is causing the bug in some way (still not sure how it could happen, unless copying bitflag vars is subject to a byond bug). 

I'm not able to test this myself now, but if anyone's inclined to it would be useful to see how the `infectable_biotypes` var changes when mixing diseases a few times.

**Comment by willox** [comment]
I mixed a disease with Facial Hypertrichosis and a disease with Inorganic Biology 10 separate times and every time the resulting disease had the correct infectable_biotypes (MOB_ORGANIC & MOB_MINERAL)
