### ISSUE TITLE
 dmm loading isn't initializing turfs properly on map place.

### ISSUE THREAD

**Issue by JusticeGoat** [tgstation/tgstation#51323]
When i load a map though the debug map template - place, wires and atmos pipes fail to place under the floor tiles.

**Comment by Valtosin** [comment]
this also happens with shuttle manipulator, I think only after init

**Comment by Dennok** [comment]
Bad

**Comment by Valtosin** [comment]
Still not fixed?

**Comment by JusticeGoat** [comment]
the last time i tried placing a map file for an event it was still broken last month.

**Comment by Valtosin** [comment]
Most probably this #50015 or this #49644 breaks things, I'll try to dig more

**Comment by Valtosin** [comment]
So, the problem is here: 
https://github.com/tgstation/tgstation/blob/259acc8c81054d89f7b6bcd9ff702fdf587a19ed/code/datums/elements/undertile.dm#L32
It passes 100 invisibility variable value, but then somehow it loads with 0 invisibility. You can fix this temporary with VV by setting all wrong loaded hidden pipes/cables invisibily to 100. 

Maybe someone can fix this properly?

**Comment by JusticeGoat** [comment]
Ok so i setting cables invisibility to 100 will have all of the maint wires and pipes that need to be shown vanish too.

**Comment by Jalleo** [comment]
@Time-Green do you think that https://github.com/tgstation/tgstation/pull/49644 caused this issue due to trying to check the tile before its fully ready to process the comsig?

**Comment by Time-Green** [comment]
> @Time-Green do you think that #49644 caused this issue due to trying to check the tile before its fully ready to process the comsig?

It’s very possible

**Comment by Time-Green** [comment]
Issue has been fixed (I forgot how but the feature just works)
