### ISSUE TITLE
Derelict Drone Shell Dispenser Infinite Materials Exploit/Bug

### ISSUE THREAD

**Issue by jwc1015** [tgstation/tgstation#51402]
Issue reported from  Round ID: [138446](https://scrubby.melonmesa.com/round/138446) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1501

If I attempt to put materials (or at least iron) into the dispenser, no matter how much I put in, it is added to the machine, but the stack in my hand is not removed/lessened or whatever. Then I could remove the mats from it with a crowbar, and theoretically repeat for infinite mats.

**Comment by willox** [comment]
I'll document the problem here. I'll probably make it sound confusing, though.

Drone Shell Dispensers set `/datum/component/material_container/var/precise_insertion` to `TRUE`. This means that you get a prompt for how many materials you want to insert. This prompt is weird a.f. because it really wants to know how many material units you want to insert, not how many stacks. 2000 units would be 1 sheet (this is fuck-up number 1)

Your average user thinks its the amount of stacks, and writes something like `50`. `/datum/component/material_container/proc/insert_item` converts and rounds its `amt` var to the nearest amount of sheets, so in this case `0`.  It then calls `/datum/component/material_container/proc/insert_item_materials` which will insert _all_ materials from the item regardless of the `amt ` var (this is fuck-up number 2). `insert_item` then returns the `0` to `/datum/component/material_container/proc/user_insert`, which results in no materials being removed from the sheet.

The fix is: `insert_item` should actually use the `amt` param properly and also return the number of mats it has used to `user_insert`. This is because `user_insert` needs to know how many mats to remove from the source item.
The bonus fix is: The `precise_insertion` input box should take the number of sheets instead of the number of mat units.
