### ISSUE TITLE
if you somehow resurrect(nanite defib,etc) inside a dragon you can beat him to death from the inside

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#51491]
138978

**Comment by Time-Green** [comment]
I swear to god tlal how difficult is it to put a "steps to reproduce" in there?

**Comment by IndieanaJones** [comment]
Can't seem to reproduce on my end.

**Comment by Tlaltecuhtli** [comment]
i wasnt the one vored, i was ghost and saw a dude beating the dragon from the inside, maybe fake deaths like deathcoma ?

**Comment by ATH1909** [comment]
Were they a ling?

**Comment by Tlaltecuhtli** [comment]
13:44:31 [mob_471] (0,0,0) || Rafael Collins 's Defibrillation nanite program was triggered by a Damage Sensor program with code 4.

defib nanites revived him in the dragon's belly

**Comment by Doosteroni** [comment]
This should be a feature

**Comment by IndieanaJones** [comment]
This has also been a longstanding bug with pretty much any mob that contains another.  Such things include:

- Zombie Blob Spores
- Slaughter/Laughter Demons
- Morph

The ideal solution is debatable.  You could disable their ability to harm the mob they're contained inside, or just say this is a feature and call it a day.

**Comment by Firecage** [comment]
Honestly, this is a thing which happens in so, so many video games, movies, anime, manga, comics, etc. That, well, it isn't even strange honestly if it unintentionally happens. I would rather say it should be turned into a full fledged feature instead of a bug.

Remember how it was a feature how we could attack Xenomorphs from the inside after they swallowed us?

**Comment by IndieanaJones** [comment]
Fixed for Space Dragon specifically as of #54124
