### ISSUE TITLE
Design Disks don't seem to properly load designs onto autolathes.

### ISSUE THREAD

**Issue by Learner10** [tgstation/tgstation#51493]
## Reproduction: Simply load an object onto a _design disk_ (not a technology disk), and use it on an autolathe.

When you use the disk on the autolathe, it will begin a progress bar, and inform you that a design is being loaded onto the autolathe, but once completed, nowhere within the autolathe menus will the new design be listed. In the previous situation, the autolathe that was the subject of error had been a newly assembled lathe that was constructed with upgraded parts.

**Comment by timothymtorres** [comment]
@Learner10 I tested this just now and I had no issues.

I spawned a design disk (from a ruin) using admins commands and inserted it into cargos autholathe.  The objects from the design disk appeared in the "imported" tab.  I then went and built an autholathe from scratch using upgraded parts and inserted the same disk and the objects still appeared in the "imported" tab.  Going to close this since this probably got fixed in the last two years.  If you have the same problem just ping me and I will reopen this.
