### ISSUE TITLE
Zombie "succumb" comand bug.

### ISSUE THREAD

**Issue by DrCrawler** [tgstation/tgstation#51601]
Issue reported from  Round ID: [139372](https://scrubby.melonmesa.com/round/139372) (/tg/Station Basil [ENGLISH] [US-WEST] [100% FREE LAG])

Reporting client version: 513.1525

Aight, so the thing is when you type "succumb" as zombe you turn human
.

**Comment by XDTM** [comment]
Zombies turning back into human when dying is intended, although a bit of a remnant from when they didn't have NODEATH.

Whether succumb should work or not with NODEATH is worth discussing, since it's more or less on the same level as suicide, which does work.

If you turn back into human AND stay alive then it's an actual bug, but i'm pretty sure that shouldn't be happening.
