### ISSUE TITLE
Dynamic message appeared that shouldn't have appeared.

### ISSUE THREAD

**Issue by BeeSting12** [tgstation/tgstation#51675]
Issue reported from  Round ID: [139695](https://scrubby.melonmesa.com/round/139695) (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 513.1513

I did not force anything so not sure as to how this appeared.

ADMIN LOG: DYNAMIC: Checking for midround injection.
ADMIN LOG: Possible volunteers was 0. This shouldn't appear, because of ready(), unless you forced it!

**Comment by kriskog** [comment]
Seems we dont log which ruleset failed in this instance, but it was a midround from_ghost ruleset. Theres a few of them without a specific ready() defined, which would cause them to fall back to the midround ruleset ready() that does not check if there are any ghosts to poll. This check is necessary for every from_ghost ruleset, so adding one and making the others call it instead of checking individually is a solution.

**Comment by JohnFulpWillard** [comment]
Closed by https://github.com/tgstation/tgstation/pull/56221
