### ISSUE TITLE
The disk can teleport into the greentext room on Icebox

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#51753]
Issue reported from  Round ID: [139933](https://scrubby.melonmesa.com/round/139933) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1526

I'm not really sure if this is intentional or an oversight, but the disk was taken off the z-level and teleported back to safety, which ended up being the greentext Lusty Xenomorph room. It's not _technically_ an illegal place for it as you can enter that room, but it still shouldn't be able to land there.

![image](https://user-images.githubusercontent.com/7019927/85127903-ee386a80-b1f5-11ea-92f0-ae0b06a0182c.png)

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/c31b2c990bc80e259311b252992b9778d51c6aac/code/modules/antagonists/nukeop/equipment/nuclear_authentication_disk.dm#L27-L30

https://github.com/tgstation/tgstation/blob/c31b2c990bc80e259311b252992b9778d51c6aac/code/datums/components/stationloving.dm#L52-L72

https://github.com/tgstation/tgstation/blob/c31b2c990bc80e259311b252992b9778d51c6aac/code/datums/helper_datums/teleport.dm#L111-L187

Some pertinent background information involving stations on a normal space map, the ruins are on another z-level.  However for Ice station there are 3 z-levels and the top two z-levels are considered to be the station.  Ruins spawn on the middle part of the z-level, so by extension these are also considered to be apart of the station since they spawn on the same z-level.

The find safe turf proc should probably use an `istype(turf_area, /area/station/)` check or have it as an argument.  It should fix a lot of these similar problems.

**Comment by Sealed101** [comment]
should have been fixed by #83012; only real way for it to be considered a safe area now is if all station areas are somehow not in the global `the_station_areas` list, which is how likely to happen again? anyone?

https://github.com/tgstation/tgstation/blob/f6c8c4675785076b453d93f64eeef907dc08e17f/code/datums/components/stationloving.dm#L52-L73
https://github.com/tgstation/tgstation/blob/f6c8c4675785076b453d93f64eeef907dc08e17f/code/controllers/subsystem/mapping.dm#L467-L485
