### ISSUE TITLE
Getting then losing HARS removes brain traumas

### ISSUE THREAD

**Issue by PKPenguin321** [tgstation/tgstation#51841]
Had a dude come into the genetics lab to do this maybe a few weeks ago and forgot all about it until a HARS thread on the forums reminded me recently

## Reproduction:

- Get a brain trauma
- Get HARS, exploding your head and brain
- Cure HARS, regrowing your head and brain
- No more trauma

**Comment by Timberpoes** [comment]
This is less a bug and more a fact that brain traumas are stored in the brain. I've always considered this interaction closer to emergent gameplay rather than a de-facto bug.

To explain what happens with HARS:
HARS sets the brain as a non-vital organ, explodes the head, deletes the brain and scatters the eyes, tongue, ears and some gibs across the room.

The brain is now gone. Like, full QDEL gone. Curing HARS regrows a brand new set of eyes, ears, tongue and brain to fit in the poor sod's new head.

So technically curing HARS also cures eye damage including damage-induced blindness, ear damage including damage-induced deafness, the inability to speak properly due to lacking a tongue and removes all brain damage and brain traumas.

Personally, I find this specific use-case hilarious and love the cross-departmental interaction. It's also the only reliable method to clear deep-rooted brain traumas, which are otherwise curable only by RNG which can often given even worse traumas in return.

If it's too powerful, we can probably take steps to address it (storing a reference to the old brain as opposed to flat out QDELing it) but I'd personally oppose it. I love that "in-the-know" medbay staff come knocking on my door for HARS mutators when there's a minor major abductor outbreak.

**Comment by Pugie** [comment]
Yeah... plus with wounds now if you do end up using HARS to get rid of traumas you will probably get a critical skull fracture and have to seek medical help.

**Comment by PKPenguin321** [comment]
It may or may not remove magical or permanent traumas which would be a bug

**Comment by trexter555** [comment]
feature

**Comment by Pugie** [comment]
> It may or may not remove magical or permanent traumas which would be a bug

it removes quirk traumas so yes

**Comment by Timberpoes** [comment]
> 
> 
> > It may or may not remove magical or permanent traumas which would be a bug
> 
> it removes quirk traumas so yes

Which quirk traumas are actually brain traumas? I added a bunch of negative ones that seem like they'd be brain traumas, and they're ALL listed as disabilities, which have nothing to do with the brain.

![image](https://user-images.githubusercontent.com/24975989/85703791-9a3af380-b6d7-11ea-95cf-34a0774b7a90.png)

After curing HARS, all disabilities are still present and the act of curing HARS deals enough brute damage to the head to crack your skull and give you a cerebral trauma.

![image](https://user-images.githubusercontent.com/24975989/85704220-01f13e80-b6d8-11ea-867f-d074e1bfa9f0.png)

![image](https://user-images.githubusercontent.com/24975989/85704130-ee45d800-b6d7-11ea-91f2-001f7ac735f0.png)

Although, by its very nature of destroying and regrowing the brain, it does wipe
TRAUMA_RESILIENCE_MAGIC //Curable only with magic
TRAUMA_RESILIENCE_ABSOLUTE //This is here to stay

Which does include quirk paraplegics. We could possibly compromise and store all MAGIC and ABSOLUTE brain traumas and re-apply them when HARS is cured, although it wouldn't stop those traumas not existing while HARS is active. There's no brain for the traumas to reside in, so it's functionally impossible to have ANY trauma while HARS is active as they're all brain code.

Some traumas also depend on having a specific item equipped (most often these are MAGIC traumas) which could encounter problems as to whether they should be cured or not.

Indeed, if you equip an item that is meant to give you a trauma while you have HARS, you probably won't get that trauma when HARS is cured because the gain_trauma proc will usually only fire when equipped.

I'll have to look into this. There is a chance anything that is a MAGIC or ABSOLUTE trauma can be shifted to the trait system instead, which is far more robust when dealing with things like brain and body transplants and pod cloning?

**Comment by ExcessiveUseOfCobblestone** [comment]
Some of the traumas (particularly quirk ones) are balanced around you not being able to nullify them which I think is a problem in itself.

**Comment by XDTM** [comment]
I don't know how HARS is coded, but it would probably solve any brain-related issue if it just teleported the brain item in the chest or nullspace but kept it reachable through the regular procs.
