### ISSUE TITLE
Mime crayon does not successfully dye many items.

### ISSUE THREAD

**Issue by Quietly12** [tgstation/tgstation#51857]
## Reproduction:

1). Kill mime and steal his unique crayon
2). Throw crayon in washing machine with various articles of clothing (found this bug with imperial monk robes and sombrero, and insulated gloves.
3). Insulated gloves turn out white, other clothing remains unchanged.

## Expected behavior

(Potential for Cool) -Clothing becomes invisible/transparent to go along with crayon writing with transparent/invisible ink.
(Normal) - Clothing becomes white.

**Comment by timothymtorres** [comment]
So I code dived inside the washing machine code and it appears this is intentional.  Only certain jumpsuits, gloves, and clothing objects can be dyed a color.  

https://github.com/tgstation/tgstation/blob/fb2ccde37ef9c4f9c3842d74cfe0efb375a84261/code/modules/clothing/under/color.dm#L1-L3

https://github.com/tgstation/tgstation/blob/master/code/game/machinery/washing_machine.dm

Special clothing and hats like the imperial monk robe and sombrero won't work with the dye.  I'm sure as more clothing gets transferred over to GAGS that this will change.  I do like your invisible/transparent clothing idea.
