### ISSUE TITLE
Silicons can't read

### ISSUE THREAD

**Issue by ReplicantTerry** [tgstation/tgstation#51959]
Issue reported from  Round ID: [140893](https://scrubby.melonmesa.com/round/140893) (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1525

Cyborgs can't read  pieces of paper and AI can't read through their cameras like they used to be able to. I dunno if AI's can't read when people hold things up to their camera.

**Comment by ReplicantTerry** [comment]
apparently neither can I

**Comment by Wayland-Smithy** [comment]
Cyborgs, and humans too, can read by examining twice like when looking for scars. For AI though no dice which is truly unfortunate.

**Comment by dragomagol** [comment]
Cyborgs can still read papers by examining them, but as far as I know AI have never been able to examine things through their cameras unless it's mashed up against them

**Comment by Wayland-Smithy** [comment]
Before when AI examined paper through cams it would become obfuscated, like when you overhear a whisper from a distance.

**Comment by dragomagol** [comment]
Oh that's right, that's how you would get the PDA messaging log password from the CE's office

**Comment by timothymtorres** [comment]
I do believe AIs have never been able to read papers at least to my knowledge unless a person shoves a paper in front of a camera.  Nor do I think this would be considered oversight since silicon players have certain flaws and I think not being able to read paper would be one of them.  Similar to how AIs can't hear people talking unless they turn on a nearby intercom.

**Comment by Wayland-Smithy** [comment]
I disagree, and think this should stay open.

The difference between hearing and someone speak and reading text on paper is clear, and the limitations of the camera aspect were taken into account. For instance when the AI would read a piece of paper on a desk that says "Hello World!" it would see "He#l^ $or%d!" but the obfuscation would change with each viewing so with enough patience you could work out what exactly was on the page. It really only matters for the messaging server key, and it was in fact nuked by the paper UI upgrade a long to support richer text that happened a time ago just ask any other vets.

**Comment by timothymtorres** [comment]
So I don't know how long the paper obfuscation has been a thing, but I do know that an AI could read paper when it was pressed directly against the camera.  If you look at https://github.com/tgstation/tgstation/commit/c20712414247245ed1ca63e1159af6281739ca7b you see this behavior was added directly and you had to be standing 1 tile away from the camera (just like when regular mobs have to read paper) to read something.

**Comment by Wayland-Smithy** [comment]
Holding paper up to the camera has always been a different mechanic that allows for another way to contact AIs where they can read the text in the clear. While previously AIs could examine paper in camera range with the obfuscation I described. I'm sure I could dig up that code, possibly reused from whispers, from the "new paper" PR that nerfed AIs and made it so they must depend on a borg to read sensitive documents.

**Comment by Wayland-Smithy** [comment]
Pretty sure this is it: https://github.com/tgstation/tgstation/blob/6ef421be4282bb15a70f09b4964bb517b9c6e26f/code/modules/paperwork/paper.dm#L123-L128
And the PR that deleted it #51534

**Comment by timothymtorres** [comment]
If you read the code a few lines below you see that distance was accounted for:

https://github.com/tgstation/tgstation/blob/6ef421be4282bb15a70f09b4964bb517b9c6e26f/code/modules/paperwork/paper.dm#L123-L134

The AI could only read papers unless the camera was one tile away just like every other mob in the game.

If you git blame all the way back this was the commit that added `attack_ai` for paper https://github.com/tgstation/tgstation/commit/2b4f25c11f31abb4ec7134fb599fa7590218318f

Regardless, it's pretty clear that the AI was never supposed to be able to see a paper from any tile in view.  The obfuscation code was a hack to prevent powergaming AIs from becoming too OP by hacking the PDA message console.

**Comment by Wayland-Smithy** [comment]
> Regardless, it's pretty clear that the AI was never supposed to be able to see a paper from any tile in view.

I saw that code, and it reads to me like if the camera (ai.current right?) is 0 to 1 tiles away from the paper then it is displayed in the clear `<BODY>[info]<HR>[stamps]</BODY>` but if it is 2 or more tiles away then it's obfuscated by I presume the stars proc `<BODY>[stars(info)]<HR>[stamps]</BODY>` and probably the reason the functionality was not ported was because that "starring" would need to account for and not malform the new markup the PR I mentioned was adding support for which seems hard.

> The obfuscation code was a hack to prevent powergaming AIs from becoming too OP by hacking the PDA message console.

Sorry I don't see a PR in those blames and I'm not going digging could you share the specific text that led you believe that was the intent since is was around like that for a really long time and not an issue?
