### ISSUE TITLE
Blazing oil blobbernaut is not immune to fire

### ISSUE THREAD

**Issue by DemonOfHatred** [tgstation/tgstation#52058]
Issue reported from  Round ID: [141304](https://scrubby.melonmesa.com/round/141304) (/tg/Station Terry [EU] [100% LAG FREE] [New-Dedi])

Reporting client version: 513.1526

**Comment by Kaffe-work** [comment]
it's weak to heat, actually

**Comment by Kaffe-work** [comment]
ill take a look at it tomorrow, if I remember

**Comment by Wayland-Smithy** [comment]
It is supposed to be immune to fire specifically, but burn type damage should get though and sometimes triggers a fire.

**Comment by Kaffe-work** [comment]
It's not even immune to fire in any way, no one coded it **Thonk**.

**Comment by Wayland-Smithy** [comment]
Please feel free to correct me here, as I am still familiarizing myself with the codebase and dmcode in general, but if I am reading this correctly the "fire" damage_flag specifically does 0 damage. Maybe I am confused because of armor calc code?

![image](https://user-images.githubusercontent.com/64715958/86978692-54991480-c134-11ea-82d0-ef1db812eb4c.png)

**Comment by Kaffe-work** [comment]
Yeah, but blobbernaut itself also has max temp set to 360, and when that is higher it means the blobbernaut will take damage - not from fire itself. (Unless im mistaken)
