### ISSUE TITLE
IceDemons OpenFire proc is utterly busted

### ISSUE THREAD

**Issue by optimumtact** [tgstation/tgstation#52365]
## Round ID:[142735](https://scrubby.melonmesa.com/round/142735)
![](https://file.house/mI5G.png)

**Comment by TheVekter** [comment]
29 instances pulling higher CPU than atmos 🤔

**Comment by TemporalOroboros** [comment]
Relevant code.

https://github.com/tgstation/tgstation/blob/732d83f249a3a6f60b1e31f9fcea6a6561d90dd3/code/modules/mob/living/simple_animal/hostile/mining_mobs/ice%20demon.dm#L52-#65

The OpenFire proc appears to be the way ice demons handle teleportation as well as shooting. I have a feeling it might have something to do with SLEEP_CHECK_DEATH. Just a hunch though since I'm on mobile and don't want to track down the macro.

**Comment by LemonInTheDark** [comment]
`#define SLEEP_CHECK_DEATH(X) sleep(X); if(QDELETED(src) || stat == DEAD) return;`

**Comment by LemonInTheDark** [comment]
I doubt it's this, it's passed 8, so it should only be sleeping for 0.8 seconds

**Comment by optimumtact** [comment]
it's not the macro, it's the view call doing something unintended, but nobody can spot the issue right now, and it's hard to reproduce exact cause

**Comment by optimumtact** [comment]
it was users sentience potioning the demon
