### ISSUE TITLE
look_up hotkey as dead/new_player causes runtime

### ISSUE THREAD

**Issue by kriskog** [tgstation/tgstation#52442]
## Round ID:
[142617](https://scrubby.melonmesa.com/round/142617)

```
[16:03:23] Runtime in living.dm, line 40: undefined proc or verb /mob/dead/new_player/end look up(). 
proc name: up (/datum/keybinding/living/look_up/up)
usr: REALB/(REALB)
usr.loc: (start area (8,174,1))
src: look up (/datum/keybinding/living/look_up)
call stack:
look up (/datum/keybinding/living/look_up): up(REALB (/client))
REALB (/client): keyUp("L")
```

**Comment by ShizCalev** [comment]
https://github.com/tgstation/tgstation/blob/add74bee56cfde91602eb8ee28e3cae5959bc4f6/code/modules/keybindings/bindings_client.dm#L74-L94

https://github.com/tgstation/tgstation/blob/2f3e4fc696a5fdb3207d9d06e331a5949d1e972f/code/datums/keybinding/living.dm

pretty sure this should happen for anything that has a unique key_up(), since there's no check to see if key_down() was successful, or if the mob type has changed after keydown
