### ISSUE TITLE
Killing an AI that used to own the shell with the shell it used to own will ghost you as well.

### ISSUE THREAD

**Issue by ZeroMODE0** [tgstation/tgstation#52551]
## Round ID:
https://sb.atlantaned.space/rounds/142958

## Testmerges:
No test merges

## Reproduction:
Was roundstart station AI (Z3R0) And later on G.I.O was created. At the end of the round, he went SSD so I had an Engineer take his shell to robo to have the BORIS module taken out and put back in So I could claim it. Later on, as that shell, I killed his AI core and the moment his died, I was killed too. In the image, you can see his ghost as well as mine; We'd both died. In the round end report, it was shown that I played both G.I.O and Z3R0.  -- I think the game thought my shell belonged to G.I.O's AI core, and killing his AI core made it kill both of us, as well as the shell. (Z3R0 was still functional however, as though just using the shell!)
![image](https://user-images.githubusercontent.com/62538745/88631127-46754e80-d077-11ea-887e-4ab0fa78f0e8.png)

**Comment by ZeroMODE0** [comment]
Sorry if this is confusing! I don't post much and it was a very complex situation to begin with.
As Z3R0:
Took out GIO's shell modules> Put B.O.R.I.S. back in> Claimed shell> Killed G.I.O> Both of us died, Z3R0 is fine> ZeroMODE played both G.I.O and Z3R0?

**Comment by GunHog** [comment]
I am going to hazard a guess here and say that the soullink() from the previous AI did not get cleared, as soul-link is what returns the controlling AI to its own body instead of the cyborg. 

Basically, when you deploy your AI shell, you become the same as a normal borg, except that you are given AI radio, your laws are always synced, and that any damage or action taken against your core will return you. The intent behind this is to, lore-wise, give the idea that the AI is controlling the shell as if it were an FPV drone. The code reality is that your mind is transferred to the shell and you play as a borg until you return. 

Soullink(), the part of code that says "If the AI core dies while the player is in a shell, return the player to the core so it can die properly" may not be getting reset properly. When you killed the old AI, it seems that because the previous soullink was still there, it moved your mind to the old AI and killed you. I suspect that anything that killed the old AI would have had the same result.

**Comment by Dennok** [comment]
https://github.com/tgstation/tgstation/blob/f3997580d0da181f02095842b812a09338803f73/code/game/objects/items/robot/robot_upgrades.dm#L490-L512

Seems like 
https://github.com/tgstation/tgstation/blob/master/code/game/objects/items/robot/robot_upgrades.dm#L501
check don't give true when user offline

https://github.com/tgstation/tgstation/blob/b12fab6c092626bb76c5da819968261eeab6656b/code/modules/mob/living/silicon/robot/robot.dm#L967-L987

Seems like 
https://github.com/tgstation/tgstation/blob/b12fab6c092626bb76c5da819968261eeab6656b/code/modules/mob/living/silicon/robot/robot.dm#L969
mind check don't give true when user offline, so this shell cant be normally cleared.
