### ISSUE TITLE
Brew Master is uncool. (Naming doesn't work)

### ISSUE THREAD

**Issue by Vanadiom** [tgstation/tgstation#52561]
## Round ID:
143003
Any (Found 143003 )

## Testmerges:
None

## Reproduction:
1. Try to name a bottle in the BrewMaster.
2. Look at the bottle produced.
3. Nothing written about your magnificent product.
4. Make sad offbrand noises.

**Comment by Angustmeta** [comment]
I reported this in #51942. It apparently shouldn't even ask for a name.

**Comment by nightred** [comment]
The option to name should not exist and needs to be removed.

**Comment by MIK517** [comment]
If you think about removing it, then you should as well remove condibottle renaming with pen.
It (pen renaming) is also broken, as name (and description) changes back to auto-generated as soon as you drink a bit from container and cause reagent change.

I thought fixing it as my first PR (pretty much just applying almost the same code as in `drinkingglass` and toggling `renamedByPlayer` when naming through CondiMaster) but got some questions:
1) Is it even needed or all condi renaming should just be disabled completely?
2) Is it fine to override `update_icon` with 'nop' as is done in `/obj/item/reagent_containers/food/condiment/pack`? Overridden `/atom/proc/update_icon()` seems to send some signals, not sure how important they are.
3) Should renaming be moved from `update_icon` or it's fine to have non-icon changes there if they're related? Maybe it all (including icon change) just should be moved to `on_reagent_change` like in `drinkingglass` and `condiment/pack`?
4) Also, considering huge possible change in icon when changing reagents (like typical bottle to small salt shaker or flour pack), maybe rather than fully changing it on reagent change allow to set it on creation (like with pills)?
5) Also, should `renamedByPlayer` be reset when bottle is empty (like with `drinkingglass`) or not, considering bottles are (conceptually) more stable with their contents than drinking glasses?
