### ISSUE TITLE
Opening UIs prevnts the use of some keybinds (like the talk keybind)

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#52663]
## Round ID:

no specific round ID but it's happened in every round i've played in the past week, will update next time it happens (and no testmerges since they were all on manuel)

## Reproduction:

opening a UI like a vendor or the seed extractor and closing it stops the use of some keybinds for 10 or so seconds, for example some custom keybinds like emotes fail and T to talk doesn't work

to reproduce: open ui, try to talk, no say window opens, try to use custom binds, nothing happens
since i feel like it might be a byond version issue or something i'm on version 513.1526

**Comment by cyclowns** [comment]
i also encounter this issue. seems like it's only with TGUI stuff

**Comment by ATH1909** [comment]
Ah, THAT'S what's causing that.

Can we get a high priority label on this? It's SUPER annoying, and definitely affects common gameplay significantly (in a negative way).

**Comment by Fhaxaris** [comment]
It's because the main game windows is de-focused when the TGUI is opened. It breaks everything that is a function key or isn't a custom keybinding (Talk, OOC, Ahelp, and Screenshot). What's most annoying is that after you close the TGUI, it remains in focus and you have to click the main game window to return focus to it and fix everything.
