### ISSUE TITLE
Succumbing as an infectious zombie destroys your tumor and cures you

### ISSUE THREAD

**Issue by NoxVS** [tgstation/tgstation#52729]
If you are knocked into critical as a zombie and succumb to death rather than allow yourself to be killed, you will be cured. You will not come back to life and will instead be reverted back to your original race

Normal zombie deaths result in the corpse remaining the infectious zombie race, and eventually coming back to life.

Issue reported from  Round ID: [143547](https://scrubby.melonmesa.com/round/143547) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1526

**Comment by NoxVS** [comment]
Duplicate of #51601 but significantly more detailed to make it clear what the actual issue is

**Comment by ATH1909** [comment]
I thought the way it worked was that because infectious zombies have TRAIT_NODEATH, you can't actually "kill" them, they just remain in deepcrit and eventually regenerate. Presumably, succumbing somehow gets around this immunity to death and causes them to actually die, which in turn somehow results in the deletion of their tumor.

But hey, that's just a theory... a GAME theory.

**Comment by ExcessiveUseOfCobblestone** [comment]
the trait needs to c*ckblock succumbing.

**Comment by Fikou** [comment]
zombies did work correctly even when succumbing for like forever, my only guess at what might have broken it was that HARS pr, but not sure about that
