### ISSUE TITLE
Upgrading Autolathes Permits Creation Of Infinite Materials

### ISSUE THREAD

**Issue by Paxilmaniac** [tgstation/tgstation#52852]
## Reproduction:
Upgrading an autolathe reduces the amount of materials it takes to create an object, but when you recycle said object, it recycles to the same amount of materials as it took to make it unupgraded.
The biggest offender of this is foam riot dart boxes, which normally take 50000 metal to make, and when the autolathe is upgraded can go down to I think 30000.
Make a box of foam riot darts then recycle it, and now you have a 20000 iron profit, all for zero cost.
This applies to literally anything you can make in the autolathe.

**Comment by Paxilmaniac** [comment]
This also applies to upgraded recyclers, which means the process of making infinite materials can be semi-automated

**Comment by Kaffe-work** [comment]
Does this go for protlathes as well, or is is autolathe specific?

**Comment by Paxilmaniac** [comment]
Probably works with protolathes if you use a recycler

**Comment by Kaffe-work** [comment]
F U C K

**Comment by ArcaneMusic** [comment]
Sounds like the solution would be to make the custom material amount assigned to the object equal to it's highest upgraded value, but leave the lathe scaling alone, so it would still cost the 50000, but be worth only it's upgraded amount.

**Comment by WarlockD** [comment]
Found it.  Has to do with how the autolathe makes boxes of junk.  First off it never sets custom_materials when making an item.  It needs to do this every time it makes something, like the prolathe does, because that's how the material component figures out how something is deconstructed.  Secondly, and this applies to the prolathe as well, ammo boxes set the material usage of the ammo ON Initialize.  So calling set_custom_materials proc after that doesn't change the physical ammo itself.  So when its deconstructed, the box is set to the ENTIRE amount of materials when it was created AS WELL AS the bullets without any upgrades.  So even if the autolathe isn't upgraded, deconstructing an ammo box will always yield double.

Easy fix though.  Override set_custom_matierals on the ammo box and make the autolathe always set the custom materials.  I will pr it shortly.

**Comment by WarlockD** [comment]
Ok, ammo box is shit, why the fuck is it setting the custom_materials IN update_icon
