### ISSUE TITLE
Statis beds not receiving advanced surgeries from operating computers.

### ISSUE THREAD

**Issue by NaturesMayhem** [tgstation/tgstation#52885]
I encountered this issue in round multiple times, you'll make the stasis beds and then the operating computer last and you won't get any of the advanced surgeries that the operating computer is supposed to grant. The issue after a little testing was determined to be that if the stasis bed is placed down before the operating computer, you won't get the surgeries. However, if you place the operating computer first, and then the stasis bed, you will have access to the surgeries.

Steps to reproduce:

1. Create 2-8 stasis beds in a 3x3 cube, with the idea that the computer will be going in the center.
2. Create the operating computer in the center of the beds.
3. Make sure the beds have been constructed first, then the computer (if you did the computer first, it will function as intended and the surgeries will be available)
4. Make sure you have any advanced surgery unlocked via R&D.
5. Sync the operating computer with R&D so that the surgeries are established inside the computer.
6. Buckle a human to the bed and attempt to perform surgery on them.

By doing this you will find that you don't have access to the surgeries you had researched and can only do the first basic 7 that can be performed anywhere. This has the same functionality with operating tables as well, tables made via table frame and silver for surgery purposes, often found in medical. The sole exception to this rule may be that the computer established a connection with a single computer sometimes, it seemed that either the bed in front of the computer or behind the computer would gain the surgeries. However, the remaining 7 in the square would not. 

A summary of how this functions. If you make multiple stasis beds around a single operating computer, with the beds coming first and the computer second, you will only get surgeries on the first. You do the opposite, the computer first then the beds, you will have surgeries available on all of them.

**Comment by AU518987077** [comment]
can verify this report, issue was reproducible

**Comment by Timberpoes** [comment]
The Operating Computer syncs to only a single stasis bed or operating table, preferring an operating table first and if there is not one next to the computer, a stasis bed second.

The link is double - The operating computer links to the stasis bed, and the stasis bed links back to the operating computer.

The reason for this two-way link is because the operating computer only supports displaying surgery steps on a single person at a time. As a result, I wouldn't classify this as a bug, but more as an intended design decision.

The expected gameplay loop would appear to be a unique operating computer for each operating table and stasis bed and that appears to be what the system is designed to support.

**Comment by nightred** [comment]
Based on the the reproduction being one computer with multiple beds and the code does show that the design is one bed to one computer. This is as designed and not a bug.
