### ISSUE TITLE
Skillchips can't be removed from other people

### ISSUE THREAD

**Issue by Angustmeta** [tgstation/tgstation#52921]
### Reproduction 1:
* Spawn a station engineer next to the skillsoft station. 
* Spawn a different person and possess it. 
* Put engineer in skillstation and try to figure out a way to extract the skillchip. 

**Result:** The UI won't open. Clicking the skillstation will just toggle doors. 

### Reproduction 2:
* Remove the engineer's brain with organ manipulation: No skillchip pops out. 
* Amputate the engineer's head with surgery: No skillchip pops out. 
* Cut brain out of the engineer's severed head: No skillchip pops out. 

I don't know what the intended methods to steal skillchips are.

**Comment by Timberpoes** [comment]
@AnturK Care to chime in on if I've missed anything below?

Re #1:
The skill station was designed by AnturK and is to my knowledge self-use only; think of it this way - the controls to make the skill station work are on the inside of the pod instead of the outside, because it takes only 1 person to operate it. It can't be operated from the outside.

Re #2:
The skillchips are implanted within the brain; they're not like surgery-based implants. Think of them as closer to subdermal implants that require a different method to remove. Forcefully removing skill chips from another player involves taking a sharp object (such as a scalpel) direct to the brain, done after the brain has been removed from the skull.

**Comment by ShizCalev** [comment]
skillchips are extracted by attacking the brain with an edged weapon.

**Comment by AnturK** [comment]
Yes, the skill station being self-use only is intentional. You need to extract the brain and use sharp tool on it.
I'm not sure about adding manual removal/implanting surgery , the intent was to make these pretty hard to be stolen/messed with by third parties so they're reliable enough to be used for job advantages.

**Comment by Angustmeta** [comment]
I'll wikify this info
