### ISSUE TITLE
blind people can't tell how full they feel when eating

### ISSUE THREAD

**Issue by joybod** [tgstation/tgstation#52938]
Issue reported from  Round ID: [144262](https://scrubby.melonmesa.com/round/144262) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1527

this makes it a guessing game to tell if you are full yet as you can't stop when unwillingly eating

**Comment by MrMelbert** [comment]
this is because `visible_message` is used interchangeably between "things you see happening" and "things you feel happening". Same thing happened to blind people being unable to feel hugs a month back.

 the easy fix is to add some `to_chats` to the problem messages, while the more encompassing fix to stop this from happening in multiple places is to either add a `touch_message` or, say, a touch flag to `visible_message`s.

**Comment by Guestratem** [comment]
is this with the info messages you see in chat? or with something else

**Comment by joybod** [comment]
> is this with the info messages you see in chat? or with something else

yeah, the messages that usually say, for instance, you nibble the meat clown. the flavor I think still shows up but the other message fails to show. Also related is that, while blind, you can use an atmos analyzer on pipes but not use it on the environment(by using it in hand).
