### ISSUE TITLE
spell cards still don't home in on people

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#52946]
The spell's supposed to make a shotgun spray of cards that'll turn mid-flight to home in on people, but all it does currently is make a shotgun spray of shitty cards that don't home in on people. As such, the spell does basically jack shit to people unless you're only a tile or so away from them (and even then, the damage output of the spell cards is so poor that you need multiple "reloads"(/recastings) of the spell to kill someone at point blank range with it).

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/b79dd74fd0aef748a8e54c45402cebb3cd98e1c6/code/modules/spells/spell_types/aimed.dm#L135-L191

From looking at gitblame there doesn't seem to have been any fixes to this since this bug report and it likely still exists unless ATH messed something up when he tested it.
