### ISSUE TITLE
Core R&D Console DCs you if you try to open it.

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/tgstation#53124]
## Testmerges:
- #52413 
- #52998 

## Reproduction:
- Locate an affected console
- Try to open it
- Disconnect

Not every core R&D console is affected, but if one is that specific console will disconnect whoever tries to use it. On the linked round an admeme bombed the room with the console in it and while it was in the broken glass state I managed to open the interface without getting DCed.

**Comment by kopoba** [comment]
Happens to me and other crew during Round ID: 152955
I try 2 different consoles that we build in rnd both DC
You can unscrew screen and screw back and then you can access to console without DC but when you try click Technology on first screen of interface you get DC

**Comment by Sealed101** [comment]
that particular machine no longer exists as of [experisci](https://github.com/tgstation/tgstation/pull/54093), and the new research console has had a good bunch of attempts at making it less laggy, some of which are bound to have worked. either way, this issue is not applicable anymore

the round does have a good bit of runtimes over atoms taking damage after being destroyed but oh well
