### ISSUE TITLE
cyborgs can't set their headlamp to level 1 anymore

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#53351]
<img width="1440" alt="nolevelone" src="https://user-images.githubusercontent.com/42606352/91685053-ce3ef480-eb1e-11ea-928a-e9342df223d8.PNG">

It just gets skipped right over.

**Comment by GunHog** [comment]
Because of this:
https://github.com/tgstation/tgstation/blob/25287e0134873b8a0d94085e3111f0aa0e78cafb/code/modules/mob/living/silicon/robot/robot.dm#L544-L545

PR'ed in https://github.com/tgstation/tgstation/pull/52413

**Comment by zxaber** [comment]
For the record, I'm currently nearing completion of a bit of a revamp of borg UI, which includes axing the lamp button in favor of a TGUI control. The new system allows for setting of lamp color, with power usage based on how bright the color is (so you can effectively get a low setting by selecting a grey color).

Just so that someone doesn't spend too much time on a fix for this issue.

**Comment by nightred** [comment]
Looks like it is intended but not explaine.
If borgs use numbered light levels they should be able to use all of them, the light levels might need names so that you see low, mid, high not 0,2,3

**Comment by ATH1909** [comment]
Light level 1 does still have its uses, even if that's the default see-darkness range. Sure, _I_ might be able to see myself without a light, but that doesn't mean that other people in a dark room with me can.

**Comment by GunHog** [comment]
Please see https://github.com/tgstation/tgstation/pull/53373, as it includes both a fix and improvement (RGB BORGS!) for this issue. Also, light level 1's intended use is to make a borg visible to others in the dark at no energy cost. Also because borgs have accent lighting makes them look cool.

**Comment by zxaber** [comment]
This issue can be closed; borg tablets re-added light level 1 as an option.
