### ISSUE TITLE
Feedback around husks, lings, and reviving husks is generally poor/non-existent

### ISSUE THREAD

**Issue by msgerbs** [tgstation/tgstation#53580]
We spent some some time chatting on Discord about husks and the generally poor feedback around them. I'm going to be looking at improving this, but here's a general list of some of the issues identified in case anyone has any other issues or think these are dumb complaints:

- [x] Husks can only be identified visually. There is no examine text, nothing in health scanners, etc. It's bad thematically, because it should be utterly, blatantly obvious that somebody's been turned into a shriveled mess of a human being. 
- [x] Similarly, trying to defib a husk gives a generic message that doesn't tell you it's because they're a husk.
- [x] ~~Unhusking a ling husk silently fails with no indication given as to why. Again, it's thematically bad and it forces the player to rely on OOC knowledge to just know that "oh sythflesh failed, they're a ling husk". There's no reason that there can't be some sort of message here for this.~~ Decided not to touch this for the time being as there's no good way to do this without changing the flavor of synthflesh. Alternate solution was enhanced clarification on what husked them in the health scanner.
- [x] There is still a trait and proc for uncloneable status even though cloning is entirely removed and nothing else checks this trait.

**Comment by Timberpoes** [comment]
I fully agree on all points.

Some of the issues around husked corpses and revival trip up new players and experienced players alike from time to time.

I don't like the idea that players have to wiki dive to figure out why defibs aren't revive what would otherwise appear to be a pristine corpse and we have things such as health scanners and the defibs themselves which can provide good feedback to the user as to why they failed.

**Comment by Timberpoes** [comment]
Linky linky to #53599
