### ISSUE TITLE
Can't put .38 in .357 revolver?

### ISSUE THREAD

**Issue by JusticeGoat** [tgstation/tgstation#53639]
The .357 Magnum cartridge was literally designed as a high-pressure .38 Special its the same size why can't i put low pressure .38 in the normal syndicate revolver?

**Comment by Tumesuo** [comment]
because it's .38 not .357

**Comment by JusticeGoat** [comment]
> 
> 
> because it's .38 not .357

You're unable to read?

**Comment by Tumesuo** [comment]
It's a whole .013 size difference, of course, it's not going to fit??

**Comment by Tumesuo** [comment]
.38 special would wiggle around the barrel too much

**Comment by Tumesuo** [comment]
wouldn't fit*

**Comment by JusticeGoat** [comment]
> 
> 
> It's a whole .013 size difference, of course, it's not going to fit??

that's length of cartridge, while in a auto loading gun like a 1911 that would not work, a revolver its fine due to the way the rounds are contained.

**Comment by FreshestSoup** [comment]
The .357's I've fired IRL were capable of firing .38 special. In fact, they did.

**Comment by Tumesuo** [comment]
Must have been some fucking prototype guns or something because guns don't work like that.

**Comment by cyfause** [comment]
![image](https://user-images.githubusercontent.com/13970003/100448808-e02e2600-3080-11eb-89a6-9de9b0b89eda.png)
literally just admit you're wrong
and if it matters that much balance wise, just make up some bullshit and claim it's for balance reasons.
at this point you just want to be correct when clearly all evidence points against you

like just do a google search before you say shit LOL

**Comment by Tumesuo** [comment]
@cyfause google and stackexchange aren't a reliable source of information

**Comment by Fikou** [comment]
.38 special would wiggle around the barrel too much

**Comment by GreenTea988** [comment]
https://www.pewpewtactical.com/different-ammo-in-the-same-gun/#:~:text=But%20because%20the%20diameter%20of,less%20than%20that%20of%20a%20.&text=38%20Special%20round%20can%20be,Magnum%20revolver%20or%20lever%20gun.
https://www.ccwclasses.net/can-a-38-special-shoot-357-rounds/
https://forums.sherdog.com/threads/can-i-shoot-357-magnum-rounds-in-a-38-special-revolver.2614749/
Literally every source says basically, "You can, but you shouldn't" and yall are goofy for saying otherwise
