### ISSUE TITLE
Security camera range check is broken

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#53679]
Issue reported from  Round ID: [146219](https://scrubby.melonmesa.com/round/146219) (/tg/Station Manuel [ENGLISH] [US-WEST] [ROLEPLAY] [99% LAG FREE])

Reporting client version: 513.1528

The security camera console stops checking for range at around 7 tiles instead of one, which means as long as you're within seven tiles of the security camera console, you can see anything on the cameras.

**Comment by kopoba** [comment]
Seems logic to me. You can see TV from distance

**Comment by msgerbs** [comment]
This one's interesting... Normal tgui behavior is to stop updating the UI at 3+ tiles and close it at 6. But it looks like the camera view ignores the ui_state and just does it own thing. Without looking too into if I'm guessing it probably just embeds the old camera view rather than building anything new for tgui, and this isn't the only place I've notice some fuckiness with them (if you hit F5 to refresh the page, which happens a lot during debugging) it stops working.
