### ISSUE TITLE
Drop pods that are set to effectOrgans deal no damage and keep clothes on

### ISSUE THREAD

**Issue by Barhandar** [tgstation/tgstation#53710]
Issue reported from  Round ID: [146278](https://scrubby.melonmesa.com/round/146278) (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])
Reporting client version: 513.1532

Meaning that the dumbass - in the relevant round, RD who tried to send himself with the mech to mining via orbital mech drop pad - who gets _disassembled_ by the drop pod with full sensors on keeps showing up in crew monitor as perfectly healthy (or as healthy as they were).

A more general issue is that lacking all organs and limbs reads as 0 damage, due to damage being separate thing.

P.S. Oh by the way this means you can harvest someone for organs (or debrain them!) much faster and easier on station without needing to build an organ harvester.

**Comment by msgerbs** [comment]
Quick fix here is to set it to do additional damage besides just throwing their organs everywhere. Better fix is to... somewhat make missing organs show damage even it technically isn't? idk

**Comment by Barhandar** [comment]
I mean, if you lack relevant organs and are alive it gives you damage, this just skips that because it kills instantly and completely. Species that have to breathe probably should show some arbitrary minimum oxyloss (or, for example, an exclamation mark next to damage) if they're missing lungs, brute if heart, toxin if liver, etc.

**Comment by timothymtorres** [comment]
@Barhandar missing or damaged organs has never shown up in the crew vitals monitor.  It doesn't make any sense either to show it.  Surgically removing your eyes or amputating a limb still results in perfect health and it should be that way.  It'd be like if the monitor could show viruses that the crew has.  Basically it boils down to balance.  The medical scanner is supposed to show a full diagnosis readout.  The crew vital monitor is not.  Examining another player shouldn't reveal too much medical issues as well.  Now it would be cool if there was some type of R&D upgrade to make medical monitors show the above.

Although I will say that a drop pod instagibbing a mob with healthy organs sounds like an exploit.

**Comment by Sealed101** [comment]
this report is kinda confusing since the actual(i think?) issue is crew monitor showing a dead and delimbed corpse as "healthy" - which is not the case currently; the death symbol shows correctly, and _some_ damage is being dealt by the organ removal process, probably the limb loss to be exact, so i suppose the issue is resolved? 
![изображение](https://github.com/user-attachments/assets/f2d65512-1709-4654-8241-ac893c75443c)

in any case the pod's `effectOrgans` doesn't seem to be intended for anything besides removing organs; the _"body"_ of the character receives no special treatment, and clothes are kept on as expected.
https://github.com/tgstation/tgstation/blob/5744c93f08b73f18ae548d08ed65a4af0effbc7f/code/modules/cargo/supplypod.dm#L320-L334
