### ISSUE TITLE
Meat Cutlet is larger than serving tray , Meat Cutlet cooks in the oven and gets duped.

### ISSUE THREAD

**Issue by Fishimun** [tgstation/tgstation#54134]
Issue reported from  Round ID: [147448](https://scrubby.melonmesa.com/round/147448) (/tg/Station - Terry [EU] [100% LAG FREE])

Reporting client version: 513.1507
Can't put Normal Sized raw meat cutlets into a bulky serving tray.
I just cooked 6 meat cutlets and it gave me 6 raw cutlets and 6 cooked ones.
Edit: Can't put meat cutlet on pizza bread

**Comment by Owai-Seek** [comment]
Similar issue, noticed on a downstream.

Most food items cannot be placed on a tray.

Possible Issue? Serving trays have no `STR.set_holdable` variable on them. I'm still getting up to date on current TG code, however.

Items that -have- worked on a tray.
- Flour, Rice, Sugar Sack
- Several Donk Pocket varieties.
- Enzyme Bottle
- Beakers
- Mint
- Soy and Space Milk
- Condiment Packs
- Salt/Pepper Shakers

Items that -have not- worked on a tray.
- Raw Meat/Cutlets
- Cooked Meat/Cutlets
- Raw or Cooked Eggs
- Banana Cream Pie

**Comment by nightred** [comment]
@Qustinnus Looks like something broke that you touched.

**Comment by ArcaneMusic** [comment]
It seems the meat duplication issue has been resolved previously, as microwaving cutlets appears to be working correctly yet again.
From floyd:
Custom pizza crafting has been nixed by design for the time being until the food refactor has been finished, due to the branching typepaths on food/snack/whaever versus just "foods".
