### ISSUE TITLE
Station blueprints room creation not working 

### ISSUE THREAD

**Issue by R3nn0c** [tgstation/tgstation#54190]
## Reproduction:

I was trying to make an expansion on to the station above arrivals on meta station where there is that big open area with metal and stuff. Anyway I fill that entire area with floor tiles and put walls all around it when I try to use the station blueprints to signify it as a new room it only changes 1 or 2 tiles to the room not the whole area.
I have no clue if I’m doing something wrong or if it’s a bug.
Please let me know.

**Comment by TheOneAndMightyRed** [comment]
Similar thing happened to me but on lavaland. Tried making a outbent 5x5 gas farm on lavaland and tried to designate the room for a gas farm. 
https://i.imgur.com/r4Ui1SX.png
I was in the middle of deconstructing the walls when a storm hit and then realized that only a small fraction actually got designated instead of everything i had planned to.

**Comment by Dennok** [comment]
<details>

![image](https://user-images.githubusercontent.com/7734424/95100585-eddac580-0739-11eb-892c-4f8b52a55546.png)

</details>

**Comment by R3nn0c** [comment]
Thank you Dennok your the best :)
