### ISSUE TITLE
Hydroponics trays treat water as nutrient when pumped in through ducts

### ISSUE THREAD

**Issue by FelineEsquire** [tgstation/tgstation#54226]
If you pump Water into a Hydroponics Tray using fluid ducts from a synthesizer you can see that the water fills up nutrient space, but then empties into the water space whenever the plant ages, this makes fertilizing the plants with the chemicals you want hard if you have a plumbing system set up to keep them all watered

**Comment by brotherbeyondd** [comment]
It also does that if the water is full I believe when using a beaker?

**Comment by ArcaneMusic** [comment]
So, this was the case when it was added to the waterworks/shower plumbing PR, and better handling of how water is handled turned out to be rather difficult with the current plumbing/reagent implementation.
Ideally it'd just count as a constant application of `adjustWater` with a self-removal of the water reagent, but for the life of me I couldn't find a clean implementation for it.

**Comment by TemporalOroboros** [comment]
Override on_reagent_change for the tray and have it convert whatever water's in the tray into the nutrient water?

**Comment by ArcaneMusic** [comment]
I recall trying that, but I recall there was some kind of issue involving implementing it like that.

**Comment by msgerbs** [comment]
Maybe it should be changed to just use an internal tank rather than special "water/nutrient" values and have the plant consume reagents from the tank as it grows. This would also open the door for plants that don't consume water/nutrient and consume other reagents instead or even create reagents in their tray instead (which could then be piped out to other trays)

**Comment by ArcaneMusic** [comment]
ALRIGHT, here is the full reason that this is still occuring:

> Reagents in trays proc on_hydroponics_apply once every hydroponics tick, which is the machine tick, so every 5 seconds. When THERE, water is removed from the nutrient reagent tank and the quantity added to the water_level value on the tray, but it's not done instantly as we'd expect, because right now it's being processed from /datum/reagent/water/on_hydroponics_apply -> /obj/machinery/hydroponics/proc/apply_chemicals, which implements both a time delay as well as prevents the water from being instantly removed.

**Comment by MrStonedOne** [comment]
This is the kind of thing to best look at in IC terms if you want to solve it.

Input from ducts should go into its own reagent store, with a tgui interface for the operator to control if it then goes into a small reagent store of nutrients to be placed into the main water over time (like a drip feeder), or into the main water tank.

ie, trays need 3 reagent containers and tgui interface pages to control how they move reagents around.
