### ISSUE TITLE
Mobility Refactor bug

### ISSUE THREAD

**Issue by wabash1** [tgstation/tgstation#54545]
Mobility refactor bug possibly related to https://github.com/tgstation/tgstation/pull/54078
## Testmerges:
#54483: 'Shuttle Takeoff/Landing Animations' by Cyberboss at commit 818d43b75b
#54517: 'fix fix chat' by actioninja at commit 9dd0d3d4f3
#52493: 'LINDA Atmos: Reforged and associated fixes/changes' by LemonInTheDark at commit 1dc4d637f2

## Reproduction:

Pick up clown with aggressive grab while he wears PDA and shoes, use help intent, try to slip people. it does not work anymore. (I  believe this was a feature it was the funniest shit.)

**Comment by wabash1** [comment]
@Rohesie 
Do you believe this bug is related to the refactor?

**Comment by Rohesie** [comment]
This was a bug and the mobility refactor fixed it. Guess I forgot to document it.

The clown would slip people because the check was whether they were rotated to 90 or 270 degrees, which would be assumed to mean they were on the ground. That caused the fireman-carry to slip people.

Now the check is more clear.
