### ISSUE TITLE
Syndicate Tomes turn you into a chaplain. As in, makes you Holy.

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#54856]
The relevant code:

```
/obj/item/storage/book/bible/syndicate/attack_self(mob/living/carbon/human/H)
	if (uses)
		H.mind.holy_role = HOLY_ROLE_PRIEST
		uses -= 1
		to_chat(H, "<span class='userdanger'>You try to open the book AND IT BITES YOU!</span>")
		playsound(src.loc, 'sound/effects/snap.ogg', 50, TRUE)
		H.apply_damage(5, BRUTE, pick(BODY_ZONE_L_ARM, BODY_ZONE_R_ARM))
		to_chat(H, "<span class='notice'>Your name appears on the inside cover, in blood.</span>")
		var/ownername = H.real_name
		desc += "<span class='warning'>The name [ownername] is written in blood inside the cover.</span>"
```

And take note of this bit: ```H.mind.holy_role = HOLY_ROLE_PRIEST```

This means several things, because of the hacky nature in which this super bible works.

**1) You can do all the normal chaplain things.**

You can make holy water with your tome, you can turn other bibles into Syndicate Tomes, you can reskin the null rod, use the chaplain beacon, use the chaplain's soul stone, create a sect and even use normal bibles to heal people instead of your special super version.

**2) You cannot be converted to cult.**

You can now fill in the role of the chaplain in cult rounds by using the Syndicate Tome and doing all his chaplain things for him. He's not special anymore, any syndicate agent can become him.

But as a result, you can prevent cultists from being able to convert you into a cultist yourself even without a mindshield implant thanks to the tome. If that is a good thing or not is entirely up for debate.

**3) This lets you get access to Holy Water without even needing a chaplain present or interacting with botany.**

This is useful. For shenanigans. Like hostile life grenades. But also just having access to Strange Reagent as a whole. You also heal from Trappist Beer.

**Is this a feature or just a result of shit code?**

I don't know but it's pretty funny. Please vote rocket for feature or thumbs down for shitcode that should be refactored.

**Comment by brotherbeyondd** [comment]
feature shutu p!1!

**Comment by Dorsisdwarf** [comment]
Looks like a feature to me.

**Comment by Ghommie** [comment]
Most of these things are pretty tame, but I believe holy roles need to use into the trait system for convenience.

**Comment by ATH1909** [comment]
> use the chaplain's soul stone

Can't most crew members do that anyway?

**Comment by Ghommie** [comment]
Someone remember me to PR this branch https://github.com/tgstation/tgstation/compare/master...Ghommie:Ghommie-tg45 when november is over, thanks. :pensive:

**Comment by tmtmtl30** [comment]
I dislike this. First of all, it's clearly not really the intended functionality, as it's not mentioned in the item's description in the uplink (it's even mentioned as being inferior, see "Though lacking the esoteric abilities of the originals, these inferior copies are still quite useful".)

Since this is unintentional, this throws the balance of everything involving holy_role into shit. Not being able to be converted into a cult is non-trivial now that dynamic is a common fixture. You can tell who has the syndicate tome based on their examine text using the empath quirk. Instead of being gated behind the chaplain (i.e., requiring social interaction, the _backbone_ of SS13) or botany, holy water is gated behind 5 tc, meaning that so, too, is every chemical involving it, and the ability to deconvert cultists. 

"Chaplains aren't THAT special," perhaps, but their special abilities are also the only thing the role has to itself. They are THE unique selling point of being a chaplain. Handing them out to traitors makes playing as a chaplain way less unique; you essentially get a single 5 tc traitor item. That's boring!

Aside from that, it also makes the associated abilities way less _interesting_, in a way that doesn't really fit. SS13 is a pile of tropes, and the chaplain's abilities are an example of that. The chaplain gains his abilities from the force of his faith, or his status as an ordained priest, or (whatever you want to roleplay it as). That's _cool_, and it makes playing as a chaplain and resisting the evil of a blood cult cool. With this, that's no longer the case. It can't be -- what sense does it make that the chaplain gains his powers from anything remotely related to his faith, if Terrorist James Bond's book-with-teeth can hand out those same powers? It makes the trope that the chaplain's abilities rely upon fundamentally unsatisfying, cheapening the same powers that this book (again, seemingly unintentionally) hands out. It's so much more _boring_ this way.

**Comment by necromanceranne** [comment]
It's also really silly to be able to just run around bapping bibles into syndicate tomes.
