### ISSUE TITLE
Whispering with the Memento Mori equipped kills you while in crit.

### ISSUE THREAD

**Issue by Izzy513** [tgstation/tgstation#55008]
Issue reported from  Round ID: [150457](https://scrubby.melonmesa.com/round/150457) (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])

Reporting client version: 513.1536

I had an Issue where whispering to my Power Miner while in crit with the Memento Mori equipped killed me while he was dragging me to the station, unsure if this is intended or not but on the Shaft Miner wiki page it doesn't state anything about the Memento Mori being able to do this.

**Comment by cacogen** [comment]
If you whisper in crit you succumb with last words

**Comment by necromanceranne** [comment]
It is a bug. Memento Mori is meant to prevent literally any death except the ones that just straight up bypass anything that normally prevents deaths by hard deleting your mob, like explosions and the incincerator. Even if you lack a heart or ran out of blood, the memento mori will save you. This is supposed to also be a double edged sword because it would call a return on anything that would kill you, so succumbing is supposed to be impossible.

If you'd rather not accept it as a bug, then it's a consistency issue.

**Comment by Taylorkills2** [comment]
Well this is kinda how momento mori used to work.
Momento mori used to let you succumb and even do your last whisper. Though to die via a whisper you needed a fuckton of damage and that might have been a big in itself.
It was changed to specifically prevent succumbing in any way. Only for lore/ooc punishment for using it. (Though it fixed a bug that would let you die and not ash yourself)
Since the PR didn't want succumbing in any way this at least unintentional.
This could also let you succumb without dusting again.

**Comment by necromanceranne** [comment]
Oh if it isn't dusting you when you succumb this is strictly a bug, FYI. I've not tested it myself.

**Comment by Taylorkills2** [comment]
> Oh if it isn't dusting you when you succumb this is strictly a bug, FYI. I've not tested it myself.

I tested it, if you completely bleed out, you can die using momento mori and not be dusted. Although if momento mori is removed afterwards you'll be dusted.
