### ISSUE TITLE
Plasma in Lightbulb can be injected endlessly

### ISSUE THREAD

**Issue by Mirino97** [tgstation/tgstation#55071]
Injecting Plasma into lightbulbs behaves weirdly. You can inject an infinite amount, while the explosion by itself seems to be capped at 5 or 10 units of Plasma. It still explodes normally, just seems weaker than it should, but I understand why this would be coded to have a very low maxcap.

Other things that accept plasma injection have a max you can inject, while lightbulbs seem infinite. I tried with 400u on a private server and the explosion still seemed the same.

When injecting, the syringe injects all it's contents, instead of asking you to click 3 times if the syringe is set to inject only 5u. It gets suck on "Inject", forcing you to activate it in hand to change it's mode manually, when it's normal operation is to change as soon as it's empties itself.

## Round ID:

N/A

## Testmerges:

N/A

## Reproduction:

1: Grind Plasma
2: Fill a syringe with Plasma
3: Grab a lightbulb from the socket
4: Inject the lightbulb
5: Repeat endlesly

**Comment by MrMelbert** [comment]
https://github.com/tgstation/tgstation/blob/f84020850c30f06c05df62bf4c8c38ca907db038/code/modules/power/lighting.dm#L884-L898

relevant code. the syringe only ever checks if you have 5u of plasma, and if you do, it rigs the cell to explode and clears the syringe of its contents. Adding more plasma wouldn't do anything because you only need 5u to rig it once.

looks like a simple enough fix for anyone looking for an easy issue to close.
