### ISSUE TITLE
Temperature on icebox seems to ignore miner exosuit and potentially many more

### ISSUE THREAD

**Issue by Sparkezel** [tgstation/tgstation#55178]
## Round ID: 
////////

## Testmerges:
////////

## Reproduction:
Step into the ice wastelands with your armor on
Get slowed down and die to demonic watchers

Since the temperature rework got merged, mining on icebox got much tougher and you need atleast few cups of coffee or temp stabilising meds to not slow down and die to fauna/cold.

**Comment by ATH1909** [comment]
goddamnit nightred

**Comment by nightred** [comment]
looking in to this.

**Comment by timothymtorres** [comment]
Not a bug.

This is how hardsuits behave. They keep their internal temperatures insulated from outside temperatures.  This has the unfortunate effect that if your character is burning up or freezing they are stuck at this temp until you remove the hardsuit.  Something like a changling cryo sting is fatal to anyone in a hardsuit because their bodies don't warm back up.
