### ISSUE TITLE
Voice of god nearing spam filter

### ISSUE THREAD

**Issue by FlamingCheese** [tgstation/tgstation#55392]
Reporting client version: 513.1536

## Round ID:
[151710](https://scrubby.melonmesa.com/round/151710)

## Testmerges:
Testmerge is not the cause of the issue

## Reproduction:

I got voice of god once from a lobotomy, from bwoinks the admin said that voice of god was repeating "YOU. STOP." and that was nearing the spam filter, not sure if i got muted by the spam limit

**Comment by dragomagol** [comment]
I have heard of this issue before, but was unable to reproduce it

**Comment by dragomagol** [comment]
Probably the same thing as #45241

**Comment by Jared-Fogle** [comment]
has happened to me before

**Comment by YPOQ** [comment]
I think this may be because of the `can_speak` call here https://github.com/tgstation/tgstation/blob/cbbb6ea4484e9605647478f28c556271057dfb58/code/modules/surgery/organs/vocal_cords.dm#L129 eventually calling https://github.com/tgstation/tgstation/blob/0eaab0bc542ddb081556e11dd9d8dee75d077bce/code/modules/client/client_procs.dm#L147 with a null `message` which triggers the repeated message filter if done enough times.
Normally this doesn't matter because the `say` call a few lines down passes the right message arg but if you're in crit this won't be reached.
