### ISSUE TITLE
you "dive out of the way" of medibots

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#55438]
what used only to be implemented in clownbots and beepsky is now being applied to medibots, if you walk into a medibot path u get stunned

**Comment by timothymtorres** [comment]
So I code dived with git blame during, before, and after this issue to see if I could find any funky code.  It turns out that honkbots, and beepsky both had this "dive out of the way" code at some point.  Beepsky appears to have had this code reverted at some point since that code behavior doesn't seem to exist anymore.  I also dug around the files for bot, medibots, and simple_mobs and there is none of this behavior that I could find anywhere.  It was odd that this issue is the only one I've seen talking about this behavior with medibots.  If this was really the case, there would be a massive uproar over bot behavior and a lot more complaints and bug reports on this.

What I suspect actually happened is #44156.  The medibot is a big sprite and other bots tend to clump up together.  Beepsky was probably underneath the bot when you walked past and got thrown to the ground.

**Comment by timothymtorres** [comment]
@Tlaltecuhtli if you are still having this behavior feel free to ping me and I will reopen this.
