### ISSUE TITLE
Borgs have a Kilo execution access workaround

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#55477]
## Reproduction:
Borgs can't open the execution (Justice something) doors as expected with the menu or hotkeys, but can use the buttons to unbolt them anyway.

**Comment by zxaber** [comment]
So borgs can use CTRL-click to unbolt the execution door? Or do you mean the bolt button in the airlock UI?

Is this actually limited to just Kilo? A bug like this sounds airlock code missing a check, and thus would occur on all maps.

**Comment by dragomagol** [comment]
I wasn't able to use the UI or hotkey to unbolt it, but I was able to use these buttons here: 
![image](https://user-images.githubusercontent.com/66640614/102261627-cbe28980-3ec6-11eb-9ca8-d1c9ca44fb9a.png)

**Comment by Ewwmewgewd** [comment]
Security door remote also doesn't work on these two doors.

**Comment by zxaber** [comment]
Oh, the wall buttons? Yeah, I doubt there's any code existing to prevent silicon use, as borgs otherwise are supposed to have access to everything. Giving buttons wires that include AI control and then preventing silicons from using the button with that wire cut would be a good solution. Like the execution door itself, you'd just need a button child type with a pre-cut AI control wire.

**Comment by Ewwmewgewd** [comment]
This doesn't seem like a bug and it doesn't only happen on Kilo. All execution room doors on all maps have this variable set to 1:
![image](https://user-images.githubusercontent.com/60656530/102679342-73a1d500-41af-11eb-814c-7bf198f0391c.png)
I guess this is to prevent AI from trying to prevent human harm in the execution room?
