### ISSUE TITLE
water from any source cleans stuff

### ISSUE THREAD

**Issue by Fikou** [tgstation/tgstation#55498]
## Reproduction:

see slaughter demon
see a blood source and message about blood bubblin
use extinguisher on the tile
its cleaned
realize the janitor is now a completely useless job
cry

**Comment by cacogen** [comment]
I wasn't sure if it was a bug or an intended side-effect of some other change. I like using this as a cargo tech or the QM in lieu of spending points on a janitorial supply crate or the janitor existing and getting around to cleaning cargo amidst the rest of the station's stains and trash.

Either way, you could give every department a space cleaner bottle roundstart and the janitor would never be out of trash and stains to clean up.

**Comment by Mickyan** [comment]
I believe this may have been caused by this refactor https://github.com/tgstation/tgstation/pull/52477

As it stands most of the janitor's tools are outclassed by stuff like extinguishers and damp rags

**Comment by Owai-Seek** [comment]
You don't even need to spend points on a janitorial supply crate, you can print mops/buckets/brooms, or make soap with liquid gibs (ask the chef, or grind up some mice.)

It basically makes all of that irrelevant because you can just, ask cargo to print an extinguisher for 10 use hallway wide space cleaner bottles from the autolathe.

**Comment by cacogen** [comment]
Mops suck. Extinguishers as they function now aren't as good as space cleaner. And even with extinguishers as they are now there's still too many stains on the station for the janitors to stay on top of, not to mention rubbish and broken lights. This bug is a boon to balance not a detriment.

**Comment by Owai-Seek** [comment]
This isn't a boon, this allows literally anyone to clean anything with access to an autolathe or extinguisher closet.

What's the point of Mops?
What's the point of Space Cleaner?
What's the point of Advanced Sanitation?
What's the point of Cleaning Grenades?

It also means that fire extinguishers -constantly- get used up to clean shit, and the wall lockers remain empty.

This needs fixed, or fire extinguishers need a new reagent.

People should request janitorial, or order cleaning supplies, but instead they go to the nearest extinguisher cabinet, or fire locker, and leave them half-empty on the floor.

**Comment by cacogen** [comment]
Mops are shit tools for players to have to clean as many tiles as they do so that's a good question.

As someone who cleans cargo each round, resorting to the fire extinguisher only if I haven't ordered a janitorial supply crate, this doesn't remove the usefulness of space cleaner and certainly not of cleaning grenades.

Advanced sanitation unlocks more than just the advanced mop.

I always refill the cargo extinguishers myself before returning them to the cabinets in case somebody catches fire. I know that other players won't do this especially not without a water tank within sight but I don't really see it as being an important or widespread issue.

Also fuck, if people are having to resort to using fire extinguishers to clean because the janitors are absent or it continues to be entirely unreasonable to expect them to stay on top of mess with the tools provided and their only other option is to drop everything and spend a non-trivial amount of time trying to get a crate through cargo doesn't that indicate something needs to be done to make cleaning tools more readily available to the people who need them and/or that janitors need to be able to clean much faster?

I remember reporting welding fuel cleaning as being unintended functionality janitors were using to get around slipping people back in like 2012/2013 probably and being unhappy when it was fixed but no attempts were made to examine why it was being used or to fix the endless tedium of being a janitor that incentivises getting borged even while trash is still incredibly slow going for them. This is a similar situation where it's a harmless bug/unintended feature that's proven to be a useful measure for players against lacking game design no one feels able or willing to address. Fixing this without doing anything to make cleaning more accessible to the crew and/or faster for the janitor is only fixing a symptom of the problem because it affects you.

Anyway this was an odd thing to write a think piece about on my phone at 1:30 in the morning but this is one of the long-standing issues I have with the game like the infeasibility of rebuilding after a bombing and it seems other people can't even recognise the problem let alone take measures to solve it. Maybe I'm misguided for wanting to be able to keep every tile on the station clean for as long as possible instead of just mopping the same subset of bloodstained tiles endlessly but isn't that what janitors do? It has never been feasible to stay on top of stains and trash no matter the effort on behalf of the player, which is setting players up to fail.
