### ISSUE TITLE
xenobio is nearly impossible to do normally now because of the monkey AI changes

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#55776]
![image](https://user-images.githubusercontent.com/42606352/103182564-df500600-4871-11eb-92ca-2f4e2b3b9cd3.png)

**Comment by kopoba** [comment]
https://github.com/tgstation/tgstation/pull/55238 this was a mistake. Also humanized monkey are magicians that can get out from locked DNA scanner if they have target and nothing can stop them even death

**Comment by interestingusernam3** [comment]
Money Smart

**Comment by interestingusernam3** [comment]
Managed to reproduce the thing with directional windows in all the following situations:
- Monkey surrounded by windows on same time
- Monkey surrounded by windows on surrounding tiles
- Monkey able to move, but unable to reach player due to windows on monkey's side
- Monkey able to move, but unable to reach player due to windows on player's side
- Monkey surrounded by non-directional windows on 4 cardinals, player standing in corner

**Comment by redguy999** [comment]
I'd say the easiest way to fix this is add injectors to each camber (BZ camber already has one), a port with an N2O canister and connect those injectors to the new gas port.

**Comment by necromanceranne** [comment]
You should probably address this when you can @Qustinnus and also https://github.com/tgstation/tgstation/issues/56559

**Comment by Qustinnus** [comment]
This was resolved a while back
