### ISSUE TITLE
Directional lighting illuminates machinery you shouldn't be able to see

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#55793]
## Reproduction:
![image](https://user-images.githubusercontent.com/66640614/103250042-db31f000-4926-11eb-8b89-944d00ee615a.png)
The person in the other room had a flashlight, and when they went by I could see the intercom etc.

**Comment by timothymtorres** [comment]
#36527
#55793
#47841

Are all duplicates and this behaviour is intended.  This is a mapping effect that happens when you place a wall-mounted object on a tile and then offset by pixel x/y.  So if you can send the tile it was placed on, you can also see the object that was offset regardless of if it is on another tile or not.
