### ISSUE TITLE
roundstart plasteel is kinda buggy now?

### ISSUE THREAD

**Issue by Tlaltecuhtli** [tgstation/tgstation#55944]
i tried to put plasteel from auxbase to protolathe and it said <<< this thing contains no materials >>> or something like that, printing plasteel and putting it back works fine
153539
maybe caused by this https://github.com/tgstation/tgstation/pull/55296

**Comment by rdragan** [comment]
Actually seems to happen with any material, round start or not.

**Comment by Tlaltecuhtli** [comment]
also the protolathe material list wasnt set right, it had uranium and other minerals on top instead of the usual metal, glass etc

**Comment by Tlaltecuhtli** [comment]
can this shit be untestmerged? kinda game breaking.............

**Comment by Pugie** [comment]
Yeah this is really really really awful

**Comment by TemporalOroboros** [comment]
Should be fixed in around 10 minutes.

**Comment by TemporalOroboros** [comment]
@Tlaltecuhtli @Pugie @rdragan Should be fixed in ~10 minutes. Testing a fix now.

**Comment by TemporalOroboros** [comment]
Fix has been pushed, and has passed the linter. It should be fixed the next time Terry updates.

**Comment by Pugie** [comment]
still broken

**Comment by TemporalOroboros** [comment]
@Pugie The fix is on github, but apparently not on the servers. I'm poking the people with the power to update the TM. In the meantime, this should only effect machines connected to the silo and materials not already in the silo. Desync them or find a way to get the mats into the silo otherwise and they should work fine. In the first case you're going to need to port around the mats by hand though.

**Comment by nightred** [comment]
@TemporalOroboros what is the pr that you are referring to?

**Comment by dragomagol** [comment]
Appears to have been fixed
