### ISSUE TITLE
Nar Nar acts as a singularity

### ISSUE THREAD

**Issue by TheSilverNuke** [tgstation/tgstation#56077]
Reporting client version: 513.1526

## Round ID:
[153924](https://scrubby.melonmesa.com/round/153924)

## Testmerges:
- [[DNM] Revert move type refactor, fixing the constant server crashes](https://www.github.com/tgstation/tgstation/pull/55913)
- [15.ai VOX: Say the pickle rick meme, but as any voice!](https://www.github.com/tgstation/tgstation/pull/55626)

## Reproduction:

Nar'Sie was summoned in xenobio, and was dragging around walls, grills, and other static objects as a singularity might. Reproduction? Summon in xenobio on Icebox.

![2021-01-09 20_43_11-Window](https://user-images.githubusercontent.com/36066032/104113877-58604c00-52bb-11eb-9073-76e1116853f3.png)

**Comment by Jared-Fogle** [comment]
It's because of these usages of singularity_pull:

https://github.com/tgstation/tgstation/blob/master/code/datums/components/singularity.dm#L176

This should probably be made into its own callback, which Nar'Sie would then pass as none.

**Comment by LemonInTheDark** [comment]
I hate admins

**Comment by interestingusernam3** [comment]
Tested locally without the testmerges, on icebox and metastation, and failed to reproduce.

**Comment by interestingusernam3** [comment]
>It's because of these usages of singularity_pull:

>https://github.com/tgstation/tgstation/blob/master/code/datums/components/singularity.dm#L176

>This should probably be made into its own callback, which Nar'Sie would then pass as none.

Narsie has a consume range higher than the grav pull, this should prevent singularity_pull from running and seems to do so.

**Comment by Jared-Fogle** [comment]
That's probably true, actually. I'm not sure then.

**Comment by interestingusernam3** [comment]
I'm almost sure this was caused by admin fuckery or a cosmic ray.

**Comment by TheSilverNuke** [comment]
Round 155218. Issue occurred again on Delta where Nar Nar would pull tiles and destroy things.

**Comment by JJRcop** [comment]
https://github.com/tgstation/tgstation/blob/160c89903d45e8dde2657324b28161cb688d5bea/code/modules/power/singularity/narsie.dm#L3
https://github.com/tgstation/tgstation/blob/160c89903d45e8dde2657324b28161cb688d5bea/code/modules/power/singularity/narsie.dm#L50

![cursedthink](https://user-images.githubusercontent.com/5211576/111521574-ab2d0880-872f-11eb-8a6c-4ae8fb44ea99.png)

**Comment by JJRcop** [comment]
https://github.com/tgstation/tgstation/blob/160c89903d45e8dde2657324b28161cb688d5bea/code/modules/power/singularity/narsie.dm#L30-L32

https://github.com/tgstation/tgstation/blob/160c89903d45e8dde2657324b28161cb688d5bea/code/modules/power/singularity/narsie.dm#L44-L45

![cursedthink](https://user-images.githubusercontent.com/5211576/111521574-ab2d0880-872f-11eb-8a6c-4ae8fb44ea99.png)

Nar\'Sie acts like a singularity because she is a singularity internally. The singularity component doesn't actually support consuming objects without pulling too. Nar\`Sie's `consume_range` is larger than her `grav_pull`, but those extra 2 tiles are never actually counted, because the singularity component will only ever check objects inside the `grav_pull` range. It was made to support the singularity, and assumes `grav_pull` will always be larger or equal to `consume_range`.

**Comment by Mothblocks** [comment]
I'm the one that wrote the singularity component, and Nar'Sie should not be pulling anything in them.

**Comment by JJRcop** [comment]
Well, it looks like the component needs to be reviewed again, because the way I see it, it will either pull things or not consume anything.

**Comment by SethLafuente** [comment]
Narsie no longer pulls things to them as most people that play the game to this day have seen while playing cult

**Comment by Mothblocks** [comment]
We've had no reproduction of this so I'll just mark this as fixed
