### ISSUE TITLE
Digitigrades are immune to leg paralysis

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#56141]
## Reproduction:

Separated this issue from #56076 .

Digitigrade Lizards, are immune to having either or both their legs disabled via brain trauma. This includes from the roundstart paraplegic quirk (Free +2 points for digi lizards, wowee)

**Comment by Manybones** [comment]
I should add my insights on the problem if anyone wants to do it. For the record, the paralysis traits doesn't work on any non-human limb, this includes monkeys and such. 
The problem resides in that paralysis code only adds the register signal for the traits on the proc set_owner. This proc gets called when limbs are created with the proc create_bodyparts. This works as expected in totally normal humans BUT non human limbs are not created this way. If the proc for creating carbon/human detects they are creating a diferent species, the proc searchs for special limbs that species may use, and replaces the normal human part with the kink one. This isn't done with the create_bodyparts proc (i think) and such, it doesn't call the set_owner proc.
I would have fixed it myself but Im not very knowledgeable in DM code yet and species code is very weird. Honestly, It would be better to rewritte paralysis code to prevent future bugs due to excess of elongated pasta.
