### ISSUE TITLE
the "blast cannon" traitor item creates infinite looping much-stronger-than-rods rods

### ISSUE THREAD

**Issue by Serxule** [tgstation/tgstation#56355]
Round ID: [154804](https://scrubby.melonmesa.com/round/154804)

Reproduction:
I don't know how toxins work, get a blast cannon to work, shoot it, infinite looping rod that literally DELETES everything in its path, not to mention EVERY ROD MADE LOOPS

**Comment by necromanceranne** [comment]
Looping requires that the zlevel of the station be an active loop. Which means it doesn't go to a different zlevel. 

This is also all apparently deliberate.

https://github.com/tgstation/tgstation/pull/55573

I'll let @TemporalOroboros weigh in on this if they want.

**Comment by TemporalOroboros** [comment]
The effects the OP mentioned are intentional and I can explain both.

When you fire a blastcannon it calculates the range and destructive power of the projectile it launches from the TTV it consumes as ammunition. The range of the projectile is set to the light explosion range of the TTV, specifically the _theoretical_ light explosion range. For 50K bombs this is somewhere upwards of 4500. Projectile range in finicky. I'm not sure what the exact ratio of projectile range to turfs traveled is, and I'm pretty sure it depends on the angle you fire the shot, but in any case the effective range of the blastcannon can be _very long_. They aren't actually infinite and will stop going eventually, it will just take a while. Additionally, since the blastcannon's projectile is a projectile and not an immovable rod subtype as @necromanceranne assumed the projectile has absolutely no issue traveling across z-level boundaries and looping over multiple z-levels.

The destructive power of the blastcannon is also the explosive range of the bomb used to fire it. When the projectile travels over a turf it emulates a bomb's shockwave hitting the turf and everything in the turf. The exact force emulated by the projectile is the force the bomb used to fire it would have used... if the bombcap didn't exist. For the first quarter of the projectile's range this is `EXPLODE_DEVISTATE` which gibs weakly protected and unprotected mobs, punches through walls, and breaches through the floor. For the next quarter the projectile inflicts `EXPLODE_HEAVY` which crits mobs and can, though not necessarily will, breach walls and floors. For the remaining distance the projectile inflicts `EXPLODE_LIGHT` which deals middling damage to mobs and cannot breach through the floor. There may actually be a glitch here. I'm not certain, but I think the projectile might apply the explosion effect multiple times as it passes over a turf. It should occasionally be leaving lattice behind as punches through the floor and that's not happening so I think it's exploding the lattice too. I'll look into it and see if that's happening. If it is I'll fix it.

So yeah, that's the blastcannon. I just buffed the thing out of being the worst non-meme return on investment in the entire uplink so I'm not exactly keen on seeing a nerf unless it starts being overused, but if anyone wants to bother PRing a nerf go ahead and I'll chime in. Just don't dunk it back into uselessness please.

Also, I'm sensing some ided&TRADE; brand salt in OP's post.... Possibly because I blindfired a blastcannon with a 50K TTV up the center of departures hallway and that happens to line up perfectly with the armory.... Sorry about your wiz round.

**Comment by Qustinnus** [comment]
not a bug apparently so why keep it open. if you want this changed open a PR
