### ISSUE TITLE
Airlocks look closed when carrying a body with no access through ones you have access to

### ISSUE THREAD

**Issue by cacogen** [tgstation/tgstation#56420]
Reporting client version: 513.1539

## Round ID:
[154994](https://scrubby.melonmesa.com/round/154994)

## Testmerges:
- [/mob/living/proc/Life(delta_time)](https://www.github.com/tgstation/tgstation/pull/55534)

## Reproduction:

(courtesy of rdragan below)
1. Fireman carry a body with no access
1. Walk into an airlock that you have access to

I've seen it happen with a cyborg carrying a body too.

**Comment by rdragan** [comment]
Repro for this:
1. Fireman carry a body with no access
2. Walk into an airlock that you have access to

**Comment by cacogen** [comment]
Yeah, it was carrying a body now that I think about it.

**Comment by cacogen** [comment]
Still an issue.

**Comment by Sealed101** [comment]
since it's putting the denied animation to reset to normal locked state on a timer, and it checks buckled_mobs first before getting the access of the fireman, we get a denied animation that is overridden by the fireman with an open animation, and the denied's reset animation callback goes through as normal

https://github.com/tgstation/tgstation/blob/5e21011aabd978dccf2f98dc7f0638e4c8831f38/code/game/machinery/doors/airlock.dm#L603-L613

while `Bump()` code is kinda wacky, this should maybe use some better logic. flick animating perhaps?
