### ISSUE TITLE
Clipboards don't let you write on the paper that they hold

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#56456]
## Reproduction:
Put paper in clipboard
Click clipboard
![image](https://user-images.githubusercontent.com/3204033/105968521-cbecb200-604c-11eb-8d40-57849e69455a.png)
"Write" doesn't do anything

**Comment by mozi-h** [comment]
Adding to this: Adding a pen (hold it in active hand and click "Add Pen") doesn't change this either.
In addition to that, clicking on "paper" (or whatever the name) should probably let you view the paper instead of only printing you the inspection text. It's the purpose of a clipboard after all.

I'll take a look at this once I have time.
