### ISSUE TITLE
Grey cores do not produce monkey cubes when injected with blood

### ISSUE THREAD

**Issue by Superlooktome** [tgstation/tgstation#56485]
## Reproduction:

Injecting blood in grey slime extracts makes it bubble but doesn't produce monkey cubes.
> Xenobiology is over within 5 minutes

**Comment by ArcaneDefence** [comment]
This is related to #56019 
Fails to reproduce on master. 
Would be nice if you included the testmerges in that round, as they were  #56019 #55645 #56221

**Comment by Thalpy** [comment]
I tried this on my #56019 branch - but I can't seem to reproduce the error when I spawn in a grey slime core. It might be an issue caused by the current testmerge missing some changes I did, so I will do a bit more testing and ask for a testmerge update after. Thanks for letting me know, and sorry for any trouble caused!

**Comment by Superlooktome** [comment]
The problem seems to persist with any slime core that's supposed to spawn something upon injecting blood/plasma/water into it.

Green cores, for example, still produce the unstable mutation toxin (or whatever it's called) when injected with plasma.

**Comment by ArcaneDefence** [comment]
Fails to reproduce on master, xenobio is fine.
