### ISSUE TITLE
Nuclear Authentication Disk can leave station Z level via Custom Vendor Machine

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#56535]
## Reproduction: 
Put the disk into vendor machine, unanchor and drag to other Z level.

![Screenshot_127](https://user-images.githubusercontent.com/64209864/106382158-66077e00-63f0-11eb-84f8-400dc5e549de.png)

**Comment by TemporalOroboros** [comment]
Are you sure it didn't just teleport out of the vendor and the vendor's just keeping a ref to it?

**Comment by Livrah** [comment]
> Are you sure it didn't just teleport out of the vendor and the vendor's just keeping a ref to it?

Ghost orbit menu shows that the disk inside.

**Comment by maxymax13** [comment]
and there he goes. INTO lavaland. the vendor HASS the disk

**Comment by timothymtorres** [comment]
![dreamseeker_N456choQyh](https://user-images.githubusercontent.com/5195984/152704711-ac98fecb-1e82-4b1e-b203-ce51cbda2185.png)

![dreamseeker_Iz37JphpZz](https://user-images.githubusercontent.com/5195984/152704713-c94258b7-5498-49b8-8b6a-2ba9e28059a6.png)

Tested this just now.  The nuke disk gets teleported back to the station however the custom vendor UI breaks.  The nuke disk is still a selectable option and the icon gets broken.  Trying to vend the disk results in nothing happening.  Leaving this open for now since it's not fully fixed.

**Comment by RandomGamer123** [comment]
Can't reproduce anymore, seems to have been fixed by #61335

**Comment by Sealed101** [comment]
![изображение](https://github.com/user-attachments/assets/bfcd6fa9-a6b5-4b32-b98c-be36872bc557)
