### ISSUE TITLE
Atmos: DELETED

### ISSUE THREAD

**Issue by Sparkezel** [tgstation/tgstation#56554]
## Round ID: 155419
So a new round starts, and for some reason pipes don't have any gas at all, pumps arent working, gasses dont even move in rooms, so I get an idea to plasma-flood medbay, but plasma also didn't move at all, each tile was like its own bubble 😂 

## Reproduction: None that I know of

![image](https://user-images.githubusercontent.com/53384660/106402804-a6382200-642b-11eb-853a-712d7fdc1be8.png)

**Comment by LemonInTheDark** [comment]
A known if painful issue, should really get to fixing it.

If this line runtimes due to say a null ending up in the pipenets to be rebuilt list, the whole subsystem freezes up. Forever 
![image](https://user-images.githubusercontent.com/58055496/106403668-abbe4980-63e4-11eb-812a-a1f6f7ea8b36.png)

Really just needs a sanity check. I dislike the process in general because it can't yield, but that's a problem for not today.

check the logs for null.build networks for [evidence](https://tgstation13.org/parsed-logs/terry/data/logs/2021/01/31/round-155419/runtime.txt)
