### ISSUE TITLE
BMP Asteroid away mission spawns with no atmos

### ISSUE THREAD

**Issue by castawaynont** [tgstation/tgstation#56693]
## Reproduction:
the caves away mission spawned with no atmos, this has been consistent over a few rounds

**Comment by ATH1909** [comment]
This has been known for at least half a year, probably much longer.

IIRC, I talked with the guy who had originally made the BMP asteroid away mission, and he said that it wasn't intentional, but that it was funny/lethal enough to keep in. The conversation is somewhere on the Discord server, if you want to search for it.
