### ISSUE TITLE
Toggle combat mode doesn’t work as a borg

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#56822]
## Round ID:
(This was less than a week ago)

## Testmerges:
Manuel

## Reproduction:
1. Become borg
2. Try to toggle combat mode, fail

I haven’t tried it recently, so I don’t know if it has been fixed by now.

**Comment by zxaber** [comment]
I believe the issue you experienced was due to the old intent cycle hotkey for borgs still existing. The hotkey didn't do anything, but was bound to 4 by default, and thus blocked the combat mode hotkey.

The intent cycle hotkey has since been removed, so this issue should be fixed for you. If not, there's a new bug to track down.

**Comment by redguy999** [comment]
just tested it, it does work.
So i'll close this
