### ISSUE TITLE
Mindswap into pAI causes permasleep

### ISSUE THREAD

**Issue by Randomguy523** [tgstation/tgstation#56861]
## Testmerges:
#56767: 'Upgrade marked to 2.0.0, along with the other deps' by stylemistake at commit 8d0f8acfa9

## Reproduction:
Mindswap into a pAI who is currently using holochassis, the one put into the pAI should be permaslept.

**Comment by ATH1909** [comment]
Note that this wasn't always the case, as I've mind transfered into pAIs before (a year or two ago, IIRC).

**Comment by Zytolg** [comment]
I tested this on Monday's (2/8) build and you could mindswap into the PAI. However I should note some funny behavior that appears to be part of a larger issue:
1) Mindswap will not work after the swap. Instead, this will trigger the ability for the original mob the caster swapped into the PAI from. The PAI now inside the casters previous body will not be able to use use mindswap since you can't use a spell you don't know. 
2) There appears to be a funny interaction between mindswap and a PAI's drone form. More testing is needed, but this would need to be done with multiple people on a server (aghost hopping works to a certain extent but bug out mindswap for some reason).

**Comment by timothymtorres** [comment]
Fixed by #67083
