### ISSUE TITLE
Holodeck Issue: Frozen Gun Beam Thingie

### ISSUE THREAD

**Issue by san7890** [tgstation/tgstation#56904]
## Reproduction:
Shoot laser beam (such as the disabler in the holodeck simulation of star trek or whatever)
Have someone else switch the holodeck mid-beam movement
It will stay frozen right there, no matter how many times you change the holodeck simulation
(note: you can't interact with the beam, it's just like the sprite is frozen there, it doesn't inflict any damage if you walk into it or anything)

![image](https://user-images.githubusercontent.com/34697715/107859620-d30b1280-6df7-11eb-97f5-60ccc6dc0bda.png)

**Comment by Kylerace** [comment]
copy paste from the pr in case it gets closed for whatever reason:

the bug report is inaccurate, the holodeck puts the original projectile spawned by the energy guns stored ammo_casing into its spawned list and tracks it normally. whenever its time to delete everything in the spawned list (ie when the holodeck program changes) derez() makes everything with contents move its contents to its loc before being deleted. this is fine for guns that are spawned without being fired because the projectile is in the spawned list as well (and is thus deleted), but if the gun is fired once then the projectile held inside the guns ammo_casing isnt in the spawned list, so it gets moved onto the guns turf and doesnt get deleted. so you now have a stationary laser beam standing there runtiming whenever someone touches it.
