### ISSUE TITLE
Glass bottles smashed onto peoples heads do not splash their victims unless you rightclick (and it doesn't 'splash' either)

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#57042]
It will still smash the bottle over their heads if you are in combat mode, but it only ever splashes the target of the attack if you use the right click.

Also, unlike other reagent splashes, this one apparently doesn't treat the effect as having splashed them with the reagent in the first place. So touch chems do nothing. Which is really weird. It soaks them in whatever is inside the bottle however, so alcohol and other flammables work.

**Comment by Thalpy** [comment]
If this around when I wake up, I'll take a look.

**Comment by Thalpy** [comment]
I might need a bit more information - how did it work before? Left and right click current seem to feed the bottle to someone when not in combat mode, whereas combat seems to smash for both left and right click. It looks like the issue is that spillable is set to false for these bottles, so I'll try adding an override spillable var and putting up a PR for that.

**Comment by SuperNovaa41** [comment]
Fixed
