### ISSUE TITLE
Players on the "alternative spawn" Station hear messages from the "main station"  -  Spawner Menu

### ISSUE THREAD

**Issue by rtizzy** [tgstation/tgstation#57268]
## Round ID:

N/A This bug applies across rounds on any TG server that allows the "spawner menu" 

## Reproduction:

In any arbitrary match, select "spawner menu" an spawn on the "alternative station" .

This station is "In Character" unaware of the the other station "as they are awoken from cyro sleep" with no power and do not have communications open. 

If they did, they would simply call for help. 

This communication in any direction should not be possible without IC reasons for having been accomplished.

**Comment by Ewwmewgewd** [comment]
You're referring to the Charlie station. Can you clarify what do you mean by they can hear messages? Which messages? How?

**Comment by rtizzy** [comment]
Apologies for lack of screenshots, I'll see about grabbing some next time. 

At minimum I believe any station announcement messages.

Canonically this doesn't make a ton of sense as when you spawn you have no power, no PDA, and seemingly no way to engage in communication.

**Comment by TheBonded** [comment]
> You're referring to the Charlie station. Can you clarify what do you mean by they can hear messages? Which messages? How?

Station messages, like shuttle being called and centcom messages. Maybe head of staff announcements, unclear by the issue report

**Comment by TheBonded** [comment]
> Apologies for lack of screenshots, I'll see about grabbing some next time.
> 
> At minimum I believe any station announcement messages.
> 
> Canonically this doesn't make a ton of sense as when you spawn you have no power, no PDA, and seemingly no way to engage in communication.

I believe this does make sense, and here's why: 
Centcom sends the messages on a broad all use frequency so all nanotrasen employees hear it, to ensure that even if comms are down or an employee is offstation they are still informed of whatever extremely important announcement centcom is sending. This is because it goes straight to their nanotrasen brand identity implant, given to all nanotrasen employees so they can be identified when they arrive at centcom. (It's also possible they are terragov implants given to all citizens born or working in terragov controlled space)The charlie station employees would still have these, so that's why they can hear them, although IC they would assume it is some sort of malfunction with the station's relay.

The reason why these implants aren't used for identification on station is because it takes expensive equipment that can't be risked getting into enemy hands

**Comment by Ewwmewgewd** [comment]
Correct me if I'm wrong but this case isn't isolated only to Charlie station, you can hear these announcements anywhere as anyone? Including things like ash lizards, space dragons, carps and other things that shouldn't hear them. So the IC explanation doesn't really stand.

**Comment by TheBonded** [comment]
> Correct me if I'm wrong but this case isn't isolated only to Charlie station, you can hear these announcements anywhere as anyone? Including things like ash lizards, space dragons, carps and other things that shouldn't hear them. So the IC explanation doesn't really stand.

That's true, but usually it doesn't make all that much of a difference.

**Comment by interestingusernam3** [comment]
Announcements are delivered by AssBlast Co. Low-Orbit super-speakers that somehow work in space.

**Comment by TheBonded** [comment]
> Announcements are delivered by AssBlast Co. Low-Orbit Super-Speakers that somehow work in space.

AssBlast Co. Low-Orbit Super-Speakers are currently being tested as a concept in the space around the new Nanotrasen Space Station 13. It uses cutting edge translation and rapid communication technology to send subspace messages across bluespace channels to all sentient beings in a several hundred kilometer radius. Several mild side effects have been recorded, including rapid organ failure, brain liquification, permanent attention disorders, errors in both telecommunications and arificial intelligence machinery, and death. AssBlast Co. will not be held liable for damages to any personnel or equipment. All rights reserved, AssBlast Co. a subdivision of Donk Co.
