### ISSUE TITLE
Reaction chamber issues

### ISSUE THREAD

**Issue by Etgfrog** [tgstation/tgstation#57363]
Some issues regarding pull request #57071. The reaction chamber does not pull the acid or base buffer into it while its reacting and the limits are way outside what Ph normally is.

Fix can be done by changing code/modules/plumbing/plumbers/reaction_chamber.dm Line 58 and 60 to remove the ! .
Other issue can be fixed by changing tgui/packages/tgui/interfaces/ChemReactionChamber.js Line 139, 140, 160, and 161 so its min value is 0 and max value is 14.

**Comment by TheBonded** [comment]
I've seen people do this before, so I know there must be a reason, but if you know what code changes can fix the problem why not pr it yourself?

**Comment by Etgfrog** [comment]
Because last time I tried using git hub it took half a day to set up to the point I could make a pr, which usually I don't have the time.

**Comment by stylemistake** [comment]
Would probably still be faster than waiting until someone steps up to reproduce/test/fix this.

**Comment by TheBonded** [comment]
> Because last time I tried using git hub it took half a day to set up to the point I could make a pr, which usually I don't have the time.

really? because my first pr on /tg/ was my first time ever coding, I had no idea what the hell I was doing and I had to ask around in the discord of how to fix what I was trying to fix, but github let me make a pr right after I verified my email, no setup needed. I'm fairly certain you just have to click edit, make the change, then pr it. what took half a day to set up?
