### ISSUE TITLE
Sleepy pens give no chat message to their victim

### ISSUE THREAD

**Issue by ArcaneDefence** [tgstation/tgstation#57410]
## Round ID:
Tested locally

## Testmerges:
N/A

## Reproduction:
Log in with two clients like a pro
Poke with a pen
No feedback on the receiver
Poke with a sleepy pen
No feedback on the receiver 
![image](https://user-images.githubusercontent.com/51932756/109907602-db6ca580-7c5f-11eb-8caf-35da6b4339ba.png)

**Comment by ATH1909** [comment]
```
/obj/item/pen/attack(mob/living/M, mob/user,stealth)
	if(!istype(M))
		return

	if(!force)
		if(M.try_inject(user, injection_flags = INJECT_TRY_SHOW_ERROR_MESSAGE))
			to_chat(user, "<span class='warning'>You stab [M] with the pen.</span>")
			if(!stealth)
				to_chat(M, "<span class='danger'>You feel a tiny prick!</span>")
			. = 1

		log_combat(user, M, "stabbed", src)

	else
		. = ..()
```
If I had to guess, someone probably added a new argument to the attack() proc at some point, and the pen code here is interpretting whatever's being inputted as the third parameter of the attack() as being the value for "stealth".

We could probably fix this issue by just removing the stealth argument and the stealth check, since I don't think we actually have a pen (without a force value) that doesn't try to send the pricking message whenever you successfully jab someone with it.

**Comment by KathyRyals** [comment]
Can confirm it happened to me on round 57305, got stabbed by a sleepy pen and didn't know until I was down.

**Comment by msgerbs** [comment]
Sleepypens actually being useful is a bug.

**Comment by TheBonded** [comment]
> Sleepypens actually being useful is a bug.

Then why not keep them that way? Maybe put a 1 second timer but keep it silent
