### ISSUE TITLE
Randomly losing connection from all servers

### ISSUE THREAD

**Issue by JenqaDev** [tgstation/tgstation#57486]
Playing any SS13 codebase/server on byond is impossible for me, specifically /tg/ (where it is more unstable). I've been constantly losing connection for no reason at all for the past few months I tried to play again. My Internet may not be the most average one but a year ago I didn't lose the connection so many times in one round. Never had this problem playing spessmen.

## Reproduction:

I connect to the game, sometimes I instantly get the "You're AFK, or the connection has closed" text on the corner, but mostly it's during the game, which makes me afraid of playing any important role since sometimes I get to the point where I can't reconnect anymore. I think the solution that SOMETIMES works is cleaning cache, totally killing byond from my pc and then restarting the program and rejoining. Otherwise i'll just get Connection Closed or Connection Failed.

And both the reconnect button on the top left corner and the one in chat are useless to me, they won't reconnect at all.

**Comment by EnPeignoir** [comment]
Update your client as shown on my screenshot in beta : 
![byond_v9oADU6SIx](https://user-images.githubusercontent.com/75167369/110206656-5069f600-7e7f-11eb-9417-3629e655ecdb.jpg)

**Comment by JenqaDev** [comment]
![image](https://user-images.githubusercontent.com/43709941/110207349-c750c000-7e7a-11eb-9b1a-efb39dce7424.png)
you mean like this or like in your screenshot?

**Comment by EnPeignoir** [comment]
Like this, yea

**Comment by EnPeignoir** [comment]
I'll take for a yes, hope i helped you

**Comment by JenqaDev** [comment]
I actually hadn't got this issue since I updated. It simply returned out of nowhere.
Round ID is 157945

**Comment by TheBonded** [comment]
Do you have anything open in the background? a funny quirk of BYOND games is they put themselves on the lowest possible priority for your processor and GPU, so if you have anything open that can be using those BYOND will decide that you don't need graphics or server connection.

Also, do you see other people moving? I used to have this issue a lot on a small lowpop server, where I would get unreasonably high ping, but I could still see other people moving. The reason for that was I was running a newer version of BYOND than the tg branch they had was. I don't believe tg is running BYOND 514 yet, so if you're using the newest version that could also be causing this. Try joining a tg server with nothing on in the background (Google chrome should be fine but it's safer to try it without) and with BYOND 513. Hope this works!

**Comment by JenqaDev** [comment]
Sometimes I not just see people moving, but can see them talking normally while the game is supposedly disconnected.
i was on some update i forgot that mso told me to use instead a few months ago. Only updated 4 days ago.
> Do you have anything open in the background? a funny quirk of BYOND games is they put themselves on the lowest possible priority for your processor and GPU, so if you have anything open that can be using those BYOND will decide that you don't need graphics or server connection.

yeah discord and chrome. maybe that's what causes this? maybe it's what makes my game start to stutter a bit into the round (i lose my butter smooth 60 fps in the game). Is there any way to set it to the highest priority?

**Comment by JenqaDev** [comment]
Will setting the priority in task manager even matter?

**Comment by TheBonded** [comment]
> Sometimes I not just see people moving, but can see them talking normally while the game is supposedly disconnected.

I encountered this too, when I had this issue on the lowpop server I used to play, that ran an earlier version of tg code, and I would lose control but see other people moving and interacting just fine. It seems BYOND and Dreamseeker are receiving information just fine, but having trouble sending it to the server. I'm pretty sure this is caused by running a version of BYOND that's newer than what the server is running on, for my case it was running version 513 on a version 512 server, and in your case running the newest version of BYOND, 514, on tg which runs BYOND version 513.

> i was on some update i forgot that mso told me to use instead a few months ago. Only updated 4 days ago.

Judging by your screenshot, you are likely running the newest version. because of how old tg's code is, we have to make preparations sometimes to update the BYOND version of the server, as the updates sometimes break things. Moving back to BYOND 513 should fix this for you.
 
> yeah discord and chrome. maybe that's what causes this? maybe it's what makes my game start to stutter a bit into the round (i lose my butter smooth 60 fps in the game). Is there any way to set it to the highest priority?

I use discord and chrome in the background as well, so this shouldn't be causing the connection issues. Also, no, there is no way to set priority of GPU, as they run on separate drivers, I have already tried this so I can play other games while I play SS13. Your best bet, like I recommended earlier in this comment, is to downgrade your BYOND version to 513. if you look at the screenshot @EnPeignoir put, they are running 513.1542, which works with tg servers because that's what they run. it makes it easier on BYOND because it doesn't have to convert some data to the older version, which is likely one of the reasons you disconnect but can still see other people moving. 

This doesn't happen in other games because most other games have your computer run the game, whereas in ss13's case the server runs the code, and you just need the client. This is good in a lot of ways because it allows each server to have greatly varying codebases while only requiring the base client to run. In other games with different servers that have different features, they have to force the players to download mods to play with their features. The disadvantage to this is that if the server is running on a newer or older version of the client, players will have trouble connecting and playing on the servers, as the different versions process things differently. this usually isn't too bit of a deal, as for example version 513.1542 wouldn't be all that different from 513.1268, but it starts to become an issue when the differences in version becomes to great, like with version 514 clients connecting to version 513 servers.

I hope that explains things well enough, and I hope this helps! I'll be checking back onto this post every so often to make sure we can get your game running smoothly.

**Comment by JJRcop** [comment]
This issue has nothing to do with tgstation itself. If you would like, please visit our discord

**Comment by JenqaDev** [comment]
This might look funny, but i got banned from there like 5 months ago. I'd like to get unbanned though, could you get me some discord jannie's discord to see if I get a chance?

**Comment by JJRcop** [comment]
You can appeal on the [/tg/station Ban Appeals board][tgban].

[tgban]: https://tgstation13.org/phpBB/viewforum.php?f=7
