### ISSUE TITLE
Can't Get Ash From Icy Stones

### ISSUE THREAD

**Issue by Jones-SnowCone** [tgstation/tgstation#57500]
Reporting client version: 513.1528

## Round ID:
[157707](https://scrubby.melonmesa.com/round/157707)

## Reproduction:

1. Be a miner/have a mining equipment on you.
2. Go to Icebox's ice wastes
3. Repeatedly hit icy stones for ash
4. ???
5. "Miners! We need more glass!!"

Legit, after shooting/hitting multiple rocks with PKAs and other items for mining, the rocks just disappear with no piles of ash crumbling to take their place.

**Comment by Whoneedspacee** [comment]
https://github.com/tgstation/tgstation/pull/55785

>Such as spawning ruins or generating terrain. This also makes so cleaned rocks properly dont drop ash, but have to be mined

I guess this is so destroyed rocks from ruin generation wouldn't just spawn ash everywhere? Kinda makes this an issue though because destroying the rocks in any way should probably drop ash, you can still technically mine them with a pickaxe or drill and get ash.

**Comment by JohnFulpWillard** [comment]
I believe it only works with a pickaxe

**Comment by Sealed101** [comment]
it only works with a pickaxe as #55785 made sure of that, though it did that to avoid mapgen ruin template placing not leave ash piles when a rock is destroyed.
