### ISSUE TITLE
Tramstation's bluespace translocations can space the AI core under a rock.

### ISSUE THREAD

**Issue by ZeroMODE0** [tgstation/tgstation#57692]
## Round ID: [158149](https://scrubby.melonmesa.com/round/158149)
Bluespace translocation teleported me outside the AI sat under a rock, and a spacecarp sniped me through it.
![image](https://user-images.githubusercontent.com/62538745/111051727-f1762500-841a-11eb-8b49-0fb5bb76ce2d.png)
**this is not cool, this is so not cool**

An admin decided this wasn't intentional and revived me, so I am making an issue report on it.

**Comment by MMMiracles** [comment]
More of an issue with bluespace translocation not caring if the turf it chose is a closed turf or not, it just happens to be not as big of an issue on other stations.

**Comment by ZeroMODE0** [comment]
Thinking it over some more- It's possible that I could've been teleported to an area north of the sat and "fallen down"
This isn't even on the same Z level as where I was.

**Comment by Sealed101** [comment]
_technically_ not an issue since the code does not indeed care where the victim would end up - it takes the turf that's somewhere in the middle in between a random station-side teleportation beacon and the victim's turf.
being forcemoved to that exact spot on tramstaion but on the zlevel above didn't lead me to dropping down the zlevel in testing; we've had some gravty reworks that have hopefully managed to catch such stupid things
