### ISSUE TITLE
Ghosts cannot view Crew Monitoring Consoles

### ISSUE THREAD

**Issue by FelineEsquire** [tgstation/tgstation#57815]
Title says it all, despite being able to see other computers and even chem dispensers you can't view the crew monitoring console as a ghost. I like to know if my sensors are still on or not

**Comment by Timberpoes** [comment]
Inconsistent behaviour compared to other console types.

When testing PRs relating to this on local and triaging problems on live, I'd had to turn on admin AI interact to do it,

Likely because the UI is set to show on `/obj/machinery/computer/crew/interact(mob/user)` instead of in `ui_interact` like all our other interfaces.

`attack_ghost` doesn't interact with machines, for obvious reasons.

Can probably be fixed by calling the `GLOB.crewmonitor.show()` proc from `ui_interact` instead of `interact`
