### ISSUE TITLE
Monkeys dying in vents

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#57875]
## Reproduction:

Monkey takes contant damage inside vents. At first I was blaming atmos (#57748 ), but noticed its a same behavior as polymorhing back to human from mice/slime inside a vent (#53740 ). Probably happened after Monkeys rework into species.

**Comment by davethwave** [comment]
If I remember right, this happened with a PR relating to vampires where originally a vamp could turn into a human in the middle of a pipe in order to exit it from anywhere. Since monkey's are a subtype of humans now or something like that, it make it so that they can still go into vents and the like but still take damage and at the same time still travel in them while normally you wouldn't be able too and be trapped.

**Comment by vincentiusvin** [comment]
Could not reproduce. Monke is alive and well on 101kpa air vent mix. Next time this happens to you, would you mind posting a gas scan of the pipes?

**Comment by Livrah** [comment]
> Could not reproduce. Monke is alive and well on 101kpa air vent mix. Next time this happens to you, would you mind posting a gas scan of the pipes?

Every time roundstart.

**Comment by vincentiusvin** [comment]
Roundstart pipe pressure is empty and needs to be filled.
![image](https://user-images.githubusercontent.com/54709710/112014084-28f07a00-8b5d-11eb-87d1-ba330b26ba2b.png)
Your earlier assumption was correct, and this is most definitely not a bug.

As dave said, monkeys are a subtype of humans and therefore fall under atmospheric limitations.

**Comment by davethwave** [comment]
Ah, I probably misremembered then about it.

**Comment by Livrah** [comment]
Same happened on wiz round with mouse transform spell - pressure was good for simplemob, but started to damage with low pressure when I accidentally transformed back to human form.

**Comment by vincentiusvin** [comment]
> Same happened on wiz round with mouse transform spell - pressure was good for simplemob, but started to damage with low pressure when I accidentally transformed back to human form.
> 
> If it is an atmos issue, simplemobs would die too.

Thats because mouses dont check for pressure. They only check for the type of gas (has o2 or not in the case of mouse) and temperature.
Temp:
`	
///Temperature effect.
var/minbodytemp = 250
var/maxbodytemp = 350
`

O2:
`var/list/atmos_requirements = list("min_oxy" = 5, "max_oxy" = 0, "min_tox" = 0, "max_tox" = 1, "min_co2" = 0, "max_co2" = 5, "min_n2" = 0, "max_n2" = 0)`

However, the gas check doesn't bother if the location of the simple animal isn't a turf (this explains why old monkey can ventcrawl, and why mouse can ventcrawl inside an empty pipe if temp isn't too high).
`/mob/living/simple_animal/proc/environment_air_is_safe()
~omitted some things to keep this comment tidy~
	if(isturf(loc) && isopenturf(loc))
`
Again, not a bug, more of a consistency issue, but not really. Quite sure this was expected when monkey was moved from simple animal to a full fledged species.

**Comment by Pugie** [comment]
good!
