### ISSUE TITLE
Negative latejoin traitor timer

### ISSUE THREAD

**Issue by wabash1** [tgstation/tgstation#57925]
## Round ID:
[158809](https://scrubby.melonmesa.com/round/158809)

## Reproduction:
Currently the latejoin injection timer is counting in the negative and at a rapid (5x?) speed. Roundstart threat was about .4? 

Latejoin: -19047 seconds [Now!]
Midround: 26.5 minutes [Now!]

Latejoin: -19142 seconds [Now!]
Midround: 26.4 minutes [Now!]

**Comment by Mothblocks** [comment]
Okay so this is an old bug, but I'm realizing now it's pretty bad.

1. It's not ticking rapidly, it's just displaying deciseconds as seconds.
2. Going negative isn't a bug either, it just means someone hasn't joined yet.
3. The real bug is that **the latejoin timer doesn't reset**. This means that, after a certain point, everyone who joins will become an antag until all the threat is drained.

**Comment by Mooshimi** [comment]
@Mothblocks So the only part of this left would be the deciseconds thing?

**Comment by Mooshimi** [comment]
will close this since I see you have an issue open for just that #56100
