### ISSUE TITLE
Account Registration Machine is FUBAR.

### ISSUE THREAD

**Issue by unit0016** [tgstation/tgstation#57929]
## Round ID:
N/A, Local Branch

## Testmerges:
N/A, Local Branch

## Reproduction:
Bank Accounts created with the account registration device are counted as departmental accounts, meaning they can't buy anything from vending machines. This effectively ruins half their functionality.

**Comment by ArcaneMusic** [comment]
The wording on the feedback could use some work on the player-facing side.
`else if(!C.registered_account.account_job)
	say("Departmental accounts have been blacklisted from personal expenses due to embezzlement.")`
This was supposed to prevent departmental budgets from being used to bankroll vending machines, so that to use the account reg. machine to make a savings account you would need to assign a job.

**Comment by timothymtorres** [comment]
This might be related to #62167

**Comment by ArcaneMusic** [comment]
The accounting machine was removed last month, whoops!
