### ISSUE TITLE
trying to create Fluorosulfuric Acid doesnt work and trying to creatre nitric acid deletes all chems in the beaker

### ISSUE THREAD

**Issue by Serxule** [tgstation/tgstation#58001]

**Comment by ArcaneDefence** [comment]
I had success in using a quickly made basic buffer to maintain the ph of a fluorosulfuric acid reaction ending at purity 0.376028, pH of 4.7, and a temperature of 487.631K.
Using that I made nitric acid with a purity of 0.792009, pH of 5.6 and a temperature of 642.86K.

Tanking the ph of either of these reactions simply made viscous sludge as expected, but did not seem to delete water present in the beaker when failing the reaction from having too low of a ph. 

Even slamming a reaction for fluorosulfuric at 1000K instantly completes it at 19.6u of acid for 20u of component reagents, which then combined with 5u of hydrogen peroxide and nitrogen completed to 10u of nitric acid without deleting other reagents.

There was ~3.3k runtimes on that round through, and I haven't been able to find anything immediately related.
https://sb.atlantaned.space/rounds/159076/chemical_reaction This doesn't help me figure it out either, as it doesn't show how many reactions became sludge, only that attempts were made.

Do you happen to have any further details?

**Comment by Serxule** [comment]
> I had success in using a quickly made basic buffer to maintain the ph of a fluorosulfuric acid reaction ending at purity 0.376028, pH of 4.7, and a temperature of 487.631K.
> Using that I made nitric acid with a purity of 0.792009, pH of 5.6 and a temperature of 642.86K.

the temperature must be wrong in the wiki then, as it says to heat the fluorosulfuric acid to 380k, not 480k, I'll see if I can get the chem deletion to happen again

**Comment by Serxule** [comment]
alright it seems that the fluorosulfuric acid not creating was a round specific bug, but I was able to get the chems to delete again. 
https://youtu.be/HsRC8FE7c2w (sorry for using a current round but I don't have the stuff for a personal server)

**Comment by ArcaneDefence** [comment]
As far as the temperatures go, you can generally crank things up hotter to get them to react faster, which may be a good or a bad thing for the reaction you're doing. The temperature of the reaction also tends to change based on if it's exo/endothermic.

Regarding the reagents deleting- You're combining potassium and water in a non-stasis container, which creates the potwater explosion reaction, which empties the reagent holder.
The water was an example specifically for making nitric acid, which does not have potassium. You should be able to use other, nonreactive reagents and fail to reproduce that issue.

This is expected behavior, from this proc, as at the end it clears the holder.
https://github.com/tgstation/tgstation/blob/15f14ce48abefc88cb4f0da5085bf281afa94f29/code/modules/reagents/chemistry/recipes/pyrotechnics.dm#L11-L30

Medstaff have been using this as a trick to purge reagents out of their patients for a long time.

**Comment by Serxule** [comment]
huh, it really should probably be more descriptive, as it gives really no hint as to why everything deleted suddenly
