### ISSUE TITLE
Thermomachines and smart pipes killed sci toxins.

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#58132]
## Testmerges: #58038

1) Roundstart sci toxins thermomachinery doesnt work without atmos tech actualy doing their job instead of autism pipefuck.
![Screenshot_197](https://user-images.githubusercontent.com/64209864/113477025-6d5b0e80-94a9-11eb-98e1-29010748b2a6.png)
![Screenshot_212](https://user-images.githubusercontent.com/64209864/113477065-b0b57d00-94a9-11eb-98c8-f12b7e22c4c5.png)
2) "Smart" pipes with 3x3 workplace toxins area (or less if Kilo) isnt a thing. 
![Screenshot_211](https://user-images.githubusercontent.com/64209864/113477106-01c57100-94aa-11eb-9256-125c7d111a1c.png)
Id like if such big rebalance/nerf changes dont go through cos person who did that doesnt know what he doing.
![Screenshot_213](https://user-images.githubusercontent.com/64209864/113477209-79939b80-94aa-11eb-9930-50e2926e8bca.png)

**Comment by Ghilker** [comment]
For the first issue (not an issue) you left out my comment about asking an atmos tech to do their job and add to waste some gas for heat management. You kept asking so I told you to breathe so that waste slowly fills with co2 (you need very small amounts for the machine to work)

The second issue (again not an issue) is easily managed, colored pipes don't connect to other colors, grey can connect to all other colors on the same layer. You also have five different layers where to place pipes. With 12 colors (11 if you exclude grey) you'll manage to make a different setup instead of the "meta" one

**Comment by Livrah** [comment]
No shit it got closed by you before anyone could comment.
 1st one was 1hr+ into a round.
 2nd you dont know "meta" setups.

**Comment by Ghilker** [comment]
1. You can just attach a canister of plasma to that (or any gas for that matter) and store the heat that way.
2. That's irrelevant, learn to use colors and different layers
