### ISSUE TITLE
lings soul stays in the head and not the body when you die 

### ISSUE THREAD

**Issue by theta006** [tgstation/tgstation#58138]
Reporting client version: 513.1542

 lings soul is stuck in the brain and not the body 
## Round ID:
[159550](https://scrubby.melonmesa.com/round/159550)

**Comment by ATH1909** [comment]
not agaiiiiiiiin

**Comment by rdragan** [comment]
> not agaaaaaain

yes again. and again. and again. it never ends, this shit.

**Comment by ArcaneDefence** [comment]
https://github.com/tgstation/tgstation/issues/51408
Was it even fixed?

**Comment by Shadowflame909** [comment]
This bug came back.

My round: 174017

As I was in reviving stasis, I got beheaded, and My powers were in my fake-head, and so was my soul. My body was completely ignored and I couldn't go inside of it.

An admin had to manually re-attach my head to my body, to regive my body powers. 

How do we keep fake-heads to stay fake?

**Comment by Potato-Masher** [comment]
It's.... still happening. 

Round: 177409 (https://sb.atlantaned.space/rounds/177409)

Beheaded while in stasis, and brain was scooped out. Ghost shifted to the brain and attempting to use the reviving stasis power yielded nothing.

Brain on examine said there was still a spark of life in it.

**Comment by Mooshimi** [comment]
Same issue as #51408 Please repost related experiences there instead of here
