### ISSUE TITLE
PIPES LITERALLY DO NOT EXIST ON MANUEL

### ISSUE THREAD

**Issue by notfrying1pans** [tgstation/tgstation#58141]
THERE ARE LITERALLY 0 PIPES HOLY SHIT
[PIC OF ATMOS WHILE PIPES WERE BEING BUILT ](https://cdn.discordapp.com/attachments/434508948595408896/828013454123728926/unknown.png)
## Round ID:

Round ID: 159552

## Testmerges:
https://www.github.com/tgstation/tgstation/pull/58096

**Comment by LemonInTheDark** [comment]
lol wut

**Comment by notfrying1pans** [comment]
i have no clue what happened but literally zero pipes were present round start last round on manuel

**Comment by LemonInTheDark** [comment]
zero pipes? there was nothing connected to vents and such? or was it just in atmospherics

**Comment by dragomagol** [comment]
https://tgstation13.org/raw-logs/manuel/data/logs/2021/04/03/round-159552/runtime.log

Runtimes for that round

**Comment by notfrying1pans** [comment]
> 
> 
> zero pipes? there was nothing connected to vents and such? or was it just in atmospherics

there were zero pipes whatsoever

**Comment by LemonInTheDark** [comment]
The null.archive runtime is unrelated, pipes and turfs shouldn't have that kind of effect on each other

**Comment by necromanceranne** [comment]
To clarify even further, this seems to have been on Kilo

**Comment by Ghilker** [comment]
not a bug, this was caused by errors in the compiling of the TMs
![image](https://user-images.githubusercontent.com/42839747/113513120-57605300-9568-11eb-89bb-9cc866a87e5e.png)

This happened because the maps somehow got changed (so they had the smart piping) but the TM code wasn't present, so this deleted the pipes (notice how pumps and filters were still a thing)

**Comment by LemonInTheDark** [comment]
what the fuck cyberboss
