### ISSUE TITLE
Materials created with a stable metal extract aren't counted when added to an exo-fab/lathe.

### ISSUE THREAD

**Issue by Gristlebee** [tgstation/tgstation#58189]
## Reproduction:
1. Get a stable metal extract and a sheet of whatever material, and have the stable metal create an additional sheet. 
2. Insert your stack into the exo-fab.
3. It only as counts a single sheet.

<img width="444" alt="bug1" src="https://user-images.githubusercontent.com/56049844/113678078-186af400-9673-11eb-89dc-beed324b6370.PNG">
<img width="219" alt="bug2" src="https://user-images.githubusercontent.com/56049844/113678098-1dc83e80-9673-11eb-96aa-976172472158.PNG">
<img width="204" alt="bug3" src="https://user-images.githubusercontent.com/56049844/113678110-21f45c00-9673-11eb-8008-c97fe4287cef.PNG">
<img width="87" alt="bug4" src="https://user-images.githubusercontent.com/56049844/113678120-2587e300-9673-11eb-946b-85fee40ffe9a.PNG">

I also tried this with a protolathe and got a similar issue.

**Comment by TemporalOroboros** [comment]
Found it. This is happening because the extract directly adjusts the amount of sheets in the stack and thus doesn't actually update the amount of materials in the stack. Until it gets fixed the best workaround is probably just to split the stack before you put it in any thing. That should update the materials.
