### ISSUE TITLE
Reaction chamber doesn't wait for correct temperature and Ph

### ISSUE THREAD

**Issue by Kulik242** [tgstation/tgstation#58320]
![Snímka](https://user-images.githubusercontent.com/77277943/114298490-fcbe7e00-9ab6-11eb-8177-06241707b5d1.PNG)
So, as you can see from the image, the inputs are flowing into the chamber, the temp is set to 400K and Ph between 6-7. The chamber sends the input chemicals without reaching these thresholds. The output gate contains the inputs at 322.652 K  and 5.16 Ph. Both input gates are topped off with correct buffers. Resetting the output gate and the reaction chamber with the plunger produces the same results.

**Comment by Time-Green** [comment]
This is intended (I guess?). They simply try to cool/heat and add the appropriate buffers for the duration of the reaction, if the reaction ended it's too late anyway. If you want a specific temp, you should use the chemical acclimator. There is no machinery for a specific pH yet

**Comment by Kulik242** [comment]
I see, but the reaction didn't started, if it did, there would be some of the product, right?

**Comment by Time-Green** [comment]
Ah, you're right. You're doing a temperature dependent reaction, but the reaction wont start because it needs to reach a temperature first which it wont reach unless it's reacting. It's not really a bug, since you should be using the chemical acclimator for this, but then you run into issues with pH...

I honestly don't really know what to do with this, do you have any ideas? I can't make the reaction chamber a better acclimator, but you need both the power of the acclimator and pH controle to do finnicky reactions. The in-game solution is to react only a little bit and have a lot of non-reactive chems present to buffer the pH, but that's not exactly obvious

**Comment by Kulik242** [comment]
I'm not really sure either. Perhaps just instead of "reacting" the chamber could give "unable to react". Oh, and the chem. plumbing section should have a note under the reaction chamber description that some reaction may need acclimator to reach favorable conditions otherwise the chemicals won't react.

**Comment by Time-Green** [comment]
> I'm not really sure either. Perhaps just instead of "reacting" the chamber could give "unable to react". Oh, and the chem. plumbing section should have a note under the reaction chamber description that some reaction may need acclimator to reach favorable conditions otherwise the chemicals won't react.

Good idea, I haven’t updated it in a bit

**Comment by Thalpy** [comment]
There's a var that tracks potential reactions that fail due to pH and temperature as part of the reagents datum called `failed_but_capable_reactions` (it just lists the typepaths of possibilities iirc). But it might be hard to figure out if something in there will want to be reacted or not (since water will always add ice to that list for example). I'll probably  have to go over the chambers when I finally get 3.0 in a non buggy state.

**Comment by mGuv** [comment]
I am struggling with this too.

There are some reactions that if you try and acclimate to the right temperature, they happen INSTANTLY in the acclimator and you get junk out the other side - due to not having a chance to balance the PH before it enters the reaction chamber.

The only thing I can think of but haven't tried due to the headache that it would be, is manually acclimating each reagent separately (one per reagent, ew) to the PERFECT temperature (good luck as different reactions have different exo/endo rates) and them combine them in the chamber - and it'll probably ruin it anyway as the reaction has no time to adjust the PH.

I get why you wouldn't want the Reaction Chamber to be a "better" acclimator  - but I'm finding it impossible to do temperature AND pH sensitive reactions.

**Comment by Time-Green** [comment]
I forgot and finally updated the wiki
