### ISSUE TITLE
You can't fix an emagged/hacked APC without fully destroying it and building a new one 

### ISSUE THREAD

**Issue by Sparkezel** [tgstation/tgstation#58324]
## Reproduction:
Have APC emagged/hacked
Destroy it and rebuild it in hope that you can turn on tcomms or other important machines
The newly rebuilt apc (after being given new circuits etc) is still hacked, but the interface is unlocked
You still can't lock it/unlock it and it is still emagged/hacked

**Comment by ArcaneDefence** [comment]
I can't think of anything that allows you to un-emag something outside of deconstructing and rebuilding.
Since the APC remains even if you remove the circuit card and replace it I'm in no way surprised that's the behavior.
This seems more about how APC construction/deconstruction sucks than emags themselves.

**Comment by Iamgoofball** [comment]
this is not a bug, the issue tracker is for bugs

**Comment by Iamgoofball** [comment]
also yeah there's nothing in the game that allows you to un-emag it to my knowledge, so it isn't a consistency issue either

**Comment by Mothblocks** [comment]
i'll mergre whatever makes apc [de]construction less of a massive pain in the ass
