### ISSUE TITLE
Fracture derived brain traumas persist after fixing the fracture

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#58369]
Reporting client version: 513.1536

## Round ID:
irrelevant

## Testmerges:
Manuel
- [[DNM] Revert "Advanced Greyscale Sprite Generation", potentially fix constant server crashing](https://www.github.com/tgstation/tgstation/pull/58313)

## Reproduction:
1. get a fracture in your head
2. get a brain trauma from said fracture
3. go on a stasis bed and have someone fix the fracture
4. have the brain trauma still remain
I'm 99% sure that any fracture derived traumas are suppose to stop existing once the fracture is fixed.

**Comment by ArcaneDefence** [comment]
https://github.com/tgstation/tgstation/blob/d0066e6a262cf77466db359c24e10691bd597bf4/code/datums/wounds/bones.dm#L55-L57

Yeah, that sounds about right.
Related runtime: https://pastebin.com/V91etmts

**Comment by iprice** [comment]
Just was looking into this one myself, it's a very recent bug, not sure I'm adding anything useful but since I bothered to test it before checking if it was already filed, here's what I found.
Running /tg/ revision: 2021-04-09
origin/master: f02c47f947d344541daec6f56519aba1634b850d [worked](https://pastebin.com/M0gFfsfM)
and bugged in
Running /tg/ revision: 2021-04-14
origin/master: 5d2fe9b662535531720792bf0351cfce6c047360 [broken](https://pastebin.com/PwNHQbbr)

Broken in the last 24 hours I think honestly, 48 tops.  Even tried brain surgery (does nothing, as expected) and even lobotomy I tried on a live round, which just gives them an additional permanent trauma

**Comment by iprice** [comment]
Well, this makes my previous post even more redundant, the results of the git bisect are, perhaps unsurprisingly (once you read the entire change log)

560597896cdfe1ca2df45799ad68c0c70583d26a is the first bad commit
commit 560597896cdfe1ca2df45799ad68c0c70583d26a
Author: Thalpy <33956696+Thalpy@users.noreply.github.com>
Date:   Sat Apr 10 23:29:41 2021 +0100

    Fermichem 2.5 - Organ(kinda) related medicines adjustments! (#57806)

Full git bisect final output and the bisect log are [Here (scroll down for git bisect log)](https://pastebin.com/cD73uca3)
