### ISSUE TITLE
only the maintenance sect has access to the ritual that creates ritual totems

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#58377]
this almost certainly isn't intentional, as ritual totems (and the ritual to create them) aren't particularly maintenance-themed and have code for handling deacons (which are currently an honorbound sect-exclusive thing)

**Comment by ATH1909** [comment]
arm's response when I asked him if this was intentional:
![image](https://user-images.githubusercontent.com/42606352/114495028-004f2380-9be3-11eb-9f77-72df07a410c7.png)
thank you arm, very cool

**Comment by ArcaneDefence** [comment]
The only thing they have for handling deacons is preventing them moving them, when consider deacons are specifically supposed to be less holy than the chaplain, it fits perfectly.

https://github.com/tgstation/tgstation/blob/cc74c134e8369c8f373ebcc72d935b70dba4982b/code/modules/religion/religion_structures.dm#L89-L91
https://github.com/tgstation/tgstation/blob/cc74c134e8369c8f373ebcc72d935b70dba4982b/code/datums/components/religious_tool.dm#L143-L146

While it may not be "maintenance-themed" it's shamanistic, and that  follows that theme of a tunnel dwelling tribalistic leader very well. Having further spoken to Arm, he even said it is intentional. 
There's a fair chance he just didn't want to talk to you about picking his features apart.

**Comment by ATH1909** [comment]
:walter:
