### ISSUE TITLE
Character setup initially displays the player model in only one direction

### ISSUE THREAD

**Issue by ArcaneDefence** [tgstation/tgstation#58458]
## Round ID:
Tested locally

## Testmerges:
N/A

## Reproduction:
Boot it up
Open char prefs
Don't change anything
Get ass
![image](https://user-images.githubusercontent.com/51932756/114927052-4a582500-9dee-11eb-8569-2518b7e7a5c3.png)

**Comment by TriggeredBoi** [comment]
Even though I recently touched dummy code, this does not happen in any of my PRed branches but does indeed happen on master; so it's either caused by some other change or the combination of both.

**Comment by TriggeredBoi** [comment]
So it turns out this happens _randomly_ and I just got (un?)lucky that none of my quick tests on my branches had actually experienced this.

Anyways, after a LOT of checking out commits, compiling, launching and relaunching the game to see if it would still happen, I have narrowed it down to https://github.com/tgstation/tgstation/pull/57934. As in, I have confirmed it to happen when checked out on that PR, and it did not happen on the PR directly preceding it after 8+ launches.

Something else I noticed is that the proper icons are actually there, just _under_ the map of the char facing north.
![image](https://user-images.githubusercontent.com/36010999/116650462-87c4c280-a957-11eb-9396-95fdf84b9892.png)
