### ISSUE TITLE
traitor's uplink only checks station pop upon its creation

### ISSUE THREAD

**Issue by SirJohanot** [tgstation/tgstation#58527]

**Comment by SirJohanot** [comment]
I don't often make posts on girhub so pardon me if anything's incorerct. When I discovered this, an admin told me it was probably an oversight and that I should report it on github

**Comment by Fikou** [comment]
are you sure it was 25+ players ingame and not just 25+ players on server? they could be in lobby or observing

**Comment by SirJohanot** [comment]
> are you sure it was 25+ players ingame and not just 25+ players on server? they could be in lobby or observing

no, not completely. I don't know how I can reproduce it myself. The server had something more than 25 players, but the number of living crew I didnt check.

**Comment by Livrah** [comment]
I thought it was intended, can confirm.

**Comment by RaveRadbury** [comment]
Pretty sure I've seen this happen with contractor kits.

**Comment by necromanceranne** [comment]
This doesn't need reproducing, it's definitely a thing since it was a significant enough problem to have been fixed here over on cit https://github.com/Citadel-Station-13/Citadel-Station-13/pull/11768

Essentially, the start of the round population is what determines what is available in the uplink, never updating in accordance with the total players in a round. So if a huge amount of players join late into a round, you can significantly impact the availability of what traitors can purchase from their uplink. I suspect this might also impact war declarations and nukie numbers too. But I'm unsure how it interacts with traitors. Potentially a fresh spawned traitor might have an appropriate updated uplink.

**Comment by SuperNovaa41** [comment]
I thought this was intended? I was sure most people were aware of this.

**Comment by SuperNovaa41** [comment]
> I suspect this might also impact war declarations and nukie numbers too, since that continues to be a major problem for the above reasons. But I'm unsure how it interacts with late spawned traitors from dynamic. Potentially a fresh spawned traitor might have an appropriately updated uplink.

It works on the uplinks initialization. So if you roll mid round you would be able to purchase items that round start traitors wouldn't be able to. (If the population had increased sufficiently)
