### ISSUE TITLE
Mail thought recipient had a different job than they actually did.

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#58742]
Reporting client version: 513.1536

## Round ID:
[161059](https://scrubby.melonmesa.com/round/161059)

## Testmerges:
Manuel
- [Adds new wrinkles to monkey brains](https://www.github.com/tgstation/tgstation/pull/58631)

## Reproduction:
One of the pieces of mail said I was a station engineer, when I was a paramedic, not sure how this happened, and the rest of the mail to me had the correct job listed.

**Comment by ArcaneMusic** [comment]
Mail assigns a player's name and job title at the time that the mail is sent out, with the caveat that it checks against Ckey when opened so that the real recipient of the mail will be available to get it. This is complicated by a few things in theory, like wizard spells that fuck with identity or bodyswapping, but as it checks Ckey, the issue is bypassed.

I realize it's been awhile since this came up, so not knowing is fine, but do you recall if this was early on in a shift? Since the mail delivery fires on economy SS, and it will always fire at roundstart, I wonder if something like an antagonist assignment/job ban/etc could have swapped the name out in some way because the game hadn't fully started yet.

Last question, were you able to open the mail do you recall?
