### ISSUE TITLE
Pump Random Event doesn't seem to be going off

### ISSUE THREAD

**Issue by RaveRadbury** [tgstation/tgstation#58986]
## Round ID:
[161909](https://scrubby.melonmesa.com/round/161909)

## Reproduction:
Mash that `pump random event button`
No random events occur. Sad!

**Comment by Sealed101** [comment]
seems to have been fixed at some point; doubt that it was #82511 since the bit of code didn't really change but oh well
![изображение](https://github.com/user-attachments/assets/31db7040-0227-403e-819a-7ea6a58d570c)

https://github.com/tgstation/tgstation/blob/f3f13d35b1ae2eb4b9c91e4918d3e27d34c41d30/code/modules/admin/verbs/debug.dm#L682-L687
