### ISSUE TITLE
Check Plumbing verb breaks horribly with smart pipes

### ISSUE THREAD

**Issue by Maurukas** [tgstation/tgstation#59168]
## Testmerges:
N/A

## Reproduction:

Enable debug verbs from the debug tab, then in the mapping verb run the "Check Plumbing" verb. Your client will freeze for up to five minutes before blowing out the chat buffer with a list of every single mapped atmos piping segment:

![image](https://user-images.githubusercontent.com/66576896/118551930-218bbe00-b713-11eb-87c0-5d158e6b503b.png)

**Comment by ArcaneDefence** [comment]
I think "no longer supported" is a pretty good phrase here lol

**Comment by Maurukas** [comment]
Probably. I don't think the logic originally used is going to work here, since smart pipes don't connect the same way old pipes did. It might be possible to change it over to something like checking a pipe for <2 connection.

If it can't be, then the verb should be removed as it can cause client crashes in its current state.

**Comment by norill** [comment]
i don't think it should be removed - it is needed with smart pipes more than ever
![2021-05-22 01_46_58-tgstation  _maps_map_files_IceBoxStation_IceBoxStation dmm  - Dream Maker](https://user-images.githubusercontent.com/6893107/119207783-fb597b80-ba8e-11eb-9c71-98244bdd8520.png)
i would detect fuck ups like this. green bridge pipe is not connected to the filter, because the purple pipe is actually a manifold, and not a straight horizontal pipe. in the game that is impossible to spot when the green pipe is above the purple one
