### ISSUE TITLE
Sparks wouldn't disappear

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#59387]
Reporting client version: 513.1533

## Round ID:
[163156](https://scrubby.melonmesa.com/round/163156)

## Testmerges:
- [Toggles harddel searching for use on live [DNM]](https://www.github.com/tgstation/tgstation/pull/59118)
- [Lowers the cold temperature activation threshold for fire alarms/firelocks](https://www.github.com/tgstation/tgstation/pull/59205)
- [[READY] Lighting list cleanup.](https://www.github.com/tgstation/tgstation/pull/59002)

## Reproduction:
![image](https://user-images.githubusercontent.com/66640614/120086837-51ce4780-c097-11eb-8cf7-7290641c9a1c.png)

Even after being fixed, light sparks would replay their animation whenever they came into view. Glass floors stopped showing things underneath them and the arrivals shuttle area was black. 

After a few minutes the spark animation played several times in a row and then everything went back to normal.

**Comment by timothymtorres** [comment]
This looks like a test merge bug from #59002 or some other runtime that broke a bunch of logic.

While testing out a new PR on my local, I accidentally created an endless loop that caused a bunch of runtimes and similar behavior to this.  Shuttle turf was black, glass floors and open-space areas were also black.  My character was slowly suffocating as well.

Whatever caused this likely had a snowball of runtimes that broke everything as was my testing PR.  Also it doesn't seem like there are any matching issues relating to this since it happened.  I'm marking this for cleanup due to the above reasons.
