### ISSUE TITLE
Chemical reaction's pH behaves unintuitively.

### ISSUE THREAD

**Issue by mGuv** [tgstation/tgstation#59503]
## Issue

There is a lot of confusion among players how pH works. I aimed to write a guide to explain it and when writing it, I found that pH when reacting doesn't work at all how I expected.

Take Oil for example, its reaction, as defined in the code and on the wiki, is meant to increase the pH of the solution.

![image](https://user-images.githubusercontent.com/7647687/120869366-3929ca00-c58e-11eb-97b3-392d70c97b11.png)

(H+ consuming means it removes hydrogen ions which in turn would increase the pH, as it makes the solution more basic)

However, if you pre-balance the pH of your Hydrogen, Carbon, Welding Fuel to pH 6, then add them together. You will find the pH goes down. Ultimately pushing it outside of the Optimal range and making impurities.

Frankly, this makes no sense. If the reaction increases the pH normally, why does it DECREASE it when the pH is high? Is the reaction H+ consuming or not?

I've also seen that reactions can just be straight up be impossible to pH control sometimes, due to just how rapidly the pH changes, even when spamming high volumes of buffer. It's frustrating and people seem to really dislike working with Purity as a result, as pH is just too much. This is especially worse on endothermic reactions as they tend to speed up as they react.

## Reproduction:

- Add 30u of Carbon and 30u of Hydrogen to a Beaker
- Put the beaker in a reaction chamber and add basic buffer until it's about pH 6
- Add 30u of Welding Fuel to another beaker
- Put that beaker in a reaction chamber and add basic buffer until it's about pH 6
- Mix the two beakers together and watch the pH in the chamber
- Note that the pH went DOWN not UP

This behaves directly different to just mixing them together normally, which makes the pH go up (due to the three normally mixing to a lower starting pH, due to it having pure hydrogen in it).

So there is something strange here as it behaves two ways, which is not how reactions work in the real world.

## Deep Dive

As always, I ended up in the chemistry code and found what I believe is the culprit. A reaction works as follows:

- Consume some of the Reagents
- Adjust the pH of each Reagent based off of the reaction's hydrogen ion change
- Create the Products of the reaction with the **base pH of that chemical**
- Adjust the pH of the Product based off of the reaction's hydrogen ion change
- Add the product to the container
- Recalculate the entire container's pH

Bold for emphasis on where I think the issue lies.

## Thoughts

Creating the products with their pH set to their defined pH seems wrong. The pH of a solution is based entirely of off it's components. This means a beaker sat at say 14 pH that generated a chemical of 1 pH would somehow actually create that at 1 pH, when that's not how it would work - the solution is homogenous, that beaker would just naturally shift it's hydrogen ions as the reaction consumed/produced hydrogen ions based off of the chemical changes.

I propose changing the reaction code to:

- Consume Reagents and adjust their pH
- Recalculate the beakers total pH (reagents have consumed/freed hydrogen ions at this point)
- Create Products with the pH equal to the container - as that is the pH of the solution, there is no need to adjust the products pH as it came in to existence due to the earlier hydrogen ion change
- Add the products to the container

I have made this change locally and it seems to work however it has made chemistry a lot easier - reactions are far more stable/slow meaning the pH is easier to control. However, it also feels fairer/more predictable/more correct. Maybe another change would be to adjust the ion release/consumption ratios of the reactions to make some more challenging.

Also, Oil has a pH of 4 yet an optimal reaction range of 5 - 9, that also seems wrong? How can the pH of the chemical be outside it's optimal range?

@Time-Green I would love to hear your thoughts on this. I don't have a chemistry background at all and I'm just looking at the numbers. My real issue might just be that oil's optimal pH range is wrong?

**Comment by Time-Green** [comment]
@Thalpy is actually the pH/reaction guy, I’m just the plumbing man. I am actually a chemistry student, but pH mechanics have simplified to a point where it’s moot

I’m not sure it’s a bug or not, but it is weird since, I’ll ask Thalpy

**Comment by norill** [comment]
there are more issues, im not sure if i recall it correctly, but i think every reagent in a beaker has their own current pH, that affects purity, instead of using the "beaker pH" that is shown everywhere. this means that your reaction could be outside optimal pH range even though it shows an optimal pH everywhere.

**Comment by Thalpy** [comment]
Hi! Thanks for the detailed feedback! I really appreciate someone taking the time to write up an issue like this.

So - for the crux of the issue, on the wiki the pH changes are determined algorithmically, which is to say I press a button in ss13 and it puts out a txt of all the reactions. The way it determines how the pH will change is based off the reactions H_ion_release var. What this does is adjust all of the relivant reagents' pH by a factor per 1u created, so it's not accurate. What I could do is add a function to the reaction tester to determine what direction pH will change, but that would require running every reaction to fully update the wiki.

My plan is to go through all of the reactions and tweak them to fit the mechanics better based on how they naturally react and build interactions from there. While doing that I also update the wiki. Oil is one that I haven't got to yet, and it inherits the default reaction range of 5 - 9. Basically, if the range is 5 - 9 then it's likely because I haven't touched it yet. For most of the reactions I try to set it so the default purity is about 75% when you let it react on it's own (except for stronger chems).

As for your thoughts, there's a reason why it works like this - primarily because if you use the chemmaster to hotswap reagents in and out of a reaction you can mess with the pH in a way that doesn't make sense. Originally I planned on having pKa assigned to reagents instead and considered having solvents be their own thing, but I realised to do that I would have to revamp concentration to be independant of volume, and I was concerned of overcomplicating the whole process.

I'm not against your idea of adjusting it however! I'm unsure what effects this would have on the reactions I have been able to tailour to the mechanics. I would agree and expect that that H_ion_release would have to be changed however. I can do some tests after the 20th(when my thesis draft is due), or you're welcome to give it a try if you're interested in that sort of thing!


> 
> 
> there are more issues, im not sure if i recall it correctly, but i think every reagent in a beaker has their own current pH, that affects purity, instead of using the "beaker pH" that is shown everywhere. this means that your reaction could be outside optimal pH range even though it shows an optimal pH everywhere.

This shouldn't be happening at all - It always uses the beaker's sum pH. The other aspect that can affect reactions is the purity of the reactants, which will modify the product's purity by how pure it is. In this case I know oil is an issue as it isn't pure by it's default reaction. I have done some tests to tweak it, but unfortunately I had to dedicate the last few months to finishing up my PhD so I wasn't able to finish it in time (and to be honest I got distracted by implementing states of matter as I wanted t odesign reactions to use those mechanics too).

**Comment by norill** [comment]
> there are more issues, im not sure if i recall it correctly, but i think every reagent in a beaker has their own current pH, that affects purity, instead of using the "beaker pH" that is shown everywhere. this means that your reaction could be outside optimal pH range even though it shows an optimal pH everywhere.

nvm this, i made some tests and it appears i was wrong :P

**Comment by mGuv** [comment]
Thanks for the replies. I wish I knew about Chemistry to comment on what would be best to do. @Thalpy I appreciate that you're busy so I'll see if I can help.

Like I have no idea if what I'm talking about is even an issue or how it does work (take the oil example where the pH can go up/down based on starting pH).

I have made the change locally and played with it and it still doesn't quiet behave 100% how I expect (it does until it reaches the end of the reaction where the pH shifts in the opposite direction to what I'd expect! Might be an issue with what I've done).

The main issue with my changes is the pH now moves very slowly - which makes it far easier to automate, control in a reaction chamber and set up the pH before by just adding some buffer. I am unsure what this would do to the 'meta' of Chemistry, i.e. would it become too easy? I can already automate 100% pure of most healing chemicals I need. I only found this when I tried to write a guide.

Could a chemical ever have a natural pH outside of it's own optimal range? Or is that literally just the case of "no all chemicals/reactions were updated and inherit from some base component that might not make sense".

**Comment by norill** [comment]
> 
> Could a chemical ever have a natural pH outside of it's own optimal range? 

mannitol

**Comment by mGuv** [comment]
> > Could a chemical ever have a natural pH outside of it's own optimal range?
> 
> mannitol

I mean in real life. There are plenty in SS13.

**Comment by mGuv** [comment]
> 
> S which is to say I press a button in ss13 and it puts out a txt of all the reactions.
> 

@Thalpy apologies for the direct ping but I was doing some thinking and recalled you saying this. Is this code that outputs this part of tgstation or is it something you have locally? I'd like to see the code to do similar to help me debug some issues. It'd be great if I could just hit a button and have it check all chemicals/reactions and log something out.

**Comment by Thalpy** [comment]
> 
> 
> > S which is to say I press a button in ss13 and it puts out a txt of all the reactions.
> 
> @Thalpy apologies for the direct ping but I was doing some thinking and recalled you saying this. Is this code that outputs this part of tgstation or is it something you have locally? I'd like to see the code to do similar to help me debug some issues. It'd be great if I could just hit a button and have it check all chemicals/reactions and log something out.

It is indeed in tgstation! Though I don't recommend using it on the live server, you'd need to do it on your own test server. Under the debug tab there is a button called "Parse Wikichems" which will write the wiki code for your to a text file. If you enter the name of a reagent it should output that, and you can do multiple by putting a comma between entries (nospaces between them). It's designed so you can just copy and paste it over to the tgwiki too.

**Comment by Mooshimi** [comment]
https://docs.google.com/document/d/1bDPd4N3ZyJCGQyLAx5nZrzGooUBgQkxocqdIYb40vN0/edit#heading=h.byik7dru2dap

**Comment by Mooshimi** [comment]
> > there are more issues, im not sure if i recall it correctly, but i think every reagent in a beaker has their own current pH, that affects purity, instead of using the "beaker pH" that is shown everywhere. this means that your reaction could be outside optimal pH range even though it shows an optimal pH everywhere.
> 
> nvm this, i made some tests and it appears i was wrong :P

I said it wasn't a bug because of this btw, along with Thalpy's response about the formula being intended but open to change
