### ISSUE TITLE
Diagonal Tiles Display Wrong Turf For Liquid Plasma

### ISSUE THREAD

**Issue by unit0016** [tgstation/tgstation#59605]
## Round ID:
N/A, Local branch

## Testmerges:
N/A, Local Branch

## Reproduction:
Build slanted wall next to plasma lava on icemoon.
![image](https://user-images.githubusercontent.com/50649185/121609632-49282a80-ca22-11eb-8c83-26f75dde9daa.png)

The problem here's that it's inheriting that it should display lavaland's basalt, rather than displaying snow.

**Comment by Mooshimi** [comment]
![image](https://user-images.githubusercontent.com/85910816/146624789-d3858dbb-15ba-41b4-ba6f-e0d0392ddf97.png)
looks like plasma lava just doesn't have the rock overlay which makes it look super weird. but logically there is no lava in that tile, instead there is a wall that is half not seen due to the wall wrap.

**Comment by Mooshimi** [comment]
wait why is there rock in that picture you have if it's on icebox... it's supposed to be snow.....

**Comment by timothymtorres** [comment]
![dreamseeker_22Z8WjhHe9](https://user-images.githubusercontent.com/5195984/146625103-708b1ce8-b99f-4efe-a4e8-0b490035f031.png)

**Comment by unit0016** [comment]
> wait why is there rock in that picture you have if it's on icebox... it's supposed to be snow.....

thas the bug

**Comment by Mooshimi** [comment]
> > wait why is there rock in that picture you have if it's on icebox... it's supposed to be snow.....
> 
> thas the bug

Being descriptive in your opening comment would help with this. Multiple things could be a bug there, including how the lava edge doesn't wrap with the wall and is instead straight and janky.

**Comment by Sealed101** [comment]
thanks smoothing
![изображение](https://github.com/user-attachments/assets/d93c126e-52f8-4a17-8dd0-2f5d6950d740)
it's inheriting the basalt underlay from the plasma, which is a `/turf/open/lava` subtype, so go figure
also it's a funky-stupid issue with these turfs overall as it picks the turfs around itself to smooth with instead of the one that's underneath
relevant code
https://github.com/tgstation/tgstation/blob/3a6007b7970e97fcc196fc031d1934dbca695f70/code/__HELPERS/icon_smoothing.dm#L496-L507

it reaches the neighbouring plasma-lava turf's underlay icon
https://github.com/tgstation/tgstation/blob/3a6007b7970e97fcc196fc031d1934dbca695f70/code/game/turfs/open/lava.dm#L181-L184
and uses that

we could just swap the snow's code in this tidbit to use the snow's icon but that would make plasma rivers less immersive since it would always mean that they are snow-bound... or something. i'm sure wallening woulda fixed it _sadsmile_

**Comment by unit0016** [comment]
now that I think about it again; couldn't we just move the basalt underlay to `/turf/open/lava/smooth`? the underlay's only being overriden for the benefit of smooth lava anyways

**Comment by unit0016** [comment]
> sure but then someone is going to make a non-snow map with a plasma river, place some diagonal walls, then open this issue again

i'm someone :trollface:

all the same though I tried moving it to lava/smooth on a local instance; and this actually does fix the issue w/o that being a problem at all:

![image](https://github.com/user-attachments/assets/398c0dbd-8007-4bd7-bbb2-b08c5fba6d48)


in the process though I discovered this also applies to chasms; so uhh. give me a minute i have to get my /tg/ branch up to date and fix both parts for real
