### ISSUE TITLE
It is possible to generate energy in a Chem Dispenser with a specific reaction.

### ISSUE THREAD

**Issue by mGuv** [tgstation/tgstation#59663]
Me again with another Chemistry bug (I play too much chemist).

## Issue

With a very specific set of steps you can cause a strange issue with a REGULAR beaker:

- It says it is full when in fact it's at 35.01 units
- Using this beaker in a chem dispenser and clicking dispense on ANY chemical and value will instead GIVE energy to the dispenser, with no change to the beaker.

I found this by trying to record some recipes in a chem dispenser and I was making one for Basic Buffer but made a mistake (I didn't use enough Hydrogen).

## Reproduction Steps

- Put a REGULAR (the small 50u beaker) beaker in a Chem Dispenser
- Record a Recipe of:
  - 15u Hydrogen
  - 5u Nitrogen
  - 10u Chlorine
  - 10u Oxygen
  - Hit save
- Click your new recipe to dispense it in to the beaker
- Wait for the beaker to finish reacting
- Click dispense and watch the energy go UP, note that nothing changes in the actual beaker
- You now have a magic beaker of infinite energy. You can put this is in any other chem dispenser and the behaviour stays. It seems to be attached to the beaker itself.

## Thoughts

I haven't looked in to the code for this one but something really odd is happening as this doesn't happen if you mix the exact same chems manually (and doing Nitrogen last to kick it all off in the same starting condition)

I -THINK- the macro step, dumping all the chems in at once, then looks for available reactions and it sees the 15 Hydrogen + 5 Nitrogen as 15 Ammonia, so it starts reacting, only the second some Ammonia is available, it then all combines and starts making the Basic Buffer. When all the Nitrogen runs out, the beaker ends up at 35.01u, but if I had to guess, I'd say it's reserved 15u of the beaker for the original outputs it thought it was going to make.

That explains why it thinks the beaker is full. What it doesn't explain is why on earth using this beaker in a Chem Dispenser magically generates energy in the dispenser...

This same issue doesn't seem to work in the 100u beaker. I didn't try any others.

**Comment by RandomGamer123** [comment]
The beaker being full when it isn't is an issue i've seen previously although at the time I was unable to reproduce it so thanks. The negative energy probably comes from 
```
var/free = R.maximum_volume - R.total_volume
var/actual = min(dispense_amount, (cell.charge * powerefficiency)*10, free)
``` 
Where actual is the power used (before powerefficiency is considered)
The free value here would be negative, meaning that it becomes using power.
I have no idea why free is used in this equation at all though.

**Comment by TemporalOroboros** [comment]
The free value is so we can't try to add more reagents than we have space for.

**Comment by mGuv** [comment]
Thanks for the tips both, I didn't have any time to look at it today.

Luckily I imagine the energy part is embedded directly in the reaction chamber code so should be easy to fix. The mystery issue of the beaker though might be a lot harder... The game is reporting it as `35.01u`, even in those calculations it seems... But something at the transfer level stops it.

I'll step through that code tomorrow and have a look.

**Comment by TemporalOroboros** [comment]
Found it. This is a combination of two bugs. The first bug is the obvious one in the reagent dispenser code with the uncapped free volume calculation. It tries to add a negative quantity of reagent to the beaker and withdraws a correspondingly negative amount of power from the cell. The result is no change in the beaker and power added to the cell. This is possible because the beaker ends up in a state where it has a `total_volume` greater than its `maximum_volume`. This is due to the second bug.

When the beaker updates its `total_volume`, which can happen basically whenever anything changes but especially often when reacting, the reagent holder sets the `total_volume` of the beaker to zero and then loops through all of the reagents in the beaker tallying up their volumes. One of the other things the proc responsible for this does is does is clear out any reagents sufficiently low volumes. When it clears one out it deletes it, which initiates another round of the same procedure. Since the accumulator is the object variable and it's only ever reset at the beginning of the update proc this means that the proc can double-count all of the reagents after the last deleted reagent. This makes it possible to wind up with a `total_volume` greater than the `maximum_volume` of the container.

The given macro makes the last tick of the reaction enter an `update_total()` call with a _tiny_ amount of remaining hydrogen. The hydrogen, as the first reagent, gets deleted and sets off another round of `update_total()` which tallys up the other reagents in the beaker. Then it returns to the original `update_total()` call and counts them all again, giving it a `total_volume` of ~70u... out of 50u. Then you try to dispense more reagents and the dispenser takes the energy for -20u out of the cell.

**Comment by TemporalOroboros** [comment]
For people confused about the procedure

1. Proc update_total() is called
2. `total_volume` is set to 0
3. For each of the reagents in the beaker
     1. If there's not enough of the reagent to bother remove this reagent and do this entire process once.
     2. Otherwise, add the volume of the reagent to `total_volume`

Notice if there's one reagent with really low volume followed by reagents with enough volume to care about the one with low volume will get deleted and all of the reagents will be counted again. Then it will drop back into the original loop and count everything after that reagent a second time.

**Comment by TemporalOroboros** [comment]
The solution is to both add guards to the reagent dispenser proc and to switch update_total() to using a local proc var instead of the object var.

**Comment by mGuv** [comment]
Great work.

I hadn't had a chance to look at it yet, I've been side tracked with another project.

Is this a fairly easy fix and do you think you'll be raising it? I'm keen to get this fixed as it's an exploit. Whilst it's not the worse exploit in the world - Energy can be an issue for powergaming chemists, as they could easily churn out thousands of chems with this trick at round start. Which is normally impossible due to no upgrades and power not set up.
