### ISSUE TITLE
antimagic doesn't make you immune to honk staff projectiles

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#59903]
because they're technically bullets, not magical projectiles, for some reason

**Comment by AlinaStarkova** [comment]
i tried working on this and i made it so those with anti-magic cannot be slipped or harmed by the honk staff or the mime finger gun, however in the case of the honk staff the banana still flies through you instead of vanishing and the finger gun still makes you draw blood and such (but you take no damage). nothing I have tried would make them actually be "blocked" rather than give you noslip or prevents damage, which is odd since im basing it off of how literally everything else in anti-magic stops things. ill work on it some more later and may even add anti-magic to allow you to pass through mimes walls as well.
