### ISSUE TITLE
Input delay issue with BYOND's 514. version

### ISSUE THREAD

**Issue by exymian** [tgstation/tgstation#59940]
## Round ID: 
[165148](https://scrubby.melonmesa.com/round/165148)

## Testmerges:
#59914: 'Cache asset/mappings results' by Mothblocks at commit 0a909af7f4

## Reproduction:

 - The issue is input delay that happens only on clicks and this delay can sometimes queue up(which you can see if you spam right click or left click then try to type) and continue after you dont click anywhere. I have encountered this issue after updating to version 514. , i have tried .1557, .1556, .1555, .1554 and so far all of these subversions have the same issue. Im still testing the subversions.

 - I have found out that not everyone has this issue and everyone who has it has informed me that it occured after they updated byond.

 - The way i installed was just downloading the setup from byonds website and running it, thats how i encountered the issue.
 
 - Clearing BYOND's and IE's cache did not help.

**Comment by ArcaneMusic** [comment]
I'll pre-emptively label this as a byond issue until we can learn more about it.

**Comment by exymian** [comment]
Thanks, can a byond issue be fixed ?

 Also in the round i posted, you can see the input queue i talked about around the time i say something about .1555 in ooc, hope it makes it easier

**Comment by MrStonedOne** [comment]
> Thanks, can a byond issue be fixed ?

Yes, but you generally have to find the exact byond version that caused the issue for byond to be able to figure out how the issue came to be.

One trick I would suggest is to do a binary search, don't test version by version.

For every version that has it, you can assume that all later ones also have the issue, and for every version that doesn't have it, you can also assume every earlier version also doesn't have it so instead test the halfway point between the earliest that you know has the bug, and the latest version you know doesn't have the bug.

Should let you figure out the exact version that introduced it in only 8 to 10 tests.

**Comment by LummoxJR** [comment]
This appears to be related to http://www.byond.com/forum/post/2683666. That bug report is actually lacking some information, but according to Repo82 there's a timing issue in 514.1547 onward that appears to be related to the fix for inaccurate timers at high precision. (To be honest I'm not sure if F0lak's issue is really the same thing as Repo82's or not, because I don't have all the information. But Repo82's info definitely lines up with this /tg bug report.)

I've been wrestling with that bug for a while and I finally managed to cobble together a fix just a few minutes ago, so I'm hoping 514.1558 will eliminate the problem.

**Comment by exymian** [comment]
I am sad to announce that 514.1561 still has the issue. The problem may or may not scale with how bad your pc is.

**Comment by Pinkufeck** [comment]
yeah there's definitly still input lag

**Comment by exymian** [comment]
The issue is still there in version 514.1568.
