### ISSUE TITLE
PAI Loudness Booster still dont work

### ISSUE THREAD

**Issue by SamDDBS** [tgstation/tgstation#60474]
## Round ID:
[166708](https://scrubby.melonmesa.com/round/166708)

## Testmerges:
#60187

## Reproduction:
be pai
buy loudness booster
go to loudness booster menu
buttons will click but dont open up synthesizer window
reeeeeeeeeeee at admins for refund

**Comment by timothymtorres** [comment]
#59719, #48925, #51151, #50796 are all duplicates

**Comment by SamDDBS** [comment]
admin who was helping me refund loudness booster said "make another lol"

**Comment by timothymtorres** [comment]
So I finally figured out why pAIs can’t use musical instruments while not in holoform.  It’s because they have `TRAIT_HANDS_BLOCKED` when in normal intellicard form.  The relevant code change needs to be made in `obj/item/instrument/ui_interact(mob/living/user)` in file `code/modules/instruments/items.dm`

Just add a istype for pAI to bypass this

**Comment by SamDDBS** [comment]
this issue can be bypassed by simply entering a state where the TRAIT_HANDS_BLOCKED is not active, which can be done by not being carded as pai
still leaving this issue up because it is still an issue, maintainers or whoever can close this when somebody fixes being unable to open synthesizer ui as carded pai
