### ISSUE TITLE
You still get turned into a moth from teleporter accidents even if moth week is over

### ISSUE THREAD

**Issue by FlamingCheese** [tgstation/tgstation#60623]
## Round ID:
167007

## Reproduction:
Use a non calibrated teleporter, get turned into a moth even if moth week is over

**Comment by Mothblocks** [comment]
> probably irrelevant

No. It isn't irrelevant, specify it or this is useless to future people working on it. BECAUSE: I had a round the other day which was *not* moth week, and a teleporter accident made me a fly--round 166937.

THAT BEING SAID, I noticed during the marathon round that a lot of stations had moth in their name, when I know moth week has ended (especially since I was turned into a fly myself).

**Comment by Mothblocks** [comment]
Which is to say--MOTH WEEK IS BROKEN 3 YEARS IN A ROW BABY LETS GOOOOO 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉

**Comment by Mothblocks** [comment]
Round 167009 had Rosy Maple in the name--MOTH WEEKS BACK BABY IT NEVER ENDS

**Comment by Mothblocks** [comment]
![image](https://user-images.githubusercontent.com/35135081/127762012-c7b9f1c6-f704-4d26-89cf-69100d0f4298.png)
LETS GOOOO

**Comment by FlamingCheese** [comment]
Round id is in the issue report now

**Comment by interestingusernam3** [comment]
Mothblocks wild ride

**Comment by ATH1909** [comment]
not a bu- wait a minute...

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/8c7e4ef6ee0b6e60783ccb084d60138353b2e2be/code/game/machinery/teleporter.dm#L65-L91

**Comment by Mothblocks** [comment]
It has nothing to do with that code because the bug is moth week lasting longer than it was supposed to

**Comment by Sealed101** [comment]
i missed this year's moth week - did it cause any issues after it ended?

**Comment by Mothblocks** [comment]
Going to assume fixed after #68280
