### ISSUE TITLE
Icebox's Bar/Kitchen Issues

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/tgstation#60711]
Reporting client version: 513.1542

## Round ID:
[167246](https://scrubby.melonmesa.com/round/167246)

## Testmerges:
- [Disable ALL slips until they are fixed AND admin tool shortcomings get resolved.](https://www.github.com/tgstation/tgstation/pull/60611)

## Reproduction:
1. The restaurant portal that is currently in the bar is for the chef, It should be a bar one.
2. Kitchen is missing a grinder.
3. Kitchen is missing a food processor.

**Comment by CMDR-Gungnir** [comment]
Also, strangely, you cannot use wrenches on the tables in the bar to disassemble them?

**Comment by AlinaStarkova** [comment]
> 
> 
> Also, strangely, you cannot use wrenches on the tables in the bar to disassemble them?

because its the wrong subtype, its a special bar meant for the shuttles so you cant harrass the bar drone, hence why you cant climb onto the icebox bar counter either

**Comment by CMDR-Gungnir** [comment]
> because its the wrong subtype, its a special bar meant for the shuttles so you cant harrass the bar drone, hence why you cant climb onto the icebox bar counter either

Interesting to know!  I kinda hope it isn't intentional, because a lot of bartenders I've seen have wanted to redesign it a little themselves

Oh! Another issue I've remembered, the disposals pipe for the entire Service Department is broken under the Bartender's inner-table, and will eject all contents there.

**Comment by AlinaStarkova** [comment]
> 
> 
> > because its the wrong subtype, its a special bar meant for the shuttles so you cant harrass the bar drone, hence why you cant climb onto the icebox bar counter either
> 
> Interesting to know! I kinda hope it isn't intentional, because a lot of bartenders I've seen have wanted to redesign it a little themselves
> 
> Oh! Another issue I've remembered, the disposals pipe for the entire Service Department is broken under the Bartender's inner-table, and will eject all contents there.

doubtful its intentional, the subtype literally just says wood/bar and gives no indication in sdmm that its a shuttle sybtype, i already have a PR ready to fix this as well as one more issue on icebox. i just have to wait until the current PR to fix icebox service disposals pipes is pushed, because they will conflict if i PR it now since we edit the same single tile lol

**Comment by CMDR-Gungnir** [comment]
> because its the wrong subtype, its a special bar meant for the shuttles so you cant harrass the bar drone, hence why you cant climb onto the icebox bar counter either

isn't it possible to have them be part of the same PR? I don't really know how github works, but I see collaboration PRs all the time.

**Comment by AlinaStarkova** [comment]
> 
> 
> > because its the wrong subtype, its a special bar meant for the shuttles so you cant harrass the bar drone, hence why you cant climb onto the icebox bar counter either
> 
> isn't it possible to have them be part of the same PR? I don't really know how github works, but I see collaboration PRs all the time.

you could, but i wouldnt get GBP for it, and i need some GBP since i have a few features i plan to make after the freeze

**Comment by Maurukas** [comment]
Fixed in #60708
