### ISSUE TITLE
Cyborgs can use jedi mind powers to right toppled vending machines wirelessly.

### ISSUE THREAD

**Issue by ZeroMODE0** [tgstation/tgstation#60750]
## Round ID:
[167356](https://scrubby.melonmesa.com/round/167356)

## Reproduction:
The chemist built themself a suicide chair, where an unwrenched vending machine goes around and around and shoots through a disposals loop to splatter themself until they're so thin you can't even click on them.

when I stopped the conveyor, I could click on the vending machine as though I were right next to it, wirelessly righting it.

**Comment by ZeroMODE0** [comment]
I tried this on round 167363 and it worked, the machine was toppled and I could right it as though I was using telekinesis.

**Comment by Mooshimi** [comment]
#60693 may have fixed this

**Comment by AlinaStarkova** [comment]
> #60693 may have fixed this

untested but i dont think it did. my refactor wouldnt have changed that bit.

my guess is tht a toppled vending machine is still actually considered a fully functional and interactive machine and that it simply has an override early return for righting it rather than opening its UI. hence the borg is able to click on it, because its "not broken, not in maintenance, no panel open, interactive" etc ... 

you can probably fix this by making it so when toppled the machine has no power. if it has no power then borgs cant interact with it at range. but that might make it so humans cant when adjacent, vending machines may just need a refactor, idk why it was coded so that toppled vending machines are fully active machines in the first place.

**Comment by timothymtorres** [comment]
@AlinaStarkova thats actually a pretty robust solution
