### ISSUE TITLE
something is causing gold slime cores to produce a frankly comical amount of roaches

### ISSUE THREAD

**Issue by nianjiilical** [tgstation/tgstation#60931]
## Testmerges: 
#60302: '[READY] Adds memory system, and engraving walls with chisels' by tralezab at commit d7d323e63c
#60905: 'Add Requests Manager to View All Prayers, Centcom/Syndicate Requests & Nuke Code Requests in Round' by bobbahbrown at commit 5a55037092
#60694: 'Basic Mobs: the cooler simple mobs that run on datum AI. (With reworked cockroach AI as proof of concept)' by AMonkeyThatCodes at commit 25152bd8ac

## Reproduction: 
i dont know exactly but i was a creature and the xenobiologist said they would get me a fugu gland and then popped like 20 gold slime cores and i swear 85% of what came out was hauberoaches and glockroaches

ive played a shitload of xenobio and theres no way this many roaches is a coincidence

**Comment by timothymtorres** [comment]
I think #60694 might be causing this issue.

**Comment by timothymtorres** [comment]
@nianjiilical Good catch.  On the coder discord we identified the problem and @AMonkeyThatCodes will fix it when he can.

**Comment by Ghommie** [comment]
I doubt this is still an issue @timothymtorres.

**Comment by timothymtorres** [comment]
@Ghommie I used gitblame to search for code and procs related to the gold slime extract.  I searched several files and I saw nothing that indicated any code had been changed since #60694 was implemented.  It could be possible that the problem was in the basic mob code or the list of neutral/hostile/friendly mobs but I'm not going to dig that deep.  

If someone can test this with several gold slimes using plasma, blood, and whatever injector chems are possible. (it's been a while since I've done xenobio)  If the roaches aren't getting spammed at spawn then this should be considered resolved.

**Comment by Ghommie** [comment]
This had something to do with an indentation problem that caused roaches (the only basic mob at the time) to be added to th spawnables static list each time `create_random_mob` was called.
The reason why you couldn't find verify it's fixed through git blame was that the commits were squashed before being merged. It's fixed in a commit in the same PR (https://github.com/tgstation/tgstation/pull/60694/commits/9547e6b157eba52bf70494125ea58751c9f49b2a)
