### ISSUE TITLE
Banana glutton regurgitate not working and health starting at greater than 150%

### ISSUE THREAD

**Issue by golfer45** [tgstation/tgstation#60933]

**Comment by timothymtorres** [comment]
It appears the clown glutton is missing a `maxHealth` variable so that's why health is 150%.

https://github.com/tgstation/tgstation/blob/3c4196e9600c625c1d5080e56365d5f19f61f21e/code/modules/mob/living/simple_animal/hostile/retaliate/clown.dm#L296-L317

Regurgitate is an ability that fires objects that were digested.  

https://github.com/tgstation/tgstation/blob/3c4196e9600c625c1d5080e56365d5f19f61f21e/code/modules/mob/living/simple_animal/hostile/retaliate/clown.dm#L391-L405

@golfer45 can you confirm if the object was fired from the glutton clown?

**Comment by golfer45** [comment]
I did not notice anything happening when attempting to regurgitate, its been a month but I also think I was unable to eat more becuase I was full, and unable to regurgitate.
