### ISSUE TITLE
Linking Golem ORM to Ore Silo Deletes Everything in ORM

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#60944]
As stated on tin. ORM is emptied, no materials come out.

Round ID: [168146](https://scrubby.melonmesa.com/round/168146) (and more)

Reproduction: Build an ore silo and link it to the ORM.

Problem with reproduction: not always consistent. Sometimes it doesn't happen and it links normally. We've tried to reproduce it in the Thunderdome, and been completely unsuccessful. But for some reason, linking the golem ORM to an ore silo has wiped it clean six or seven times now, for me alone - there were other instances of this, too.

**Comment by dragomagol** [comment]
I see the round linked was on Icebox, and there's been issue with Golems and the ORM on Icebox before (#56631). My guess is that the ore you were seeing and depositing into the ORM was going to the station's silo.

**Comment by AnonymousNow** [comment]
Possibly, though that doesn't explain why it would do that in the first place - normal behaviour for linking an ORM to a silo is to boot all the materials out, but they just vanish. And once linked, there's no problems for the rest of the round - it's not like future ore is sent to the wrong silo.
What you're saying about Icebox seems like a good shout. Is the Icebox station silo on one of the mining Z-levels?

**Comment by dragomagol** [comment]
It spitting out ore when connected would be the case if it wasn't connected in the first place. Next time you see it happen, check to see if it's on Z2; I suspect that's the issue, it being on a station Z. Silo should be in the vault, which I think is Z1.

**Comment by TheBonded** [comment]
the issue here is that, as has been said earlier, on icebox the golem ORM will be connected to the station silo if the ship spawns on the second z level. in this case, all ores you deposit are NOT stored in the ORM; they are being stored in the station's silo. because of this, when you unlink the ORM it has no ores inside it to spit out, which is why it seems like they disappear. This is less that the ores are being deleted and more that the golem ORM shouldn't be connected to the station silo.

**Comment by githubuser4141** [comment]
Not sure if it's related, but if you build a new and unsynced ORM on the station, dump materials into it (in this case 100's of iron, gold, silver, etc) then dismantle it thinking it'll dump all the mats out, well, turns out it just vaporizes 1000's of materials instead of dumping them. At least they don't go in the station silo and they're not there when you rebuild it.

**Comment by SuperNovaa41** [comment]
there needs to be a way to create multiple ore silo networks on the same zlevel
