### ISSUE TITLE
Borg names don't change on model change anymore

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#61080]
## Round ID:
Over multiple rounds

## Reproduction:
Previously when a borg chose a model it would go from being "Default Cyborg-985" to something like "Engineering Cyborg-985", but this stopped happening at some point.

**Comment by Prometheos2** [comment]
I think I found the problem.
Cyborg names are all defined as custom ones, and those are kept on model change.
Shells also are affected, although the names are reset on deployment—so quitting and rejoin a shell resets its name to something referring to the model.
___
_/mob/living/silicon/robot/fully_replace_character_name_ proc (l.659 in robot.dm) updates _custom_name_ to the _new_name_ parameter.
It is called by _setup_default_name_ (initialization) and _updatename_ (model change), since the August 13th (#60060); most likely as it should.

I will have to test on a local server, but that looks like it might soon be a thing of the past.

**Comment by Sealed101** [comment]
got fixed at some point so the default shells properly rename themselves to a module-appropriate name
though if they then switch to a new model it will stay the same but iirc that was the behavior before this got broken
oh well
