### ISSUE TITLE
Borg alert panel doesnt work at all

### ISSUE THREAD

**Issue by FlamingCheese** [tgstation/tgstation#61093]
## Round ID:
[168612](https://scrubby.melonmesa.com/round/168612)

## Testmerges:
#60694 

## Reproduction:
borg alert panel shows no categories for alerts (it should have fire alarm air alarm motion and burglar alarms)
neither do alerts show up in the chat
station alert consoles works properly though

**Comment by twilightwanderer** [comment]
I found out that this bug is related to the introduction of listeners into the alarm system by [this request](https://github.com/tgstation/tgstation/pull/60060). The listener from this query creates and works fine in consoles and programs, but is completely unwilling to work with cyborgs and AI. I've been trying to solve this problem, but so far my search for a solution is fruitless.

**Comment by LemonInTheDark** [comment]
yeah this is most likely my fault, ahhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh

@twilightwanderer if you wanna chat about it bug me on discord yeah? I'm some variant of potato there

**Comment by twilightwanderer** [comment]
> 
> 
> yeah this is most likely my fault, ahhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
> 
> @twilightwanderer if you wanna chat about it bug me on discord yeah? I'm some variant of potato there

This is no longer necessary. [#61070](https://github.com/tgstation/tgstation/pull/61070)

**Comment by LemonInTheDark** [comment]
Well damn nice
