### ISSUE TITLE
Some things can't be ctrl-click pulled anymore, but CAN be pulled through the verb

### ISSUE THREAD

**Issue by Mothblocks** [tgstation/tgstation#61276]
On round 169145, I tried to pull a PACMAN but couldn't through ctrl-click, I had to use the verb.

I also believe that rechargers are the same--only pullable through verb.

**Comment by Ghilker** [comment]
caused by #60693 they added can_interact to ctrl_click checks 
![image](https://user-images.githubusercontent.com/42839747/132316643-5c14c0c3-53e5-451d-b775-b9350469c483.png)
this also causes thermomachine pulling to fail because you need to have the panel open to drag them (un-anchored) and the check fails because 
![image](https://user-images.githubusercontent.com/42839747/132316892-5b752a78-5584-41fa-98cf-6fd2352c7988.png)
and the flag can't be added because it would cause other issues like usable ui and controls while the panel is open/machine disconnected

**Comment by AlinaStarkova** [comment]
> 
> 
> caused by #60693 they added can_interact to ctrl_click checks
>image
> this also causes thermomachine pulling to fail because you need to have the panel open to drag them (un-anchored) and the check fails because
> image
> and the flag can't be added because it would cause other issues like usable ui and controls while the panel is open/machine disconnected

to be clear, panel being open isnt specifically whats failing the check, it being unanchored is whats failing the check (in the case of thermomachines, both are whats causing it, but it being unanchored is whats failing it for all machines)
