### ISSUE TITLE
stick pistol dropping code doesnt work

### ISSUE THREAD

**Issue by Fikou** [tgstation/tgstation#61281]
```
/obj/item/gun/ballistic/automatic/pistol/stickman/pickup(mob/living/user)
	SHOULD_CALL_PARENT(FALSE)
	to_chat(user, span_notice("As you try to pick up [src], it slips out of your grip.."))
	if(prob(50))
		to_chat(user, span_notice("..and vanishes from your vision! Where the hell did it go?"))
		qdel(src)
		user.update_icons()
	else
		to_chat(user, span_notice("..and falls into view. Whew, that was a close one."))
		user.dropItemToGround(src)

```
the drop item to ground code doesnt work, so you can obtain a makarov from the stickman ruin
also its shit code in general

**Comment by necromanceranne** [comment]
So the intent here is clearly to prevent the user from acquiring the gun, since either result causes them to be unable to equip the gun. Yet for some reason there is a probability that it doesn't delete itself instantly, yet that still doesn't otherwise let you pick up the gun? Or like, just not allowing the stickmen to drop the gun at all? I'm not entirely sure what the logic of this code actually is.
