### ISSUE TITLE
co2 is not on the dangerous gasses alert list

### ISSUE THREAD

**Issue by Mooshimi** [tgstation/tgstation#61288]
## Reproduction:
Open co2 canister. Admin does not get an alert on open like with plasma. This is a dangerous gas.

**Comment by TheBonded** [comment]
This is less of a bug and more of a consistency issue (which are still logged here in the issues section), though I wouldn't say CO2 is as dangerous as plasma, since it's easily counterable with the internals in your bag, and it gives anyone breathing it a big alert box in the top right warning them that they can't breathe here.
