### ISSUE TITLE
Pixel Scaling always set to "Stretch to Fit"

### ISSUE THREAD

**Issue by ProfessorSniff** [tgstation/tgstation#61535]
## Testmerges:
none on local

## Reproduction:
Setting your pixel scaling to "Pixel perfect 1x/1.5x/2x/3x" in the game preferences menu doesn't actually set your scaling to what you selected. Closing and re-opening the menu reverts the setting to "Stretch to fit."

![image](https://user-images.githubusercontent.com/65641177/133874019-5132c3df-b54e-45be-8423-8a3939dae36d.png)

**Comment by newfren** [comment]
possibly related to #61533? How many preferences don't respect that you've changed them.

**Comment by Mothblocks** [comment]
it's probably stupid bullshit relating to the fact that this is a choiced preference based on numbers, which the system doesnt handle too well

**Comment by Wayland-Smithy** [comment]
How is this not high priority? IMO this is pretty major regression of an essential graphics option. 

I was lucky until now and managed not to change my pref since the new UI was introduced only to discover that not only am I unable to change from 2x to 1x temporarily for a screenshot I am also now prevented from getting back to 2x and stuck with stretch 😡
