### ISSUE TITLE
Alt Clicking a tile with glass on it will not show pipes on that tile

### ISSUE THREAD

**Issue by golfer45** [tgstation/tgstation#61699]

**Comment by timothymtorres** [comment]
So I asked about this a while back when I was doing some mapping stuff and this is intentional.  Players were using alt clicking behavior underneath windows to cut wires, smash grilles, etc. basically it was an exploit.  So the coders made it so that anything under windows cannot be interacted with.

There is a caveat though.  If you are wanting windows to allow pipes to be interactable you can set the layer for the affected windows and then pipes will spawn on top of the window and be clickable.

**Comment by LemonInTheDark** [comment]
Rather then being intentional, I get the feeling this was the result of windows going from all directionals to solid one tiles
That said, I think it makes more sense this way, and don't like the idea of people cutting wires under grills and such.

The layer solution is kinda hacky, and I think looks a bit crummy. Also makes the spaces impossible to replicate, which kinda sucks. Maybe you could do something with flags? but I'm pretty sure this is byond internal stuff.

**Comment by timothymtorres** [comment]
> The layer solution is kinda hacky, and I think looks a bit crummy. Also makes the spaces impossible to replicate, which kinda sucks. Maybe you could do something with flags? but I'm pretty sure this is byond internal stuff.

It's definitely a cheap hack but it'd only be used for atmos and the SM windows.  Might even want to make this a new glass type or something.
