### ISSUE TITLE
Simple rotation on machineries that needs power are somewhat broken

### ISSUE THREAD

**Issue by vincentiusvin** [tgstation/tgstation#61852]
## Reproduction:
#60693 implementing can_interact on atom level alt and ctrl click directly seems to have broken a few interactions for machines that should have non-power related interactions, i found a few examples, there are probably some that i missed.
Machineries which use simple_rotation component seems to be broken if area is unpowered. Most machineries can be rotated when unwrenched, but some loses power when unwrenched and therefore cant receive the alt click signal 
https://github.com/tgstation/tgstation/blob/64afba725d2d1dae8ab05a058f12bc243e665568/code/datums/components/rotation.dm#L49
https://github.com/tgstation/tgstation/blob/f9379e09c40f9b65a9ff70e264f39dfc92575a0f/code/_onclick/click.dm#L393-L395 
https://github.com/tgstation/tgstation/blob/6c01cc2c010c8dc15c5500434ae8e55261511781/code/game/machinery/_machinery.dm#L499-L501
Most impactful example is probably being unable to rotate tachyon dopplers since it's the one of the rare(?) machineries that directly turns off power when unwrenched, but you also cant rotate plumbing machines (reaction chambers, input gates, etc) and chem dispensers if the apc is off.

**Comment by LemonInTheDark** [comment]
😢

**Comment by AlinaStarkova** [comment]
since this was brought up in coder channel and is apparently still an issue, ill fix it, just FYI the fix was easy to do a long time ago, this interact check is regarding the TGUI menus and stuff, simple operations such as rotation can skip this check entirely since it doesnt matter if it has power or not, so right above that power check, just add a check something like "if(action == rotation), then return TRUE", (not the exact code you would use), the basic idea is that rotation doesnt care if you can interact or not, so skip checking if you can interact or not, its irrelevent

ill make the PR adding that bypass tomorrow when i wake up
