### ISSUE TITLE
You can't see a lings armblade when you examine them.

### ISSUE THREAD

**Issue by Edelor68** [tgstation/tgstation#61927]
## Reproduction:

Examine a ling that has an armblade out: apparently nothing out of the ordinary to see here.

So I'm not sure if this is a bug or just an oversight but I'm pretty sure that you should be able to notice it when someone's arm is replaced with a blade.

**Comment by necromanceranne** [comment]
It's an arm replacement. The same happens when you examine chaplains with the dark blessing or chainsaw arm, or anyone who also has chainsaw arms or synthetic armblades grafted to them. I don't think it's really an oversight or a bug, those items are sorta easily observed and rely slightly on misdirection (like false armblade sting), so I'm probably just closing this one.
