### ISSUE TITLE
White Ship Navigation Console preview outline missing

### ISSUE THREAD

**Issue by SppokiBoogi** [tgstation/tgstation#62099]
## Round ID:
[171253](https://scrubby.melonmesa.com/round/171253)

## Reproduction:
When using the White Ship Navigation Console, the ship placement outline is no longer visible. This was reported on round 171253, however the player who alerted me to the problem states this issue is also happening on Terry and Manuel. After asking other players and testing myself I found this issue to be universal. 

![shuttlemachinebroke](https://user-images.githubusercontent.com/61590109/137207279-de3f730d-513c-49d9-b432-9199b9c12407.png)

**Comment by Imaginos16** [comment]
As of the writing of this post, me and @Mothblocks discovered that calling the proc "createEye" on the shuttle navigation console fixes it. This issue not only affects white ships, but also pirate ones. I suspect this may be on every kind of console in general.

**Comment by Sealed101** [comment]
previews were broken as late as Oct(?) 2023 if my memory serves right but as of current year 2024 month of September it is no longer an issue - it's offset but that should be an easy fix i think (bridshot whiteship used for testing)

![изображение](https://github.com/user-attachments/assets/478c3d46-b375-40bc-9a67-72b90623f280)


relevant code; only bit that was recently changed was line 108 due to [Wallening](https://github.com/tgstation/tgstation/pull/85491)
https://github.com/tgstation/tgstation/blob/48b7b890b440a88f3e91f054052699d227dd886d/code/modules/shuttle/navigation_computer.dm#L90-L112
