### ISSUE TITLE
heretic is seemingly missing a few qol administration things that other antags have

### ISSUE THREAD

**Issue by nianjiilical** [tgstation/tgstation#62114]
## Round ID:
all of them

## Reproduction:
as an admin, when removing heretic from people, it doesnt seem to update their "faction and special role", meaning you have to vv their mind to properly remove all traces of it

also there doesnt seem to be a way to force trigger a midround heretic from the dynamic game panel using "execute midround ruleset" like there is for traitor and whatnot, so if you want to add a heretic to the round you have to either pick a player manually or use the force next latejoin option

it seems like these were just forgotten about when heretic was added but itd be nice if someone tossed them in sometime

**Comment by Mothblocks** [comment]
> also there doesnt seem to be a way to force trigger a midround heretic from the dynamic game panel using "execute midround ruleset" like there is for traitor and whatnot, so if you want to add a heretic to the round you have to either pick a player manually or use the force next latejoin option

This isn't a bug, since midround heretic just isn't a great ruleset (even sleeper agent was being prepared to go on the cutting room floor), though the problem of "you have to either pick a player manually or use the force next latejoin option" is a valid one. One thing MSO suggested to me when I removed the create antagonist menu is an easy way to figure out who in the round has what preference enabled, and being able to pick one randomly to give to.
