### ISSUE TITLE
Nuclear Operative Ship doesn't show up on Shuttle Console

### ISSUE THREAD

**Issue by san7890** [tgstation/tgstation#62203]
## Reproduction:

Be a nuclear/clown operative
Try to send your ship to a specific location
You can not see it (the buttons like "place" and "rotate" seem to work but it's of no consequence if you can't SEE that nice and dandy green outline.

![image](https://user-images.githubusercontent.com/34697715/137848016-c0c5a5ab-08a3-4966-bf72-cfcac10562ac.png)

**Comment by TheBonded** [comment]
extension of https://github.com/tgstation/tgstation/issues/62099

**Comment by Sealed101** [comment]
previews were broken as late as Oct(?) 2023 if my memory serves right but as of current year 2024 month of September it is no longer an issue - it's offset but that should be an easy fix i think

![изображение](https://github.com/user-attachments/assets/26d20658-d4b4-4c01-9311-439901c1f3f2)


relevant code; only bit that was recently changed was line 108 due to [Wallening](https://github.com/tgstation/tgstation/pull/85491)
https://github.com/tgstation/tgstation/blob/48b7b890b440a88f3e91f054052699d227dd886d/code/modules/shuttle/navigation_computer.dm#L90-L112
