### ISSUE TITLE
Bluespace navigational gigabeacon cannot be manufactured after research and is unlocked by another unknown research item

### ISSUE THREAD

**Issue by Addust** [tgstation/tgstation#62445]
Reporting client version: 514.1561

## Round ID:
[172147](https://scrubby.melonmesa.com/round/172147)

## Testmerges:
Not applicable

## Reproduction:
Research Bluespace Navigational Gigabeacon (Regulated Bluespace Technology)
Despair when you go to the circuit imprinter and it doesn't work

## Recommendation:
Find which piece of the tech tree the gigabeacon is bound to and rebind it to Regulated Bluespace.

**Comment by Addust** [comment]
charlie station imprinter

**Comment by TheBonded** [comment]
> charlie station imprinter

Charliestation and all other ghost roles cannot print gigabeacons, teleporters, teleport beacons, GPSs, or any other bluespace related teleport-ey items, to prevent them from going to the station and metagrudging whoever killed them, and to prevent people on station from going to the ghostrole and murdering them because haha valid ghostrole

This is not a bug.

**Comment by Addust** [comment]
ah okay
so just a safety measure
closing the issue asap

**Comment by Addust** [comment]
closed because it wasn't a bug
