### ISSUE TITLE
You can't deconstruct alien screwdrivers

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#62456]
trying to put them in the destructive analyser just opens the panel on the machine.

**Comment by timothymtorres** [comment]
Have you tried doing it with normal screwdrivers?

**Comment by TheBonded** [comment]
> Have you tried doing it with normal screwdrivers? Also test it with harm intent mode on/off to see if that does anything.

@timothymtorres This has been an issue for a long time, the destructive analyzer (the red glass covered thing that gives you illegal/alien tech) is unable to accept a screwdriver of any type no matter how you try to put it in, since using a screwdriver on the machine just opens the maintenance panel. A check should be made that allows you to insert a screwdriver by left clicking (and open the maintenance hatch by right clicking, since right clicking is used for deconstruction generally)
