### ISSUE TITLE
Can't start messages with "ahelp" in dchat

### ISSUE THREAD

**Issue by wesoda25** [tgstation/tgstation#62501]
Reporting client version: 514.1568

## Round ID:
[172295](https://scrubby.melonmesa.com/round/172295)

## Testmerges:
- [Fixes halloween roundstart species](https://www.github.com/tgstation/tgstation/pull/62427)
- [[DNM] [TM Candidate] Infuses certain vents with an aroma of garlic, repelling bat form vampires.](https://www.github.com/tgstation/tgstation/pull/61816)

## Reproduction:
![dreamseeker_qzD9tVqz7J](https://user-images.githubusercontent.com/37246588/139619915-824c2bab-2fad-4ec9-b0d2-882c0672b2da.png)

**Comment by timothymtorres** [comment]
So when you type "ahelp" in the chat you get a emote help message?  What were you expecting to happen?

If I type:

Rocco Ward says "ahelp" then it's not going to do an admin help prompt

**Comment by wesoda25** [comment]
I was expecting the message to successfully go through, it's dchat and is annoying to work with especially as an admin.

**Comment by TheBonded** [comment]
> So when you type "ahelp" in the chat you get a emote help message? What were you expecting to happen?
> 
> If I type:
> 
> Rocco Ward says "ahelp" then it's not going to do an admin help prompt

@timothymtorres the issue comes when you're in dchat and talking with someone, and need to start a message with "ahelp". An example would be if I was orbiting someone and they just got killed by a security officer because they took some donuts that were at the sec counter, I might want to tell them "ahelp that, the security officer had no right to kill you there, you only took some donuts.", but I would be unable to start the message with "ahelp". It's not a huge issue, since there are easy ways around it, but it is an annoyance that should be dealt with.

**Comment by timothymtorres** [comment]
> > So when you type "ahelp" in the chat you get a emote help message? What were you expecting to happen?
> > If I type:
> > Rocco Ward says "ahelp" then it's not going to do an admin help prompt
> 
> @timothymtorres the issue comes when you're in dchat and talking with someone, and need to start a message with "ahelp". An example would be if I was orbiting someone and they just got killed by a security officer because they took some donuts that were at the sec counter, I might want to tell them "ahelp that, the security officer had no right to kill you there, you only took some donuts.", but I would be unable to start the message with "ahelp". It's not a huge issue, since there are easy ways around it, but it is an annoyance that should be dealt with.

This makes a lot of sense now when you explain it like that.

**Comment by wesoda25** [comment]
Sorry if that wasn't clear, my bad
