### ISSUE TITLE
Having a limb melt to the bone causes you to scream even while dead, it seems.

### ISSUE THREAD

**Issue by redguy999** [tgstation/tgstation#62530]
Reporting client version: 514.1568

## Round ID:
[172375](https://scrubby.melonmesa.com/round/172375)

## Testmerges:
- [Fixes halloween roundstart species](https://www.github.com/tgstation/tgstation/pull/62427)
- [Undoes "Removes CHECK_TICK from overlays, following the same theory as instant explosions" (#58382)](https://www.github.com/tgstation/tgstation/pull/61919)
- [[DNM] [TM Candidate] Infuses certain vents with an aroma of garlic, repelling bat form vampires.](https://www.github.com/tgstation/tgstation/pull/61816)

## Reproduction:
![_tg_Station Manuel  ENGLISH   US-WEST   ROLEPLAY   99% LAG FREE _ Bone-Rattling Village III 11_2_2021 1_08_29 PM](https://user-images.githubusercontent.com/61719178/139913059-ddd7c9a3-5b16-4dc8-9c9d-c48b1a867264.png)

**Comment by TheBonded** [comment]
I believe a similar thing happens if you hit someone so they cough up blood, as that still happens while dead. certainly an issue with wounds still giving their messages while the person is dead, since it also gives the ghost a large red alert in chat if they are in their body when it gets a burn/cut wound.

**Comment by ArcaneDefence** [comment]
based feedback
