### ISSUE TITLE
Wrong Accesses (science related stuff)

### ISSUE THREAD

**Issue by Archemagus** [tgstation/tgstation#62548]
## Reproduction:

3 moments:
1. RnD consoles was replaced by civilian modular one on all maps. And they have not preinstalled with ScienceHub programm, and Scientist doesn't have access to it. Which means, that now researches begins from DIY RnD console. Kinda stupid isn't it?
2. There is cool idea with department related mech accesses like "Science Mech Access" or "Medical Mech Access" etc. But Roboticists have only science one. Which means, that they can't finish access configuration of mecha, and it should be preformed by user department (but we all know they will just DNA-lock it). Also it means, that Roboticist can not preform maintainence of correctly ID configureted mechs. Again, a bit stupud situation.
3. So DNA-locking departament's mechs. What a mess? It shouldn't be so easy. Well, at least maybe make it possible only if ID editing is enabled on mech? You know, should press few more buttons to shit on everyone's life?

#### In the End.

I am asking for next implementations:
- [ ] Grant access for Science Hub programm to Scientist (and preinstall it to RnD consoles)
- [ ] Grant all department mech accesses to Roboticists
- [ ] Make unable to DNA-lock mech if ID upload panel is locked

**Comment by KittyNoodle** [comment]
>Grant all department mech accesses to Roboticists
This is already the case
> Make unable to DNA-lock mech if ID upload panel is locked
While we are at it can we make ai control beacons and tracking beacons only be insertable when maint protocols are enabled

**Comment by TheBonded** [comment]
> RnD consoles was replaced by civilian modular one on all maps. And they have not preinstalled with ScienceHub programm, and Scientist doesn't have access to it. Which means, that now researches begins from DIY RnD console. Kinda stupid isn't it?

This was done as part of a rework that never ended up getting finished, which left the only R&D consoles on the bridge and in the RD's room. Generally speaking scientists just print a new console board from the circuit imprinter since modular computers can't take the tech disks from BEPIS research. Since the rework was abandoned, I see no reason for the console to stay as a modular computer instead of an R&D console, and I see no reason for scientists not having access to the R&D program. They can download it on their tablet they spawn with, so it makes sense for them to have it.

**Comment by JohnFulpWillard** [comment]
The first one is intentional, Command spawns with the tablet to do research and the app to do it is behind Bridge access. There's also a Core RnD console in the Bridge for it.

The second one, I'm not entirely sure as I havent looked into

The third one just looks like a feature request than a report.

**Comment by timothymtorres** [comment]
From what other people have pointed out either that stuff was intended and GitHub is not the place to make feature requests.
