### ISSUE TITLE
Rad storms cause mutations in rad immune species

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#62541]
be shadow person
exist in a rad storm
take no rads, get mutated anyway.

forgot to report this during the round so no id

**Comment by TheBonded** [comment]
This is because radstorms force mutations, and don't actually irradiate anything. A good fix would be to make them irradiate carbons inside the storm instead of force mutations, or just have it check for rad immunity, since I think right now the only reason it doesn't effect golems and plasmamen is that they don't have DNA.
