### ISSUE TITLE
Emitters firing diagonally

### ISSUE THREAD

**Issue by Likteer** [tgstation/tgstation#62678]
## Reproduction:
1. Set up SM with your 2 atmos bros.
2. Wait, why did one of them just break?
3. 8th of November 2021, "the diagonal emitter" incident
![obraz](https://user-images.githubusercontent.com/68878861/140789498-d88c5642-2b72-4d9d-92bd-d30c2d83a032.png)

**Comment by TheBonded** [comment]
do you have any idea what happened before this? did it still happen if you deconstructed and reconstructed the emitter? was this the only emitter doing this?

My only ideas of what could have caused this is that there was a reflector in the same tile that the emitter is on, which was deconstructed, which might be bugged to cause that tile to still redirect laser based beams, which is why the emitter is firing diagonally.

**Comment by TemporalOroboros** [comment]
If the movement refactor was tmed the emitter may have been pulled/pushed diagonally and so it technically facing NE.

**Comment by TheBonded** [comment]
> 
> 
> If the movement refactor was tmed the emitter may have been pulled/pushed diagonally and so it technically facing NE.

the movement refactor was testmerged during this round, good thinking.

**Comment by LemonInTheDark** [comment]
#62605

**Comment by NanoCats** [comment]
What if you wanted to start the SM
but the emitter said:

**Comment by Likteer** [comment]
@TheBonded No funny invisible reflectors here sir and I did alt click some of them, to rotate into the correct position.

**Comment by BraveMole** [comment]
Should be fixed, this maybe change the way the dir is set when pushing diagonnaly, tell me if there is a noticeable difference

**Comment by Likteer** [comment]
Pretty sure it no longer does that, until someone proves me wrong.
