### ISSUE TITLE
Can't enter positronic brains that another ghost has ghosted out of

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#62716]
Reporting client version: 514.1568

## Round ID:
[172792](https://scrubby.melonmesa.com/round/172792)

## Reproduction:
Likely as a result of #61413 . 
Have a posibrain that another ghost has entered but ghosted out of. 
Notice when you click on it nothing happens. Roboticists keep trying to activate it, but clicking on the popup and chat link does nothing.

**Comment by GunHog** [comment]
Ghosting out of the Posibrain is supposed to make it available for new ghosts, otherwise it would have to be discarded and reprinted. I do not know why that PR considered this restriction a fix. 

If re-entering the brain is undesired for some reason, then make it so that a living player must reset it manually.

**Comment by TheBonded** [comment]
Likely caused by https://github.com/tgstation/tgstation/pull/61413

**Comment by TheSmallBlue** [comment]
Ah crud, my PR was supposed to not allow the _same_ ghost to join a posibrain after ghosting, I overlooked this.

**Comment by redguy999** [comment]
> Ah crud, my PR was supposed to not allow the _same_ ghost to join a posibrain after ghosting, I overlooked this.

fixed yet?

**Comment by TheSmallBlue** [comment]
I haven't had time, once I do make a PR to fix it you'll get a notif saying that it has been linked here
