### ISSUE TITLE
Tramstation Generic Base Construction Console is borked

### ISSUE THREAD

**Issue by tnekohue** [tgstation/tgstation#62778]
RoundID: 172945
The following pull requests are currently test merged:
#62771: 'Fix team antag HUDs displaying when they shouldn't, and the other way around' by Mothblocks at commit de9a58ae25
#62711: 'Allows players to send more visible adminhelps when no admins are on, which'll definitely alert admins' by Watermelon914 at commit 288695b981
#62727: 'Departmental Security Rework Option \#1: Department First, Security Second' by Iamgoofball at commit 029f550f7e

The drone is not locked to the confines of the aux base zone, and none of the buttons except logout, move up, and move down are visible
Additionally, its possible to view the entire station in real time, (similar to AI camera), and see any even going on at the time

**Comment by GunHog** [comment]
Your description leads me to believe that the map is using `/obj/machinery/computer/camera_advanced/base_construction` instead of `/obj/machinery/computer/camera_advanced/base_construction/aux`. 

The correct name for the console is "aux base construction console". The generic one is the parent object without all the Aux base controls.

**Comment by tnekohue** [comment]
Yeah, can confirm this is the case
