### ISSUE TITLE
Being borged counts towards assassination but not towards prevent escaping alive

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#62839]
## Testmerges:
The following pull requests are currently test merged:
#62727: 'Departmental Security Rework Option #1: Department First, Security Second' by Iamgoofball at commit 029f550f7e
#62711: 'Allows players to send more visible adminhelps when no admins are on, which'll definitely alert admins' by Watermelon914 at commit 5dcc0b783d

## Reproduction:
Grant Steele had been made into a borg, slaved to an ai.
https://puu.sh/Ipihv/90a9b5ade2.png
you can see marigold had successfully assassinated him, but Lauren has not successfully prevented him from escaping alive.

**Comment by LemonInTheDark** [comment]
it's still you, you're just dead

**Comment by necromanceranne** [comment]
I think if it counts as dead, it shouldn't also count as escaping alive if they're a borg. That seems to be a trap for players who might otherwise want to borg people to keep them in the round despite still having killed the person and assumed based on how the other objective worked, this objective worked the same. 

Which isn't very fair on the antag sticking their neck out when they otherwise would have succeeded if they had the kill objective (and also killed and kept their target dead, which is kinda derivative), and in fact would be just downright confusing.

**Comment by SuperNovaa41** [comment]
Yeah idk, i know its been like this for a while. It's probably up to the *dmins to decide which is which

**Comment by timothymtorres** [comment]
> I think if it counts as dead, it shouldn't also count as escaping alive if they're a borg. That seems to be a trap for players who might otherwise want to borg people to keep them in the round despite still having killed the person and assumed based on how the other objective worked, this objective worked the same.
> 
> Which isn't very fair on the antag sticking their neck out when they otherwise would have succeeded if they had the kill objective (and also killed and kept their target dead, which is kinda derivative), and in fact would be just downright confusing.

This makes sense.  It gives antags incentive to not space/cremate the body and keep other people in the round.

**Comment by newfren** [comment]
if a man is assassinated they have not escaped alive right
