### ISSUE TITLE
All objects block sprayed reagents

### ISSUE THREAD

**Issue by Angustmeta** [tgstation/tgstation#62873]
Local testing on a few days' old build. 

## Reproduction
![211116 spraybug](https://user-images.githubusercontent.com/46400996/141999199-d4bbef37-7e55-4122-98c2-d1e26a6b5a99.gif)

1. Put graffiti on floor. 
2. Add any object to same tile, such as a cigarette butt, a light fixture or vent. 
3. Set a space cleaner to 5u and try to spray it. 

Result: Sprays set to 1 range can't clean it. Change range setting and it works again, at least if you click behind it. 

This makes spraying people with reagents/viruses not work if they stand for example next to a fire alarm, or on same tile as an open firelock.

**Comment by LemonInTheDark** [comment]
@Timberpoes seems to have changed what `puff_reagent_left` means with https://github.com/tgstation/tgstation/pull/58070, leading to this new behavior.
Can't tell if it was intentional or not

**Comment by Timberpoes** [comment]
> @Timberpoes seems to have changed what `puff_reagent_left` means with #58070, leading to this new behavior. Can't tell if it was intentional or not

I believe it was intended but not fully documented. Sprays at max range were exposed to all atoms on the turf regardless of how many units the spray had left in its puff. 

When you set the spray to 1u, it can only ever be exposed to 1 atom on the turf. If the turf has multiple atoms,  which atom the puff hits is just random based on iterating contents.

**Comment by LemonInTheDark** [comment]
The comment on `puff_reagent_left` seems to describe it as a counter of how many turfs/mobs/dense objects it's hit.
https://github.com/Timberpoes/tgstation-nxt/blame/d803c32dede13c28b55ce07e43b76c83b3bf15af/code/modules/reagents/reagent_containers/spray.dm#L70
That's why it was only decremented when you sprayed a mob/turf (where did dense objects go? gabennnnnn). Your change made it decrement on hitting a mob or passing a turf, or on hitting an object if it was in the last step of a stream. Seems strange since the longer range spray mode does not behave like that at all, still retaining the "only go down if you hit a mob/turf" thing

**Comment by LemonInTheDark** [comment]
I have defeated timberpoes in single combat (After a long discussion we agreed that any negative effect the old behavior had was minor, and god spray code is the worst)
