### ISSUE TITLE
Demonic frost miner arena doesn't spawn correctly

### ISSUE THREAD

**Issue by Striders13** [tgstation/tgstation#62901]
## Reproduction:
Be demonic frost miner, don't have your arena (or you) spawn because there are some walls and 3 dogs underneath you

Topmost layer of the arena is present (the big arena-sized hole and the hut), there's nothing in the hole and a structure 2 levels below. I'm pretty sure this is not intended.

**Comment by msgerbs** [comment]
Yes this is still broken. I have an idea to fix it, it won't be trivial to fix.

**Comment by Striders13** [comment]
> Yes this is still broken. I have an idea to fix it, it won't be trivial to fix.

was this not fixed in https://github.com/tgstation/tgstation/pull/70097?

**Comment by msgerbs** [comment]
Nope, that was a different issue causing multi-Z ruins (this one) to not spawn at all. They literally could not spawn at all. Now that's fixed and we're back to this issue again, which is that the top part will always spawn, but it doesn't actually check if the bottom part can spawn when it chooses where to place it, so it can end up failing to place the bottom part. The solution is to make the placement process recursive so it will check all attached layers of a ruin before allowing it to be placed. If somebody else wants to tackle that feel free, otherwise it's on my "list of things to eventually get to".

**Comment by Sealed101** [comment]
have heard reports that it's still not spawning lmao

**Comment by msgerbs** [comment]
Can we get some round IDs?

**Comment by msgerbs** [comment]
Also this issue is specifically stated to be the top part spawning and the bottom part not spawning. If we're seeing the entire ruin not spawning, that is a different issue and should be reported elsewhere. This also shouldn't have been closed in the first place because that wasn't the issue that change fixed.

**Comment by Sealed101** [comment]
[this one i think](https://scrubby.melonmesa.com/round/214609)

either way should take a closer look, livrah may have been mistaken

**Comment by Striders13** [comment]
fixed somewhere

**Comment by msgerbs** [comment]
Who the heck fixed this and how did they do it?
