### ISSUE TITLE
Can't exile rev heads on icebox

### ISSUE THREAD

**Issue by JusticeGoat** [tgstation/tgstation#63112]
The only way for this to happen is all of them riding the shuttle together, the gulag does not count as off station.

**Comment by newfren** [comment]
does the third floor count as exile? it teleports the disk

**Comment by timothymtorres** [comment]
> The only way for this to happen is all of them riding the shuttle together

So if you send all of them on the shuttle together it counts?  I'd say this seems like it's intended though because unlike lavaland, ice is technically attached to the station.  

@EOBGames what do you think?

**Comment by SuperNovaa41** [comment]
@timothymtorres Idk the ice is pretty dangerous i would say that the station zlevel should count as exile

**Comment by TheBonded** [comment]
> @timothymtorres Idk the ice is pretty dangerous i would say that the station zlevel should count as exile

 @SuperNovaa41   The reason why the 2nd level does not count as exile is because botanists, bartenders, mimes, clowns, and cooks can all spawn in the lower z level, and on lower pop (or with serious luck) the only revhead can start in the bottom level of botany or bar or kitchen and immediately lose. I'd go so far as to say that this **isn't a bug**, as you can still exile revs and staffheads by sending them to the bottom z level. The reason why the gulag does not count as exile is because it is on the second z instead of the bottom z.
