### ISSUE TITLE
You can have a trauma of "nothing"

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#63188]
Reporting client version: 514.1568

## Round ID:
[173975](https://scrubby.melonmesa.com/round/173975)

## Testmerges:
- [Mouse Entered Profiling](https://www.github.com/tgstation/tgstation/pull/63098)
- [Fixes Massive Radio Overtime, Implements a Spatial Grid System for Faster Searching Over Areas](https://www.github.com/tgstation/tgstation/pull/61422)
- [pAI TGUI conversion](https://www.github.com/tgstation/tgstation/pull/62916)

## Reproduction:
![image](https://user-images.githubusercontent.com/66640614/144162335-dff4a0c5-b526-4c96-a4e9-748da2d3cf58.png)
Saw it in the round before this one on Sybil as well, only thing I could guess at to explain this was that the person with the trauma was hypnotized, but had hypnotized victim disabled in prefs. There were no associated runtimes.

**Comment by moocowswag** [comment]
Its caused by neruwhine.

When you get the chemical in you it rolls a random "permanent" trauma for you to have until the chemical runs out, if you roll hypnotized it doesn`t come with an objective and when the chemical runs it somehow fails to remove the trauma. (As far as I can tell this is the only trauma that doesn`t remove itself upon the chemical running out).
