### ISSUE TITLE
Firelocks missing functions

### ISSUE THREAD

**Issue by Edelor68** [tgstation/tgstation#63472]
## Testmerges:
#62055: 'Moves atmos checking from Fire Alarms to Fire Locks, Fire Locks now close on their own rather than area-based, a bunch of related stuff.' by zxaber at commit 613bfeb30d

## Reproduction:
1. You can't open the maintenance pannels on firelocks anymore. Nothing happens when you click on them with a screwdriver in your hand

2. You can close all firelocks in an area with the fire alarm but you cant open them back up

3. This might be not a bug but in the round this happened firelocks kept closing without any cause. Might have been an EMP but because a lot of fuckery was going on with the firelocks I thought I'd add this.

**Comment by zxaber** [comment]
The second one is because clearing the firelocks in a room is now right-click (with the testmerge). As firelocks can activate on their own now, rooms will be left in a "half and half" state, and a toggle button doesn't make sense. So left-click will manually activate all firelocks in the area, and right-click will clear all firelocks in the area.

For the third one, if you remember, what color were the upper lights? Red means the firelocks detected fire, blue means they detected cold, and white means someone is pulling a fire alarm.

**Comment by Edelor68** [comment]
Pretty sure they were white. So probably not a bug then.

**Comment by zxaber** [comment]
>1. You can't open the maintenance pannels on firelocks anymore. Nothing happens when you click on them with a screwdriver in your hand

It works correctly if the firelock is welded shut. I believe this is how you disassembled them before the PR, as most of the deconstruction code was just copied from old firelocks.

**Comment by dragomagol** [comment]
Appears to have been resolved; feel free to open another issue if there's something that hasn't been addressed.
