### ISSUE TITLE
Food Duplication Via Processor - Quantum Entangled Corn Produces Near Infinite Tortillas

### ISSUE THREAD

**Issue by Thunderfleece** [tgstation/tgstation#63640]
Reporting client version: 514.1561

## Round ID:
[175481](https://scrubby.melonmesa.com/round/175481)

## Reproduction:
1 - Put a food item that the processor can process (ie: potato wedges, cutlets, steaks, dough slice, corn, etc.).
2 - Right click on the processor, select eject contents.
3 - Repeat
4 - Finally activate the processor to get a stack of food equivalent to the amount of times you stuffed things into the processor and ejected them. The items you did put into the processor will be consumed no matter how far away from the processor they are when it finishes, if you kept them ejected before activation. May cause weirdness if you consume the original food before it finishes processing.

**Comment by LemonInTheDark** [comment]
This has been for almost a year, lordie 
https://github.com/tgstation/tgstation/blob/55bcbd09c20794883330be655d2fb3b382abb0c5/code/modules/food_and_drinks/kitchen_machinery/processor.dm#L174-L177
which was introduced by https://github.com/tgstation/tgstation/pull/55872

Since we're emptying contents rather then processor contents, processor contents always has entries.
Fix for this would be to remove this override and instead override Exited(). Just lazyremove the exiting object from `processor_contents`, if it's not already inside the list it'll do nothing, and if it is we've just saved some effort

This also means we can remove the one existing lazyremove, since it'll happen on its own now
