### ISSUE TITLE
You can hear disposals while deaf

### ISSUE THREAD

**Issue by DragonTrance** [tgstation/tgstation#64016]
You can hear disposals (presumably) while deaf
![image](https://user-images.githubusercontent.com/26515331/149055367-ce5c2524-519b-4476-8540-0c08b8ad1af7.png)

**Comment by timothymtorres** [comment]
Did someone disposal you?  How did this happen?

**Comment by SuperNovaa41** [comment]
The issue here is actually from buckle code. 
https://github.com/tgstation/tgstation/blob/6830f244c64424932a46507f6ada849d185244d1/code/game/objects/buckling.dm#L308-L310
there are four of these.
The line you're seeing is only supposed to play for those that are blind. So I think the `visible_message` proc is incorrectly sending blind messages to the deaf.

**Comment by timothymtorres** [comment]
I figured out the problem.  In the visible_message proc someone wrote some edge case code to check if objects were visible and then if it wasn't to change the default message to be blind WITHOUT updating the message type to `MSG_AUDIBLE`.  This meant that the blind messages were being sent as if they were the `MSG_VISIUAL` type.

**Comment by Mothblocks** [comment]
Please avoid useless issue titles, it makes it harder to go through the tracker
