### ISSUE TITLE
Xenomorphs hivemind talk causes xenomorph talking sound

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#64059]
## Testmerges:

#63666: 'makes ai static into images added to obscured turfs to save on maptick' by Kylerace at commit 7d56c359ec

## Reproduction:

Use hivemind to speak, realize the xeno tongue noise goes off and inform everyone in nearby rooms of what is going on.
Proceed to make another bug report on the github.

**Comment by timothymtorres** [comment]
But the real question is, did you survive?

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/6d470992cb649d363f7a2c009a3ebd94f628bf31/code/datums/saymode.dm#L9-L33

https://github.com/tgstation/tgstation/blob/f1758f39b8abe1794c833c98791378e02272d1f3/code/modules/mob/living/carbon/alien/alien_say.dm#L1-L25

This may need to get retested to see if it still exists since Kapulimbs changed a lot of stuff.
