### ISSUE TITLE
Instant cure to Paraplegia(Doctors hate him)

### ISSUE THREAD

**Issue by B00tz** [tgstation/tgstation#64122]
## Round ID:
[176615](https://scrubby.melonmesa.com/round/176615)

## Reproduction:
Be Paraplegic, go through tele that isn't calibrated yet. Become a walking flyman.

**Comment by SuperNovaa41** [comment]
lol

**Comment by NanoCats** [comment]
> species changes remove all brain traumas... paraplegic is a brain trauma? 🤔

Pretty sure that yes, it is. It's a brain thing, there's nothing actually wrong with your legs themselves(?)

**Comment by timothymtorres** [comment]
This is related to #40040

**Comment by Time-Green** [comment]
> This is related to #40040

I don’t see how. Quirks are body specific, and while those methods in that issue create a new body, species changes do not.

**Comment by timothymtorres** [comment]
Read the comments in that issue.  It doesn't just cover mindswapping, but transformations and polymorph.  That's why I said it's related and didn't mark it as a duplicate.

I do think we need to split up quirks into MIND / BODY / SOUL sources because right now they are all jumbled up from different sources.  The polymorph code is also a nightmare.  There are about 6 different transformation procs that handle it differently each time.

**Comment by Artemchik542** [comment]
Can't reproduce this bug anymore, maybe fixed in https://github.com/tgstation/tgstation/pull/84805

**Comment by Artemchik542** [comment]
https://github.com/tgstation/tgstation/issues/82546
https://github.com/tgstation/tgstation/issues/81651
looks same fixed, can't reproduce too

**Comment by Time-Green** [comment]
Fixed in #84805

**Comment by Time-Green** [comment]
Thank you for checking!
