### ISSUE TITLE
Runtimes with modular ruins at initialize 

### ISSUE THREAD

**Issue by MMMiracles** [tgstation/tgstation#64192]
## Round ID: 
Local Server, updated master as of [here.](https://github.com/tgstation/tgstation/commit/9ddb8cf084e292571d4e9c79745db25befbd82fe)

## Testmerges: 
N/A

## Reproduction: 
Start a game with a modular ruin, check dream daemon/runtime log after initial startup.

Two main ones I can see from the runtime log in-game are an issue with reading null gas lists and assigning light objects where they already exist.

[**null.gases**](https://pastebin.com/GWR4yU8q)

[**Stack trace of lighting objects**](https://pastebin.com/RtpL8jy9)

**Comment by Kylerace** [comment]
for posterity: the reason this happens is because when SSatoms initializes every atom in the world it keeps a list of lateloading atoms that it iterates through and initializes when InitializeAtoms() is finished with everything else, but this list is on the entire subsystem. When the ruin spawner object initializes it spawns a map template which itself calls SSatoms' InitializeAtoms() proc while the world init proc is still underway. this means that the list of lateloading atoms that were meant to initialize after everything else in the world initializes when the ruin is spawned which is too early.
