### ISSUE TITLE
Items being in the screen's contents when not inside a storage item

### ISSUE THREAD

**Issue by DragonTrance** [tgstation/tgstation#64190]
Round ID: [176768](https://scrubby.melonmesa.com/round/176768)
I'm not sure how this happened exactly. I thought it was from an item being inside a box, but turns out it was just anything I tried to take out of my storage. Not sure about the storage of other containers.

In the middle of the round this just suddenly started occurring

Here's a vid of it happening to me: https://youtu.be/z5--CzHwtdY

**Comment by timothymtorres** [comment]
Thank you for the bug report.  Have you been able to replicate this behavior consistently?  Can you check if this is only happening with the miner backpack?

**Comment by LemonInTheDark** [comment]
This is likely "caused" by #64095 
I have no idea what the issue is however. it seems to be related to storage removal, which I did technically add new code to, but none of that ought to be causing this. Especially this weird hud teleportation I'm seeing reports of. It's v worrying.

I really wish we had better replication steps for this. If I had those I could at least A/B debug this, but I don't, so I can't. Can't even get it to trigger on a local. Very sad

**Comment by LemonInTheDark** [comment]
![image](https://user-images.githubusercontent.com/58055496/150231705-7ddb3685-c1ef-4b8f-ba1f-60518747eff4.png)
@vincentiusvin I love you
