### ISSUE TITLE
Free Golems Get Hungry

### ISSUE THREAD

**Issue by SomeDongus** [tgstation/tgstation#64420]
## Round ID: 
[177216](https://scrubby.melonmesa.com/round/177216)

## Reproduction:
Free Golems get hungry. I'm pretty certain they aren't supposed to. Golems are made entirely of refined materials, and magic. Them having stomachs doesn't make sense. I'm unsure if golems made by xenobiology also have this problem, or if this is exclusive to the ghost spawner golems. If you want to test this, spawn as a free golem and run around for 1 to 10 minutes. You will see that you are getting hungry.

**Comment by Serxule** [comment]
golems definitely arent supposed to be hungry, i dont think they even can eat

**Comment by SuperNovaa41** [comment]
Good

**Comment by Ryusenshu** [comment]
> golems definitely arent supposed to be hungry, i dont think they even can eat

They can, they eat the same things as humans
I have seen golems make entire kitchens down there

**Comment by timothymtorres** [comment]
Looks like #51713 has similar problems.

**Comment by SomeDongus** [comment]
> Looks like #51713 has similar problems.

Similar, but probably not related, since its from two years ago and golems needing getting hungry has been a recent thing.

**Comment by Donpedrito** [comment]
I can confirm that free golems getting hungry has been happening for a while; I don't know the exact time, as I assumed it was intended and microwaved some goliath steaks, but I'm pretty sure it's been like that for years (unless it was fixed, then broke again recently).

**Comment by Donpedrito** [comment]
Update: I used this as an excuse to learn a bit of GitHub; golems have all human organs, as well as an extra organ that lets them hear adamantine resonance, and a second extra organ only for adamantine golems which lets them do that resonance. This means they still have a human stomach, so they have, as far as I know, had hunger for as long as they've existed, and this is definitely not something that happened recently. This _probably_ isn't a bug, since golems aren't given the NOHUNGER trait, but I may be wrong.
