### ISSUE TITLE
Mapped in Closed Firelocks are Inconsistent 

### ISSUE THREAD

**Issue by Jolly-66** [tgstation/tgstation#64524]
## Round ID:
Tested locally

## Reproduction:

While trying to figure out why the hell Charlie Station (old station) has so many active turfs, I've ran into another issue (so I'm closing that other report in favor of this; see for #64426 more info).

For whatever reason, mapped in firelocks seem to just be incredibly inconsistent. Old Station has 16 mapped in firelocks that are closed, but only 4 are ever active. They ALL generate active turfs despite having the correct aired turfs. As for the ones going directly to space, they create active turfs ON the firelock turf and the turf adjacent (airless). This is not true for the 10 firelocks closed that don't border space, they generate active turfs ON their turf.

Through testing, putting airless turfs under the firelocks (or adjacent) opens the firelocks, or doesn't Whatevers going on is incredibly inconsistent and rather annoying, especially for future mappers/adminbus events, which would require an airlock to be closed.

**Comment by Jolly-66** [comment]
Relevant video
https://user-images.githubusercontent.com/70232195/151642248-f329ec48-0bf3-467f-a71b-b7f57a7efc9f.mp4

<details>
<summary>Image</summary>
![image](https://user-images.githubusercontent.com/70232195/151642321-65166564-cea0-4328-b573-1ebf7ae0ad86.png)
</details>

**Comment by Timberpoes** [comment]
Broken by #62055

Stack trace of code path forcing closed firedoors doors to open on ruin spawn
![image](https://user-images.githubusercontent.com/24975989/151671935-52900a89-59cd-4d3c-9c32-200e91f8b64e.png)

As part of `power_change()` the door corrects its state. Because there is no `alarm_type` set, this correction results in the door opening.
![image](https://user-images.githubusercontent.com/24975989/151672184-851708c4-43ba-4a1f-a86e-18251599b275.png)
