### ISSUE TITLE
Runtime on conveyor for right clicking

### ISSUE THREAD

**Issue by timothymtorres** [tgstation/tgstation#64595]
## Reproduction:

Right clicking on a conveyor with a wrench creates a runtime because the `attackby_secondary` proc is supposed to return a `SECONDARY_ATTACK_CANCEL_ATTACK_CHAIN`. I'm not sure why this attack chain needs to do this when primary the primary attack chain doesn't have this behavior.  Nor does Alt or Ctrl clicking.  

https://github.com/tgstation/tgstation/blob/4dfb104016a0e3c7fecd22fbedb39e64fd311535/code/modules/recycling/conveyor.dm#L275-L285

**Comment by Mothblocks** [comment]
> I'm not sure why this attack chain needs to do this when primary the primary attack chain doesn't have this behavior.

Because right-clicking in BYOND is horse-shit. It pipes it all through the normal Click and only tells you it's a right-click through a flag. 

*Nothing* should return `..()` from `attackby_secondary`, because the default is the legacy behavior of making right-click pass as left-click (which I want to kill ASAP, once nothing uses the stupid flags anymore).

Remove `else return ..()`, and make this whole thing do `return SECONDARY_ATTACK_CANCEL_ATTACK_CHAIN`.
