### ISSUE TITLE
Clicking Vampire on the Magic Mirror doesn't do anything

### ISSUE THREAD

**Issue by Shadowflame909** [tgstation/tgstation#64590]
## Reproduction: 1. Roll Wizard. 2. Use the Magic Mirror. 3. Click Vampire Race. 4. Nothing happens, repeat from 1.

Where my vampire?? No jojo reference today?

**Comment by JohnFulpWillard** [comment]
Why is there no round ID? Was this tested locally?
I also can't seem to reproduce this
![image](https://user-images.githubusercontent.com/53777086/152293392-9f98bd59-425a-4c1c-8824-8307528da858.png)

Are you using latest TG? I know magic mirrors broke twice recently, because I fixed them both times: https://github.com/tgstation/tgstation/pull/63201 https://github.com/tgstation/tgstation/pull/63828

**Comment by Shadowflame909** [comment]
Thank you JohnFulpWillard what would I do without you
