### ISSUE TITLE
certain megafauna dont spawn

### ISSUE THREAD

**Issue by Serxule** [tgstation/tgstation#64804]

**Comment by JohnFulpWillard** [comment]
![image](https://user-images.githubusercontent.com/53777086/153255418-371b858a-28bd-4641-bd2b-ff792056a272.png)
Hiero always spawns

![image](https://user-images.githubusercontent.com/53777086/153255461-1e4f2588-d8ba-4105-a67b-cb9c35a62e76.png)
Blood drunk doesn't

![image](https://user-images.githubusercontent.com/53777086/153281984-6d461ee5-0892-46a4-b978-cf1eac77d3e2.png)
Bubblegum has a very high chance to spawn, but not always.
The puzzle ruin on lavaland also spawns a bubblegum if one hasn't spawned.

Bubblegum also can't spawn twice, unlike the other two in the bubblegum screenshot, because it removes themselves from the list of they are picked
![image](https://user-images.githubusercontent.com/53777086/153282141-99953062-00c2-4d7a-ae61-936b0a015c45.png)
