### ISSUE TITLE
Holodeck deleting items

### ISSUE THREAD

**Issue by derekhearst** [tgstation/tgstation#65103]
Reporting client version: 514.1575

## Round ID:
[178878](https://scrubby.melonmesa.com/round/178878)

## Testmerges:
- [makes vent scrubbers only activate if a gas they filter is on their tile](https://www.github.com/tgstation/tgstation/pull/64664)
- [Armor Rework: New Vegas Damage Threshold System](https://www.github.com/tgstation/tgstation/pull/65053)

## Reproduction:

When putting a badge or pin on a uniform generated by the holodeck, when leaving the holodeck the pin also gets destroyed.

**Comment by LemonInTheDark** [comment]
This is intended. Anything the holodeck spawns is "owned" by it, and when the deck changes sim, the things it "owns" get nuked

**Comment by derekhearst** [comment]
The issue is not the holodeck deleting the uniform itself, but its deleting attachments on the uniform too.

**Comment by TheBonded** [comment]
does this mean you could put the two captains medals on holodeck uniforms to permanently delete them? that doesnt seem intended, @timothymtorres are you sure this isnt a bug?

**Comment by derekhearst** [comment]
> does this mean you could put the two captains medals on holodeck uniforms to permanently delete them? that doesnt seem intended, @timothymtorres are you sure this isnt a bug?

Yes, captain medals can get deleted this way

**Comment by TheBonded** [comment]
being able to delete antagonist objectives using the holodeck is likely not intended, and it seems like an oversight that there is no check for attachments on the jumpsuits when they are deleted 

for example, if a jumpsuit with a medal on it is destroyed by fire, it will drop the medal before turning to ashes (though I think the medal comes off before it is destroyed, due to the jumpsuit being damaged and being unable to hold it anymore)

**Comment by timothymtorres** [comment]
I wasn't aware that captain's medals were an indestructible antag objective.  After my PR it should be fixed.
