### ISSUE TITLE
Permanent pacify from wiz "living duffelbag"

### ISSUE THREAD

**Issue by derekhearst** [tgstation/tgstation#65116]
Reporting client version: 514.1575

## Round ID:
[178900](https://scrubby.melonmesa.com/round/178900)

## Testmerges:
- [makes vent scrubbers only activate if a gas they filter is on their tile](https://www.github.com/tgstation/tgstation/pull/64664)
- [Armor Rework: New Vegas Damage Threshold System](https://www.github.com/tgstation/tgstation/pull/65053)

## Reproduction:

Wizard used his living dufflebag curse thing on me, killed me. Doctors melted it off with acid much later but when i was revived I still was pacified, even with the bag off. This is not very good as about half the crew had the same thing happen to them leaving us quite in a pickle when blob showed up.

**Comment by necromanceranne** [comment]
Pretty sure this is because the curse adding traits to you isn't being removed by the bag being destroyed, rather than the normal method (feeding it bad food). It's likely skipping a proc due to never actually being deleted the _right_ way or dropping.

This was a bug I noticed when I redid them, and fixed at the time, so it's like something that came about when it was made into a component.

**Comment by realthomas69** [comment]
this is still happening, just occurred during round #195205

**Comment by MrMelbert** [comment]
#71969
