### ISSUE TITLE
Abandoned crate continues to QDEL

### ISSUE THREAD

**Issue by carshalash** [tgstation/tgstation#65541]
## Testmerges:
#65445 

## Reproduction:
Have a player in a crate
Fail to do code/purposefully fuck it up
Player get Qdel and everyone around it gets damaged

**Comment by SuperNovaa41** [comment]
How would a player get into a trapped crate?

**Comment by timothymtorres** [comment]
Looks like a duplicate of #46239

**Comment by SuperNovaa41** [comment]
Its not even like close to the same thing @timothymtorres

**Comment by timothymtorres** [comment]
> Have a player in a crate

The only way I know of to get a player in a abandoned crate is the skitterish quirk

> Fail to do code/purposefully fuck it up

The skitterish code for this is broken and buggy as hell.

> Player get Qdel and everyone around it gets damaged

When a player activates the skitterish quirk on a abandoned crate it gibs the player and hurts surrounding mobs.

This bug report is shit at describing this though so this is what I'm inferring.

**Comment by SuperNovaa41** [comment]
The end result is the same but the actual bug of the other one is that they can bypass the lock

**Comment by timothymtorres** [comment]
Nowhere in the other bug report indicates that they were able to bypass the lock.  Someone mentioned they _thought_  the lock would prevent it from exploding but that was not the case.

I still think this is a duplicate and should be closed but I'll let you decide Nova. (also the bug description should be rewritten by the OP since everything is too vague)
