### ISSUE TITLE
the cryoxadone change has made the dark blue extract's minor luminescent activation effect just kill you

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#65680]
It adds some cryoxadone to your system alongside some frost oil to bring you down into cryoxadone healing range. Now that cryoxadone only works while you're asleep (thanks, https://github.com/tgstation/tgstation/pull/65513), activating that ability just causes you to take large amounts of damage due to your cold weakness as a luminescent. It is literally a suicide button that claims that it's a healing ability now.

This also happens with the burning dark blue crossbreed's effect.

Fun fact: Someone actually pointed this exact issue out in the comments section of that PR, but it was merged anyway without any changes being made to account for it. Very cool!

**Comment by moocowswag** [comment]
It wasnt specificallly advertised as a healing ability, more for dealing with fire since it puts you out and cools you down then heals you in the process so you dont die from it. But even that use is really bad because slime people take very little damage from high temp (even less than lizards) while also having good temp stabilization.

I dont think it is useful even in that application anymore since you`d probably die from overcooling.

**Comment by interestingusernam3** [comment]
trolled
:trollface:

**Comment by ExcessiveUseOfCobblestone** [comment]
Why can’t you guys use the review function correctly smh
