### ISSUE TITLE
Syndicate Bioweapon Base Sleepers Bugged

### ISSUE THREAD

**Issue by RikuTheKiller** [tgstation/tgstation#65691]
## Reproduction: 

1. Try upgrading the sleepers in the syndicate bioweapon spawner base.
2. Fail even while using the bluespace RPED that spawns there. 
3. Realize you could deconstruct it. 
4. Deconstruct it only to find that there is magically no circuit board and you've just permanently deleted the sleepers.

To fix this, you could add a circuit board to it, though this would make it able to be recovered back to the stati- oh wait you can already do that with charlie and also charlie is far less rare than the syndicate bioweapon base.

So yeah, I don't think it's intended that it's both not upgradable AND undeconstructable, making the sleepers almost useless.

**Comment by newfren** [comment]
it's definitely intended that it's undeconstructable from when the sleepers were removed from main stations

**Comment by RikuTheKiller** [comment]
> it's definitely intended that it's undeconstructable from when the sleepers were removed from main stations

I personally think that's not intended as the charlie sleeper can still be recovered. Also, what's the point of making sleepers THAT hard to get, jesus.

**Comment by TheBonded** [comment]
this is indeed intentional, you cannot retrieve the circuit board from deconstructed sleepers, and there is only 1 location which has a sleeper board, that being charliestation. (technically its bravostation, since charliestation is the middle one, and so the research part is deltastation, as written in the computer log on the bridge, but who cares about the lore)

if you want to change that to allow you to deconstruct sleepers, that would be a balance change.

**Comment by RikuTheKiller** [comment]
> this is indeed intentional, you cannot retrieve the circuit board from deconstructed sleepers, and there is only 1 location which has a sleeper board, that being charliestation. (technically its bravostation, since charliestation is the middle one, and so the research part is deltastation, as written in the computer log on the bridge, but who cares about the lore)
> 
> if you want to change that to allow you to deconstruct sleepers, that would be a balance change.

Love how you closed it without addressing the main issue, that being that they cannot be upgraded.

And the fact the charlie station sleeper board still exists.

**Comment by TheBonded** [comment]
> Love how you closed it without addressing the main issue, that being that they cannot be upgraded. (And even added a "not a bug" label when it clearly describes the fact they cannot be UPGRADED with the literal on-station bluespace RPED that is meant for upgrading things.)
> 
> And the fact the charlie station sleeper board still exists.

do upgrades even do anything for sleepers? what stock parts do sleepers even have? there are several machines that dont have any actual use for being upgraded because it doesnt do anything (for example, the ORM).

**Comment by newfren** [comment]
sleepers used to gain more chems when upgraded, I think possibly a chem rework ago?

**Comment by TheBonded** [comment]
I dont remember upgrades ever actually doing anything but ill trust you on this

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/fece725a272e87e8bf120c45e4d46583a9228571/code/game/machinery/Sleeper.dm#L34-L38

https://github.com/tgstation/tgstation/blob/d14eac752bc72eae35118a91497fcd5a64687284/code/game/objects/items/circuitboards/machine_circuitboards.dm#L768-L776

![StrongDMM_RRhtreyTPI](https://user-images.githubusercontent.com/5195984/160737365-620413bb-fd7a-47f4-afd5-e6075050ace9.png)

To chime in here:  Bonded is correct in that the circuit restriction is hardcoded and intentional design choice.  Charlie is the only station that has a circuit board for sleepers.  Any preloaded mapped sleepers gets their circuit and components deleted.  If you build a sleeper with the charlie circuit, neither the circuit nor the components get deleted, meaning you can upgrade it and retrieve the circuit.  No other sleeper can do this.

**Comment by TheBonded** [comment]
@timothymtorres what about the fact you cant upgrade them? apparently thats something you used to be able to do

**Comment by timothymtorres** [comment]
You can upgrade the sleeper that is built with the circuit.  The ones that are mapped in have their components deliberately removed so they can't be upgraded.  This was a maintainer decision and not something I see them reverting anytime soon.

**Comment by TheBonded** [comment]
ah, @RikuTheKiller you have your answer. maintainer decision it seems.

**Comment by RikuTheKiller** [comment]
> > Love how you closed it without addressing the main issue, that being that they cannot be upgraded. (And even added a "not a bug" label when it clearly describes the fact they cannot be UPGRADED with the literal on-station bluespace RPED that is meant for upgrading things.)
> > And the fact the charlie station sleeper board still exists.
> 
> do upgrades even do anything for sleepers? what stock parts do sleepers even have? there are several machines that dont have any actual use for being upgraded because it doesnt do anything (for example, the ORM).

Also just to comment on this, YES, upgrading sleepers has drastic effects and almost doubles the amounts of chemicals that can be used and also increases the severity of the wounds they can treat. (Up to -75% health.)

I honestly think that while deconstructability being removed is feasible, upgrading is not as it makes the sleepers pretty much completely useless compared to an upgraded version since you can't even heal people in fairly low critical. (Can't you just delete the board whenever a sleeper gets deconstructed apart from the charlie one rather than removing it at roundstart?)

**Comment by timothymtorres** [comment]
Feel free to have that discussion in another a PR that adds the feature you are wanting or talk with maints in coderbus.
