### ISSUE TITLE
Papers don't seem to handle sanitization serverside

### ISSUE THREAD

**Issue by CocaColaTastesGood** [tgstation/tgstation#65731]
## Reproduction:
1: Modify the text parameter to have your code. Scripts don't work without some form of bypass like using img.
2: Press save once, go to edit, then save again.
3: Paper contains code
This might be known already #50981

**Comment by CocaColaTastesGood** [comment]
![image](https://user-images.githubusercontent.com/47264839/160285047-d4b83975-63d2-4764-8f9e-0596dbbbdc18.png)

**Comment by optimumtact** [comment]
what text are you putting into the text parameter?

**Comment by CocaColaTastesGood** [comment]
> what text are you putting into the text parameter?

Sorry about the bad description.
![image](https://user-images.githubusercontent.com/47264839/160299691-85edcf5b-b825-4420-a882-b8c4904fd596.png)
I'm modifying the .js file first, it's not done fully in game. One of these parameters causes it, I'm not sure which though.

**Comment by optimumtact** [comment]
I see what you mean yeah.

**Comment by CocaColaTastesGood** [comment]
> I see what you mean yeah, are you just modifying this out of your local cache? I'm surprised byond will accept the modifed version (I guess I should not be)
I set a breakpoint on the tgui.bundle.js file with fiddler classic then modify the file before sending it. I don't quite remember if it works if you just overwrite the file in cache, I haven't tried in a while. I can see why you were so irritated with paper a while ago though.

**Comment by Mothblocks** [comment]
Have you tried seeing if this works on other people? You edit your cache to allow malicious JavaScript, then it works on others who read it and haven't?

This issue report doesn't make much sense--sanitization not being performed server-side is intentional because it all happens client side. Sanitization server side is why we kept getting into this mess, because it didn't work.

**Comment by CocaColaTastesGood** [comment]
> Have you tried seeing if this works on other people? You edit your cache to allow malicious JavaScript, then it works on others who read it and haven't?
> 
> This issue report doesn't make much sense--sanitization not being performed server-side is intentional because it all happens client side. Sanitization server side is why we kept getting into this mess, because it didn't work.

I'm just modifying what gets saved on the paper, not the actual contents of the paper. Sanitization is performed clientside, but it allows certain tags through either way otherwise papers wouldn't work, this issue could be partially mitigated by blacklisting images and videos as well since they are used to bypass the script tag filter or just show annoying content. I'm not sure if this would break anything though.

This was tested live though. 
![image](https://user-images.githubusercontent.com/47264839/160355950-441c3ef5-9d37-4fa6-9a8e-96ff578bc11e.png)

**Comment by Mothblocks** [comment]
Okay, I thought so. I remember doing some of this stuff myself.

We should just filter `img`. That's the only element like it.

**Comment by Mothblocks** [comment]
![image](https://user-images.githubusercontent.com/35135081/160452617-34bad411-d4d6-413b-bb96-e42d9e0f3264.png)

The odd thing is `img` isn't supported in the first place.

**Comment by Mothblocks** [comment]
@AnturK fixed this apparently but didn't link the PR

**Comment by LemonInTheDark** [comment]
Resolved by #65752 

We actually have tried sanitizing server side. It never worked. That's why we disabled it on live back then, and why in theory paper uses tgui.
Rather then trying to plug all the inputs, it's easier to just plug the output. This is somewhat influenced by the best sanitizer we have being js side.

Unfortunately, I think this was partly forgotten when paper code was implemented as it is now, since it was just sanitizing the input again, but this time with tgui. I hate this codebase

**Comment by optimumtact** [comment]
the point of doing it in tgui was
A) offloading the work to clients
B) being able to easily use a third party validator like markdown js which is doing the heavy lifting

even with this oversight, those things are still true Lemon

**Comment by LemonInTheDark** [comment]
Yeah but wasn't it done to prevent all the headache we had with handling encoding and such? We managed to offload the work to clients, but in a way where any untrusted client could fuck it up for everyone else, which seems like it defeats the point

**Comment by optimumtact** [comment]
no? the problem was we simply forgot to actually implement the sanitizing being done by the other clients?

The sanitising was never going to go away, that is just part of handling untrusted user input, the main goal was to offload that work to third party library developers && offload the rendering work to the client.

**Comment by optimumtact** [comment]
also it's worth noting I think part of it was from having to support all the legacy html papers.

**Comment by LemonInTheDark** [comment]
To be honest with you I was mostly concerned with making sure we didn't start relying on server side sanitization. I'm sorry if I misconstrued the history of the change. 

I do find it wildly funny that there was a large rework of paper code to stop abuse, which worked, when it didn't actually plug the hole fully, the guys messing with it just went away for like a year and a half
