### ISSUE TITLE
Emissives show through walls on the Z-Level above them

### ISSUE THREAD

**Issue by san7890** [tgstation/tgstation#65800]
Reporting client version: 514.1581

## Round ID:
[180764](https://scrubby.melonmesa.com/round/180764)

## Testmerges:
- [Pingbus changes and improvements](https://www.github.com/tgstation/tgstation/pull/65625)

## Reproduction:

Have an emissive (Air Alarm / Fire Alarm)
Place it on a wall
Go to the Z-Level above the wall, and place another wall.

Observe the following:

Upper Z-Level:

![image](https://user-images.githubusercontent.com/34697715/160757853-052507fc-c38d-4a21-bfbf-040e486d063e.png)

Lower Z-Level:

![image](https://user-images.githubusercontent.com/34697715/160757870-8f1cca33-c1a0-4a0b-a643-3e37008ea681.png)

Those grey spots perfectly correspond to the emissive portion of those alarms, so I blame that. I think this only shows up when you have /turf/openspace present (since those two are in that little stairwell in the IceBox Kitchen Area).

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/32d8a4e91d069c23cb2c509e24314e6495d62316/code/game/machinery/firealarm.dm#L97-L110

So the sprite that is bleeding over the top of the multi z appears to be from the `emissive_appearance` proc the code for that is:

https://github.com/tgstation/tgstation/blob/4537bbbe443ae2b9f07a0fd97714f03ad5bb9ae3/code/__HELPERS/lighting.dm#L1-L11

and if you compare that to the `mutable_appearance` proc:

https://github.com/tgstation/tgstation/blob/4e2a36fe7e56fad93495adf01c697f4b5de04e90/code/datums/mutable_appearance.dm#L7-L21

What's happening is that the `emissive_appearance`  is setting it's plane to a hardcoded `EMISSIVE_PLANE` regardless of parent object's plane.  In contrast to `mutable_appearance` proc that uses `FLOAT_PLANE` which is set to inherit the parent object's plane when rendering...

So this is my solution:

We set `emissive_appearance` plane to be EMISSIVE_PLANE + FLOAT_PLANE, and then we need to go to these defines

https://github.com/tgstation/tgstation/blob/8723e200a19c2e7ba2040ad4094ae73df210198a/code/__DEFINES/layers.dm#L5-L28

and subtract them by `EMISSIVE_PLANE` which is 150:

https://github.com/tgstation/tgstation/blob/8723e200a19c2e7ba2040ad4094ae73df210198a/code/__DEFINES/layers.dm#L131-L140

@LemonInTheDark I'm cc'ing you for thoughts on this.  Anything that uses the emissive appearance will have this problem with multi-z rendering.

**Comment by LemonInTheDark** [comment]
I've seen this, but need to think about it. I don't think your proposed solution will work out that well, since I think it would bork planemasters totally. Also its plane would just end up being the constant for EMISSIVE_PLANE + the constant for FLOAT_PLANE, these are just numbers and all. What we really want to do is hide any emission that isn't visible through openspace, at least I think. Outside of that standard emissive blocking ought to be fine? 

I think the way to do that would be somehow masking only emissives on the plane below us using the inverse of the openspace plane? not totally sure honestly, that seems like it wouldn't work either. I don't want to make all floors and walls emissive blockers tho, if that's the solution this is a bug we shouldn't fix.

**Comment by timothymtorres** [comment]
[FLOAT_PLANE is not a constant. ](https://www.byond.com/docs/ref/#/atom/var/plane) 

It is the inherited plane from an object's parent and is what MultiZ uses to render things to shift all child objects planes down when you set a turf to the OPENSPACE_PLANE.

If we just shift all the negative planes (that are lower than OPENSPACE) by the value of the EMISSIVE_PLANE (-150 in this case) nothing should (theoretically) break with the planemaster since their order will still be intact.  When I get my own PC I will play with these numbers and see if I can get it to work properly...

**Comment by timothymtorres** [comment]
> Anyway #67902 has a solution to this, by redoing how multiz works using stacked plane masters and manually offsetting planes on z level change. 

That's a smart solution.  Glad you were able to figure it out despite the massive amount of pain incurred as a result.
