### ISSUE TITLE
AI Can't use newscasters anymore.

### ISSUE THREAD

**Issue by unit0016** [tgstation/tgstation#65801]
Reporting client version: 514.1582

## Round ID:
[180767](https://scrubby.melonmesa.com/round/180767)

## Testmerges:
- [Pingbus changes and improvements](https://www.github.com/tgstation/tgstation/pull/65625)

## Reproduction:
Be AI, open newscaster. Cry.

Probably a proximity check issue? That's my guess. Didn't codedive on this one.

**Comment by unit0016** [comment]
Update: AI can now interact with the UI!
..Sadly they can't actually post anything still, but it's a start.

**Comment by FernandoJ8** [comment]
Been testing it and looking at the code. The issue seems to be that, when creating a channel or performing other such actions, the newscaster looks at the user's ID's bank account for information. If that information isn't present, it runtimes when creating a channel because there's one mispelling in the if checks. The runtime's easy enough to fix but we need to get a standardized way to deal with bank accounts for silicons, since they're still treated as a person without an ID and just get in-game error messages when trying to do anything.

**Comment by JohnFulpWillard** [comment]
I can use newscasters as AI, but anything I post comes up without a name
![image](https://user-images.githubusercontent.com/53777086/162565183-73fdbc89-90fa-423a-8a5b-65a60746466c.png)

**Comment by timothymtorres** [comment]
Also someone pointed out in a duplicate issue that cyborgs can use newscasters either.

**Comment by FernandoJ8** [comment]
> Also someone pointed out in a duplicate issue that cyborgs can use newscasters either.

Oddly enough in my first tests they could. Now I just tried while also checking if I could replicate John's results and they too cause a runtime. Oh and I couldn't manage to do anything as AI either, running up-to-date master it causes a runtime so uh... black magic I guess.

**Comment by JohnFulpWillard** [comment]
Closed by https://github.com/tgstation/tgstation/pull/66551
