### ISSUE TITLE
Health HUD bars on some players still showing after removing the health HUD,

### ISSUE THREAD

**Issue by RobertRoberts2020** [tgstation/tgstation#65925]
## Round ID:
[181059](https://scrubby.melonmesa.com/round/181059)

## Reproduction:

Not sure what the actual steps to reproduce this are

1) at some point I put health HUD glasses on
2) at some point I took them off and replaced them with mesons
3) I also used a mod suit at some point

![image](https://user-images.githubusercontent.com/38957322/161523347-164dee09-d058-4b2e-a708-7214b4e9607a.png)

**Comment by timothymtorres** [comment]
Were you using any visor modules with the modsuit?  How did you take off the health HUDs?

**Comment by TheBonded** [comment]
borgs and ais can see the health hud of anyone with their sensors maxed, perhaps this is somehow related? was there an AI in your modsuit, perhaps?

**Comment by Sealed101** [comment]
no relevant runtimes regarding the hud, the modsuit AI (it had that one fuckass runtime with deploying to shells that i've fixed in #78816) or the HoP, i think. with no other leads i don't think we can plausibly reproduce this
https://github.com/tgstation/tgstation/pull/65189 may have helped in some way i guess?
