### ISSUE TITLE
TGUI made a bluescreen while loading fancychat, d'awww

### ISSUE THREAD

**Issue by MrNihil** [tgstation/tgstation#66289]
## Round ID:
[181787](https://scrubby.melonmesa.com/round/181787)

## Reproduction:
1. Join game.
2. Wait for a fancy chat to fail to load, as it always does when you join a game.
3. Click LOAD FANCY CHAT
4. Get error:
A fatal exception has occurred at 002B:C562F1B7 in TGUI. 
TypeError: Object doesn't support this property or method „subscribe”
   at b (http://127.0.0.1:62878/tmp3404/tgui-panel.bundle.js:1:400245)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {}

Fancychat does not want to work despite multiple reloads.

(optional)
5. Contact local NT Support
6. Sigh audibly and die of old age waiting for a response.

**Comment by MrNihil** [comment]
Things that failed:

- Reboot
- Reinstall Byond
- Clear byond cache (you might need another reboot)

**Comment by stylemistake** [comment]
It is temporary because tgui received a major update with breaking changes, and server is currently in superposition, because it serves new javascript files, but the base html file is the old one (and html file defines the API that broke).

Round should end and server should be restarted, there's no other way.
