### ISSUE TITLE
Names on ID console are always Capitalized.

### ISSUE THREAD

**Issue by AssassinT90** [tgstation/tgstation#6633]
Reproduction:
Get an ID.
Change its name to "Does caPitalization work"
It will be renamed "Does CaPitalization Work"
Some (few) people have names that aren't capitalized. So they will never be matched to new IDs.
![image](https://cloud.githubusercontent.com/assets/6020070/5564349/e3781f8e-8eb8-11e4-9957-5bf30bd7a7bb.png)

**Comment by phil235** [comment]
I don't think this is a bug. Whenever you change a name (lobby options, choosing your clown name, ID console renaming) it always gets capitalized. The real bug is those uncapitalized names.

**Comment by Firecage** [comment]
@phil235 But I would prefer it if atleast one first letter in a surname of a character I create doesn't have a capital letter. Like many surnames IRL are.

**Comment by kevinz000** [comment]
@optimumtact im just going to tag you but this isn't a bug, i checked and what I found appears that the I console uses the same restrictions as game preferences on naming, so if this is "fixed" all it's doing is letting users pick non-allowed names in game because they can't do it roundstart, unless you want to do it for both.

**Comment by Jordie0608** [comment]
Whoops, forgot to comment; closed because the ID console disallowing names that would be disallowed by character creation is correct behaviour.
