### ISSUE TITLE
Thief and Opportunist have weird sprites for their preferences

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#66346]
## Round ID:
[181886](https://scrubby.melonmesa.com/round/181886)

## Testmerges:
The following pull requests are currently test merged:
[#66220: 'Add button to relaunch the game alongside reconnect when you lose connection' by Mothblocks at commit 99bf4a0cd5](https://www.github.com/tgstation/tgstation/pull/66220)

## Reproduction:
https://puu.sh/IVNLN/b8ef67f57a.png
open the preferences menu and click antagonists
counter strike missing graphics

**Comment by JohnFulpWillard** [comment]
I think this is caused by https://github.com/tgstation/tgstation/pull/65760

**Comment by Ebb-Real** [comment]
fairly sure its because the preview icon uses overlays on the dummy which dosen't go well with GAGS.
![image](https://user-images.githubusercontent.com/95765134/167915698-9618cee2-d666-429c-bcdc-a58905953177.png)

to fix it you would most likely have to make GAGS compatible with overlays or make the dummy not use overlays somehow.

**Comment by Ebb-Real** [comment]
fairly sure its because the preview icon uses overlays on the dummy which dosen't go well with GAGS.
![image](https://user-images.githubusercontent.com/95765134/167915698-9618cee2-d666-429c-bcdc-a58905953177.png)

to fix it you would most likely have to make GAGS compatible with overlays or make the dummy not use overlays somehow.
