### ISSUE TITLE
Rev Head demoted on Icebox station after changing z-level.

### ISSUE THREAD

**Issue by orthography** [tgstation/tgstation#66341]
## Reproduction: On icebox station was solo rev head chemist, got into cargo and had movement bug due to the ddos and went down the stairs to lower cargo z-level. Got a pop-up saying I was now enemy of the state and that the mutiny has been quelled. Didn't go outside, and I had gone down to the morgue at some point and hadn't gotten removed from rev head. 

The direct tile I was on was (Mining Station EVA (77,102,2))

**Comment by MrMelbert** [comment]
The lowest level of icebox is not considered "on the station Z level", and thus counts for exile for rev heads and heads of staff during a revolution

**Comment by SuperNovaa41** [comment]
Its not a bug but it certainly shouldn't happen

**Comment by TheBonded** [comment]
multiz stations were a mistake

**Comment by san7890** [comment]
It's an oversight that makes no sense given how well integrated the third Z-Level of IceBoxStation is with the cargo division... it doesn't largely make sense . I heavily endorse an update that makes the third Z-Level of IceBoxStation a part of the station to prevent stuff like this happening in the future.

**Comment by Zytolg** [comment]
The plan for level 3 is to have minimal access points. Naturally, providing cargo (mining) with an access point to all z's is a must since they're the ones who engage with it the most. Sec is second on the list due to gulag, and I suppose there could be some other sites here or there in the future. This is to all say, this was bound to happen sooner or later, and Multi-Z is a curse we all have to live with.
