### ISSUE TITLE
You can use dead carp as an indestructable vehicle (and become mostly immune to bullets)

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#66438]
Reporting client version: 514.1582

## Round ID:
[182002](https://scrubby.melonmesa.com/round/182002)

## Testmerges:
- [Dynamic 2022, Part 1 - Redesigning midround rolls (Midrounds happen far more frequently now, and scale their power over time)](https://www.github.com/tgstation/tgstation/pull/65997)
- [Human Life Optimization: Citrus Flavored](https://www.github.com/tgstation/tgstation/pull/66037)

## Reproduction:
![image](https://user-images.githubusercontent.com/66640614/164863109-2beb9569-5c66-4976-b6c0-9e82a1667b9d.png)
Nuke op was riding around a dead Cayenne, supposedly it made him immune to bullets. 
![image](https://user-images.githubusercontent.com/66640614/164863728-628e6e4a-1cae-4c2d-904d-a1ea4f13e815.png)

**Comment by RandomGamer123** [comment]
I was looking at projectile code recently, and I think I know why the bullet part happens:
https://github.com/tgstation/tgstation/blob/ee7f0d0a6080441148bf69c0a8e3b5afb174959a/code/modules/projectiles/projectile.dm#L461-L472
If the "original target" (ie the place the shooter pointed at) is not on the tile, then it tries to hit living objects, but if its a buckle stack with multiple mobs, it always picks the lowest mob. In this case the lowest one was Cayenne, which was dead, which meant that unless you aimed (ie. clicked on) the nukie directly, the bullets would all hit dead Cayenne instead. This is more of an oversight caused by the fact that you can buckle yourself to dead mobs (is this intended? should there have been a check for this? not sure), which would be the main cause of this.

**Comment by RandomGamer123** [comment]
(The lowest_buckled_mob check was added at first by https://github.com/tgstation/tgstation/pull/31660)

**Comment by interestingusernam3** [comment]
Ring di ding ding ring di di di ding
