### ISSUE TITLE
agent ids can't get lathe tax exemptions

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#66601]
<img width="454" alt="image" src="https://user-images.githubusercontent.com/42606352/166069648-82336631-5681-40fe-b782-4dc241f23cf9.png">
<img width="533" alt="image" src="https://user-images.githubusercontent.com/42606352/166069661-93992755-085c-4164-8d09-13d870e63f7e.png">

**Comment by ArcaneMusic** [comment]
So as it stands, a single job assignment has a payment department from the assigned parent job assigned as `paycheck_department`. Ideally, one player's ID should have a single payment department because they have a single department.

However, it makes more sense that something like an agent ID would have multiple payment departments as they get more access, so that they could avoid paying taxes while going under the radar from something like the accounting console. I have also heard in the last 24 hours that ID cards getting reassigned doesn't assign them a new payment department, likely as a consequence of the job refactor from a few months back.

**Comment by Palpetinus** [comment]
The year is 2022
The syndicate now commits the biggest crime of them all: tax evasion.
