### ISSUE TITLE
Mold cells cytology issues

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#66640]
## Reproduction:

Modly bread and moldy mess doesn't have any cells, which makes vatbeast impossible to make. I didn't know about maint mold pizza, might be too.

**Comment by moocowswag** [comment]
mold pizzas were the only thing I`ve seen/heard anyone say gives the cells for vat beast. 

I think its only limited moldy pizzas because its intended for vatbeast and alot of other cytology mobs to be rare and hard to get so you can`t just collect the hard to acquire chems and expect to always be rewarded.

**Comment by Rhials** [comment]
I'm pretty sure this was an intentional change made after some discussion in #61233.

moldy pizza/bread slices that have the cell lines attached to them are sometimes spawned into maintenance mini-fridges. There's a separate type of bread/pizza that food will decompose into that does not have a cell line attached.

**Comment by necromanceranne** [comment]
It's unfortunately intended, yes. The bacteria rich items are found in maintenance fridges and are quite rare. Other items don't count.
