### ISSUE TITLE
Telecomms "message monitor console" still has a button to "Send Admin Message" even though the feature was (stealth) removed by mod PDAs 

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#66777]
## Reproduction:

- Visit message monitor console
- Click "Send Admin Message"
  - Past: You could send fake pda messages to other people
  - Present: Button does nothing 
- Look up code and gitblame
- See mod PDAs removed the hrefs calls entirely that made this function work without replacing them, not mentioned at all in the changelog, but kept the button in for some reason

**Comment by magatsuchi** [comment]
oh man who did this one

**Comment by Hamcha** [comment]
I tried re-adding the functionality and I gave up because I don't understand the new code enough. If anyone wants to give it a shot this is the very little progress I did (works but I get runtimes): https://github.com/tgstation/tgstation/commit/4b2ae9c66425f4065dd6abc6a5794e4552f1ee5e

On another note: I want this to work because it lets Syndie Comms agent interact through messages and I feel they are very nerfed since this broke.
