### ISSUE TITLE
Holodeck Lounge Template Map Incompatibilities

### ISSUE THREAD

**Issue by san7890** [tgstation/tgstation#66884]
## Reproduction:

![image](https://user-images.githubusercontent.com/34697715/167770366-1d968605-dbfb-48dc-9610-591d47694b43.png)

On DeltaStation, the table directly impedes this airlock. I'm not sure if this might occur on other maps, though. However, please rearrange the _holodeck template_ to not potentially impede doors across all the five station maps (as possible), while still retaining as much of the original furniture as you can. Do not alter stations to fit this template.

**Comment by Son-of-Space** [comment]
This is going to need to be fixed by tweaking the space so that we can maintain consistency on how our templates are formatted. Delta has a 1 window gap between doors whilst all of our other maps have two. I'm working on something now that will stay consistent with how the rec area was mapped previously.
