### ISSUE TITLE
Zombies with Tongue Tied trait cannot speak.

### ISSUE THREAD

**Issue by notfrying1pans** [tgstation/tgstation#66979]
## Round ID:
#183132

## Testmerges:
#65791 
#65997 

## Reproduction:

* Make a character with the Tongue Tied trait
* Become a zombie
* Fail to speak, as zombie claws count as held items.

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/4d7a64fa30a45615518fc69f0776695f6b295491/code/modules/mob/living/living_say.dm#L340-L363

https://github.com/tgstation/tgstation/blob/7844b34a5fc507a3fd53ed2fc9eea690e9c1f0c7/code/datums/quirks/neutral.dm#L336-L360

https://github.com/tgstation/tgstation/blob/6397e99d24a9322ed10598696447710dc4d0fdf2/code/modules/mob/living/carbon/human/species_types/zombies.dm#L129-L139

This may have gotten fixed with Kapulimbs not too long ago, so this needs to be retested.
