### ISSUE TITLE
Mech refactor broke odysseus's ability to equip more then one item.

### ISSUE THREAD

**Issue by Shadowflame909** [tgstation/tgstation#67267]
## Reproduction: 
                             1. Make an odysseus.
                             2. Attach an item
                             3. Try to attach another one and get an error message like "The odysseus cannot hold ___ item!"
                             4. get confused because the items require each other to function.

This error has happened to other mechs prior and been resolved. Safe to say it probably effects all mechs at this rate. Similar issue here. #65777

**Comment by techno0** [comment]
Did you switch the targeted arm after attaching a item?

**Comment by Shadowflame909** [comment]
> Did you switch the targeted arm after attaching a item?

I tried to, but I was unable to swap modules. It'd just stay on the same one no matter how many times I clicked the button. Never going into an unarmed state.

**Comment by projectkepler-ru** [comment]
this also killed the odyseuss ability to do surgery which make me weep

**Comment by Sealed101** [comment]
ody mech can equip two out of three medical equipment pieces available at a single time, because the equipment pieces (syringe gun, sleeper and medibeam gun) are counted as mecha arm slots. ideally there should be some sort of feature for the ody to have a 3rd arm slot or similar to help with this but that's not really a mechanical issue is it now
