### ISSUE TITLE
Confusing messages when trying to close one closet in another

### ISSUE THREAD

**Issue by dragomagol** [tgstation/tgstation#67811]
Reporting client version: 514.1583

## Round ID:
[184988](https://scrubby.melonmesa.com/round/184988)

## Testmerges:
- [TGUI Say: Upgrades chat input with modern features](https://www.github.com/tgstation/tgstation/pull/67116)
- [Lemon attempts to optimize lighting [TM]](https://www.github.com/tgstation/tgstation/pull/67669)

## Reproduction:
Was trying to clean, dragged bodybag with garbage onto open locker. Tried to close locker, access denied. Removed bodybag and could close locker. Put non-bodybag things into locker and could close it.

**Comment by nemvar** [comment]
https://github.com/tgstation/tgstation/blob/9e98f8549c3846eccb87646f2027b550d66cfe18/code/game/objects/structures/crates_lockers/closets/bodybag.dm#L2

This is intentional behavior. Bodybags are not just structures (none of which can be put into lockers) but are themselves lockers in all but name.

Is the issue that an incorrect error message is displayed?

**Comment by dragomagol** [comment]
Testing this out on local, I think it's more an issue with the error message. If you have access to the closet and it locks, it tells you you locked/unlocked it (instead of closing it). If you do the same with a closet that doesn't lock, it provides no feedback.

**Comment by CPTANT** [comment]
Its not a confusing message per se, you DO lock the locker, its just weird behaviour that you lock the locker when you try to put another locker on it and close.
