### ISSUE TITLE
Blind people do not get notifications for being stripped or hit by objects, or being forcefed (and probably a lot more)

### ISSUE THREAD

**Issue by ZeroMODE0** [tgstation/tgstation#67815]
## Reproduction:
Asking the clown to throw something at you, object goes pap, no notification.
Clown forces Greentext into your hands, and you get shoved for it, then someone takes your shoes. You get no notifications for it being put into your hands, or your shoes getting taken.
Security takes your wig while you're not paying attention and feeds it to you. You do not get a notification for being forcefed your wig.

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/91210485510f655abdb8a6f244fd00045c070595/code/modules/mob/mob.dm#L235-L241

https://github.com/tgstation/tgstation/blob/76a11cc09e9cc073b9e07d9ffe007973a03efec6/code/game/objects/items/food/pie.dm#L44-L56

This stems from the proc `visible_message` having an optional `blind_message` arg that isn't used in a lot of places in the codebase.  To fix it is quite trivial since you just need to add something simple like `"You feel something sticky smack into your face!"` as the third message whenever `visible_message` is used.

There are probably thousands of places where blind messages need to be added to.

**Comment by ZeroMODE0** [comment]
During [round 185022](https://sb.atlantaned.space/rounds/185022) I learned that blind people:

- Do not get notifications for being stun batonned
- Do not get notifications for being facehuggered, xeno blue intented, or xeno red intented (Even though you can hear a whoosh when the xeno queen uses their spinny attack)
- Do not get notifications for getting pepper sprayed
- Do not get notifications for being ebow'd and Hypertool'd
- Do not get notifications for being shoved and hit by an article of clothing
- Cannot use health analyzers
- Cannot use the DNA vault (Probably intended)

Most things that happen directly TO you need to be seen to get a notification and know what happened, unless you're paying a lot of attention to the screen and seeing it happening. You get notifications when there's something embedded in you, but not the notifications when something embeds, etc.

**Comment by timothymtorres** [comment]
We probably want to be using these types of messages:

https://github.com/tgstation/tgstation/blob/91210485510f655abdb8a6f244fd00045c070595/code/modules/mob/mob.dm#L291-L327

We could potentially rework visible messages so that when it's a `self_message` you still get a notification while blind since it's likely something you are touching.
