### ISSUE TITLE
Luxury shuttle takes your money even if you don't have 500 credits

### ISSUE THREAD

**Issue by rellyreri** [tgstation/tgstation#67824]
Reporting client version: 514.1583

## Round ID:
[185028](https://scrubby.melonmesa.com/round/185028)

## Testmerges:
- [Optimizes Runechat](https://www.github.com/tgstation/tgstation/pull/65791)
- [Lemon attempts to optimize lighting [TM]](https://www.github.com/tgstation/tgstation/pull/67669)
- [TGUI Say: Upgrades chat input with modern features](https://www.github.com/tgstation/tgstation/pull/67116)

## Reproduction:

1. Try to pass luxury shuttle gate with less than 500 credits
2. Fail
3. Check bank account
4. Realize you now have 0 credits
5. Cry

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/36b885292223a2bf0f7242a8a5485fa55682befb/code/modules/shuttle/special.dm#L307-L314

https://github.com/tgstation/tgstation/blob/36b885292223a2bf0f7242a8a5485fa55682befb/code/modules/shuttle/special.dm#L392-L399

There should have been a credit received message that pops up since it takes whatever balance you have and lowers the cost to get through the gate.

**Comment by rellyreri** [comment]
it does infact, lower the cost.
