### ISSUE TITLE
Can't fire two Bulldog Shotguns at the same time

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#67871]
## Reproduction:

Although the Bulldog Shotgun requires only one hand to fire, Сombat Mode with shotguns in both hands only one in the active hand fires.

**Comment by ArcaneDefence** [comment]
https://github.com/tgstation/tgstation/pull/27978
The bulldog being a medium weight weapon is intentional
https://github.com/tgstation/tgstation/blob/30751c318f5c74db0c06d19dbd12006415fa1c65/code/modules/projectiles/gun.dm#L238-L253
Unless you're asking for feedback messages, I don't see why this issue should remain open.

**Comment by nemvar** [comment]
I don't see why this issue should remain open.
