### ISSUE TITLE
Rat King can summon nearly infinite simplemobs 

### ISSUE THREAD

**Issue by thgvr** [tgstation/tgstation#67926]
Reporting client version: 514.1583

## Round ID:
[185331](https://scrubby.melonmesa.com/round/185331)

## Testmerges:
- [Optimizes Runechat](https://www.github.com/tgstation/tgstation/pull/65791)
- [Mining Outpost Overhaul: Island Living Edition](https://www.github.com/tgstation/tgstation/pull/67796)
- [Completely removes `proc_holders` from existence. Refactors all wizard, xeno, spider, and genetics powers to be actions. Also refactors and sorts ton of accompanying code. ](https://www.github.com/tgstation/tgstation/pull/67083)

## Reproduction:
Be rat king
Click on disposal bin for an uncountable amount of time
Click rat button once. The rats will multiply.
Click it again, they all turn into hostile simplemobs that stack on top of eachother, and the corpses layer above them, each doing five damage a hit.
Repeat until you can instantly kill anyone who comes near.

I assume this is supposed to be capped.

**Comment by CursedBirb** [comment]
I assume that you have not seen Manuel "RAT VAULT" incident

**Comment by ArcaneMusic** [comment]
The crux of your issue is misinformed,

We have a config based variable called `/datum/config_entry/number/ratcap`. It prevents the spawning of any mice, or rats, based on that config to prevent an infinite cascade of either rat kings spawning an army, OR, a player breeding an infinite stack of mice. 

We need to confirm that this is reproducable first, as I'm unsure how the disposals bin interacts with this mechanic.

**Comment by ArcaneMusic** [comment]
Nope, I can confirm, they cannot go over the rat cap. The Disposal bins don't go over that number, so this is not a bug. If you'd like the number changed, that's part of the config and you can speak with the headmins or head over the policy subforum to ask for it to be changed.
https://tgstation13.org/phpBB/viewforum.php?f=33&sid=4d59f5ae43f7fbf4a71be638b7f4e307
