### ISSUE TITLE
Random station name generator can create at least one unfortunate combination

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#67934]
Terry in round 185366 started with "White Pride Center" as the station name. Big yikes.

**Comment by san7890** [comment]
> I am closing this as this is not an issue with the code or game balance. Please keep this in mind for future issue reports.

Who are you?

**Comment by optimumtact** [comment]
This seems pretty rare, is there a reason why you cant resolve this by just editing the name?

**Comment by optimumtact** [comment]
Or you could just do your job

**Comment by LemonInTheDark** [comment]
ahem
the "issue" here is ironically caused by the pride name, which only rolls during pride month (hhhhh)
that's 1/52 weeks in the year.
white is a 1/41 draw (there's more prefixes that would cause "trouble", though not as on their face)
center is a 1/65 draw
oh and prefixes will only roll 1/10 times
multiplying those all out gets us 1 out of 1385800 per year
but that's a bit unfair, since it assumes we only get one chance of seeing the roll per year, which isn't right
lets see, 7 days in a week, maybe ah 40 rounds a day? so that brings us up to a chance per year of 1/4949
so you could expect to see this combination maybe once every five thousand years

**Comment by TheVekter** [comment]
> ahem the "issue" here is ironically caused by the pride name, which only rolls during pride month (hhhhh) that's 1/52 weeks in the year. white is a 1/41 draw (there's more prefixes that would cause "trouble", though not as on their face) center is a 1/65 draw oh and prefixes will only roll 1/10 times multiplying those all out gets us 1 out of 1385800 per year but that's a bit unfair, since it assumes we only get one chance of seeing the roll per year, which isn't right lets see, 7 days in a week, maybe ah 40 rounds a day? so that brings us up to a chance per year of 1/4949 so you could expect to see this combination maybe once every five thousand years

Listen, you're not allowed to invalidate my concern by using logic or math, okay?
