### ISSUE TITLE
Xenomorphs can two-shot humans and one-shot cyborgs using corrosive acids

### ISSUE THREAD

**Issue by SarmentiCampbell** [tgstation/tgstation#67968]
## Reproduction:
1.  Be a drone or any xenomorphs that can use corrosive acids
2. Find victim, preferably a cyborg
3. Puke on them by using your ability 'corrosive acid' 
4. ???
5. Profit.
![unknzown](https://user-images.githubusercontent.com/61919894/175456747-2c980dc3-dc03-409d-957f-dc48909aa5b2.png)

**Comment by jjpark-kb** [comment]
acid_act is the reason. Should you be able to vomit over mobs? totally. one/two shot? probably not.

**Comment by ATH1909** [comment]
This ability previously could only be used on, like, structures, right? I suspect some rework or another accidentally made it able to target living creatures.

**Comment by TemporalOroboros** [comment]
ATH's right. The old behavior only let it target objects and turfs. The alien vomit acid volume got put through the moon when I refactored acid into a component to keep the timing on melting turfs roughly comparable since the new decay is exponential and the old system mandated ~30 cycles or so. I wasn't exactly balancing around it being applied to mobs because that wasn't a thing.

If you want to keep mobs on the possible targets list you're going to want to lop off most of the acid power and volume on the vomit. Make sure you drop the turf melt threshold too if you drop the power or you'll break xenos melting walls. Keep in mind that if it falls under ~40 or so fluoro will become capable of melting through walls. Similarly, you'll need to rescale either the wall melting cycles or the decay rate of acids as a whole if you significantly decrease the volume.

**Comment by Likteer** [comment]
No-one used to notice, because the "balance" for it used to be the ancient non-tgui menu asking what you wanted to spit at.

**Comment by Shadowflame909** [comment]
vomiting takes like a crazy amount of plasma anyways right. Like 200?

If you got a borg alone, definitely should be powerful and costly. Which I think it is currently since you're out of plasma to stop any other combatants.

**Comment by CoffeeDragon16** [comment]
#67083 is refactoring corrosive acid, once it's merged I should check in on this and see if it fixed it

**Comment by nemvar** [comment]
benos op
