### ISSUE TITLE
Alien Biological tools are impossible to research.

### ISSUE THREAD

**Issue by Xander3359** [tgstation/tgstation#68140]
Reporting client version: 514.1583

## Round ID:
[185909](https://scrubby.melonmesa.com/round/185909)

## Testmerges:
- [Makes pAI screen alert actually work](https://www.github.com/tgstation/tgstation/pull/68118)
- [Optimizes Runechat](https://www.github.com/tgstation/tgstation/pull/65791)
- [Completely rewrites the orbit screen](https://www.github.com/tgstation/tgstation/pull/68054)

## Reproduction:
Despite the challenging slime survey being removed, the alien biological tools require it, so it's impossible to actually get it. It also requires a pre-requisite tech that doesn't seem to exist.

**Comment by Salex08** [comment]
I tested it on a local server it works, once you inserted alien tools you can choose between unlocking alien tech node or alien biological tools node first and the challenging slime survery isnt removed it still shows up in the experimantal scanner even before you unlock the alien biological tool node

**Comment by VladinXXV** [comment]
The easy and medium slime experiments were removed, but challenging has not been removed. "Alien Biological Tools" has two prerequisite technologies: "Advanced Biotechnology" and "Alien Technology". "Alien Technology" requires you to deconstruct some other abudctor gear. So in order to get "Alien Biological Tools" using, say abductor surgery tools found on the crashed UFO ruin on lavaland, you'll need to bring back TWO tools to deconstruct.

**Comment by timothymtorres** [comment]
Based on what others have said, I'm going to mark this as `Not a bug` and it will autoclose in 7 days.
