### ISSUE TITLE
Tramstation's xenobio's disposals removes the floor tile that is underneath it when engaged

### ISSUE THREAD

**Issue by Pepsilawn** [tgstation/tgstation#68248]
## Round ID:

Found on downstream then later replicated on local tg code server.

## Reproduction:

![image](https://user-images.githubusercontent.com/25415050/177744959-836b818f-e2af-466c-bc3b-2137f34d63a7.png)

- Put any item into these disposal bins normally used to throw things into the chambers.
- Wait for it to engage/engage it yourself.
- Floor tile that's underneath the bin will fly off its tile.

**Comment by timothymtorres** [comment]
@san7890 I'm not sure what to make of this?  Is this a mapping issue or maybe the dir on the dipsoals is messed up?

**Comment by san7890** [comment]
I'm not sure if disposals bins placed right on top of "Disposal trunk that goes down" will work, hence resulting in the floor tile popping off since it's not in a valid configuration (like if you didn't have a trunk at all). You might have to use a normal trunk, _then_ feed that directly into "Down" disposals trunk that feeds into the "Up" disposals trunk. In (hopefully) easier terms, I don't think disposals bin will directly work on `/obj/structure/disposalpipe/trunk/multiz/down`, maybe only just `/obj/structure/disposalpipe/trunk`, which you then have to feed and route into `/obj/structure/disposalpipe/trunk/multiz/down`.

You could also figure out the code to see if you can have it be a valid configuration. Mapping option sounds simpler.

**Comment by orthography** [comment]
@san7890 Tested using just a normal trunk under the disposals. Tiles still pop off.

**Comment by san7890** [comment]
> @san7890 Tested using just a normal trunk under the disposals. Tiles still pop off.

I mean like this:

![image](https://user-images.githubusercontent.com/34697715/178063917-9b6c8170-d8c4-4235-b998-44b8b050e286.png)

![image](https://user-images.githubusercontent.com/34697715/178064259-f847fd80-4d7e-47a2-a3b7-1e4d5f91658b.png)

Which works fine on my local:

![image](https://user-images.githubusercontent.com/34697715/178064604-64576d0b-3f62-4386-bbaa-436ed18a614f.png)
