### ISSUE TITLE
Symbiotic resilience doesn't prevent instability stat mutations 

### ISSUE THREAD

**Issue by trexter5555** [tgstation/tgstation#68440]
RoundID 186666

on the wiki it says for symbiotic resilience: Prevents stat mutations resulting from instability.

it does no such thing, the stats do mutate. so the wiki is inaccurate or its bugged

**Comment by the-orange-cow** [comment]
Round ID: 188696
BYOND Version: 514.1583
Server revision compiled on: 
Master commit: [4e6c617da441bc4aec494f6fa6b354087f10b411](https://www.github.com/tgstation/tgstation/commit/4e6c617da441bc4aec494f6fa6b354087f10b411)
The following pull requests are currently test merged:
[#69031: 'Unique ambience for virology!' by DrDiasyl at commit 4e75783760](https://www.github.com/tgstation/tgstation/pull/69031)
[#69084: 'Fixes storage mass transfer being generally broken, adds mass transferring onto griddles ' by MrMelbert at commit f6b78a59fa](https://www.github.com/tgstation/tgstation/pull/69084)
[#69091: 'Kills `/obj/shapeshift_holder`, replaces it with `/datum/status_effect/shapechange_mob`, also does a lot of Wabbajack refactoring' by MrMelbert at commit 5a1d137cf2](https://www.github.com/tgstation/tgstation/pull/69091)
[#69181: 'Buffs Heretic Curses, Living Heart, Leeching Walk, and technically Entropic Plume by fixing some bugs' by MrMelbert at commit ed75f232d1](https://www.github.com/tgstation/tgstation/pull/69181)

Local commit: 401c0ba36f93d7c5a6a1965e0611697711cf6dbd
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

So, I just tested this out live and didn't observe what you're describing.  I grafted jumping beans, then added the graft to aloe while raising instability, and observed it over 10 minutes as the instability climbed(from around 30 to 100).

The symbiotic resilience trait only prevents stat changes due to instability, but not stuff like yield loss due to weeds and potency loss due to pests.  It also doesn't stop the instability itself from rising, as that is due to a fertilizer, and of course fertilizers can still change stats.

Is it possible you were experiencing stat changes due to fertilizer, weeds, or pests?

**Comment by Mooshimi** [comment]
cleanup tag to give them a week to answer the above question to continue discussion before this closes, thanks for looking into this @the-orange-cow

**Comment by the-orange-cow** [comment]
I worded that poorly, it does stop instability from rising due to instability mutation.  I meant the instability can still rise due to fertilizer.  The wiki is correct.
