### ISSUE TITLE
Golems are completely immune to flesh worm attack

### ISSUE THREAD

**Issue by private-tristan** [tgstation/tgstation#68970]
## Round ID:
[187854](http://127.0.0.1:51105/tmp3808/eced00dc.htm?action=openLink&link=https%3A%2F%2Fsb.atlantaned.space%2Frounds%2F187854)

## Testmerges:

[#68763: 'Adds the Mothroach' by Justice12354 at commit 55f95faa96](https://www.github.com/tgstation/tgstation/pull/68763)
[#68630: 'Revolution victories now call the shuttle when enough of the station is revolutionaries' by Mothblocks at commit c001c14cf6](https://www.github.com/tgstation/tgstation/pull/68630)

## Reproduction:

turn into worm
attempt to attack golem
watch as all your attacks  bounce off of them
cry

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/2ff790863981eda4e2cf1fe2dcdc65040497f0b2/code/modules/mob/living/carbon/human/species_types/golems.dm#L1-L21

https://github.com/tgstation/tgstation/blob/1f8479c877460f68f047bbf5f8dad835271dba9e/code/modules/mob/living/simple_animal/heretic_monsters.dm#L303-L321

Golems have the trait `TRAIT_NODISMEMBER` which makes them immune to the attacks.  This looks intentional but I will let @MrMelbert confirm.
