### ISSUE TITLE
Savannah-Ivanov cannot shot missile

### ISSUE THREAD

**Issue by trexter5555** [tgstation/tgstation#69278]
RoundID 188742

[#69031: 'Unique ambience for virology!' by DrDiasyl at commit 4e75783760](https://www.github.com/tgstation/tgstation/pull/69031)
[#69084: 'Fixes storage mass transfer being generally broken, adds mass transferring onto griddles ' by MrMelbert at commit f6b78a59fa](https://www.github.com/tgstation/tgstation/pull/69084)
[#69091: 'Kills `/obj/shapeshift_holder`, replaces it with `/datum/status_effect/shapechange_mob`, also does a lot of Wabbajack refactoring' by MrMelbert at commit 5a1d137cf2](https://www.github.com/tgstation/tgstation/pull/69091)
[#69181: 'Buffs Heretic Curses, Living Heart, Leeching Walk, and technically Entropic Plume by fixing some bugs' by MrMelbert at commit ed75f232d1](https://www.github.com/tgstation/tgstation/pull/69181)

create the dean ivanov mech
attempt to use the missile
it doesnt do anything after pressing the button (the screen gets a red tint and the cursor is a missile, had a co-pilot)
cant launch the missile or whatever
it is entirely possible it is not broken and i just dont know how to use it

**Comment by trexter5555** [comment]
tried another round and it worked if i shot the missiles instantly after pushing the button, weird

**Comment by SethLafuente** [comment]
I think what happened is that they didnt understand that mechs can only shoot and do stuff through the area they are looking at and they tried to shoot behind them which didnt work since the mech dosent have a field of view to shoot things there and I dont think its meant to be able to do so as shown in the video below:



![dreamseeker_9NPPutAZn4](https://github.com/tgstation/tgstation/assets/84478872/4d532377-2e68-4829-adf0-a7a61b2a38ee)

Otherwise if the missiles where not fully working now they do

**Comment by Sealed101** [comment]
sounds plausible
