### ISSUE TITLE
Custom Vendor explodes when you admin delete it

### ISSUE THREAD

**Issue by lessthnthree** [tgstation/tgstation#69444]
## Reproduction:
As an admin, shift-right click the vendor and select Delete
/obj/machinery/vending/custom

![image](https://user-images.githubusercontent.com/83487515/186540320-585d7895-126b-465b-82b1-12683e4ee18a.png)

Why this is a problem:
The player was standing right next to the vending machine and it sent them flying across the room into the wall. While hilarious in retrospect, should probably not happen.

**Comment by timothymtorres** [comment]
The commit in https://github.com/Tlaltecuhtli/tgstation/commit/3b65c9ffb005a0e8b40bad1a9ab49f5642232623 added this and the PR in #46240 or #45736 makes no mention in the changelog about adding in explosions or why they were needed.  

@Tlaltecuhtli or @MrMelbert is this necessary especially since the items get dropped anyway?  Maybe the items should just be `QDELETED`

**Comment by lessthnthree** [comment]
The explosion is an anti-theft measure so people don't smash the machine and steal everything inside.

**Comment by LemonInTheDark** [comment]
> The commit in [Tlaltecuhtli@3b65c9f](https://github.com/Tlaltecuhtli/tgstation/commit/3b65c9ffb005a0e8b40bad1a9ab49f5642232623) added this and the PR in #46240 or #45736 makes no mention in the changelog about adding in explosions or why they were needed.
> 
> @Tlaltecuhtli or @MrMelbert is this necessary especially since the items get dropped anyway? Maybe the items should just be `QDELETED`

Tim, in the words of skog, there is always a shotgun.

**Comment by Kapu1178** [comment]
omegalul
