### ISSUE TITLE
IV Plumbing containers don't work (or aren't obvious how they work)

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#69539]
Reporting client version: 514.1585

## Round ID:
[189469](https://scrubby.melonmesa.com/round/189469)

## Testmerges:
- [Day and night controller](https://www.github.com/tgstation/tgstation/pull/68239)

## Reproduction:

This may simply be user error but...

Create the following setup, all wrenched down.  Producers are 5u water.  Note that the random chem tank fills up but the IV tank doesn't.

![image](https://user-images.githubusercontent.com/3789327/187257995-7fc23c5e-0eae-482c-91eb-2c0e151002cd.png)

Also of note, the UI could do with hiding the "container / eject" section of the UI if use_internal_storage=TRUE for the iv_drip since such controls are not relevant if not using an external storage and may confuse players.

**Comment by Time-Green** [comment]
Working as intended, see the plumbing IV’s description. Flow is put straight into their bloodstream, and drawn blood is put into the actual IV. There’s no bloodstream so there is nowhere to put the reagents

This is done because otherwise the two reagents would mix. Plumbing supports handling multiple reagent holders for one object, but it’d require a rework of IV’s
