### ISSUE TITLE
Igniting a stack of plasma now explodes when it previously just flooded plasma

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#69579]
## Reproduction:

- Spawn a stack of plasma
- spawn a welder
- bring one to the other

expectation:
- a cloud of hot fire is released
old reality:
- this happened
current reality:
- it explodes in your face

**Comment by Palpetinus** [comment]
Seems like according to /datum/material/plasma, anything made out of plasma (including sheets) has the explodable component.

```
/datum/material/plasma/on_applied(atom/source, amount, material_flags)
	. = ..()
	if(ismovable(source))
		source.AddElement(/datum/element/firestacker, amount=1)
		// Ideally exploding plasma objects should delete themselves but we still have the flooder and SSexplosions to rely on deleting it asynchronously so it's not that bad.
		source.AddComponent(/datum/component/explodable, 0, 0, amount / 2500, 0, amount / 1250, delete_after = EXPLODABLE_NO_DELETE)
	source.AddComponent(/datum/component/combustible_flooder, "plasma", amount*0.05) //Empty temp arg, fully dependent on whatever ignited it.
```

And according to the file's history, it was always how it worked (/how it was intended to work?)
And anecdotally, I distinctly remember playing in mid-2021 and blowing myself up by trying to reload a plasmacutter with plasma by clicking it.

**Comment by timothymtorres** [comment]
Plasma has both the [explodable](https://github.com/tgstation/tgstation/blob/master/code/datums/components/explodable.dm) and [combustible_flooder](https://github.com/tgstation/tgstation/blob/master/code/datums/components/combustible_flooder.dm) components which use the same trigger involving heat.

Blowing yourself up with plasma cigarettes has been a thing since like r4407.  The gas flooding effect was added afterwards.

Honestly feel like the explosion effect should have precedence when it comes to heating.  Gas flooding should be triggered by something else.

**Comment by vincentiusvin** [comment]
Cant reproduce the not making plasma part. Only found that the temperature is broken, making the plasma room temp. I think that's what you're noticing.
Ill open a PR to address it and tag it as a fix, if it doesn't actually fix it bug me again. 

Proof it works on my machine:
https://user-images.githubusercontent.com/54709710/187648280-01d3e56b-3862-46f5-8899-14a4b07495c5.mp4
