### ISSUE TITLE
Mining Shuttle locked down at roundstart

### ISSUE THREAD

**Issue by Kitfox88** [tgstation/tgstation#69641]
Reporting client version: 514.1585

## Round ID:
[189655](https://scrubby.melonmesa.com/round/189655)

## Testmerges:
- [Buffs Heretic Curses, Living Heart, Leeching Walk, and technically Entropic Plume by fixing some bugs](https://www.github.com/tgstation/tgstation/pull/69181)
- [Moves "catch this var/flag" code from obj/init and datum/new into the types that use it ](https://www.github.com/tgstation/tgstation/pull/69634)
- [Macro optimizes SSmapping saving 50% ](https://www.github.com/tgstation/tgstation/pull/69632)

## Reproduction:
Start game on Tram
Be excited to mine
Get brutally mogged by the chad mining shuttle lockdown
Virginwalk to the public shuttle or labor shuttle instead

**Comment by msgerbs** [comment]
Can you be more specific, what is "lockdown"?

**Comment by Kitfox88** [comment]
The shuttle control consoles indicated that they were in Lockdown and could not be used to activate the shuttle for travel to or from a place. The normal miners couldn't control it and I as a mining borg could not control it. The prison labor shuttle worked once to go to lavaland but couldn't return, the only shuttle that seemed to be functional the entire shift was the public access shuttle.

**Comment by msgerbs** [comment]
So, it looks like the Locked status is caused by it not being able to find a docking port to dock at. I don't really understand how that could just spontaneously occur, and I can't reproduce it. My suggestion is to ahelp if you see this again so an admin can check it out.

**Comment by msgerbs** [comment]
So I did a bit more digging, and it kind of looks like the mining shuttle console at first got linked to the public shuttle. The first shuttle log event is:

`Floral Shoppe/(Richter Rat) has sent shuttle "the lavaland shuttle" towards "mining_away", using the mining shuttle console.`

This shouldn't happen, that's the wrong shuttle for that console. However, because the console is what determines where you can send a shuttle, the player was able to send the public shuttle to the mining shuttle dock on lavaland. Later on, I see the opposite:

`Deadeagle/(Tate Brier) has sent shuttle "the lavaland shuttle" towards "mining_home", using the mining shuttle console.`

I also see a couple times where the mining shuttle was, in fact, moved. However I am guessing that for most of the round it was blocked by the public shuttle. In any case, I think the issue lies in the mining shuttle console linking to the wrong shuttle... somehow. I wasn't able to reproduce, but hopefully somebody else will stumble upon it.

**Comment by Kitfox88** [comment]
I did adminhelp it to try and figure it out but yeah they were confused too. Either way it wasn't a huge round ruiner, just meant mining was a little more inefficient than usual.

**Comment by msgerbs** [comment]
My plan is to improve shuttle logging to hopefully make it easier to track down something like this in the future. It's not the first time I've had to dig around to figure out a shuttle going where it wasn't meant to go and breaking things, sadly :)

**Comment by msgerbs** [comment]
I got it! @JohnFulpWillard pointed me in the right direction. This is caused by a snowflakey override for people with TRAIT_ILLITERATE interacting with the mining shuttle console. Problem is that this override is also present on the public shuttle consoles. When an illiterate player interacts with these consoles, the shuttle is _always_ sent to mining_home or mining_away regardless of whether it's the mining shuttle, the public shuttle, or something else entirely. I have a few ideas to fix this and I'll work on it over the next few days.

**Comment by WarlockD** [comment]
It might have something to do with both shuttles unlocking and locking the target locations.  I know that was a bug with the shuttle code where you could put a custom location just a little offset where you are at and it would put down two copys of the shuttle and not delete them properly.  Especaily on rotates.

**Comment by msgerbs** [comment]
Made a PR to hopefully fix this. Instead of hardcoding illiterates to send only the mining shuttle, they just send whatever shuttle to a random valid destination. Meaning the public shuttle gets send to its appropriate dock instead of the mining dock, as well as the labor shuttle, etc. which will hopefully stop this issue from happening again.

**Comment by msgerbs** [comment]
Oops that wasn't actually the issue but I fixed _something_!

**Comment by msgerbs** [comment]
The very first shuttle move recorded in the logs was sending the public shuttle from the mining shuttle console, and the user who moved it posted the below video in discord.

`02:21:41 | SHUTTLE | LePiromano/(Lepir Omano) has sent shuttle "mining_common" towards "mining_away", using the mining shuttle console.`

https://user-images.githubusercontent.com/1313921/192081401-1b0ea841-d6a7-4969-9dbc-a6ad4fb8e748.mp4
