### ISSUE TITLE
Passive slime extracts do not work in modsuit storage

### ISSUE THREAD

**Issue by YakumoChen** [tgstation/tgstation#69682]
## Reproduction:
Tested with light pink stabilised. Put it in a medical modsuit. Did not run fast. Held the extract in hand or in pocket. Ran fast.

**Comment by Time-Green** [comment]
Does it work in a normal backpack?

**Comment by YakumoChen** [comment]
I'm not sure, haven't had the chance to test

**Comment by Time-Green** [comment]
I'd appreciate if you could include a round ID next time and whether normal backpacks are also broken

**Comment by Time-Green** [comment]
Stabilized extracts indeed don't seem to work from modsuit storages. Normal bags and inhand works fine
I believe it's because the storage module is not directly attached to the mob, but to the modsuit which is attached to the mob. Ugggggh

Relevant snippet:
https://github.com/tgstation/tgstation/blob/cf77fd39cfe294173762fb67c84971a5d76bfb64/code/modules/research/xenobiology/crossbreeding/_status_effects.dm#L445
