### ISSUE TITLE
Pirate-ships cant be piloted, leaving pirates stranded in space

### ISSUE THREAD

**Issue by realthomas69** [tgstation/tgstation#69776]
## Round ID:
[190085](https://scrubby.melonmesa.com/round/190085), [190057](https://scrubby.melonmesa.com/round/190057)

## Reproduction:
The pirate shuttle navigation console will not function and states this message:
![image](https://cdn.discordapp.com/attachments/952505243525062658/1017334990310227968/unknown.png)
You cant pilot the ship to go anywhere, so you're stranded without admin intervention

**Comment by rasepretep** [comment]
I wonder if this is related to the issue with mining shuttles we currently have, where either public or mining (on Tram) is unable to be controlls and the consoles just mess with the one that does work.

**Comment by Kitfox88** [comment]
Yeah, for what it's worth I haven't seen the mining shuttle issues anywhere but tram.

**Comment by msgerbs** [comment]
I strongly doubt this is related to the issues with the mining shuttle, however more reports would help. Feel free to drop some round IDs where you've had mining shuttle issues in #69641 (preferably with scrubby links if you love me!)

The pirate shuttle uses a completely different system to move and IIRC creates its own docking location from the camera console. It's interesting that this broke because I was just a pirate last week and it worked fine, and also there was a battlecruiser last night on Sybil that was moving just fine as well and that uses the same system I believe.

**Comment by TheVekter** [comment]
Happened in round 190171 as well, this time on Meta.

**Comment by msgerbs** [comment]
When you've seen this have you ahelped? Would be curious if an admin could see anything obviously wrong when looking at the console.

**Comment by TheVekter** [comment]
> When you've seen this have you ahelped? Would be curious if an admin could see anything obviously wrong when looking at the console.

I am an admin. I don't know enough about the issue to tell you if anything was wrong. Are you in our Discord? I can ping you next time it happens.

**Comment by msgerbs** [comment]
> > When you've seen this have you ahelped? Would be curious if an admin could see anything obviously wrong when looking at the console.
> 
> I am an admin. I don't know enough about the issue to tell you if anything was wrong. Are you in our Discord? I can ping you next time it happens.

I'm VexingRaven in Discord, feel free to ping me and if I'm not busy I can try and go through some troubleshooting.
