### ISSUE TITLE
Bone material floor tiles have no inhand sprite

### ISSUE THREAD

**Issue by Rhials** [tgstation/tgstation#69949]
## Reproduction:

Kill dragon

craft material floor out of his bones

![image](https://user-images.githubusercontent.com/28870487/190549863-3c885b07-60a0-498d-8910-a47006a302ed.png)

oh my goodness gracious

**Comment by timothymtorres** [comment]
The original PR that added bones was in #66181

**Comment by Hoolny** [comment]
After further investigation it seems like this is an issue with all material tiles, not only bone, 

this is probably do to this
![xFoyKDW](https://github.com/user-attachments/assets/7343ab1d-a7f0-4642-aa76-5ffec7beff9e)
material floor tiles don't really have anything to connect them to as far as in hand sprites come, they do seem to show a variation in their error changing their color slightly, not sure why that is.
![dreamseeker_9LydKsFUBx](https://github.com/user-attachments/assets/c1427656-8d97-4090-aa2a-8538a778653f)

I will be renaming this to be more accurate instead of closing it.
