### ISSUE TITLE
Random bits of kudzu are parralaxed on all layers just like the access indicator on doors used to be

### ISSUE THREAD

**Issue by ZAMODA** [tgstation/tgstation#70834]
Reporting client version: 514.1585

## Round ID:
[193197](https://scrubby.melonmesa.com/round/193197)

## Reproduction:
Have kudzu spawn on the lower level of icebox, specifically in the lower area of the service hall
see this:
![image](https://user-images.githubusercontent.com/36141254/198322551-796abb83-e5d8-412a-b260-3f359a6e12c8.png)

**Comment by Mooshimi** [comment]
strange lookin house plant you got there

**Comment by blackdav123** [comment]
Experienced this bug too, the kudzu that is acting fucky has the trait timid (https://github.com/tgstation/tgstation/pull/70306) and the bug is making all timid kudzu on lower Z levels have the weird visual effect as well as making them all layered incorrectly, as timid kudzu should be on a layer below players and items and such.

**Comment by Mooshimi** [comment]
> Experienced this bug too, the kudzu that is acting fucky has the trait timid (#70306) and the bug is making all timid kudzu on lower Z levels have the weird visual effect as well as making them all layered incorrectly, as timid kudzu should be on a layer below players and items and such.

good info tyty

**Comment by Salex08** [comment]
you can close this has been fixed in https://github.com/tgstation/tgstation/pull/72050
