### ISSUE TITLE
Omni pressure tanks runtime at shuttle rotation

### ISSUE THREAD

**Issue by mc-oofert** [tgstation/tgstation#71092]
```
[2022-11-05 09:28:41.475] runtime error: list index out of bounds
 - proc name: shuttleRotate (/obj/machinery/atmospherics/shuttleRotate)
 -   source file: shuttle_rotate.dm,94
 -   usr: null
 -   src: the omni pressure tank (Air) (/obj/machinery/atmospherics/components/tank/air)
 -   src.loc: the plating (167,169,8) (/turf/open/floor/plating)
 -   call stack:
 - the omni pressure tank (Air) (/obj/machinery/atmospherics/components/tank/air): shuttleRotate(270, null)
 - the omni pressure tank (Air) (/obj/machinery/atmospherics/components/tank/air): afterShuttleMove(hyperspace (105,28,12) (/turf/open/space/transit/west), /list (/list), 2, 8, 8, 270)
 - the omni pressure tank (Air) (/obj/machinery/atmospherics/components/tank/air): afterShuttleMove(hyperspace (105,28,12) (/turf/open/space/transit/west), /list (/list), 2, 8, 8, 270)
 - the omni pressure tank (Air) (/obj/machinery/atmospherics/components/tank/air): afterShuttleMove(hyperspace (105,28,12) (/turf/open/space/transit/west), /list (/list), 2, 8, 8, 270)
 - White Ship (/obj/docking_port/mobile): cleanup runway(the custom location (/obj/docking_port/stationary), /list (/list), /list (/list), /list (/list), /list (/list), 270, 8, Hyperspace (/area/shuttle/transit))
 - White Ship (/obj/docking_port/mobile): initiate docking(the custom location (/obj/docking_port/stationary), 8, 0)
 - White Ship (/obj/docking_port/mobile): check()
 - Shuttle (/datum/controller/subsystem/shuttle): fire(0)
 - Shuttle (/datum/controller/subsystem/shuttle): ignite(0)
```

## Reproduction:

1. Find a pilotable shuttle
2. If it doesnt have a pressure tank already, add one
3. Rotate your ship via custom location/docking/whatever
4. Runtime

**Comment by JohnFulpWillard** [comment]
this is still an issue
@LemonInTheDark any thoughts on this?

https://user-images.githubusercontent.com/53777086/221701002-cc4eb7dd-b9e7-4fa3-8c06-e23df2b7254e.mp4

**Comment by LemonInTheDark** [comment]
I am become depression. No I don't know why this happens, tho I really should just stare at it for a bit

**Comment by mc-oofert** [comment]
> I am become depression. No I don't know why this happens, tho I really should just stare at it for a bit

@LemonInTheDark 
if i remember correctly its because the tanks always connect in all direction
forgor what the var was but it was set to stuff like BINARY,UNARY

whatever custom stuff the airtank does, its shuttleRotate proc does not like it

**Comment by Profakos** [comment]
I can confirm that something odd happens when the omni air tank is supposed to be gets rotated.

![image](https://github.com/tgstation/tgstation/assets/2676196/543f1489-dd7b-4fdd-884f-84b151c9b276)
Real node connect grabs the current list of ports via ` `get_node_connects()`, and then attempt to rotate them. Now, here is our first oddity. Our pressure tank starts with one node pointing north, and the rest of them are null. However, its a Quaternary machine, so when it gets rotated, it claims all of its ports are pointing eastwards, therefore, it suddenly gets four eastward pointing nodes.

![image](https://github.com/tgstation/tgstation/assets/2676196/9fe2f180-ca56-48c8-90b1-1280bde1c932)

The `supposed_node_connects` is likewise called in via `get_node_connects()`. `set_init_directions` is called beforehand, but this is not implemented for the pressure tanks. This causes the port to not rotate at all, and we return the list of one node pointing north, and three empty ones. 

```
	for(var/i in 1 to device_type)
		var/new_pos = supposed_node_connect.Find(real_node_connect[i])
		nodes[new_pos] = nodes_copy[i]
```
The code then attempt to find east in the unrotated node port list, however, as it can not find it, it return 0. Thus, it runtimes in the next line, as BYOND is not zero indexed. 

Unsure what the proper implementation here would be, tanks have a lot of bespoke behaviour, due to their ability to merge.
