### ISSUE TITLE
infinite flight

### ISSUE THREAD

**Issue by Fikou** [tgstation/tgstation#71119]
## Reproduction:

1. use flight potion
2. gain wings
3. open your wings and fly
4. change race
5. you now have flight without wings

**Comment by moocowswag** [comment]
Jesus lizard

**Comment by Serxule** [comment]
to make it clearer (since i found this exploit a bit ago and its not well explained here)

1. get flight potion for wings
2. activate wings
3. change race via magic mirror
4. lose wings and ability button but have permanent flight
5. flight is unaffected by gravity/atmosphere and works anywhere, even in space

**Comment by Shadowflame909** [comment]
speedrunners are gonna love this new meta
