### ISSUE TITLE
Strange behaviour from manhandling SEs

### ISSUE THREAD

**Issue by AnonymousNow** [tgstation/tgstation#7113]
In the past twenty minutes, I've had two instances of saving an SE, injecting that SE into a subject, and having that SE not match the SE I saved in the slightest, or any SE I've had in that individual. The second time, I'd started saving SEs three times to avoid this bug from hitting again, only to find that all three were completely and utterly useless variations on each other. In each instance I'd isolated three of the four powers, knowing where the last one was, and was just about to get the fourth when this bug hit.

What the hell is going on?

**Comment by phil235** [comment]
@Razharas

**Comment by Razharas** [comment]
Well injectors have powers instead SEs now, so if you inject someone with injector they get random SE that just matches the powers in the injector
Theres however bug with SEs resetting completely for no reason while in dna machine, what causes this im struggling to imagine since i didnt really touch machine much

**Comment by naelstrof** [comment]
I've had the same problem with SE's just resetting completely or acting very strangely. It seems to happen more often when I have lots of powers and disabilities enabled.

**Comment by phil235** [comment]
is this still happening?

**Comment by jughu** [comment]
@korphaeron can be closed?
