### ISSUE TITLE
Rat king mutated mice attack non-mutated mice that you summon

### ISSUE THREAD

**Issue by ZAMODA** [tgstation/tgstation#71296]
## Reproduction:
Call upon a mouse
Mutate it
Call upon a second mouse
Mutated mouse kills normal mouse
Realize the whole point of your existence has been invalidated so you just go break some stuff

**Comment by Jacquerel** [comment]
Rats are provided with their creator in their faction list when mustated from mice.
Rats perform an _exact_ faction check to facilitate fighting the rats of other regal rats.
Mice which naturally exist on the station do not have the regal rat in their faction list because why would they.

Consequently rats will hunt and kill any mice they see 😔

**Comment by Ryusenshu** [comment]
Mutated mice arent even called rats anymore, it became a (now hostile) mouse with a different description

On another note, NPC Rat Kings are super hostile now which they werent before

**Comment by Mooshimi** [comment]
Just directly summon the hellspawns not normal mice

**Comment by ZAMODA** [comment]
this was solved, not sure why no one closed this
