### ISSUE TITLE
Strange Geysers not working

### ISSUE THREAD

**Issue by Siefer21** [tgstation/tgstation#72037]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
discover any strange geyser on lavaland with a mining scanner, they all make Oil now, which is unintended as far as I know. After the change where Geysers didn't need to be plungered, a few days past that, all the strange geysers stopped being random and only make Oil instead of a random chemical. Thought it would be fun to run the 'Holy shit theres oil here' for awhile but honestly, its not nearly as fun as finding a geyser that produces condensed capsaicin or hot ramen on an ice planet. Plus the lavaland ruin with the graves already had oil geysers, so theres that.

**Comment by Time-Green** [comment]
Strange, has probably been broken for a while then

**Comment by Profakos** [comment]
Review the code and it looks like that the random chemical is selected only after the geyser is full of oil, due to the parent being called first during initialization. It looks like once the oil reserves go below the maximum, it will swap to producing the new reagent.

However testing shows, the geysers of all types will not actually recharge their contents. I got all the oil out with hand, and it never started to produce again. Same when i empty them using liquid pumps.

**Comment by Time-Green** [comment]
> 

Ah signals failing for ??? reason is always a good time
