### ISSUE TITLE
Ghosts can mess with the new RCD menu.

### ISSUE THREAD

**Issue by Baskett55** [tgstation/tgstation#72036]
Reporting client version: 514.1589

## Round ID:
[196391](https://scrubby.melonmesa.com/round/196391)

## Testmerges: 
- [Partially reverts moving up/down whilst in a movable from #70431](https://www.github.com/tgstation/tgstation/pull/71527)
- [Saves on average 10 seconds from roundstart times](https://www.github.com/tgstation/tgstation/pull/71730)

## Reproduction:
Get rcd, have a ghost open up the RCD and mess with it while someone tries to build something

**Comment by Baskett55** [comment]
probably caused by #71710

**Comment by Mothblocks** [comment]
https://github.com/tgstation/tgstation/blob/18fab91ee9fee7f87c4e5abf7af52230b1494dde/code/game/objects/structures/construction_console/construction_actions.dm#L67-L72

https://github.com/tgstation/tgstation/blob/dacc575ad22b7b52a8b4a72b716a9c8e8bdcd924/code/game/objects/items/RCD.dm#L570-L575

Whatever this was doing was wrong from the start. This should be using `ui_host()` instead of whatever this is.

**Comment by Mothblocks** [comment]
@SyncIt21

**Comment by SyncIt21** [comment]
The window does not open when you use the RCD in the construction console without this line, i was just experimenting with it. I'll see if ui host works

**Comment by SyncIt21** [comment]
Ok so Bad news `ui_host()` did not work . ui_state() calls the super method when an human player is using the RCD so it can optimize and decide not to update anything if the user did not change  any option. However this optimization will prevent the window from opening when using the RCD in the construction console hence we return always active in this specific case so its best we dont change this.

Good news usr.canUseTopic()  inside ui_act did work. I also noticed the same bug inside plumbing constructor and fixed that as well. I'll create the PR now

**Comment by SyncIt21** [comment]
Named the title wrong. I meant to type can't mess not can
