### ISSUE TITLE
Gorrilla bugs

### ISSUE THREAD

**Issue by gamefreak2998** [tgstation/tgstation#72066]
Gorillas are now unable to use station consoles, the specific message given seems to be related to literacy (the given message seems to be this "You try to read [viewed_atom], but can't comprehend any of it.") rather than an issue with hand size or something of that kind. Next one could have been intentional but I couldn't find a PR for it so i'll include it here, Gorillas can't delimb anymore it seems when attacking crit/dead players.

**Comment by timothymtorres** [comment]
Gorillas and monkeys are NOT literate by default.   When I added literacy to the code, I only intended for intelligent mobs to be able to read or write.  Monkeys can overcome this by gaining the clever mutation in genetics, but a gorilla is unable to do so since it is considered a simple mob.

The other part of your bug report with delimbing sounds strange.  Can you confirm if you are able to delimb living people?

**Comment by gamefreak2998** [comment]
Well atleast the Gorilla illiteracy is intentional, odd but intentional. On that note, are they supposed to be able to use machines just fine?
I haven't extensively tested it but when  I crit or attack a corpse as a gorilla I have never been able to delimb.

**Comment by gamefreak2998** [comment]
More extensively tested it. Gorillas outright cannot delimb now.
