### ISSUE TITLE
Mute + sign language people cannot cast spells even though they can talk

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#72165]
## Reproduction:

- Be mute
- Have sign language
- Be able to talk (via sign langauge)
- Be unable to cast spells which require talking

This appears to be an oversight as the old behavior allowed this

**Comment by Floofies** [comment]
I am looking into this. It was most likely one of the follow-up PRs which changed how speech works

**Comment by Floofies** [comment]
Looks like this was always the case since `/datum/action/cooldown/spell/proc/try_invoke()` has this conditional in it which checks `living_owner.can_speak()`. Sign language never un-muted players in the past and this makes perfect sense in the context of needing speech

That proc includes this conditional:
```
if(HAS_TRAIT(src, TRAIT_MUTE))
		return FALSE
```

**Comment by Floofies** [comment]
That sounds like a good idea! I like your solution because it solves one problem and avoids causing another problem. In this way we can change voice-based spells to fallback on emoting if voice is unavailable, then if emoting is unavailable (cuffed or delimbed) the Player's choice of picking the Mute quirk won't be bypassed. Your solution my preferred one because it means Mute will still be impactful when appropriate.

I will make a proof-of-concept solution :smiley:
