### ISSUE TITLE
Nukies cannot war inside their own base even with req pop

### ISSUE THREAD

**Issue by arnociiroc** [tgstation/tgstation#72214]
## Testmerges: 
[#71986: 'Refactors armor into dedicated subtypes' by ZephyrTFA at commit 6832f0adaa](https://www.github.com/tgstation/tgstation/pull/71986)
[#72042: 'holopara qol update' by Fikou at commit 601e4a04dd](https://www.github.com/tgstation/tgstation/pull/72042)

## Reproduction: Spawn in as nukies, try to war inside spawn room and lower areas, fail! controller says "you must be in your base to do this"
Nukie base is also missing many windows, not sure if they just failed to spawn or got deleted.

**Comment by ZephyrTFA** [comment]
Cannot reproduce windows not spawning in

**Comment by Robustitron** [comment]
Had the same problem with "you must be in your base to do this" and maybe a more specific way to reproduce it.

We were lingering in the base waiting for the population to go up from 49, I step on and off the infiltrator shuttle, at which point "you must be in your base to do this" is the only response I get from the war beacon, no matter how deep into the nukie base I go, as the population starts going over 50.

My theory is that stepping onto the Nukie shuttle at all triggers this because you technically are not in the base, and it persists even if you step off and go back into the base.

**Comment by ZephyrTFA** [comment]
this is already been diagnosed and a pr fixing it is up
