### ISSUE TITLE
Drones can't edit doors after a specific wire is cut

### ISSUE THREAD

**Issue by AdipemDragon** [tgstation/tgstation#72249]
## Round ID:
[196982](https://scrubby.melonmesa.com/round/196982) but it happened in an older round too

## Testmerges:
unknown, also they don't touch drones

## Reproduction:
![image](https://user-images.githubusercontent.com/76874615/209480067-d5187d7b-3aed-40fb-9038-8af3607d5ad9.png)

Be a drone (yay), 
try to undo a door to re-program the circuit. 
Marvel as how, once you cut a specific wire, you stop being able to see into the door even if you're Right There. 
(Might be the AI interaction wire)
Wait and hope someone with proper hands finishes the job as you go do something else

**Comment by Sealed101** [comment]
the wire is High Voltage Ground.
electrifying the airlock in general will make the drone unable to access it since they aren't silicons but they will fail the `ishuman()` check during `interactable()`

https://github.com/tgstation/tgstation/blob/ba209adb358144454ea3ffeaa59e88d76cfad4b8/code/datums/wires/airlock.dm#L74-L85
