### ISSUE TITLE
Basic syndicate mobs apparently never lose aggro

### ISSUE THREAD

**Issue by Mothblocks** [tgstation/tgstation#72250]
## Round ID: [197004](https://scrubby.melonmesa.com/round/197004)

On this Manuel round I was told that the syndicate basic mobs on the gateway never lost aggro by Yulice. Logging on I could see that it kept shooting and there were literally 13k bullets on the floor and going to them would crash your client right away

https://github.com/tgstation/tgstation/pull/71871 CC @mc-oofert @tralezab

**Comment by mc-oofert** [comment]
`[2022-12-26 00:27:18.073] ATTACK: *no key*/(Syndicate Commando) shot *no key*/(CH3RUB) with .45 bullet (NEWHP: 500)  (Research Maintenance (138,138,12))`

The relevant SMG syndicate shot at a /mob/living/silicon/pai (CH3RUB, who was disconnected), 5000 times.
pAI cards contain a living pAI mob, which, according to a basicmob is apparently the same as a person hiding in a locker
Apparently since basicmobs can attack the object the person is hiding inside in, (this being the pAI card), the syndie was attempting to destroy the hiding spot (pAI card) to access the target (pAI), which is impossible because the pAI card is an indestructible item.
Replication steps:
1. become pAI
2. Go holoform
3. Aggro syndicate
4. Get out of holoform
5. Syndie still attacks
