### ISSUE TITLE
RCDs can remove indestructible windows

### ISSUE THREAD

**Issue by Zonespace27** [tgstation/tgstation#72271]
## Reproduction:
1. Place down an `/obj/structure/window/reinforced/fulltile/indestructible`
2. RCD it away
3. It's gone

**Comment by san7890** [comment]
That path doesn't exist?

![image](https://user-images.githubusercontent.com/34697715/209612430-626ad23b-5e1c-4f86-a58d-f76cc3c2ebea.png)

I tried it on `/turf/closed/indestructible/fakeglass` and wasn't able to reproduce either.

**Comment by Zonespace27** [comment]
> That path doesn't exist?
> 
> ![image](https://user-images.githubusercontent.com/34697715/209612430-626ad23b-5e1c-4f86-a58d-f76cc3c2ebea.png)
> 
> I tried it on `/turf/closed/indestructible/fakeglass` and wasn't able to reproduce either.

missed `fulltile`, fixed, apologies

**Comment by SyncIt21** [comment]
So this window type has all the flags making it indestructible
https://github.com/tgstation/tgstation/blob/c19120aaa80def953695a4a8abfb7ae840a2af6b/code/modules/awaymissions/mission_code/murderdome.dm#L2-L5

But since it inherits its stuff from obj/structure/window it returns the usual rcd values for deconstruction without taking into account the flags
https://github.com/tgstation/tgstation/blob/c19120aaa80def953695a4a8abfb7ae840a2af6b/code/game/objects/structures/window.dm#L87-L91

Solution would be to override this proc inside `/obj/structure/window/reinforced/fulltile/indestructible ` to always return FALSE or check for flags inside proc `obj/structure/window/rcd_vals()`
