### ISSUE TITLE
Drone dispenser material amount selection does not work

### ISSUE THREAD

**Issue by robotduinom** [tgstation/tgstation#72288]
## Round ID:

#197113

## Reproduction:

Take a stack of glass or iron in your hand.
Click to the drone dispenser machine.
Enter the amount you would like to load.
No matter what you entered, it always takes the whole stack.

**Comment by SyncIt21** [comment]
For some reason material container completly ignores `stack_amt` i.e the amount you insert
https://github.com/tgstation/tgstation/blob/c19120aaa80def953695a4a8abfb7ae840a2af6b/code/datums/components/material_container.dm#L175-L187

And something else after inserting `/datum/component/material_container/proc/user_insert()` deletes the stack from your hand rather regardless of the amount you inserted rather than subtracting from the stack & updating appearance

https://github.com/tgstation/tgstation/blob/c19120aaa80def953695a4a8abfb7ae840a2af6b/code/datums/components/material_container.dm#L165-L168

Since the material container is shared by a lot of devices i'm not sure what else is effected by this
