### ISSUE TITLE
Everyone has access to engineering lobby and lathe.

### ISSUE THREAD

**Issue by Pickle-Coding** [tgstation/tgstation#72450]
## Reproduction:
Touch engineering lobby airlock as an assistant, it opens. The airlocks require either construction or engineering access, but apparantly people with neither can still open them.

**Comment by Maurukas** [comment]
I am able to reproduce locally. The doors in question have two access helpers stacked on them, which results in req_one_access being populated instead of req_access. When req_access is null, req_one_access isn't being checked and the door is being treated as open access. This seems to be a problem with access checking itself, not the mapping or the handlers.

**Comment by tgsAvylaar** [comment]
Ashlyn's bane. It were the coders all along...
