### ISSUE TITLE
Early Launching Pods Is Completely Bust

### ISSUE THREAD

**Issue by san7890** [tgstation/tgstation#72966]
## Round ID: It's on master right now

If you really care, this is the commit I used on my local: https://github.com/tgstation/tgstation/commit/ce2b5cbb03c1f9214b4e9dd2489fc7390371d0f0

## Reproduction:

First, get an emag (or update the emergency level to red/delta, but that requires proc calling).
Next, use the emag on the escape pod's shuttle computer.
Then, click on the screen to open up the escape pod.

![image](https://user-images.githubusercontent.com/34697715/214721663-13b63b7b-a5ca-4dac-bec6-8a18afa52fe0.png)

Old behavior used to be such that you could immediately jettison yourself off into lavaland once you "allow yourself" to early-launch by emagging, but this has completely broken recently. Not really sure what happened, but there is just no way to send the shuttle even after emagging.

**Comment by CMDR-Gungnir** [comment]
Worth noting, you used to be able to launch when the alert was in Delta, without an e-mag. But you can't do that anymore, either.

**Comment by JohnFulpWillard** [comment]
Location and destination seems to say this has to do with not having any locations, not that emag just doesn't do anything.

**Comment by san7890** [comment]
> Location and destination seems to say this has to do with not having any locations, not that emag just doesn't do anything.

Emag is how you reproduce it, the whole functionality is just busted and doesn't work the way it's meant to

**Comment by msgerbs** [comment]
Oh shuttlecode, why must you be so cursed?

**Comment by Profakos** [comment]
Extentensive debugging showed me that the randomized docking port's dockingwidth was 0, and the pod's was 1, and thus it returned with Docking Width Too Large, which was swallowed up by the Silent setting. I have checked the destination ports, one of them was in a plating area between the mining bases, and the other was on a necropolis wall.

Another bug found: pod 2, 3 and 4 sign up for pod_lavaland, in addition to their own linked lavaland pod. Pod 1 only signs up for the base pod_lavaland.

**Comment by Profakos** [comment]
Setting the values to be the same as the one on stationary pods works, and the other bug is filtered out by the console, but I don't know how to fix this without making an ugly set of defines for escape shuttle widths.

**Comment by msgerbs** [comment]
I'm not really familiar with the code flow for the escape pod functionality, do these random ports get placed when the pod is launched or at round start? If they're placed when the pod is launched, could we simply create ports that match the size of the pod after the port size was automatically calculated?

**Comment by Profakos** [comment]
The random ports are placed on the map before the pods are loaded, and they might not actually touch the shuttle either (can't call linkup). Honestly, just telling the ports to allow docking despite dimensions, akin to transit docking ports, works.

I have spent a few hours on the other bug: its caused by the fact that `/obj/machinery/computer/shuttle/pod/connect_to_shuttle` is called multiple times. More specifically, called the time the template loads in, when all escape pods are called "pod", and once when shuttles with the same id all receive a suffix, barring the first one. Thus, the first loaded shuttle can go to one specific pod, while every other shuttle can go to the first one and the one keyed to their ID.

I also noted that all 4 random shuttle crash site docks are name pod_lavaland on tramstation, so I wonder what other bugs will that cause.

You can't even spawn the random docking ports on launch, as the shuttle computer needs them to exist to be able to select them. Maybe they could spawn when the shuttle computers are unlocked, and all the IDs are fixed.

**Comment by msgerbs** [comment]
I think if I was looking at this I'd rework the escape shuttle console to call a "random launch" function that takes care of both placing the ports and linking them up, and remove the list of available ports from this console variant. This existing solution is kind of spaghetti. But it sounds like what you found is good enough.

**Comment by Profakos** [comment]
Oh i have dreamed up the solution in my sleep. If `initial(port.shuttle_id)+"_lavaland"` is in the list, delete it and add the new one. This should solve it.

**Comment by san7890** [comment]
![image](https://user-images.githubusercontent.com/34697715/219102207-0cdc1dc4-0792-43cb-a344-1d989b9f4917.jpeg)
