### ISSUE TITLE
Plant restyle (secateur) is not functional

### ISSUE THREAD

**Issue by Unit2E** [tgstation/tgstation#73089]
Secateur restyles are not functional currently as a result of #72734

## Reproduction:

Target head as pod person, RMB with secateur, get returned a "There are no restylable features there!"

This is likely a known issue as hairstyles are not implemented under the new system as introduced in that PR, but here it is for posterity.

**Comment by Profakos** [comment]
Debugged this and found multiple problems:

- It looks like pod people heads only contain the pod people hair in their contents, as the external_organ list is depracated. The restyling proc loops through the external organ list, and as it is empty, it returns with the "no restyleable features" message.
- The pod person itself only signs up for the restyling signal when the head is surgically added. If you cut off the head of a pod person, and place it back on, the signal will be caught, and we will also get the "There are no restylable features there!" message, due to the reasons in the first point.
