### ISSUE TITLE
Quadriple Amputee can be still amputated by explosion.

### ISSUE THREAD

**Issue by Helg2** [tgstation/tgstation#73103]
Reporting client version: 514.1589

## Round ID:
[199265](https://scrubby.melonmesa.com/round/199265)

## Reproduction:
Get exploded, i personally got exploded by explosive holoparasite, and got my arm lying on the ground, also gloves didnt drop off, so this is quite broken. Also was playing as plasmaman, if it really matters.

**Comment by Jacquerel** [comment]
What's the bug here? 
If you explode then sometimes your arms fall off. Is the bug just that it didn't unequip your gloves?

Someone attempted to make the quirk protective of your limbs in #72535 but it was closed as being too precious about the gimmick goes against the sandbox nature of the game (similar reason to why luxury shuttle was disabled).

**Comment by Helg2** [comment]
> What's the bug here? If you explode then sometimes your arms fall off. Is the bug just that it didn't unequip your gloves?
> 
> Someone attempted to make the quirk protective of your limbs in #72535 but it was closed as being too precious about the gimmick goes against the sandbox nature of the game (similar reason to why luxury shuttle was disabled).

Oh, it was closed. k then, my bad.

**Comment by Helg2** [comment]
I just though that it was merged because my gloves didnt dropped after my arm got dismembered.
