### ISSUE TITLE
Posters, trapped with a shard dont hurt people

### ISSUE THREAD

**Issue by SuperSlayer0** [tgstation/tgstation#73105]
## Round ID:

Round ID: [199274](https://scrubby.melonmesa.com/round/199274)

## Reproduction:

Round breaking bug

1. Make a wanted poster
2. Trap is with a shard so random greytiders wouldn't tear it off the wall
3. Someone tears the poster of the wall
4. Shard doesn't make them hurt, cry

![image](https://user-images.githubusercontent.com/91609255/215832201-2feb9165-8744-42ef-bece-f48c3c4fb340.png)

I tested it myself, the shard trap didnt work even without gloves

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/f7d36718ff7392c8c421eabf71619b70252fbe0b/code/game/objects/effects/poster.dm#L197-L224

**Comment by Jacquerel** [comment]
I think this isn't a bug and just is a consequence of me being too conservative.  
Testing locally you can indeed still embed shards of glass with your hand and it does about 26 damage... but it doesn't _always_ happen even in the unlikely event that you're not wearing gloves.
This is because even when passed the "force = TRUE" argument the "tryEmbed" proc does not force it to _succeed_ and glass only has a base 50% chance to stick into someone, so 50% of the time it won't do that.

I am personally happy to be of the opinion that it should work 100% of the time if you bothered to go to the effort, but unfortunately I cannot remedy this during this month because I would need to tag it as a balance PR and not a fix.
It'd probably be easy to do this by just creating the embedded component yourself rather than going through the proc.

**Comment by JohnFulpWillard** [comment]
i guess wait for feature freeze to end
