### ISSUE TITLE
RPD-placed Pipes are always 4-way visually even if they only have 1/2 connections and do weird stuff when unwrenched/re-wrenched

### ISSUE THREAD

**Issue by Inari-Whitebear** [tgstation/tgstation#73195]
## Round ID: 199441

Place a pipe with RPD:
![dreamseeker_mC3QovPUsE](https://user-images.githubusercontent.com/1077971/216689776-4a9cc0bb-1873-4ed4-9751-5b2b9f9d1f90.png)

![dreamseeker_HTffhoWyMn](https://user-images.githubusercontent.com/1077971/216689785-8ad92f27-9710-4835-8b41-b342e6ee026e.png)

it also seems weird when you unwrench/rewrench that pipe then
But otherwise seems to work normally

## Testmerges:

Not sure, scrubby doesn't list any though

## Reproduction:

* Take RPD
* Place pipe

**Comment by Pickle-Coding** [comment]
Seems like an intentional but quite questionable change. #72957

**Comment by SyncIt21** [comment]
Yeah this was intentional.  So to avoid the pipes from dissappearing after you connect them to a machine/other pipes I decided to render the pipe sprites in all its specified directions so cross pipes are rendered cross shaped always,  T pipes are rendered T shaped always and so on.
For specific map loaded pipes which are by default cross pipes to hide the extra free edges so they dont look ugly all over the place I created a specific edge just to handle that but after you unwrench them they regain their cross shape again 
Just make sure you specify the correct directions for the pipes so they fit in perfectly and everything should be fine

**Comment by lessthnthree** [comment]
> Yeah this was intentional.
> 
> Just make sure you specify the correct directions for the pipes in the RPD so they fit in perfectly and everything should be fine

Then what's the point of smart pipes? This looks weird and everyone **is** going to think it's a bug.

**Comment by SyncIt21** [comment]
I don't have a better solution to address the pipes disappearing when they are connected on only one end.
The pipes are more visible and appear as they always should have but if you have a  better idea then do share

**Comment by LSommers** [comment]
Dynamically generated "caps" on the unused directions or something? It's goofy-ahh to have an "easy pipe" that's meant to dynamically connect or something but it just looks like this. Imagine if easy wires displayed every possible connection at once.

**Comment by Inari-Whitebear** [comment]
> I don't have a better solution to address the pipes disappearing when they are connected on only one end. The pipes are more visible and appear as they always should have but if you have a better idea then do share

I mostly find it weird looking, scared you make bad connection you don't see (because e.g. it might connect to another pipe below the floor), and if you do a 5-layer using setup it is a messy visually.

I haven't read the code, but shouldn't be impossible to have pipes connect correctly from a purely technical standpoint

**Comment by Strathcona** [comment]
Why not have the 4-way be the visual only when connected on 1 side? Is there a problem with choosing the sprite based on adjacent connections?

**Comment by iprice** [comment]
Just as gameplay examples players were confused / tripped up by.

1)
![image](https://user-images.githubusercontent.com/3789327/216802844-0e2802ea-909f-4052-abea-931f2e51f2f2.png)
"OMG is my engine going to be okay?" type ticket

2) This is after the delam sadly, but the delam is caused by the pipe run on the right - metastation filters area, the orange pipe coming back in from the cooling loop fed into the red pipe going up to a filter.  Or it didn't, because orange pipes dont connect to red pipes.  but now imagine both those pipes are a full size + shape... it LOOKS connected but it isn't.  As you can tell from the screen shot, they did not discover the cause and the engine was not saved (confirmed the disconnect by gas scanning both sides of the orange/red join)

![image](https://user-images.githubusercontent.com/3789327/216802895-c8020d44-4398-4e5a-a82e-2fa36f2de56d.png)



Both of these situations end up quite "unintuitive" compared to what is being visually told to the players, also just looks generally ugly I think, but ultimately will lead to confused / paniced ahelps and/or engine delaminations more than it really helps.
