### ISSUE TITLE
telekinetic carp

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#73237]
Reporting client version: 514.1589

## Round ID:
[199528](https://scrubby.melonmesa.com/round/199528)

## Reproduction:
I was working on getting the QM in a cell when I suddenly started dying. Chat was telling me a carp was biting me, but there were no carp next to me. It was determined that the carp in brig control was somehow biting me from where it was. Through a window, windoor, or wall, and across multiple tiles. Carp came from typical carp spawn event, to my knowledge.

**Comment by IndieanaJones** [comment]
I had a similar issue where I was killed by either a telekinetic carp or an invisible carp. I didn't see any carp in my vision radius, though. This one was notably a shark.

**Comment by necromanceranne** [comment]
@Jacquerel Might wanna look into this one. Hopefully this is isolated to carp because it definitely sounds like an AI issue.

**Comment by Jacquerel** [comment]
Yeah it's on my list, Carp don't have their own melee attack implementation so theoretically this is actually present in any basic mob with a melee attack 😓

**Comment by Jacquerel** [comment]
My leading suspicion is:
- Attack behaviour sets movement target to the player
- *something else changes the target*
- AI moves into position, registers that it is now at range for its *movement target* and starts biting 
- Attack action performs no further checks because it assumes the movement and attack target are the same thing 

But as for what or why is doing that, idk lol
Not even sure if that is the actual cause

**Comment by Trioct** [comment]
Ah, someone already made the issue. Same thing happened to me with many viscerators through a wall. Watching the clip I have makes me think that suspicion is probably correct.
