### ISSUE TITLE
RCD cant Fix breaches under objects and cant finish girders anymore

### ISSUE THREAD

**Issue by Ryusenshu** [tgstation/tgstation#73256]
## Round ID:
[199578](https://scrubby.melonmesa.com/round/199578)

## Testmerges:
#73206

## Reproduction:
Tested in Thunderdome

- The RCD was able to place plating under machines/frames, often used after bombings, which is no longer possible

- Same goes with girders, that cant be finished anymore with an RCD

Possibly caused by #72757

edit:
- Borgs cant put Walls/Windoors under themselves anymore

**Comment by necromanceranne** [comment]
You also can't place pumps on geysers using the plumbing device. Not sure if its related, but worth noting.

**Comment by SyncIt21** [comment]
> You also can't place pumps on geysers using the plumbing device. Not sure if its related, but worth noting.

You can actually. You click on the turf where the geyser is at & not on the actual geyser. This seems intentional from the code
https://github.com/tgstation/tgstation/blob/3c0013dfa5198db867426ea27df14534cf95949f/code/game/objects/items/RCD.dm#L1327-L1331
If you want to wrench the pump down on the turf you need plating under it & for that use the rcd to lay plating under the gyser so you can secure the pump to the plating. Don't know who decided it has to be this way, but it works so not a bug.


https://user-images.githubusercontent.com/110812394/217774272-263f1d32-20c0-4aa3-8e64-ce02b1906546.mp4
