### ISSUE TITLE
Fire overlays seemingly never go away, even if the person in question isn't actually on fire. (but only sometimes)

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#73283]
Reproduction:

Fire overlays can sometimes, without much explanation, never go away despite the source of that fire no longer affecting the 'on fire' mob. Setting yourself on fire again doesn't actually remove the overlay either...except sometimes it does.

Some sources are more consistently doing this than others. Lava, drake fire, and being on fire while immune to fire seems to result in this behaviour occurring more reliably. This is also potentially related to some of the image caching issues plaguing the game currently.

Probably related to this issue: https://github.com/tgstation/tgstation/issues/73235

**Comment by ShizCalev** [comment]
Correct, same issue.

**Comment by necromanceranne** [comment]
Just hop on a live server for a while, and just watch and wait for it to happen. It will happen at least a few times, its just a matter of observing it.

**Comment by Profakos** [comment]
I have had the opportunity to debug this live in a round, and the person in question replicated it by walking into lava and then extinguished themselves. They had no fire stacks, on_fire was false, the fire status handler had deleted itself. So my best guess is that there is a race condition due to signals somewhere. Could be that the signal that removes the permanent fire trait when you exit lava gets interrupted by extinguishing at a specific point, or the other way around. 

Of course others said it happens not just with lava so, vexing...

**Comment by Profakos** [comment]
I have checked and found out that there are no signals involved here, the extinguish and ignition signals only relate to changeling fleshmend.

**Comment by Profakos** [comment]
This has happened now with the radioactivity mutation's overlay. Someone got mutadone'd, the mutation went away, but the overlay stayed.
