### ISSUE TITLE
Black sprites and missing background after reconnecting

### ISSUE THREAD

**Issue by maskenary** [tgstation/tgstation#73364]
## Reproduction:

After disconnecting and reconnecting to the game, the sprites turn black and the background goes transparent.
I've tried enabling/disabling multi z parallax and then changing zlevels, it fixes the sprites but then the HUD disappears.

![1](https://user-images.githubusercontent.com/125152643/218275852-39170e44-7238-442b-a68e-4841dba78037.png)
![2](https://user-images.githubusercontent.com/125152643/218275861-4c6bdecd-f340-44a7-af02-2e6b90b99a02.png)

F12 to fix the HUD instead makes the bug happen again

![3](https://user-images.githubusercontent.com/125152643/218275962-76d69fc6-90a0-4663-b549-3a77cc944b32.png)

**Comment by DragonTrance** [comment]
I was able to _slightly_ reproduce this. There seems to be trouble with the hud when reconnecting, because in the last one I recorded, the crafting UI element was just completely visible when the hud shouldn't had been visible.

I was only able to recreate problems with the hud if the HUD was invisible and I switched the HUD to visible while still in that sort of "connecting" state. I wasn't able to reproduce this on local, but I didn't do the same things as in this video.

This doesn't seem to necessarily be a problem, but #73387 had an issue where it wasn't able to be removed even after reconnecting.

(I had to compress this video because the file size was a bit too much and the audio turned out ass)

https://user-images.githubusercontent.com/26515331/218326067-57ef590d-0b81-435a-b730-d336c48ba318.mp4
