### ISSUE TITLE
Flashlights of the same type no longer stack.

### ISSUE THREAD

**Issue by j-nengel** [tgstation/tgstation#73535]
Round ID 200416.

Turning on a flashlight, then turning on a second flashlight, then turning off one of them (leaving the other on) causes lighting to appear as if you didn't have them turned on.  

Same issue, you can't benefit from two firefighter hats, for instance, and turning one off, disables the lighting for both.

**Comment by j-nengel** [comment]
Dropping a flashlight on the floor, THEN activating one in your pocket, THEN picking the lit flashlight up, seems to brighten the zone of light as expected. 

If you drop two flashlights that are lit, and pick them both up, it'll also be more bright. Then, if you flick one off, it'll be normal, and turning it back on won't increase the brightness, and turning it off again will turn both off. 

Because of that, the issue seems to be with turning on the source not updating something properly.

Not a huge issue as moving will cause it to re-adjust properly, but still odd.

**Comment by LemonInTheDark** [comment]
Alright so uh, this is annoying.
The problem goes like this.

The way we handle flashlights is by using underlays, which rely on this canonical representation of how things look.
If you add something to the underlays list, then modify it, the display won't change because you didn't add a thing, you added HOW IT LOOKED.
The same works in reverse. If you add something to underlays, change it, then try to remove it, you'll remove nothing, because the appearance you're trying to remove isn't the same as the thing you're removing "with". It's changed.

What's going on here is when a flashlight is turned on, we remove the "appearance" we keep of its light pre-emptively, to prevent accidental stacking somehow.

![image](https://user-images.githubusercontent.com/58055496/220042283-28312ee9-8bb9-4e2a-bad6-f9070dd5b47c.png)

The problem is if our flashlight appearance, and the appearance of say, another flashlight we are also holding (which is already on), are the same, then we accidentally remove the OLD LIGHT (because the two appearances are the same). Then we dutifully add the same light back (since we're turning on and all) and we end up in this stupid state.

I'm honestly a bit unsure of what to do here, need to think a bit.

For more about this appearance behavior, see https://github.com/tgstation/tgstation/blob/master/.github/guides/VISUALS.md#appearances-in-byond

**Comment by LemonInTheDark** [comment]
The easiest fix might just to be adding our second light before doing this bit (I was wrong btw, this bit is actually handling the direction of the light. It removes the old light so it can update the underlay rather then leaving the old one hanging.)
