### ISSUE TITLE
brimdust sac not fittin in chest with no other special organs

### ISSUE THREAD

**Issue by Dawnseer** [tgstation/tgstation#73667]
Reporting client version: 514.1589

## Round ID:
[200833](https://scrubby.melonmesa.com/round/200833)

## Reproduction:
Tried getting a doctor to jam a brimdust sac that was stabilized in me. They got told it didn't fit. I didn't have any other organs of special nature in me. It's a chest organ, allegedly.

**Comment by Jacquerel** [comment]
Afraid this one was not a bug, your doctor was attempting to use Cavity Implant surgery instead of Organ Manipulation. 
```
02:52:29 | ATTACK | Electrosheep/(Peach  Tangerine) operated on Dawnseer/(Minds-Their-Business) (OPERATION TYPE:  Cavity implant) (TARGET AREA: chest) (NEWHP: 99.6)

02:54:54 | SAY | Electrosheep/(Peach  Tangerine) "You being to insert the brimdust sac into  Minds-Their-Business's chest... you can't seem to fit the brimdust sac."
```

I can understand the confusion because it definitely sounds like that's what you would use to implant an organ, but Cavity Implant is for like putting grenades or objects inside people's chests rather than functioning organs.

**Comment by Dawnseer** [comment]
Ah so they were bungling it. Oh well, cheers.
