### ISSUE TITLE
butchering bread dog creates errors

### ISSUE THREAD

**Issue by michaelsmetsker2** [tgstation/tgstation#73765]
Reporting client version: 514.1589

## Round ID:
[201132](https://scrubby.melonmesa.com/round/201132)

## Reproduction:
butchering a bread dog creates error items named food
not sure if it happens to cat's as well
![Capture](https://user-images.githubusercontent.com/26945240/222769988-2e14f46c-457f-424f-9e52-297c423b0775.JPG)

**Comment by Sealed101** [comment]
it's supposed to be spawning bread slices, but it spawns the base item, which defaults to having the base food item's icon, desc and name. changing it to spawn breadslice/plain should fix the issue
bread's and breadslice's base classes are not obtainable in normal play and should be documented/distinct for mappers or otherwise

https://github.com/tgstation/tgstation/blob/aff9cf1b434c7a95d156ea20108d8b2bc015083d/code/modules/mob/living/basic/pets/dog.dm#L784-L801

https://github.com/tgstation/tgstation/blob/aff9cf1b434c7a95d156ea20108d8b2bc015083d/code/game/objects/items/food/bread.dm#L23-L28
