### ISSUE TITLE
Chameleon Projector borks objectives

### ISSUE THREAD

**Issue by Stickymayhem** [tgstation/tgstation#7383]
http://imgur.com/LWe53Iu

I was disguised as a backpack on the main shuttle and completed my escape alive objective, but the changelings objective had me not on the shuttle. It seems disguising makes you appear to be not on the shuttle to whatever handles the prevent escape objective.

**Comment by optimumtact** [comment]
A) did you have their identity
B) did you have their ID card?
C) are you sure
D) if you're a backpack you're not really fufilling A)

**Comment by Stickymayhem** [comment]
No I completed my objective. The issue is that the changeling ALSO completed their objective despite me being alive and well on the shuttle. I was the traitor not the changeling.

I didn't need any Id cards I just needed the medal of captaincy. It makes no sense that while I escaped alive the changeling achieved their objective of preventing me from escaping alive.

**Comment by optimumtact** [comment]
Oops, I should read bug reports

**Comment by PKPenguin321** [comment]
This also happens if a wizard statues you on a shuttle, you achieve your escape objective if you're a traitor but the game still registers you as marooned on the station
Happened in an edge case admin event to me the other day on basil

Considering chameleon projectors put you inside of the item you disguise as or something and being made a statue puts you in the statue those things are probably related

**Comment by Jordie0608** [comment]
I can't reproduce this.

**Comment by Jalleo** [comment]
@incoming5643 will the antag datum help with this?

**Comment by Incoming5643** [comment]
this is an issue because the escape objective won't track things that are on the shuttle but contained within objects/structures/other mobs.

Also it's still coming Jalleo I swear

**Comment by Jalleo** [comment]
I was meaning the bug as in still existing

**Comment by optimumtact** [comment]
old with no repro
