### ISSUE TITLE
Mecha directional damage multiplier is being used inconsistently

### ISSUE THREAD

**Issue by Sealed101** [tgstation/tgstation#74022]
it would seem that mecha's armor weaknesses from the rear/sides are not used throughout every way to attack a mecha, i.e. ranged and blob attacks use the directional armor, while most of other attacks don't.

way back in #16607 it was used throughout seemingly every attack instance, but some of those were seemingly lost during the multiple refactors in the following years

`take_damage()` proc even has the `attack_dir` var but it goes unused

https://github.com/tgstation/tgstation/blob/413f2413144e658b8b8f687d3834a265c84db05c/code/modules/vehicles/mecha/mecha_defense.dm#L39-L50

https://github.com/tgstation/tgstation/blob/413f2413144e658b8b8f687d3834a265c84db05c/code/modules/vehicles/mecha/mecha_defense.dm#L72-L107

https://github.com/tgstation/tgstation/blob/413f2413144e658b8b8f687d3834a265c84db05c/code/modules/vehicles/mecha/mecha_defense.dm#L116-L130

https://github.com/tgstation/tgstation/blob/413f2413144e658b8b8f687d3834a265c84db05c/code/modules/vehicles/mecha/mecha_defense.dm#L280-L301

**Comment by Sealed101** [comment]
_seemingly_

**Comment by githubuser4141** [comment]
I'm pretty sure handheld items i.e. e-swords, toolboxes, pencils don't use the directional armor which might (?) be intended? Because, honestly, that'd be unbalanced in several ways.

Simple mob attacks (bleb, xenos, spider, goliath, etc etc) and ranged attacks (laser, bullet) are normally telegraphed, so the pilot can predict where they'll land and position themselves accordingly. Simple mobs are (often) slower, weaker, less numerous or 'dumb' if they're not controlled by a player. So I presume, and hope that the decision to NOT have handheld items be affected by direction is 100% intentional. Because that'd be a HUGE nerf to mechs overall (and a moderate buff to mechs that hang out exclusively on 1x1 tunnels).
