### ISSUE TITLE
Abductors Glands decay in Organ Transport Box

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#74114]
## Reproduction:

Abductors Glands (hearts) can be placed in Organ Transport Box, become freezed, but still decays other time unlike any other organs in the box. Smart Fridge still works fine with Glands.

**Comment by Jacquerel** [comment]
This may actually just be something misleading about the organ box, it will "freeze" things placed into it even if it doesn't have any coolant and the object having the "frozen-" name does not actually mean its decay is paused.
Resultingly this might be fixed by #74070 where I have refactored it to display the visual feedback consistently.

**Comment by TheVekter** [comment]
I can't replicate this on live. If it's still happening, open a new issue.
