### ISSUE TITLE
Some sentient diseases can luck out and become uncurable

### ISSUE THREAD

**Issue by JohnFulpWillard** [tgstation/tgstation#74220]
Similar to https://github.com/tgstation/tgstation/issues/68209 but was closed for not being a bug

Sentient diseases can roll things like Happiness and Haloperidol. Problem is, Happiness is a Drug, and Haloperidol purges drugs (5 units per tick).
This means that the sentient disease can't get cured, because one cure chem will purge the second.

**Comment by Profakos** [comment]
Yeah, I didn't specify Happiness in #68209, but that is the one I meant there.
I have been told later that this combo and the Anacea+any medicine one can be sidestepped by using a gigantic amount of chemicals, but that is still rather unreasonable.

**Comment by iprice** [comment]
This isn't an insolvable issue, you mix the whole thing with water and drip feed 1u so that it entirely metabolises both chemicals entirely from the blood in one pulse.  Or you just saturate the person with the chems.  There's good and bad ways to solve this IC.

It's not "uncurable" and frankly getting something like anacea in your cure is the ONLY meta that gives the sentient disease any reasonable chance of winning, any other combo is very quickly solved by medical.

**Comment by Mooshimi** [comment]
I find this funny when it happens.

**Comment by necromanceranne** [comment]
been on the receiving end of that combo. Sufficed to say, it was pretty much an easy win for the sentient disease. It was, unironically, the only time I've seen a unanimous round restart vote work because it resulted in a stagnant round.

**Comment by newfren** [comment]
for the record, giving the patient a shittonne of whatever chem is being purged will still allow them to be cured, but it's extremely dumb how much more difficult it makes curing the disease
