### ISSUE TITLE
space dragon on-fire particles are dragon colored instead of fire colored

### ISSUE THREAD

**Issue by kawoppi** [tgstation/tgstation#74633]
## Round ID:
[203464](https://scrubby.melonmesa.com/round/203464)

## Reproduction:
Have a space dragon shoot fire and walk into it's own fire.
Their on-fire particles will have the same color as the dragon instead of the normal fire color.
![dragon fire bug](https://user-images.githubusercontent.com/94711066/230800889-6d95df08-3fa1-49aa-9765-9ec061bd37e9.PNG)
I'm not sure if even they're supposed to have on-fire particles in the first place.

**Comment by Mooshimi** [comment]
Things that normally dont appear to be on fire now have the sprite due to the update. Ex: drones. 
Related code(?):

https://github.com/tgstation/tgstation/blob/bf6f81a9b5697c3e4498b61836a26d0a1e988d78/code/modules/mob/living/simple_animal/hostile/space_dragon.dm#L214

https://github.com/tgstation/tgstation/blob/728a0f1b9147197bb81f22d946f67e9d08719d5a/code/modules/events/ghost_role/space_dragon.dm#L39

https://github.com/tgstation/tgstation/blob/b7da743e7dca0ed0b8f96b02e184d8aed230526a/code/modules/mob/living/basic/basic.dm#L220-L230

**Comment by IndieanaJones** [comment]
Space Dragon shouldn't be able to catch on fire in the first place.

**Comment by kawoppi** [comment]
I think the related code might be somewhere in here though, since it looked like the new fire particles and not the fire overlay
https://github.com/tgstation/tgstation/pull/74555/files
