### ISSUE TITLE
NorthStar only has a Tcomms server for the Common channel, yet every other radio network works fine anyways

### ISSUE THREAD

**Issue by plutori** [tgstation/tgstation#74749]
Reporting client version: 514.1589

## Round ID:
[203802](https://scrubby.melonmesa.com/round/203802)

## Testmerges:
- [Adds a Material Stack manipulation apparatus for Engineer Cyborgs, replaces the R-Glass tool](https://www.github.com/tgstation/tgstation/pull/74297)

**Comment by BlueMemesauce** [comment]
Not an issue, the tcomms server is currently useless. The only reason it's still on the other maps is because nobody bothered to remove them.

**Comment by plutori** [comment]
> Not an issue, the tcomms server is currently useless. The only reason it's still on the other maps is because nobody bothered to remove them.

But this is wrong? I hopped on a live server just to double check to make sure there was no change in the last like, 5 hours since the last shift I played, and servers indeed work as expected, individual servers control individual channels, and tcomms on every other map requires something to be set to control a frequency. You can delink security comms to disable only the security channel, for example.

**Comment by BlueMemesauce** [comment]
You can just do that through using filtered frequencies on other machines. But I guess there is a slight benefit to the servers because it allows people to block a specific channel without knowing how to use filtered frequencies.

**Comment by plutori** [comment]
> You can just do that through using filtered frequencies on other machines. But I guess there is a slight benefit to the servers because it allows people to block a specific channel without knowing how to use filtered frequencies.

I guarantee you 99.9% of people have no idea what this is.

**Comment by the-og-gear** [comment]
A server specifically for a channel shouldn't be required for a certain comm network to work - the server is for storing logs afaik. The fact that it's linked over to a network at all means it should be able to communicate on channels that network recognizes.

**Comment by BlueMemesauce** [comment]
> A server specifically for a channel shouldn't be required for a certain comm network to work - the server is for storing logs afaik. 

I forgot about the logs. I know scripts were disabled, but I dont know if logs still exist. In that case the servers actually have a use and this issue is correct

> The fact that it's linked over to a network at all means it should be able to communicate on channels that network recognizes.

Depends if the server has filtered frequencies set or not. I believe the common sever is filtered to every channel except encrypted ones. In that case encrypted channels wouldn't get the benefits of the server.

**Comment by BlueMemesauce** [comment]
The benefits of the server are very minimal, which is why all of the other channels still work. It's not a bug where the other channels run off magic, they just dont require the server to run. Which makes sense because servers are unprintable, so you need to be able to make a functional tcomms network without them.

**Comment by BlueMemesauce** [comment]
So I looked in the code and North Star uses the "birdstation" telecomms server variant, which accepts all frequencies.  It just inherits the name "Common Server" for some reason, despite actually being for every frequency. So the messages all go through a server, they just go through a single one. The tcomms on North Star is 100% functional.
The only benefit to having multiple servers is that its easier for people who don't know how to set filtered frequencies to sabotage a specific frequency. And North Star is meant to be a compact station, tcomms would have to be expanded to fit all 8 servers.

I actually used the monitoring console for the first time and logs do function from the servers. I've never seen anyone use that feature ever. But then I also found a bug with it because it allows you to read any radio message even if its in a language like codepeak #74810
