### ISSUE TITLE
items from holographic lockers are real

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#74765]
![blood packs](https://user-images.githubusercontent.com/42606352/232272573-40a5b0ae-2e89-4f81-a717-300bcdddf2a5.PNG)
![chapel-courtroom](https://user-images.githubusercontent.com/42606352/232272574-28692088-5321-4ff6-9b6b-74de7b663156.PNG)
![holoclothes0](https://user-images.githubusercontent.com/42606352/232272578-abec32d7-87e9-4738-bc8c-b6fedb66a0f5.PNG)
![holoclothes](https://user-images.githubusercontent.com/42606352/232272576-d4624532-8ca6-4a45-946b-f48f1794f2f1.PNG)

step 1: load up a holodeck simulation that contains a locker or crate
step 2: open up the crate.
step 3: the items that started in the crate are real and remain after the holodeck simulation is turned off.

This can be used to make real blood packs, clothing, briefcases, pens, and folders.

bonus round:
![holodog](https://user-images.githubusercontent.com/42606352/232272649-0f2ea490-e5fd-44cd-ae8e-8a8f629c81ed.PNG)
you can stick a holographic dog in a washing machine and run it, and the gibs produced will be real. personally, I think this is funny.

**Comment by SyncIt21** [comment]
Related to  #74612.  @ShizCalev assign to self?

**Comment by Mooshimi** [comment]
Things like the apple on the school desk are able to be eaten as real food and this is currently being used to spawn infinite apples to eat(it's so stupid I don't know why.)

**Comment by timothymtorres** [comment]
I do believe this is because the code for locker/crate spawn was changed to initialize the items once it gets opened so they don't properly register to the atoms that need to be destroyed.  They did this to optimize load times for rounds to start fast.

A simple fix would probably be to add a `/obj/effect/holodeck_effect/locker` subtype.  I had to do the same thing with playing cards for similar reasons since they don't initialize the cards inside until someone touches the deck.
