### ISSUE TITLE
Tritium in trace amount results in constant toxin damage

### ISSUE THREAD

**Issue by Hardly3D** [tgstation/tgstation#74760]
## Reproduction:

Should be fairly easy to reproduce; Leak tritium on a room, scrub it through portable scrubbers or through the air alarm.
Once the room has trace amount of tritium (at least 0.01 or even 0 moles will do), enter and you should start to receive constant toxin damage due to the trace amount of tritium, the only way to stop taking damage is by either turning on your internals or fully getting rid of tritium to the point it no longer shows up on the gas analyzer.

I guess it's reasonable that breathing tritium should be causing toxin damage but the fact that even 0 mole of tritium causes toxin damage seems to be kind of unintended?

**Comment by OverwatchVoice** [comment]
Same goes for plasma. The slightest amount is enough to cause plasma damage.

**Comment by SinfulBliss** [comment]
very bad bug, causes constant slow toxin damage to everybody in the round without a warning they’re receiving it from the air (so they don’t know to enable internals)

especially problematic on icebox since opening an airlock to the outside will often result in minuscule amounts of toxins getting into a room which triggers the bug

**Comment by RandomGamer123** [comment]
> very bad bug, causes constant slow toxin damage to everybody in the round without a warning they’re receiving it from the air (so they don’t know to enable internals)
> 
> especially problematic on icebox since opening an airlock to the outside will often result in minuscule amounts of toxins getting into a room which triggers the bug

A quick look at the code shows that there is no (and has not been afaik) an alert for tritium gas in the air, and the plasma alert should be thrown whenever you're breathing in an unsafe amount of plasma.

However the `moles_visible` value of tritium is set to `MOLES_GAS_VISIBLE`, ie. 0.25 moles (same with plasma), while the toxin damage is dealt beyond 0.05 moles of plasma or 0.0001 moles of tritium (below 0.0001 moles of tritium, `QUANTIZE` kicks in and deletes the gas). This means that in the case of tritium, there is quite a large range where you can't see the gas or be alerted to it, but still take toxin damage from breathing it in.

Another issue here is that while toxin damage is scaled based on concentration, the minimum damage is `MIN_TOXIC_GAS_DAMAGE` ie 1 damage per tick, even if there's just 0.0001 moles of tritium in the tile, you still get dealt 1 damage per tick.

Potential fixes would be to increase the threshold at which toxin damage begins to be dealt, reduce `MIN_TOXIC_GAS_DAMAGE`, and/or add feedback so that players know why they are taking toxin damage.

**Comment by OverwatchVoice** [comment]
Having very slow toxic damage could by used by traitors or similiar, but the most frustrating thing is that therre is not an actual solution to getting rid of the negligible amounts of gasses - It always rounds down from the neighboring tiles.
