### ISSUE TITLE
Library Chuunibyou granter book doesn't seem to grant the spell.

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/tgstation#74960]
Reporting client version: 514.1589

## Round ID:
[204384](https://scrubby.melonmesa.com/round/204384)

## Testmerges:
**N/A**

## Reproduction:
The library Chuunibyou book (Added with #74404) doesn't seem to be giving the spell.
![Screenshot 2023-04-24 211346](https://user-images.githubusercontent.com/85206687/234166295-d1c46a69-79fc-4a4f-bc37-b8d9c4280ef1.png)
Its the first time I've found this book and I'm not sure if I missed something which caused it to not give the spell.

1. Find mysterious Chuunibyou book.
2. Read.
3. Become Chuunibyou.
4. No spells were granted.

**Comment by Rex9001** [comment]
It doesnt grant any spells, just gives you funky text when you cast spells

**Comment by Jacquerel** [comment]
> It doesnt grant any spells, just gives you funky text when you cast spells

As written here, this isn't a bug. 
This book "augments" existing spells that you have, it doesn't grant a new one.
It also doesn't grant the spell which grants the chuuni aura, because that would be a bit of a pointless middle step.

If what you actually meant was "I used this and the effect wasn't happening" but explained it in a confusing way then we can reopen this.
