### ISSUE TITLE
Become an infinitely exploding grenade with this one weird trick!

### ISSUE THREAD

**Issue by trexter5555** [tgstation/tgstation#74984]
RoundID: 204441

Step 1: Wear the RD modsuit (i assume anything explosion-proof or resistant would work the same)
Step 2: Acquire a stabilized oil extract
Step 3: Die
Step 4: Watch as your corpse explodes infinitely and travels across the entire station and the entire expanse of space, exploding everything in its path.

**Comment by moocowswag** [comment]
just have the extract qdel itself when triggered

**Comment by OHJ4Y** [comment]
this a feature leave it in!!!

**Comment by Mey-Ha-Zah** [comment]
I vote to leave it in, but as a traitor final objective type deal.

**Comment by dragomagol** [comment]
It's too glorious not to show: https://www.youtube.com/watch?v=KqZ4uipUPdM

**Comment by DrDiasyl** [comment]
If those won't be made a Traitor final objective in future, I will eat a stabilized oil extract IRL

**Comment by Mey-Ha-Zah** [comment]
Did some testing of my own and found out WHY it only works with the RD Modsuit.
Because that Modsuit BACKPACK is specifically what doesn't explode. Every other bag, jumpsuit and modsuit get blown up. The only reason this works for that suit, is because the backpack section CANNOT be blown up. Simply the reason.
