### ISSUE TITLE
limb anomaly gives "d_golem" parts that make the victim weak and unable to equip items

### ISSUE THREAD

**Issue by wawabenford** [tgstation/tgstation#75157]
## Reproduction: Stand next to a limb swaping anomaly and inherit a "d_golem" part

Standing next to a limb swapping anomoly made me gain a "d_golem" left arm that made me "weak" and "able to pacify people with my hugs" this amounts to not being able to equip items such as clothes or an ID even after the limb is removed

**Comment by JohnFulpWillard** [comment]
d_golem is durathread golem limbs, which doesn't change anything.

The hugs and being unable to equip anything comes from the Gondola liver, which is usually given through genetic infuser, however the organ isn't blacklisted from the anomaly so you CAN roll it. I don't think this is a bug, it's the bioscrambler working as intended, you just rolled an organ you didn't like.

**Comment by BlueMemesauce** [comment]
But it's also confusing as fuck when you get a new liver that affects your arms and prevents you from equipping items. How does a liver do that? But I don't really know how this could be solved except for saying the effect is coming from the liver in the message, which wouldn't really make sense because how would you know that. Maybe we could make it easier to scan yourself to know what organs you have?

**Comment by wawabenford** [comment]
the liver part was wack I didnt know that

**Comment by tralezab** [comment]
> But it's also confusing as fuck when you get a new liver that affects your arms and prevents you from equipping items. How does a liver do that? But alerting the player the effect is coming from the liver wouldn't really make sense either because how would you know that. Maybe we could make it easier to scan yourself to know what organs you have?

ss13 is allowed to have mysteries. anomalies doing a confusing or rare effect is engaging
