### ISSUE TITLE
You can alt-click under an electrified grille and spam click the floor while dragging someone to near-instantly kill them

### ISSUE THREAD

**Issue by trexter5555** [tgstation/tgstation#75246]
RoundID 205282

see title, was told this was an exploit.

**Comment by Sealed101** [comment]
alternatively just make the grilles block the plating underneath from appearing in the alt menu like walls/doors/windows(?) do it

**Comment by distributivgesetz** [comment]
> alternatively just make the grilles block the plating underneath from appearing in the alt menu like walls/windows(?) do it

unfortunately that wouldn't fix the issue because I found at least two other ways to instantly toast a mob by diagonally moving the body past the grille and by shoving the person into the grille. Unless we change grilles to shock you no matter what when dragging/shoving bodies or if we added a cooldown to dragging stuff around, admins will have to moderate the exploit themselves
