### ISSUE TITLE
Mutes are not persistent, and reset at the end of the round (and don't carry over between servers)

### ISSUE THREAD

**Issue by ZephyrTFA** [tgstation/tgstation#75332]
`/datum/preferences/var/muted` is not read or saved at any point in it's lifecycle.

@Timberpoes and I were discussing this earlier and agreed it should be persistent.

This will need to be saved in the DB, and not in the preferences savefile.

**Comment by Mothblocks** [comment]
This isn't a bug. Whether or not it "should" be persistent is another question, but if it "should" be then it's a matter of adding more bans, not tacking it onto this.

The preferences datum is used because it's a persistent object even when the client logs in and logs out.

If you want it to be persistent, then you would want to create a new feature for these kinds of mutes (which already exists for all of it IIRC?), so that admins actually affix reasons, you can read them in game, you can appeal, etc.
