### ISSUE TITLE
Mech Engine seems nonfunction and panel is missing a line about a component alert

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/tgstation#75613]
Reporting client version: 514.1589

## Round ID:
[206774](https://scrubby.melonmesa.com/round/206774)

## Testmerges:
- [Spider Infestation Balance Rebalance Expansion Part 1](https://www.github.com/tgstation/tgstation/pull/75204)

## Reproduction:
![Screenshot 2023-05-23 184930](https://github.com/tgstation/tgstation/assets/85206687/ae16498b-3ba7-4a3e-97a6-a3fd6f602e6a)
(Image is from a previous round but is still relevant)
- The blank in the alerts area is supposed to have text regarding a internal capacitor fault. (Or something like that.)
- The engine doesn't properly display the inserted fuel (I added 25 sheets of plasma), but even then it doesn't seem to actually produce power for the mech.

**Comment by Sealed101** [comment]
the generator currently does not accept any `attackby` calls and thus no fuel can be inserted.
https://github.com/tgstation/tgstation/blob/8e49222b72f6fdcbe741d2a6ce0a8425d95010b7/code/modules/vehicles/mecha/equipment/tools/other_tools.dm#L326-L328

it's displaying NaN because it generates a ghost plasma stack as fuel when created so it knows what to accept, presumably. this shit stank
