### ISSUE TITLE
Elevator music is broken as hell

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#76043]
Reporting client version: 514.1589

## Round ID:
[208190](https://scrubby.melonmesa.com/round/208190)

## Reproduction:
- Be on northstar
- Standing in the brig, doing nothing
- Elevator music starts playing despite me not being anywhere near it
- Hit stop sounds, it comes back a minute later.
- Turn off elevator music in the settings. It STILL comes back
- FREE ME FROM THIS NIGHTMARE GOD

**Comment by Higgin** [comment]
Reproduced on 230865 on Northstar. Entering an elevator, sending it up or down a floor, and stepping off seems to cause music loops for some people. Stop sounds has the same issue as described here, but turning off elevator music in prefs stops it from recurring.

**Comment by Moltovz** [comment]
Hi, to clarify for Higgin because I finally got into my fucikn' github account.
![image](https://github.com/tgstation/tgstation/assets/61367602/e643fe9e-b423-4abb-95c9-8168963a1561)
Stepping *off* of the elevator while it is in transit will cause the elevator music to stick until you pass on and off of the elevator again, so the catwalks here on NorthStar for example.
Stop sounds and disabling elevator music will not make the music stop until you've made it stop by walking on and off of the elevator again.
