### ISSUE TITLE
Zero gravity lava walk

### ISSUE THREAD

**Issue by Fallen1220** [tgstation/tgstation#76380]

**Comment by Sealed101** [comment]
?

**Comment by SyncIt21** [comment]
!!

**Comment by Sealed101** [comment]
fill out the issue template and describe the issue in detail with reproduction steps, otherwise i'm closing this within 3 days

**Comment by Sealed101** [comment]
## You MUST fill out the report for clarity, because an issue manager/contributor may not be able to pull enough data out of the round's logs. Here's what I've found, however.

judging by the game logs, the station was experiencing a gravity generator blackout. the player used red/blue cubes linked to a room on lavaland mining station. somehow, the gravity did not update
getting similar vibes to #75480, as both the cubes and the fulton use `forceMove()`

code (__OW__)
https://github.com/tgstation/tgstation/blob/8b258383362c02b820859b0c022e4085d320b5da/code/modules/mining/lavaland/tendril_loot.dm#L319-L352
