### ISSUE TITLE
Captains duffle bag spawns empty, no contents

### ISSUE THREAD

**Issue by SyncIt21** [tgstation/tgstation#76407]
**1. Reproduction**

1. Sign up as captain
2. Check your duffle bag
3. See that its empty when in fact it should have contained a
    - Survival Box
    - Telescopic beacon
    - Station Charter

Even the code agrees with me
https://github.com/tgstation/tgstation/blob/fe3738ffa09de102a48f5b3f5b6b2c6f328a72d3/code/modules/jobs/job_types/captain.dm#L63-L66

Revert #76313 & Test Locally
1. Sign up as captain
2. Check your duffle bag
3. Everything is there as it should be

Conclusion Broken by #76313

@LemonInTheDark

**Comment by PVT-LF** [comment]
Just found this out too while testing for a different bug...

**Comment by ChungusGamer666** [comment]
bruh

**Comment by Funnytoilet** [comment]
I don't believe the capacity was meant to be changed, as backpacks and satchels can carry 7 normal sized items, while duffels could hold 10 normal sized items, now duffels can only hold 7 normal sized items, I think it somehow got reset during the change.

**Comment by Funnytoilet** [comment]
Also, along with the main bug report your items as any job don't spawn in your duffel, such as the survival box, also not to mention any trait given items spawn below you, although I've only tested it with one trait item and late joining, but I think it's safe to say it doesn't work shift start either.

**Comment by Funnytoilet** [comment]
Ok after even FURTHER testing apparently duffels only can hold 7 items, period, meaning you can only hold 7 pens or whatever combo of different sized items without you being able to hold more, almost as if it was a box, odd, but I hope this helps contribute to a fix.

**Comment by LemonInTheDark** [comment]
wtf

**Comment by wulfenbach-jpg** [comment]
This is related to the zipper code. After testing on a local, a bandaid fix to have department duffel bags spawn with their contents is to modify the following code
https://github.com/tgstation/tgstation/blob/616772574efc407b895f5d9526f00df384564ebd/code/game/objects/items/storage/backpack.dm#L402-L404
to instead:
```
/obj/item/storage/backpack/duffelbag/Initialize(mapload)
	. = ..()
	set_zipper(FALSE)
```
This can be seen to work in the following screenshot:
![dreamseeker_29-21-28](https://github.com/tgstation/tgstation/assets/53832839/1e8bdb3a-1a6c-46cb-a33a-67e39957c1b2)
However, this is a bandaid fix, and does not solve the root cause of the issue, that being, the way that zippers work in relation to `backpack_contents`.

**Comment by LemonInTheDark** [comment]
![image](https://github.com/tgstation/tgstation/assets/58055496/9bc1004c-00ad-4123-8c02-11e1ebe9c940)

I can't think of anything more workable here, since we can't bypass locked on addition. wouldn't make any sense yaknow?

**Comment by LemonInTheDark** [comment]
Should have failed unit tests deleting when filling an outfit shouldn't be acceptable

**Comment by TheVekter** [comment]
We're so back boys
