### ISSUE TITLE
Space cleaner foam grenades do not clean the color reagent

### ISSUE THREAD

**Issue by paprka** [tgstation/tgstation#7640]
on tiles or otherwise

**Comment by Miauw62** [comment]
@Iamgoofball

**Comment by Iamgoofball** [comment]
does it work with things other then foam such as smoke and spray bottles?

**Comment by paprka** [comment]
Don't think so

**Comment by Iamgoofball** [comment]
i just tested, it works with spray bottles

**Comment by paprka** [comment]
No, because it didn't work before cheridan's update

Look at the date this issue was created goof

**Comment by Iamgoofball** [comment]
oh

**Comment by Cheridan** [comment]
rekt

**Comment by phil235** [comment]
Currently nothing can clean the color reagent because it's coded to use the target atom's color var, and plenty of other things use that variable. So anything that is coded to clean that reagent would also be able to remove the blob's color or space vines color for example. The solution could be to make the color reagent use another variable altogether, and then make space cleaner and water reset this new var.

**Comment by nullbear** [comment]
OR you could have things with a modifiable/non_modifiable color (such as blobs, the red space carp plush, etc) have a flag (flags |= UNCOLORABLE) and then space cleaner (and colorful reagent) would only color or uncolor objects that do not have that flag.

**Comment by PKPenguin321** [comment]
A whole new flag for one reagent seems kind of tacky

**Comment by nullbear** [comment]
it would be for two reagents + sinks and adminshittery
