### ISSUE TITLE
Botany bags harvesting plants incorrectly

### ISSUE THREAD

**Issue by zoomachina** [tgstation/tgstation#76462]
BYOND 514.1589

## Reproduction:
Grow a plant, wait until it's ready to harvest.
Try to harvest it with the plant bag.
The harvested fruit will drop on the tray, instead of being put into the bag automatically.

Also, if you're standing on top of another fruit while doing this, it will be put into the plant bag, even though you never clicked on it.

**Comment by Sealed101** [comment]
the way that bag picks up produce is janky and hilarious. when a player clicks the tray with a bag, it causes the player to actually click the tray with hand, which drops the produce under the player. then the bag just eats up anything below the player.
#76018 broke that stupid chain by always setting `output_loc` as the tray's loc instead of the previous `parent.Adjacent(user) ? user.loc : parent.loc //needed for TK`

ideally this interaction should be made less non-sensical but otherwise just changing the bag's item pickup to be able to pick up the produce from the tray's loc should work

holy shit that's a lotta __relevant code__
https://github.com/tgstation/tgstation/blob/067bc9f15ca8c08aa60f35674dc503d6bb72b121/code/modules/hydroponics/hydroponics.dm#L990-L994

https://github.com/tgstation/tgstation/blob/067bc9f15ca8c08aa60f35674dc503d6bb72b121/code/modules/hydroponics/hydroponics.dm#L1061-L1075

https://github.com/tgstation/tgstation/blob/067bc9f15ca8c08aa60f35674dc503d6bb72b121/code/modules/hydroponics/seeds.dm#L201-L235

**Comment by MTandi** [comment]
Working on it

**Comment by MTandi** [comment]
I just reverted my changes without refactoring the way items are picked up.
