### ISSUE TITLE
Supermatter Starts by itself, and Ignites

### ISSUE THREAD

**Issue by CherryCatGal** [tgstation/tgstation#76467]
## Round ID:
[209435](https://scrubby.melonmesa.com/round/209435)

## Testmerges:
None, I believe.

## Reproduction:

Issue occurred on Icebox, but has happened on other maps before. I set up a fairly standard N2 SM gas loop, which is more or less identical to the instructions on the wiki last I checked it, save for swapping out the pressure pumps for volumetric ones. I checked the gas meters, and was waiting for the n2 to cool. because of icebox's subpar cooling loops. Initially I had the outdoors pipes out of the loop because of icebox's subpar cooling loops, but added them in while the gas was pumping in the hopes it would speed up the process. When I did that the SM starts sparking on its own, and immediately sets itself on fire, despite not touching, throwing anything into, lasering, or turning on the emitters for the SM. Unsurprisingly the SM exploded not long after, despite my best efforts to prevent it.

**Comment by Jacquerel** [comment]
From logs from this round: `The supermatter crystal has been powered for the first time by environmental factors.`
Now I don't understand enough about gas or the engine to explain exactly what happened but this log implies that this isn't a _bug_, rather than just something you didn't want to happen? It seems like it's intended that under certain atmospheric conditions (looks like heat with certain gas mixes) then it will consider itself to be stimulated enough to turn on.

Also does it if it encounters Miasma, but that wasn't what happened here.

**Comment by SyncIt21** [comment]
The supermatter is triggered by
1. Proto-nitrate
2. CO2
3. Excess O2 relative to N2 

The best explanation which also happened to me is that you probably either
- turned off the vents by accident
- didn't set them to internal OR atleast a good external pressure(above 101kpa)
So as the scrubbers were taking N2 & O2 out of the chamber not enough N2 was being pumped back in which means at some point there was more O2 than N2 in the chamber which activated the crystal.

Best possible theory

**Comment by TheVekter** [comment]
Given the above comments I'm going to close this as it appears to have been intentional. If you notice it happen again, get a gas reading real quick as soon as you see it and we can probably better piece together what happened.
