### ISSUE TITLE
floorpill viruses are mutatable

### ISSUE THREAD

**Issue by ATH1909** [tgstation/tgstation#76487]
for some reason, they were made /datum/disease/advance subtypes instead of /datum/disease subtypes

this means you can add symptoms to them beyond their default ones and otherwise operate them as you would a normal virus

you can give them enough transmissability to make them infectious, for example

you can also force your deathviruses to have the same cure as one of the three floorpill viruses (in this case, carpet, the same as the carp virus), regardless of its resistance stat:
![image](https://github.com/tgstation/tgstation/assets/42606352/4e035eb7-f039-42b1-bea7-a86926be1484)

and yes, you do teleport if you base your virus off of the carp one:
![image](https://github.com/tgstation/tgstation/assets/42606352/16077716-a71b-44d0-b761-7632a983771e)

this could be a feature, the pr's author hasn't responded to my discord pings yet

beeviro real??

**Comment by TheVekter** [comment]
This is funny enough that I'm tempted to say it's intended, but until I hear otherwise from the author, I'm listing it as a bug.

**Comment by MTandi** [comment]
This is intended. 

They were made advanced diseases to override diseases with lower resistance and vice versa. Simple diseases can't be overridden. 

Carpelosis has lower roll (20%) because it is infective with bites.

And the cure is static to avoid cases where it can be used as base for deathvirus - you need a simple chemical to heal it and you can prepare the vaccine in advance.

**Comment by TheVekter** [comment]
Noted, thank you.
