### ISSUE TITLE
TGUI ghost role pop-ups make me want to slam my keyboard into the wall

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#76507]
## Round ID:

N/A
## Testmerges:

N/A

## Reproduction:

1) Be in the middle of typing up an adminhelp
2) Pop-up comes up about being a fucking carp or something
3) Hit almost any key
4) Choice Registered: Yes

Can we PLEASE stop making them steal focus it's infuriating

**Comment by MrStonedOne** [comment]
i spent ALOT of time making the fake tgui alerts (tg_alert) not steal focus. i think we might have to move unsolicited prompts back over to that

**Comment by Iamgoofball** [comment]
this seems like a bug, they're supposed to not steal focus anyhow

**Comment by MrStonedOne** [comment]
> this seems like a bug, they're supposed to not steal focus anyhow

i spent a whole ass weekend making tg_alert *actually* not steal focus. tweaking and fucking with everything and testing it under different levels of latency.

if whoever made tgui_alert didn't do that, then it steals focus.

**Comment by jlsnow301** [comment]
i'll take a look into this, as alerts have been on my list

**Comment by JohnFulpWillard** [comment]
I thought ``autofocus`` arg in ``tgui_alert`` was for this

**Comment by jlsnow301** [comment]
> I thought `autofocus` arg in `tgui_alert` was for this

It is, and ironically the example given in the OP references a line that doesn't use it. The LTO ghost role popups have it set to off, so that would just mean it isn't working at all

**Comment by MrStonedOne** [comment]
the key thing is that while byond has an window property for is-focused, you can't trust it because winset() and browse() use two different client network message queues.

the method i had to use was to spam a winset to set the old focused window element to focused until the browser control triggered a callback to say it had loaded, and then send one more.

Even this wasn't perfect, as the element that was focused could have changed since opening the window.

Use "clumsy" on Windows to simulate lag, but it's broken on localhost (it will only add lag to 1 direction ), so you have to connect DS to your computer's local ip instead of hitting the yellow join button.

Do not run the game in standalone (ds running the server and the client) as this will fully erase the race condition and everything will seem fine when its not.

review my tg_alert pr https://github.com/tgstation/tgstation/pull/14074/files for reference on how i had to impliment focus preservation. Some of this should/could be moved to the tgui window manager on the client to get rid of the race conditions.

**Comment by TheVekter** [comment]
79105 has mercifully freed me from this special little corner of hell, popups are dead, the second best death in 2023
