### ISSUE TITLE
PAI holoform can be used to safely stow vorpal scythe

### ISSUE THREAD

**Issue by VladinXXV** [tgstation/tgstation#76879]
Reporting client version: 514.1589

## Round ID:
[210329](https://scrubby.melonmesa.com/round/210329)

## Testmerges:
- [Optimization pass focused on foam code (saves about 30% of cpu usage I think)](https://www.github.com/tgstation/tgstation/pull/76104)

## Reproduction:
1. Get a pAI
2. Have them go into holoform
3. Hit them
4. Your scythe may now be stowed safely.

![image](https://github.com/tgstation/tgstation/assets/44104681/067ee29a-121d-4b0a-82f2-bc6b4814a912)

**Comment by necromanceranne** [comment]
I don't give a shit to fix this while holoform is up in the air as to whether it will remain in the game in the near future. If that isn't resolved, I still don't give enough of a shit to resolve this edgecase. You can also use any multitude of small animals and robots to do the same thing, and I think that's entirely fine because I don't want to have players trying to use these in valid situations (like trying to actually kill a holoform PAI that is fleeing) be punished arbitrarily just because a few people figured out a loophole with a friendly PAI. 

Its not a terribly strict restriction, it just wants you to hit something, and I'll leave any loop holes in as workarounds and entirely within scope. I'd be more worried if you could empower using something other than a human with a mind (and listen, even that has some loopholes, like funny business using lings)

**Comment by VladinXXV** [comment]
works for me i just wanna make sure im not gonna get in trouble for exploits or something if Big Brother sees

**Comment by necromanceranne** [comment]
If anyone gives you shit, point them to me.
