### ISSUE TITLE
attempted to observe while already observing spam in admin log

### ISSUE THREAD

**Issue by SapphoQueer** [tgstation/tgstation#77034]
## Round ID:
[210837](https://scrubby.melonmesa.com/round/210837)

## Reproduction:
I can't guarantee that this is it, me and the admins involved in the ticket also weren't sure. But as far as I could tell
1. Be in observe.
2. Toggle the "auto-observe" toggle
3. swap through some people
4. click on their backpack?
5. hud disappears, thing starts to be spammed in admin log.

Best bet however is probably to logdive, sadly.

![image](https://github.com/tgstation/tgstation/assets/94389951/9558da0a-0b73-4a44-bf60-b5a40841ea5f)
(thanks jackraxxus for showing me the exact message)

**Comment by distributivgesetz** [comment]
My guess is that this check fails because eye is not a mob or eye is the player, causing `cleanup_observer` not to be called, which leaves `observetarget` as not null, causing the admin log spam and the stack traces. What set of bizarre circumstances makes `eye` invalid, I really have no fucking clue https://github.com/tgstation/tgstation/blob/e746dda8d02290095f6911fca010961d796942d6/code/modules/mob/dead/observer/observer.dm#L871-L872

**Comment by distributivgesetz** [comment]
Update, got consistent reproduction down

1. Be a ghost
2. Enable Auto Orbit
3. Auto orbit yourself
4. Auto orbit another thing in the orbit menu, your HUD should disappear and every orbit should produce an admin log message

**Comment by MrMelbert** [comment]
(deliberately spamming admin logs is pretty nothing-burger since the admins can just kick you)
