### ISSUE TITLE
Mining Scanners unable to or unresponsive in defusing Gibbonite

### ISSUE THREAD

**Issue by Chocodaemon** [tgstation/tgstation#77142]
## Round ID: [205598](https://scrubby.melonmesa.com/round/205598)
Terry server, but issue has been experienced on Sybil server as well.

## Reproduction:
Normal or advanced mining scanners are unresponsive and fail to defuse gibbonite properly. Spam clicking sometimes works but this isn't the optimal way to defuse gibbonite, and failure usually results in the death or severe injury of the miner or defuser.

**Comment by Sealed101** [comment]
what is this round id

**Comment by Chocodaemon** [comment]
Just a random round where another miner brought it up. They said they got blown up 4-5 times from attempting to defuse gibbonite themselves.

**Comment by Sealed101** [comment]
this round is non-existent, change the first 9 to a 2 in the name and the link

**Comment by Chocodaemon** [comment]
Thanks, not sure why it was pasted wrong in the first place!

**Comment by Sealed101** [comment]
ahh there it is - it gets unresponsive when the player is clicking the gibtonite's flashing mutable appearance. this thing doesn't count as part of the gibtonite and thus doesn't interact with the mining scanner in any way. it used to be an image and it did not intercept clicks in any way, but mutable appearance does apparently. clicking on the rock instead of the overlay is snappy as always.

caused by #76937
https://github.com/tgstation/tgstation/blob/adf4605b24258e9c96fa985e1d11912add6aae19/code/game/turfs/closed/minerals.dm#L704-L715

**Comment by Chocodaemon** [comment]
Is it actually fixed? Tried mining Round 211257 and it doesn't seem like anything changed. Will double check later to make sure.
