### ISSUE TITLE
You can boh bomb by putting a single boh inside itself

### ISSUE THREAD

**Issue by Looks-to-the-Moon** [tgstation/tgstation#77204]
## Round ID:

private testing

## Testmerges:

n/a

## Reproduction:

1. Open bag of holding's inventory
2. Put it in your hand
3. Insert it into itself
4. Proceed

https://github.com/tgstation/tgstation/assets/84770128/6518cd1d-6eeb-40ee-993f-61c2c0cc99f2

**Comment by the-orange-cow** [comment]
Feature

**Comment by YakumoChen** [comment]
I can't believe we regressed this behaviour somehow

**Comment by Sealed101** [comment]
waiting on a livrah video where he boh bombs nar'sie with this

**Comment by Sealed101** [comment]
since the boh bomb reaction is intercepting the `attempt_insert()` it doesn't get to the `can_insert()` checks

https://github.com/tgstation/tgstation/blob/da13ec07f7635382c43082f73386fe2456bd08e2/code/datums/storage/subtypes/bag_of_holding.dm#L7-L19

https://github.com/tgstation/tgstation/blob/da13ec07f7635382c43082f73386fe2456bd08e2/code/datums/storage/storage.dm#L427-L439

https://github.com/tgstation/tgstation/blob/da13ec07f7635382c43082f73386fe2456bd08e2/code/datums/storage/storage.dm#L330-L351

**Comment by timothymtorres** [comment]
Can you insert a regular backpack into itself?

**Comment by Ghommie** [comment]
> Can you insert a regular backpack into itself?

Nope, `can_insert` prevents situations like it.
