### ISSUE TITLE
Parasitic infection seems to have issues being cured

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#77275]
Reporting client version: 514.1589

## Round ID:
[211478](https://scrubby.melonmesa.com/round/211478)

## Reproduction:

Spawn a /obj/item/food/candy/bronx
Force feed it to an NPC
They get a parasitic infection
Follow the advice and remove their liver.  It wont cure them.  They'll slowly die of toxin (which since they have no liver to heal chems you'll have to admin abuse to keep them alive ??)
Replace the liver with a new one.  This doesn't seem to help either.

Calling cure() on the disease datum DOES cure it so something''s just going wrong in the early lines of stage_act in datums/diseases/parasitic_infection.dm I think where it calls the parent and the parent will return "FALSE" because the required_organ is missing and thus bail the check_act entirely before the cure?

**Comment by Jacquerel** [comment]
Your evaluation of the cause seems likely to be correct.
May be solvable simply by setting `required_organ = null` but this would have the sad side effect that you wouldn't be able to implant infected livers into other people.
Perhaps easier to just move the check for absence of a liver to before `..()`
