### ISSUE TITLE
Regal Rats destroy disposal units again

### ISSUE THREAD

**Issue by ZeroKelvn** [tgstation/tgstation#77522]
Reporting client version: 514.1589

## Round ID:
[212235](https://scrubby.melonmesa.com/round/212235)

## Testmerges:
- [Trying to qdelete a callback now lags the server instead.](https://www.github.com/tgstation/tgstation/pull/77447)
- [Revert "Bumps rust-g to `3.0.0` "](https://www.github.com/tgstation/tgstation/pull/77307)
- [Feature: bitrunner, a new supply role](https://www.github.com/tgstation/tgstation/pull/77259)
- [Fixes some lua problems, specifically with qdeling callbacks and adds lua utility functions](https://www.github.com/tgstation/tgstation/pull/77468)

## Reproduction:
1. Become a Regal Rat
2. Try to fish for cheese in a disposal unit
3. Attack the disposal unit while trying to fish for cheese
This has been flagged as a bug before and been fixed, but it seems like we've had a regression at some point again.
Also I've noticed that rats will just refuse to attack people and quiver, and even the admins don't seem to understand why. It seems completely pointless when they also can't damage anything, and means the Regal Rat is left completely defenseless to anyone looking to curb stomp them.

**Comment by san7890** [comment]
This shouldn't be happening post-#77681 because it's impossible to both attack AND try to attack a disposals unit. I think there was something weird with sleeping in the pre-refactored code? Regardless let us know if this happens because this issue was made a week before the refactor (that should have resolved this issue, as well as all of the other AI issues) was merged.
