### ISSUE TITLE
Being forced to join round as random job after setting 'Return to lobby if job unavailable' and not getting preferred jobs

### ISSUE THREAD

**Issue by DeerJesus** [tgstation/tgstation#77609]
## Round ID: 

212491

## Testmerges:

#77307: 'Revert "Bumps rust-g to `3.0.0` "' by MrStonedOne at commit 8dad0feceb
#77447: 'Trying to qdelete a callback now lags the server instead.' by MrStonedOne at commit e15efd1604

## Reproduction:

set job to clown or AI only
set to 'return to lobby as unavailable'
spawn in as a random job anyway for some reason ??
suicide roundstart because my extremely goofy looking clown character is now a paramedic

also it was a round where everyone started drunk and in vomit so maybe that had something to do with it

**Comment by MrMelbert** [comment]
In the future you should include your ckey when reporting job issues, as we can check the job debug file to verify what went wrong

However in this situation, it appears to be obvious

- Dynamic selected Revolution roundstart
- You were chosen as the initial headrev
- You could not become AI (invalid role) and another player rolled Clown before you, leaving you with no possible roles
- Because you had no roles, but were selected for an antag, you were given a random job 

And much later down the line

- Something happened to you, no idea what, but you were in an invalid state to take on Headrev when it actually executed

`[2023-08-14 05:33:18.974] DYNAMIC: Roundstart Revolution discarded Kofka Palazzino from head revolutionary due to ineligibility.`

**Comment by DeerJesus** [comment]
MY FUCKING ANTAG TOKEN!!

**Comment by DeerJesus** [comment]
Hold on, I haven’t been able to roll antag for a WHILE now. Is there a possibility this is repeating itself?

**Comment by DeerJesus** [comment]
Nvm it was because I suicided due to getting paramedic on the wrong character and it didn’t tell me I even had headrev because of the delay
