### ISSUE TITLE
You can't hear anything from holopads

### ISSUE THREAD

**Issue by rageguy505** [tgstation/tgstation#77730]
Reporting client version: 514.1589

## Round ID:
[212810](https://scrubby.melonmesa.com/round/212810)

## Testmerges:
- [Feature: bitrunner, a new supply role](https://www.github.com/tgstation/tgstation/pull/77259)
- [Separate init_possible_values() from icon generation](https://www.github.com/tgstation/tgstation/pull/77660)
- [Disable Rust based url decoding and encoding overrides](https://www.github.com/tgstation/tgstation/pull/77397)

## Reproduction:
Unsure if the ai suffers from this but, call a pad and try to have a converstation. The one on the pad can't hear anything on the other end.

**Comment by Quink-Fix** [comment]
Can confirm, at least from downstream; the 'caller' can see certain emotes (e.g. simplemobs) but cannot hear anything from people on the other end.

**Comment by rageguy505** [comment]
https://github.com/tgstation/tgstation/assets/54517726/62405adb-8859-4424-a990-0c7ee46fa007

**Comment by OverwatchVoice** [comment]
Can confirm thiss is still an active issue

**Comment by Shadow-Quill** [comment]
It was broken in #75931 due to these lines: https://github.com/tgstation/tgstation/blob/36f336bfd1c7d3a3a1a6fc40a41f661527afcce8/code/modules/mob/living/living_say.dm#L279-L283

This code is checking the distance between the actual human and the listener, instead of the hologram and the listener. If a holopad is _just_ outside the normal hearing range, you'll get slightly starrified text.
