### ISSUE TITLE
polymorphic belt thing can't scan some things that it seems like it should be able to

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#77756]
Reporting client version: 514.1589

## Round ID:
[212897](https://scrubby.melonmesa.com/round/212897)

## Testmerges:
- [Trying to qdelete a callback now lags the server instead.](https://www.github.com/tgstation/tgstation/pull/77447)
- [Revert "Bumps rust-g to `3.0.0` "](https://www.github.com/tgstation/tgstation/pull/77307)
- [MODLink System (+ NWTLMM)](https://www.github.com/tgstation/tgstation/pull/77639)
- [Revert "Edits a proc from dynamic.dm to use the actual cumulative formula of the Cauchy-Lorentz distribution."](https://www.github.com/tgstation/tgstation/pull/77728)

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/12635164/c2638eba-77d0-4631-9b0e-38ed96ac091c)
couldn't scan this thing while alive or dead, and previously in the round I couldn't scan an adult slime

**Comment by Sealed101** [comment]
bile/vileworms are considered bugs, and slimes are... slimes

https://github.com/tgstation/tgstation/blob/7d18b6317035ec868068b100a2e049b6e153b0bb/code/modules/mob/living/basic/lavaland/bileworm/_bileworm.dm#L8

https://github.com/tgstation/tgstation/blob/7d18b6317035ec868068b100a2e049b6e153b0bb/code/modules/mob/living/simple_animal/slime/slime.dm#L28

https://github.com/tgstation/tgstation/blob/7d18b6317035ec868068b100a2e049b6e153b0bb/code/modules/clothing/belts/polymorph_belt.dm#L63-L65

i'd wager this is intentional but it's up to jacq, really

**Comment by newfren** [comment]
bugs are organic

**Comment by Sealed101** [comment]
not in the code they're not :^)

**Comment by Jacquerel** [comment]
I would have to double check if there was some reason they're not organic but i don't necessarily see the harm.  
We could perhaps even flip it to "not robotic" if it is important not to be able to use tend wounds on a slime.

**Comment by Sealed101** [comment]
yeah probably blacklisting biotypes instead of whitelisting the organic biotype could be less sanity-crushing with all the mobs out there - the dupe also mentioned a heretic mob for example
