### ISSUE TITLE
Reaching the healing threshold of breathed-in healium puts the user (victim) in a neverending sleep.

### ISSUE THREAD

**Issue by OverwatchVoice** [tgstation/tgstation#77859]
Reporting client version: 514.1589

## Round ID:
Private server, git build from 20.08.2023

What it says on the tin. If a mob reaches the effective threshold of Healium (The one at which point healium appears in their bloodstream), the user will be exiled to a neverending slumber, with nothing short of an aheal, or constantly dosing modafinil capable of breaking the curse.

**Issue likely lies in the proc `PermaSleeping()`, with the Healium reagent being the only instance in the code where it's used.**
Maybe having it work more in line with N2O would just be simpler than trying to fix it?

## Reproduction:
Have a gas canister with sufficent healium in it. Breathe it in. Gaze in awe as you're unable to do anything, forever.
(I used 2:1 Healium : Pluoxium at 12kpa).

**Comment by Inari-Whitebear** [comment]
From what I can tell it's because when the sleeping status_effect gets created by permasleep, `START_PROCESSING` isn't called because the duration is -1.
But then when healium ends metabolization it calls `SetSleeping` which just updates the duration, but doesn't actually cause the status effect to process?

Maybe I'm wrong though

**Comment by MrMelbert** [comment]
#77637
