### ISSUE TITLE
Ash walkers can't get materials from goliaths/lobstrosities by sacrificing

### ISSUE THREAD

**Issue by Papersmiles** [tgstation/tgstation#78089]
## Round ID:

https://github.com/fulpstation/fulpstation

## Reproduction:
Bring a dead goliath/lobstrosity to the tendril. Tendril eats it but doesn't spit out any bones/meat/etc

**Comment by Sealed101** [comment]
that's because simple_animal mobs like brimdemons or the basic lavaland mobs before their basic-bitchification have a `gib()` override that drops their `butcher_results`, and basic mobs don't

https://github.com/tgstation/tgstation/blob/b66b56cef9cc9462ffb2f1e641f9daf5fda38b6f/code/modules/mob/living/simple_animal/simple_animal.dm#L406-L417
