### ISSUE TITLE
Revolvers (and possibly other boltless weapons) cannot reload if ammunition fired from them is caseless (uses caseless element and all)

### ISSUE THREAD

**Issue by Paxilmaniac** [tgstation/tgstation#78182]
## Reproduction:
Be a little silly and load a revolver with ammo using the caseless element.
Fire the revolver to empty.
As the rounds were caseless, there are no shells to eject.
Be unable to reload weapon.

What’s probably happening here is that despite there being nothing in the revolver’s internal magazine, because it never ejects any casings it still thinks its full.

**Comment by Paxilmaniac** [comment]
Actually its dumber than I initially thought. It works completely fine with the caseless element but if you set the is_cased_ammo var to false then it breaks??

**Comment by necromanceranne** [comment]
https://github.com/tgstation/tgstation/blob/17562248c90410d445f1213994e5aad498205d36/code/modules/projectiles/guns/ballistic.dm#L438-L439

It's very likely this is depreciated. However, this likely has always been broken with regards to revolvers, since it replicates a bug that has broken revolvers at least twice now in the last few months.

We may want some kind of unit test for this, since revolvers are holding a reference to ammunition still stored in the magazines' ``stored_ammo`` list, and that value can actually be a null.
