### ISSUE TITLE
Legendary fisher achievement is broken

### ISSUE THREAD

**Issue by Livrah** [tgstation/tgstation#78187]
## Reproduction:

>fish
>get 0 fish cos minigame sucks
>grind legendary skill anyway
>cool hat but no achievement 
![Screenshot_114](https://github.com/tgstation/tgstation/assets/64209864/8a782438-70de-4af2-8708-041233b26d2d)
Either only one person per round can get this achievement or admins are just built different.
![Screenshot_115](https://github.com/tgstation/tgstation/assets/64209864/b7324cef-827e-4927-944c-334c52195990)

**Comment by VladinXXV** [comment]
The first round I reached Legendary Fishing skill I didn't get the achievement either, I don't think anyone else got it though? Second time it worked fine though. 

Looking into it, I think the issue is in `code\modules\fishing\fishing_minigame.dm` on line 159.

https://github.com/tgstation/tgstation/blob/7c687a82306be8433faeee608cb2598541cf25dd/code/modules/fishing/fishing_minigame.dm#L150-L165

If I'm reading it right, you only get the achievement if you complete the minigame without it being interrupted in some way. From my experience, sometimes you just get interrupted for no reason at all. 

I can't think of any reason we'd need to make sure the minigame isn't interrupted; if the player has reached legendary, they should get the achievement. Simple as that.

**Comment by OuroborusReporter** [comment]
Absolutely unplayable
![Screenshot 2023-09-08 142748](https://github.com/tgstation/tgstation/assets/88996803/dd634855-fd64-47fe-9fda-b411d1a56d8d)

**Comment by cnleth** [comment]
Tried getting the achievement myself and found out that you need to catch something after reaching legendary skill level for the achievement to count. With that in mind, I managed to get it quite easily by just spending some time fishing after the legendary skill level
