### ISSUE TITLE
Elaborate invincibility as a Power miner and potentially also Holoparasite

### ISSUE THREAD

**Issue by Toxicpid** [tgstation/tgstation#78186]
Reporting client version: 514.1589

## Round ID:
[214142](https://scrubby.melonmesa.com/round/214142)

## Reproduction:
First off, you need to be a Power miner or a Holoparasite, preferably the Protector type of the Power Miner. Second, the owner you are bound to needs to be turned into a cyborg via the machine that AIs that have combat upgrades/are malfunctioning get. In my case, when my Owner entered the machine and was turned into a cyborg, i no longer was bound to any person, rather bound to an empty tile. While i retained my health value, it was no longer able to be decreased. I was able to return to teleport to the empty tile and be buckled, and could re-manifest at any time. What i noticed is that as the Protector type Power Miner i was able to move the empty tile (as the owner is leashed to you, instead of the other way around as a Protector type.)

**Comment by Jacquerel** [comment]
I can't replicate this, I've been ghosted as the guardian every time.

**Comment by Toxicpid** [comment]
It might also depend on whether youre manifested or buckled to your owner while they walk into the machine, as i was manifested when they went into the machine.

**Comment by san7890** [comment]
`Robotize()` will always `qdel()` the original mob (in this case, the summoner), and we delete ourselves as a summoner in the new framework. This should have been how it was previously as well, but I'm more confident that this new code should catch this case now. Let us know if this happens again somehow (maybe it's because the `transformer` (the malf ai robot factory) sleeps? i'm unsure but that raised an eyebrow).
