### ISSUE TITLE
Wigs don't fit on settler (lizards?)

### ISSUE THREAD

**Issue by BangingDonk** [tgstation/tgstation#78215]
## Testmerges:
[#77307: 'Revert "Bumps rust-g to `3.0.0` "' by MrStonedOne at commit 8dad0feceb](https://www.github.com/tgstation/tgstation/pull/77307)

## Reproduction: Be a lizard with the Settler trait and Smooth Headed. Put on your wig. You end up with an absolutely atrocious graphical glitch as a result.

![Wig Problem 01](https://github.com/tgstation/tgstation/assets/16439557/28da4cd9-0f04-4007-a33d-4ea5f91e2eb8)
![Wig Problem 02](https://github.com/tgstation/tgstation/assets/16439557/6e965981-3635-4afe-a29e-f64db1338ad6)

**Comment by FlufflesTheDog** [comment]
Applies to any race. Wigs don't work right with anything that modifies height (settler, spacer, dwarf), the height offset overshoots your head, going too far in either direction.
Just _not_ applying the hair layer height offset seems to fix this since it already renders at head level, but I'm too afraid to touch it because icon code gives me a headache, and I can't figure out what other purpose that code serves.

Some somewhat relevant code:
https://github.com/tgstation/tgstation/blob/70e7c2e5f7cf9b873428f2a645661a247dd601ad/code/modules/clothing/head/wig.dm#L44
https://github.com/tgstation/tgstation/blob/70e7c2e5f7cf9b873428f2a645661a247dd601ad/code/modules/mob/living/carbon/human/human_update_icons.dm#L685

**Comment by necromanceranne** [comment]
@MrMelbert any ideas of a fix?

**Comment by MrMelbert** [comment]
no ideas no
