### ISSUE TITLE
Bluespace launchpads can be used to get to Centcom

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#78387]
Reported by Midnight on our Discord.

Quote: "You just quantum pad from another shuttle to the shuttle z-level, then quantum pad over to the cargo shuttle and hide in a wrenched locker which stops you being sold."

**Comment by Addust** [comment]
this has been noted. i shall spraypaint rude messages in centcom. you are already too late.

**Comment by NoxVS** [comment]
So, more specific explanation. You have shuttles, with hyperspace surrounding them, and then a cordon around the hyperspace. This all occurs on the transit z level that all shuttles share. If you use a launchpad you can go from the shuttle to beyond the cordon, at which point you can make another launchpad to jump into another shuttle's cordoned off area to enter it. Because the cargo shuttle itself has NOTELEPORT, you need to teleport into the hyperspace around it and then climb inside. You can then hop in a locker and ride to CentCom. I haven't attempted to replicate this but from what I know and have seen this is what I believe is happening.

This also allows access to all in transit shuttles, as well as the nukie base, dojo, and heretic sac rooms - All of which are also on the transit z level
