### ISSUE TITLE
Unable to chop towercap logs or bamboo

### ISSUE THREAD

**Issue by Zargoar** [tgstation/tgstation#78402]
Reporting client version: 514.1589

## Round ID:
[214753](https://scrubby.melonmesa.com/round/214753)

## Testmerges:
- [Revert "Bumps rust-g to `3.0.0` "](https://www.github.com/tgstation/tgstation/pull/77307)
- [Pipe gas visuals](https://www.github.com/tgstation/tgstation/pull/78217)

## Reproduction:

1. Grow one tray of tower cap logs and one tray of bamboo.
2. Harvest both trays.
3. Attempt to process both the tower caps and bamboo using a sharp object like a hatchet.
4. Observe neither material is able to be cut.

**Comment by SyncIt21** [comment]
Related #78375

**Comment by jegub** [comment]
Tower caps, durathread, carbon roses and presumably all other non /food/ grown items cannot currently be picked up, dragged, chopped etc. using a direct click. They can be picked up or pulled by interacting via the examine menu. Placing one in a portable seed extractor then trying to extract seeds via Ctrl+Left-Click does nothing, attempting to use one on the seed extractor machine gives "You can't extract any seeds from the [ITEM]!" at which point it vanishes.
These plants look to be resetting to their initial stats again at the point of harvest, can't be sure because I can't use a scanner on them.
