### ISSUE TITLE
blob can make borgs forever druggy

### ISSUE THREAD

**Issue by mc-oofert** [tgstation/tgstation#78489]
Reporting client version: 514.1589

## Round ID:
[215036](https://scrubby.melonmesa.com/round/215036)

## Testmerges:
- [Revert "Resolves parallax harddels" test merge to find lag](https://www.github.com/tgstation/tgstation/pull/78457)
- [Feature: bitrunner, a new supply role](https://www.github.com/tgstation/tgstation/pull/77259)

## Reproduction:

1. dunno what strain, was purple
2. get hit as borg
3. youre now forever druggy

**Comment by IndieanaJones** [comment]
Pretty sure it's regenerative materia iirc

**Comment by GPeckman** [comment]
Can't reproduce this. When tested locally on master, regenerative materia did make borgs druggy, but the status effect wore off relatively quickly. However, the duration stacks with each hit, so its plausible that a borg that got hit many, many times could remain druggy for the rest of the round.

**Comment by SethLafuente** [comment]
Not druggy forever just tested it the effect leaves within 40 seconds, although borgs shouldnt be affected by drugs since they arent meant to be able to process chemicals so this shouldn't happen its most likely have to do with how blobs druggy effect just causes it by hitting then giving the hallucination thing
![dreamseeker_YLpwLEAYiO](https://github.com/tgstation/tgstation/assets/84478872/e8435dd2-79bb-4176-b10b-1e027ac1c5d6)

**Comment by SethLafuente** [comment]
Non the less the issue isnt about borgs getting the effect specifically is about it lasting forever something that isnt an issue so I will be opening #79841 to both clarify that this isnt an issue anymore and to signify the actual issue behind this happening anyways.
