### ISSUE TITLE
Robusta and Arabica Beans when ground in the impressa machine do not transfer reagents.

### ISSUE THREAD

**Issue by dalmationer** [tgstation/tgstation#78485]
## Reproduction:

Grow a fancy bean, such as the robusta mutant coffee bean, which contains ephedrine or cross-pollenating for good reagents.
dry the beans, then grind them in the Impressa coffee machine.
Examine the reagents in the pot in the chemmaster: you'll note that it's only produced cofee.

(this may be intended, but I figured I'd make an issue in case it's not.)

**Comment by SyncIt21** [comment]
Seems intentional from code
https://github.com/tgstation/tgstation/blob/9dd41681d82e4164a8bb756e0b7af7386e24272d/code/modules/food_and_drinks/machinery/coffeemaker.dm#L718-L720

Basically it doesn't care about the properties of the coffee bean it just adds coffee reagent to the container as long as the `coffee` list is not empty(i.e. as long as there are coffee beans in the machine)

Makes sense cause the coffee machine only has that 1 job. If you want to extract the reagents from the bean grind it up in an All in 1 grinder or plumbing chemical grinder

**Comment by SyncIt21** [comment]
Please close this issue if you have no further questions as we have a large amount of open issues at the moment
