### ISSUE TITLE
Dying as a polymorphed creature does not kill you, but it does severely hurt you, and leaves a corpse of your morphed form behind

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#78721]
## Reproduction:

Just get any polymorph spell. Polymorph. Subsequently die. Hey presto, you're back to normal with only a portion of the remaining damage and leaving behind a body of the creature you were.

## Expected outcome

Polymorphing into another creature should be transferring the damage between both forms based on a multiplier of either forms remaining health so that it is consistent across both forms. That is, if you drop to 0, you'll come back in crit. Right now it is _not_ consistent. So you can actually abuse this in some ways to gain substantially more uses of your polymorphic form and use it as a buffer of health.

Also, I don't believe this should be leaving behind a body.

**Comment by GPeckman** [comment]
I did some testing, it looks like when you get un-polymorphed it randomly picks one limb to apply damage too. If it picks the chest, then you're probably going to be put in crit. If it picks a leg or arm, however, you'll be damaged but not in crit due to the way that health and damage work with those limbs.

Also, if you die in a vent (while polymorphed into a ventcrawler), it doesn't gib you or eject you from the vent as expected. You're instead stuck in the vent, unable to get out, and unable to polymorph again even if you're not in crit. I'm not sure if that's related.
