### ISSUE TITLE
Broken Gateway Elevators

### ISSUE THREAD

**Issue by KateAnbolho** [tgstation/tgstation#78858]
## Round ID: [216284](https://scrubby.melonmesa.com/round/216284)

Gateway away ice world mission that has the crashed infiltrator features broken elevators!

https://gyazo.com/aa63dcabe8e1efa96959f044bc33b112

Easy to reproduce, you just get on the elevator and it moves instantly without taking you up with it 

Kinda weird

**Comment by mc-oofert** [comment]
thats not even an elevator thats a shuttle

**Comment by SethLafuente** [comment]
First of all yes its a shuttle but I think in gateway it is meant to be an elevator and that's why it's instant you can just call it back for it to instantly come anyways, there is a console in there for that same reason, the console having a timer is a bit misleading but this is hardly an issue and I doubt anyone will even bother with it so
