### ISSUE TITLE
Wendigo Incredibly Difficult Due to Projectile Spam Lag

### ISSUE THREAD

**Issue by Eronymun** [tgstation/tgstation#78871]
Reporting client version: 515.1614

## Round ID:
[216331](https://scrubby.melonmesa.com/round/216331)

## Testmerges:
- [Fixes modified MA overlays potentially causing duplicate overlays](https://www.github.com/tgstation/tgstation/pull/78719)

## Reproduction:
Not sure if this has been reported or not, though I'm sure it's well known that excessive projectiles causes projectile processing to slow to a crawl. This effects the Wendigo in particular as they have bullet patterns that are heavily reliant on timing with very punishing damage. Combine that with the fact that Wendigo produces enough projectiles to cause said lag, and you have a fight that is either very easy or impossible to win.

**Comment by GPeckman** [comment]
This is an issue with Wendigo more than Colossus because Wendigo has a small arena with no cover to hide behind if the projectiles are lagging. Your best bet for beating Wendigo is to bring like 7 legion cores and at least 2 luxury pens. Make sure you always have the luxury pen icon in the top-right, even if you don't need the healing; The icon means that you have penthrite in your system, meaning that you can take 60 more damage before going into crit. When Wendigo does the death bolt spiral, just tank it and heal with the legion cores. As long as the Wendigo doesn't use the spiral like 4 or 5 times you should be able to scrape by.

**Comment by gueba14** [comment]
I mean, a boss should be hard but it should give a way to escape fro. The atacks, if the boss itself causes lag in a way that its atack ar imposible to escape from then it sounds like an issue to me

**Comment by gueba14** [comment]
Sad that no one gives this atention
