### ISSUE TITLE
Blob zombies aren’t working properly 

### ISSUE THREAD

**Issue by SethLafuente** [tgstation/tgstation#78968]
## Round ID:[216594](https://scrubby.melonmesa.com/round/216594)

1.blob zombies show a health bar

2.blob zombies dont show the blob helmet on top

3.blob spores instantly kill any one sleeping or in crit

4.blob zombies now have notifications when they spawn instead of showing like a ghost role (posibrains, spider eggs)

**Comment by Jacquerel** [comment]
>  blob zombies now are for call instead of working like they used to which is far better

What does this sentence mean

**Comment by SyncIt21** [comment]
A wise man once said.

![Screenshot (321)](https://github.com/tgstation/tgstation/assets/110812394/7fc6b15e-b228-4273-9a48-8a9fdc1850bb)

**Comment by SethLafuente** [comment]
> > blob zombies now are for call instead of working like they used to which is far better
> 
> What does this sentence mean
> 
> > blob zombies show health
> 
> also this one tbh
> 
> This is inadequate as a bug report

It’s very simple blob zombies show a health bar when they aren’t mean to

**Comment by SethLafuente** [comment]
> > blob zombies now are for call instead of working like they used to which is far better
> 
> What does this sentence mean
> 
> > blob zombies show health
> 
> also this one tbh
> 
> This is inadequate as a bug report

What else do you want? All it reports is blob zombies aren’t working properly it also has the round ID to check logs

**Comment by Jacquerel** [comment]
"show a health bar" under what circumstances?

**Comment by Jacquerel** [comment]
I cannot replicate these issues on a local server:

Spores do not convert anyone who is asleep, unconscious, or in any state other than "dead".
Zombies produced by those spores have spores on their heads.
I don't know if they "show health bar" because I still don't know what you're talking about with that one.

I can make them do an alert rather than a yes/no popup but so far out of four things that's the only actionable item in this issue and it's a suggestion rather than a bug report.

**Comment by timothymtorres** [comment]
This is such an awful bug report that I'm going to mark it to autoclose in 7 days unless you rewrite the reproduction steps properly.
