### ISSUE TITLE
Oxyloss no longer causes passing out over 50.

### ISSUE THREAD

**Issue by Higgin** [tgstation/tgstation#79034]
## Testmerges:

The following pull requests are currently test merged:
#78230 : 'Tram v6/Transport Subsystem' by lessthnthree at commit 0117e13ec1

## Reproduction:

1. Put on an air tank.
2. Turn it to 0 kPa and wait.
3. See oxyloss go over 50.
4. Still remain conscious.

I suspect this is due to the changes made to code/modules/mob/living/carbon/carbon_defense.dm in #78657 @vinylspiders 

Particularly these blocks where check_passout() got changed

```
/mob/living/carbon/adjustOxyLoss(amount, updating_health = TRUE, forced, required_biotype, required_respiration_type)
	if(!forced && HAS_TRAIT(src, TRAIT_NOBREATH))
		amount = min(amount, 0) //Prevents oxy damage but not healing

	. = ..()
	check_passout()

/mob/living/carbon/proc/get_interaction_efficiency(zone)
	var/obj/item/bodypart/limb = get_bodypart(zone)
	if(!limb)
		return

/mob/living/carbon/setOxyLoss(amount, updating_health = TRUE, forced, required_biotype, required_respiration_type)
	. = ..()
	check_passout()

/**
* Check to see if we should be passed out from oyxloss
*/
/mob/living/carbon/proc/check_passout()
	if(!isnum(oxyloss))
		return
	if(oxyloss <= 50)
		if(getOxyLoss() > 50)
			ADD_TRAIT(src, TRAIT_KNOCKEDOUT, OXYLOSS_TRAIT)
	else if(getOxyLoss() <= 50)
		REMOVE_TRAIT(src, TRAIT_KNOCKEDOUT, OXYLOSS_TRAIT)
```

**Comment by MrMelbert** [comment]
That's goofy. the former `oxyloss` arg is the same name as the class's `oxyloss` arg. 

So prior it was checking `if incoming oxyloss damage is less than 50, and total oxyloss damage is greater than 50, KO.` or otherwise, `if incoming oxyloss damage is greater than 50, and total oxyloss damage is less than 50, un-KO`. 

Now it's checking `if total oxyloss damage is less than 50, and total oxyloss damage is greater than 50, KO`, which is dumb.
