### ISSUE TITLE
Curious error where selling materials is sometimes producing way too many credits.

### ISSUE THREAD

**Issue by ArcaneMusic** [tgstation/tgstation#79114]
## Round ID:
Confirmed locally and downstream.

## Testmerges:
N/A

## Reproduction:
> so you have to sell over 700 or so uncubed mats
it usually happens more if you wrap the crate in paper
runtimes doesn't say alot about it, eiter
![image](https://github.com/tgstation/tgstation/assets/41715314/d26e422c-5b11-4ba9-8d67-1e630808ea71)

One theory is that this is "almost as if they had a bad elasticity value, for the same crate."
Almost certainly has something to do with the material sheet export datums that were adjusted with #78500. Looking for more concrete information as well.

**Comment by SyncIt21** [comment]
> Confirmed locally and downstream.

Could you write the reproduction steps to produce locally?

I tired
- Selling 20 stacks of iron (total 1000 sheets) in a single crate
- Selling 20 stacks of iron (total 1000 sheets) in 20 different crates

No luck.

**Comment by Iajret** [comment]
@ArcaneMusic there's severe problem inside price calculation equation when you export stuff directly. 
https://github.com/tgstation/tgstation/blob/bbdfba68fc90c35dd06081135b7968398c8c6044/code/modules/cargo/exports/materials.dm#L142
First of all, we account for increase in material amount twice. We already increased it by `amount` at previous line. But thats not a problem. 
The main problem is... `price` variable. Not sure exactly when it fails, but after some steps since we use the price of ENTIRE stack for supply-demand drop, sometimes we get negatives and our material starts having negative prices on market. Then we get larger positive price, even larger negative, much larger positive... since cargo code doesn't sell stuff at negative prices, this loop always end up with big positive numbers.

iron at 6 cr and with 13k stock properly got its price decreased to 0 after selling... 10-ish stacks.
diamonds... sigh, should've written numbers before testing... about 400-600 cr and 600 stock, got negative price after selling first stack. 

I'm not as good at math as i would want to be, so i cant say from a glance at which exact variable this equation fails. But it fails nonetheless. 

![image](https://github.com/tgstation/tgstation/assets/8430839/99e53568-6f68-444f-b222-5fb32d966043)

![image](https://github.com/tgstation/tgstation/assets/8430839/124a116d-7b6f-4297-a56c-bdcaae94bbd7)

looking through screenshots, i may be wrong with all "cargo doesn't export at negative prices" but anyways. 5 stacks sold. Only 3 stacks worth of diamonds accounted for.

**Comment by Iajret** [comment]
i really not sure, how this equation supposed to work, but changing `price` to `SSstock_market.materials_prices[material_id]` should at least eliminate negative numbers (it should have a limit of zero, but as i said, i cant math). I couldve check it, but i'm to lazy to do it. It already took me more than a week to run this thing through a debugger:)
