### ISSUE TITLE
You can buy more materials from the GMM than exist on the market.

### ISSUE THREAD

**Issue by ArcaneMusic** [tgstation/tgstation#79116]
## Round ID:
N/A, locally reproduced on master.

## Testmerges:
N/A

## Reproduction:
Ugh, yeah this one's my bad, I mean most of these wind up being my bad but like this was was MY BAD ya know?

Alright so spawn yourself a metric ton of spacecash into your account or the cargo budget (c10000 bills work well)
Then, use that money to buy 500 units of a high rarity but low quantity material, like bluespace crystal. Typically it's quantity drops to around 350 most rounds in testing anyway.
Nothing will prevent you from adding 500 bluespace crystals to your order in the event that there's only 350 materials.
Send the cargo shuttle, pay for the bluespace crystals.
**The quantity of bluespace crystals on the market do not go down.**

**Shit.**

So in any situation where we're buying materials, the quantity should go down, and quantity that you're attempting to purchase should be weighed against the market in the moment that the order is sent. So if the quantity on the market were to fluctuate lower than what was available in your order before, potentially it would not charge you for the amount that was previously available.

This is more of an ask but in this same vein the contents of the player's order should probably be shown on the GMM tgui somehow but that's not necessary to fix the bug as it allows for some bike levels of profit.

**Comment by HalfPunch** [comment]
If this thing will be fixed then no one on Campbell will be able to use GMM. Because after 4-5 hours of round quanity of all materials equals 0. It's happening because their quanity naturaly mooving towards 0 to simulate(a.k.a do nothing at all) demand of material.
So first of all. It will be good if someone made GMM an actual market... i mean. Are we the only corporation in this world that mine/produce/sell materials? Then where the hell came materials that are "pre-loaded" in GMM

**Comment by Jacquerel** [comment]
Unfortunately we don't design for marathon rounds, Campbell operating in a way the game isn't designed to be played isn't a particular concern when any change is made to the codebase.
