### ISSUE TITLE
points generation doesn’t increase when creating more RnD servers 

### ISSUE THREAD

**Issue by deathrobotpunch** [tgstation/tgstation#79726]
## Reproduction:
1. create an RnD server inside the server room
2. check server console to see if it is connected
3. look at RnD console
4. realise that points per second has not increased

**Comment by SyncIt21** [comment]
- #70912 
Also I created a PR to solve the problem but 
- #71931 
That got rejected

**Comment by deathrobotpunch** [comment]
well that’s shit

**Comment by deathrobotpunch** [comment]
maybe I will try the same PR without the scanning modules

**Comment by SyncIt21** [comment]
> maybe I will try the same PR without the scanning modules

That would get rejected too. because they don't want point generation to increase in any way. Only if you can slip your PR past orange do you have a shot so good luck with that

**Comment by deathrobotpunch** [comment]
> got rejected

I want to make another PR on it without the scanning module upgrades which might have made maintainers more adverse to merging it, could you tell me how to allow server synchronisation?

**Comment by deathrobotpunch** [comment]
if they are against AFKing in the first place wouldn’t less point generation make that worse?

**Comment by SyncIt21** [comment]
> I want to make another PR on it without the scanning module upgrades

The scanning modules was not the reason it got closed yes it definitely made them close the PR close faster but they did not like the idea of players creating multiple servers to increase points in any way.

Oranges idea was to replace the point system altogether with more experiments to unlock designs so he does not like any PR that boosts the point system in any way.

>  could you tell me how to allow server synchronisation?

The code has changed a lot since then. My idea was to just sum the average of all available servers but even that would allow massive point generation so i have no new formulae now.

> if they are against AFKing in the first place wouldn’t less point generation make that worse?

Like i said they want to solve the problem of AFKing by replacing the point system with more experiments therefore giving players something to do. That was the plan but nobody has gotten around to implement it yet
