### ISSUE TITLE
Initial TGUI chat panel crashes

### ISSUE THREAD

**Issue by lessthnthree** [tgstation/tgstation#79814]
BYOND 514.1589

When the server first starts, the initial TGUI chat panel crashes

![image](https://github.com/tgstation/tgstation/assets/83487515/37e94d1b-8438-49bd-bfaf-7ce30a2417e6)

```
SyntaxError: Syntax error
   at Anonymous function (http://127.0.0.1:64969/tmp8868/tgui-panel.bundle.js:1:239105)
   at Anonymous function (http://127.0.0.1:64969/tmp8868/tgui-panel.bundle.js:1:425650)
   at window.update (http://127.0.0.1:64969/tmp8868/browseroutput.html:468:5)
   at eval code (eval code:1:1)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; Tablet PC 2.0; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0)
State: {}

Nanotrasen (c) 2525-540
```

## Reproduction:

Start server, connect to it

**Comment by san7890** [comment]
i always think it's weird why reading `GLOB.year_integer` fails in this situation

**Comment by SyncIt21** [comment]
Duplicate #79576

**Comment by lessthnthree** [comment]
Oh it's that old huh.

**Comment by san7890** [comment]
according to this stack trace (because the CDN obfuscates the information), something is yorking in `chatRenderer.changePage();`, which is invoking something in `Byond.subscribe`, which is erroring on line 468 of `browseroutput.html` (which for the record is just `tgui.html` which reads:

```html
// Message handler
window.update = function (rawMessage) {
  // Push onto the queue (active during initialization)
  if (window.update.queueActive) {
    window.update.queue.push(rawMessage);
    return;
  }
  // Parse the message
  var message = Byond.parseJson(rawMessage);
  // Notify listeners
  var listeners = window.update.listeners;
  for (var i = 0; i < listeners.length; i++) {
    listeners[i](message.type, message.payload); // this is line 468
  }
};
```

This happened during test merges and is now consistently happening on my local with zero code changes. I don't know why eval code is erroring or why it clears on `fix-chat`.

**Comment by SyncIt21** [comment]
It's best to move the above comment and future discussions over too #79576, make it the central issue so we can close this

**Comment by san7890** [comment]
that one is compromised because the issue appears to be one with the CDN due to the obfuscation of the stack trace which is why people assumed cloudflare or something was screwing up (because the PR was test merged) but now it's real merged and a real problem and now we actually have workable data, so i'm going to do the opposite.

**Comment by san7890** [comment]
anyways yes it might be likely that https://[github.com/tgstation/tgstation/pull/79244](https://github.com/tgstation/tgstation/pull/79244) has something to do with it in response to your question so i'm going to look into that avenue

**Comment by SyncIt21** [comment]
Better call saul I mean @stylemistake

**Comment by san7890** [comment]
no reverting `d103c6c8c3c45cf51a63e3daaa6380b13dbb2117` just bricks everything into forcing you to use old chat
