### ISSUE TITLE
Medipen Refiller Doesnt Work

### ISSUE THREAD

**Issue by Cutplays** [tgstation/tgstation#79992]

**Comment by SyncIt21** [comment]
It says that because initially the machine has no reagents. You have to first fill the machine with the necessary reagents via a beaker/ any container and then put your medipen in it.

Better examines/screen tips could aid in explaining how to use this machine so this could be labelled as consistency.

**Comment by Admiral-Gigaton** [comment]
> It says that because initially the machine has no reagents. You have to first fill the machine with the necessary reagents via a beaker/ any container and then put your medipen in it.
> 
> Better examines/screen tips could aid in explaining how to use this machine so this could be labelled as consistency.

they should make it so you can emag it and give it chems to make the something something syndicate disease pen that gives you hyper brain cancer aids
