### ISSUE TITLE
Putting b. in the create object window crashes the client

### ISSUE THREAD

**Issue by Draggeru** [tgstation/tgstation#80186]
## Issue Summary

Entering b. into the create object window via admin tools crashes the admins game.

## Round ID:
[220145](https://scrubby.melonmesa.com/round/220145)

## Reproduction:

Access the create object window via the game panel, enter b. into the search bar, hit search or hit enter, game crashes

**Comment by MrMelbert** [comment]
This happened because you searched the equivalent of `Show me every typepath in the game that has a B followed by any character`

And there's like, over 10,000 typepaths or whatever, so it printed 10,000 typepaths to your game panel

It doesn't actually crash you if you stick around long enough it'll finish rendering
