### ISSUE TITLE
Cannot physically attack alien nests

### ISSUE THREAD

**Issue by Derpguy3** [tgstation/tgstation#80311]
Reporting client version: 514.1589

## Issue Summary
Alien nests seem to be unable to be attacked by a person. You have to either burn it, or shoot it.

## Round ID:
[220459](https://scrubby.melonmesa.com/round/220459)

## Testmerges:
- [Bridge Assistant Station Trait](https://www.github.com/tgstation/tgstation/pull/80279)
- [Revert "FOV is Dead (Long Live FOV)"](https://www.github.com/tgstation/tgstation/pull/80301)

## Reproduction:
1. Acquire alien nest (Home grown by your local xenomorph)
2. Attempt to use a method of brute force against the nest to destroy it.
3. Nothing happens.
4. Resort to flamethrower.

**Comment by MrMelbert** [comment]
Looks like it was caused by #80104 @san7890 

By default all objects have the flag `CAN_BE_HIT`
https://github.com/tgstation/tgstation/blob/32fb42d19e0c763f7e5e3dafb9844d0f05e86630/code/game/objects/objs.dm#L2-L5

But the PR in question added object flags to a bunch of things without inheriting the default flags 
https://github.com/tgstation/tgstation/blob/32fb42d19e0c763f7e5e3dafb9844d0f05e86630/code/game/objects/structures/beds_chairs/alien_nest.dm#L15

Someone should do an audit of everything that has `obj_flags = NO_DECONSTRUCTION` and make sure everything that should has `CAN_BE_HIT`, does
