### ISSUE TITLE
Anesthetics leaking

### ISSUE THREAD

**Issue by MTandi** [tgstation/tgstation#80322]
## Issue Summary

When you try to enable internals on the patient's back, the gas mix is getting released into the air, affecting the doctor.

![9BbYoDVQPw](https://github.com/tgstation/tgstation/assets/3625094/f6a27076-4b99-44ea-b0a0-0a471d5c0479)

## Round ID:

N/A

## Testmerges:

N/A

## Reproduction:

- Get a monke
- Put a mask and an anesthetic tank on it via strip menu
- Enable monkes internals via strip menu
- The area is contaminated with N2O and you start giggle

**Comment by MrMelbert** [comment]
The reason this happens is because when you inhale N2O, it does not consume it, so you exhale the N2O back into the environment.

You exhale into the environment rather than the tank, because that's how all of our internals works, you don't breathe out CO2 in to the tank you're breathing

A while back I thought this was a bug too, but when I went to fix it, I did some research into Anesthesia it turns out doctors commonly have to work around N2O leaks like this IRL.
...So I thought "it's just added immersion".

**Comment by tralezab** [comment]
We could probably do with adding a small description note on the anesthetic tank about this little factoid

**Comment by MrMelbert** [comment]
I personally made it to surgical room scrubbers start pre-set to scrub N2O + extended range but yea

**Comment by tralezab** [comment]
Not fixed, but solved by ^^^^
