### ISSUE TITLE
having mutadone applied when decapitated by a mutation kills and sets your body DNR

### ISSUE THREAD

**Issue by Neocloudy** [tgstation/tgstation#80375]
Reporting client version: 515.1621

## Issue Summary
If you are decapitated by a mutation like from a radstorm, and you get mutadone applied, you die instantly and your body is treated as DNR/catatonic. only fixed by jannie intervention (stuffing your ghost back into your body)

## Round ID:
[220565](https://scrubby.melonmesa.com/round/220565)

## Reproduction:
1. gain whichever mutation decapitates+blinds and deafens you
2. have mutadone applied by someone
3. Your head is still restored and other mutations are removed, but you die instantly and get set to DNR. (I also gained a hairline fracture)

**Comment by Neocloudy** [comment]
probably just broken by the organ refactor

**Comment by SethLafuente** [comment]
This might have been an issue once upon a time but it no longer is, or it requires more reproduction and the reason it was caused is not for the reasons given making this obsolete for use reopen if any further evidence is given this is still an issue or the actual reason is found IF there is even a possibility this can happen again under other circumstances.
![dreamseeker_8lcnPcQ23Y](https://github.com/tgstation/tgstation/assets/84478872/b183e5e7-0b6e-46d0-a270-a0325bd745af)
