### ISSUE TITLE
Psykers were blind, now they are blind AND laggy as hell.

### ISSUE THREAD

**Issue by MrrFiish** [tgstation/tgstation#80442]
Reporting client version: 515.1620

## Issue Summary
Being a psyker will give you horrible FPS lag and you will cry.

## Round ID:
[220707](https://scrubby.melonmesa.com/round/220707)

## Testmerges:
- [Votes now show the percentage of total votes each choice got | Adds weighted random vote type | Map votes are now weighted random](https://www.github.com/tgstation/tgstation/pull/80362)
- [Updates eslint + sorts imports](https://www.github.com/tgstation/tgstation/pull/80430)

## Reproduction:
1) Be a psyker
2) Exist for an indeterminate amount of time that seems to be like 20 seconds
3) Lag

**Comment by necromanceranne** [comment]
I think I've got some insight into how this happens. It seems that multiple psykers in proximity is somehow rapidly causing more and more lag due to overlapping 'sonar pings', if that makes sense. While you can see another psykers ping, the game seems to lag considerably. The pings seem to go off independently at this point as well, which is something that wasn't a problem before.
