### ISSUE TITLE
Sometimes when pulling someone, you can't click nearly anything until you pull something else

### ISSUE THREAD

**Issue by Mothblocks** [tgstation/tgstation#80492]
Reporting client version: 515.1621

## Issue Summary
I can't reproduce it, but sometimes when you pull someone you can't click anything in your inventory, anything in the world, click to turn around, etc. You can seem to click on the action buttons to drag them around and you can click on combat mode though.

This persists even after you stop pulling, but can be solved by pulling something else.

## Round ID:
[220857](https://scrubby.melonmesa.com/round/220857)

## Testmerges:
- [Refactors TS in Box component](https://www.github.com/tgstation/tgstation/pull/80368)
- [(Testmerge Ready) New Antagonist: Tiger Cooperative Fanatic](https://www.github.com/tgstation/tgstation/pull/80313)
- [[TM ONLY] Remove 'natural' beheading](https://www.github.com/tgstation/tgstation/pull/80439)
- [Optimizes the pipeline of basic mobs](https://www.github.com/tgstation/tgstation/pull/79498)

**Comment by RikuTheKiller** [comment]
This may be related to how, when holding CTRL, you can't do certain actions, including changing intents and such.
I encountered this issue on TGMC when holding CTRL to sneak as a hunter, it ended up making me unable to do practically anything else, which sucked.
So I had to use ahk to rebind CTRL to something else to get it to work, but yeah, seems like this might be related since CTRL is used to pull things as well.

**Comment by Mothblocks** [comment]
FWIW Pressing Escape has always fixed that but it doesn't for this

**Comment by MrMelbert** [comment]
May be caused by #79498 test merge?
It changes how `incapacitated` is read and grabbing is an incap state.

**Comment by SyncIt21** [comment]
This still a bug? The test merge was closed a while back
