### ISSUE TITLE
Hovering your mouse over a spraycan gives you the "You are too far away!" message

### ISSUE THREAD

**Issue by Justice12354** [tgstation/tgstation#80880]
Reporting client version: 515.1623

## Issue Summary
Hovering your mouse over a spraycan gives you the "You are too far away!" message

## Round ID:
[221947](https://scrubby.melonmesa.com/round/221947)

## Testmerges:
- [tgui now disables topics on world reboot, should fix reconnects randomly failing](https://www.github.com/tgstation/tgstation/pull/80779)

**Comment by Mothblocks** [comment]
It's because the code for screentips in spray cans calls `can_perform_action`, which not only shits out messages but also doesn't even seem to provide an easy way to turn them off.

Removing the check entirely wouldn't be a terrible fix, but `can_perform_action` (and procs that read like that in general) shouldn't spit them out by default to begin with.
