### ISSUE TITLE
Cyborg code assumes the internal radio is guaranteed to exist, when it's not

### ISSUE THREAD

**Issue by nikothedude** [tgstation/tgstation#80892]
## Issue Summary

Reported from Nova Sector

![image](https://github.com/tgstation/tgstation/assets/59709059/bcd35f36-e7cc-4868-88b9-e0bc5a4d6101)

Title. As seen in silicon.dm initialize(), radio isnt guaranteed to be instantiated, and is in fact, null by default. Yet, In robot_model/proc/transform_to(), cyborg.radio is accessed. This causes runtimes when a borg is made with no radio, such as with a ghost cafe cyborg in nova sector.

## Reproduction:

Step 1: Join nova sector
Step 2: Spawn as a roleplay cyborg in the ghost cafe
Step 3: See a runtime from unsafe assumptions

**Comment by K4rlox** [comment]
why are you making a issue here instead of nova sector...?

**Comment by nikothedude** [comment]
> why are you making a issue here instead of nova sector...?

because its an upstream bug

**Comment by nikothedude** [comment]
the RUNTIME is a issue on nova but the code is flawed up here

**Comment by zxaber** [comment]
The runtime is helpful for us because we don't have any borgs that should ever exist without a radio, so runtiming due to the radio missing helps alert to the problem.

Because this is in the `transform_to` proc, it fails catastrophically when it runtimes, meaning that it forces someone to notice. Quietly not stocking a radio could mean a bug slips through for ages undetected.

For Nova's case, I'd probably recommend looking into making a radio with zero channels, since I assume that would be the least likely to conflict with an upstream future PR and should still get the job done.

**Comment by nikothedude** [comment]
yeah i guess i misunderstood the nature of this bug, ill close it

**Comment by nikothedude** [comment]
i forgot where the close issue button was

**Comment by necromanceranne** [comment]
No, zxaber is correct, this is a problem worth addressing. The suggestion he made would only be a bandaid at best.

**Comment by LemonInTheDark** [comment]
Not a bug

**Comment by wonderinghost** [comment]
if possible i would like to hijack this
im trying to port over the spatial grid and unassigned borg shells produce runtimes because they dont have a encryption key in them

**Comment by LemonInTheDark** [comment]
this is not relevant to our codebase.
if you are looking for help please do so in coderbus

**Comment by wonderinghost** [comment]
figured out the problem, older code bases looking to clear the runtime check if you got borg radio in scr. if it is delete that and make sure in the silicon page that you got a radio var filled out. then return to the borg page and connect the parented radio with the borg radio
