### ISSUE TITLE
Bubblegum tendril attack issue

### ISSUE THREAD

**Issue by sole1777** [tgstation/tgstation#80982]
Reporting client version: 514.1589

## Issue Summary
While I was fighting Bubblegum, a legion caught his attention and he went after it. He then started attacking the tendril it came from. He was doing no damage to the tendril and therefore got stuck in a loop where he was repeatedly attacking the tendril to no effect. I killed him while he was in this state. 

## Round ID:
[222293](https://scrubby.melonmesa.com/round/222293)

## Testmerges:
- [Refactors pod launcher UI](https://www.github.com/tgstation/tgstation/pull/80887)
- [Bumps rust-g to `3.1.0`](https://www.github.com/tgstation/tgstation/pull/80955)
- [Wait 10s in TGS build for ESBuild to exit](https://www.github.com/tgstation/tgstation/pull/80958)

## Reproduction:
Bring Bubblegum near a tendril, let him start attacking a mob from that tendril, and then let him start attacking a mob as it spawns on the tendril. I think this only works if Bubblegum is attacking a mob while it is on the same tile as the tendril.

**Comment by rasepretep** [comment]
Are you sure it was attacking a tendril? Because if there was a legion corpse there, it could be related to: https://github.com/tgstation/tgstation/issues/79757

Short version: megafauna gibbing was removed, but they heal by gibbing corpses. If they can't gib something, they get stuck in an endless loop of trying to gib the corpse.

**Comment by Sealed101** [comment]
attack logs confirm the above

![изображение](https://github.com/user-attachments/assets/4c697bea-e16b-44c5-995d-5c9dfe3c7327)

fixed by #81008
