### ISSUE TITLE
Screwdriver Can't Be Used As A Screwdriver

### ISSUE THREAD

**Issue by dalmationer** [tgstation/tgstation#81017]
## Issue Summary

The screwdriver cocktail currently doesn't work as a screwdriver as intended.
This appears to be a fairly simple order of operations issue.

## Reproduction:

-add 2 parts vodka and 1 part orange juice to a glass.
-Attempt to use it for screwdriver things, such as unscrewing a door's panel, screwing off a computer screen, etc.
-nothing will happen.

**Comment by MrMelbert** [comment]
https://github.com/tgstation/tgstation/blob/5353eca1970901b4847dff3073e4fcb40973d310/code/modules/reagents/chemistry/reagents/drinks/alcohol_reagents.dm#L592-L594

If i'm reading this correctly the only time screwdriver makes the glass a screwdriver is if the glass is "ingesting" the drink ??

**Comment by 00-Steven** [comment]
Looking into this right now.
I don't know exactly *why* that check for ingestion is there, but it seems on_transfer is never actually called for transferring reagents from dispenser to cup or cup to cup in the first place.
The proc used for checking this, `on_transfer(...)`, seems to be inherited from `/datum/reagent`
```dm
/datum/reagent/consumable/ethanol/screwdrivercocktail/on_transfer(atom/atom, methods = TOUCH, trans_volume)
	(...)
```
```dm
///Called after a reagent is transferred
/datum/reagent/proc/on_transfer(atom/A, methods=TOUCH, trans_volume)
	return
```
which is called in `/datum/reagents/proc/trans_to(...)` only if there is at least one method set:
```dm
(...)
if(methods)
	reagent.on_transfer(target_atom, methods, transfer_amount)
(...)
```
However, this proc defaults to `methods = NONE` and does not change it at any point, while transferring from a dispenser to a cup or a cup to a cup seems to call it without setting a method.
```dm
/obj/item/reagent_containers/cup/afterattack(atom/target, mob/user, proximity_flag, click_parameters)
	(...)
	if(target.is_refillable()) //Something like a glass. Player probably wants to transfer TO it.
		(...)
		var/trans = reagents.trans_to(target, amount_per_transfer_from_this, transferred_by = user)
		to_chat(user, span_notice("You transfer [trans] unit\s of the solution to [target]."))

	else if(target.is_drainable()) //A dispenser. Transfer FROM it TO us.
		(...)
		var/trans = target.reagents.trans_to(src, amount_per_transfer_from_this, transferred_by = user)
		to_chat(user, span_notice("You fill [src] with [trans] unit\s of the contents of [target]."))
	(...)
```
Furthermore, I can't find any other way in which the `INGEST` method would be used when transferring to a cup.
Increasingly curious, I looked up the original pr. No changes to the `screwdrivercocktail/on_transfer()` proc since then.
So I went through the history of each file involved back to when the pr was made.
No hints at this ever working.

So out of morbid curiosity, I downgraded my byond, downloaded, and booted the original pr branch.
And lo and behold:
![image](https://github.com/tgstation/tgstation/assets/42909981/9e15e860-64a3-4408-a65f-e195165c896a)
I don't think it ever worked.

I'm not *exactly sure* how to resolve this cleanly, I'll look into that in just a bit, but like.
but just like.

man.
