### ISSUE TITLE
Ice Box has no ore

### ISSUE THREAD

**Issue by Skebulba** [tgstation/tgstation#81058]
Reporting client version: 514.1589

## Issue Summary
Ice Box generates no ore, apart from in some tiles next to ruins.

## Round ID:
[222618](https://scrubby.melonmesa.com/round/222618)

## Testmerges:
- [Newspapers now use TGUI](https://www.github.com/tgstation/tgstation/pull/80991)

## Reproduction:
Go to Ice Box. Look outside.

**Comment by Inari-Whitebear** [comment]
I believe I heard someone say the vents on icebox don't have ores assigned or so too

**Comment by ArcaneMusic** [comment]
Yeah... It's an issue specific to icebox.
Icebox has more vents that spawn on it due to the fact that icebox has 3 mining layers, so I increased how many vents that can spawn on icebox's cave generation. However, the issue is that the `ore_generation` subsystem has a static list it copies for the ore types that can spawn on a specific map, and as lavaland is designed around only having 15 vents that it needs to pull from, we run out of minerals on `ore_vent_minerals`. Ideally, We'll have a map specific to icebox and another specific to lavaland-mining maps to futureproof it against other maps that have remote mining.
