### ISSUE TITLE
Ayys can teleport onto blob

### ISSUE THREAD

**Issue by adamkad1** [tgstation/tgstation#81119]
## Issue Summary

As in title, abductors can use their teleporter to teleport onto blob (So you can like, teleport next to core and slap it. Then if you still got your buddy, get him to bring you back, heal you and do it again. Needless to say that's not very fair. (Not that I actually tried to kill it, I bailed out the moment something hit me and and I didnt have a buddy anymore.

## Round ID:
[222837](http://127.0.0.1:51912/tmp8804/6e8b7715.htm?action=openLink&link=https%3A%2F%2Fstatbus.space%2Frounds%2F222837)

## Testmerges:
#81089

## Reproduction:
Be abductor. Move camera next to blob core. Teleport self or friend. Smack blob. recall if it looks back. profit.

**Comment by YakumoChen** [comment]
Not really a bug so much as abuse of mechanics. Ayys are instructed to largely not interfere with the station.

**Comment by Likteer** [comment]
You will be auto attacked by 9 tiles of blob after a moment.

**Comment by adamkad1** [comment]
> Not really a bug so much as abuse of mechanics. Ayys are instructed to largely not interfere with the station.
I didnt see anything like that but maybe im just blind.

**Comment by YakumoChen** [comment]
> > Not really a bug so much as abuse of mechanics. Ayys are instructed to largely not interfere with the station.
> 
> I didnt see anything like that but maybe im just blind. I just know they shouldnt murderbone. But if they prohibit you from teleporting into ai core and pacifying the ai... And no bwoink either

Check the first two paragraphs of their wiki page

**Comment by davethwave** [comment]
Yeah, not a bug but an administration issue. You yoink the AI you get slapped. You kill a major antag for no reason, you get slapped. An abductor is a research team on the study of humanoid research. If the AI delta's you grab whoever you can as your last subject and leave the crew to their fate.

**Comment by SethLafuente** [comment]
Yeah this isn't really a bug as much as is just a mechanic within the game many other things can teleport into blob since its just a biotic entity that takes over the ground it can also hold corpses above itself so it wouldn't be ingame illogical for it to happen also blob can easily counter it anyways last time I checked abductors can only view places that have cams so blob can just destroy the cams not a bug.

As shown here:
![image](https://github.com/tgstation/tgstation/assets/84478872/76997d98-b4a9-48e9-9a72-a51942ac456f)
with cameras

![image](https://github.com/tgstation/tgstation/assets/84478872/b73dc487-1cb8-45c6-98dc-4c050aeb3831)
When blob destroys cameras

Not only is it not a good strategy but its also mostly not viable anyways.
