### ISSUE TITLE
Autolathes eat 5% power per any usage but show no spike in load on the APC

### ISSUE THREAD

**Issue by Zergspower** [tgstation/tgstation#81167]
## Issue Summary

Something's fucky with the Autholathes

A roundstart autolathe will eat a raw 5% of the cell but not show any spike in power usage, it also current only works with an APC so any area that is powered by the area itself it wont function. 

This happens regardless if the powernet is saturated with 5 MW of power or offline, it looks like it's taking power straight from the cell and ignoring the powernet completely

## Reproduction:

go to cargo or anywhere an autolathe exists, print something and watch no change on the apc except the power cell losing charge.

go to any place (Golems or some shuttles) that have an autolathe and it rejects their ability to use it even though every other machine will work.

**Comment by SyncIt21** [comment]
The fix is simple enough but the change was intentional in #80839

Power consumption was changed from using the powernet(via `use_power()`) to direct local apc(`directly_use_power()`). Was not documented in the PR body/chagelog

![Screenshot (385)](https://github.com/tgstation/tgstation/assets/110812394/b48e54d7-6135-4c62-8455-df0495db1d7a)

I didn't understand the implication of this change when i tried to patch it up in #81116

I'm busy so i won't be making PR's for some time but If your interested in fixing this now you know how. It would fix #81155 as well

**Comment by ZephyrTFA** [comment]
use_power doesn't ensure that the local powernet actually has enough power.

**Comment by Zergspower** [comment]
![image](https://github.com/tgstation/tgstation/assets/22140677/5fc79544-8284-4673-8dfe-c0c6f2d53d79)
 it will also do this, where it bugs the APC out until you take it apart

**Comment by ZephyrTFA** [comment]
upgrade your lathe or accept that printing things costs power

**Comment by Zergspower** [comment]
> upgrade your lathe or accept that printing things costs power

I will slap you

**Comment by FlufflesTheDog** [comment]
\>0% power
\>fully charged
working as intended

**Comment by ZephyrTFA** [comment]
To be more specific, an APC requires ten full power processes to begin charging.
```dm
		if(chargemode)
			if(!charging)
				if(excess > cell.maxcharge*GLOB.CHARGELEVEL)
					chargecount++
				else
					chargecount = 0

				if(chargecount == 10)

					chargecount = 0
					charging = APC_CHARGING
```

**Comment by Zergspower** [comment]
I guess the next question is how do we address the non-apc instances? And i wonder why only the autolathe got this tweak unless something else is planned for all the others?
