### ISSUE TITLE
boulders can build up to the point where it severely lags your game to look at them

### ISSUE THREAD

**Issue by newfren** [tgstation/tgstation#81404]
Reporting client version: 515.1630

## Round ID:
[223689](https://scrubby.melonmesa.com/round/223689)

## Testmerges:
- [A red spy has entered the base: Adds Spies, a roundstart antagonist inspired by Goonstation's Spy-Thief](https://www.github.com/tgstation/tgstation/pull/81231)
- [Temp keybinds patch for 515.1628](https://www.github.com/tgstation/tgstation/pull/81089)

## Reproduction:
set up a timer on the boulder summoner (assumed) so you don't have to baby sit it
mine normally (assumed)
never get the machines upgraded
have the round go for 2 and a half hours (exact length possibly not required)
walk near the boulder processing machines
lag to shit from the sheer number of boulders on your screen

in this round it was on birdshot and I was the only person with xray eyes, so I was the only one to notice it (until I died and got to show a buncha ghosts)

**Comment by SyncIt21** [comment]
> set up a timer on the boulder summoner (assumed) so you don't have to baby sit it

This is the problem, tier 1 refineries aren't built to refine a boulder at the rate the timer is spawning them.

Even a small boulder takes upto 10 seconds(5 process ticks) to refine assuming it doesn't get rejected, speaking of which you have to keep an eye on boulders rejected by both the smelter and refinery and get rid of them(throw them into space or something idk), else they clog up the pipeline adding more to the lag.

The solution is to remove the ability to add timers and actually monitor the BRM from time to time. This problem can be aleviated by my batch processing technique but you would still have to keep track of rejected boulders,  but for now we have remove the ability to attach timers altogether.

Idk @ArcaneMusic thoughts?

**Comment by ArcaneMusic** [comment]
So, another reason why I didn't implement "true" teleportation toggling on the BRM originally was to try and prevent "doomstacks" of boulders such to the point that examining or being near that many items would cause latency. That's why there's a line on the BRM to stop teleportation if `x` many boulders were already on the floor with the brm:

```
/obj/machinery/bouldertech/brm/process()
[snip]
	for(var/obj/item/boulder/ground_rocks in loc.contents)
		boulders_contained += ground_rocks
		if(boulders_contained.len < boulders_held_max)
			continue
		toggled_on = FALSE
		boulders_contained.Cut()
		update_appearance(UPDATE_ICON_STATE)
		return PROCESS_KILL
```
Additionally, vents will stop spawning boulders onto the same tile after 10 exist on the same place, all to stop situations like this from occurring, but as a trade off to giving the BRM wires, manually this can occur. Immediately my thoughts jump to adding a bit more rigor to if/when the BRM will enable for you to teleport a boulder either manually or automatically. Even if you allowed for boulders to get processed instantly, you could still manually create a BRM on a tile without a conveyor belt on a timer and still create a lagtrap in such a way.

Even if we move away from how it works right now, using the "10 boulders sitting on a tile as the maximum" as the current threshold for maximum boulders per tile feels like a somewhat intuitive middleground

**Comment by SyncIt21** [comment]
```
/obj/machinery/bouldertech/brm/process()
[snip]
	for(var/obj/item/boulder/ground_rocks in loc.contents)
		boulders_contained += ground_rocks
		if(boulders_contained.len < boulders_held_max)
			continue
		toggled_on = FALSE
		boulders_contained.Cut()
		update_appearance(UPDATE_ICON_STATE)
		return PROCESS_KILL
```

This should work to prevent such laggy situations but i guess there is a problem in the way `boulders_contained` list is updated and. A better solution using this same concept is to stop the BRM & refinery. from spitting out boulders even if there is just 1 boulder in their loc using a simple check

```
if(if(locate(/obj/item/boulder) in loc))
     //hault operations till this one boulder is cleared up by a conveyer belt
```

This seems to work quite well so i'll link the issue with my PR as a fix, I'll let you review this code in my PR
