### ISSUE TITLE
Sentient Slimes can't stop feeding

### ISSUE THREAD

**Issue by ZeroKelvn** [tgstation/tgstation#81463]
Reporting client version: 515.1630

## Issue Summary
As a pyroclastic slime, click-dragging onto another person and feeding on them meant I could not unbuckle from them. This included after being fire-extinguishered into a baby slime, still being stuck on the same person until killed.

## Round ID:
[223883](https://scrubby.melonmesa.com/round/223883)

## Testmerges:
- [Temp keybinds patch for 515.1628](https://www.github.com/tgstation/tgstation/pull/81089)

## Reproduction:
1. Become a sentient slime
2. Start feeding on someone
3. Try to stop feeding on someone and fail drastically

**Comment by Profakos** [comment]
Hello, I need a few more info to test this. Did you try to unbuckle via hitting Feed again, clicking on the mob, or the status effect?

**Comment by Swootch** [comment]
Can confirm this bug, nothing lets you unbuckle once you're feeding, neither clicking the mob, nor the status effect, do anything to free you.

**Comment by Profakos** [comment]
Thank you, I will take a look when I have time.

**Comment by Profakos** [comment]
I could reproduce clicking on the buckled status effect, and it indeed does not unbuckle you. However, I clicking on the feed action, or the mob itself, worked properly for me. 

The issue is simply, that slimes have "can_buckle_to" set to false, which doesn't let them use the buckling system... unless if called directly, bypassing the checks.
