### ISSUE TITLE
The Nuclear Operative cybernetic implants that spies can get come in the reusable autosurgeon variant

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#81827]
## Issue Summary

Let's say the Mr. Tern Coate managed to complete a bounty for a nice and shiny CNS Rebooter. Well, the Rebooter is nice and all but once Mr. Tern Coate has used up the CNS Rebooter, nothing actually stops them from filling up that autosurgeon with literally any organ they want and keep using it to inject all kinds of things into themselves. Like more cyberware from science.

This isn't the case for any implants that would normally be available to traitors and not operatives (like the Laser Arm implant). The reason operatives have a reusable variant is...well, who really cares if they procure more cyberware on the station, that's fine. It's more difficult and convoluted for them to do that. Spies are crew, they've got some degree of a cover. As a result, spies can mostly bypass the typical restriction of other players to gain an increase in potential cybernetic prowess.

## Reproduction:

It's not really worth reproducing some steps here, it should be self explanatory.

**Comment by Admiral-Gigaton** [comment]
I mean, TBH this just makes them extremely susceptible to EMP and Ions, so i think its a fine balance, being able to just breath an ion on them and they becoming a twitching mess on the ground

**Comment by jughu** [comment]
I made the laser arm one use because design philosphy for autosurgeons because they orginally were added to cut on surgery time or for antags thay couldnt get x stuff implanted without Y person knowing they are an antag hence laser implant coming in a auto surgeon, personally i think all preset implants that come in auto surgeons should be 1 use and if you buy the unlimited auto surgeon(which personally should be limited aswell personally) but jts whatever

**Comment by Y0SH1M4S73R** [comment]
Here's a worrying implication of this issue.

- Get implant with reusable autosurgeon.
- Get mail counterfeit device.
- Put monkey brain into autosurgeon.
- Rig mail with autosurgeon.
- Instant soft RR.

**Comment by jughu** [comment]
Nukies get unlimited auto surgeons because theres no point for them to waste doing surgeries

Traitor gets one use surgeons because they cant ask somoene do a laser arm implantation because then they would know they're valid.

Autosurgeon philospy was always if you have no other choice its ok to put it in a one use autosurgeon same goes for cmo special autosurgeon

**Comment by necromanceranne** [comment]
I'm probably just gonna fix this one myself tbh
