### ISSUE TITLE
Selling anything on cargo shuttle has a value of zero credits.

### ISSUE THREAD

**Issue by the-orange-cow** [tgstation/tgstation#81987]
Round ID: [225491](https://scrubby.melonmesa.com/round/225491)
BYOND Version: 515.1633
Server revision compiled on: 
Master commit: [0981acb23db2561073a9a4e7605e9e5f5e11a468](https://www.github.com/tgstation/tgstation/commit/0981acb23db2561073a9a4e7605e9e5f5e11a468)
The following pull requests are currently test merged:
[#81952: 'Might fix reagent loop' by optimumtact at commit 0646da5764](https://www.github.com/tgstation/tgstation/pull/81952)

Local commit: 92e8d31d25ad9d779b53810e110f666854ab8c7f
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.3

1. Make a stock block via inserting material into galactic market
2. Put stock block on cargo shuttle
3. Send cargo shuttle to centcom and notice how the station doesn't get any money.

The stock blocks have a value on examine, it just doesn't seem to get added.

**Comment by necromanceranne** [comment]
is it possible they melted before they arrived to Centcom? You have to sell them pretty fast.

**Comment by the-orange-cow** [comment]
> is it possible they melted before they arrived to Centcom? You have to sell them pretty fast.



> This is true, when you freeze a stock's value that value only holds for 3 minutes, after which the value changes back to the current market value for that export. Potentially if the stock went liquid during transit or without noticing, it could have been sold when the price dropped to zero.

No.

Some of them may ahve melted, but I ddid this with numerous boxes.  There was zero value being added.

**Comment by Zenog400** [comment]
I've been experiencing this issue with Cargo the past couple days, but on a wider scale - I haven't been able to sell ANYTHING to add to the Cargo budget, stock blocks or otherwise. Even just sending crates back empty doesn't earn any money for the budget. I _have_ still been able to sell stuff for profit with export barcodes, including stock blocks, but that only gives me a maximum of half of the value of whatever gets sold. It also goes into my personal account instead of the cargo budget, which means a 10% markup on anything I want to buy.

**Comment by ArcaneMusic** [comment]
I stand corrected 😁 

![image](https://github.com/tgstation/tgstation/assets/41715314/f587c552-7e3f-4546-8357-c1bfa1044733)

Was able to recreate, it seems like ALL minerals are missing a sale value for some reason, so something must have touched market code in the last week or so which is effecting all minerals sale value, from blocks or otherwise.
