### ISSUE TITLE
Unfathomable Curio's shield doesn't work.

### ISSUE THREAD

**Issue by starrm4nn** [tgstation/tgstation#82068]
## Issue Summary

The shield doesn't block anything and the visual effect that screams "KICK ME, I'M A HERETIC" doesn't go away on hit.

## Round ID:

N/A

## Testmerges:

N/A

## Reproduction:

Wear the Unfathomable Curio as a Heretic, Get hit with a melee attack or shot, The shield doesn't block anything and doesn't dissipate.

**Comment by Bilbo367** [comment]
I think it has always been broken.

**Comment by necromanceranne** [comment]
It *does* work, but for it to work you need to actually hold it in hand, as it is only checking block while it is in-hand. This is an easy fix, it just needs a shield check on the item to make sure it is only ever checking to block while equipped in the belt slot.

**Comment by Bilbo367** [comment]
> t just needs a shield check on the item to make sure it is only ever checking to block while equipped in the belt slot.

What do you mean a shield check? I dont think its even checking to block while equiped.

**Comment by necromanceranne** [comment]
It's just missing some signals to make it work. That said, I think something else is not quite right with the shielded component, since I've managed to get it to work on the belt, though it's being finnicky about not working in-hand. Not that it matters terribly much, I at least have it _working_ as somewhat intended. I'll make a PR in a bit.
