### ISSUE TITLE
Antag roll disabled for normal job preferences.

### ISSUE THREAD

**Issue by Pickle-Coding** [tgstation/tgstation#82111]
Round ID: [225784](https://scrubby.melonmesa.com/round/225784)

CE was highest priority with station engineer and atmospheric technician medium. I got the warning that antagonists were disabled because of low chances of rolling the jobs, despite not failing to roll once since this year.

**Comment by Pickle-Coding** [comment]
Note that this only happened when I failed to roll CE, but rolled atmos tech.

**Comment by Jacquerel** [comment]
This isn't a bug, this message and calculation occurs based on the conditions in the round you were in.
As in this particular round it appears that you had only a small number of highly competitive rolls selected, it deprioritised you from antagonism because selecting only a small number of very popular rolls is a way to antag roll.

Probably just an unusually large number of people wanted to play CE in that round.
