### ISSUE TITLE
Slimes are significantly harder to satisfy

### ISSUE THREAD

**Issue by ZeroKelvn** [tgstation/tgstation#82283]
Reporting client version: 515.1632

## Issue Summary
This is a concern I had explicitly asked about when https://github.com/tgstation/tgstation/pull/82176 was being pull requested, because I could see this very likely causing unintended issues with slime feeding. Slimes now require three monkeys in order to grow from baby to adult, or, perhaps more accurately and dangerously, two and a half. This is somewhat compensated by the more responsive nature of the slimes, but this was a concern brought up during the merge request that was deemed unintended.

## Round ID:
[226266](https://scrubby.melonmesa.com/round/226266)

## Testmerges:
- [[Testmerge Only] [No React Randys] Removes the paralyse from shoving someone while they are knocked down](https://www.github.com/tgstation/tgstation/pull/81886)
- [Makes lua file upload work with bigger files and standardizes a few file|null](https://www.github.com/tgstation/tgstation/pull/82202)

## Reproduction:
1. Throw two monkeys at an unfed slime
2. Witness it still be hungry after the normal amount of feeding
3. Throw a third monkey at it
4. Watch it split while feeding

**Comment by Profakos** [comment]
I have ran this dozens of times, for the whole week, and they always split/evolved seconds before the last monkey died, so I thought it was fine.

But then turns out, I have multiplied the nutrition gained, based on the damage dealt with `seconds_between_ticks` a second time. And since I had no lag on my own computer, I didn't notice the issue. Fixing this right now.
