### ISSUE TITLE
Cult EMP spell bypasses null magic.

### ISSUE THREAD

**Issue by excalisword** [tgstation/tgstation#82446]
Reporting client version: 514.1589

## Issue Summary
Null magic does not seem to protect you from EMPs caused by the cult EMP spell. I found this out by being an android chaplain with the null rod on person while the cult EMP spell was used near me.

## Round ID:
[226635](https://scrubby.melonmesa.com/round/226635)

## Testmerges:
- [Creates a "busy" animation for players](https://www.github.com/tgstation/tgstation/pull/82416)

## Reproduction:

1. Be an android.(Haven't seen what happens to energy based weapons when on the Chaplain's person, but most likely EMPs affect those on them as well.)
2. Grab a form of anti magic.
3. Be near a cult emp spell when its used.
4. Get EMPed.

**Comment by moocowswag** [comment]
Because the emp itself isnt magic its an emp...one time brick mortar was an android chaplain and i used spirit realm to meta it out, and told the players i summoned to just go emp him



Being an android had downsides regardless if you are anti magic or not, you get flat damage reduction as the upside, unless the removed that in which dont go android sect lol.

**Comment by excalisword** [comment]
I thought androids didn't have flat damage reduction anymore?

**Comment by moocowswag** [comment]
Then maybe look into nerfing their downsides/adding more counterplay to emp.

**Comment by necromanceranne** [comment]
alternatively, just have the spell call an isolated emp on every target in range, and check for antimagic there, rather than emp pulse from the caster

**Comment by Sealed101** [comment]
agree on this not being a bug, even if it feels a bit cheesy
