### ISSUE TITLE
You can cremate the nuclear operatives' nuke

### ISSUE THREAD

**Issue by Nobelium-XVIII** [tgstation/tgstation#82497]
## Issue Summary
As it says on the tin, you're able to cremate the nuclear operatives' nuke...

## Round ID:

N/A, Tested on a local branch (https://github.com/Nobelium-XVIII/tgstation if it matters), up to date as of 4/6/2024

## Testmerges:
N/A

## Reproduction:
1: Put the nuclear operative's nuke into the crematorium
2: Activate the crematorium
3: The nuke is now gone

**Comment by san7890** [comment]
It sucks but I think the nuke should be considered a valuable item that you shouldn't let the station get ahold of (since they can run it off the z-level anyways)- we have the self-destruct kiosk for a reason too.

Do inform me if you disagree but I don't mind the way it is currently. Secure dat fukkin disk and take care of dat fukkin nuke

**Comment by ATH1909** [comment]
aren't the codes for the nuke and the nuke core separate?

**Comment by Deadgebert** [comment]
should have anchored it

**Comment by Nobelium-XVIII** [comment]
> aren't the codes for the nuke and the nuke core separate?

they are

**Comment by san7890** [comment]
Hm, maybe if the nuclear operative nuke gets deleted or Z_LEVEL_CHANGED then we should give the self-destruct codes to the nukies then

**Comment by the-orange-cow** [comment]
If they cremated it, it probably wasn't anchored, at which point you could just move it off the zlevel anyway.

**Comment by gueba14** [comment]
this is one of the few ways a quick and smart crew memeber could stop the nuke beisdes metalgen, dusting and trowing into space

**Comment by san7890** [comment]
yeah i'm really thinking that this should be chalked up to "skill issue", even though the code probably doesn't explicitly account for it the current gameplay loop (getting rid of dat fukkin nuke) accomodates for it well enough. i still like my self-destruct failover idea though, give nukies a bit more of an extra challenge to redeem that skill issue.

**Comment by SethLafuente** [comment]
The nuke can be functionally destroyed in many ways I don't see why we should remove this the crematorium has had the consistent ability to destroy anything that is put within it.

The station still has a working self destruct machine that mostly cannot be destroyed so this dosent inherently ruin nukies chances for winning also just anchor the nuke.

I do admit we have some issues with how the nuclear systems works to begin with nuclear disk having a god barrier with the ability to instantly respawn after destroyed.

In my opinion nuclear disk should be able to be destroyed but it should have two protocols if it's not within the station to explode automatically instead of it teleporting the second protocol being once no nuclear disk is detected in the station one should be send in a drop pod and announced to everyone.

For the nuke if someone wants to make a balance change and make it so if the nuclear operatives nuke is destroyed in the same fashion as the disk the syndicate sends a new one on their base by drop pod I don't think it would be very opposed. 

Non the less I don't think this is a bug everything seems to be working as intended.
