### ISSUE TITLE
Admin outfit drops spawn contents on ground

### ISSUE THREAD

**Issue by lessthnthree** [tgstation/tgstation#82705]
## Issue Summary

I think PR https://github.com/tgstation/tgstation/pull/82494 fixing a storage size bug breaks the admin outfit, which was using that bug as a feature to keep all it's stuff in the MODsuit.

Now equipping the admin outfit drops all that stuff on the ground, with no storage to put it in.

https://github.com/tgstation/tgstation/assets/83487515/3c5290fd-f75e-40fe-a316-ad1e0d229b24

## Reproduction:

Change into admin outfit

**Comment by iansdoor** [comment]
Box of materials that does that.

**Comment by AdipemDragon** [comment]
Gotta love the debug box exploding like that

**Comment by msgerbs** [comment]
That's weird, the box should be able to hold this shouldn't it? https://github.com/tgstation/tgstation/blob/a300ec3f7bbc616b4342f0b7ae12cd1f58100e96/code/game/objects/items/storage/boxes/engineering_boxes.dm#L29

**Comment by msgerbs** [comment]
So the issue here is that `PopulateContents` happens in `/obj/item/storage/Initialize`, which gets called *before* the size of the bag gets changed. But it also can't be done before the call to parent because then the storage doesn't exist at all.

1. atom_storage gets created
2. PopulateContents is called
3. Each item that gets created gets spit out for being too busy
4. The storage size gets changed to be able to hold those items, but it's too late now
