### ISSUE TITLE
Slimes attack and try to eat slimepeople

### ISSUE THREAD

**Issue by Follint** [tgstation/tgstation#83324]
## Issue Summary
While being transformed in any slimeperson type you expect to not be attacked by your jelly pals, but they do. And they also try to eat you even when not that hungry. Started after the refactor in #82176

## Reproduction:
1. Be a slime person
2. Come near any non-befriended slime or make one with a grey extract
3. Get attacked and/or eaten

**Comment by Profakos** [comment]
This is caused by me forgetting to port the faction check to the hunt behaviour, sorry! However, reimplementing this is unclear. I dont want to reimplement the old behaviour, which circumvented the dedicated faction checking proc, by removing the neutral faction from slimes and compared what was left. 

How much trouble would it cause, if slimes lost the neutral faction, I wonder.

**Comment by Profakos** [comment]
It looks like, the main issue would be aggressive Neutral mobs would attack them, along with shuttle turrets.
