### ISSUE TITLE
Portable Chemical Mixer's ui doesn't open when equiped on the belt slot

### ISSUE THREAD

**Issue by xJavaMaster** [tgstation/tgstation#83344]
## Issue Summary
When I try to open the Portable Chemical Mixer's ui when it's closed, the ui doesn't pop up.

## Round ID:
[229116](https://scrubby.melonmesa.com/round/229116)

## Reproduction:
1. Equip the Portable Chemical Mixer
2. Ctrl + click to close it
3. Left click on it
4. Text says "Closed!" instead of opening the ui like stated in the wiki (https://tgstation13.org/wiki/Guide_to_chemistry#Portable_Chemical_Mixer)

**Comment by SyncIt21** [comment]
The wiki is outdated. See #79710 for new instructions

**Comment by xJavaMaster** [comment]
I got the ui to open but only when the Portable Chemical Mixer is in my hand as per the instruction of Synclt21, the bug happens when it's on the belt slot.

**Comment by SyncIt21** [comment]
> the bug happens when it's on the belt slot.

This isn't a bug and is intentional because the behavior was changed to only open when in hand.  This was done to lock players hand up so they cant do anything else with them while mixing reagents. This is now a feature request which isn't meant for the issue tracker.

Please close the issue as the bug has now been resolved
