### ISSUE TITLE
Trait `TRAIT_STRONG_GRABBER` is useless for mobs other then carbon but used in `/mob/living/basic/spider/giant/ambush`

### ISSUE THREAD

**Issue by Gaxeer** [tgstation/tgstation#83485]
## Issue Summary

Trait `TRAIT_STRONG_GRABBER` is useless for mobs other then carbon but used in `/mob/living/basic/spider/giant/ambush`.
Was changed in: https://github.com/tgstation/tgstation/pull/81097 , file `living_defense.dm`, lines 241-242

## Round ID:

Local server with latest /tg/ codebase

## Reproduction:

1. Spawn `/mob/living/basic/spider/giant/ambush` or any other non-carbon mob with `TRAIT_STRONG_GRABBER`
2. Try grab mob
3. You just start pulling

**Comment by Gaxeer** [comment]
@MrMelbert sorry for mention. But I want to take handle of this and need to understand, why you made grab strengthening only available for `carbons`? There is a `max_grab` var, we can make `basic` mobs only be able to grab passively and make exception for some of them. 
Thank you for your time

**Comment by MrMelbert** [comment]
I had no idea `max_grab` was a var

That line was put there because `grab` was moved from human + alien level to the living level, which allowed cyborgs and corgis to neck-grab people. 

You can remove that arbitrary check but you just gotta make sure all the right mobs have the right levels. I would suggest making `max_grab` default to `GRAB_PASSIVE`, setting it to `GRAB_KILL` for humans, and then aggressive for whatever else needs it (spiders)

**Comment by Gaxeer** [comment]
Thank you. Will do
