### ISSUE TITLE
bolas dont work when thrown 

### ISSUE THREAD

**Issue by kidgenius703** [tgstation/tgstation#83577]
Reporting client version: 515.1639

## Issue Summary
Bolas break when the victim grabs a item

## Round ID:
[229678](https://scrubby.melonmesa.com/round/229678)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)

## Reproduction:
Its easily dumb, throw a bola at someone, the bola victim picks a item out of their bag or inventory or pocket literally any storage, now the bola victim can move freely with no slowdown at all.

**Comment by necromanceranne** [comment]
Works exactly as described. Sucks to be sec at the moment I guess.

**Comment by GoblinBackwards** [comment]
Not sure how to go about fixing it but hopefully this can help.

Items only get included in the speedmod calculation if they are equipped, which means they need the IN_INVENTORY flag.
https://github.com/tgstation/tgstation/blob/f6c44181cea46839d205848ff4ed4f5c6d093b1a/code/modules/mob/inventory.dm#L394-L401

The equipped proc adds this to the bola when it hits a player and equips onto them.
https://github.com/tgstation/tgstation/blob/f6c44181cea46839d205848ff4ed4f5c6d093b1a/code/game/objects/items.dm#L728-L745

The after_throw proc removes this flag from the item as a callback after being thrown.
https://github.com/tgstation/tgstation/blob/f6c44181cea46839d205848ff4ed4f5c6d093b1a/code/game/objects/items.dm#L862-L868

The problem is, the after_throw callback is running after the bola already hit the player, so its removing the flag after the bola has already been equipped to the hit player so it isn't included in the speedmod calculations. This means that as soon as update_equipment_speed_mods gets called again (usually by the player picking up or dropping an item), their speed mods will be recalculated with the bola not counted as an equipped item.
