### ISSUE TITLE
Spy item slot bug 

### ISSUE THREAD

**Issue by WarerBrow** [tgstation/tgstation#83742]
Reporting client version: 515.1639

## Issue Summary

Stealing an item which you are wearing on your item slot as a spy makes that slot bugged. Instead of stolen item there appears a strange black icon, which you cannot examine (it shows as a "slot"), but when trying to put something on it shows the message about wearing that exact non-existent item.
![image](https://github.com/tgstation/tgstation/assets/106118256/37a007a9-53e6-45d3-b90c-69dd2d990f5d)
(look at the belt slot and message in chat about pipe dispenser)

## Round ID:
[230038](https://scrubby.melonmesa.com/round/230038)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Removes logging each lua function called on the dm side of things.](https://www.github.com/tgstation/tgstation/pull/83483)

## Reproduction:

1. Put something on your belt as a spy.
2. Steal this thing by right clicking it with PDA.
3. Enjoy the BELTLESS GAMEPLAY...

**Comment by WarerBrow** [comment]
Probably should've tried to re-equip jumpsuit though...

**Comment by projectkepler-ru** [comment]
This also happens if you manage to somehow force yourself to have an item that occupy a slot via admin command, sometime ago I was able to force myself to have an item that occupy both pocket at once

This mostly occur in downstream of TG where you can get roundstart item that occupy your pocket slot and it conflict with your job slot
