### ISSUE TITLE
The loss of memory after being kidnapped away is inconsistent with other kidnapping antags

### ISSUE THREAD

**Issue by iansdoor** [tgstation/tgstation#83760]
I was asking other admins about the thoughts of someone being kidnapped by a contractor, they are supposed to forget.
This is the message left to anyone kidnapped.
```
Your head pounds... It feels like it's going to burst out your skull!
Your eyes sting a little.
Your head pounds...
Your eyes sting a little.
A million voices echo in your head... 
"Your mind held many valuable secrets - we thank you for providing them. 
Your value is expended, and you will be ransomed back to your station. 
We always get paid, so it's only a matter of time before we ship you back...

```
Heretic, you have to forget
Abductors, you have to forget
Contractor for the spider clans, doesn't specific that.

**Comment by Crushtoe** [comment]
I asked around on Discord after the round where this was a problem and there seemed to be a user consensus (obviously that’s not admins, I’m just saying this to say what the end-user understanding has been) that contractor kidnappings aren’t meant to have a forgetting element, and people have gotten revenge on their contractor before.

If someone wants to change contractor kidnappings to have a forgetting part, go ahead; but I’d like to mention that as traitors, a contractor is actively choosing to pick up the contractor job. They have the ability to hide their identity like anyone else, they choose to pick up this activity instead of it being a built in part of what they rolled a la abductor and heretic, and they play it as a risk/reward for the benefits of contracting. It’s not just abductor: crew edition.

**Comment by TheVekter** [comment]
Let me poke some other admins and see if that's how we want to handle it, but to my knowledge, you don't forget upon being kidnapped.
