### ISSUE TITLE
EMAG Changes Needed

### ISSUE THREAD

**Issue by ZephyrTFA** [tgstation/tgstation#84110]
EMAGs need to have a chance to burn out and become non functional when used by a non-traitor.
The chance should scale and after X uses must burn out.
I recommend X being 4, I will not consider higher although I will consider lower.

**Comment by Sadboysuss** [comment]
does this give gbp?

**Comment by tralezab** [comment]
👍 👍 👍
huge design space limiter. we can have zero effects that benefit the traitor on emag instead of hurting the station on emag because any use of the emag by traitors will be better used by security.

**Comment by tralezab** [comment]
> does this give gbp?

you'll be the shah of tgstation brother (you'll probably get a no-gbp tag so it doesn't cost you)

**Comment by ZephyrTFA** [comment]
I will award one (1) gbp

**Comment by ATH1909** [comment]
This was brought up on the Discord in the context of this enabling more positive emag effects that won't be able to be spammed by sec.

IMO, this isn't something that warrants a broader emag nerf. New emag effects should generally be things like making machines fucked up and evil and not things that just give you free stuff.

If only these new benefits had the burnout chance (with it being boosted to compensate), I'd be down for that.

**Comment by tralezab** [comment]
> This was brought up on the Discord in the context of this enabling more positive emag effects that won't be able to be spammed by sec.
> 
> IMO, this isn't something that warrants a broader emag nerf. New emag effects should generally be things like making machines fucked up and evil and not things that just give you free stuff.
> 
> If only these new benefits had the burnout chance (with it being boosted to compensate), I'd be down for that.

free stuff when used by traitors is interesting especially since it requires keeping the emagged machine a secret. it's a problem when security can then use the emagged machine for their benefit. we had to say bye bye to null crates because security can use emags better than traitors. we continually have to reject perfectly fine sabotage ideas and traitor plans because security can abuse the emag effect without any risk of getting caught for as many station members as they want for the rest of the round (as long as the machine isn't destroyed)

> I will award one (1) gbp

the shah of tgstation......

**Comment by MrMelbert** [comment]
Feature requests are not handled in the repository. The best place to discuss these ideas would be on the /tg/station 13 forums here: https://tgstation13.org/phpBB/viewforum.php?f=9&sid=5153c1c704a4fb1006bf7a265e45e03f
