### ISSUE TITLE
Most scientific papers boost nonexistent nodes

### ISSUE THREAD

**Issue by Profakos** [tgstation/tgstation#84153]
## Issue Summary

Most of the boosts that scientific papers still refer to nodes that no longer exist. 

## Round ID:

N/A

## Testmerges:

N/A 

## Reproduction:

Example, search for "micro_bluespace", see that it does not exist as a tech web node ID.

**Comment by Time-Green** [comment]
Man we really need to get rid of the string id’s

**Comment by MTandi** [comment]
I have updated the boostable_nodes, but have no clue what the points/gains and multipliers mean and how to balance them out. The vars are also terribly documented.

Need help, if we even need this.

This mechanic looks extremely unintuitive not just from the code but also UX perspective, I'm considering to just unlock a random node from the list on paper upload instead of all this point trickery.
