### ISSUE TITLE
Inventory deletes all the mobs looking at it when it gets deleted

### ISSUE THREAD

**Issue by MrMelbert** [tgstation/tgstation#84447]
## Issue Summary

`storage_interfaces` is an assoc list of [mob] to [storage interface]

https://github.com/tgstation/tgstation/blob/838742297ee2cd692362c42b8bccde8a5e307376/code/datums/storage/storage.dm#L998-L999

When storage datum is destroyed it qdels all the mobs in the list instead of all the storage interfaces

https://github.com/tgstation/tgstation/blob/838742297ee2cd692362c42b8bccde8a5e307376/code/datums/storage/storage.dm#L148

**Comment by SyncIt21** [comment]
It should be `QDEL_LAZYLIST_VAL_ASSOC` to delete only values and not keys

**Comment by GoldenAlpharex** [comment]
That's a pretty epic bug right there

**Comment by ZephyrTFA** [comment]
lol

**Comment by zoomachina** [comment]
I'm sure it's caused by #84160 , as a side note there's also this weird visual bug
![image](https://github.com/tgstation/tgstation/assets/97964454/89c47357-e8a7-4acb-9530-987fed7f7e4f)

**Comment by lessthnthree** [comment]
at least this one leaves your species intact...

**Comment by iprice** [comment]
Something weird going on with the storage interfaces var perhaps, which might explain why the visual bug also happens?

New box looks like this (in its /datum/storage)
![image](https://github.com/tgstation/tgstation/assets/3789327/68a25da9-4a99-4e8d-a517-e3194a055ade)
I open the box
![image](https://github.com/tgstation/tgstation/assets/3789327/909d112a-4bb9-4467-9b79-fd6ee1056f24)
Mob to storage interface.  If i close the box, and move away from it entirely,
![image](https://github.com/tgstation/tgstation/assets/3789327/86bbe91c-295a-49ce-ad7b-11f0c483e3ad)

I dunno if thats right, I dont really know the internals of byond's list/map structure but that last layout feels wrong (and maybe why it destroys a mob instead of just an interface?)

**Comment by GPeckman** [comment]
Fuckup of the year 2024 anyone?

**Comment by lessthnthree** [comment]
> Fuckup of the year 2024 anyone?

Think so. We haven't had one in a while.

**Comment by SmArtKar** [comment]
OOPS
