### ISSUE TITLE
The icebox cytology equipment locker lacks a kitchen knife.

### ISSUE THREAD

**Issue by plutori** [tgstation/tgstation#84466]
Reporting client version: 515.1640

## Issue Summary

As in the title. The icebox cytology locker should have a kitchen knife like Metastation does so that way cytologists can cut up monkeys for protein, since protein is used in like 98% of cytology recipes.

## Round ID:
[231341](https://scrubby.melonmesa.com/round/231341)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Some alt & ctrl click improvements](https://www.github.com/tgstation/tgstation/pull/84203)
- [Moves tool use back higher in the chain, but makes it so tool acts are only called on non-combat-mode](https://www.github.com/tgstation/tgstation/pull/84083)

## Reproduction:

Open the locker in xenobiology.

**Comment by TheVekter** [comment]
I need GBP sooooo

**Comment by EuSouAFazer** [comment]
Not an issue. 
As of https://github.com/tgstation/tgstation/pull/84235 the cytologist starts with protein in their locker; butchering monkeys isn't needed anymore. + the cytology maps were made to intentionaly have pros and cons between themselves, some maps are okay to skip on not-integral equipment like the knifes now are.

The real problem here is that Icebox does not have a growing vat and the plumbing RCD was removed from the locker; it's literally impossible to do cytology on icebox right now.

**Comment by Sadboysuss** [comment]
fixed by https://github.com/tgstation/tgstation/pull/84697
