### ISSUE TITLE
Blob cannot spread over space

### ISSUE THREAD

**Issue by zoomachina** [tgstation/tgstation#84618]
## Issue Summary
Can't manually spread blob tiles onto space, it claims there are no adjacent blobs to it.

## Reproduction:
1. Spawn as blob
2. Try to spread over space
Possibly related that the space was caused by an explosion

**Comment by DATA-xPUNGED** [comment]
Will try reproducing this at home if no other issue manager did it by then

**Comment by DATA-xPUNGED** [comment]
This bug is weirder than I thought; I max capped myself as a blob on runtimestation. The space tiles inside a previous area and outside of it are the same, so it's unrelated to an explosion.

Trying to spread to a space tiles tries attacking it instead at random, and sometimes just spreads normally, this is probably related to attack chain heck

**Comment by Jewelry-x** [comment]
This is by design, there is an 80% chance that spreading into space will not expand the blob. I imagine whoever implemented this did it for the purpose of balance, as the blob freely traversing space to reach new areas is pretty strong when the vast majority of the crew does not have access to space proof equipment.

**Comment by DATA-xPUNGED** [comment]
![image](https://github.com/user-attachments/assets/a0d9bb91-ae17-450c-8299-809ed5d5f00d)
As shown by Jewelry-x this is apparently intended, very weird design decision, though, i'll tell you that.

**Comment by zoomachina** [comment]
We as a society should know better
