### ISSUE TITLE
Bloody footprints are a bit overtuned

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#84727]
Reporting client version: 515.1641

## Round ID:
[231720](https://scrubby.melonmesa.com/round/231720)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Offset render relays for non-offsetting planes to match highest matching render plane](https://www.github.com/tgstation/tgstation/pull/84184)
- [tgui: custom font bluescreen fix, typescript'd](https://www.github.com/tgstation/tgstation/pull/84601)

## Reproduction:
![image](https://github.com/tgstation/tgstation/assets/62606051/867802ea-6540-4551-9995-59d04720d64e)
#84665 made footprints carry for more tiles before they degrade but ever since then even a small amount of blood just leads to massive trails like this going everywhere. When before it would trail off it now just looks ugly

**Comment by MrMelbert** [comment]
For one I kinda doubt this was only caused by a "small amount of blood", I would presume someone was actively bleeding somewhere

For two this is a quirk of how bloody footprints works, if your feet are bloody are you step on existing bloody footprints, it'll just transfer a small amount of blood, meaning you can really draw out the trail

Fixing this requires a fair bit of tweaking to the component / blood decals themselves than just adjusting the value of a multiplier

Shown:
Left, a 50 bloodiness pool of blood
Right, a 50 bloodiness pool of blood that I refreshed back to 50 every time I stepped in it again

![image](https://github.com/tgstation/tgstation/assets/51863163/68745505-22da-4b2c-894b-c545a9d1fc92)

**Comment by Sadboysuss** [comment]
bloody footprints probably shouldn't also bloody your prints

**Comment by LemonInTheDark** [comment]
This isn't a bug, they've always been real bloody

**Comment by Sadboysuss** [comment]
> This isn't a bug, they've always been real bloody 

What happened in rounds was hallways were filled bloody footprints at all times because (I assume) footprints bloodied your footprints and left new bloody footprints that led to new bloody footprints and repeated the cycle. So infinite bloody footprints.
