### ISSUE TITLE
Metalgen changes stats of items with the corresponding material

### ISSUE THREAD

**Issue by EDGELORD333** [tgstation/tgstation#84992]
I think it would be more funny if the metalgen was capable of turning day to day items more robust like a plastic banhammer into a viable weapon or strong weapons like the fire a e into a crappier version of it Self like a plastic fireaxe!

**Comment by Time-Green** [comment]
Hi! This is the issue report section. For feature idea’s, please check out the idea section on the forums!

**Comment by Time-Green** [comment]
Also on your suggestion: mechanics like that are extremely risky. We already change some properties like flammability or making items radioactive, but allowing it to improve combat potential is a very easy way to break the sandbox and is generally frowned upon to implement.

The wizard fantasy affixes sorta do this already, but we don’t give people controle over it and also I mean it’s wizard

**Comment by EDGELORD333** [comment]
Huh but isn’t metalgen  already a hard to make item cause the recipe
changes every 3 day?  Would it really mess with the Balancing?

Time-Green ***@***.***> (időpont: 2024. júl. 15., H, 22:25)
ezt írta:

**Comment by Time-Green** [comment]
When something becomes really powerful, it’ll be a lot less rare. I don’t see why we need to play with fire at all here, but I’m just one person.

 If you can write down your actual idea’s (on the forums) instead of just a general vibe, we (and/or others) can discuss it further. Don’t expect anyone to code it though, it’s exceptionally rare for coders to code someone elses idea’s

**Comment by EDGELORD333** [comment]
Alright kinda new to this  git hub thing and i’m not really Great with
words but i try

Time-Green ***@***.***> (időpont: 2024. júl. 15., H, 22:42)
ezt írta:
