### ISSUE TITLE
Shuttle Dust Meteors spawn inside the shuttle

### ISSUE THREAD

**Issue by DaydreamIQ** [tgstation/tgstation#85030]
Reporting client version: 515.1641

## Round ID:
[232214](https://scrubby.melonmesa.com/round/232214)

## Testmerges:
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [Ghosts once again can see people's true names and roundstart jobs](https://www.github.com/tgstation/tgstation/pull/84951)

## Reproduction:
![image](https://github.com/user-attachments/assets/c5e8df64-ac60-460c-b4b7-d17849c4a5db)
Shuttle rolled dust meteors as its danger thing and several people got bodied by them spawning on top of them

**Comment by Rhials** [comment]
Well, I'm willing to wager this is related to #84994.

The Nebulastation shuttle seems to be misconfigured for meteor-adjacent shuttle events, in a catastrophic manner.

Paging @KikoWen0 for input on their shuttle design.

**Comment by Inari-Whitebear** [comment]
> Well, I'm willing to wager this is related to #84994.
> 
> The Nebulastation shuttle seems to be misconfigured for meteor-adjacent shuttle events, in a catastrophic manner.
> 
> Paging @KikoWen0 for extra eyes on this, in case this is a nebula-localized issue.

I think it's something about the test merge, or possible shuttle travel direction? Since I had it happen on Birdshot too when I had nebula merged

But yeah, it's the same thing, in my tests the safe dust event spawned them there too, just like it does with the meteors
And they use the same event/spawning algorithm
