### ISSUE TITLE
The boulder refinery system just refused to properly process, accept (except handloaded) and shift boulders along the conveyor belt system

### ISSUE THREAD

**Issue by necromanceranne** [tgstation/tgstation#85081]
Reporting client version: 515.1640

## Issue Summary

The roundstart refinery system completely ceased to work. Boulders wouldn't move, and when inserted, would spit out the boulder without actually seemingly processing it properly even when it was at the end of the steps.

A new refinery when constructed seemed to begin operating entirely fine. But the original one simply refused to operate even when reconstructed.

## Round ID:
[232291](https://scrubby.melonmesa.com/round/232291)

## Testmerges:
- [Ghosts once again can see people's true names and roundstart jobs](https://www.github.com/tgstation/tgstation/pull/84951)

## Reproduction:

I wouldn't have a clue. Pretty sure power was lost, and restarting the conveyor belt did not fix the issue once it was back on. I think gravity was also briefly lost.

**Comment by ArcaneMusic** [comment]
This is particularly bad because it completely bricks boulder processing on Deltastation as there is not dedicated roundstart foundry on that map.

Good thing we wouldn't have a large influx of players who would be forced to exclusively play on deltastation or something crazy right now, r-right anon?

(Fuck)

More seriously, it doesn't appear to be runtiming, so there must be something going on here that's completely breaking the logic, as I was seeing it appear in conjunction with #84051 at the same time, with both cases causing boulders to stop behaving with their standard processing behavior and then locking in behavior as though they were stuck on a conveyor belt forever.

**Comment by Metekillot** [comment]
Did you examine the boulders that weren't processing? Occasionally, a boulder with 0 steps left will somehow end up in the chain and that fucks it pretty hard.

**Comment by ArcaneMusic** [comment]
What's worse is that I've compiled the code twice now today trying to cause this to occur on a new setup using deltastation as the backbone, and I've failed both times to re-create the issue, but I know it does exist at the least. I'll need to look for more consistent recreation steps perhaps?

**Comment by ilikesaying** [comment]
The problem seems to be linked to the boulder machines that come pre-built, such as the ones from the boulder beacons, as disassembling and reassembling them fixed the issue.
