### ISSUE TITLE
Magicarps involuntarily use their magic

### ISSUE THREAD

**Issue by lnGoror** [tgstation/tgstation#85504]
Reporting client version: 515.1636

## Issue Summary

Magicarps involuntarily shoot their spells.

## Round ID:
[233079](https://scrubby.melonmesa.com/round/233079)

## Testmerges:
- [[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://www.github.com/tgstation/tgstation/pull/85392)

## Reproduction:

Spawn in as a magicarp, click anything that is further away than 1 tile and the bolt will go off even without having it selected to cast.

**Comment by Jacquerel** [comment]
Seems to not be a bug, was introduced as intended behaviour because it'd be a pain in the ass to toggle a spell with a 2 second cooldown every time you want to cast it. Mobs which only have one or two abilities generally speaking _should_ just use them on click. 
We could probably make it only happen in combat mode though.
