### ISSUE TITLE
(Wallening) RCD menu issues

### ISSUE THREAD

**Issue by excalisword** [tgstation/tgstation#85561]
## Issue Summary
I've found that the RCD menu cannot select to create vertical airlocks and can only create horizontal ones. Also, the sprites for some of the RCD options have been replaced with floors.

## Round ID:
[233256](https://scrubby.melonmesa.com/round/233256)

## Testmerges:
[#85491: 'Wallening [IDB IGNORE] [MDB IGNORE]' by LemonInTheDark at commit 5637441acf](https://www.github.com/tgstation/tgstation/pull/85491)

## Reproduction:
![image](https://github.com/user-attachments/assets/c2bb8563-59e5-49cf-a339-07c860319b94)
![image](https://github.com/user-attachments/assets/41147feb-fb80-4701-bd4b-6cc6780ef79b) (All of these were made via RCD)

**Comment by Mothblocks** [comment]
Also weird that they appear to be showing the older sprites

**Comment by excalisword** [comment]
> Also weird that they appear to be showing the older sprites

Interestingly enough, all the airlocks that still have sprites are the ones that I've detailed in my other issue report.
https://github.com/tgstation/tgstation/issues/85562

**Comment by Kylerace** [comment]
the icons issue is because new door icons arent 32x32, the reason why only half of them look like floors and the other half look like old doors is because half of them are randomly set to new icons at compile time and the other half to old icons (and set to correct icons at runtime somewhere). we'll need 32x32 door icons for uis
