### ISSUE TITLE
Lizards no longer gain proper insulation from wearing winter coats.

### ISSUE THREAD

**Issue by EnterTheJake** [tgstation/tgstation#85575]
Reporting client version: 515.1642

## Issue Summary

Very likely a consequence of this pr https://github.com/tgstation/tgstation/pull/85401.

Insulation doesn't seem to do much for lizards anymore, you used to be able to go outside icebox  and i think space too, without getting cold, since the mentioned PR got merged that's no longer the case.

## Reproduction:

1) Be a lizard on Icebox
2) put a winter coat on
3) go outside
4) freeze to death.

**Comment by Sadboysuss** [comment]
<details>

![image](https://github.com/user-attachments/assets/49696149-1803-47c6-a572-8cb3341b003c)

</fuck>

**Comment by munthie** [comment]
i can attest for this the mining suit doesnt help either, only the space suit actually protects you from freezing to death

**Comment by BlueMemesauce** [comment]
The PR has been reverted, but it's not really a bug. Lizards are meant to be cold blooded and insulation wouldn't help a cold blooded species. Insulation clothing helps warm blooded species maintain body temperature because they generate body heat. The clothing traps the heat and reduces heat loss, allowing the body to keep up in colder temperatures. Meanwhile cold blooded species do not generate heat, so insulation is doing nothing for them except slow down the rate they become colder once they go out into the snow from the station. Therefore, it makes sense that insulation wouldn't work for lizards and only space suits would work.
