### ISSUE TITLE
Purchased crates cannot be renamd

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#85628]
## Issue Summary
Crates purchased from a departmental order cannot be renamed after you remove the electronics.

## Round ID:
local

## Reproduction:
1. Purchase departmental crate
2. Deliver and open the crate
3. Remove the electronics from the crate, maybe even recolor it
4. Use pen while it is closed
5. "Not yours to rename!"

**Comment by SyncIt21** [comment]
It's intentional. In order to rename the crate you must first own it(have your ID registered with it).This was an department owened crate which isn't yours hence access denied. 

Try swiping your ID/PDA on the crate when closed but unlocked and select "Personal" to claim it first 

This was done so people don't go around renaming department closets and confusing everyone what that closet/crate is supposed to be(especially if it doesn't have a paint  job like a regular closet) unless it's they own it.

**Comment by Sadboysuss** [comment]
> This was an department owned crate

__Was__. I completely agree with you here if the crate has a card reader or airlock electronics, but I specifically removed both of those. The crate isn't owned by anyone because it had no electronics or card reader.
