### ISSUE TITLE
Moths are blinded by welding tools even with double protection

### ISSUE THREAD

**Issue by Tw3n7y** [tgstation/tgstation#85798]
## Issue Summary
Moths are blinded by welding tools even with double protection

## Round ID:
[234802](https://scrubby.melonmesa.com/round/234802)

## Reproduction:
Equip welding goggles and mask as a mothperson and use welding tool on wall, borg, mech, etc.

**Comment by Sadboysuss** [comment]
https://github.com/user-attachments/assets/b6e0decb-c970-4891-8c71-68e9400b8b36

https://github.com/user-attachments/assets/102b5ccf-26dc-4f68-8cce-235934c74850

https://github.com/user-attachments/assets/947a092a-1927-4b4d-984b-ba913589e136

https://github.com/user-attachments/assets/2213a25a-b602-4e57-9faf-78003f7974d1

Unable to reproduce, please provide a video of the issue or new reproduction steps, otherwise this will be autoclosed in 7 days

**Comment by ATH1909** [comment]
are you certain you weren't using the collectable variant of the welding helmet?

```
/obj/item/clothing/head/collectable/welding
	name = "collectable welding helmet"
	desc = "A collectable welding helmet. Now with 80% less lead! Not for actual welding. Any welding done while wearing this helmet is done so at the owner's own risk!"
	icon = 'icons/obj/clothing/head/utility.dmi'
	worn_icon = 'icons/mob/clothing/head/utility.dmi'
	icon_state = "welding"
	inhand_icon_state = "welding"
	lefthand_file = 'icons/mob/inhands/clothing/masks_lefthand.dmi'
	righthand_file = 'icons/mob/inhands/clothing/masks_righthand.dmi'
	clothing_flags = SNUG_FIT
```
