### ISSUE TITLE
Layering on felinid ears is broken

### ISSUE THREAD

**Issue by Bm0n** [tgstation/tgstation#86453]
### Client Version:

515.1642

### Issue Summary:

The layering on felinid ears is broken. It seems like only the inner ears are layered above the hair, this is very noticeable on the side sprite and when you are wearing a hat.

### Round ID:

[236584](https://scrubby.melonmesa.com/round/236584)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)

### Reproduction Steps:

Be felinid

Have hair

Look at the ears

**Comment by 00-Steven** [comment]
also cc @Time-Green 

I believe this is due to, well:

It seems that previously the outer colourable part of the cat ears would be on `BODY_FRONT_LAYER` for their front, left, and right sprites, and `BODY_BEHIND_LAYER` for their back sprites, where the inner ears were also on `BODY_FRONT_LAYER` for front, left, and right.
Currently, however, it seems we use a mutant bodypart that defines the inner ears to be on `BODY_FRONT_LAYER` while the outer ears are on `BODY_ADJ_LAYER` for every direction, which is below the `HAIR_LAYER`. Meaning the outer ears render behind the inner ears in all directions, even the front.
![image](https://github.com/user-attachments/assets/a3ca59c3-948e-40f2-b485-57ec07fa7050)
I'm unsure how this could be made to work with the current logic, given both the inner ears And the outer ears have to be on `BODY_FRONT_LAYER`, and I'm not sure if the `/datum/bodypart_overlay/mutant` can easily handle that.
It's also currently using that layer distinction to define which sprite to colour:
https://github.com/tgstation/tgstation/blob/a56864644780db285e82afb43ef6bc10e7b1fb63/code/modules/surgery/organs/internal/ears/_ears.dm#L151-L152
