### ISSUE TITLE
Selecting ears is gone for felinids

### ISSUE THREAD

**Issue by Bm0n** [tgstation/tgstation#86452]
### Client Version:

515.1642

### Issue Summary:

You can no longer select your ear type in the character preferences for felinids. The option is gone.

![image](https://github.com/user-attachments/assets/dc82e69b-e3e7-4193-b7ae-d71167e87198)

### Round ID:

[236584](https://scrubby.melonmesa.com/round/236584)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)

### Reproduction Steps:

Open char prefs.

No ear selection.

**Comment by Sadboysuss** [comment]
> Also, I think there is some weird overlaying issue where the hair is layered above the ears at least on the side sprite? only the inner part of the ears are showing

This should be a separate issue report, I didn't even notice it at first

**Comment by Bm0n** [comment]
> This should be a separate issue report, I didn't even notice it at first

maybe ye. ill make edit it out and make another issue report

**Comment by 00-Steven** [comment]
I think the selection not being present may be due to the fact that the ears preference checks for:
https://github.com/tgstation/tgstation/blob/ad9a493227befe5bf84e540b7ab140d3ae67c443/code/modules/client/preferences/species_features/felinid.dm#L23
which only checks whether it's in `mutant_organs`: 
https://github.com/tgstation/tgstation/blob/ad9a493227befe5bf84e540b7ab140d3ae67c443/code/modules/mob/living/carbon/human/_species.dm#L1410-L1416
while the ears for felinids are actually `mutantears`, not `mutant_organs`:
https://github.com/tgstation/tgstation/blob/ad9a493227befe5bf84e540b7ab140d3ae67c443/code/modules/mob/living/carbon/human/species_types/felinid.dm#L8
