### ISSUE TITLE
Cyborg unable to remove organs

### ISSUE THREAD

**Issue by Jacobthegamer0709** [tgstation/tgstation#86676]
### Client Version:

515.1643

### Issue Summary:

The organ manipulation menu opens, but when i select a organ and click submit, nothing happens.
Putting an organ in works fine.

### Round ID:

[237969](https://scrubby.melonmesa.com/round/237969)

### Reproduction Steps:

1. Get to the organ manipulation part of the Organ Manipulation surgery.
2. Use hemostat on patient.
3. Try to remove an organ.
4. Observe.

**Comment by Sadboysuss** [comment]
were you perhaps on combat mode? 😅

**Comment by Jacobthegamer0709** [comment]
> were you perhaps on combat mode? 😅

No, I dont think that I had combat mode on, and I think if it was on, it would have hit the person with the hemostat

**Comment by Sadboysuss** [comment]
Are there any other details you missed? Perhaps there was extra condition that happened, which caused the bug to happen. Please describe all the events leading up to the bug, however minor they may seem.

**Comment by Jacobthegamer0709** [comment]
> Are there any other details you missed? Perhaps there was extra condition that happened, which caused the bug to happen. Please describe all the events leading up to the bug, however minor they may seem.

I'll try to recreate the issue, and note anything that could have effected it.

**Comment by Sealed101** [comment]
the surgery step here tries to fetch the item that's been used to facilitate the step, i.e., a hemostat, to match it to the one that's being held by the surgeon. borg omnitools reference a simple scalpel to trick surgeries into thinking that instead of an omnitool with no tool behaviours the borg is using a hemostat. this fails in this exact surgery step because it gets the omnitool with `user.get_active_held_item()` and not the hemostat used for reference
relevant code:
https://github.com/tgstation/tgstation/blob/bcc2bbd76c4a1d3380d35b3a9a81829177e26c49/code/modules/surgery/organ_manipulation.dm#L212-L232
https://github.com/tgstation/tgstation/blob/bcc2bbd76c4a1d3380d35b3a9a81829177e26c49/code/modules/mob/living/silicon/robot/inventory.dm#L4-L8
https://github.com/tgstation/tgstation/blob/bcc2bbd76c4a1d3380d35b3a9a81829177e26c49/code/game/objects/items/robot/items/tools.dm#L207-L231

**Comment by Jacobthegamer0709** [comment]
I've tried to build the latest tg-master but it keeps ending up in errors, i'll try to replicate on the server.

**Comment by Sealed101** [comment]
> I've tried to build the latest tg-master but it keeps ending up in errors, i'll try to replicate on the server.

iirc our build doesn't work on the latest byond version, downgrade to an earlier one for it to work
https://www.byond.com/download/build/

or just don't bother, since i've reproduced this already lmao
