### ISSUE TITLE
Haunted longswords are unintuitive and a moderation issue.

### ISSUE THREAD

**Issue by Kiromaka** [tgstation/tgstation#86864]
### Client Version:

515.1640

### Issue Summary:

Haunted longsword - cult reward for saccing a heretic, is an almost immortal blade that can not be contained (since it can brake walls). This may be seen as a worthy reward for saccing a heretic, but it isnt.

The blade is allowed to kill WHOEVER it wants, by code. Its strong enough to 3tap armored cultists and can brake cult buidlings, which it will do, since you just ruined their heretic round.

Cult should not be punished for doing cult things - completing their objectives and saccing people. Heretics right now SHOULD never be sacced because of this blade, it can easily kill cult in minutes and is allowed to.

It should not be allowed to harm cultists or even be able to, since this is very unintuitive, and leads to cult getting punished for doing something good.

`tochat(trapped​entity, span_userdanger("You've been sacrificed to the Enemy, and trapped inside a haunted blade! While you cannot escape, you may help the Cult, your current wielder, or even pester everyone with what few abilities you kept."))"`

Pester = kill half the cult.

### Round ID:

[238786](https://scrubby.melonmesa.com/round/238786)

### Test Merge Information:

- [[TM ONLY] Adds a couple of sanity checks to storage code and temporary logging for when they are inevitably hit](https://www.github.com/tgstation/tgstation/pull/86842)

### Reproduction Steps:

1. Sacrafice a heretic
2. Recieve a Haunted longsword
3. Watch it kill cultists and brake your base
4. Try to throw it away
5.It can jump out of hands and use spells
6. Watch cult loose

**Comment by iprice** [comment]
Agree on this one, having handled a case with one of these I literally had to go read the codebase to check that this weird 4th objective is hard coded rather than some weird stuff the Heretic did with custom objectives.

Like why on earth would cult making a legitimate conversion/sacrifice create a weapon that then goes on to murder cult, who think its all on their side, so probably aren't expecting what happens next.  How is this good intuitive game design for a mechanic.  Cult's already a lot of stuff to manage and since i have no idea how to tell what heretic does what i guess cult should now just flush all dead heretics into space just to be safe?  And new players are supposed to just know this?  Or get f***ed by it?

Is it a bwoinkable offence to create an anti cult weapon by cult sacrifice?  What if you do it knowing it will happen?

**Comment by Kiromaka** [comment]
> Is it a bwoinkable offence to create an anti cult weapon by cult sacrifice? What if you do it knowing it will happen?

Thats also and interesting question, should I now report cultists making these blades, sicne blade cant be punsihed, its in de code, he can do it.

**Comment by Das15** [comment]
Ah yes, nothing like game mechanics punishing players for doing what they were supposed to... Fun. Also the said situation happened not on round ID 238786, but on 238780.

**Comment by Metekillot** [comment]
It is in fact bizarrely unintuitive that the blade is able to kill cultists.

**Comment by carlarctg** [comment]
Hello! I made this thingy. I think it's cool. I am also the direct cause of this whole debacle to begin with, being the sword that got people angry. (i also suggested this issue title)

The concept of a 'Cursed Sword' is a great and interesting one - to have a powerful artefact in your hands that only obeys its malicious whims, that you need to restrain and may not be able to handle its ire, necessitating it be destroyed or sealed away forever, is a unique and engaging dynamic that isn't present in similar items such as the chaplain's sword or the soul scythe. In our social game, I think this is a extremely cool concept. The sword's complete independence is what makes it so intriguing an item. 

See: https://tvtropes.org/pmwiki/pmwiki.php/Main/EvilWeapon

This is balanced, or at least it's supposed to be balanced, by the fact that it's hard for it to break free from the grasp of a cultist, and that they can just chuck you into a recycle bin, throw you into space, seal you in a room, or put you in the deep fryer and eat you. If you want to be an ass to the people that quite literally hold your power, they won't have TOO much difficulty. 

Being fair here, the round that caused this issue is one where I was a rust heretic, so I had more power than usual in terms of breaking out of places, due to rusting walls away with the one spell they're allowed to have. With any other path it couldn't really have happened.

There seem to be large problems with visibility, which did not come up before in all the months this was merged beforehand, which I'm unsure how to display properly that THIS IS NOT YOUR FRIEND. But the concept is a solid one, that's nowhere else in the game, and it's worth trying to see how to keep it in.

A part of the issue might be that our players may just be too narrow-minded to think of what to do in unique situations like this. They see something they can't stab or shoot and mentally BSOD. That's my overly cynical view, though. And I do think it would be really, really sad if something like this was deemed unfit for the game because players can't work their way around it.

Of note is that in the round, what I ended up doing, by myself, as far as I recall, was:

- Kill an Artificer that kept trying to drag my evil ass into space (which never asked for someone with, you know, hands, to come by and help)
- Kill the Wraith that sacrificed me
- Rust a bunch of areas
- Be a minor general nuisance to the crew, throwing myself at them, which ended up critting one guy and having another throw me into disposals, which didn't grind me due to a broken pipe but did cause me to miss the shuttle

Not really that much of an impact.

The sword's throwing damage is overtuned - that's my bad. If nothing else, I definitely will up that to at least a 4 hit kill, if not 5.

Do note how strong this sword is in the hands of a cultist that can work around it.

It has 35 force, 55 block chance, high wounding, and grants you a powerful cooldown spell (which cultists don't otherwise have, needing to reset for each spell used). It's a double edged blade.

**Comment by Metekillot** [comment]
Killing 3-4 people after already being killed does in fact seem like something of an impact -- causing massive wounds to cultists and being able to kill them with no counter besides maybe you don't roll well on resisting out of their hands also doesn't seem particularly fair to the cultists who have already busted ass to kill a heretic who has passive counters to most of their powers, not even considering if that heretic has researched more powers.

We see the vision of it being an eldritch artifact and all of whatever, but if you've just had your overpowered antag round snuffed out, it is certainly much easier -- and much more common, as I can attest for three of my cult rounds where 20% of each was spent nursing wounds from one of these -- to just spam click at the people who killed you. 

Why would you choose being toted around rather than nonstop attempts to murder cultists? Fuck's sake man, you're the one who designed it and you're testifying you yourself choose to murder rather than being a fancy talking sword for the team who merk'd your silly ass.

**Comment by iprice** [comment]
Why would anyone ever intentionally make this thing?  And I think its an unnecessary insult to call the players "too narrow minded" for not realising that a weapon that comes from them doing their intended thing is then going to just murder them.  No-one expected this, not admin, not players, other than you, because you coded it.

Also what meta do you expect this to lead to?  What I learned here is throw heretics into space dont sac em?

**Comment by optimumtact** [comment]
> tochat(trapped​entity, span_userdanger("You've been sacrificed to the Enemy, and trapped inside a haunted blade! While you cannot escape, you may help the Cult, your current wielder, or even pester everyone with what few abilities you kept."))"

This should be replaced with the antag policy config system so keyholders/headadmins can decide what this should be doing.

**Comment by Kiromaka** [comment]
Have to agree with ian, as strong as the dark blades are (2-3 hit ko with sharp) - which I would call the best reward out of 3, the downside of having a murderous sword rampaiging thru your buildings and culties isnt worth it. Gonna be throwing heretics into space for now.

Balance side is wack btw.
>Steps to kill cult as salty heretic.
>Step 1 - brake the pylons (2-3 throws should be enough), most cultists wont realise that this wasnt a mistake, yet.
>Step 2 - start wounding the culties, chances are, you are in an inclosed space, very hard to dodge your launges.
>Step 3 - tell sec where the base at, they gonna be raiding that soon.
>In case of you getting caught - resist from hands and spam your button, most paths will give you something strong enough to kill your weilder, do 2-3 launges, escape from the crime scene.

The sword isnt a mob - cant be killed or critted, those you have to transport a murderous sword to kitchen/crem/space or bring acid, which all takes time (that the sword will use to kill culties) and kitchen/crem will expose you to sec and validhunters.

**Comment by carlarctg** [comment]
> We see the vision of it being an eldritch artifact and all of whatever, but if you've just had your overpowered antag round snuffed out, it is certainly much easier -- and much more common, as I can attest for three of my cult rounds where 20% of each was spent nursing wounds from one of these -- to just spam click at the people who killed you.

I've already stated the throwing damage's overtuned.
 
> Why would you choose being toted around rather than nonstop attempts to murder cultists? Fuck's sake man, you're the one who designed it and you're testifying you yourself choose to murder rather than being a fancy talking sword for the team who merk'd your silly ass.

Everyone but me, apparently, because this only came up as a problem now. I only did it because the cultists broke a truce of silence. Otherwise I'm usually just helping whoever happens to be my wielder at the moment.

> Why would anyone ever intentionally make this thing? And I think its an unnecessary insult to call the players "too narrow minded" for not realising that a weapon that comes from them doing their intended thing is then going to just murder them. No-one expected this, not admin, not players, other than you, because you coded it.

> Also what meta do you expect this to lead to? What I learned here is throw heretics into space dont sac em?

I don't think about 'metas' because that's gross and anathema to the best parts of this game, that word belongs in a moba

**Comment by iprice** [comment]
Okay, well, not thinking about metas or once again just randomly disparaging something doesn't mean they dont exist, and doesn't offer any reasoning as to why it doesn't matter.

You can still answer the asked question in hindsight rather than just claiming obliviousness.

**Comment by Metekillot** [comment]
I respect the technique of clause by clause address of comments but you also totally neglected about a third of mine. And the throwing damage being overtuned does nothing to address you having little -- if none at all -- incentive to help the people who just reduced your antag round to telekinesis. I love to murder. Murdering is fun. I can still murder as the TK sword. Why would I choose to be carried around and occasionally cast a spell?

**Comment by optimumtact** [comment]
i don't think i'ts a big deal, you can choose not to make the sword if you dont want to.

The role policy could **maybe** need adjusting but players being a dick is first and foremost an admin issue.

**Comment by optimumtact** [comment]
oh i thought it was an optional part of the rite, i guess its' problematic if you don't have control over if one appears or not.

**Comment by carlarctg** [comment]
I've been thinking about this, and one of the ideas I had was that the sword spawned 'bound', limiting it from taking action but also limiting _you_ by being unable to cast its spells. Cultists would be able to bind and unbind it at will, but it'd always start bound.

**Comment by Kiromaka** [comment]
> The role policy could **maybe** need adjusting but players being a dick is first and foremost an admin issue.

The player shouldnt be punished for doing something he is allowed and practicly told to do, if the cult killing should be ruled as being a dick and be punished by the admins, why not just remove the - you are allowed to kill cultists and be dick prompt.

> I've been thinking about this, and one of the ideas I had was that the sword spawned 'bound', limiting it from taking action but also limiting you by being unable to cast its spells. Cultists would be able to bind and unbind it at will, but it'd always start bound. So now it has an incentive not to fuck over the cult fnr.

Why ? Why just not remove the - you are allowed to be a dick to cult and ruin their gameplay. Saccing a heretic is an extremly hard task, since heretic is immune to cult magic and much stronger then any cultist. No one will ever unbound the sword, since it has a big chance of leading to cult loosing. 

This change is the same as doing nothing - right now the best thing to do with heretic is to space them, with that change the best thing would be to space the sword, since it isnt that good without spells and you probably wont be using it unbound, and leaving a sword, that can kill half the cult and rat to sec, on the floor, for some random noobie to unbound, isnt the smartest move.

**Comment by iprice** [comment]
Yeah, also don't understand why you're so hell bent on creating an outcome from cult doing their proper normal thing that can backfire and f* cult.  Cultists ruin your heretic run too many times or something so you added a way to continue to murderbone as a partial heretic?

**Comment by Metekillot** [comment]
Letting heretic fuck cultists from beyond the grave I could be onboard with if they had to work for it, such as doing a ritual that requires them to sacrifice the hearts of three cultists.

**Comment by ExcessiveUseOfCobblestone** [comment]
https://github.com/tgstation/tgstation/blob/master/.github/guides/POLICYCONFIG.md#requirements

GFPR to put it into policy system

**Comment by ExcessiveUseOfCobblestone** [comment]
Also the evil sword trope is a bit weird when the guys youre giving it to are already the evil guys of the narrative. It doesnt come as a surprise if people think the sword that's hoisted onto them as a "reward" is aligned to them.

**Comment by optimumtact** [comment]
> > The role policy could **maybe** need adjusting but players being a dick is first and foremost an admin issue.
> 
> The player shouldnt be punished for doing something he is allowed and practicly told to do, if the cult killing should be ruled as being a dick and be punished by the admins, why not just remove the - you are allowed to kill cultists and be dick prompt.

I don't give a shit what you think you are told to do.

The first rule on tgstation is don't be a dick, everything else is secondary.

**Comment by carlarctg** [comment]
> Also the evil sword trope is a bit weird when the guys youre giving it to are already the evil guys of the narrative. It doesnt come as a surprise if people think the sword that's hoisted onto them as a "reward" is aligned to them.

That's a great point. Sadly, it's still the only 'real' option because all the magic in the game is concentrated in our antagonists, unless there were to be some form of elaborate ritual given to the chaplain I guess. Not that I'm going to do that for this, or maybe at all. It seems like slippery slope & bloat into magic station.

**Comment by Kiromaka** [comment]
> I don't give a shit what you think you are told to do.
> 
> The first rule on tgstation is don't be a dick, everything else is secondary.

Dont be a dick is an extremly vague rule, is killing someone = being a dick ? 

Do antags need to be banned for killing their goals, the person killed wont be pleased with that, so you were a dick to him. Should sec be banned for arresting people, its a dickhead move, shitsec is prelevant, but i dont see anyone getting banned. 

The sword is still a heretic, and has full Carte Blanche on killing ANYONE, unless he is told otherwise - antags are allowed to do ANYTHING except brake other rules, and "dont be a dick" is a rule made to give admins a reason to ban shitheads who avoid braking the rules on technicalities, it has no substance.

And I dont even think the heretic is being a dick by killing cult - his antag-round was ruined, he got practicly round-removed by cult and has more then enough motivation to kill them all. And this motivation is supported by the freedom of action his HERETIC role gives him, while also having a nice lil promt - "go harras cult", appear when he gets sacced.

Imagine if revs/cult tires to convert you and fails, (dunno maybe headrev was slow as fuck, or no one tped to sac you.) would you just lie down and wait for them to finally get their shit together ? Saccing a heretic right now doesnt convert him, it just changes his form of existence, he is motivated by both his role and freedom to kill valids, so why shouldnt he do it, he isnt being a dick in any-way, the code is just shit.

**Comment by ExcessiveUseOfCobblestone** [comment]
> > Also the evil sword trope is a bit weird when the guys youre giving it to are already the evil guys of the narrative. It doesnt come as a surprise if people think the sword that's hoisted onto them as a "reward" is aligned to them.
> 
> That's a great point. Sadly, it's still the only 'real' option because all the magic in the game is concentrated in our antagonists, unless there were to be some form of elaborate ritual given to the chaplain I guess. Not that I'm going to do that for this, or maybe at all. It seems like slippery slope & bloat into magic station.

im just saying it needs to be conveyed better because the intuitive approach is that you are getting a giga drop for doing this really hard task, not damning yourself for converting someone who happened to be a heretic.
