### ISSUE TITLE
Ethereal's cannot feed from APC's

### ISSUE THREAD

**Issue by GarryRomaniev13** [tgstation/tgstation#86985]
### Client Version:

515.1643

### Issue Summary:

When tried to feed from an APC, it simply doesn't work. According to Ian0 it is caused because APC's have 10 million power and ethereals only have maximum 20.000. So game automaticaly sees it "too much for the ethereal to consume".

### Round ID:

[239440](https://scrubby.melonmesa.com/round/239440)

### Test Merge Information:

- [Adds the NT BR-38 Battle Rifle. A sci-fi hybrid gun (that can critically fail on existence). Throws combat shotguns (the big ones from cargo) into the bin. Other changes. (SPRITES WIP)](https://www.github.com/tgstation/tgstation/pull/86853)
- [[TESTMERGE READY] The Torment Nexus: The future of Security brigging and prisoner rehabilitation!](https://www.github.com/tgstation/tgstation/pull/86106)

### Reproduction Steps:

Go to any charged APC as an ethereal
Try to charge your energy
Observe how it responds and doesn't work.

**Comment by Sadboysuss** [comment]
supposedly this pr fixed it: https://github.com/tgstation/tgstation/pull/86910

**Comment by GarryRomaniev13** [comment]
It doesn't fixed. Still doesn't work.

**Comment by 00-Steven** [comment]
seems this is because the define for the ethereal apc drain/charge uses `STANDARD_BATTERY_CHARGE`:
https://github.com/tgstation/tgstation/blob/5529ee679d63500b3655f67aff22da375fdddc09/code/modules/power/apc/apc_attack.dm#L4-L5
while the ethereal charge values use `STANDARD_CELL_CHARGE`:
https://github.com/tgstation/tgstation/blob/5529ee679d63500b3655f67aff22da375fdddc09/code/__DEFINES/mobs.dm#L294-L301
which is 100x as small:
https://github.com/tgstation/tgstation/blob/5529ee679d63500b3655f67aff22da375fdddc09/code/__DEFINES/power.dm#L29-L30

Swapping `STANDARD_BATTERY_CHARGE` for `STANDARD_CELL_CHARGE` fixes this and allows ethereals to drain/charge APCs again!
But then there's the issue that they do not make even a dent in the charge levels in either direction with the current ethereal charge levels versus APC megacell charge levels, as a single roundstart APC would take almost 100x the maximum charge an ethereal can even have.

**Comment by 00-Steven** [comment]
cc @SyncIt21

**Comment by SyncIt21** [comment]
Ethereals have to scaled up to use batteries as a whole to have an effect on APCs but that would turn it into an balance PR.

**Comment by 00-Steven** [comment]
arguably yes, though currently it just doesn't work at all as per the aforementioned bits- poked you cause it seems it was your pr that tried to fix it but introduced this bug

**Comment by SyncIt21** [comment]
> arguably yes, though currently it just doesn't work at all as per the aforementioned bits- poked you cause it seems it was your pr that tried to fix it but introduced this bug

Yeah I didn't understand all the moving parts of ethereals when I made that PR, so thanks for notifying me on this.

Anyone interested in making a balance PR for this I'll pet them to it

**Comment by KingkumaArt** [comment]
https://github.com/tgstation/tgstation/pull/87231
