### ISSUE TITLE
Apostrophes are broken again.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#8708]
![](http://i.imgur.com/uu5EpCX.png)

The last name was supposed to be Mc'Meme'rs. This also followed into their actual names when mousing over them, examining, actions, speaking etc.

It did NOT happen through radio chatter, strangely enough. That worked fine.

**Comment by d3athrow** [comment]
I think the sanitizing is intended since its done this as long as i can remember

**Comment by WJohn** [comment]
This is effectively an infinitely common bug. It seems we've run into it about 20+ different times so far.

**Comment by Cyberboss** [comment]
This has nothing to do with goonchat

**Comment by PraiseRatvar** [comment]
you're right, im dumb

**Comment by MrStonedOne** [comment]
Everything we do passes thru `sanitize()` on input, rather than output. It's done this way to massively lower the XSS vector and it was easier to get coders to do this.

We would have to massively shift that entire paradigm to fix bugs like this, and it would have to be all at once, in one pr, with no mistakes or we would have more bugs and likely some XSS and CSRF exploits that would allow players to make admin clients that can see their messages perform admin actions.

**Comment by WJohn** [comment]
I haven't seen this in a while so it's likely fixed.
