### ISSUE TITLE
sharpening a mounted chainsaw doesnt work

### ISSUE THREAD

**Issue by carlarctg** [tgstation/tgstation#87140]
### Client Version:

n/a

### Issue Summary:

you cant sharpen an active mounted chainsaw

when you sharpen an inactive mounted chainsaw it increases damage

this damage does not carry over to when its active

and is reset when inactivated to initial values wasting the whetstone

### Round ID:

[240053](https://scrubby.melonmesa.com/round/240053)

### Test Merge Information:

n/a

### Reproduction Steps:

1. get mounted chainsaw
2. get whetstone
3. sharpen inmactive saw
4. notice how stats are lost when toggling on and off

**Comment by Arturlang** [comment]
Is this a issue with literally every other wielded blade? (Fireaxes)

**Comment by necromanceranne** [comment]
No, the two_handed component listens for when the parent item is sharpened and adds that value to the component's damage increase on wield. HOWEVER, it only does this when wielded and actually removes that extra force on unwield (this isn't how sharpening works normally, but frankly I don't think anyone gives a shit to fix this since most melee weapons with two-handed wielding aren't going to be used one-handed)

Chainsaws do not utilize the two_handed component to handle its force. Instead, the item handles the force instead as it is using a totally-not-just-tranforming-component method on the item itself that doesn't respond to sharpening at all.
