### ISSUE TITLE
Gas analyzers scan the tile when placed on a table

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#87354]
### Issue Summary:

it places the gas analyzer on the table alongside scanning the tile it's on

### Reproduction Steps:

click table with gas analyzer

**Comment by Hoolny** [comment]
Not a bug this is a normal interact that happens when you are in harm mode, many other tools follow this logic such as wrenches when in harm mode you will attack towards the table when not you will place, in the case for gas analyzer harm mode will make you analyze the table and non harm made will make you put the gas analyzer in the table.

![dreamseeker_kDgJPHA5I4](https://github.com/user-attachments/assets/e72194ca-c308-483b-a6f5-60e751140841)

**Comment by Sadboysuss** [comment]
I don't think you understood the bug but I don't care

**Comment by Sealed101** [comment]
hoolny update your fork this is an actual issue on master
combat mode does not prevent scanning nor placing the analyzer on the table
