### ISSUE TITLE
Eldritch Card portals placed on shuttles can teleport non-heretics to arbitrary turf reservations once the shuttle is in transit

### ISSUE THREAD

**Issue by Y0SH1M4S73R** [tgstation/tgstation#87591]
### Client Version:

515.1645

### Issue Summary:

I stumbled into an Eldritch Card portal placed on the emergency shuttle while it was in transit. I ended up on the syndicate infiltrator.
![the lock heretic when they portal the shuttle](https://github.com/user-attachments/assets/1a076c7e-0632-4e61-8049-06351c8349d1)

### Round ID:

241067

### Test Merge Information:

#83227
#84826

### Reproduction Steps:

1. Have a heretic use an Eldritch Card to create a portal with one end on the shuttle.
2. Have the shuttle enter transit.
3. Have a non-heretic enter the portal from the shuttle while it is in transit.

**Comment by necromanceranne** [comment]
since this is up, since the heretic can reverse the effects of the portal for themselves, and there are shuttles that can be utilized by anyone to move while in transit, it's entirely possible that a lock heretic could arbitrarily just hop into the Infiltrator at any time.

Since they are also the Masters of Unlocking and can make themselves completely invulnerable to damage, there is a nonzero chance they just then go raid the rest of the base with impunity.

**Comment by mc-oofert** [comment]
oops

**Comment by carlarctg** [comment]
feature
