### ISSUE TITLE
Antimagic Does Not Block Void Heretic Status Stacks

### ISSUE THREAD

**Issue by TagGamerGang22** [tgstation/tgstation#87621]
### Client Version:

515.1637

### Issue Summary:

Antimagic does not block the status stacks from at the least the void ascension effect. I did not test to see if there's a similar issue with the other void heretic spells that apply the stacks like void conduit.

### Round ID:

[241147](https://scrubby.melonmesa.com/round/241147)

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [[TM ONLY] The roundstart report will only ever show either Pulsar Star or White Dwarf](https://www.github.com/tgstation/tgstation/pull/87584)

### Reproduction Steps:

1. Have antimagic
2. Be next to an ascended void heretic
3. Still get the status stacks

**Comment by timothymtorres** [comment]
There are 3 different types of antimagic resistance:
- Spells (wizards spells)
- Holy (cult spells)
- Mind (mindswap, abductors, etc.)

I do believe a lot of heretic magic falls into different categories depending on the spell. So depending on the resistance you have and the type of spell being used, it may not apply.

**Comment by Sealed101** [comment]
https://github.com/tgstation/tgstation/blob/0fc890df6ac1f65d0fa9520512c5da41303d1b0a/code/modules/antagonists/heretic/magic/void_conduit.dm#L93-L100

**Comment by moocowswag** [comment]
What was the anti magic you had? The "magic isnt real" trauma? the null rod? The tinfoil hat?

**Comment by Sealed101** [comment]
a holymelon helmet wouldn't protect, for reference, it only gives `MAGIC_RESISTANCE_HOLY`

**Comment by the-orange-cow** [comment]
Unless there was was semi recent change, holymelons have been blocking almost everything for me.  Cult stuff, wizard stuff, most heretic stuff.

Not sure if the helmets actually work though.  Holding holymelons blocks a heretic hand, but the helmet didn't.

**Comment by Sealed101** [comment]
i specifically stated _helmet_ (and also armor apparently lol)
https://github.com/tgstation/tgstation/blob/0fc890df6ac1f65d0fa9520512c5da41303d1b0a/code/modules/clothing/suits/armor.dm#L818-L825

https://github.com/tgstation/tgstation/blob/0fc890df6ac1f65d0fa9520512c5da41303d1b0a/code/modules/clothing/head/helmet.dm#L700-L707

the plant gene adds `MAGIC_RESISTANCE` as well
https://github.com/tgstation/tgstation/blob/0fc890df6ac1f65d0fa9520512c5da41303d1b0a/code/modules/hydroponics/unique_plant_genes.dm#L13-L26

**Comment by timothymtorres** [comment]
Looks like an oversight. There should be no reason that crafted holymelon armor should lose it's `MAGIC_RESISTANCE` antimagic flag.

**Comment by timothymtorres** [comment]
Playing with an LLM gave me:

---

It looks like the issue lies in the difference between the `antimagic_flags` set in the two code snippets.

**Problem:**

* **Holymelon Plant Gene:**  Sets `antimagic_flags = MAGIC_RESISTANCE|MAGIC_RESISTANCE_HOLY`. This means it resists **both** general magic (`MAGIC_RESISTANCE`) and holy magic (`MAGIC_RESISTANCE_HOLY`).

* **Holymelon Armor Crafting:** Sets `antimagic_flags = MAGIC_RESISTANCE_HOLY`. This means it only resists holy magic.

**Explanation:**

If the "magical effects" the player is experiencing are not specifically classified as "holy" magic, then the crafted armor will not provide resistance, while the growing plant would have.

**Solution:**

To fix the bug and make the armor resist all magic, you need to include the `MAGIC_RESISTANCE` flag when adding the `anti_magic` component during crafting.  You should change the crafting code to:

```dm
 AddComponent( 
 	/datum/component/anti_magic, \ 
 	antimagic_flags = MAGIC_RESISTANCE|MAGIC_RESISTANCE_HOLY, // Added MAGIC_RESISTANCE flag
 	inventory_flags = ITEM_SLOT_OCLOTHING, \ 
 	charges = 1, \ 
 	drain_antimagic = CALLBACK(src, PROC_REF(drain_antimagic)), \ 
 	expiration = CALLBACK(src, PROC_REF(decay)) \ 
 ) 
```

**Important Note:** This assumes that the game's magic system correctly categorizes spells and effects with the appropriate flags. If there's a mismatch between how spells are flagged and how the `anti_magic` component checks for resistance, you might need to adjust the spell code or the resistance flags accordingly.

**Comment by Sealed101** [comment]
that's about it yeah
BUT this is a separate issue as long as the OP of the issue doesn't tell us what kind of antimagic they were employing. because the holymelon stuff was brought in by me so uh yeah
i would be inclined to close this issue otherwise because without the exact antimagic source for the issue it becomes hilariously tedious to find and patch
