### ISSUE TITLE
possible issue with lone operative spawning weight

### ISSUE THREAD

**Issue by Jackal-boop** [tgstation/tgstation#87681]
### Issue Summary:

on round 241259 . the disk was left unsecured and never touched for about the first 45 to maybe an hour into the shift, during the time no lone operative spawned. 

### Round ID:

[241259](https://scrubby.melonmesa.com/round/241259) 

### Reproduction Steps:

wait 45 minutes staring at a unsecured disk

**Comment by MrMelbert** [comment]
No issue - "increased chance to spawn" =/= "guaranteed chance to spawn"

**Comment by MrMelbert** [comment]
![20144141249210337-2014-05TechnologueFp170](https://github.com/user-attachments/assets/a8610bed-50b6-4f90-a8c9-97fcf0e68c46)

Course, there could be a very very slim chance that something is actually bugged, hard to verify without logs. 
But I've seen countless times where lone op chances rose to 100s and it didn't fire because (see figure 1)
