### ISSUE TITLE
Wizard lustrous exploit

### ISSUE THREAD

**Issue by Sadboysuss** [tgstation/tgstation#87897]
### Client Version:

515.1642

### Issue Summary:

Transforming to lustrous and back keeps the bluespace stream abilties

### Reproduction Steps:

1. Transform into lustrous at a magic mirror
2. Transform back into another species
3. observe bluespace streams

**Comment by timothymtorres** [comment]
Relevant code:

https://github.com/tgstation/tgstation/blob/2e01bb1827972e4be6a6c91af105eaf94807e3ba/code/modules/mob/living/brain/brain_item.dm#L360-L397

https://github.com/tgstation/tgstation/blob/2e01bb1827972e4be6a6c91af105eaf94807e3ba/code/modules/mob/living/brain/brain_item.dm#L445-L460

So what's happening here is that the lustrous brain is adding the `/datum/brain_trauma/special/bluespace_prophet` when the brain is inserted into a mob, and then removing it when the brain is removed. The problem is that the `before_organ_replacement` proc is triggered that transfers the trauma over to the new brain before it can be removed.

This is an edge case since that is the only brain type that adds/removes a trauma. Unfortunately that trauma is in the same group categories as other traumas so there is no easy way to fix it without possible affecting other things.

## Solution 1 - Skip special brain traumas from transfer

```dm
	// Transfer over traumas as well
	for(var/datum/brain_trauma/trauma as anything in traumas)
		if(istype(trauma, /datum/brain_trauma/special)
			continue
		remove_trauma_from_traumas(trauma)
		replacement_brain.add_trauma_to_traumas(trauma)
```

## Solution 2 - Skip traumas with low resilience level and change `bluespace_prophet` resilience level

```dm
	// Transfer over traumas as well
	for(var/datum/brain_trauma/trauma as anything in traumas)
		if(trauma.resilience <= TRAUMA_RESILIENCE_WOUND) // skip weak traumas
			continue
		remove_trauma_from_traumas(trauma)
		replacement_brain.add_trauma_to_traumas(trauma)
```

These are probably going to be the most ideal choices. Sure you can add `if(istype(trauma, /datum/brain_trauma/special/bluespace_prophet))` check but it's just a band aide. We need to put brain traumas into categories where you want them to follow a mob into a fresh body. (ie. polymorph/etc.)

CC @MrMelbert since you added the brain trauma transfer code in:
- #70530

**Comment by MrMelbert** [comment]
I don't see why we can't just implement `/obj/item/organ/brain/lustrous/before_organ_replacement` to cure the trauma before transfer
