### ISSUE TITLE
Pineapple orders not working

### ISSUE THREAD

**Issue by ISwearToStonedImNotGod** [tgstation/tgstation#87956]
### Client Version:

515.1645

### Issue Summary:

As chef, I tried to order pineapples from my produce console. The pineapples never came in the supply pod. Other items from the console worked fine, but pineapples just wouldn't arrive. The map was Ice Box, no idea if this happens on other maps

### Round ID:

[242310](https://scrubby.melonmesa.com/round/242310)

### Test Merge Information:

- [[tgui] Tgui core components D-M](https://www.github.com/tgstation/tgstation/pull/87763)
- [Guncode Agony 4: The Great Projectile Purge](https://www.github.com/tgstation/tgstation/pull/87740)
- [[TM ONLY] Buffs jetpack/wing forces and stabilization greatly to see how major the subsystem chugging issue is](https://www.github.com/tgstation/tgstation/pull/87742)
- [Batons have their stamina damage reduced by armor, get stun armor penetration](https://www.github.com/tgstation/tgstation/pull/87754)
- [Add ignition sound and roaring fire to atmos fire](https://www.github.com/tgstation/tgstation/pull/84280)

### Reproduction Steps:

1. Late join a shift as a cook.
2. Use the produce console to order pineapples with an express order
3. See if the pineapples arrive in the supply pod that drops from an express order

**Comment by Loafin34** [comment]
tried this on nebula, doesn't work either. grand NT blockade on pineapples, confused them with grenades

**Comment by lizardqueenlexi** [comment]
Caused by #87735.

Specifically, the setup for the juicing trait, which only pineapples have:

https://github.com/tgstation/tgstation/blob/6859e714d07d8a7fabc642cdd400ce4311c43178/code/modules/hydroponics/seeds.dm#L280-L283

For some reason, this uses the `juice()` proc to swap in the correct juice in place of nutriment/vitamins. Post-refactor, `juice()` does a lot more work, and as a side effect, qdels the item being juiced if it is inside of any `/atom/movable`.

https://github.com/tgstation/tgstation/blob/6859e714d07d8a7fabc642cdd400ce4311c43178/code/game/objects/items.dm#L1096-L1099

https://github.com/tgstation/tgstation/blob/6859e714d07d8a7fabc642cdd400ce4311c43178/code/game/objects/items.dm#L1113-L1119

This makes pineapples delete themselves if they spawn inside of, say, a delivery pod or a cargo crate, but not if they spawn on the floor. I imagine the solution here is to modify how the juice reagents are added, since calling `juice()` feels kind of hacky to begin with (and now doesn't work at all).
