### ISSUE TITLE
Bug with human sprites(??)

### ISSUE THREAD

**Issue by tedward1337** [tgstation/tgstation#9074]
There was no body but the clothes were still attached? 

![](http://puu.sh/hjWrj/e15259f398.jpg)

**Comment by RemieRichards** [comment]
Well, the clothes being there is just because the clothes part of update_icons() worked.

Was it badminnery?

**Comment by tedward1337** [comment]
No, no badminnery was in place. This was just standard xenos

**Comment by Miauw62** [comment]
I've seen this happen before with broken monkey transformations I think.

**Comment by phil235** [comment]
Did anyone check what the human's icon vars were like?

**Comment by phil235** [comment]
The issue is that the human's base icon state was changed and did not match the name of a base human sprite anymore. With the introduction of dismemberment this bug will be even harder to reproduce since only a few species still use the base icon state code.

If noone witnessed this bug recently, I think we should close it.
