### ISSUE TITLE
Instrument BPM tuning is fuck

### ISSUE THREAD

**Issue by SconesC** [tgstation/tgstation#9248]
It starts off in increments of 10, then moves to 20, then like >200 it just starts adjusting in increments of 111 and it's really fucking weird please send help

**Comment by TheWiznard** [comment]
yeah I never set the bpm by the buttons, it's much easier to type what bpm you want when you import a song

**Comment by Supermichael777** [comment]
that doesn't work ether

**Comment by TheWiznard** [comment]
Are you talking about setting it when you import? Last time I tried it, it worked for me.
Example: 
BPM: 200
Gb4/0.92,Bb/0.99,Bn,G/0.99,Eb/0.99,Bb,Bn,G/0.99
Ab/0.93,Bb/0.99,Bn,G/0.99,E/0.99,Bb,Bn,G/0.99

just change 200 to whatever, works every time

**Comment by Supermichael777** [comment]
their was a recent update to instruments certain ones may be suffering from FEATURES. specifically the new guitar seems to be locked to odd bpm choices

**Comment by Boggart** [comment]
Code-wise the guitar is identical to the violin, I just moved all of the code from the violin to instrument so they could share a common base.

BPM weirdness might be related to this: #8456

Apparently BPM gets rounded on import or setting but I've noticed that the buttons will let you pick BPMs that importing will round away from.

**Comment by MrPerson** [comment]
Working as intended. This is what all other values would get rounded to anyway. Well I guess some smaller values might round differently for half and quarter notes and such, but at the point where that starts to matter, we're already looking at fairly small BMP differences anyway.

If you want more options, increase the frame rate. I'll go ahead and explain why this is so dependent on the frame rate though.

Image this is a (shitty) song you want to play
A-A-A-A-A-A-A

At 6000 bpm (100 notes per second), you're doing (remember, sleep() is in deciseconds so 0.1 means 0.01 seconds)
A-sleep(0.1)-A-sleep(0.1)-A-sleep(0.1) etc

The problem is that sleep(0.1) rounds to the nearest frame. With 11 fps or 0.09 seconds per frame. So it's equivalent to

A-sleep(0.9)-A-sleep(0.9)-A-sleep(0.9) etc

So even though you asked for 6000 bpm, you actually got "just 660". And you can't get more. The absolute most you can get is the frame rate * 60, and the differences between various viable bpm's is tied to the frame rate as well.

**Comment by Boggart** [comment]
It's kind of weird that you can set values (even if they get rounded, it doesn't seem to show it though) with the buttons that you can't with import.

**Comment by Dorsisdwarf** [comment]
Thats not the bug here though, MrPerson. The problem is that anything above ~160 gets rounded to a multiple of 111

**Comment by MrPerson** [comment]
It's the same effect though. You can't get a bpm of say 450. That rounds to 300. That's just how it works.

Here's a proof-of-concept of what I mean: https://gist.github.com/MrPerson/3ad1972e60822bdf0478

Put any song in there. Go ahead. When you click "Play Both", a second instrument datum will also play except this one used the "raw" bpm you inputted or imported. Its window will open so you can see this in action. If the two songs were playing at a different rate, you would hear them go out of sync. Except they don't, they stay perfectly in sync.

Can we please close this issue now?

**Comment by optimumtact** [comment]
This isn't a bug
