### ISSUE TITLE
Mind swapping with another wizard can break your ability to recognize other wizards.

### ISSUE THREAD

**Issue by WJohn** [tgstation/tgstation#9601]
What it says on the tin, you lose the little wizard hat marker next to people if you mindswap with another wizard (or are mindswapped by). I think they lose vision of you too because I've been killed by another wizard this way, too, since they can't readily recognize me and we're jumping identities constantly.

**Comment by phil235** [comment]
The wizard hud icon also only appear during wizard game mode. Admin spawned wizard do not get this hud.

**Comment by WJohn** [comment]
This also happened to a gangster who was abducted and operated on. When they were made a survivor (or whatever abductee antags are) they lost their ability to recognize other gangsters, even though the traitor panel still listed them as one.

**Comment by WJohn** [comment]
This is still broken.

I instantly had this happen as soon as I mindswapped with somebody. Became unable to recognize myself or my apprentice as a wizard.

**Comment by Rinoka** [comment]
Trying to error check some of the older issues. 

Haven't gotten the chance to test in-game right now, but I think this might have something to do with the teamcode for wizards. The code is deliberately coded so that it doesn't have a default team (and won't generate one until you summon your wizard minions), but I'm not sure the transfer_to properly saves and returns wizard teams, which activates wizard.dm:159.

>update_wiz_icons_added(M, wiz_team ? TRUE : FALSE) //Don't bother showing the icon if you're solo wizard

I'm thinking it might actually call things out of order, since this is the only snowflake check I can see that would make HUDs weird for wiz but nobody else.

The gangster issue is also no longer relevant since I don't even think we HAVE gangcode anymore, but it probably had something to do with gangsters and can_coexist_with_others.

**Comment by kriskog** [comment]
You can no longer mindswap with other wizards.
