### ISSUE TITLE
Observe randomly breaks

### ISSUE THREAD

**Issue by Miauw62** [tgstation/tgstation#9634]
Metastation, about 7:30 PM Brussels time. 24/5/2015

Observers were unable to spawn. Hitting observe produced a clientless, mindless ghost and removed a player's buttons. VV still showed those as newplayers, they were stuck.
No idea why.

**Comment by WJohn** [comment]
I had this randomly occur to me about two months ago, relogging put me back on the lobby screen. I could only properly get in game by jumping to an area, spawning a human, editing myself in and then ghosting back out. I suppose making an actual ghost would've worked too but eh.

This stopped happening the very next round, and I haven't experienced or heard of it since.

**Comment by RocKeD** [comment]
There must be some sort of special or coincidental conditions that are just right or "lined up" for this to happen. If this happens to anyone in the future I would make notes on what's going on in the round and how you died etc..

**Comment by Dorsisdwarf** [comment]
We've gone a year without this edgiest of cases coming up again.
