### ISSUE TITLE
Editing shuttle docks can cause the shuttle to dock in nullspace

### ISSUE THREAD

**Issue by theOperand** [tgstation/tgstation#9644]
According to Sticky shuttles can dock in nullspace if somebody makes it fly during edits. they should probably just not move at all instead of going to nullspace.

**Comment by Stickymayhem** [comment]
I've seen this happen twice. The reason I believe it was nullspace is because I was on the shuttle one time, got sent to the black screen of nothingness and then the server immediately crashed. Both times it was space turfs being edited, and both times it occurred in a very small time frame around the actual edit. No directional things were messed with and it was the vanilla central command ferry.

**Comment by KorPhaeron** [comment]
@AnturK 

Is this still relevant?

**Comment by AnturK** [comment]
There might be some edge case but straightforward edit will just make it bounce for normal shuttles or force ending for emergency.
