### ISSUE TITLE
Borgs being shot with ion rifles causes weird messages

### ISSUE THREAD

**Issue by bgobandit** [tgstation/tgstation#9716]
What happened:

Kor Phaeron fires the ion rifle (AI Bane)!
THE LAW is hit by an ion bolt in the chest!
_BZZZT_
Warning: Electromagnetic pulse detected.
The station bounced radio overloads.
Cyborg sounds an alarm.
Fortune Ray sounds an alarm.

Context: I was Fortune Ray at roundstart, got turned into a secborg later on in the round. My borg name was THE LAW. No other borgs were near me, this was in space.

**Comment by Xhuis** [comment]
It was likely your MMI.

**Comment by bgobandit** [comment]
I figured, yes, but this isn't supposed to happen, let alone "Cyborg"

**Comment by Incoming5643** [comment]
MMI brainmobs are weird, they remain as a mob in the mmi inside you even after you transfer to the borg proper. Hell you can even give control of the brainmob to someone else and have your own brain yelling at you from the inside.

In a perfect world there'd be a refactor for them, because they inspire flakey checks in a lot of things.

**Comment by optimumtact** [comment]
I'm pretty sure that message is using the wrong replacments for name
