### ISSUE TITLE
Singularity center object interacts oddly with other objects

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#9946]
If the singularity hits a dense object, it doesn't eat it and continue moving like you would expect, it stops at that object until it consumes it(at which point it starts drifting again, as normal)
The singularity also doesn't consume objects it directly Crossed() as in, if the center object drifts over an object, the object won't be consumed if the singularity drifts fast enough away.

**Comment by AlexanderUlanH** [comment]
That's because the singularity's drifting and consumption's from before "everything drifts".  It's still moving one square every and consuming everything it's on every machine tick.  Drifting is just incidental.
The accidental increase in singularity speed's a positive change IMO, and it would be nice if it were rewritten with drifting in mind.

**Comment by Anonus** [comment]
Well, drifting is part of it, but this is stuff it always did(though it mattered a lot less back when it'd still be over the object after moving)
