### ISSUE TITLE
Shuttle tiles don't retain appearence if crowbarred up and replaced

### ISSUE THREAD

**Issue by ChangelingRain** [tgstation/tgstation#9984]
This isn't consistent with tiles on the station; if you crowbar up a tile on the station with a special appearance(like any tile in science) it'll have that appearance still if you replace it.

**Comment by optimumtact** [comment]
there's a couple of other tiles like that, ideally they should all be replaceable

**Comment by Mervill** [comment]
This is because the shuttle uses `/turf/open/floor/mineral/titanium/blue` tiles which drop `/obj/item/stack/tile/mineral/titanium` when destroyed. That stack is actually doing it's job correctly by setting the turf to `shuttlefloor3` (Additionally, `/obj/item/stack/tile/mineral` stacks are bugged when there are exactly two tiles in the stack).

If you take a **plasteel floor tile** `/turf/open/floor/plasteel` and place in on a tile in the shuttle where there was a blue tile previously, you'll get a `/turf/open/floor/plasteel` **that looks blue, instead of an original** `/turf/open/floor/mineral/titanium/blue` tile.

Space Station 13 ... it never changes

**Comment by coiax** [comment]
I think at the time this issue was made, we didn't have titanium. But this is just another in a line of "DAMN FLOOR TILES ARE HARD"

**Comment by Bawhoppen** [comment]
Should have been fixed by #26221

**Comment by Bawhoppen** [comment]
maybe idk actually

**Comment by Razharas** [comment]
We can reopen if its still bad
